### ISSUE TITLE
RTF

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#1]
Looks promising! Any plans to support rtf as a document format?

**Comment by glushchenko** [comment]
In last release was added custom extensions, you can select rtf by default.

**Comment by jeff-h** [comment]
Cool! :) It does now read my RTF files, but isn't parsing them correctly. As an example, one starts with:

```
{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf340
\cocoascreenfonts1{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural
```

**Comment by glushchenko** [comment]
@jeff-h, rtf support will be fixed in next releases. Stay tuned ;)

**Comment by jeff-h** [comment]
Very cool. How feasible do you think it would be to have it load docs with ALL filetypes it knows about (ie `.md` and `.rtf`) and change the preference to "Default filetype" which would be used for all newly created notes?

**Comment by glushchenko** [comment]
Breaking news! Try new build https://github.com/glushchenko/fsnotes/releases/download/0.8/FSNotes.app.zip

:)

**Comment by jeff-h** [comment]
Wow, great! This is getting surprisingly close to daily-usable for me — especially good since nvALT is so broken on 10.13 (which I am running). There are a bunch of niceties from nvALT that I am hoping can make their way into your app over time (eg auto bullet-list creation), but for now I just pointed fsnotes at my nvALT documents folder (with 1,150 RTF notes in it) and it's working just fine. Especially good is that the search is virtually instant!

Thanks for all your work.
