### ISSUE TITLE
Feature Request: Disable Note Previews

### ISSUE THREAD

**Issue by proksch** [glushchenko/fsnotes#10]
I would love to have an option to disable the note preview in the left pane. Having a large number of notes, I personally prefer to only see the file name and the date in the left pane and see the content only when selecting a note.

**Comment by glushchenko** [comment]
Good idea, proksch.

**Comment by williamsmj** [comment]
This doesn't need to be an option. The way nvALT handles it is good IMO: if you select a note, it's displayed. If you unselect a note, the pane is empty.

**Comment by proksch** [comment]
I'm not talking about the content pane, but about the "teaser" of the content that is shown together with the title at the moment.

**Comment by glushchenko** [comment]
Checkout https://github.com/glushchenko/fsnotes/releases/download/0.8/FSNotes.app.zip
