### ISSUE TITLE
horizontal elasticity

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#100]
Version 1.2.3 introduced a regression whereby the main note view (in RTF view, at least) is able to be scrolled left and right. It doesn't actually seem to scroll as such, but shows the elastic "end-of-scroll" effect.

**Comment by glushchenko** [comment]
Hi @jeff-h can you record screen? How to reproduce? Thanks.

**Comment by jeff-h** [comment]
Sorry, not sure how! But I realised it's a simple fix; in interface builder, there's a setting for elasticity on both horizontal and vertical. The app is built with this set to `Automatic Elasticity` for both.

Weirdly when I build the app in Xcode, it's perfect, but the release version from Github behaves as though `Elasticity Allowed` was selected in the horizontal setting. If you want to see what I'm seeing, build it with that chosen, as per my screen shot.

I imagine the fix would be to select `No Elasticity` for horizontal, if you don't mind. Not really worth a PR I think, but apparently under some circumstances, Cocoa decides that the `Automatic Elasticity` setting should in fact be on, when in fact (I think) we never want it to be.

![Elasticity config](https://user-images.githubusercontent.com/841871/35249065-6a5180ae-0035-11e8-90b3-898e9f03da0d.png)
