### ISSUE TITLE
Periods being inserted automatically after words when spacebar is pressed twice despite "Correct Spelling Automatically" being disabled.

### ISSUE THREAD

**Issue by dmattera** [glushchenko/fsnotes#1000]
**Describe the bug**
Periods being inserted automatically after words when spacebar is pressed twice, even with the setting "Edit" > "Spelling and Grammar" > "Correct Spelling Automatically" disabled.

**To Reproduce**
1. Uncheck the setting "Correct Spelling Automatically" under "Edit" > "Spelling and Grammar"
2. type any word and press the spacebar twice.

**Expected behavior**
No automatic spelling/grammar corrections should be applied with this setting disabled

**Actual behavior**
A period is automatically added after the word from step 2 above

**Workaround**
None so far

**Supporting Files**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.6.1 (411)

**Additional context**
N/A

**Comment by glushchenko** [comment]
```
defaults write -globalDomain "NSAutomaticPeriodSubstitutionEnabled" -bool false
```

**Comment by glushchenko** [comment]
Anniversary issue #1000 🥳

**Comment by dmattera** [comment]
> `defaults write -globalDomain "NSAutomaticPeriodSubstitutionEnabled" -bool false`

Yep, this was the issue.

(Can also be changed in the normal macOS Keyboard settings under "Text" > "Add Period with double space".

I just failed to notice it when checking there originally *facepalm*
