### ISSUE TITLE
[Request] Possible to add an option to make it so only CMD+clicking on a URL located in the editor actually opens it?

### ISSUE THREAD

**Issue by dmattera** [glushchenko/fsnotes#1001]
**Describe your feature request**
 With this feature request, left-clicking on the URL would insert the caret into the URL like it would if clicked on non-URL text rather than opening the URL. To open the URL, you would instead do a CMD+click on the URL.

Reasons why this feature would be nice:

- allow for easier modification of the URL. If you want to edit the middle of a URL currently, you have click on either side of the URL text (being careful not to click on the URL itself) and then arrow over to the part you want to edit. 
- avoid accidental clicks on URLS in the editor

**Additional context**
macOS only, I think

**Comment by glushchenko** [comment]
Option + click for cursor positioning, and added option Clickable links.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
