### ISSUE TITLE
Interface button overlap if select Hide/Show sidebar

### ISSUE THREAD

**Issue by KreiDer** [glushchenko/fsnotes#1002]
**Describe the bug**
Interface button overlap if select Hide/Show sidebar

**To Reproduce**
1. Select View -> Hide/Show sidebar
2. See overlap interface buttons

**Expected behavior**
Buttons isn't overlapped 

**Actual behavior**
Buttons is overlapped 

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
<img width="316" alt="image" src="https://user-images.githubusercontent.com/14274525/97291471-0af74580-185b-11eb-953c-cbde42e9a147.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - FSNotes version: 4.7.3

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.4/FSNotes_4.7.4.zip
