### ISSUE TITLE
Tags in in-line code block not ignored

### ISSUE THREAD

**Issue by pdanford** [glushchenko/fsnotes#1003]
**Describe the bug**
Tags appear for #words in inline code blocks when they are with other non-# words in the same block and also indented code blocks.

**To Reproduce**
In edit window, enter:

\`test #t1\`
and
\`\`\`
test #t2
\`\`\`
This also happens for double ticks such as \`\`test #t3\`\`

    And also for indented blocks #t4

**Expected behavior**
Neither t1,t2,t3, or t4 should appear under "# Tags" in sidebar since they are all in code blocks.

**Actual behavior**
t1\`,t3\`\`, and t4 do appear (t2 does not which is as expected and agrees with issue #932) 

**Workaround**
none

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.7.3

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.4/FSNotes_4.7.4.zip

**Comment by pdanford** [comment]
This looks like it fixed it. There is one lingering related problem: code blocks that are done by indenting 4 spaces instead of ``` delimiters still have tags extracted.

Thank you for the fast fix on the others!
