### ISSUE TITLE
New tag design

### ISSUE THREAD

**Issue by educbraga** [glushchenko/fsnotes#1004]
**Describe your feature request**
A new tag design in the text editor and on the sidebar.

Light mode:
![Captura de Tela 2020-11-02 às 18 07 09](https://user-images.githubusercontent.com/21699905/97919914-603dc600-1d37-11eb-8748-43676fc6fcaf.png)

Dark mode:
![Captura de Tela 2020-11-02 às 18 12 32](https://user-images.githubusercontent.com/21699905/97919916-62078980-1d37-11eb-9576-9b720ba3c1f7.png)

**Comment by saf-dmitry** [comment]
Depending on line spacing and line/window width tags in editor view may look screwed:

![Screenshot 2021-08-18 at 15 10 00](https://user-images.githubusercontent.com/30050534/129904838-15074aa1-8abf-4af8-a03a-bbcdf7ad0a4b.png)

**Comment by glushchenko** [comment]
@saf-dmitry macOS 10.13?

**Comment by saf-dmitry** [comment]
Sorry, I forgot to mention: macOS 10.14.6

**Comment by glushchenko** [comment]
Thank you, i will check it later today :)

<img width="410" alt="image" src="https://user-images.githubusercontent.com/1089917/129913546-05d20e49-e590-4c76-ab01-b61d45890f90.png">

Will be disabled in RC

**Comment by glushchenko** [comment]
Feature available on Big Sur +
