### ISSUE TITLE
FSNotes closes when editing the note color

### ISSUE THREAD

**Issue by educbraga** [glushchenko/fsnotes#1005]
**Describe the bug**
FSNotes closes when editing the note color

**To Reproduce**
1. Go to 'FSNotes'
2. Click on 'Preferences'
3. Click on  'Layout'
4. Click on 'Note Color' color
5. Try to change the color on the palette
6. FSNotes will suddenly close.

**Expected behavior**
The possibility to change the note color

**Actual behavior**
FSNotes Closes

**Supporting Files**
![Captura de Tela 2020-11-02 às 20 55 46](https://user-images.githubusercontent.com/21699905/97932365-8f136680-1d4e-11eb-9ba0-a3887053f2e5.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.7.4 (432)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.6/FSNotes_4.7.6.zip

**Comment by educbraga** [comment]
Thank you!
