### ISSUE TITLE
Tags appear for \#words in indented code blocks (not ``` fenced).

### ISSUE THREAD

**Issue by pdanford** [glushchenko/fsnotes#1007]
**Describe the bug**
Tags appear for \#words in indented code blocks (i.e. blocks only indented by 4 spaces - not surrounded by \`\`\` fence).

**To Reproduce**
1. Create note
2. Add indented (not \`\`\` fenced) code block:

        this is an indented code block
        #t1    
        end

**Expected behavior**
\#t1 should not get picked up as a tag - it should be ignored.

**Actual behavior**
Appears as tag.

**Workaround**
Use code fence (\`\`\`)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.7.6

**Additional context**
This is a real problem with code that has #include or #define a lot.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.9.0b444/FSNotes_4.9.0.zip

**Comment by pdanford** [comment]
Fix works well. Thanks!
