### ISSUE TITLE
HTML Does Not Rendered

### ISSUE THREAD

**Issue by m2akhyar** [glushchenko/fsnotes#1008]
**Describe the bug**
HTML tag inside the note does not rendered.

**To Reproduce**
1. Write an HTML tag in the note, eg. `<p>Hello World</p>`.
2. Turn on the preview.

**Expected behavior**
HTML to be rendered.

**Actual behavior**
Does not show anything.

**Workaround**
Haven't found any.

**Supporting Files**
1. Preview OFF
    <img width="935" alt="Screen Shot 2020-11-06 at 04 50 18" src="https://user-images.githubusercontent.com/5679000/98294918-aae76880-1feb-11eb-871b-0ae6ca90c2d5.png">

2. Preview ON
    <img width="935" alt="Screen Shot 2020-11-06 at 04 50 07" src="https://user-images.githubusercontent.com/5679000/98294936-b33fa380-1feb-11eb-8cc1-b68891a0f4c1.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.7.6

**Additional context**
HTML rendering is in markdown specs, so I expect it would work. Please kindly advice if I do it wrongly. Thanks in advance!

**Comment by glushchenko** [comment]
Fixed, thanks!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/4.8.1

**Comment by m2akhyar** [comment]
Awesome, thank you so much! I'm closing it now, keep it up!
