### ISSUE TITLE
URL scheme link does not select the linked note

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#1009]
**Describe the bug**
Activating an URL scheme link like `fsnotes://find?id=5` when the app is _not_ active (not launched) has following effect: The app does start but does _not_ jump to the linked note.

**To Reproduce**
1. Open the app, select a note and select "Copy URL" in the context menu.
2. Close the app.
3. Open Terminal app and issue `open <pasted URL>`.
3. See FSNotes started but not jumping to the requested note.

**Expected behavior**
The app should start and follow the requested URL.

**Actual behavior**
The app does start but is not following the requested URL.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.7.6

**Comment by glushchenko** [comment]
Thanks, fixed

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/4.8.1
