### ISSUE TITLE
Maximise window

### ISSUE THREAD

**Issue by 1900forever** [glushchenko/fsnotes#1010]
**Describe the bug**
Double click the window bar cannot maximize the window, which it should.

**To Reproduce**
1. Direct mouse pointer to the window bar
2. Double click the window bar
3. Nothing happens

**Expected behavior**
this operation should maximize the activated window size

**Actual behavior**
Nothing happens

**Workaround**
Tried close and reopen FSNotes, nothing has changed
**Supporting Files**

![ezgif-5-ff1d67c95b24](https://user-images.githubusercontent.com/3516677/99192213-b6e7ce80-273f-11eb-95eb-894975311a76.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.0.1
 - FSNotes version: 4.8.1

**Comment by glushchenko** [comment]
Bug? Holy shit, even not all Apple apps has this behaviour.

**Comment by 1900forever** [comment]
> Bug? Holy shit, even not all Apple apps has this behaviour 🤬

Oops, I even didn't notice that. It should be a "Feature Request" then

**Comment by glushchenko** [comment]
Implemented

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/4.8.3_build438
