### ISSUE TITLE
textbundle loses data when external editor is used

### ISSUE THREAD

**Issue by pdanford** [glushchenko/fsnotes#1011]
**Describe the bug**
textbundle loses data when external editor is used and later edited in open instance of FSNotes 

**To Reproduce**
1. Create new file in textbundle format in FSNotes and add some text
2. Open note in external editor with control-cmd-E (and do not exit FSNotes)
3. In external editor, add some more text and save
4. Switch back to FSNotes. Text is not updated in FSNotes (for textbundle notes).
5. Add some more text to the note in FSNotes.
6. Exit FSNotes and relaunch

**Expected behavior**
Note should have updated in open instance of FSNotes when text is added and saved in external editor.

**Actual behavior**
All text added to note in external editor is lost when non-updated version of note is edited again  in open FSNotes instance.

**Workaround**
Exit and relaunch FSNotes **before** editing textbundle note again in FSNotes.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.8.2

**Comment by glushchenko** [comment]
Thanks, Peter, i will check it soon.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.8.4/FSNotes_4.8.4.zip

**Comment by pdanford** [comment]
Looks to be fixed but note that new files created by FSNotes and then immediately edited in an external editor need to exist about 15 to 20 seconds before the macOS file system will start sending change notifications to FSNotes. After that initial time for new files, works well.

Thanks for the fast fix!
pdanford
