### ISSUE TITLE
All notes disappeared after upgrading Big Sur

### ISSUE THREAD

**Issue by hosupc** [glushchenko/fsnotes#1015]
**Describe the bug**
I opened FSNotes first time after upgrading Mac OS to Big Sur. All notes are gone. I checked Preferences, and Storage location is set to `/Users/myname/Library/Containers/co.fluder.FSNotes/Data/Documents`. But it's empty. Trash folder under there also empty. I tried open Time Machine backup from Storage Location, and I don't see any files there.

**To Reproduce**
Upgrade Mac OS to latest version. And open FSNotes.

**Expected behavior**
All my existing notes should be there.

**Actual behavior**
All my notes are gone.

**Workaround**

**Supporting Files**

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.0.1
 - FSNotes version: 4.8.3

**Additional context**

**Comment by glushchenko** [comment]
Where did you keep your notes?

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/issues/1014

**Comment by hosupc** [comment]
Thank you for #1014 reference.

I'm using a Mac App Store version, not a HomeBrew version. So I don't know why it changed the Storage location. I reinstalled the app from App Store, now I can see every notes.

Thank you again.
