### ISSUE TITLE
Can't download version from homebrew

### ISSUE THREAD

**Issue by juanfcocontreras** [glushchenko/fsnotes#1017]
**Describe the bug**
I can't download latest version (4.8.4) from homebrew.

**To Reproduce**
1. brew update

**Expected behavior**
Update fsnotes

**Actual behavior**
`Error: fsnotes: Download failed on Cask 'fsnotes' with message: Download failed: https://github.com/glushchenko/fsnotes/releases/download/4.8.4/FSNotes_4.8.4.zip`

**Workaround**
Not known

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.8.1

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.8.4_build442/FSNotes_4.8.4.zip

**Comment by juanfcocontreras** [comment]
I filled in the bug so you could update the homebrew recipe. I had already downloaded the update directly from releases.

Thanks!

**Comment by glushchenko** [comment]
Personally i do not support brew, i didn't configure it.

**Comment by juanfcocontreras** [comment]
Ok, sorry. Then I close the issue.

**Comment by glushchenko** [comment]
No problem @juanfcocontreras
