### ISSUE TITLE
Release tag numbering

### ISSUE THREAD

**Issue by ulab** [glushchenko/fsnotes#1018]
**Describe your feature request**
Please try and follow a proper release / tag numbering scheme :). 

Having the latest version tagged with a number like 4.9.0b444 while a previous "pre-release 4.9.0 beta 1" was tagged 4.9.0 and similar makes it really difficult if not impossible to keep the brew cask versions up to date.

**Comment by glushchenko** [comment]
Pre release was flagged after release, sometimes shit happens. But I try to stick to certain rules, this is an exceptional situation. Thank you for feedback :)

**Comment by ulab** [comment]
I just noticed it over the last few releases which irritated me a lot, so I thought I'd give you a short heads up ;-)

**Comment by ulab** [comment]
I'm sorry, but I have to come back to this as a reminder :)

https://github.com/glushchenko/fsnotes/releases/tag/5.0.3

This is tagged as 5.0.3, but the file has 5.0.2 and the release information only includes a note on 5.0.2 too?

This makes it really difficult to update the brew cask and I guess I have to skip this version to do so. In fact brew's default versioning of using a variable doesn't work at all in this case.

If you follow a common schema it's just a single `brew bump-cask-pr --version` command to upgrade, but for the v5 release I had to edit the ruby file, change the version, the URLs, download the archive, do a sha256 checksum and figure out a fix for the livecheck to work properly so that the pull request checks don't fail.

**Comment by gingerbeardman** [comment]
I've edited the release to 5.0.2 thanks for spotting the error.
