### ISSUE TITLE
Inline markup is interpreted inside math environments

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#1019]
**Describe the bug**
Inline markup is interpreted inside math environments in both _editing_ and _preview_ mode:
![Screenshot 2020-11-25 at 13 51 35](https://user-images.githubusercontent.com/30050534/100230086-8533ec00-2f25-11eb-953b-babe70f2b7c0.png)
![Screenshot 2020-11-25 at 13 39 36](https://user-images.githubusercontent.com/30050534/100229205-2a4dc500-2f24-11eb-8074-83bdabd5a39d.png)

**Expected behavior**
Inline markups should be completely ignored inside inline and displayed math.

**Actual behavior**
Inline markups is interpreted inside inline and displayed math.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.9.1

**Comment by saf-dmitry** [comment]
From looking at the code I can see that one need a proper math extension for the Markdown parser, which basically would detect math in Markdown  source (using proper delimiter syntax for inline and display math blocks) and pass it through untouched to MathJax (probably adapting the delimiters to MathJax's needs). This can potentially solve #950.

**Comment by glushchenko** [comment]
Fixed in 4.9.6 https://github.com/glushchenko/fsnotes/releases/download/4.9.6/FSNotes.zip
