### ISSUE TITLE
Light/Dark mode switch doesn't update note pane

### ISSUE THREAD

**Issue by tjmcewan** [glushchenko/fsnotes#1020]
**Describe the bug**
I have my system "Appearance" set to Auto.  When the mode switches, the search box & note list adapts, but the note pane does not.

**To Reproduce**
1. open sys prefs > general
2. switch Appearance to Light
3. open fsnotes
4. switch Appearance to Dark, observe that the note font does not adapt so the note will illegible
5. close & reopen fsnotes, note will be readable
6. switch Appearance to Light, observe that the entire note pane stays in Dark mode

**Expected behavior**
It should adapt the note pane to the system Appearance.

**Workaround**
Need to restart the app.

**Supporting Files**
Dark mode with note font still in Light mode:
<img width="628" alt="dark_mode_bug" src="https://user-images.githubusercontent.com/107308/100352161-b0f7c480-3040-11eb-9969-48274746d8ee.png">

Light mode with note pane still in Dark mode:
<img width="672" alt="light_mode_bug" src="https://user-images.githubusercontent.com/107308/100352192-bce38680-3040-11eb-9f2d-d301b639fc89.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.0.1
 - FSNotes version: 4.9.1

Thank you! :)

**Comment by tjmcewan** [comment]
Then again, I've just installed on a brand new Mac (m1) and it's adapting just fine...

**Comment by glushchenko** [comment]
How to reproduce this? Of course, everything works well for me. Can you record a video?

**Comment by tjmcewan** [comment]
Sorry I don't know how to reproduce it other than the steps I gave.  My system is obviously in some state.  I've been searching for the prefs file to trash it and start over, but I can't find it?

**Comment by tjmcewan** [comment]
Ok, I found the preferences in `~/Library/Containers/co.fluder.FSNotes` and trashed them.  It's working again now.

**Comment by zagrue** [comment]
This is no again happening to me, just installed on m3 Mac Sonoma.
