### ISSUE TITLE
Pin/Unpin notes not working

### ISSUE THREAD

**Issue by henyop** [glushchenko/fsnotes#1022]
**Describe the bug**
Pinning a note works...until the app is closed an reopened then the note is no longer pinned.

**To Reproduce**
1. Select note. Choose Pin.
2. Close app.
3. Open app.
4. Note is no longer pinned.

**Expected behavior**
Pinned notes should remained pinned at all times. 
**Actual behavior**
A clear and concise description of what actually happens.
Pinned notes no longer pinned after restarting app.

**Workaround**
N/a

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.14.6
 - FSNotes version: 4.9.1 (445)

**Additional context**

**Comment by glushchenko** [comment]
How to reproduce this? Of course, everything works well for me. Can you record a video?

**Comment by henyop** [comment]
![Untitled](https://user-images.githubusercontent.com/75118533/100548907-acf9bb80-3267-11eb-99d9-74a23c278bca.gif)

**Comment by glushchenko** [comment]
This version from AppStore or GitHub?

**Comment by glushchenko** [comment]
Please try last dev build
