### ISSUE TITLE
Images not appearing

### ISSUE THREAD

**Issue by henyop** [glushchenko/fsnotes#1023]
**Describe the bug**
After adding an image to a note, the image is viewable. But when the app is closed and restarted, the image no longer is there.
**To Reproduce**
1. Add image into note
2. Close app.
3. Reopen app.
4. Image is no longer there. Image file is in the i folder, but not viewable in the note itself.

**Expected behavior**
Image to be displayed

**Actual behavior**
Image not displayed

**Workaround**
n/a
**Supporting Files**
n/a

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 4.9.1 (445)

**Additional context**
Live Image Preview setting is checked on.

**Comment by glushchenko** [comment]
How to reproduce this? Of course, everything works well for me. Can you record a video?

**Comment by henyop** [comment]
Added video :)
![Untitled](https://user-images.githubusercontent.com/75118533/100549193-5c835d80-3269-11eb-8d64-d7711cc55450.gif)

**Comment by henyop** [comment]
Hi, Ive just realised I've been using the wrong the file format - was using .txt instead of .md. 

Images working fine in markdown mode. 

Sorry about this, my fault!
