### ISSUE TITLE
image in md file not being imported

### ISSUE THREAD

**Issue by kerhbal** [glushchenko/fsnotes#1024]
**Describe the bug**
import any md file with local image, and the image is not imported

**To Reproduce**
1. create some example
```md
# test
![](media/2020-11-28-18-32-25.png)
```
and with some file structure like this:
<img width="376" alt="ForkLift-media--2020-11-28 at 18 41 51" src="https://user-images.githubusercontent.com/11629684/100528298-65145f00-31a9-11eb-9c7a-a05a6d40286a.png">

2. import to fsnote
3. check both edit and view content

![FSNotes-FSNotes--2020-11-28 at 18 44 20](https://user-images.githubusercontent.com/11629684/100528345-da802f80-31a9-11eb-99cd-4698e7bad91b.gif)

**Expected behavior**
the image in md file should be imported together with note it self

**Actual behavior**
image is missing, and the path of the image remains as before importing, this thing simply didn't work

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.9.1

hope someone can take a look, thanks!

**Comment by glushchenko** [comment]
You should select media folder too. Not bug.
