### ISSUE TITLE
New note not sorted automatically by title after renaming

### ISSUE THREAD

**Issue by wyaqoob** [glushchenko/fsnotes#1025]
**Describe the bug**
When I create a new note and immediately rename it, it is not automatically sorted, despite view > sort by > title being selected in the menu; I have to click 'title' in the menu twice to sort it. When I rename an **existing** note, however, it is automatically sorted, and when I restart FSNotes, the newly-created note is sorted.

**To Reproduce**
1. Create a new note
2. Immediately rename it
3. See that the note is not sorted by its new title in the notes list.

**Expected behavior**
A newly-created note and renamed should be sorted in the notes list according to its title after a short delay.

**Actual behavior**
The newly-created note is left in place rather than being reordered.

**Workaround**
One can click 'view > sort by > title' in the menu twice, or restart FSNotes.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.0.1
 - FSNotes version: 4.9.1

**Additional context**

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.9.7/FSNotes_4.9.7.zip
