### ISSUE TITLE
Universal link or deep linking 

### ISSUE THREAD

**Issue by oreglio** [glushchenko/fsnotes#1027]
I've been searching for an app that was a mix of the Bear app cloud sync across devices and NvAlt style and FS Notes fits perfectly. Great job.

Because it's so well made for markdown support & sync, I'm wondering if it would be possible to add a new feature to link to notes from an other iOS app. I know a feature called Universal link or deep linking in iOS but never used it. Maybe it's already implemented but I haven't found a documentation on it. Having a link between the tasks organized in an app and the notes in Fs Notes would be a great workflow.

**Comment by gingerbeardman** [comment]
It already exists, you can read about it here: 
https://github.com/glushchenko/fsnotes/wiki/Finding-&-creating-documents-via-URLs

I use it to open notes from Alfred: 
https://github.com/glushchenko/fsnotes/wiki/Alfred-Workflow

**Comment by oreglio** [comment]
Awesome I missed that part. It's well explained and I have everything I need.

Thank you !
