### ISSUE TITLE
Can not input Chinese normally after one space followed the '#' symbol during typing title.

### ISSUE THREAD

**Issue by lhrkkk** [glushchenko/fsnotes#1028]
**Describe the bug**
Can not input Chinese normally after one space followed the '#' symbol during typing title.

It works abnormally when you input Chinese followed by one space after # to input a title
<img width="319" alt="image" src="https://user-images.githubusercontent.com/934669/101239936-a2876800-3726-11eb-9ac0-88a9ace33d58.png">

It will work normally if you input Chinese followed by two space.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/934669/101239946-b337de00-3726-11eb-9d4b-6a1f12cb6826.png">

**To Reproduce**
1. Switch to any Chinese input method
2. Input #
3. Input one space 
4. Input words using Chinese input method. The first letter will be left in English. It's a problem. 
5. If you input two space followed by # , the Chinese input will work normally.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version:  4.9.1 (446)

**Comment by HenryQW** [comment]
https://user-images.githubusercontent.com/5896343/103040936-d8bd4800-456c-11eb-8447-b72dec052ccc.mov


Recorded a video for the bug.

**Comment by glushchenko** [comment]
@HenryQW @lhrkkk please try https://github.com/glushchenko/fsnotes/releases/tag/4.9.7b2 seems i fixed it.

**Comment by HenryQW** [comment]
Thank you @glushchenko. The problem is solved now.

Do you currently have space for iOS testflight? I'd like to test it out too. I sent out an email months ago to support@fsnot.es and did not hear back.

**Comment by glushchenko** [comment]
@HenryQW no.
