### ISSUE TITLE
Note names and note text get mixed up

### ISSUE THREAD

**Issue by sibob** [glushchenko/fsnotes#1029]
**Describe the bug**
I have found this happening every time I use search, but it may happen in other circumstances: 

After editing a note, or deleting a note, the Note names and their content are then mismatched. 

e.g. 'Note 1' as listed in the note list will show 'Note 2's text. Closing the app and restarting solves it temporarily. 

I have deleted important notes not realising this bug, I hope this is a common issue as I can't use FSNotes for now as a result

**To Reproduce**
1. Type a term into search box
2. Edit or delete a note from the results
3. View other notes: Now, the note text does not match the name in the note list. 

**Expected behavior**
I expect to click on a note in the note list, and see the actual text for that note, not the text of another note

**Actual behavior**
The note's text does not match the name in the note list. 

**Workaround**
Restart Fsnotes

**Supporting Files**

**Desktop (please complete the following information):**
 - OS: 11.0.1
 - FSNotes version: 4.9.1 (445)

**Additional context**

This is with notes sorted by modification date, my notes are stored in icloud, and I have 950-odd notes. I can't think of any other applicable information.

**Comment by glushchenko** [comment]
This is really bad bug report. I don't understand anything here.

**Comment by sibob** [comment]
I’ll try again:

Clicking on a note (in the ‘note list’ column) displays the text of a different note (in the editor column). 

Example:
- ’NOTE A’ is selected in the note list column.
- Yet, the note editor is displaying ’NOTE B’s text.

This is not the behaviour on startup. It happens after a while, always after using search and editing a bunch of notes. I wish I could tell you the exact method to recreate this because it is infuriating. The only way around it is restarting. 

The only information I thought might be relevant is I'm syncing notes with an icloud '1Writer' folder (the app I access my notes with on iOS).

**Comment by gingerbeardman** [comment]
please share a video and/or a set of notes that can easly repro the issue.

**Comment by sibob** [comment]
As before, the below is the way I can reproduce it, although there may be other ways:

- I use the search box, to narrow down notes (always happens in this context, but this step may not matter, I don't know)
- I edit/add/delete/work on various notes, basically just normal useage of FSNotes.
- At some point I notice the notes are mismatched.

I can’t describe it any clearer than that I'm afraid. I can't find the exact action which triggers this.
I’ve attached screenshots which show clear mismatches between the notes list column and the text editor. 
<img width="1440" alt="Screenshot 2020-12-13 at 15 07 36" src="https://user-images.githubusercontent.com/23299125/102016262-e9451580-3d57-11eb-9401-1beb2b36417b.png">
<img width="1440" alt="Screenshot 2020-12-13 at 15 05 51" src="https://user-images.githubusercontent.com/23299125/102016267-eea26000-3d57-11eb-8d1d-a0aeb05e0f98.png">
<img width="1256" alt="Screenshot 2020-12-13 at 15 04 03" src="https://user-images.githubusercontent.com/23299125/102016276-f6620480-3d57-11eb-9809-31f795e07c60.png">

**Comment by gingerbeardman** [comment]
Please try the latest release: https://github.com/glushchenko/fsnotes/releases

**Comment by glushchenko** [comment]
I cannot reproduce it, but some refactoring implemented. May be it will be helpful, may be not.
