### ISSUE TITLE
Build Universal macOS binary version 

### ISSUE THREAD

**Issue by akhenakh** [glushchenko/fsnotes#1031]
Could you ship builds with universal binary to support native m1?

Thanks

**Comment by glushchenko** [comment]
Hi, @akhenakh 

Do you have Apple Silicon?

Please try this https://github.com/glushchenko/fsnotes/releases/download/4.9.3/FSNotes_4.9.3.zip

**Comment by akhenakh** [comment]
Working well and confirmed running in Silicon 
<img width="924" alt="Screen Shot 2020-12-10 at 12 25 11" src="https://user-images.githubusercontent.com/218430/101807133-c1994780-3ae2-11eb-9f66-2e9420202f89.png">

**Comment by akhenakh** [comment]
After several days, works perfectly, closing the issue.
