### ISSUE TITLE
iOS app quits upon launch

### ISSUE THREAD

**Issue by snorky22** [glushchenko/fsnotes#1033]
**Describe the bug**
iOS app quits upon launch on iPhone, with iOS 14.2

**To Reproduce**
1. open iOS app
2. it quits immediately

**Expected behavior**
I would like to use the iOS app as I enjoy your mac app!

**Actual behavior**
A clear and concise description of what actually happens.

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: iOS
 - OS version: 14.2
 - FSNotes version: 4.4.1

**Additional context**

**Comment by glushchenko** [comment]
iCloud Drive is enabled for app?

**Comment by snorky22** [comment]
no, I do not use Icloud drive

**Comment by snorky22** [comment]
anyway I cannot enable icloud drive in the app because I do not have the opportunity to use the app.

**Comment by glushchenko** [comment]
FSNotes works only with iCloud Drive:

Settings - Apple ID - iCloud - FSNotes On

-- 
Yours faithfully,
Oleksandr Hlushchenko

> 16 груд. 2020 р. о 22:05 snorky22 <notifications@github.com> пише:
> 
> ﻿
> anyway I cannot enable icloud drive in the app because I do not have the opportunity to use the app.

**Comment by snorky22** [comment]
OK, thanks
