### ISSUE TITLE
Last line of note disappears when inserting next line

### ISSUE THREAD

**Issue by clayreimann** [glushchenko/fsnotes#1034]
**Describe the bug**
Attempting to add another item at the end of this todo list causes the current last line to be removed

**To Reproduce**
1. Open this note
2. Put your cursor at the end of the second to do item
3. Press enter

**Expected behavior**
A new to do item is added

**Actual behavior**
The last (second) to do item is removed

**Workaround**
Insert a new line somewhere in the last line and then delete the contents after your newly inserted newline.

**Supporting Files**
[Note file](https://www.dropbox.com/s/jd5g2isrplibfpl/To%20Do.md?dl=0)
[Clip of issue](https://www.dropbox.com/s/o0norhn3rh6lp93/Screen%20Recording%202020-12-17%20at%2011.27.48%20AM.mov?dl=0)

**Desktop**
 - OS: macOS
 - OS version: 10.15.7 (19H15)
 - FSNotes version: Version 4.9.4 (453

**Additional context**

**Comment by glushchenko** [comment]
Can not reproduce.

**Comment by glushchenko** [comment]
Seems it fixed in FSNotes 5
