### ISSUE TITLE
FSNotes provides a bad UX when searching words with diacritics

### ISSUE THREAD

**Issue by fturcheti** [glushchenko/fsnotes#1035]
**Describe the bug**

FSNotes provides a bad experience for searching words with diacritics, such as "reunião" or "ação".

**To Reproduce**

1. Create a note with the title "reunião"
2. In the search bar, type "reuniao"
3. The list of filtered notes is empty

**Expected behavior**

It's a common pattern to "normalize" the terms with diacritics in searches, so that "reuniao" would match "reunião", or "acao" would match "ação".

**Actual behavior / Workaround**

As in FSNotes the terms are not "normalized" for the diacritics usage, to match the notes with "ação" we have to type exactly "ação", which is more time consuming to type than simply "acao".

**Desktop (please complete the following information):**

 - OS: macOS and iOS
 - OS version: macOS 10.15.7 and iOS 14.1
 - FSNotes version: 4.9.4 (macOS) and 4.4.1 (iOS)

**Comment by glushchenko** [comment]
Fixed, thanks.

**Comment by glushchenko** [comment]
Fixed in 4.9.6 https://github.com/glushchenko/fsnotes/releases/download/4.9.6/FSNotes.zip

**Comment by fturcheti** [comment]
👍
