### ISSUE TITLE
Double [[ ]] in code-blocks are replaced by `fsnotes://find`

### ISSUE THREAD

**Issue by verginer** [glushchenko/fsnotes#1036]
**Describe the bug**
Using `[[ ]]` in code blocks is interpreted in the preview as wiki link. In codeblocks everything should be verbatim.

**To Reproduce**

1. paste 

```
df[[val1, val2]]
```

will render as:

```
df['val1', 'val2'](fsnotes://find?id='val1',%20'val2')
```

**Expected behavior**

the link should not be expanded

**Actual behavior**

the link is expanded

**Workaround**
None

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS and iOS
 - OS version: macOS 11.1, iOS 14.1
 - FSNotes version: Version 4.9.4 (453)

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.9.7/FSNotes_4.9.7.zip

**Comment by verginer** [comment]
Nice! This solves it :)


```python
df[[val1, val2]]
```

now renders as exactly that.

Thanks.
