### ISSUE TITLE
In-system and in-program folder creation differs radically

### ISSUE THREAD

**Issue by hpaves** [glushchenko/fsnotes#1037]
**Describe the bug**
Sidebar folders act differently based on whether they are created in-system, or in-program.

Scenario: I like FSnotes and want to import my notes to FSnotes. I paste my notes folder into FSnotes storage directory, and it shows up as a folder on the sidebar. Sweet! Looks like FSnotes follows the Windows convention of calling directories folders. I spend an hour sorting my notes into different folders, creating the new folders in FSnotes. Once I've sorted all my notes into different folders, I want to delete the now-empty import folder. FSnotes warns that it will delete the folder and its contents, an action that cannot be undone... while in-program showing that the folder is empty. I agree, and all my notes, along with the newly in-program created folders vanish.

**To Reproduce**
1. Navigate to FSnotes storage dir
2. Create new folder, i.e. mkdir import
3. Create some files in it, i.e. touch import/{1..12}.md
4. Verify existence of folder and files in FSnotes
5. Create new folders in FSnotes, i.e. "new1" and "new2" by right clicking the sidebar
6. Move half of created files into "new1" and half to "new2"
7. Verify in FSnotes that the "import" folder is empty
8. Delete the "import" folder

**Expected behavior**
9. Folder "import" vanishes
10. Folders "new1" and "new2" and their content stay intact
11. Directories "new1" and "new2" can be seen when exploring FSnotes storage directory

**Actual behavior**
9. Folders "new1" and "new2" also vanish along with their contents

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.9.4 (453)

**Additional context**
During my attempts to reproduce the error, one time when I deleted the "import", "new1" and its contents vanished, but "new2" stayed intact with its contents, and it ended up as a subdirectory under "Welcome". I cannot reproduce this other behavior, but I'm seeing pretty random directory nestings, so, it could be related to where I right click when creating a new folder.

**Comment by glushchenko** [comment]
> Create new folders in FSnotes, i.e. "new1" and "new2" by right clicking the sidebar

Key word is right clicking the sidebar. If you are click on Root dir, then folder will be created here in root. If subfolder was clicked, then folder will be created here in subfolder.

Be careful where you create subfolders.
