### ISSUE TITLE
Trending :)

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#104]
Congratulations! FSNotes made it onto Github's trending list for Swift :)

https://github.com/trending?l=swift

The stars are off the charts... http://www.timqian.com/star-history/#glushchenko/fsnotes

**Comment by glushchenko** [comment]
You can support and votes here:

https://www.producthunt.com/posts/fsnotes

https://news.ycombinator.com/item?id=16206939

https://www.reddit.com/r/macapps/comments/7s7kyz/fsnotes_modern_file_system_notes_manager/?st=JCR8TY8Q&sh=5271c560

🍾🎉
