### ISSUE TITLE
Feature request - graph view and folders

### ISSUE THREAD

**Issue by anupj** [glushchenko/fsnotes#1041]
Hello @glushchenko ,

I’m a big fan of fsnotes and use it to manage information overload. I do have two specific feature requests as I use the Zettelkasten method of notekeeping. 
Are you planning to support folders/sub-folders and also it would be great to have a visual graph view?

Kind regards,
A

**Comment by gingerbeardman** [comment]
1. Subfolders see #188
2. What is graph view?

**Comment by anupj** [comment]
@gingerbeardman this is a good example of graph view https://publish.obsidian.md/help/Plugins/Graph+view

**Comment by glushchenko** [comment]
Graph view not planned, subfolders implemented.
