### ISSUE TITLE
Feature request - markdown file sync/editing on iOS (dropbox/drive/git repo)

### ISSUE THREAD

**Issue by altosaar** [glushchenko/fsnotes#1042]
Using VS Code to edit markdown notes on windows/mac makes it difficult to use FS Notes on iOS devices to sync. iCloud is not an option because of markdown notes being edited on windows that need to by synced. 

Would be great to sync with a git repo or dropbox. Thank you! FS Notes is beautiful.

**Comment by taqyon** [comment]
definitely need github support

**Comment by gingerbeardman** [comment]
Git support is already in the app.

Do you mean that you want controls to push/pull?

Does it at least work to use external git tools to work with the FSNotes local git repo?

**Comment by taqyon** [comment]
> Git repo support is already in the app.
> 
> Do you mean that you want controls to push/pull/commit, etc?
> 
> Does it at least work to use external git tools to work with the FSNotes local git repo?

f*ck me im dumb! I can just stuff everything locally into folders and then push it using the github app

sry!

**Comment by ashutoshsaboo** [comment]
Hey @gingerbeardman, would be great to have native git push support just like GitJournal supports - https://gitjournal.io/ . GitJournal is pretty good for mobile, however atleast to my knowledge i don't know of any native mac notes app yet to have similar support yet. GitJournal is working on a Desktop app as well which will have that support, but I think FSNotes will still have far more superior UX/features in comparison if it can integrate github push/backup support natively. 

There are multiple scripts available on github to setup such a backup via cron scripts etc, however yet a native support would only be far more UX friendly (especially for the users who are not very tech-heavy/power users). Another added advantage of this can be -- Potentially with Github sync, there can be a toggle to disable iCloud sync if users desire for that. This would make the backups more interoperable, and users who have other android/non iOS devices can use other supporting apps to edit existing notes on those devices as well. Intuitively, one would think an interoperable sync feature to be indeed a requirement for something as personal as notes, thoughts?

Would you be willing to consider this on FSNotes' near roadmap? @gingerbeardman @glushchenko

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
