### ISSUE TITLE
FR: Align bullet list indentation

### ISSUE THREAD

**Issue by haircut** [glushchenko/fsnotes#1044]
**Describe your feature request**
In bullet lists, text that overflows the line length configured in _Preferences > Line width_ and wraps to the next line is aligned flush with the left margin instead of aligning with the first line of the bullet item.

![hanging-indent](https://user-images.githubusercontent.com/3910/103782157-1b6b2f80-5005-11eb-8b67-912d0718ec03.png)

I've highlighted the problem areas here:

![hanging-indent-highlighted](https://user-images.githubusercontent.com/3910/103782190-24f49780-5005-11eb-97ea-65e643a42459.png)

This breaks the visual flow and can make it difficult for me to differentiate list items. Especially in longer lists, the margin-aligned second lines appear to be new list items rather than continuations of the current item. As illustrated in the examples, it is even more "jarring" in todo lists.

I would prefer an option to align n+1 lines of a list item with the first line of that item, like so:

![indedentation-aligned](https://user-images.githubusercontent.com/3910/103782299-4786b080-5005-11eb-8e46-40ef6a3ab593.png)

**Additional context**
This issue is most problematic on macOS as the line width is longer.

I realize that this is a very picky and personal request, and it may be difficult to implement. It is a "nice to have" feature :)

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1
