### ISSUE TITLE
If I move/delete folders, it should detect it and remove the 'projects'

### ISSUE THREAD

**Issue by nikitavoloboev** [glushchenko/fsnotes#1047]
**Describe your feature request**

I setup FSNotes by moving my big folder of markdown files with .git found [here](https://github.com/nikitavoloboev/knowledge) to iCloudDrive/FSNotes.

FSNotes iOS started syncing but stopped and got stuck presumingly due to .git being in the folder and iCloud dying.

So I removed the folder (knowledge) from the FSNotes folder. And opened the app again on iOS. The files/folders that synced are still there.

![IMG_0398](https://user-images.githubusercontent.com/6391776/104638506-8a502480-56a6-11eb-8942-add42668ba55.PNG)

The projects (folders) are still there too:

![IMG_0399](https://user-images.githubusercontent.com/6391776/104638527-92a85f80-56a6-11eb-860c-80d9ca3bc706.PNG)

Even though they in theory should not be as there is no folder in FSNotes any more:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/6391776/104638573-a18f1200-56a6-11eb-8740-dc923d371c5a.png">

Perhaps its failing again as iCloud has issues. But my other solution is to go through the list of projects and delete each one, one at a time?

I removed .git from my folder of notes and wanted to move it in FSNotes again. Hoping that all notes get synced this time and everything works smoothly.

Thanks for any help.

**Additional context**
Add any other related information here. macOS or iOS?

macOS & iOS

**Comment by nikitavoloboev** [comment]
I decided to not wait for FSNotes to wipe the stale data. And moved `knowledge` folder of markdown files to FSNotes iCLoudDrive folder. This time without .git

What I saw:

<img width="156" alt="image" src="https://user-images.githubusercontent.com/6391776/104639236-7953e300-56a7-11eb-8777-879405dce492.png">

**Comment by nikitavoloboev** [comment]
It would be nice if in the Projects screen on iOS or macOS you could mass select `Projects` to delete. Right now you are forced to delete each project item by item which takes a very long time.

**Comment by glushchenko** [comment]
.git sync may kill iCloud Drive completely. I am experienced it, only disable/enable iCloud Drive can help.

**Comment by glushchenko** [comment]
.cache folders disappears after app restart (workaround)
