### ISSUE TITLE
macOS: it's difficult/impossible to select text inside links because they are clickable

### ISSUE THREAD

**Issue by nikitavoloboev** [glushchenko/fsnotes#1048]
**Describe your feature request**

Coming to FSNotes from Sublime Text, I found an issue to me where selecting hyperlinked text is hard because its clickable as in example below:

![2021-01-14 20 26 39](https://user-images.githubusercontent.com/6391776/104638818-efa41580-56a6-11eb-88c9-02bad676806d.jpg)

I'd like to perhaps have a setting where links aren't treated as hyperlinks and are treated as text (just syntax highlighted) as in example below (in sublime text):

<img width="830" alt="image" src="https://user-images.githubusercontent.com/6391776/104638991-2b3edf80-56a7-11eb-897b-43d3b49b3146.png">

Thanks. 

**Additional context**

macOS

**Comment by relikd** [comment]
Same goes for email addresses.

**Comment by glushchenko** [comment]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/1089917/192106251-a636d5b4-ed54-48d3-9dba-62cead85c986.png">

1) Clickable links option added
2) You can press shift on click, then cursor will be positioned inline link

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
