### ISSUE TITLE
Add optional Dark icon on iOS

### ISSUE THREAD

**Issue by nikitavoloboev** [glushchenko/fsnotes#1049]
**Describe your feature request**

I'd love if FSnotes iOS app had an optional dark icon. Basically same icon but with dark background. My iOS screen where FSnotes is:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/6391776/104641136-ad300800-56a9-11eb-818f-5f9ae3f3be5b.png">

I can PR an icon myself although adding an interface for selecting the icon maybe hard as im not familiar with the code base.

**Additional context**

iOS

**Comment by glushchenko** [comment]
Please attach dark icon, i will try to add preference.
