### ISSUE TITLE
App crashes if you add the same storage path twice

### ISSUE THREAD

**Issue by aleks** [glushchenko/fsnotes#105]
This happens if you add the same storage folder in "Preferences > General > Add/Change" twice.

The app will crash, but start up fine afterwards. I added it accidentally twice, but this could happen to other people too, so this bug report might help. :)

**Comment by glushchenko** [comment]
Fixed already but not approved in MAS :(

**Comment by aleks** [comment]
Ah, no problem! :)

I noticed, that it's impossible to remove the "general" storage path to replace it with my own. Is this fixed too?

**Comment by glushchenko** [comment]
You can change default storage, select and change.
