### ISSUE TITLE
[iOS] Wiki Link search still use the "first line as title" even though it is disabled in view settings

### ISSUE THREAD

**Issue by ybbond** [glushchenko/fsnotes#1050]
**Describe the bug**
In View Settings, there is "Use first line as title" option that if disabled, not list will display file name instead of first line.
But when user press "wiki link" button to autocomplete note, they are still listed as if "Use first line as title" still enabled.

**To Reproduce**
1. On note lists page, press the navigation header
2. Press "View Settings"
3. Make sure the "Use first line as title" is disabled
4. Open any note
5. Press the "Wiki Link" button (between H1 and Image button, the icon looks like 2 papers on top of each other)
6. The autocomplete note name list don't follow the "View Settings"

**Expected behavior**
The autocomplete will not use first line as title if that option disabled.

**Actual behavior**
It uses the note name/file name as autocomplete.

**Workaround**
Manually typing the note name.

**Platform:**
 - OS: iOS
 - iOS version: 14.3
 - FSNotes version: 4.6.2

**Comment by glushchenko** [comment]
Fixed, thanks!

**Comment by ybbond** [comment]
I also thank you! This project has been a great and active one.

Cheers, keep up the good work 🥳

**Comment by ybbond** [comment]
confirmed working on v4.7.2, thanks!

Closing this issue as solved.
