### ISSUE TITLE
automatic backup does not work

### ISSUE THREAD

**Issue by CoolMa7** [glushchenko/fsnotes#1051]
**Describe the bug**
I configured preferences -> git -> automated backup -> every 0 hour 30 minutes
No backups are created.

**To Reproduce**
Open preferences
Click "git"
Click "save every"
input "0" hour "30" minutes 

**Expected behavior**
Save changes of documents edited all 30 minutes. (git log --oneline should show commits automatically created by FSNotes)

**Actual behavior**
In the default folder that holds the git repositories ~/Library/Containers/co.fluder.FSNotes/Data/Library/Application Support/Repositories/5f4b - FSNotes.git I do not find any commits automatically created by FSNotes. Only commits created by hitting Command-S (save revision) can be found there.

**Workaround**

**Supporting Files**

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.1
 - FSNotes version: 4.9.5

**Additional context**

**Comment by glushchenko** [comment]
Should be every 1 hour minimum. What is 0 hour?

**Comment by CoolMa7** [comment]
0 hour 30 minutes -> every 30 minutes

**Comment by glushchenko** [comment]
No. Key is "At". Examples: 

Every 1 hour at 30 minutes:

12:30
13:30
14:30
...

Every 2 hour at 15 minutes:

00:15
02:15
04:15
...

**Comment by glushchenko** [comment]
You should change time to 1 minute before, not near. I tried, working fine for me.

**Comment by CoolMa7** [comment]
OK, confirmed, it is working as expected. I misunderstood the intended interpretation of "save every" configuration item.

Thank you.

**Comment by CoolMa7** [comment]
It is working as expected.
