### ISSUE TITLE
{{TOC}} feature?

### ISSUE THREAD

**Issue by nicolasbulb** [glushchenko/fsnotes#1052]
**Describe your feature request**
I'm a NValt and 1Writer markdown user for a long time and I've discovered FSNote and I really like the clean approach but I'm surprise {{TOC}} are not included in the core features.
Is it possible to include it?

**Additional context**
macOS 10.13.6

**Comment by glushchenko** [comment]
What is TOC?

**Comment by gingerbeardman** [comment]
Table of contents

**Comment by semiopat** [comment]
Yes, TOC would be a good feature to add to fsNotes ; really missed it as writing a chaptered note.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
