### ISSUE TITLE
Case in titles cannot be corrected

### ISSUE THREAD

**Issue by cmod** [glushchenko/fsnotes#1053]
**Describe the bug**
Example Title: "My FAvorite Restaurants"
Desired title: "My Favorite Restaurants" 

**To Reproduce**
1. Create a document 
2. Click on the document "header" with the title (the top of the window frame) to edit it
3. Edit the title in such a way as to only correct for case
4. See error: "Incorrect File Name!" 

**Expected behavior**
It should just rename the file to the correct case

**Actual behavior**
Throws an error

**Workaround**
Edit the filename in finder?

**Desktop (please complete the following information):**
 - FSNotes version: 4.9.5 (454)

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.9.6beta/FSNotes_4.9.6.zip
