### ISSUE TITLE
Notes with subtags are not showing up

### ISSUE THREAD

**Issue by almeco** [glushchenko/fsnotes#1055]
**Describe the bug**

**To Reproduce**
1. Create a tag #1
2. Create subtag #1/2
3. Create a note which contains subtag #1/2
4. Click on it in the note list - it will show normally
5. Now click on the subtag #1/2 and again try to open the note attached to it - it wont show

**Expected behavior**
A note tagged #1/2 should show but it doesn't

**Actual behavior**
Note is not showing

**Workaround**
For now to actually show the note I have to click another tag or folder and then click subtag once again

**Supporting Files**
I made a movie to ilustrate the bug
https://share.getcloudapp.com/12uKwnoJ

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 3.8.2

**Additional context**
None

**Comment by stefandesu** [comment]
I've noticed similar issues, and I've also noticed issues with tags not appearing in the tag list or only appearing after leaving the note. Might be related.

**Comment by glushchenko** [comment]
Thanks guys, i will try to reproduce it later.

**Comment by glushchenko** [comment]
@almeco fixed

@stefandesu not related, please fill new issue with reproduction steps.

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.9.6beta/FSNotes_4.9.6.zip

**Comment by almeco** [comment]
will it overwrite my current notes / flush them?
