### ISSUE TITLE
Feature request: Option for disabling search highlight

### ISSUE THREAD

**Issue by espen** [glushchenko/fsnotes#1056]
It would be great if it was possible to disable search word highlighting in the note when searching.

**Comment by espen** [comment]
Thanks for the update and your great work @glushchenko.

Perhaps I am misunderstanding the commit here but it seems to fix a bug that is not related to this issue? The issue for me is that a search would highlight the search word in the notes. I would prefer an option to disable that.

See this example:

<img width="401" alt="CleanShot 2021-08-23 at 13 16 40@2x" src="https://user-images.githubusercontent.com/32258/130438771-02e2c2e9-1f73-4e2a-b3b7-2f1ea30ef385.png">

In this example the search term is repeated many times in the note so it is a bit annoying to read. If I want to edit and click the note then this is not an issue as the highlight disappears but for just checking up on some note and reading it then it too many distractions.

**Comment by glushchenko** [comment]
Thanks, will be available in near releases over advanced settings.

**Comment by glushchenko** [comment]
`defaults write co.fluder.FSNotes searchHighlighting -bool false`

Please try: https://github.com/glushchenko/fsnotes/releases/download/5.1.0beta1/FSNotes_5.1.0.zip
