### ISSUE TITLE
encrypted notes show up as plaintext in finder?

### ISSUE THREAD

**Issue by ihubgit** [glushchenko/fsnotes#1057]
Hi, something bugs me. From the menu bar dropdown menu, it seems that encryption is enabled by default (because CMD7 proposes to delete encryption), but such a note, without locking it, shows up as plaintext in finder ! So where's the encryption then?

**Comment by gingerbeardman** [comment]
See here: https://github.com/glushchenko/fsnotes/wiki/Containers

You need to use a container to encrypt.

"Remove Encryption" being available without using a container is a bug, I'll file it.
