### ISSUE TITLE
"Remove Encryption" is available without using a container

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1058]
**Describe the bug**
"Remove Encryption" is available without using a container

from #1057

**To Reproduce**
1. Set Text Container to "None"
2. Create new note
3. Right click on note, or select note and choose file menu

**Expected behavior**
- option to remove encryption (Cmd+7) should be disabled or hidden when the selected note is not using an encrypted container

**Actual behavior**
- option to remove encryption (Cmd+7) is available on all note types

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.9.5

**Comment by glushchenko** [comment]
Thank you, Matt! Fixed.

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.9.6beta/FSNotes_4.9.6.zip
