### ISSUE TITLE
Date modified and Date created issue

### ISSUE THREAD

**Issue by biznachio** [glushchenko/fsnotes#106]
Hi! First, I'm digging FSNotes and it fits near flawlessly into my workflow. I'm particular about managing my notes by date and I've noticed when I edit a note in FSNotes the app appears to overwrite the Date Created and the Date Modified as the same date. 

I've attempted adjusting the created date back to its original date using Touch but FSNotes overwrites the date upon the next edit.

I hope I explained the issue clear enough. I wanted to alert you to a potential issue and seek help finding a solution.

Thanks for the support!

**Comment by jeff-h** [comment]
Well spotted — it does do this for me too. Grrr! I love my metadata 😜

**Comment by glushchenko** [comment]
I promise fix it today/tomorrow. Thank you for bug report 👌

**Comment by biznachio** [comment]
Thanks for the prompt reply and fix!

**Comment by glushchenko** [comment]
Fixed in 1.2.7

**Comment by gingerbeardman** [comment]
@biznachio any chance you could edit your App Store review? 2 out of 5 seems harsh given how swiftly this was fixed. cheers!
