### ISSUE TITLE
WikiLinks menu item deletes selected text

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1062]
**Describe the bug**
The WikiLinks menu item deletes selected text.

The Link and WikiLinks menu items behave differently.

**To Reproduce**
1. Select some text
2. use Format > WikiLinks from the menubar

**Expected behavior**
The selected text is surrounded with double brackets, similar to Format > Link.

**Actual behavior**
The selected text is replaced with empty double brackets.

**Workaround**
If you already typed the name of a file you want to link to, surround it with double brackets manually.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.9.5

**Comment by glushchenko** [comment]
fixed

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.9.6beta/FSNotes_4.9.6.zip

**Comment by tewe** [comment]
Works for me. Thanks!
