### ISSUE TITLE
WikiLinks auto-completion is case-sensitive

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1064]
**Describe the bug**
The auto-completion to insert WikiLinks uses a case-sensitive file name search.

**To Reproduce**
1. place the cursor in a file
2. use Format > WikiLinks
3. start typing the name of one of your files
 
**Expected behavior**
Case-insensitive matching, just like the main search box.

**Actual behavior**
Case-sensitive matching.

**Workaround**
Only use lower case in your file names?

 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.9.5

**Comment by glushchenko** [comment]
fixed

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.9.6beta/FSNotes_4.9.6.zip

**Comment by tewe** [comment]
Works for me. Thanks!
