### ISSUE TITLE
Note list text is not full width (if shown as sidebar)

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#1066]
**Describe the bug**
The entries in the sidebar are not using the full available width to display the text content. In the image below the text is "Knowledge" which would fit easily in the cell content but it seems something invisible is taking up space from the right.

**To Reproduce**
NA

**Expected behavior**
The text should use the full width if nothing else is displayed in the cell.

**Actual behavior**
Text is truncated unnecessarily and leaves an unused whitespace at the end.

**Workaround**
None.

**Supporting Files**
![screen](https://user-images.githubusercontent.com/1321720/106451360-bf21f100-6486-11eb-9cf5-b9324f02bb7f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.9.5

**Additional context**
NA

**Comment by glushchenko** [comment]
How to reproduce it?

**Comment by relikd** [comment]
For me it is always like that. I dont need to do anything, it just is. You can resize the sidebar and see if the truncation starts too early

**Comment by relikd** [comment]
https://user-images.githubusercontent.com/1321720/106647219-ef54b700-658e-11eb-9a52-aaf3d266a217.mov

**Comment by glushchenko** [comment]
Fixed in 4.9.6 https://github.com/glushchenko/fsnotes/releases/download/4.9.6/FSNotes.zip

**Comment by relikd** [comment]
Nope, still there. Same distance as before. Do I need to to something?

**Comment by relikd** [comment]
And it may be a coincidence but the create-new-note icon above the list happens to be the exact space where it starts to truncate. As if the table is two column and the second column is only used for the new-note button.

**Comment by glushchenko** [comment]
Can you make video or screenshot?

**Comment by relikd** [comment]
Sure, but it literally is the same video as before:

https://user-images.githubusercontent.com/1321720/106792320-46718f00-6656-11eb-9cc2-077e8231be39.mov

**Comment by relikd** [comment]
The accessibility shows an insetted text field inside the cell.

![screen](https://user-images.githubusercontent.com/1321720/106792890-052daf00-6657-11eb-9f60-0d921e7aad3a.png)

**Comment by glushchenko** [comment]
Fixed! :)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.9.7beta/FSNotes.zip

**Comment by relikd** [comment]
The distance is shorter but still there. Approx the same distance as the padding on the left side of the cell.
But that is good enough for me, I can live with it :) 🎉
