### ISSUE TITLE
Math equations are not rendered at all

### ISSUE THREAD

**Issue by nickirk** [glushchenko/fsnotes#1067]
Describe the bug
As the title describes, either the inline or the display mode equations are not rendered.

To Reproduce
Use macOS Big Sur 11.1 or 11.2 on both Intel and Apple M1 chip Macs.

Expected behavior
The math equations should be rendered correctly.

Actual behavior
The math equations are shown as raw texts with the $$$$ 

Workaround
None.

Supporting Files
![image](https://user-images.githubusercontent.com/9270917/106736699-160a0080-6616-11eb-8ea9-f69a941133ff.png)

Desktop (please complete the following information):

OS: macOS
OS version: 11.1 and 11.2
FSNotes version: 4.9.5 (454)
Additional context
This bug shows up on both the Intel and Apple M1 chip Macs

**Comment by gingerbeardman** [comment]
View > Preview MathJax

**Comment by nickirk** [comment]
> Switch On: `View > Preview MathJax`
Thanks, I didn't know that. But it would be nice to specify this step in the example note titled "6. Mermaid and MathJax", otherwise looking at the Mermaid diagrams got correctly rendered but not the math equations, it is a bit confusing.

**Comment by gingerbeardman** [comment]
I'll add that to the example note! Thanks
