### ISSUE TITLE
Math equations not rendered when print to PDF file or paper

### ISSUE THREAD

**Issue by nickirk** [glushchenko/fsnotes#1069]
Hi FSNotes developers,

I found this app recently and fell in love with it immediately. It is a great app. Thank you for your hard work. The open source nature of it and the open-minded design philosophy behind it are the most attractive features. I have bought the iOS app to work with the macOS app. The seamless workflow among different devices is great. I can see myself use it as my main note-taking app. However, since I use math equations in my work heavily, I am very concerned about the functionalities around them. Here I found another **potential** bug related to it.

**Describe the bug**
The math equations show up correctly in preview, but when I want to print it either to a PDF file or a paper, they are not rendered, i.e. showing as raw texts. 

**To Reproduce**
1. Create any note
2. Use either display mode or inline mode to write down an equation, like $$E=mc^2$$
3. cmd + p, to print
4. Choose to save as a PDF file or print to a paper
5. Open the PDF file or see your printed paper
6. The equations are shown as raw texts.

**Expected behavior**
Apparently I expect the equations to be rendered as in FSNotes

**Actual behavior**
Other markdown features are rendered correctly, but not the math equations.

**Workaround**
I have not found one, yet.

**Supporting Files**
In FSNotes:
![image](https://user-images.githubusercontent.com/9270917/106807025-f223da80-6668-11eb-9e6c-e5794ac00c42.png)

In the printed PDF file:
![image](https://user-images.githubusercontent.com/9270917/106807085-05cf4100-6669-11eb-9284-6eff01d703f7.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 11.2
 - FSNotes version: 4.9.5

**Comment by glushchenko** [comment]
Welcome and thank you for bug report. I will try fix it ASAP.

**Comment by glushchenko** [comment]
Test build https://github.com/glushchenko/fsnotes/releases/download/4.9.7beta/FSNotes.zip
