### ISSUE TITLE
Pasted image uses absolute path

### ISSUE THREAD

**Issue by jdve** [glushchenko/fsnotes#1070]
**Describe the bug**
I've noticed that pasting an image results in using an absolute path (e.g., `/i/728b1960-76b6-4305-825c-9fb8041ec591.jpg`). This works great inside of FSNotes, but it's not particularly compatible with other markdown editors which assume that this is a truly absolute path from the root of the filesystem instead of relative to the note. It would be more compatible to use a relative path (e.g., `i/728b1960-76b6-4305-825c-9fb8041ec591.jpg`).

**To Reproduce**
1. Copy an image from somewhere into the clipboard.
2. Create a new markdown note in FSNotes.
3. Paste the image into the note.

**Expected behavior**
Pasted image should use a relative path (e.g., `i/728b1960-76b6-4305-825c-9fb8041ec591.jpg`).

**Actual behavior**
Pasted image uses an absolute path (e.g., `/i/728b1960-76b6-4305-825c-9fb8041ec591.jpg`).

**Workaround**
Manually edit the markdown file outside of FSNotes after pasting the image.

**Supporting Files**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.1
 - FSNotes version: 4.9.2

**Additional context**
N/A

**Comment by glushchenko** [comment]
Good point, fixed.

**Comment by jdve** [comment]
Wow, that was fast! Thank you so much!!

**Comment by glushchenko** [comment]
Test build https://github.com/glushchenko/fsnotes/releases/download/4.9.7beta/FSNotes.zip
