### ISSUE TITLE
Versioning (not a bug)

### ISSUE THREAD

**Issue by luckman212** [glushchenko/fsnotes#1071]
First, thank you for FSNotes! The way versioning is done in the GitHub releases is making it tough to track when new versions are pushed. I have this automated using GitHub's graph API to keep my build up to date, but for example:

| Release Tag | CFBundleShortVersionString | CFBundleVersion in Info.plist | CURRENT_PROJECT_VERSION in project.pbxproj |
|:----------- |:-------------------------- |:----------------------------- |:------------------------------------------ |
| 4.9.0       | 4.9.0                      | 443                           | 442                                        |
| 4.9.0b444   | 4.9.0                      | 444                           | 443                                        |
| 4.9.6       | 4.9.6                      | 457                           | 456                                        |
| 4.9.7beta   | 4.9.7                      | 458                           | 457                                        |
| 4.9.7b2     | 4.9.7                      | 459                           | 458                                        |

With these variations in the tag format and overlapping version strings, it makes automated version tracking hard or impossible. Have you thought of make `CFBundleShortVersionString` match the GitHub tags exactly, or adding the build number to the short version string (e.g. for release 4.9.7b2 the `CFBundleShortVersionString = 4.9.7.459`)? That would be very helpful.

**Comment by glushchenko** [comment]
All release tags with **beta** **b444** **b2** addressed to testers and marked as "Pre Release". Please dont download Pre Releases, if you are not author of the ticket. Just skip it, Thanks.
