### ISSUE TITLE
Unable to edit notes

### ISSUE THREAD

**Issue by fkruidhof** [glushchenko/fsnotes#1072]
**Describe the bug**
After selecting an existing note, I am unable to edit it.

**To Reproduce**
1. Go to the search field or click on a tag
2. Click on on a note
3. click on editor
4. you can only select text, the caret can not be placed in the text

**Expected behavior**
Caret is placed in the text of the note

**Actual behavior**
Caret is not placed in the text of the note

**Workaround**
right click the not and choose "open" to open it in a texteditor (defeating the purpose of having a quick note taking app)

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7 (Catalina)
 - FSNotes version: 3.8.2

**Additional context**
This is a recent problem, which happened after the latest Catalina security update.
New notes can be created and edited

**Comment by glushchenko** [comment]
Click eye in the right top corner 
![image](https://user-images.githubusercontent.com/1089917/107852383-16c24400-6e19-11eb-8560-c2aec206b714.png)
