### ISSUE TITLE
Confirmation of password before locking the note or use a single master password for all notes.

### ISSUE THREAD

**Issue by nickirk** [glushchenko/fsnotes#1074]
**Describe your feature request**
When encrypting a note, please add a confirmation step after the user enters the password. Or just use a single master password for all notes. 

**Additional context**
I thought FSNotes use a single password for the encryption of all notes, but I just found out that it is not the case through an unpleasant experience. 
So when I was asked to enter a password to encrypt a note, I probably mistyped the password that I thought is the "master" password which I use for the encryption of all my notes. But later on, I realised that I can no longer decrypt it with the "master" password, because I probably mistyped it during the encryption step. 

So I would suggest either adding an additional confirmation step to make sure the user types in the intended password during the initial encryption step of a note, or just using a single master password for all notes.

Add any other related information here. macOS or iOS?
For both macOS and iOS.

**Comment by Vipoli** [comment]
In my opinion a nice solution could be this one: when you encrypt a note, the system checks the password you enter; if it is different from the master one, a popup alerts you that it is different and asks you to confirm it.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.4.1
