### ISSUE TITLE
Linking to a note overwrites the contents of that note

### ISSUE THREAD

**Issue by timster** [glushchenko/fsnotes#1075]
**Describe the bug**

This is a nasty bug that will cause data loss.

If you link to an existing note, the contents of the existing note are overwritten by the contents of the new note.

**To Reproduce**

1. Create a new note.
2. Drag an existing note into the new note to create a link.
3. Click on the existing note.

**Expected behavior**

You link to the existing note and no data loss occurs.

**Actual behavior**

The contents of the existing note will have been overwritten by the contents of the new note.

**Workaround**

None that I can tell.

**Supporting Files**

https://user-images.githubusercontent.com/173666/108250165-ea157180-7123-11eb-9d1d-a704dc13236a.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.2
 - FSNotes version: 4.9.7

**Additional context**

None

**Comment by glushchenko** [comment]
Definitely horrible bug, sorry for this :( Hotfix already available https://github.com/glushchenko/fsnotes/releases/download/4.9.8/FSNotes.zip

**Comment by timster** [comment]
Oh, awesome! Thanks for the quick fix.

I had everything in version control so I didn't actually lose any notes, but glad it's fixed.
