### ISSUE TITLE
iCloud Drive synchronization on iOS only triggered when local content is changed

### ISSUE THREAD

**Issue by ambv** [glushchenko/fsnotes#1078]
I'm using iCloud Drive for FSNotes on both macOS and iOS. When a new file is created or changed on macOS, I expect to see the change on iOS as soon as it's synced to iCloud Drive. Instead, the iOS app only updates synchronized notes when a change is made in the iOS app to any notes. Force-closing and reloading the app is insufficient, I need to make a local change on the phone for other iCloud Drive changes to download. As soon as I create a new note on the phone, other changes are downloaded.

The macOS app doesn't have this behavior, new or changed files on the phone appear almost instantly on macOS.

I also noticed that the files from Mac FSNotes synchronize just fine to iCloud Drive because I can confirm this through looking at iCloud Drive on icloud.com. So the issue is that FSNotes on iOS is not refreshing on its own when changes through other devices are made.

## Versions
 - up-to-date macOS 10.15.7 Catalina on 2018 Macbook Pro
 - up-to-date iOS 14.4 on iPhone Xs
 - FSNotes Mac 4.9.8 (462) from Mac App Store
 - FSNotes Manager iOS 4.7.2 (221) from US App Store

**Comment by ambv** [comment]
Also, trying to manually "refresh" by swiping down on the list of notes shows the throbber but then only switches to the search bar, no synchronization is done.

**Comment by glushchenko** [comment]
This is not FSNotes related. You can easy check, just open Files.app on iPhone and files not be downloaded.

**Comment by ambv** [comment]
I can't see the FSNotes folder in Files.app on iPhone at all. It's there in Finder's "iCloud Drive" on the Mac. Surely this isn't intended behavior in either case. Even restarting the phone doesn't make FSNotes synchronize.

How do you deal with this yourself?

**Comment by glushchenko** [comment]
On iOS -> Files.app -> iCloud Drive -> FSNotes

**Comment by ambv** [comment]
OK so I followed this troubleshooting guide for Notability: https://support.gingerlabs.com/hc/en-us/articles/205688797-Troubleshooting-iCloud-Sync

Specifically the advice to disable iCloud Drive for FSNotes on both Mac and iOS, and then re-enable it, worked. Now syncing works as expected.

Do you mind if I add this information to your wiki?

**Comment by glushchenko** [comment]
No problem, welcome!

**Comment by ambv** [comment]
OK, I added it: https://github.com/glushchenko/fsnotes/wiki/Using-iCloud-Drive-to-sync-between-iOS-and-Mac

Thanks for your work on this wonderful app! It's awesome to have access to the text notes and not have them jailed in some closed application. It's a miracle you made this open-source as well.

**Comment by ambv** [comment]
I guess since I'm not a collaborator on the repository, I couldn't add any inline images to the Wiki page. I hope it's descriptive enough on its own.

**Comment by gingerbeardman** [comment]
It's a great entry, thanks so much. If you add the images here we can add them for you? 

Maybe put text placeholders in the page and I'll replace with the images?
