### ISSUE TITLE
Option to use filesystem tags?

### ISSUE THREAD

**Issue by iandol** [glushchenko/fsnotes#1079]
**Describe your feature request**
macOS FSNotes used to use filesystem (metadata) tags, whose benefits extend past FSNotes and are supported by iCloud, allowing search by other apps etc. It seems that most users prefer however to type plaintext tags into their files (more robust to filesystem issues, but not supported by other apps), and possibly it enables people who use iOS to easily tag their files. We can turn off the inline tag scanning, but we now cannot return to seeing the filesystem tags anymore (this feature was present, but then removed). So my request is to have an option to once again support filesystem tags. 

**Additional context**
macOS.

**Comment by glushchenko** [comment]
No. Metadata tags not reliable and removed on sync.

**Comment by iandol** [comment]
OK, thank you for your consideration and a great app! Best wishes.

**Comment by glushchenko** [comment]
Thanks @iandol
