### ISSUE TITLE
Shortcut to open FSNotes

### ISSUE THREAD

**Issue by savior1980** [glushchenko/fsnotes#108]
I've tried to switch to FSNotes from nvAlt, however, the shortcut does not behave the same way, nvAlt has the same shortcut to open the app up and to hide it, this is very useful and it does not work the same way in FSNotes. Certainly you can invoke FS with a shortcut but once you have the contents to store in a new note, you shoud be able to hide the application right away, and now it feels strange as you need to close it with Cmd+W or to swithc to other applications with Cmd+Tab, at least there should be an option to hide it with the same shortcut, once it is in focus (as nvAlt does).

**Comment by glushchenko** [comment]
Added in 1.2.8 https://github.com/glushchenko/fsnotes/releases/tag/1.2.8

**Comment by wwtex** [comment]
I'm sorry to drudge up an old issue, but I can't seem to find what the keyboard shortcut is. It's not in the README and I can only find "Hide FSNotes" in the menu bar. What is the NValt-like show/hide toggle shortcut?
