### ISSUE TITLE
Scroll view jumping around during editing

### ISSUE THREAD

**Issue by pdanford** [glushchenko/fsnotes#1082]
**Describe the bug**
Some edit operations (e.g. backspacing over a trailing back-tick) can cause random scroll jumps. See attached video.

**To Reproduce**
1. see attached video, or:
2. create multi-page markdown document
3. scroll roughly to middle
4. type something in inline code fence back-ticks
5. backspace over trailing back-tick
7. random scrolls happen 
8. I noticed this only happens when the .backgroundColor attribute is removed and highlighting is done again (i.e. when rescanAll() is executed in FSNotesCore/Shared/CustomTextStorage.swift because of shouldScanСompletely() being true).

**Expected behavior**
No surpise scrolls/jumps

**Actual behavior**
Random size edit area scrolls

**Workaround**
Fix:
In FSNotes/ViewController.swift, uncomment `editArea.layoutManager?.allowsNonContiguousLayout = false` (line 345).

**Supporting Files**

https://user-images.githubusercontent.com/5867795/109341160-db634480-781e-11eb-92d0-626923ba5ab8.mov

**Desktop**
 - OS: macOS
 - OS version: 11.2.1
 - FSNotes version: 4.9.8

**Additional context**
https://stackoverflow.com/questions/5323830/modifying-nstextstorage-attributes-causes-scroll-view-to-jump-around

**Comment by gingerbeardman** [comment]
Thanks for the great bug report.

**Comment by gingerbeardman** [comment]
What do you think @glushchenko ?

**Comment by glushchenko** [comment]
Hi, guys, i can add option for allowsNonContiguousLayout, but in my opinion this works too slow.

**Comment by pdanford** [comment]
Hi! How large a note are you talking about for the slowness? There are reports of allowsNonContiguousLayout = false not getting sluggish until you have thousands of lines of text.

I've only found slowness when "Code block live highlighting (app restart required)" is checked. With that, it can take several seconds to switch between notes (in edit mode). Without that, it's lightning fast. This is with the current allowsNonContiguousLayout mode being true. 

So that is to say, it looks like the only slowness I've seen is from the JavaScript highlighting code.

**Comment by glushchenko** [comment]
OK, i will try to implement and test it ASAP, hopefully on this week.

**Comment by pdanford** [comment]
To add to the slowness hack I mentioned above, I do
mv /Applications/FSNotes.app/Contents/Frameworks/Highlightr.framework/Versions/A/Resources/highlight.min.js \
   /Applications/FSNotes.app/Contents/Frameworks/Highlightr.framework/Versions/A/Resources/highlight.min.js.disabled

This allows "Code block live highlighting (app restart required)"  to be selected so I still get whole code block background color, but without the keyword color highlights. It's a good trade-off becuase the whole block background really helps visually in edit mode, but without the extreme slowness of making new code blocks (by typing an opening ``` manually) or pages with many code snippets.

**Comment by glushchenko** [comment]
New option was added.

https://github.com/glushchenko/fsnotes/releases/download/4.9.9/FSNotes.zip 

![Untitled](https://user-images.githubusercontent.com/1089917/111913150-80b3b600-8a75-11eb-939a-12e307eff136.jpg)

**Comment by gingerbeardman** [comment]
So default is box unchecked. Is this the same as default behaviour previously?

If I tick it it will prevent the scroll view jumping around?

It's not so clear to me.

The name of the option is technically correct, but I think will get some questions from users.

**Comment by glushchenko** [comment]
Yes, @gingerbeardman by default note loaded partially for speed up all loading (as before this build). But you can enable non contiguous loading, this is slow but note will be loaded fully.

**Comment by gingerbeardman** [comment]
My brain has a problem with the enabling of an option that says "non" in it. 😅

**Comment by glushchenko** [comment]
Me too, but this naming part of API from Apple. May be we can rename it?

**Comment by gingerbeardman** [comment]
Maybe.

From the docs "In large documents, this can significantly increase performance, since the layout does not need to performed from the beginning of the document."

I'll have a think. Need to get my head around the two modes.

**Comment by pdanford** [comment]
Some colleagues have pointed out the editing jumping around while typing is much more of a deal breaker than slowness. But I'm not seeing the slowness using non contiguous mode. I'm on a high end macbook pro, so maybe it's because of that (or does the slowness show up in iOS)? How large a note is needed before slowness is seen?

**Comment by gingerbeardman** [comment]
Let's discuss in #1097

**Comment by pdanford** [comment]
To be clear, the "Non Contiguous Layout" option should be un-checked to address this bug. And it did fix it for me. Thank you!
