### ISSUE TITLE
Search highlight of multiple terms

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#1083]
**Describe your feature request**
Hello,

In the "search and create bar", if I enter a single term, any notes with that term will be filtered, and when I press the up/down arrow, I can browse the notes with the term highlighted. This is convenient as I can quickly figure out the relevant note and context.

However, when I enter more than a single term in the "search and create bar", the terms are no longer highlighted in the notes. This makes it difficult to figure out which notes are relevant. 

I wonder is it possible to make highlight of multiple search terms in a note possible?

**Additional context**
This is a feature requested for the MacOS app.

**Comment by tewe** [comment]
In 6.8.1 it looks like it highlights the exact phrase you searched for. It still searches for each word individually, so sometimes this highlights nothing.
