### ISSUE TITLE
better Folder display options

### ISSUE THREAD

**Issue by dircadmin** [glushchenko/fsnotes#1084]
**Describe your feature request**
I would love to be able to manage the folders in the sidebar better. I would love to get nested folder support (with a triangle to expand or so) and the option to hide folders from the sidebar. Like this it gets quite messy with multiple folders. 

**Additional context**
MacOS. I attached the storage if iaWriter and there I have multiple levels of folders. Like this all of them are getting displayed and it's quite a mess. Also, labels "#" are shown at the end of the long list of folders, so maybe rearranging them above would be good as well. Hiding all folders would also work for me.

**Comment by glushchenko** [comment]
1. First part is dupe https://github.com/glushchenko/fsnotes/issues/188
2. Folders hiding/showing already implemented here https://github.com/glushchenko/fsnotes/wiki/Advanced-settings

**Comment by dircadmin** [comment]
The option to hide folders in the sidebar is not what I meant. The way you've linked is to disable the folders completely, but I wish to simply not display the folders in the sidebar. I still want to have access to the files inside the folders. 

Maybe that would be an option for the future. Hiding by folding in/out like in finder with the triangles would be perfect. This may be possible together with #188
