### ISSUE TITLE
Page jumps when pressing backspace in code blocks

### ISSUE THREAD

**Issue by qqvm** [glushchenko/fsnotes#1088]
**Describe the bug**
In edit mode in code blocks, when pressing backspace to delete previous character view is randomly jumping. Sometimes it changes position of the pointer to another line.

**To Reproduce**
1. Open a note with code blocks
2. Switch to edit mode
3. Set pointer somewhere in code block
4. Press backspace

**Expected behavior**
Character is deleted. No jumps of the interface.

**Actual behavior**
Interface is randomly jumping. Sometimes insertion point position is changed.

**Workaround**
?

**Supporting Files**
https://user-images.githubusercontent.com/54307539/110354427-d1242000-8040-11eb-924e-d194763ca04a.mp4

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.2.2
 - FSNotes version: 4.9.8

**Additional context**
I have a lot of code blocks in a note (~ 50).
TextBundle was imported from Bear notes, after exporting as a TextBundle.

**Comment by pdanford** [comment]
This is the same bug as #1082 I believe. That also has the fix for it.

**Comment by glushchenko** [comment]
Can not reproduce it, please attach example.

**Comment by qqvm** [comment]
There is a video in the issue supporting files.

**Comment by glushchenko** [comment]
1) Link not working
2) I dont want type all text from video

**Comment by gingerbeardman** [comment]
Did you try the new option "Non Contiguous Layout"?

**Comment by pdanford** [comment]
To be clear, the "Non Contiguous Layout" option should be un-checked to address this bug. And it fixed #1082 for me :)

**Comment by glushchenko** [comment]
Disabled by default in last release.
