### ISSUE TITLE
Cosmetic/usability issues - search bar preference and spelling check

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#109]
There is a preference for Search Bar Orientation with options of vertical and horizontal. It seems this has more to do with Notes List Location with options of side and top or Application Orientation with options of vertical and horizontal.

When I select a note in the notes list, the menu item "Check Document Now" under "Spelling and Grammar" is grayed-out. This makes some sense because the cursor is not in the main document window. However, this is a usability issue for me and it would be helpful if this menu item was not grayed-out in this situation.

I'm using FSNotes 1.2.7.

Thanks.

**Comment by glushchenko** [comment]
Done. Please enable "Preferences -> Editor -> Focus in editor when select note"

**Comment by peavine** [comment]
I enabled the focus-in-editor option and that works great. Thanks.

The change to "Notes List Location:" looks good, but I think the options work the opposite of what they should. For example, when I enable "Top", the Notes List is on the side.
