### ISSUE TITLE
Nested tags are not reachable in case of a long name and/or multiple levels

### ISSUE THREAD

**Issue by qqvm** [glushchenko/fsnotes#1090]
**Describe the bug**
If there is a big number of symbols in a sub-tag, it is impossible to select such tag in the navigation panel without resizing to show more space.

**To Reproduce**
1. Open a note
2. Add the next tag:
#notes/general/personal/temp/education/reading/tasks
3. Expand all tags in hierarchy

**Expected behavior**
It is possible to scroll horizontally in the navigation panel when text is too long to fit the given size.

**Actual behavior**
It is not possible to scroll horizontally in the navigation panel when text is too long to fit the given size.

**Workaround**
Enable horizontal scrolling in the navigation panel. Also it might be useful for adding sub-folder view in the future.

**Supporting Files**
<img width="138" alt="Screenshot 2021-03-09 at 15 02 32" src="https://user-images.githubusercontent.com/54307539/110474593-878f1000-80e8-11eb-9132-6aa4fc342dd1.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.2.3
 - FSNotes version: 4.9.8

**Additional context**
None

**Comment by glushchenko** [comment]
This is not very convenient, since the sidebar contains more than just tags. I recommend resizing.
