### ISSUE TITLE
Notes no longer showing in MacBook pro

### ISSUE THREAD

**Issue by sdclee** [glushchenko/fsnotes#1091]
**Describe the bug**
I have an iPhone 12, MacBook Pro, iPad Pro, iMac Pro, all up to date except for having held back on the Catalina to Big Sur upgrade. For some reason my notes don't show any longer on the MacBook pro.
I have added a note directly in there and taken a screenshot to illustrate.

All of my notes appear under iCloud Drive / FSNotes when I look in Finder but they are missing from the app itself.
I have looked in the settings but can't see anywhere to point the app at a specific folder and I haven't changed anything.
<img width="571" alt="fsnotes" src="https://user-images.githubusercontent.com/1264229/111081088-75064380-84f9-11eb-8a80-3a0c1d63e655.png">

FSNotes 4.9.8 build 462

Please advise.
Thanks in advance.
L
ee

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 3.8.2

**Additional context**

**Comment by glushchenko** [comment]
I dont see any information how to reproduce it. So i can not help.

But you can set default storage here:

Preferences - General - Default storage

**Comment by sdclee** [comment]
Thanks for the prompt reply. The only thing I could supply was the
screenshot.
Under general - default storage the folder looked to be correct.
I hit the change button and after the warning about moving the document
storage, I cancelled out and hey presto, all my notes appeared again. Go
Figure!
L
ee
