### ISSUE TITLE
ICLOUD syncing

### ISSUE THREAD

**Issue by Bicarbona** [glushchenko/fsnotes#1092]
**Describe the bug**
FSNotes stopped syncing with ICLOUD

**Desktop**

 - OS version: 10.15.7 - catalina
 - FSNotes version: 4.9.8 - (462)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/wiki/Using-iCloud-Drive-to-sync-between-iOS-and-Mac

**Comment by gingerbeardman** [comment]
Please follow the troubleshooting at the above page and report back if there is still a problem.

**Comment by Aetles** [comment]
> https://github.com/glushchenko/fsnotes/wiki/Using-iCloud-Drive-to-sync-between-iOS-and-Mac

For those finding this issue the link is now:
https://github.com/glushchenko/fsnotes/wiki/iCloud-Drive-syncing-between-iOS-and-macOS
