### ISSUE TITLE
Long-ish text items load in chunks

### ISSUE THREAD

**Issue by cmod** [glushchenko/fsnotes#1093]
This is on macOS version: 4.9.8 (462)

On longish text documents I find it takes several seconds for the items to load. And they seem to load in "chunks" as you scroll down. 

These aren't particularly huge documents. One is 7,000 words long. A few times I thought FSNotes had lost pieces of files (I append to the end of one document regularly). 

I understand there is a performance optimization component happening here, but I wonder if it's possible for FSNotes to handle documents up to, say, ~20k words in single loads, rather than chunks? 

Many thanks for all your work,
C

**Comment by gingerbeardman** [comment]
Thanks for this.

There is ongoing discussion in some other issues about this deferred loading.

**Comment by glushchenko** [comment]
New option was added.

https://github.com/glushchenko/fsnotes/releases/download/4.9.9/FSNotes.zip 

![Untitled](https://user-images.githubusercontent.com/1089917/111913150-80b3b600-8a75-11eb-939a-12e307eff136.jpg)

**Comment by cmod** [comment]
Oh, fantastic. Thanks for the quick update. Just installed — looks great. 

One gentle suggestion: I wonder if there's a more descriptive / obvious way to label that option. As it stands, I actually don't know what it means :) 

It looks like unchecked = load notes completely and all at once? 
and unchecked = load in chunks? 

What, precisely, is changing in the way notes are handled with that checked or unchecked?

**Comment by gingerbeardman** [comment]
@cmod Hi Craig, we have discussion of exactly this in #1082, not really the best place for it, and no verdict as to the best wording as yet.

**Comment by gingerbeardman** [comment]
Let's discuss in #1097
