### ISSUE TITLE
Paste and Match Style appears to be default in RTF documents.

### ISSUE THREAD

**Issue by 00-000** [glushchenko/fsnotes#1094]
**Describe the bug**
The Paste and Match Style appears to be default in RTF documents, as pasting removes all font effects (bold, italic, strikethrough, and underline). The same applies to imported RTF documents: their font effects are removed upon import. Strikethrough and underline are exceptions, as problems only arise during import, and not consistently.

Edit: The above applies only to pasting from one RTF document to another, or when importing an RTF document. Pasted HTML has no issues.

Also, ⌥⇧⌘V is used as the keyboard shortcut for Paste and Match Style, which does seem to be a common keyboard shortcut for that action (in Pages for instance). However, most applications still use the old system-wide shortcut, ⇧⌘V. I understand ⇧⌘V is the New Note from Selection shortcut in nvALT, and given the relationship between that application and FSNotes I understand why ⇧⌘V cannot simply be added as an alternate shortcut. Is there a chance of receiving the option to customise the Paste and Match Style shortcut in the General pane of Preferences? Or else (if it is not too much trouble) of yet another pane being created for keyboard shortcut customisation? It is not the only potentially workflow-disrupting keyboard shortcut difference.

Thank you for all your hard work! FSNotes has exceeded my expectations in multiple ways!

**To Reproduce**
1. Go to 'File'
2. Click on 'New RTF'
3. Use TextEdit to create a new RTF document complete with bold, italic, strikethrough, and underline. Make sure one of the words is in a monospace font.
4. Copy RTF text from TextEdit into the RTF document in FSNotes.

**Expected behavior**
Text with all styles should 

**Actual behavior**
Text with strikethrough and underline should remain unaffected, but the two other styles will be gone. At least some fonts are converted, and font size may or may not be affected (it is difficult to tell cross-font).

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.12.13
 - FSNotes version: 4.9.8

**Comment by glushchenko** [comment]
RTF support has been completely discontinued and removed
