### ISSUE TITLE
User file gets renamed automatically

### ISSUE THREAD

**Issue by alex-kovac** [glushchenko/fsnotes#1096]
**Describe the bug**
Losing characters in filenames. Not sure if bug or feature. I have a lot of files named using ISO date format. For example: '2021-03-25 note about garden.md'. I have noticed that files named like that get their filenames changed by FSNotes if I edit their content (I am not touching the filename).

**To Reproduce**
1. switch 'Files naming' preference to 'Auto rename by title'. 
1. have a file with some content placed in notes folder named e.g. '2008-01-12 001 - Title.md'.
2. access that file in FSNotes and edit the content.
3. notice that after editing file content the filename changed from '2008-01-12 001 - Title.md' to ''2008 01 12 001 Title.md'.

**Expected behavior**
_Noli turbare circulos meos._ :) If user named a file explicitly, this should be respected. (ISO date standard, parsing for online publication, etc.). So, I expect the existing filename should remain untouched.

**Actual behavior**
I am only guessing automatic some replacement is happening, since '-' and ' - ' is replaced with single space.

**Workaround**
Switch 'Files naming' preference to 'UUID' but then lose the convenience of human-readable titles.

**Supporting Files**
Example. Above is visible filename format as it was, below (selected) is filename after editing the content of the file (but not the title!)

<img width="223" alt="Screen Shot 2021-03-24 at 09 45 38" src="https://user-images.githubusercontent.com/174563/112280838-b6c78480-8c85-11eb-9f47-36e061a39510.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.9.8 (462)

**Additional context**
I was using iA Writer and only two days ago got back to FSNotes (great work done since I saw it last time!). I directed FSNotes to the existing notes folder, started using it and then noticed these renamings. I have also noticed other 'special' characters disappearing from filenames (fullstop) ... If I can provide any further info, please feel free to ask, of course.

**Comment by glushchenko** [comment]
That is, you propose to maintain a database of notes that were created in the program, and which are not?  And depending on this, change the naming strategy?

**Comment by gingerbeardman** [comment]
@alex-kovac the workaround you list is not quite correct, but is actually what you want.

If you set file naming to UUID then new files will be named as a UUID, but they can be manually renamed using Cmd+R and that name will never be changed.

**Comment by alex-kovac** [comment]
Hi @glushchenko,
Reading other users' proposals, I am not sure if the following strategy is useful but my understanding would be:

When creating a _new_ note:
- if preference 'Files renaming: UUID' then name the new file automatically using UUID.
- if preference 'Files renaming: Auto rename by title', then use the note's first line = Title.

When editing an _existing_ note, leave the title as-is no matter which preference above is set.

Thanks @gingerbeardman. As you explained, the filename keeps the hyphens if I rename it using cmd+R and 'UUID' option in preferences.

I was confused that when 'auto rename by title', the resulting, new filename was slightly changed but not to the Title of the note.

**Comment by glushchenko** [comment]
No new file or old file context. FSNotes don't store any data about import. Its just plain text files from file system.

**Comment by alex-kovac** [comment]
Yes, that is how I understand it. That is the beauty of text/markdown files, right? Perhaps my mistake was thinking that 'Files renaming' preference is relevant only when a file is created in FSNotes. And any other time it will just use the file as-it-is from file system, including the title, whatever it was. Instead, 'Files renaming' preference is persistent (if that's the right word?) and will keep renaming files on edits.

To be honest, the preference _is_ called 'Files renaming' and not 'Naming new files' :).

**Comment by gingerbeardman** [comment]
I'm not sure we want to go down this route, but we could use filesystem creation time to gauge whether a file is "new" or not. Just a thought.

But it sounds like @alex-kovac is OK now.

**Comment by alex-kovac** [comment]
Least complexity is my thinking. It is not hard to rename the file.

I did not expect 'Files renaming' would rename the files continuosly. I know, embarassing :)) it says right there... Somehow I expected it only to help users name a new file. This expectation was wrong.

Still, now I am thinking, is there a purpose in removing (or sanitizing?) hyphens, single quotes and other glyphs from the filename when 'Auto rename by title' is set? For example:
- `'House' - a concept.md` is renamed to `House a concept.md`.
- `A streetcar named 'Desire'.md` is renamed to `A streetcar named Desire.md`.

**Comment by glushchenko** [comment]
> Still, now I am thinking, is there a purpose in removing (or sanitizing?) hyphens, single quotes and other glyphs from the filename when 'Auto rename by title' is set? For example:

Of course, not all file systems supports utf16 symbols, dashes, etc.
