### ISSUE TITLE
Copying a rectangular selection only keeps the first line

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1098]
**Describe the bug**
Apple's text widget supports rectangular selection, by holding the option key while dragging. Copying that only places the first line on the pasteboard.

**To Reproduce**
1. Edit a plain text note
2. hit and hold the option key
3. drag a selection
4. CMD+C
5. open TextEdit or BBEdit
6. CMD+V

**Expected behavior**
The pasted text looks like the original selection. Copying a rectangular selection from TextEdit works like that.

**Actual behavior**
Only the first line comes over.

**Workaround**
Copy a regular selection to a different editor, make a rectangular one there, and copy again.

**Supporting Files**
![Rectangular 2021-03-26 at 00 07 28@2x](https://user-images.githubusercontent.com/645412/112555137-e1b9f180-8dc7-11eb-8ca0-db2e4d617e97.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.9.8

**Comment by gingerbeardman** [comment]
Confirmed.

Only first line is copied.

**Comment by glushchenko** [comment]
Wow, i personally didn't know about this feature before.

**Comment by tewe** [comment]
Works for me. Thanks!
