### ISSUE TITLE
Closing the main window makes it unreachable.

### ISSUE THREAD

**Issue by proksch** [glushchenko/fsnotes#11]
When I close the main window of the app, it keeps running in the dock, but it is impossible to get up the window again. The only solution is to manually quit it and restart it, this is a bit cumbersome.

I would expect that closing the main window either quits the app completely or that clicking the dock icon brings up the main window again. If you ask me, the first would actually be my preference... I would then add it as a permanent icon to my dock and start it whenever needed, without wasting resources if I don't need it.

**Comment by glushchenko** [comment]
Fixed here https://github.com/glushchenko/fsnotes/releases/tag/0.7
