### ISSUE TITLE
v1.2.8 issues

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#110]
Hey — unfortunately I'm having a couple of issues with 1.2.8.

I think you may have forgotten to commit the updated `project.pbxproj` file — neither `SortBy.swift` nor `UserDataService.swift` are included in the project (they are in git though). Also, in commit `42d994` you removed the Bridging-Header.h but it fails compilation for me without it:

`<unknown>:0: error: error opening input file '/Users/jeffh/Swift/fsnotes/FSNotes/Bridging-Header.h' (No such file or directory)`

Finally, for me at least, the Github release version of 1.2.8 crashes on launch, I think due to an incorrect iCloud entitlement expectation:

`2018-01-31 12:40:46.443097+1300 FSNotes[66422:2744424] *** Terminating app due to uncaught exception 'CKException', reason: 'The application is missing required entitlement com.apple.developer.icloud-services'` 

Other than that, I am looking forward to trying your fix for https://github.com/glushchenko/fsnotes/issues/107#issuecomment-361439596 ! Thanks for all the awesome work on this — looks like you put a lot of work into 1.2.8.

**Comment by gingerbeardman** [comment]
Have you tried the app from the releases page?

**Comment by peavine** [comment]
I downloaded the zipped app file from the release page, and it crashed on first launch. I went back to 1.2.7 and it runs fine.

**Comment by glushchenko** [comment]
@jeff-h try "pod install" and ⌘ - shift -key. Project.pbxproj updated now.

Crash fixed, please redownload.

**Comment by jeff-h** [comment]
Yeah, I already tried the pod install :) I think the new project file fixed everything though. It now compiles fine, but unfortunately crashes on launch.

If I replace `NSKeyedUnarchiver.unarchiveObject` with `NSUnarchiver.unarchiveObject` in `UserDefaultsManagement.swift` in `static var fontColor` and `static var bgColor` then it launches and runs beautifully.

Any thoughts why it's hanging up on that for me? The crash was because the forced-unwrap failed in `as! Color`, I believe. In other words, the `NSKeyedUnarchiver.unarchiveObject` returned `nil`.

Your fix for my bug report in #107 works perfectly! :)

**Comment by glushchenko** [comment]
Commit above fixes it :)

**Comment by jeff-h** [comment]
It does indeed :) Awesome! 👍
