### ISSUE TITLE
Welcome.bundle Multilingual support

### ISSUE THREAD

**Issue by MarcusPierce** [glushchenko/fsnotes#1102]
Hello, I am a FSNotes user from China.
I'm glad to see that FSNotes already has a Chinese interface.
But the built-in tutorial of the FSNotes is still in English. (Welcome.bundle)
I have started to translate this and put it on my personal blog, but I hope we can have official multilingual support.
It is hoped that it can provide a way for users of different languages to contribute to translation.

**Comment by glushchenko** [comment]
Any PR appreciated
