### ISSUE TITLE
Intended blocks should be monospaced (preformated)

### ISSUE THREAD

**Issue by spenat28** [glushchenko/fsnotes#1103]
Intended blocks should be PRE-formatted - and not highlighted (unless you chose this in settings)

Currently they are not as PRE in edit mode, but they are PRE & highlighted in preview mode.

- in edit mode they should be monospaced by default
- in preview mode they should not be highlighted if it's not turned on in settings.

This can be considered as bug, and it doesn't work consistently between iOS and macOS versions. Workaround is to use monospaced font everywhere - which is not pleasant solution.

**Comment by spenat28** [comment]
Can this be turned instead of request to bug report or should i close this and open new bug?
It's it is really getting into my way all day long.

**Comment by glushchenko** [comment]
1. In edit mode default font is monospaced "Source Code Pro".

<img width="249" alt="image" src="https://user-images.githubusercontent.com/1089917/127762860-00f54eb7-b4c1-4f97-8e39-71339aba5cf8.png">

2. Preview mode uses libcmark_gfm. Preference should be requested here https://github.com/github/cmark-gfm at first.
