### ISSUE TITLE
Search field autocompletes and doesn't show relevant results in list

### ISSUE THREAD

**Issue by spenat28** [glushchenko/fsnotes#1104]
When searching - text autocompletes to the first hit. When you continue to write that same word, list bellow stops refreshing until you write letter which was not autocompleted or press delele/backspace to remove autocompleted word/s.

**To Reproduce**
  1. Create couple of notes with some text and put somewhere same word, such as 'reader'
  2. create couple of notes with some text containing word beginning with R or RE, such as 'run', 'recept'
  3. create note with name 'reader list'
  4. search for 'read'
  5. it autocompletes 'reader list'
  6. in the list bellow, you will see all results for search of letter 'R' ( which is wrong)
  7. when you continue to write 'reader list' - results don't change ( which is wrong )

**Expected behavior**
- Expected is to have relevant search results, if you have reoccurring words such as 'GIT' and one note called 'GIT' - you should get just notes containing word GIT

**Actual behavior**
- For search when phrase autocompletes - you don't get correct search results, but results of search for the first letter.

**Workaround**
- Workaround is to type what you need, and press backspace, to delete autocompleted phrase. (Not good one.)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.2.3
 - FSNotes version: 4.9.10

**Comment by gingerbeardman** [comment]
I can confirm this behaviour. 

Thanks for the detailed bug report!

**Comment by glushchenko** [comment]
Thanks, fixed.

https://github.com/glushchenko/fsnotes/releases/download/4.9.12/FSNotes_4.9.12.zip
