### ISSUE TITLE
Autocomplete for wiki links after typing [[

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#1105]
**Describe your feature request**
I would suggest adding autocomplete functionality for wiki links when the user types `[[`, similar to already existing autocomplete suggestions for hashtags appearing after typing `#`.

**Comment by EvilKhaosKat** [comment]
It'd be awesome if such autocompletion was ~fuzzy, for example:
There are notes: `note 1`, `second note`, `something different`. 
And `[[note` would lead to autosuggesting  _both_ `note 1` and `second note` (even though word `note` in second case is not the at the start).
Basically the way common search works, which is not the case for wikilinks. 

somewhat related to https://github.com/glushchenko/fsnotes/issues/663 and https://github.com/glushchenko/fsnotes/issues/402
