### ISSUE TITLE
FSNotes 4.9.11 is not universal binary (amd64 + aarch64)

### ISSUE THREAD

**Issue by akhenakh** [glushchenko/fsnotes#1106]
Hi, it seems recent version are not built universal
```
lipo -archs /Applications/FSNotes.app/Contents/MacOS/FSNotes 
x86_64
```

According to this https://github.com/glushchenko/fsnotes/issues/1031 4.9.3 was universal

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.9.12/FSNotes_4.9.12.zip

**Comment by akhenakh** [comment]
Thanks !!
