### ISSUE TITLE
Option for double click to open in the external editor

### ISSUE THREAD

**Issue by devon** [glushchenko/fsnotes#1107]
Right now, we can open external from Menu( File - Open external) and keyboard shortcut.

How about another way to do that: an option for double click on a note to open external.

**Comment by glushchenko** [comment]
Thanks, implemented.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.9.12/FSNotes_4.9.12.zip

**Comment by devon** [comment]
> https://github.com/glushchenko/fsnotes/releases/download/4.9.12/FSNotes_4.9.12.zip

It works.  Thanks a lot.
