### ISSUE TITLE
Support extracting title from YAML header metadata

### ISSUE THREAD

**Issue by jdcowf** [glushchenko/fsnotes#1108]
**Describe your feature request**
It would be nice if a note's title could be extracted from the YAML header information if "first line" is used otherwise the title of all notes using a YAML header is "---".

<img width="947" alt="Screen Shot 2021-04-15 at 9 48 51 AM" src="https://user-images.githubusercontent.com/8037859/114880429-0d7d3580-9dd0-11eb-81f8-b87bf496cfa5.png">

**Additional context**
Affects Mac & iOS

**Comment by glushchenko** [comment]
Implemented.
