### ISSUE TITLE
Spelling and Grammar Menu Item

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#111]
I have encountered two possible issues with the "Show Spelling and Grammar" menu item. The first happens when I do the following:

1) start or restart FSNotes;

2) in the note-list sidebar, select a note which contains a spelling error;

3) select the menu item "Show Spelling and Grammar";

After doing the above, the spelling dialog is shown but it doesn't appear to spell-check anything.

The second happens when I do the following:

1) start or restart FSNotes

2) in the note-list sidebar, select a note which contains a spelling error;

3) place the cursor in the selected notes' main window;

4) select the menu item "Show Spelling and Grammar";

5) when the spelling error is found, immediately exit the spelling and grammar dialog and click on a different note in the note-list sidebar;

6) select the menu item "Show Spelling and Grammar".

After doing the above, the spelling and grammar dialog still shows the spelling error found in the first-selected note. 

Thanks.

**Comment by glushchenko** [comment]
Checkout #109
