### ISSUE TITLE
FSNotes (GitHub) ignores preferences settings on system restart

### ISSUE THREAD

**Issue by joaoponceleao** [glushchenko/fsnotes#1110]
**Describe the bug**
FSNotes (installed via homebrew) ignores any custom setting in its preferences upon system restart or shutdown. This includes ignoring custom notes folder location, and it proceeds to creating a new folder in the user documents directory.

**To Reproduce**
1. Change folder for saving notes in FSnotes preferences to a custom folder in iCloud Drive.
2. Restart mac
3. Start FSNotes.
4. FSNotes ignores custom folder and returns all preferences to factory default, creating a new notes folder (FSNotes) in the user documents folder.

**Expected behavior**
The app should read the preferences.

**Actual behavior**
All customisation in preferences are ignored. This only happens after a restart / shutdown. When quitting and reopening the app, preferences are kept.

**Workaround**
Have not found any. Need to update preferences every time this happens. It is not reproducible 100% of the time but happens >80% of the time. This bug has been present in the last few months.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - FSNotes version: 4.9.11 (466)

**Additional context**
This happens when using the release from GitHub, installed via homebrew.

**Comment by glushchenko** [comment]
This is not FSNotes problem. Please look for the problem on your side
