### ISSUE TITLE
Having an easily accessible forum or mailing list

### ISSUE THREAD

**Issue by justauserid** [glushchenko/fsnotes#1111]
There's no official forum or, or a mailing list, or an IM channel like a matrix.org room (or even IRC). 

Though a forum would be best in my opinion. A mailing list could do as well (e.g. https://www.tarsnap.com/lists.html). 

As of now there's only one way to contact or ask for support and that is to email the author @glushchenko directly and I doubt he alone would find enough time to reply to such emails especially in a timely manner.

If having a forum isn't financially viable (though there are these - https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/) reddit can be used and the subreddit can be promoted maybe from the website and project `README.md` on Github as well. 

Currently clicking on "Help" on Mac app opens this link https://github.com/glushchenko/fsnotes/wiki and that tells how to install FSNotes (which has already been installed at this point).

**Comment by gingerbeardman** [comment]
This is an interesting question.

What type of support are you in need of, or envisaging? 
This will give us an idea of what might work best.

Most support requests come in here as issues, and are marked with the `question` tag.

**Comment by gingerbeardman** [comment]
Also, the Wiki contains far more than just the install guide. I've just give it a bit of a reorganisation to make that more clear.

**Comment by justauserid** [comment]
Quick doubts, setup issues, finding ways to do it, talking about people what is their setup, sharing something they did. 

Github issues might not be appropriate for these.

**Comment by gingerbeardman** [comment]
Maybe we can enable GitHub Discussions on the repo?

https://docs.github.com/en/discussions

**Comment by glushchenko** [comment]
Enabled https://github.com/glushchenko/fsnotes/discussions
