### ISSUE TITLE
Feature Request- Service to add note to FSNotes

### ISSUE THREAD

**Issue by macinmochis** [glushchenko/fsnotes#1113]
**Describe your feature request**
When browsing a page, it would be a great help to be able to highlight text and add it automatically as a new note in FSNotes using a right-click in the Services menu. It would save the extra steps of opening the app, and copying and pasting in a new note.

**Additional context**
Yojimbo on MacOS has this service, and it is a great time saver.

**Comment by macinmochis** [comment]
OK, found the Automator workflow to make this happen!
[Add.Selection.to.FSNotes.workflow.zip](https://github.com/glushchenko/fsnotes/files/6423854/Add.Selection.to.FSNotes.workflow.zip)

**Comment by gingerbeardman** [comment]
@macinmochis please check Wiki for this and more https://github.com/glushchenko/fsnotes/wiki/Services-(macOS)
