### ISSUE TITLE
Bold text next to a comma or period not rendering as bold.

### ISSUE THREAD

**Issue by mmerline** [glushchenko/fsnotes#1115]
<!— NOTE: ignoring this template will lead to your issue being dealt with more slowly —>

**Describe the bug**
Bold text next to a comma or period does not show as bold. For example, this text:

```
This is a test of *italics*, **bold text**, and `code`. Or bold text at **the end of a sentence**.

This is **bold text** located in the middle of a sentence.
```

Here’s how it looks in FSNotes Version 4.9.13 (468) on MacOS (and on iOS):

![Screenshot (2021-05-11 at 09 14 25)@2x](https://user-images.githubusercontent.com/1504420/117831842-97d38080-b23a-11eb-8a1c-5c3fef13b82c.png)

**To Reproduce**
Make text bold when next to a comma or period. This may apply to other characters as well.

**Actual behavior**
The text should be rendered as bold, but isn’t. For example, here’s the same text rendered in Marked.app instead:

![Screenshot (2021-05-11 at 09 16 59)@2x](https://user-images.githubusercontent.com/1504420/117831915-a6ba3300-b23a-11eb-974a-190eb9f36989.png)

**Workaround**
N/A

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 11.3.1 (20E241)
 - FSNotes version: Version 4.9.13 (468)

**Comment by glushchenko** [comment]
Thanks, fixed.

**Comment by mmerline** [comment]
> Thanks, fixed.

Thanks for the quick response! I'm a new user and really enjoying the app.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.10.0/FSNotes.zip

**Comment by mmerline** [comment]
Thanks. The 4.10.0 download above solved the issue as expected.

<img width="538" alt="Screen Shot 2021-05-16 at 2 58 59 PM" src="https://user-images.githubusercontent.com/1504420/118410869-41f64280-b657-11eb-80e9-94fc52b7a063.png">
