### ISSUE TITLE
open a file from tag view , can't jump to link normally

### ISSUE THREAD

**Issue by hqweay** [glushchenko/fsnotes#1116]
**Describe the bug**
If some .md files contain the same tag, and they quoted each other. When I try to jump to a link of the .md file that I choose from file list of the tag view, I can't jump to the right .md file(the link).

**To Reproduce**
1. create A.md contains tag 'X'
2. create B.md contains tag 'X', link A.md as [[A]] in B.md
3. click tag [[X]]
4. click B.md
5. click [[A]] -- now jump to 

**Expected behavior**
jump to A.md

**Actual behavior**
can't jump to A.md

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.2
 - FSNotes version: 4.9.13

**Additional context**
I record a video : https://www.youtube.com/watch?v=5FGxJWqTeRo

**Comment by gingerbeardman** [comment]
Latest FSNotes is 4.9.13

https://github.com/glushchenko/fsnotes/releases/latest

Please confirm that the issue still exists

**Comment by hqweay** [comment]
> Latest FSNotes is 4.9.13
> 
> https://github.com/glushchenko/fsnotes/releases/latest
> 
> Please confirm that the issue still exists

Thanks for your reply. I confirmed it in the latest version. And when I click a tag like #A/B in a note, I can't open it.

**Comment by glushchenko** [comment]
Fixed, thank you for bug report.

**Comment by hqweay** [comment]
> Fixed, thank you for bug report.

Thank you!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.10.0/FSNotes.zip
