### ISSUE TITLE
*.md format in iOS version create *.markdown file 

### ISSUE THREAD

**Issue by nixorg** [glushchenko/fsnotes#1118]
**To Reproduce**
1. Go to Settings and setup *.md format
2. Create any note
3. And check file extension of created file

**Expected behavior**
I expect *.md file created if I specify md in settings

**Actual behavior**
if I specify md file format in settings it create *.markdown files

**Desktop (please complete the following information):**
 - OS: iOS
 - OS version: 4.8.0

**Additional context**
If would be handy to add additional formats in settings as *.markdown, *.md

**Comment by glushchenko** [comment]
Thank you. Added 2 new options .txt and .md
