### ISSUE TITLE
Feature Request: Fountain file format

### ISSUE THREAD

**Issue by marlowe310** [glushchenko/fsnotes#112]
This app is outstanding thus far, can't tell you how much it's filling a gap in my workflow at the moment. 

The one thing that would make it perfect would be if it could display Fountain files (essentially markdown for screenwriting). Even without syntax highlighting, it would be great if they could just be recognized in the list of files -- viewing them as plain text would be fine (although syntax highlighting would be pretty stellar too!).

Is that a possibility? Thanks much!

**Comment by gingerbeardman** [comment]
Reference https://fountain.io

**Comment by gingerbeardman** [comment]
@marlowe310 to get Fountain syntax highlighting and styling in FSNotes, you need Fountain support in/for https://github.com/isagalaev/highlight.js

There are lots of resources of fountain-related highlighting and support in text editors that should make the work much easier - if you are interested in doing it. Fountain for TextMate or Sublime Text should port quite easily, for example.

**Comment by glushchenko** [comment]
Arrr, now i reproduced it. Will patch tomorrow.
