### ISSUE TITLE
Split View editor mode

### ISSUE THREAD

**Issue by bekemax** [glushchenko/fsnotes#1121]
**Describe your feature request**
It would be wonderful if FSNotes (at least the Mac OS app) had an option to open a split view editor!
IMHO, this would be helpful in two ways:
1. For those who are not very experienced in Markdown yet, so they don't have to toggle preview very often if they'r unsure what they are typing (so more people start using FSNotes maybe!)
2. When typing math formulae (thank you for MathJax support, btw, this is great!), if a formula is quite complicated, it is easier to "debug" it with a split view

I know one can just use any other MD editor, but having everything in FSNotes would be so much better.

Here's a note with a formula in FSNotes:
<img width="937" alt="FSNotes" src="https://user-images.githubusercontent.com/32070551/118817456-e4aefb00-b8bb-11eb-86e5-0413dea1ec2f.png">

Here it's open in another MD editor, there are options to toggle preview, or to open a split view
<img width="870" alt="OneMToggle" src="https://user-images.githubusercontent.com/32070551/118817480-eb3d7280-b8bb-11eb-8836-68ac81701245.png">

Here's the split view mode of that editor:
<img width="869" alt="OneMSplit" src="https://user-images.githubusercontent.com/32070551/118816945-605c7800-b8bb-11eb-88ab-6a6dba860e8e.png">

Yep, looks like this other editor doesn't support dark mode on the preview, and the formula delimiters are different – it uses $...$ instead of ((...)), so the first in-line formula doesn't render. 

**Additional context**
I suppose it makes more sense for the Mac OS version of the app, but maybe also the iPad one.

**Comment by bekemax** [comment]
Also, I believe, you can't use any other editor on an encrypted note

**Comment by A6669** [comment]
this is an important feature if you type Latex

**Comment by thehackermonkey** [comment]
This is a given on most markdown editors nowadays. Please consider adding it. 👍🏼

**Comment by glushchenko** [comment]
FSNotes 6 add multiple windows support. So now you can open one note in preview mode and edit it.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by bekemax** [comment]
Thank you for adding this! 🤩
I've tested editing one note in one window and previewing it in another – and it works! Changes in the source are updated quite swiftly in preview.

But, unfortunately, something got broken with math formula rendering for me:

<img width="1440" alt="Screenshot 2022-12-12 at 13 36 20" src="https://user-images.githubusercontent.com/32070551/207025021-71b83f67-b5cb-4541-b536-8b150f7adcd2.png">
