### ISSUE TITLE
Is there a better way of handling conflicts or synchronization?

### ISSUE THREAD

**Issue by wilhelmloof** [glushchenko/fsnotes#1122]
**Describe your feature request**
I am getting conflicts for notes. Even when I have made no changes on another device. Are the notes still seen as active or cached in some way on iOS devices that causes the desktop version to think that there is a conflict? There are differences in the files even if they are made on the same device (usually desktop). It's almost as if FSNotes is not syncing when closing and then gets conflicts when re-opening.
Prior to FSNotes, I used nvALT synced with Simplenote.com and I got no conflicts with that setup (and no missing data).
nvALT always did a forced synchronization when closing. I don't know if that's a good or bad idea.

### Compare function
One way to easier handle the recurrent conflicts would be to add a compare function. Preferably with a path setting for chosen compare app in settings, like `/usr/local/bin/bcompare` for Beyond compare. And then run it by selecting two notes and select 'Compare' from the right click menu, or via keyboard shortcut.

**Additional context**
macOS 10.14.6 and iOS 14.5 and storing notes in iCloud.

**Comment by glushchenko** [comment]
Auto merge was added
