### ISSUE TITLE
Why is there an iChat symlink in FSNotes folder?

### ISSUE THREAD

**Issue by wilhelmloof** [glushchenko/fsnotes#1123]
**Describe the bug**
Why is there an iChat symlink in FSNotes folder?

**To Reproduce**
```
username@machine.local:~/Library/Containers/co.fluder.FSNotes/Data/Documents
$ ls -la iChats 
lrwxr-xr-x  1 username  staff  31 19 Jul  2020 iChats -> ../../../../../Documents/iChats
```

**Comment by glushchenko** [comment]
This is part of macOS sandbox, i don't think that you should worried about.

**Comment by gingerbeardman** [comment]
More info: https://apple.stackexchange.com/questions/407270/mysterious-folders-that-appeared-in-documents-on-upgrade-to-big-sur

**Comment by wilhelmloof** [comment]
Thanks for you replies. I have never seen this before. Apple are usually quite tidy, is there any logic behind these files?

Is it safe to delete this file?

**Comment by gingerbeardman** [comment]
See this answer: https://apple.stackexchange.com/questions/407270/mysterious-folders-that-appeared-in-documents-on-upgrade-to-big-sur#comment568648_407787
