### ISSUE TITLE
Admonitions and Call Outs

### ISSUE THREAD

**Issue by mmerline** [glushchenko/fsnotes#1124]
<!— NOTE: ignoring this template will lead to your issue being dealt with more slowly —>

**Describe your feature request**
The addition of admonitions or “call outs” to the app’s default markdown syntax would make for more robust notetaking and wiki options. Here are how a few other notetaking apps and wiki systems define this feature:

> [Sublime Text [PlainNotes Package](https://packagecontrol.io/packages/PlainNotes)]
> When writing a note, you might need to distinguish a block or section by giving it a special title and box. These sections might appear several times in your document. Some examples would be Note, Tip or Caution blocks in an article.

> [[Markdeep](https://casual-effects.com/markdeep/)]
> Maruku + github + Admonition + CommonMark Markdown features: Admonitions (callout notes)

> [[MkDocs](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)]
> Admonitions, also known as call-outs, are an excellent choice for including side content without significantly interrupting the document flow. Material for MkDocs provides several different types of admonitions and allows for the inclusion and nesting of arbitrary content.
> Admonitions follow a simple syntax: a block must start with !!!, followed by a single keyword which is used as the type qualifier of the block and an optional title in quotes. The content of the block then follows on the next line, indented by four spaces. For example:
> ```
> !!! note
>    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
>    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
>    massa, nec semper lorem quam in massa.
> ```
> ```
> !!! note "Phasellus posuere in sem ut cursus"
>    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
>    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
>    massa, nec semper lorem quam in massa.
> ```

>[PyMdown Extensions]
>PyMdown Extensions is a collection of extensions for Python Markdown. They were originally written to make writing documentation more enjoyable. They cover a wide range of solutions, and while not every extension is needed by all people, there is usually at least one useful extension for everybody.

> [Paligo]
> Admonitions (sometimes called “safety messages” or “hazard statements” is an umbrella term used for the note, important, notice, caution, warning, danger and tip elements. You can add notes, warnings, tips, and other “admonition” elements to make parts of your content stand out. (Admonitions is the term for collectively describing all of the notes, warnings, tips, etc.).

**Additional context**
If implemented, I hope this would allow the same syntax usage across both OS apps.

**Comment by gingerbeardman** [comment]
FSNotes uses [CommonMark](https://commonmark.org) so your issue will need to be filed there.

**Comment by mmerline** [comment]
> FSNotes uses [CommonMark](https://commonmark.org) so your issue will need to be filed there.

I'll look into submitting a similar request to the CommonMark spec.

**Comment by gingerbeardman** [comment]
A quick shared showed numerous requests for both, perhaps even an extension for one or the other (but not both)

**Comment by mmerline** [comment]
@gingerbeardman Just as a heads up, I did fill out [a CommonMark issue](https://github.com/commonmark/commonmark-spec/issues/679) about this topic, but it was closed immediately to push me to the extensions forum. Unfortunately, I noticed the same recurring complaints in those threads about added syntax; it's probably not going to happen.

That's not to say FSNotes needs to implement anything that's off-spec, but I don't think CommonMark will adapt this suggestion anytime soon.

**Comment by gingerbeardman** [comment]
Ah, I thought that might be the case. 

Did you find an extension for either?

**Comment by mmerline** [comment]
> Did you find an extension for either?

I assume it's not possible to integrate this into FSNotes, but MarkDeep might work for some of my publishing use-cases. The CMS my employer uses doesn't seem to want to cooperate with Markdeep as another layer on top of its own internal CSS and content styling.
