### ISSUE TITLE
Show storage folder name before title in edit window

### ISSUE THREAD

**Issue by wilhelmloof** [glushchenko/fsnotes#1127]
**Describe your feature request**
It would be handy if there was a setting for displaying storage name before title in the top of the edit window. Similar to Finder where you can choose to display folder path.

Now it looks like this 'Note title', but it would be convenient if it could be displayed something like this: 'Folder/Note title'. One step down might be sufficient.

I have several folders and I am constantly showing in Finder just to verify in which folder I am working.

**Comment by gingerbeardman** [comment]
Related: #188 which I still wish for every single day

**Comment by wilhelmloof** [comment]
Examples of possible solutions:

![FSNotes-Folder_in_title-v1](https://user-images.githubusercontent.com/71853350/119339096-1267bb80-bc91-11eb-97a8-77d69cfe57a3.png)

![FSNotes-Folder_in_title-v2](https://user-images.githubusercontent.com/71853350/119339093-11368e80-bc91-11eb-9a3c-62bed1912644.png)

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1
