### ISSUE TITLE
Losing pinned notes when opening them in another application

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#1128]
**Describe the bug**
When I pin a note but then open it in another application, when I quit and reopen FSNotes that note is no longer pinned.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.4
 - FSNotes version: 4.10

**Comment by glushchenko** [comment]
Application from the mac app store or github?

GitHub version uses Extended Attributes for saving pin data. This may be cause of data loose, if another app drops this data.

**Comment by gingerbeardman** [comment]
@volt4ire what other application are you using? I can look into what is happening.

**Comment by volt4ire** [comment]
> @volt4ire what other application are you using? I can look into what is happening.
@gingerbeardman @glushchenko Thanks so much! I'm using the GitHub version

**Comment by gingerbeardman** [comment]
@volt4ire what application are using to open the note outside of FSNotes?

**Comment by volt4ire** [comment]
Thanks! I use a variety of other apps to edit these notes, including a Drafts action and IAwriter on macOS, both of which come through the Mac App Store; as well as Sublime 4, VS Code, Logseq, Obsidian, and QOwnNotes on both Linux and macOS. Also I should note the notes in question are in a synced Dropbox folder, and I edit them in a few iOS and Android apps such as 1Writer, Drafts, and Markor, so I'm not sure if those could contribute to the issue

**Comment by volt4ire** [comment]
> Dropbox is the issue, it only syncs certain xattr (Extended Attributes) so the one FSNotes uses for pin status is discarded.

Thanks for this explanation! I don't have any desktop app development experience so I'm not sure how feasible this would be, but would it be possible to have FSNotes write out the file names and/or UUIDs in a separate location like a database or plist file that it reads from to keep track of favorites besides/in addition to using Extended Attributes? Thanks!

**Comment by gingerbeardman** [comment]
Possible.

Though perhaps that goes against FSNotes philosophy of being just the app and your text notes.

Also, FSNotes already works as designed with iCloud on macOS and iOS. 

The loss of xattr is a Dropbox problem. Maybe ask them to support all xattr?

I'm interested to hear @glushchenko opinion as the creator of FSNotes.

**Comment by glushchenko** [comment]
Hi, guys!

Finally i'm here. xattr not reliable therefore it was removed for non cloud FSNotes version. Now data stored in local storage.

And in iCloud for Mac App Store FSNotes version.

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by volt4ire** [comment]
Awesome thank you so much – this fully version addressed my issue!!
