### ISSUE TITLE
Delete Note - Command + DEL do not work

### ISSUE THREAD

**Issue by lrzuniga** [glushchenko/fsnotes#1129]
**Describe the bug**
When trying to delete a note using keyboard COMMAND+DEL, note does not get deleted

**To Reproduce**
1. Go to a note
2. Click on a note
3. click and hold command + del key

**Expected behavior**
note deleted

**Actual behavior**
note not deleted

**Workaround**
right click on note and select delete from popup menu

**Supporting Files**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.4
 - FSNotes version:  4.10.1 (471)

**Additional context**
tried command + backspace, no joy

**Comment by glushchenko** [comment]
If checked "Focus in editor when selecting note" in Preferences -> Editor you should use "⌘ + option + delete" shortcut.
