### ISSUE TITLE
Substitutions > Smart Copy/Paste is not in sync between Context and Edit menus

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1132]
**Describe the bug**
Substitutions > Smart Copy/Paste is not in sync between Context and Edit menus

**To Reproduce**
1. Right click in note to show context menu > Substitutions
1. Choose Edit menu > Substitutions

**Expected behavior**
- options/selections should be the same

**Actual behavior**
- options/selections are different
- Smart Copy/Paste is active in Edit menu, but not Context menu

**Supporting Files**

Context menu
<img width="400" alt="Screen shot 2021-06-07 at 16 18 29" src="https://user-images.githubusercontent.com/49612/121043521-9e5b0680-c7ac-11eb-9d6f-f22adfcb2fa5.png">

Edit menu
<img width="415" alt="Screen shot 2021-06-07 at 16 19 26" src="https://user-images.githubusercontent.com/49612/121043545-a2872400-c7ac-11eb-9342-5745347e5ea7.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.4 (20F71)
 - FSNotes version: 4.10.1 (471)

**Additional context**

**Comment by glushchenko** [comment]
Trying reproduce without success:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/1089917/121772123-2d389c00-cb7c-11eb-84fe-d551cfbfd7cd.png">

<img width="282" alt="image" src="https://user-images.githubusercontent.com/1089917/121772130-3590d700-cb7c-11eb-8eb1-b2fbb1d3c6c2.png">

**Comment by gingerbeardman** [comment]
1. Toggle in Edit menu
2. Restart FSNotes
3. Look
   - Edit menu is still checked
   - Context Menu is not checked

**Comment by glushchenko** [comment]
Seems i understand "problem". when you restart app first responder is SearchTextField with custom Edit menu settings. Try to focus in EditTextView and check this settings :)

**Comment by gingerbeardman** [comment]
Yes, you're correct! 

So, everything works OK.
