### ISSUE TITLE
Scrollbar for sidebar cannot be hidden

### ISSUE THREAD

**Issue by anthonyesau** [glushchenko/fsnotes#1133]
**Describe the bug**

The scrollbar for the sidebar cannot be hidden and remains in view even when the sidebar itself is hidden.

**To Reproduce**

1. With the sidebar visible, click the right vertical edge of it (the line that separates it from the note content) and drag to the left to the boundary of the FSNotes window. 

Hiding the sidebar via the menu command View > Hide/show sidebar leaves the scrollbar visible as well.

The issue persists after quitting and then reopening FSNotes.

**Expected behavior**

The sidebar along with the scroll bar for it should be hidden completely.

**Actual behavior**

The scroll bar remains in view at the left edge of the window.

**Workaround**
Uninstalling FSNotes and then reinstalling seems to allow the scrollbar to be hidden via View > Hide/show initially but it quickly has the same issue when hiding and showing the sidebar. So not a reliable workaround.

**Supporting Files**

![Screen Shot 2021-06-09 at 8 14 33 AM](https://user-images.githubusercontent.com/11262546/121362168-880f9080-c8fb-11eb-9cf3-0528a78a5010.jpg)

![Screen Shot 2021-06-09 at 8 14 40 AM](https://user-images.githubusercontent.com/11262546/121362216-9198f880-c8fb-11eb-9ea3-a51c41814dd5.jpg)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.3.1
 - FSNotes version: 4.10.1 (471)

**Comment by glushchenko** [comment]
This is not on FSNotes side. Please check system settings.

![image](https://user-images.githubusercontent.com/1089917/121769473-741e9580-cb6c-11eb-86a0-209186b1acd6.png)

**Comment by anthonyesau** [comment]
Ah. Setting Show scroll bars to "When scrolling" fixed the issue. 

I was having the issue when it was set to "Automatically based on mouse or trackpack" by default, and the issue returns when set to that again. The scrollbars were always visible in FSNotes with that setting which doesn't quite seem like the intended behavior so maybe the OS has a problem.

I hadn't noticed the sidebar scrollbar issue in earlier versions of FSNotes so thought it was a bug that had popped up but also don't show/hide the sidebar all too often. Thanks for your help!
