### ISSUE TITLE
Encrypted note renames itself when opened on iOS app

### ISSUE THREAD

**Issue by markmonroy** [glushchenko/fsnotes#1134]
Experiencing a minor, repeatable bug on an encrypted note in iCloud Drive. The file is named Journal 2021.etp. If I open it on my Mac, everything works as expected. If I open it on iOS, the filename immediately changes to "Sunday March 14 2021" which is the first line of the file.

https://user-images.githubusercontent.com/32033503/121679055-f1230f80-ca85-11eb-8b3c-8fceaeb613ae.mov

**Comment by glushchenko** [comment]
What in Setting - Files naming? UUID?

**Comment by markmonroy** [comment]
Yes, UUID.

**Comment by glushchenko** [comment]
OK, i will try to reproduce it ASAP

**Comment by glushchenko** [comment]
Files naming in macOS app same? UUID?

**Comment by markmonroy** [comment]
Apologies, UUID WAS the Mac App. In the iOS app it’s set to Auto Rename By Title. I assume I should go ahead and set them both to UUID?

**Comment by glushchenko** [comment]
> Apologies, UUID WAS the Mac App. In the iOS app it’s set to Auto Rename By Title. I assume I should go ahead and set them both to UUID?
> 
> 
> > On Jun 11, 2021, at 12:07 PM, glushchenko ***@***.***> wrote:
> > 
> > ﻿
> > Files naming in macOS app same? UUID?
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Definitely

**Comment by markmonroy** [comment]
Got it, thanks. Did that, now my encryption password is not working. Hmm.

**Comment by markmonroy** [comment]
Restored from backup and all is well! Thanks, this can be closed.
