### ISSUE TITLE
Not possible to drag main window by toolbar when scrolled down in sidebar

### ISSUE THREAD

**Issue by CarlMangno** [glushchenko/fsnotes#1136]
**Describe the bug**
When one scrolls downward in the sidebar by any amount, it is no longer possible to move the main window by dragging on the top toolbar near the traffic light buttons .

**To Reproduce**
1. Scroll down in the sidebar by even the smallest amount
2. Click on the toolbar near the traffic light buttons and attempt to move the main window.

**Expected behavior**
It should be possible to drag the main window by the toolbar at all times.

**Actual behavior**
It is not possible to drag the main window by the toolbar when one is scrolled down in the sidebar.

**Workaround**
1. Scroll up in the sidebar to the top so that "Inbox" is visible. It is then possible to drag the window by the toolbar.
OR
2. Drag the main window by the right-hand side of the toolbar

**Supporting Files**
<None>

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - OS version: 11.3 (20E232)
 - FSNotes version: 4.10.1 (471)

**Additional context**
<None>

**Comment by gingerbeardman** [comment]
Confirmed, thanks for reporting!

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by CarlMangno** [comment]
Excellent! It appears to have fixed two problems. It is now always possible to drag the application by the title bar, and also nested sub-folders collapse nicely. I will continue to use it and let you know if any stability problems show up.

Thank you,
Charles
