### ISSUE TITLE
Can not render assets like Image with space in name , Audio-Video Files

### ISSUE THREAD

**Issue by Genxster1998** [glushchenko/fsnotes#1137]
**Describe the bug**
I imported by notes from Android App One Jotter which supports textbundle format . But FSNotes seems to fail render images with space in their name in assets .Also it cant allow a preview or link to open audio-video files in Notes at same time.

**To Reproduce**
1. Go to 'Finder'
2. Click on 'textbundle file'
3. Load it in Fsnotes

**Expected behavior**
Allow spaces in assets file names , allow playback button for audio-video files via external app or just offer to open content URI .

**Actual behavior**
Just plane link to assets file unable to render
**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.10.1

**Additional context**

**Comment by gingerbeardman** [comment]
Confirmed, thanks for reporting!

**Comment by glushchenko** [comment]
Hi, please provide textbundle example.

**Comment by glushchenko** [comment]
Feel free to open again with attached example.
