### ISSUE TITLE
Wrong appearance with codeblocks, dark mode, macOS

### ISSUE THREAD

**Issue by wagaaa** [glushchenko/fsnotes#1138]
**Describe the bug**
Code blocks does not appearing properly

**To Reproduce**
1. Input a code block
2. Turn on dark mode

**Actual behavior**
Words are not clear

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 3.8.2
<img width="773" alt="截屏2021-06-22 下午7 57 54" src="https://user-images.githubusercontent.com/13414470/122920592-24be3d80-d394-11eb-9a1e-a43a13768d65.png">

**Comment by wagaaa** [comment]
The block theme is **monokai-sublime**. 
It appears normally when changed to other themes.

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1
