### ISSUE TITLE
Labeling system. In some cases, the label cannot be found, and the world label cannot be found if there is a label.

### ISSUE THREAD

**Issue by AiPacino** [glushchenko/fsnotes#1141]
tag system. In some cases, the tag cannot be found, and the world tag cannot be found if there is a tag.

demo:

- [ ] hello world #user test

	this is #world test

**Comment by gingerbeardman** [comment]
Confirmed

**Comment by glushchenko** [comment]
Interesting but can not reproduce.

**Comment by glushchenko** [comment]
Can you reproduce it dev build?

https://github.com/glushchenko/fsnotes/releases/tag/5beta1
