### ISSUE TITLE
Dropping images into the editor inserts newlines elsewhere

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1142]
**Describe the bug**

When an image is dragged onto the editor, two newlines are inserted at the last cursor position, instead of at the drop point.

**To Reproduce**

https://user-images.githubusercontent.com/645412/124350678-4e7a2e80-dbf6-11eb-8808-801aed00498f.mp4

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.10.2

**Fix**

[EditTextView.swift](https://github.com/glushchenko/fsnotes/blob/9ea03d54f2a734f7b8367efd331c94c4fe73dd4d/FSNotes/View/EditTextView.swift#L1412)
```swift
insertText("![](\(filePath))", replacementRange: insertRange)
insertNewline(nil)
insertNewline(nil)
```

Probably the `insertNewline` should also be given the `insertRange` somehow.

**Comment by glushchenko** [comment]
Thank you @tewe. Fixed!

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by tewe** [comment]
The beta removes the newlines completely, which works for me.
