### ISSUE TITLE
FSNotes 5 Roadmap

### ISSUE THREAD

**Issue by glushchenko** [glushchenko/fsnotes#1143]
Hi, guys. I want to share some minds about FSNotes (macOS) future.

As you can see, past couple weeks i commits without any releases. At this moment inplemented most requested features:

1) #188
2) #774
3) #1127
etc.

When this all will be available? Beta releases from 11.07.2021

Before stable i want implement as many tasks as possible. 

Stable release end of August not later than 1.09.2021

Any suggestions are appreciated 🖖

Current progress: https://github.com/glushchenko/fsnotes/projects/2
Dev branch: https://github.com/glushchenko/fsnotes/pull/1144

**Comment by glushchenko** [comment]
Beta 1 https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by glushchenko** [comment]
Beta 2 https://github.com/glushchenko/fsnotes/releases/tag/5b2

**Comment by gingerbeardman** [comment]
Some thoughts:

- I often press escape to deactivate text selection, especially when using column select mode. Here Escape sends me back to search field.
- Should "FSNotes" parent folder be in the side bar? Seems redundant?

**Comment by gingerbeardman** [comment]
If I have FSNotes parent folder highlight that means search does not find items in sub folders. Obviously it should find matches in all sub folders.

**Comment by glushchenko** [comment]
@gingerbeardman https://github.com/glushchenko/fsnotes/releases/download/5beta3/FSNotes_v5beta3.zip

Please recheck #813, this working for me.

> I often press escape to deactivate text selection, especially when using column select mode. Here Escape sends me back to search field.
> Should "FSNotes" parent folder be in the side bar? Seems redundant?

Fixed

**Comment by gingerbeardman** [comment]
All good

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5beta4

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5beta5

**Comment by gingerbeardman** [comment]
Request
- I open FSNotes with URL scheme from a search
- There is only one match
- File should open

Currently
- app opens with focus is in search and one result

**Comment by glushchenko** [comment]
@gingerbeardman fixed, thanks

**Comment by glushchenko** [comment]
Final beta https://github.com/glushchenko/fsnotes/releases/tag/5beta6

**Comment by glushchenko** [comment]
Release day https://github.com/glushchenko/fsnotes/releases/tag/5

**Comment by gingerbeardman** [comment]
Congrats! Phenomenal work, well done. 👏
