### ISSUE TITLE
Inconsistent behavior of 'Notes' in navigation

### ISSUE THREAD

**Issue by wilhelmloof** [glushchenko/fsnotes#1145]
**Describe the bug**
When pressing 'Notes' it shows notes from all folders. That's great. And if you search, results are shown for all folders, BUT when you remove the search terms 'Notes' shows only the notes from 'Inbox'. Expected behavior would be to still show all notes when 'Notes' is marked in navigation.

**Comment by gingerbeardman** [comment]
Confirmed

**Comment by glushchenko** [comment]
This is not a bug, but a feature.

**Comment by glushchenko** [comment]
Search only in inbox is not interesting to anyone.

**Comment by wilhelmloof** [comment]
How can this non logical behavior be a feature? When selecting a function in a program you expect it to display just that. Now, when standing in Notes and after clearing the search field I have to select something else and then select Notes again to view all notes.

Yes I would prefer Notes to be the default view and preferable place it on top. All notes (Notes) are more valuable than the few unsorted in Inbox.

Another thing. What's the keyboard short cut for clearing the search field? Alt Cmd L would be nice.

**Comment by glushchenko** [comment]
Inbox was removed, you can use folders instead. 

> Another thing. What's the keyboard short cut for clearing the search field?

ESC

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by wilhelmloof** [comment]
> Inbox was removed, you can use folders instead.

Ok, I think that's a good change. Coming from nvALT, I was very confused with the Inbox folder and how to use it.
Most users will probably not use an intermediate step for creating notes. And if they would need that, they can create a folder called Inbox/Unsorted etc. 

> > Another thing. What's the keyboard short cut for clearing the search field?
> 
> ESC

Ah, I know that one 😀, my bad. I was a bit unclear. I am interested in a short key to clear the search results and **keep standing in the active note**. Actually this would be my preferred use of pressing ESC in fsNotes. If not possible, then Alt + ESC. Sorry for sidetracking this bug-report.
