### ISSUE TITLE
Diacritic characters omitted from search field

### ISSUE THREAD

**Issue by wilhelmloof** [glushchenko/fsnotes#1146]
**Describe the bug**
Diacritic characters get's omitted (removed by FSNotes) or displayed wrong when searching for notes with that search term only in the filename (my old nvALT notes has titles in the filename). But search usually works correctly when those search terms with diacritical characters are added to the note (it seems like FSNotes prioritizes filename in search).

For me, this bug only occurs with diacritic characters. In my case `åäöÅÄÖ`. For example the character 'ö' (Unicode dec 246) when not omitted can be displayed as 'ö' with an extra pair of diaeresis on top. Looks strange. See attached image, with the wrong 'ö' on the left and a normal 'ö' on the right. 
![Skärmavbild 2021-07-08 kl  12 28 45](https://user-images.githubusercontent.com/71853350/124907286-3f292580-dfe8-11eb-85a2-04fb3a1c4be9.png)

**Other**
glushchenko, don't be let down by all my bug reports. I think FSNotes is really great, the next step after nvALT. And I wish FSNote will grow and just get better and better.

**Comment by glushchenko** [comment]
Let me know if this is still relevant, everything seems to be working now for me.

**Comment by wilhelmloof** [comment]
I just tested this issue with FSNotes 5.3.9 and diacritic characters no longer gets omitted or replaced. BUT false positives remains. In other words searching for `åäö` also searches for `aao`. `Åäö` are unique characters and their umlauts/dots should not be treated as add-ons like accents. There are probably similar problems for other languages in FSNotes.
