### ISSUE TITLE
v. 5 beta 1 -- Feedback after removing Inbox and more

### ISSUE THREAD

**Issue by wilhelmloof** [glushchenko/fsnotes#1147]
**Describe the bug**
It's a little bit unclear where new notes are stored when Inbox is removed. After testing 5b1 I found that new notes are stored in `~/Library/Containers/co.fluder.FSNotes/Data/Documents/`
New notes are harder to find when Inbox is removed, but that could be solved and at the same time solve another logical problem. 
'Documents' was a bit unclear to me in the beginning (and I would like to read a more detail explanation for it), but with nested folders it gets clearer. To keep 'Documents' more unique and clear I think 'Documents' should **not** list all notes from all locations. Preferably should 'Documents' only list files below that level. This will also clear up the confusion of storage location, to keep the different locations separate:
'Documents' = `~/Library/Containers/co.fluder.FSNotes/Data/Documents/`
'FSNotes' = `~/Library/Mobile Documents/iCloud~co~fluder~fsnotes/Documents`

Likewise 'FSNotes' should preferably not list notes from 'Documents', but of course should search find notes from any location.

Better highlighting when searching. When selecting a note in the search list, it would be easier to navigate if the note's folder also was highlighted at the same time.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5b2/FSNotes_v5b2.zip

**Comment by wilhelmloof** [comment]
> https://github.com/glushchenko/fsnotes/releases/download/5b2/FSNotes_v5b2.zip

Thanks for the update.

* But now folders in sidebar only lists files from that level. It would be more intuitive if each folder showed all files from that level and below (including files in folders below).

* In v5b2 search only finds files in selected folder, it would be preferred if search found files anywhere within fsNotes.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5beta3/FSNotes_v5beta3.zip
