### ISSUE TITLE
Issue when dragging a note with the mouse

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#1148]
**Describe the bug**
Two cosmetic issues are encountered when moving a note from one folder to another with the mouse.

**To Reproduce**
1) Create Test Folder 1 and Test Folder 2.
2) In Test Folder 1 create a new note named Test Note.
3) With the mouse, drag Test Note from Test Folder 1 to Test Folder 2.

After doing the above, Test Note is still shown in Test Folder 1 even though it has been moved to Test Folder 2. Also, when dragging the note to Test Folder 2, the cursor contains a "+" which would seem to indicate the note is being copied rather than moved.

**Expected behavior**
After being moved, the note should not be shown in Test Folder 1. While the note is being moved, the "+" symbol should not be shown with the cursor.

**Actual behavior**
After being moved, the note is shown in Test Folder 1. While the note is being moved, the cursor shows a "+" symbol.

**Workaround**
Restart FSNotes or change the focus to another folder and back. After doing this, Test Note is no longer shown in Test Folder 1. I don't know of any workaround for the "+" symbol.

**Supporting Files**
N/A

**Desktop (please complete the following information):**
macOS 10.15.7
FSNotes 5b1

**Additional context**
None

**Comment by glushchenko** [comment]
Nice catch @peavine Fixed.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5b2/FSNotes_v5b2.zip

**Comment by peavine** [comment]
I installed FSNotes 5b2 and this issue is fixed. Thanks.
