### ISSUE TITLE
Use first line as title

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#1150]
**Describe the bug**
I have disabled the option to "Use first line as title" yet new notes created with the "Search and create" bar contain the title of the note.

**To Reproduce**
1) In FSNotes preferences, uncheck "First line as title"
2) In Folder > Show View Options, uncheck "Use first line as title"
3) Place the cursor in the Search and create bar,  type "Note xxx", and select the return key.

After doing the above, the newly-created note contains "# Note xxx" in the notes first line.

**Expected behavior**
The first line of the created note should be blank

**Actual behavior**
The first line of the created note contains the note title

**Workaround**
Manually delete first line of created note

**Supporting Files**
None

**Desktop (please complete the following information):**
macOS 10.15.7
 FSNotes version: 5b1

**Additional context**
None

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5b2/FSNotes_v5b2.zip

**Comment by peavine** [comment]
I installed FSNotes 5b2 and this issue is fixed. Thanks.
