### ISSUE TITLE
can't edit a previously entered note 

### ISSUE THREAD

**Issue by MTOLincoln** [glushchenko/fsnotes#1151]
**Describe the bug**
I went to revisit and add to a note previously entered in FSNotes. Could not enter new text into the note. ??  
**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 11.4
 - FSNotes version: 4.10.2

**Additional context**

**Comment by glushchenko** [comment]
View -> Toggle preview 

<img width="652" alt="image" src="https://user-images.githubusercontent.com/1089917/126068679-4bce9a88-da91-4305-8204-338e4d0c9b7d.png">

**Comment by glushchenko** [comment]
Or just press enter from notes list
