### ISSUE TITLE
Sync with other services

### ISSUE THREAD

**Issue by juev** [glushchenko/fsnotes#1152]
Hello!

**Describe your feature request**
In this time fsnotes can sync notes across iCloud and Dropbox only. And only iCloud on iOS.

I use Syncthing for synchronize my files. Is it possible to use local folder on my iOS device for storing notes? I cannot find setting for storing my notes.

**Additional context**

No additional context

**Comment by glushchenko** [comment]
Settings -> Apple ID -> iCloud -> FSNotes Off

But I don't recommend using FSNotes offline, it just doesn't make sense. Filesystem events do not work in iOS.

**Comment by juev** [comment]
Ha-ha!

But how I can change folder for storing my notes?
