### ISSUE TITLE
Zettelkasten note title

### ISSUE THREAD

**Issue by juev** [glushchenko/fsnotes#1153]
**Describe your feature request**
As I can see, fsnotes on my iOS device storing notes with filename as <UUID>.md

Is it possible to use Zettelkasten method?

<datetimeseconds> headline.md

**Additional context**

no additional context

**Comment by glushchenko** [comment]
I dont know what is "Zettelkasten method", but you can enable automatic renaming files by title. Settings -> Files naming -> Auto rename by title.

**Comment by juev** [comment]
Why i don't see this option?

![A241DE15-CB55-49DE-B534-C9EDD3950085](https://user-images.githubusercontent.com/114635/126117736-5dee6d73-d9d6-48f7-a87e-dbfefb7ae083.jpeg)

**Comment by glushchenko** [comment]
@juev 
![IMG_4612](https://user-images.githubusercontent.com/1089917/126784130-93377e0b-d510-4e41-85e0-cd35cedcff2f.jpeg)

**Comment by juev** [comment]
It’s not clearly. You don’t have button for open this sidebar. I need to reed docs for using you program. It not simple. :( 

Thank you.

**Comment by glushchenko** [comment]
Sidebar is opened by default
