### ISSUE TITLE
Selected Folder and Note not remembered on reboot

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#1154]
**Describe the bug**
The folder and note selected in the sidebar is not remembered after a reboot.

**To Reproduce**
1. Load FSNotes and select a folder in the sidebar and a note in the Note List
2. Exit FSNotes
3. Reboot the computer
4. Load FSNotes

**Expected behavior**
The previously-selected folder and note should be highlighted.

**Actual behavior**
The previously-selected folder and note are not highlighted, and the top-level folder which contains all subfolders is not expanded.

**Workaround**
Manually expand the folder in the sidebar and select the note

**Supporting Files**
None

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - FSNotes version: 5b2

**Additional context**
None

**Comment by glushchenko** [comment]
Nice! Fixed

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5beta3

**Comment by peavine** [comment]
I installed FSNotes 5 beta 3 and this works fine. Thanks.
