### ISSUE TITLE
Full Screen mode margin too large

### ISSUE THREAD

**Issue by CoelWu** [glushchenko/fsnotes#1155]
**Describe the bug**
When  the app is in normal size, the margin looks fine.
![image](https://user-images.githubusercontent.com/76829607/126262102-8251c2af-4f72-4742-8348-718d18dfc920.png)
However when the app enters full screen mode, the margin becomes extremely large.
![image](https://user-images.githubusercontent.com/76829607/126262158-757bbbcb-7563-4f97-be24-27c7b07da168.png)

**To Reproduce**
1. Type some text in the text area
2. Click Maximize Button
3. The margin before ``This is a test`` is extremely large

**Expected behavior**
A fixed margin before text area

**Actual behavior**
A larger margin before text area

**Workaround**
I would suggest to make the margin a constant instead of following window size

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - OS version: 11.4
 - FSNotes version: 4.10.2 (472)

**Additional context**

**Comment by glushchenko** [comment]
Preferences -> Editor -> Margin size -> 0 ?

**Comment by CoelWu** [comment]
> Preferences -> Editor -> Margin size -> 0 ?

I tried to set ``Margin size`` to 0, however the problem still exists

**Comment by glushchenko** [comment]
Margins is constants by default. You must provide more details.
