### ISSUE TITLE
Allow "'" in tags

### ISSUE THREAD

**Issue by MTOLincoln** [glushchenko/fsnotes#1157]
**Describe your feature request**
I'd like to be able to include ' [apostrophe] in defining tags. As in  #O'Brien or #Freud's 
**Additional context**
In taking notes on Sigmund Freud's theory, for example, I might want to use the following tags: #Freud #dreams #Freud's_own, which would let me retrieve not just what Freud said about dreams (in general) but what he said about one of his own dreams, in particular. 
Add any other related information here. macOS or iOS?  either

**Comment by gingerbeardman** [comment]
Technically these are not valid characters for hashtags

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/tag/5beta6

**Comment by MTOLincoln** [comment]
Thank you. Makes a significant difference for me.

Mike

**Comment by MTOLincoln** [comment]
Hi,

Was just editing some notes, and experimented with the setting to view the note summary on the top or side.  I had them on the side. Changed the checkbox to put them above.   And then all my notes promptly disappeared. Couldn’t see any of them anymore.

I don’t think they’re gone. I suspect the issue is just with the interface. But, could you help me get back to a situation where I can see my notes again?

I tried exiting and re-starting. That did not change anything.

Thanks.

Mike O’Brien

**Comment by glushchenko** [comment]
@MTOLincoln where did you keep your notes?

**Comment by MTOLincoln** [comment]
In iCloud.

Mike

**Comment by glushchenko** [comment]
@MTOLincoln is default storage as on screen?

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1089917/207652571-238872b1-70b8-4437-800a-998724ef1eda.png">

**Comment by MTOLincoln** [comment]
Yes

**Comment by glushchenko** [comment]
@MTOLincoln did you try View -> Show notes list? Or just try to move left window bezel.

**Comment by MTOLincoln** [comment]
Yes, and I have a dozen folders within iCloud/FSNotes. And my notes are all still there. I can read them in Finder.

**Comment by glushchenko** [comment]
@MTOLincoln then i dont know, try to reset settings https://github.com/glushchenko/fsnotes/wiki/Preferences-location

**Comment by MTOLincoln** [comment]
OK now.

This is what I did: went to full screen, then slid my cursor around, and then everything came back into proper view.

There’s something different about how the visuals behave in FSNotes, but I can’t put my finger on it yet.  But I’m good for now.

Thank you for your quick response and help.   

Mike O’Brien
