### ISSUE TITLE
truncating imported entries

### ISSUE THREAD

**Issue by rfouldes** [glushchenko/fsnotes#1158]
I just tried to use the iPhone app, (I'm going to try again using osx app now) to import my notational velocity backup (all text) and i noted that some of the entries had been truncated, losing the last 1-2 lines of info.  i didn't check throughly, bu intend to repeat the import on my mac now, as I really want the app to work well, I've been tied to simplenote / notation velocity for years now, and crave for somethign fast and table that sync across mac and iPhone...  and with a securable note option - what's not to love!

**Comment by glushchenko** [comment]
Let me know when you figure out how to reproduce the problem.

**Comment by rfouldes** [comment]
Thanks for quick response, sorry, checking source, the problem was in my import, which was itself in error (I have a few copies of same thing - NV and Simplenote) so I think I must have copied from wrong source, my mistake , sorry

Robert

Robert

**Comment by glushchenko** [comment]
No problems, Robert. Welcome!
