### ISSUE TITLE
Prefers image pasteboard types over text

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1159]
**Describe the bug**
When copying text from PowerPoint, FSNotes will paste it as an image.

**To Reproduce**
1. Create a blank presentation in Microsoft PowerPoint (tested with 16.51)
2. Enter some text
3. Select & copy the text
4. Open a Markdown note in FSNotes
5. Paste

**Expected behavior**
The copied text is pasted into the note, without any formatting.

**Actual behavior**
An image link to a JPEG "screenshot" of how the text looked in PowerPoint is inserted into the note.

**Workaround**
6. Paste into TextEdit
7. Select & copy
8. Paste into FSNotes

**Supporting Files**

![Clipboard Viewer 2021-07-28 at 18 38 56](https://user-images.githubusercontent.com/645412/127389387-ab7907fe-3250-4545-9d8e-95afda4e945f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.5
 - FSNotes version: 4.10.2

**Additional context**

[EditTextView](https://github.com/glushchenko/fsnotes/blob/4.10.2/FSNotes/View/EditTextView.swift#L576) always tries to paste as an image first, so this will affect any app that places multiple types on the pasteboard.

**Comment by glushchenko** [comment]
Fixed, thanks.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5beta4

**Comment by tewe** [comment]
Works for me
