### ISSUE TITLE
Alignment of list and search box

### ISSUE THREAD

**Issue by kaapow** [glushchenko/fsnotes#116]
For some reason the edge of the search box is not aligned with the edge of the text in the list. Now that I’ve seen it I can’t under it, just needs to move over by a few pixels

**Comment by glushchenko** [comment]
I think bug fixed in new ui.

**Comment by jeff-h** [comment]
While we're talking about alignment surely the elephant in the room is the fact that the top elements in each of the three columns don't line up (when in three-col layout) 🙂 Note area coloured green to make what I'm talking about more obvious.

![screen shot 2018-06-27 at 6 07 11 pm](https://user-images.githubusercontent.com/841871/41955663-09897f72-7a35-11e8-92b5-d0f95ae3f2dc.png)
