### ISSUE TITLE
Pasting images applies lossy compression

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1160]
**Describe the bug**
Any pixel data gets turned into JPEG when pasted.

**To Reproduce**
1. Hit ⌃⇧⌘3 to copy a picture of the screen to the clipboard
2. Open a Markdown note in FSNotes
3. Paste

**Expected behavior**
A Markdown link to a PNG is inserted.

**Actual behavior**
A Markdown link to a JPEG is inserted.

**Workaround**
Use "New from Clipboard" in Apple Preview, save as a PNG, and copy & paste (or drag & drop) the file from the Finder.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.5
 - FSNotes version: 4.10.2

**Additional context**

[pasteImageFromClipboard](https://github.com/glushchenko/fsnotes/blob/4.10.2/FSNotes/View/EditTextView.swift#L1793) gets the lossless TIFF data from the pasteboard, but converts it to JPEG before proceeding.

**Comment by glushchenko** [comment]
Fixed, thanks.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5beta4

**Comment by tewe** [comment]
Works for me. Thanks!
