### ISSUE TITLE
Blank lines have smaller line height than text lines

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1161]
**Describe the bug**
Blank lines have smaller line height than text lines

**To Reproduce**
- Look at smaller line height on blank lines compared to text lines.
- Then I cut and paste the whole note and blank lines now have proper line height.
- Then I quit and restart FSNotes and blank lines are narrow.

**Expected behavior**
All lines should have same line height

**Actual behavior**
Blank lines have smaller line height than text lines

**Workaround**
cit and paste the whole note contents over itself

**Supporting Files**

https://user-images.githubusercontent.com/49612/128607709-262e7cb5-c592-40f0-8120-9cf4b4a1bc8c.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.5.1 (20G80)
 - FSNotes version: 5b3

**Additional context**
I use .md note format.

editor prefs

<img width="476" alt="Screen shot 2021-08-07 at 17 47 11" src="https://user-images.githubusercontent.com/49612/128607746-0320326f-d703-4ec4-aaa9-6f78102388be.png">

**Comment by glushchenko** [comment]
I think this was fixed in beta 4

**Comment by gingerbeardman** [comment]
You are correct!
