### ISSUE TITLE
Code theme setting not saved

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#1162]
**Describe the bug**
After quitting the app code theme gets reset to 'atom-one-light'.

**To Reproduce**
1. Go to 'Preferences > Editor > Code Theme' and set it  to e.g. 'github'.
2. Restart the app.
3. See code theme reset to 'atom-one-light'.

**Expected behavior**
Code theme setting is saved.

**Actual behavior**
Code theme gets reset to 'atom-one-light' after restart.

**Workaround**
None.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.10.2 (472)

**Comment by glushchenko** [comment]
Nice catch, fixed! Thank you, @saf-dmitry

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/tag/5beta6
