### ISSUE TITLE
Rearrange folders in sidebar using drag and drop

### ISSUE THREAD

**Issue by fairread** [glushchenko/fsnotes#1163]
Hi for the new FSNotes 5 beta, I wished that the folders in the sidebar can be rearrranged easily using drag and drop. At the moment I found that if I tried to drag a folder then the folder and other folders will then be selected.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
