### ISSUE TITLE
Hanging indent in editor view

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#1164]
**Describe your feature request**
It would be very nice to have hanging indentation for long wrapped lines in editor view, like this:

![Screenshot 2021-08-15 at 21 33 51](https://user-images.githubusercontent.com/30050534/129490271-abf62502-88a7-46c8-bec8-64a7bae70ccd.png)

It will make the source text appear cleaner and more readable. Especially useful for lists and block quotes.

**Additional context**
none

**Comment by glushchenko** [comment]
What is wrong with current implementation?

**Comment by saf-dmitry** [comment]
In the current implementation (v4.10.2) long lines always get wrapped at the left margin see "sync with UI") instead of aligning with the first line of the bullet item:

![Screenshot 2021-08-15 at 21 41 35](https://user-images.githubusercontent.com/30050534/129490486-86494049-d040-4bb6-8b22-c3fedb361c13.png)

I.e., what I will is like this #1044, but in editor view.

**Comment by glushchenko** [comment]
1044 implemented in FSNotes 5
