### ISSUE TITLE
High CPU usage in v5 beta 6

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#1165]
**Describe the bug**
Upon upgrading from v5 to v6 of the latest beta, FSNotes has really high CPU usage (over 110%, with CPU time over 1:37), whereas in the previous beta it used less than 5%. I tried clearing all of FSNote's caches and preference files but that didn't fix the issue, so I had to downgrade to the previous beta.

**Supporting Files**
![image](https://user-images.githubusercontent.com/8772017/129600660-73329864-39b8-43a8-a302-8535269f2d97.png)
![image](https://user-images.githubusercontent.com/8772017/129600480-5beb7f0b-2e68-40cf-99c6-2931efd3a5c2.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.5.2
 - FSNotes version: 5 beta 6

**Comment by glushchenko** [comment]
Beta updated, please redownload and try again. Some time on start needed for attributes caching.

**Comment by volt4ire** [comment]
Great thanks so much that fixed the issue!
