### ISSUE TITLE
Wrong syntax highlighting of wiki links in editor

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#1167]
**Describe the bug**
Text between opening and closing double brackets _in code spans_ should not be recognized as wiki link:

![Screenshot 2021-08-18 at 22 39 21](https://user-images.githubusercontent.com/30050534/129969522-c055c9ff-42ff-4d0e-960e-9115b11a1eec.png)

The bug exists in editor view only. Preview renders the text correctly:

![Screenshot 2021-08-18 at 22 51 43](https://user-images.githubusercontent.com/30050534/129970562-1b807827-2bc5-4844-8f90-9ccc8f15d635.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 5beta6 (491)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5.4.0/FSNotes_5.4.0.zip
