### ISSUE TITLE
Typing lag with notes stored in new Google Drive

### ISSUE THREAD

**Issue by thiemehennis** [glushchenko/fsnotes#1168]
**Describe the bug**
Since updating my Google Backup and Sync to the new Google Drive (which uses sync as well as offline files), the typing is much slower.

**To Reproduce**
1. Download new Google Drive
2. Move notes folder to the new Google Drive
3. Make folder available offline
4. Typing still lagging 

I also moved a note to a new location (not GoogleDrive) and then the problem does not happen. It must be something to do with the syncing.

**Expected behavior**
I'd like to have no lag in typing.

**Actual behavior**
Lagging when typing.

**Workaround**
Moving notes outside of the new Google Drive (which I'd rather not have).

**Supporting Files**
N/A

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 3.8.2

**Additional context**
N/A

**Comment by glushchenko** [comment]
v3.8.2 outdated, current stable version is 4.10.2. Version 5 will be released 22.08.

**Comment by thiemehennis** [comment]
mmm.. not sure why it showed version 3.8 - in fact I use this version: Version 4.9.6 (457)

**Comment by thiemehennis** [comment]
I will update and try again.
