### ISSUE TITLE
System Font and Changing Fonts

### ISSUE THREAD

**Issue by kaapow** [glushchenko/fsnotes#117]
I've noticed that when you change the fonts, this doesn't take effect until you restart the application. Is there anyway to see what everything is going to look like before having to restart. Ideally the changes should happen live, but not sure what the restrictions currently are against that.

Also as a default setting I would've liked to see the use of San Fransisco font as a default setting before changing.

**Comment by kaapow** [comment]
Actually found a nice work around for the San Fransisco font. 
If anyone is looking to use this font (which I highly recommend), then go over here and download it:
https://developer.apple.com/fonts/

Then you're gold. I've set it at 15pt as I've found it to be the most readable.

**Comment by jeff-h** [comment]
Hmm, the font changes no longer being dynamic is a regression in v1.2.9, although in 1.2.8 I see it's broken too, albeit not as badly — the first change does take effect for me in 1.2.8 but nothing after that.

@glushchenko — hoping you have thoughts on this :)
