### ISSUE TITLE
Change “Toggle Preview” from Cmd + \` (backtick) to something else

### ISSUE THREAD

**Issue by kkaefer** [glushchenko/fsnotes#1171]
<kbd>Cmd</kbd> + <kbd>\`</kbd> is a macOS default system shortcut for cycling through windows in an application. However, FSNotes uses it for “Toggle Preview”. 

**Expected behavior**
Pressing <kbd>Cmd</kbd> + <kbd>\`</kbd> cycles between windows like in any other macOS application.

**Actual behavior**
“Toggle Preview” should use a different default shortcut, e.g. <kbd>Cmd</kbd> + <kbd>/</kbd>.

**Workaround**
~Manually change the shortcut in System Preferences.~

None?

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
  - FSNotes version: 5

**Comment by kkaefer** [comment]
> **Workaround**
> Manually change the shortcut in System Preferences.

Actually this isn’t possible. It looks like FSNotes 5 does not accept shorcut overrides from System Preferences:

![image](https://user-images.githubusercontent.com/52399/130423922-c1346051-69b3-42eb-bdb3-824657e3cd04.png)

**Comment by gingerbeardman** [comment]
make sure you match the phrasing exactly in System Preferences > Keyboard > Shortcuts > App Shortcuts

<img width="600" alt="Screen shot 2021-08-23 at 12 02 38" src="https://user-images.githubusercontent.com/49612/130436974-35d6fad4-78ff-44e5-b2ae-766292576c00.png">


gives:

<img width="279" alt="Screen shot 2021-08-23 at 12 01 46" src="https://user-images.githubusercontent.com/49612/130436884-8a57a3e8-bc2f-466b-9cb5-2cdfc6df45ef.png">

**Comment by kkaefer** [comment]
Heh, I guess then this bug report is that macOS uses Title Case for menu names, and FSNotes should too :)

**Comment by gingerbeardman** [comment]
I agree, your menu shortcut will stop working when we fix this, so maybe add both for now :)

**Comment by gingerbeardman** [comment]
See #1172

**Comment by kkaefer** [comment]
Sorry, the menu command names was only a side quest in this issue. The OP is about FSNotes overriding macOS system keyboard shortcuts, which it shouldn’t do. Could you please re-open this issue so that I don’t have to re-post?

**Comment by glushchenko** [comment]
This is an interesting question. At this point, many users already have muscle memory ...

**Comment by gingerbeardman** [comment]
Is <kbd>Cmd</kbd>+<kbd>`</kbd> the default? 

I have mine set to <kbd>Cmd</kbd>+<kbd>#</kbd>

<img width="668" alt="Screen shot 2021-08-24 at 01 34 37" src="https://user-images.githubusercontent.com/49612/130536960-3bcb7f42-e49d-44ca-a407-55d48ce97812.png">

**Comment by kkaefer** [comment]
Yes, <kbd>Cmd</kbd>+<kbd>`</kbd> is the default.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
