### ISSUE TITLE
Menu items should use Title-style Capitalization

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1172]
**Describe the bug**
Menu text does not adhere to macOS conventions for capitalization of menu item wording

**To Reproduce**
1. Open FSNotes
2. Look at menu item text
3. Compare with macOS Finder and Apple docs

**Expected behavior**
- Use title-style capitalization
> Title-style capitalization is used consistently for menu and menu item titles throughout the system. For more information, see Apple Style Guide.
https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/

Also see: Apple Style Guide PDF https://help.apple.com/applestyleguide/#/apsg1eef9171

**Actual behavior**
- Sentence style capitalization

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - FSNotes version: all

**Additional context**
- this will involve a big localisation effort to fix all languages

**Comment by glushchenko** [comment]
> this will involve a big localisation effort to fix all languages

Interesting, but capitalization in macOS related only to English. No capitalization in any other languages in macOS :)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5.4.2

**Comment by gingerbeardman** [comment]
Still to do

- Change creation date (File menu)
