### ISSUE TITLE
How do I reset the .AppleSystemUIFont

### ISSUE THREAD

**Issue by caillou** [glushchenko/fsnotes#1173]
After changing the value of `Layout > Note Font` to something else, I can not go back to `.AppleSystemUIFont`.

I this possible?

**Comment by tewe** [comment]
Run `defaults delete co.fluder.FSNotes font` in Terminal. I quit FSNotes first, but that might not be necessary.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by tewe** [comment]
The Reset button works for me. Thanks!
