### ISSUE TITLE
Preview with code block expanded to next lines

### ISSUE THREAD

**Issue by ngocphamm** [glushchenko/fsnotes#1176]
**Describe the bug**
If I have a  code block in between a list's items, the items following the code block are included in a separate code block, and not continue in the list format anymore. 

**To Reproduce**
1. Create a new note with the content like in this gist https://gist.github.com/ngocphamm/b3bfaced7f2096de29ec9e04010953be
2. Press Cmd + ` to enable preview
3. See isue with the preview in screenshot below

<img width="450" alt="CleanShot 2021-08-23 at 09 04 45@2x" src="https://user-images.githubusercontent.com/395123/130452146-6205ac87-5cab-4995-a272-c126720cdf66.png">

**Expected behavior**
The `Test 2-2`, `Test 2-2-a`, and `Test 2-3` are in normal list format, NOT in code block

**Actual behavior**
The `Test 2-2`, `Test 2-2-a`, and `Test 2-3` are in code block. see screenshot above.

**Desktop (please complete the following information):**
 - OS: macOS & iOS
 - OS version: maccOS 10.15.7 & iOS 14.7.1
 - FSNotes version: on macOS 5.0.1, on iOS 4.8.1

**Comment by saf-dmitry** [comment]
I think it is not a bug. The fenced code block _terminates_ the list above. The text following the fenced code block is not part of the list above and is indented more than four spaces, thus interpreted correctly as indented code block.

**Comment by ngocphamm** [comment]
@saf-dmitry Thanks for your answer. I just realized that Github does the same, so yeah I think you are right it's not a bug. Do you happen to know how to properly achieve that, though? Or I just should not have a code block between list items?

**Comment by saf-dmitry** [comment]
@ngocphamm To include any block-level content in a list item you need to indent it by four spaces or one tab (indented code block must be indented by eight spaces or two tabs) _relative to that item_:

~~~
1. First item

    ```
    Code block
    ```

2. Second item
3. Third item
~~~

**Comment by ngocphamm** [comment]
Thank you @saf-dmitry. Learn something new everyday!
