### ISSUE TITLE
Import from Evernote

### ISSUE THREAD

**Issue by 7aklhz** [glushchenko/fsnotes#1180]
**Describe your feature request**
Hi. I just purchased the Mac App as I'm looking for an Evernote alternative. However, I cannot seem to import my evernote notes to FSNote. I this doable ? 

**Additional context**
Add any other related information here. macOS or iOS?

**Comment by gingerbeardman** [comment]
I would guess you need to export from Evernote as markdown or plain text, which is a question for that side.

Once you have those, just out them in the folder FSNotes is looking at.

**Comment by glushchenko** [comment]
Hi @7aklhz 

You can export Evernote data to .enex format and convert it to Markdown use this tools:

1) https://github.com/wormi4ok/evernote2md
2) https://github.com/exomut/evernote-dump

**Comment by ggascoigne** [comment]
I found that evernote2md worked rather nicely to extract all of the notes and retain their tags.

I used the `--frontMatter` flag to store all of the related attributes in the frontmatter of the markdown files (as used by other markdown savvy apps like Noteable).  Is there any way to have FsNotes treat frontmatter as metadata?  Alternatively, is there any other way to keep the tags and attributes from my EverNote notes?

**Comment by webuniverseio** [comment]
evernote2md supports tag template, using `--tagTemplate="#{{tag}}"` worked for me

**Comment by webuniverseio** [comment]
One issue with evernote2md is that file references are stored like this
`[Notepad1\-2022\-01\-18\_11\_28.pdf](./file/Notepad1-2022-01-18_11_28.pdf)`
When I use copy link I see following path
`file:///Users/username/Applications/FSNotes.app/Contents/Resources/MPreview.bundle/file/Notepad1-2022-01-18_11_28.pdf`, but I expected `/Users/username/Library/Mobile\ Documents/com~apple~CloudDocs/Documents/FSNotes/Shared/evernote/file/Notepad1-2022-01-18_11_28.pdf`, so relative path to a note.
Fortunately there are not too many files and in worst case I probably can script something to fix this
