### ISSUE TITLE
[FSNotes5] Menu list hides after opening

### ISSUE THREAD

**Issue by htd-tstepien** [glushchenko/fsnotes#1185]
**Describe the bug**
Menu options are hiding after opening it

**How to reproduce**
https://user-images.githubusercontent.com/57900160/130812217-5531655a-4cc2-4814-933e-33ffd0cd8f74.mp4

**Expected behavior**
A list of options should be visible.

**Actual behavior**
A list of options hides after clicking the icon.

**Workaround**
No workaround found

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.4 (20F71)
 - FSNotes version: Version 5.0.2 (497)

**Comment by gingerbeardman** [comment]
Confirmed
