### ISSUE TITLE
Finder and Spotlight integration

### ISSUE THREAD

**Issue by scbarton** [glushchenko/fsnotes#1189]
fsnotes Issue: Bug Report Finder and Spotlight integration

I really like the new version of FSNotes and I am optimistic that it can completely replace Evernote in my workflow. The best part is the `.textbundle` based storage which is very open and potentially cross-platform.

One odd behavior, though, is that FSNotes cannot open `.textbundle` files double clicked in the Finder, even though this extension is associated with the App. I strongly recommend this be fixed, because the ability to open from the Finder would provide Spotlight integration automatically.

**Describe the bug**
FSNotes cannot open `.textbundle` files, either by using "Open with..." in the contextual menu, or by double-clicking on a `.textbundle` file in the Finder.

**To Reproduce**
1. Double-click on any `.textbundle` file in the Finder.

**Expected behavior**
If the file is in default storage, the file should be selected in FSNotes

**Actual behavior**
FSNotes launches, and the Trash is selected.

**Workaround**
I was able to make an applescript app (attached) that can open `.textbundle` files in FSNotes. It works by creating a `fsnotes://find/` URL based on the root name of the `.textbundle`. 

**Supporting Files**
Please see "FSNotes opener.app.zip" attached

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.5.2
 - FSNotes version: 5.0.2

[FSNotes opener.app.zip](https://github.com/glushchenko/fsnotes/files/7078501/FSNotes.opener.app.zip)

**Comment by glushchenko** [comment]
Fixed, thanks!
