### ISSUE TITLE
Instructions for resetting to default settings

### ISSUE THREAD

**Issue by Etheryte** [glushchenko/fsnotes#1190]
**Describe your feature request**
Alternatively, this ticket could be titled "Uninstall instructions". I would like to find a way to reset the app to its default settings, but seem to be unable to. I tried deleting [the preferences file](https://github.com/glushchenko/fsnotes/wiki/Preferences-location) (and `~/Library/Containers/co.fluder.FSNotes` in general), but when I restart the app, it's somehow still persisting the settings I used before.  

For context, I would like to use the default Git backup location, but don't know where to find it.  

**Additional context**
macOS 10.15.7  
FSNotes 5.0.2

**Comment by Etheryte** [comment]
@lfpcorreia This software is given away freely in kind by the authors. It's rude to go around demanding activity on tickets. If it helps, compare the concept to free beer. You wouldn't go around demanding more free beer just because someone bought you a beer.

**Comment by glushchenko** [comment]
`sudo killall cfprefsd` after container removing! ;)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/wiki/Preferences-location

**Comment by Etheryte** [comment]
Nice, thank you very much for the help @glushchenko, that's very helpful. 👍
