### ISSUE TITLE
Crash while typing

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1194]
**Describe the bug**
I typed into a new note and the app crashed after a few characters.

**To Reproduce**
Not so far.

**Supporting Files**

[FSNotes_2021-09-06-101622.crash](https://github.com/glushchenko/fsnotes/files/7114433/FSNotes_2021-09-06-101622.crash.txt)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.5.2 (20G95)
 - FSNotes version: 5.0.2 (497)

**Comment by glushchenko** [comment]
Hi, @tewe Can you provide more details? May be code block used or tab or spaces, lists?

**Comment by tewe** [comment]
1. Hit ⌘+N
2. Type `# How to`

That's as far as I got when it crashed.

**Comment by glushchenko** [comment]
Interesting, cannot reproduce it.

**Comment by glushchenko** [comment]
Please try this build and let me know.

[FSNotes_v5.0.3.zip](https://github.com/glushchenko/fsnotes/files/7139142/FSNotes_v5.0.3.zip)

**Comment by glushchenko** [comment]
@tewe did you try it?

**Comment by tewe** [comment]
So far it didn't crash again with either build.

**Comment by glushchenko** [comment]
OK, thanks.
