### ISSUE TITLE
'fsnotes://find?id=' links broken on iOS

### ISSUE THREAD

**Issue by daaaaaaaaaniel** [glushchenko/fsnotes#1197]
**Describe the bug**
On macOS, if you right-click a note and select 'Copy URL', the clipboard text will receive a URL formatted like this: 'fsnotes://find?id=…', which, when pasted in a document used by another app, will trigger FSNotes to open to the linked note. This works reliably on macOS. On iOS, however, FSNotes opens randomly. It doesn't open directly to the linked note. 

**To Reproduce**
1. Right click any note on the Mac app
2. Click on 'Copy URL'
3. paste the URL elsewhere, ie. in Apple Notes
4. on iOS, open the document (ie. the Apple Note) and click the link
5. FSNotes will launch but it will note open the desired note

**Expected behavior**
FSNotes for iOS should open with the same destination that it opens on macOS

**Actual behavior**
FSNotes opens to whatever was previously open on FSNotes

**Workaround**
N/A

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - macOS version: 11.5.2 
 - iOS version: iOS 14.7.1
 - FSNotes version: 5.0.2 (macOS); 4.8.1 (iOS)

**Additional context**
N/A

**Comment by glushchenko** [comment]
Fix available in the App Store
