### ISSUE TITLE
Starting a search from a link does not focus the search field

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1199]
**Describe the bug**
Clicking links to start a search does not move the focus to the search field.

**To Reproduce**
1. Type a link to a non-existing page, e.g. `[[Test]]`
2. Click the link

**Expected behavior**
The search field gets keyboard focus, so I can hit enter to create the page.

**Actual behavior**
A search is performed, but the insertion point stays where it is, so creating the page requires additional steps.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 5.0.3

**Comment by glushchenko** [comment]
Fixed here https://github.com/glushchenko/fsnotes/releases/download/5.1.0beta1/FSNotes_5.1.0.zip

**Comment by tewe** [comment]
Works for me. Thanks!
