### ISSUE TITLE
Make note pane more compact

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#12]
I'd like the note pane to be more compact. 

It would be great if the large linespacing could be reduced (it's currently larger than that in the main pane, even though the font it smaller.

More importantly, it would be really useful newlines in the note could be stripped for display, so the preview of this note
```
# Heading

This note is about foo and bar
```
becomes `# Heading This note is about foo and bar`.

Many of my notes start with heading and then a blank line, then more text (that is useful to see in the note pane preview).

**Comment by jeff-h** [comment]
I agree, this is needed. If nobody gets there before me I'll take a look at stripping the line spaces from the preview (assuming @glushchenko is happy with this).

Also, I personally always chose to have no preview (in nvALT). So I'd like that option :)

**Comment by glushchenko** [comment]
Checkout https://github.com/glushchenko/fsnotes/releases/download/0.8/FSNotes.app.zip

**Comment by jeff-h** [comment]
Nice 👍
