### ISSUE TITLE
5.0.3 version tag seems to be on wrong commit

### ISSUE THREAD

**Issue by spenat28** [glushchenko/fsnotes#1200]
5.0.2 and 5.0.3 tags are placed on the same commit

check: https://github.com/glushchenko/fsnotes/compare/5.0.2...5.0.3

expected: tag 5.0.3 should probably be on commit 453a27ef6b4cb73dbfa46729cbf502c39fa19330

**Comment by glushchenko** [comment]
Yep, data not committed yet, sorry.
