### ISSUE TITLE
Links only work for notes that are currently in the note list

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1203]
**Describe the bug**
Links only work for notes that are currently in the note list

**To Reproduce**
1. Create an untagged note
2. Create a tagged note
3. In the sidebar, click on the tag
4. Try creating a link to the untagged note and clicking on it

**Expected behavior**
Should link to the note

**Actual behavior**
The note you're currently viewing gets unselected / disappears from the editor

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.5.2
 - FSNotes version: 5.0.3

EDIT: I just tried to replicate this again today, but I can't! I'll leave the issue open though, because it definitely was happening

**Comment by tewe** [comment]
I can reproduce this.

**Comment by glushchenko** [comment]
Seems fixed, please reopen if is actual yet.
