### ISSUE TITLE
Compiler errors with Xcode 12.4, Swift 5.3.2

### ISSUE THREAD

**Issue by jqdg** [glushchenko/fsnotes#1204]
I am trying to build this project with Xcode 12.4 on Mac OS 10.15.7. I obtain compiler errors
```
fsnotes/FSNotes/View/SidebarOutlineView.swift:320:19: error: definition conflicts with previous value
        guard let project = project else { return false }
                  ^
fsnotes/FSNotes/View/SidebarOutlineView.swift:310:13: note: previous definition of 'project' is here
        var project: Project?
```
pointing to this location: https://github.com/glushchenko/fsnotes/blob/453a27ef6b4cb73dbfa46729cbf502c39fa19330/FSNotes/View/SidebarOutlineView.swift#L310-L320

I can fix all of these compiler errors by changing variable names, and then the project builds successfully.

Is there something wrong with my configuration, or is this a real issue? If so, I'd be happy to make a PR to fix it.

**Comment by glushchenko** [comment]
Works fine for me on Big Sur, but you can make PR if needed.
