### ISSUE TITLE
Tag highlighting makes it difficult to markup headings

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1206]
**Describe the bug**
- Tag highlighting makes it difficult to markup headings

**To Reproduce**
1. Enter a some text
2. Type ## in front of it to make it a heading

**Expected behavior**
- editor should keep headings and tags distinct

**Actual behavior**
- heading text and tag highlighting becomes intertwined
- text remains highlighted as a tag even after removal of #
- difficult to edit text with # close by

**Workaround**
- enter space between heading markup and text (see end of video)

**Supporting Files**

https://user-images.githubusercontent.com/49612/134218004-4325b416-6620-43da-83d5-278f35b2c532.mp4

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.6 (20G165)
 - FSNotes version: 5.0.3

**Comment by gingerbeardman** [comment]
Doesn't happen on iOS.

**Comment by jawwad** [comment]
I'd love a fix for this since this is indeed very annoying. A workaround is to first add a space before the heading and then add the tag before the space that was just added but of course, I always forget and have to delete the entire heading to get rid of the tag formatting.

**Comment by tewe** [comment]
I can't reproduce this. Tags never get highlighted while editing. But then I'm on an older macOS.

**Comment by glushchenko** [comment]
Fixed, thanks!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5.3.2
