### ISSUE TITLE
Nested folders in iOS app

### ISSUE THREAD

**Issue by pasz** [glushchenko/fsnotes#1208]
**Describe your feature request**
Like the desktop app, allow nested folders in iOS app.

**Additional context**
iOS

**Comment by joehanna** [comment]
It is very confusing trying to find a subfolder as shown on Mac OS on iOS when all folders are shown in a flat list. It is particularly confusing when 2 subfolders have the same name but no parent folder to give it context.


![IMG_A53F300FB43A-1](https://user-images.githubusercontent.com/1687108/143727161-162bdf66-c211-4fdb-a869-ab9ce4efa546.jpeg)

**Comment by ColdHeat** [comment]
Really would like this feature. Without this the iOS app is lackluster compared to the Desktop app.

**Comment by ColdHeat** [comment]
@glushchenko is there any chance you could share your thoughts here or get this on a roadmap? Without the folder structure the iOS app is really disorganized. Or if perhaps you can share a better workflow?

**Comment by BJ8** [comment]
Just found FSNotes and I am in love. Thank you so much Oleksandr for giving us this treasure! FSNotes  gives me so much peace of mind, if feels like when I switched from Windows to MacOS a decade ago. The only thing missing piece from making the FSNotes Mac and IOS combination wonderful are nested folders in IOS. Compared to the Mac app the IOS app sidebar just is a bit too cluttered without folders. <3

**Comment by glushchenko** [comment]
I've already written about it. You ask, I do. As soon as I have some time on my hands, I'll do it.
