### ISSUE TITLE
parse YAML header metadata error when it contains dos newline characters

### ISSUE THREAD

**Issue by hqweay** [glushchenko/fsnotes#1211]
**Describe the bug**

Fsnotes can't parse YAML header metadata of my notes, but when I dos2unix the notes, it works well. So I guess the reason is it contains dos newline characters? If someone has the need for cross platform synchronization, it's great to parse normally.

Thank!

**Supporting Files**

I provide a example:

[hello.md](https://github.com/glushchenko/fsnotes/files/7210460/hello.md)

 - OS: macOS
 - OS version: 11
 - FSNotes version: 5.0.3

**Comment by hqweay** [comment]
By the way, if only the title without quotation marks could be parsed correctly.
like this:
```
---
title: hello,World!
---
```

**Comment by glushchenko** [comment]
Fixed, thanks

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5.1.0beta1/FSNotes_5.1.0.zip
