### ISSUE TITLE
Inline math not displayed properly on iOS

### ISSUE THREAD

**Issue by dpo** [glushchenko/fsnotes#1218]
**Describe the bug**
In the demo note, the inline math isn't rendered. The display math is rendered.

**To Reproduce**
1. Purchase and download iOS app.
2. Preview demo note.

**Expected behavior**
Render inline math.

**Actual behavior**
Inline math isn't rendered.

**Supporting Files**
See screenshot attached.

**Desktop (please complete the following information):**
 - OS:  iOS
 - OS `version:` 14.8
 - FSNotes version: 4.8.1

<img width="787" alt="Open note" src="https://user-images.githubusercontent.com/38760/136293925-ae61f64b-6b16-4cee-8e7b-419f654618e7.png">

**Comment by glushchenko** [comment]
Fix available in the App Store
