### ISSUE TITLE
Feature request: a menu item to delete a note

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#122]
If I understand correctly, a note can be deleted by way of the context menu or the command-delete shortcut. I wondered if a delete command could be added under the File menu. Thanks.

**Comment by peavine** [comment]
If I enable the preference, "Focus in editor when note select," I am unable to delete a note when doing the following:

* Select a note in the Notes List.

* Use the command-delete shortcut to delete the note. 

Instead, to delete a note, I use the delete command in the context menu or do the following:

* Select a note in the Notes List.

* Click on the selected note a second time.

* Use the command-delete shortcut.

I mention this because it would be helpful if FSNotes had an easier way to delete a note.

**Comment by glushchenko** [comment]
⌘-shift-delete working fine ;)

**Comment by peavine** [comment]
That shortcut works great. I appreciate it.
