### ISSUE TITLE
Bug: Window position not remembered after hide/show

### ISSUE THREAD

**Issue by bjerkeweb** [glushchenko/fsnotes#1226]
**Describe the bug**
FSNotes mac does not remember it's main window location after hide/show

**To Reproduce**
1. Open or foreground FSNotes
2. Move main window position in any direction
2. Hide FSNotes
3. Command-tab to FSNotes to reactivate

**Expected behavior**
Expected window to be in the same place it was before hiding

**Actual behavior**
Main window shows up somewhere else on screen

**Workaround**
None found

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 11.2.2
 - FSNotes version: 5.1.0

**Comment by bjerkeweb** [comment]
@gingerbeardman both/either

**Comment by gingerbeardman** [comment]
Yes, I can reproduce with either.

**Comment by gingerbeardman** [comment]
Here is me reproducing:

https://user-images.githubusercontent.com/49612/138093938-003bfb48-2353-4844-b9ac-fcbe21853703.mp4
