### ISSUE TITLE
RTF Display Issues

### ISSUE THREAD

**Issue by chchen2021** [glushchenko/fsnotes#1229]
I am using FSNotes to manage RTF files between macOS, iOS and iPadOS. I found that iOS preserves the RTF format (color, boldface etc) in the edit mode, and loses the formatting in the preview mode. This behavior is the expected one.

In macOS, if the file is RTF, I cannot toggle between preview and edit. I would like to have a mechanism to retain the RTF format, just like iOS. 

In iPadOS, the edit/preview mode displays RTF just like iOS, but I easily lose the top editing menu, where there is a button to toggle between edit and preview. It takes just one toggle to completely lose the top menu. I would need to rotate my iPad from landscape to portrait mode to get the edit menu back. 

--
iOS/iPadOS 15.02 / FSNotes 4.8.1
macOS 11.6 / FSNotes 5.1.2

**Comment by glushchenko** [comment]
Sorry for delayed response, but preview is only for markdown.
