### ISSUE TITLE
Frequent crashes due to com.apple.cloudkit.*.callback

### ISSUE THREAD

**Issue by rtimmons** [glushchenko/fsnotes#123]
Hi there. FSNotes is great so far thanks for making it.
Is this the right place to report bugs in the App Store version?

I'm noticing that it crashes approximately every 20-30 minutes. The crash report indicates a SIGBUS error. Here's a gist with the crash report from the last time it happened: 
https://gist.github.com/rtimmons/0e0599a3af433b1b67db134e969087cd
No behavior in particular seems to trigger this so it may be hard to reproduce - sorry about that.

Since this seems to be related to CloudKit, would switching to Dropbox syncing would fix the issue in the short term?

I'm happy to post more system info or continue to post crash reports here if it would help, please just let me know I'll follow this issue on GH.

Thank you

**Comment by peavine** [comment]
I have also had occasional issues with FSNotes 1.2.11 crashing and this happens with both the App Store and GitHub versions. As with rtimmons, no specific event that I can determine causes the crash. 

I kept a copy of the most recent crash report, but I'm not sure where to send it or if it would be helpful. The crashed thread is: "0  Dispatch queue: com.apple.main-thread"

**Comment by glushchenko** [comment]
Hi @rtimmons, at first thank you for report. In last build CloudKit revoked completely, instead you can use iCloud Documents, and sync data over iCloud Drive. 

iOS FSNotes works with iCloud Documents too,  this is a more open way for storing documents. I spent too much time for implementing CloudKit, and now it's in the past. iCloud Documents not so fast, but more reliable.

@peavine please provide full crash report, and i will try to fix it.

**Comment by peavine** [comment]
[peavine_crash_report.txt](https://github.com/glushchenko/fsnotes/files/1782715/peavine_crash_report.txt)

I've attached the crash report.

**Comment by glushchenko** [comment]
@peavine looks like selected font not available, try to remove settings ~/Library/Containers/co.fluder.FSNotes and run again.

**Comment by peavine** [comment]
Thanks for the response. I have done as you suggested and will report back after a few days.

**Comment by peavine** [comment]
FSNotes has been working fine. Deleting the settings did the job. Thanks.
