### ISSUE TITLE
Option to set a commit message when saving note

### ISSUE THREAD

**Issue by ckayr** [glushchenko/fsnotes#1230]
**Describe your feature request**
When saving a revision of a note with File->Save revision or with Cmd-S, I'd like to set a custom message. Currently, the git commit has a templated message that says  '<Note> update'.

**Additional context**
OS: macOS
Version: 5.1.0

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
