### ISSUE TITLE
Sort child items alphabetically

### ISSUE THREAD

**Issue by farons** [glushchenko/fsnotes#1231]
Hello, WHEN I was using the directory, I wanted to sort by the folder name in positive or reverse order. I changed the folder name for many times but couldn't do it

Mac OS Big Sur

<img width="254" alt="Snipaste_2021-10-30_08-38-57" src="https://user-images.githubusercontent.com/27187429/139514276-a3810e86-f6b1-4734-adf2-35b895410dff.png">

**Comment by chchen2021** [comment]
The iOS version has a similar problem. The files (not folders) cannot be sorted alphabetically. The selection of the "sort by title" option has some effect, compared to say "sort by modification date", but the result is not an alphabetic order.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
