### ISSUE TITLE
macOS: swipe gestures like iOS

### ISSUE THREAD

**Issue by paulrudy** [glushchenko/fsnotes#1235]
**Describe your feature request**
1. In the macOS app, it would be great to be able to swipe on notes in the notes list like in iOS, to get the "Delete", "Pin", and "More" items.

2. Customizing swipe gestures/items would be an added bonus

**Additional context**
macOS

**Comment by nth-chile** [comment]
Yes. In [Bear](https://bear.app/), you can swipe right/left to open/close the notes list. If the notes list is open, you can swipe right again to open the sidebar. At that point, swiping left closes the sidebar. Swiping left again closes the notes list. Honestly, the keyboard shortcuts (`CMD SHIFT B` and `CMD CTRL SHIFT B`) are a little awkward and I use them all the time. I'm always missing the swipe gestures from Bear. I think another option would be to replace `CMD CTRL SHIFT B` with `CMD 1` and replace `CMD SHIFT B` with `CMD 2` but I know those are reserved for markdown headings (Personally I just type the hash instead)

**Comment by glushchenko** [comment]
@nth-chile any shortcuts can be rebinded in keyboard settings.
