### ISSUE TITLE
Trailing parentheses not part of URL

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1236]
### Description

URLs with parentheses (as are common on WikiPedia) work fine in the Markdown preview. While editing the trailing parentheses is not recognized as part of the address, so clicking it goes 404.

### To Reproduce

1. Start a new note
2. paste `https://en.wikipedia.org/wiki/Cowboy_Bebop_(2021_TV_series)`
3. click the highlighted URL

### Expected behavior

URL recognition in the editor uses the same algorithm as when rendering the preview.

### FSNotes version

5.1.2

### macOS/iOS version

macOS 10.14.6

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.0/FSNotes_5.3.0.zip

**Comment by tewe** [comment]
Works for me! But it seems to slightly break highlighting: the trailing parentheses in Markdown links like `[FSNotes](https://fsnot.es)` is now blue instead of grey. This does not change the URL that gets opened.

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.3/FSNotes_5.3.3.zip

**Comment by tewe** [comment]
Now for `[FSNotes](https://fsnot.es)` all brackets and parentheses are grey :)

But for `[FSNotes](https://fsnot.es).` (e.g. dot at the end of a sentence) *both* parentheses are blue?!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5.4.2

**Comment by tewe** [comment]
`https://en.wikipedia.org/wiki/The_Menagerie_(Star_Trek:_The_Original_Series)` open the correct page, but the closing parenthesis is not highlighted.

<img width="365" alt="CleanShot 2022-08-13 at 11 28 05@2x" src="https://user-images.githubusercontent.com/645412/184477855-f41b0206-c696-414d-a7e5-91b5c58f310b.png">
