### ISSUE TITLE
YAML Headers and Metadata

### ISSUE THREAD

**Issue by mmerline** [glushchenko/fsnotes#1238]
**Describe your feature request**
Please add YAML metadata support. To quote [this Markdown Crash Course](https://zsmith27.github.io/rmarkdown_crash-course/lesson-4-yaml-headers.html):

> A YAML header contains YAML arguments, such as “title”, “author”, and “output”, demarcated by three dashes (---) on either end.

Here's a screenshot of how this looks in Sublime Text, which is an effective implementation:

[Screenshot of YAML Metadata in Sublime Text](https://merline.d.pr/a8lFIn)

Ideally, this support would include a few significant features:

- Basic metadata syntax highlighting
- File naming that reflects the Title field
- Metadata is ignored when previewing the rendered Markdown

[The iA Writer implementation](https://ia.net/writer/support/general/markdown-guide) is a good model, and supports some additional inline variables, which is slick:

> iA Writer supports metadata at the beginning of documents. You can use it store important information about your documents, hidden from Preview. Metadata must be separated from the rest of the document by three dashes.
> You can use the metadata in the text by putting it in brackets adding a % sign.

**Additional context**
I believe this would apply to all OS and devices.

**Comment by xplosionmind** [comment]
Please refer also to the very insightful https://github.com/notaapp/talk/issues/86

**Comment by adamshand** [comment]
Another vote for Frontmatter support.  I'm looking at migrating from Obsidian and it would be great to be able to make use of  existing Frontmatter in my notes.

**Comment by glushchenko** [comment]
Edit mode:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1089917/192138418-19ce2abe-374d-488e-b8ad-f50c285ca813.png">

Preview mode:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/1089917/192138430-d2c5d8d5-00eb-4209-9a07-101dd0e70663.png">

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by helmut72** [comment]
Looks like tags and created/modified are not supported. Example:

```
---
title: My Title
tags:
  - tag1
  - tag2
  - tag3
created: 2022-09-23T13:16:20.385Z
modified: 2023-03-05T10:19:48.033Z
---
```

**Comment by gingerbeardman** [comment]
@helmut72  please file as a new issue

**Comment by ReessKennedy** [comment]
> Looks like tags and created/modified are not supported. Example:
> 
> ```
> ---
> title: My Title
> tags:
>   - tag1
>   - tag2
>   - tag3
> created: 2022-09-23T13:16:20.385Z
> modified: 2023-03-05T10:19:48.033Z
> ---
> ```

+1 on supporting support for tags. I am trying to get Obsidian and FS Notes to work together but have all page-level tags in FrontMatter with Obsidian.

**Comment by DesBw** [comment]
please add support for tags
