### ISSUE TITLE
Upgrade mermaid-js to support todayMarker

### ISSUE THREAD

**Issue by atkawa7** [glushchenko/fsnotes#1240]
**Describe your feature request**
This is not working 

```mermaid
gantt
    title Schedules
    dateFormat HH:mm
    axisFormat %H:%M
    todayMarker off
    Schedule A     :A, 05:00, 360min
```

**Additional context**
Add any other related information here. macOS or iOS?

**Comment by atkawa7** [comment]
@glushchenko Ping

**Comment by glushchenko** [comment]
@atkawa7 done.

**Comment by atkawa7** [comment]
Thank you

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.0/FSNotes_5.3.0.zip

**Comment by atkawa7** [comment]
Thank you @glushchenko
