### ISSUE TITLE
Duplicating a note does not adjust encoded images paths

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1241]
### Description

When duplicating a (non-TextBundle) note, any images are copied. But the new note will still point to the original files if the path is URL-encoded.

### To Reproduce

1. Make sure you container is _not_ set to TextBundle
2. Start a new note
3. Drag an image with whitespace in the filename into the note (I used screenshots created by the screenshot feature built into macOS)
4. File > Duplicate the note

### Expected behavior

The Markdown image link in the note changes to a UUID.

### FSNotes version

5.1.2

### macOS/iOS version

macOS 10.14.6

### Additional context

The [Note move function](https://github.com/glushchenko/fsnotes/blob/7d999c17f9f512f1c7cac0e0fea05f7b7035e74d/FSNotes/Business/Note.swift#L449) does a search & replace based on the output of `getAllImages`, which [removes any encoding](https://github.com/glushchenko/fsnotes/blob/7d999c17f9f512f1c7cac0e0fea05f7b7035e74d/FSNotes/Business/Note.swift#L1222).

**Comment by tewe** [comment]
#715

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5.4.0/FSNotes_5.4.0.zip

**Comment by tewe** [comment]
IMHO a bit of a hack, but works for me. Thanks!
