### ISSUE TITLE
Deleting a note removes images also used in other notes

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1242]
### Description

Deleting a notes also deletes images linked from that note, even if other notes also link to them.

### To Reproduce

1. Make sure you container is _not_ set to TextBundle
2. Start a new note
3. Drag an image into the note
4. Copy the Markdown of the note
5. Start another note
6. Paste
7. Delete either note

Alternatively #1241

### Expected behavior

The image will still display in the remaining note.

### FSNotes version

5.1.2

### macOS/iOS version

macOS 10.14.6

### Additional context

The Note removeFile function [deletes images](https://github.com/glushchenko/fsnotes/blob/7d999c17f9f512f1c7cac0e0fea05f7b7035e74d/FSNotes/Business/Note.swift#L410) without checking if they are linked from elsewhere.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5.4.0/FSNotes_5.4.0.zip

**Comment by tewe** [comment]
I'm not sure what cf18fc4 has to do with this, but I can no longer reproduce it. Thanks!
