### ISSUE TITLE
Disable tags

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1243]
Gruber's original Markdown renderer does not require whitespace between the number sign and a atx-style heading. So ten years ago I wrote my notes without.

The CommonMark spec requires at least one space character. Since FSNotes uses a library based on that, none of my old headings render correctly.

IMHO worse is that they render as "tags". Maybe this can be made optional for people with legacy data?

(They also mess up my list of tags, but I don't use that feature anyway)

**Comment by gingerbeardman** [comment]
+1

I'd also like to disable tags.

**Comment by glushchenko** [comment]
Thanks you for report, now option disable all highlights for tags.

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.0/FSNotes_5.3.0.zip

**Comment by tewe** [comment]
Spaceless heading no longer render as tags, and the list seems to be gone :)

**Comment by timotgl** [comment]
If you end up here from a search engine because you want to hide tags from the sidebar, go to `Preferences` -> `Editor` and uncheck `Scan inline tags`. (I had CSS hex color values in my markdown notes that were interpreted as tags unintentionally).
