### ISSUE TITLE
Option to use 2 spaces instead of 4 for tabs

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1244]
**Describe your feature request**
Replace the "Use 4 spaces instead of tab" option with an "Indent Using" dropdown that lets you select one of the following:
    - 2 Spaces
    - 4 Spaces
    - Tab

**Additional context**
This is already done! I submitted a PR: https://github.com/glushchenko/fsnotes/pull/1225. But maybe this is a better place to discuss it, if you guys have some better ideas or disagree with this change

**Comment by glushchenko** [comment]
Pull request requires some work https://github.com/glushchenko/fsnotes/pull/1225#issuecomment-974936906
