### ISSUE TITLE
Appearance can become a mix of Dark and Light mode when set to System

### ISSUE THREAD

**Issue by goalidea** [glushchenko/fsnotes#1245]
### Description

The topic appearance is set to follow the system, the following situation will appear
[image](https://i.loli.net/2021/11/16/UIMqOW2Hf3cpuSs.png)

### To Reproduce

1. Go to 'Preferences'
2. Click on 'Advanced'
3. Scroll down to 'Appearance'
4. Select 'System'
5. when system from dark to light will see

### FSNotes version

5.1.3

### macOS/iOS version

10.15.7

**Comment by nth-chile** [comment]
This might be related to the bug where if you customize the note bg color and then resize the sidebar, the notes list text turns black and search section turns white

**Comment by goalidea** [comment]
The MacOS appearance needs to be set to automatically. This bug does not appear if you manually set dark mode or light mode, and this bug will only appear after setting to automatically and from dark mode to light mode.

**Comment by glushchenko** [comment]
Can not reproduce it

**Comment by gingerbeardman** [comment]
I've seen this.

To reproduce it's kind of a pain to have to wait for the system to automatically change between modes.

How did you try to reproduce?

**Comment by dcd-arnold** [comment]
I am seeing this now.

**Comment by glushchenko** [comment]
Fixed in FSNotes 6

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
