### ISSUE TITLE
Fonts folder breaks FSnotes Functionality - EDITED

### ISSUE THREAD

**Issue by ksdomino** [glushchenko/fsnotes#1246]
### Description

EDIT: THE PROBLEM WAS THAT ONE OF THE FOLDERS CONTAINED AROUND 10 FONTS. APPARENTLY FSNOTES CANNOT IGNORE FONTS FOLDERS AND THAT CAUSES THIS PROBLEM TO OCCUR.

The folder list doesn't pick up all the folders unless you rename a folder, then it gets detected by fsnotes..that is until you restart fsnotes and then it loses a bunch of folders again! 
I show the problem clearly in this short 1-minute video: https://www.youtube.com/watch?v=lukxR3vR7oA

### To Reproduce

problem clearly shown in my one minute vid linked video above, I have no idea how you would reproduce this on your own system

### Expected behavior

Expect the app to show all folders, not just some of them.

### FSNotes version

5.13

### macOS/iOS version

Macos Catalina 10.15.7

**Comment by ksdomino** [comment]
Things I've tried and checked:
Permissions and properties for folders (detected and not detected) are exactly the same (as shown in the info popup for each folder).
I've removed the app completely using app cleaner and reinstalled it from the app store..same problem: Fsnotes detects and shows some of the folders while other folders and not detected/shown at all.

**Comment by ksdomino** [comment]
Ok the limitation appears to be : I can only have 16 or 17 folders in Fsnotes root folder. (I have plenty of ram: 16GB so this limitation should not be imposed)
If I copy (or create) more folders, Fsnotes chooses not to display some of the folders. 
Which folders are not shown? Some of the older folders disappear from the list, and some of the new ones so I will need to test further to determine which folders are not shown. I will also test whether subfolders within folders are the cause.
I can record more vids if you need to see any tests.

**Comment by ksdomino** [comment]
The problem was caused by a folder that contained fonts. (.OTF and .TTF files).
Alos my welcome folder (containing .txtbundle files), archive folder  and trash folders don't show up in fsnotes but that is probably expected behaviour.
I laso have another folder called "productivity" that doesn't show up so I'll check but I think it is the same bug: the existence of certain filetypes within a folder will cause FSnotes to have problems showing folders.

**Comment by gingerbeardman** [comment]
Seems similar to #1247 that unexpected file types can cause FSNotes to behave unexpectedly.
