### ISSUE TITLE
Not reading all subfolders

### ISSUE THREAD

**Issue by supermensa** [glushchenko/fsnotes#1247]
### Description

When importing folders that has subfolders and additional subfolders, many of the folders are not being imported/read.
The filenames I'm using are normal lowercase, folders containing normal .txt or .md files.

### To Reproduce

1. Go to 'Sidebar:Add External Folder...'
2. Choose a folder containing subfolders and click 'Open'
3. Error: Folder imported but only containing txt files in root or only 2-3 subfolders of 10 subfolders

### Expected behavior

I expect to be able to import all folders containing subfolders with normal filenames and normal formatted txt files.

### FSNotes version

5.1.3 (506)

### macOS/iOS version

11.2.3

### Additional context

The import of folders work if I import them manually one-by-one, but this is cumbersome.
I've also experienced that these imports have disappeared when closing and restarting the app.

**Comment by supermensa** [comment]
**Update:**
Folder/file permissions didn't seem to be the problem, so I went manually through all the folders and putting them all into root. Digging into all these sub-sub-folders, I actually did discover one or two jpg files or a pdf file. Some of the filenames deeper down also had spaces in them, so possible one of these factors caused the bug.

Anyways, with these changes FSNotes seem to be working normally.

**Comment by gingerbeardman** [comment]
Thanks for the analysis!

**Comment by ksdomino** [comment]
Agreed. I had the same issue but with fonts and some other files (I just removed the offending folder) and it seems to be ok for now. A full fix would mean that FSNotes would have to fully ignore unexpected filetypes or the user would have to be instructed to create a folder structure that only contains certain filetypes eg .txt, .MD, *RFT?/RFTD?..anyways it's apparent now that you cannot use fsnotes with project folders that contain other filetypes, you have to use it to maintain a separate and clean notes system in parallel with your projects folders.

**Comment by appscaptain** [comment]
Same issue here. Very difficult to figure out which files cause this.

Indeed ignoring certain certain filetypes would be excellent. For instance FSNotes shows .php files from projects which is a problem, bash files etc.

Being able to exclude certain filetypes also means being able to use an existing directory in one's currently filestructure as the folder for organizing one's text files. Instead of having 2 different folders with the same hierarchy where one of them is just for FSNotes. Not only for the sake of organization but also for performance reasons.

**Comment by glushchenko** [comment]
Now folders quantity unlimited, but time to scan is limited to 30 seconds.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
