### ISSUE TITLE
macOS: slow startup with many notes

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1248]
#### Discussed in https://github.com/glushchenko/fsnotes/discussions/1233

<div type='discussions-op-text'>

<sup>Originally posted by **gingerbeardman** October 30, 2021</sup>
This is my growing catalogue of vintage software CDs contents.

- 124 txt files
- 485,000 total lines
- UTF-16LE
- ach file has between 7 and 21000 lines

**FSNotes handles them "OK", but startup is very slow ~9 seconds**

FSNotes on iOS startup is instant, with the same notes folders in iCloud.
</div>

### To Reproduce

1. Extract this zip to a folder in your FSNotes iCloud [archive.zip](https://github.com/glushchenko/fsnotes/files/7608646/archive.zip)
2. Open FSNotes
3. Observe startup delay (~9 seconds for me)

zip stats:
- 180 text files
- 348992 lines
- 50.7 MB

### Expected behavior

- no delay during startup of FSNotes (iOS has no delay)

### FSNotes version

- 5.1.3 (macOS)
- 4.8.5 (iOS)

### macOS/iOS version

- 11.6.1 (macOS)
- 14.8.1 (iOS)

### Additional context

- startup delay is the same if I rename the .txt files to .md
- startup delay is the same even if I HFS+ compress the files

**Comment by glushchenko** [comment]
Hi, Matt! 

This is not bug. On iOS version loading optimised, and app started after Inbox loading. On macOS version after all files was loaded and tags scanned.

**Comment by gingerbeardman** [comment]
Interesting!

Performance is disappointing on macOS with this set of files.

**Comment by glushchenko** [comment]
I will check later, but I think the load optimization is just needed, I planned to do this.

**Comment by octos** [comment]
Same here — even after disabling tag scanning and syntax highlighting, FSNotes feels slower than it should.

**Comment by gingerbeardman** [comment]
How many notes @octos?

I only have 221 notes and it opens instantly.

**Comment by glushchenko** [comment]
How many files at all in the scanned directories, not only notes.
