### ISSUE TITLE
Lists when code block highlighting enabled

### ISSUE THREAD

**Issue by BradyRosino** [glushchenko/fsnotes#125]
Apologies if I am missing something obvious here, but is it currently not possible to have list items when code block highlighting is enabled?

For example
```
- Item 1
    - Item 2
```

OR

```
1. Item 1
    1. Item 2
```

In this example, Item 2 has has code block highlighting enabled on it. I'd expect standard markdown code blocks to only interpret the indent as a code block if the line above is either a blank line... or another line of the code block.

Let me know if I'm missing something sill, if not, I hope we can see this fixed sooner or later? I really love having the code highlighting, but this bug requires that I keep it disabled.

**Comment by gingerbeardman** [comment]
Can you post a full sample document and screenshot of what you are seeing and what you expected to see (if possible)?

**Comment by gingerbeardman** [comment]
Ah, I see what you mean. Here’s the problem:

> To produce a code block in Markdown, simply indent every line of the block by at least 4 spaces or 1 tab. [ref](https://daringfireball.net/projects/markdown/syntax#precode)

So use less than 4 spaces, and do not use a tab, to indent your nested list.

**Comment by BradyRosino** [comment]
Reviewing the same spec from Gruber. 4 spaces or one tab is the only appropriate way to do a list item.

> List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab:

Doing anything less will produce unpredictable results depending on the Markdown compiler.

**Comment by gingerbeardman** [comment]
Interesting! The markdown can mean two things. More on this:

* https://meta.stackexchange.com/questions/3327/code-block-is-not-properly-formatted-when-placed-immediately-after-a-list-item/99637#99637

Trying the below snippet in some markdown previewers I have to hand. 

(4 space or tab indents)

```
1. List
    1. Nested list
    2. Second item

    Code block

Test
```

Only one editor I have installed renders it as a code block:
* Sublime Text

All others render it as a part of the first list item:
* original markdown
* GitHub comment
* Visual Studio Code
* TextMate
* [dillinger](https://dillinger.io)


For those that see it as a list item, the code block can sometimes be forced to be separate by adding an extra line break (dillinger) or a line break with just a space character on it (TextMate). But for some you need to put some actual text, a HTML comment will do, between the list and the code block (VSCode).

FSNotes on the other hand is a bit undecided about it:

AGIF:
![2018-03-15 12_27_25](https://user-images.githubusercontent.com/49612/37463159-43d73cf4-284c-11e8-8760-1bfcdd4e58b7.gif)

**Comment by gingerbeardman** [comment]
Reported: https://github.com/iwasrobbed/Down/issues/85

**Comment by BradyRosino** [comment]
Agreed that this is an issue in Down. Here is their specific issue. Down is based on CommonMark and in the spec:

http://spec.commonmark.org/0.28/#indented-code-blocks

> 4.4 An indented code block is composed of one or more indented chunks separated by blank lines. 

They are specifically missing the requirement that to be interpreted as a code block, it must be fenced also by blank lines.

**Comment by BradyRosino** [comment]
This would also make the image shared in this thread a valid code block, it is still however an issue without the blank line.

**Comment by iwasrobbed** [comment]
Happy to accept any pull requests into Down to address this, but unfortunately a bit booked up at the moment 👍 It's also worth noting that Down is just a Swift wrapper for [cmark](https://github.com/commonmark/cmark) so feel free to try a newer version and see if it resolves your issue

**Comment by gingerbeardman** [comment]
I think the issue is Highlighter.js that Down uses.

Your example:

```md
- Item 1
    - Item 2
```

CommonMark generates:
```html
<ul>
<li>Item 1
<ul>
<li>Item 2</li>
</ul>
</li>
</ul>
```

original daringfireball MarkDown dingus generates:
```html
<ul>
<li>Item 1
<ul>
<li>Item 2</li>
</ul>
</li>
</ul>
```

They are the same.

So I would say that the syntax colouring is the thing that is missing the blank line requirement. The one they use in Down is old and abandoned with hundreds of issues and many PR waiting on GitHub.

**Comment by gingerbeardman** [comment]
@BradyRosino Where did you read about it being blank lines to qualify as code block? 

https://github.com/commonmark/CommonMark-site/issues/10#issuecomment-373480676

**Comment by BradyRosino** [comment]
Found it directly on in the CommonMark specification (latest version 0.28) which can be found here:

http://spec.commonmark.org/0.28/

Section 4.4 reads:

> 4.4Indented code blocks
>
> An indented code block is composed of one or more indented chunks separated by blank lines. An indented chunk is a sequence of non-blank lines, each indented four or more spaces. The contents of the code block are the literal contents of the lines, including trailing line endings, minus four spaces of indentation. An indented code block has no info string.
> 
> An indented code block cannot interrupt a paragraph, so there must be a blank line between a paragraph and a following indented code block. (A blank line is not needed, however, between a code block and a following paragraph.)

**Comment by gingerbeardman** [comment]
Can you post this on the common mark issue?

**Comment by flowchartsman** [comment]
I feel like this really needs to be addressed.  The most basic explanation problem is that "shift right" does not simply shift the text to the right, it starts a code block!  This should not be. With shift functionality, we should be able to nest and unnest elements exactly as it is done in tools like NVAlt.  Creating code blocks is a handy additional feature, but is otherwise ancillary to the task of notetaking, which should allow us to impose structure on text, as needed, with minimal fuss.

**Comment by flowchartsman** [comment]
I feel like this really needs addressed.  Put most simply, "shift right", does not merely shift right. It either creates a new code block or imposes some extra funky behavior.

I take notes in a nesting fashion which helps me to impose structure on my notes quickly.  nvALT supported this very well, allowing me to do the following:
![texttest](https://user-images.githubusercontent.com/926884/45433937-3f0f4c80-b67b-11e8-8cae-86e7338a4bd5.gif)

When I try it in FSNotes, even with code block highlighting turned off, I get the very-unsatisfying:
![texttest-fs](https://user-images.githubusercontent.com/926884/45434109-9a413f00-b67b-11e8-926e-9c8e57da9649.gif)

Highlighting is nice and all, but it's kind of ancillary to the task of taking notes, which is to quickly impose meaningful structure on text and then find it again.
