### ISSUE TITLE
Linking out of sub-folder doesn't work

### ISSUE THREAD

**Issue by supermensa** [glushchenko/fsnotes#1250]
### Description

Linking from a file in a subfolder into a file in the root notes takes you nowhere.

### To Reproduce

1. Make a link from a file in a sub-folder [FolderA/FolderB/File1] to a file in the root [File2]
2. Click the link

### Expected behavior

I would expect that I could link globally to another file outside of the current folder (assuming that there isn't to be a File1 in both subfolder and root).

### FSNotes version

5.1.3 (506)

### macOS/iOS version

MacOS 11.2.3

**Comment by supermensa** [comment]
Additional note:
I experienced the problem within a search query of tags as well:

In a list of search result for example tag: "Food", in one of these files I link outside the tag collection to a file in the root and it simply links to nowhere when clicked; the FSNotes logo being shown in the preview window instead

**Comment by glushchenko** [comment]
Fixed, thanks!

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.0/FSNotes_5.3.0.zip
