### ISSUE TITLE
Previewing does not displayed indenting

### ISSUE THREAD

**Issue by Brin-o** [glushchenko/fsnotes#1256]
### Description

When previewing a file that has indented text (shift right/left in the format menu) that shift is not displayed inside of the preview.

![Kapture 2021-12-05 at 13 49 51](https://user-images.githubusercontent.com/49071768/144747288-3c40a344-5f53-4266-8143-215a8903e707.gif)

### To Reproduce

1. Create a new note
2. Indent a text using "shift right"
3. Click preview

### Expected behavior

The text should be indented as well

### FSNotes version

Version 5.1.3 (506)

### macOS/iOS version

macOS 12.01

**Comment by tewe** [comment]
The preview interprets a note as [Markdown](https://daringfireball.net/projects/markdown/syntax). Like HTML, Markdown strips leading whitespace (unless preceded by a blank line, in which case it becomes a code block). So IMHO not a bug.

**Comment by Brin-o** [comment]
Hm okay. Is there a way for me to get indentation inside of the composed markdown documents?

**Comment by tewe** [comment]
I don't think so. Without CSS, HTML doesn't really do indentation. But please refer to the "specification" I linked.

**Comment by gingerbeardman** [comment]
FSNotes used the Common mark spec, which is here: https://spec.commonmark.org/0.30/

**Comment by Brin-o** [comment]
Thanks for the response! 
In my notes I use a combination of gifs and indenting a lot, yet gif playback does not work inside of the non-preview mode and indenting does not work inside of the preview :p 

Regardless, thank you for the info!

**Comment by gingerbeardman** [comment]
@Brin-o editing mode uses Native maOS controls, preview mode uses a Web View.

Please file a new issue for GIF playback in edit mode.
