### ISSUE TITLE
Edit mode does not always decorate header text

### ISSUE THREAD

**Issue by Brin-o** [glushchenko/fsnotes#1259]
### Description

Sometimes the header text inside of edit mode does not get bolded. Look at the picture.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/49071768/145183489-d504c040-ef4d-4175-9b61-a11a87a8b3e0.png">

Going on the text with the cursor and then entering a new line does bold it, however the moment I leave the note (select a different note) and come back, the text that I bolded by making a new line below it is not bold anymore.

### To Reproduce

I am not sure what is causing this specific behaviour as it only happens in some notes.

### Expected behavior

Text that's going to be converted into a heading should always be bold.

### FSNotes version

Version 5.1.3 (506)

### macOS/iOS version

macOS 12.0.1

**Comment by gingerbeardman** [comment]
Workaround is to cut and paste the whole note content over itself. This will cause a reformatting.

**Comment by glushchenko** [comment]
Can you provide steps, how to reproduce it?

**Comment by glushchenko** [comment]
Let me know if you have reliable steps for reproduce it. Thanks
