### ISSUE TITLE
Similar nvALT experience when searching and pressing enter

### ISSUE THREAD

**Issue by kevinjalbert** [glushchenko/fsnotes#126]
With nvALT if you are searching and you are halfway completing a note's title, it is actually highlighted and auto-completed. When you hit enter, you are within the note.

In FSNotes Version 1.2.11 (106), it will not auto-complete the search term to match the first note, thus it will always make a new note.

From a _quick_ search and recall perspective I'm used to the type some characters which match the title then hitting enter.

-----

Just a thought, as this was one thing that threw me off. Along with the #82 bit as well.

**Comment by glushchenko** [comment]
Added in 1.6.3
