### ISSUE TITLE
Alpha numeric hex colours highlighted as tags, even with Scan inline tags unchecked

### ISSUE THREAD

**Issue by Joolyan** [glushchenko/fsnotes#1260]
### Description

An updated review of FSnotes, last reviewed at the beginning of the year...

Unfortunately I still have issues with lots of historical notes containing # hex values, which unless they are all numeric (#123456) are identified as tags. Unchecking the 'Scan inline tags' option in preferences, removes the tags for the side panel, however the hex values are still highlight as tags in the note body text.

If tags cannot be disabled, may be the option to use a different tag character may be possible?

### To Reproduce

1. Uncheck the Prefences option 'Scan inline tags'
2. Enter the text #202bfc in the body of a note
3. #202bfc is identified as a tag

### Expected behavior

The hex colour shouldn't be identified as a tag with 'Scan inline tags' unchecked.

### FSNotes version

Version 5.1.3 (506)

### macOS/iOS version

macOS Big Sur version 11.6.1

**Comment by glushchenko** [comment]
Dupe #1243
