### ISSUE TITLE
Note list is shown, even when hidden

### ISSUE THREAD

**Issue by Brin-o** [glushchenko/fsnotes#1263]
### Description

Note list is still visible even when hidden. It's slightly distracting.

### To Reproduce

1. Open FSNotes
2. Go Vies -> Hide Notelist
3. A smudge of the note list is still visible

### FSNotes version

Version 5.1.3 (506)

### macOS/iOS version

macOS 12.01

### Additional context

![notesidebar](https://user-images.githubusercontent.com/49071768/145719110-200032de-989f-4e45-8fb7-11bb6f607a11.gif)

**Comment by glushchenko** [comment]
I dont know how to reproduce it. Please try settings reset and write steps for bug reproduction.

**Comment by Brin-o** [comment]
Hi, how can I reset the settings?

**Comment by glushchenko** [comment]
~/Library/Containers/co.fluder.FSNotes/Data/Library/Preferences/co.fluder.FSNotes.plist
