### ISSUE TITLE
Concept for app icon

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1264]
I've seen discussions about app icon in the past, just had this idea. Not urgent, just wanted to share

<img width="143" alt="Screen Shot 2021-12-15 at 6 42 59 PM" src="https://user-images.githubusercontent.com/22358233/146282005-3f1ced6b-d2fc-4759-ba55-5012c8e99076.png">

**Comment by gingerbeardman** [comment]
FWIW I like this.
