### ISSUE TITLE
Multiexport filetypes option

### ISSUE THREAD

**Issue by kiiiiit** [glushchenko/fsnotes#1265]
**Describe your feature request**
Привет! Отличное приложение. С каждой версией всё лучше и лучше!
1. Скажи, пожалуйста, планируется ли добавление вариантов экспорта созданного файла? Сегодня, к сожалению, доступен только "внешний редактор" и выгрузка в PDF через меню" печать". Было бы здорово получить возможность выгрузки в DOCX, например, или запуск PANDOC для компиляции из приложения напрямую (волшебной кнопкой/сочетанием клавиш, как Typora, например), чтоб не приходилось вручную в терминале вводить каждый раз это.
2. Может и выгрузку в wordpress/medium возможно реализовать? Очень уж это удобно..

**Additional context**
macOS

**Comment by gingerbeardman** [comment]
Use macOS Services or external apps to achieve this. You can do it _today_, no need to wait for requests and additions to FSNotes.

**Comment by kiiiiit** [comment]
> Use macOS Services or external apps to achieve this.
> 
> _You can do it today_, no need to wait for requests and additions to FSNotes.

Thank you for your opinion. I use them (pandoc / mark2 / etc). In my view, the possibility of using it in the application will be more convenient.

**Comment by gingerbeardman** [comment]
More convenient in what way? How do you imagine it integrated into FSNotes user interface?

Here's a macOS service to convert a file to DOCX using Pandoc
- [Pandoc DOCX.zip](https://github.com/glushchenko/fsnotes/files/7756701/Pandoc.DOCX.zip)

I can summon it from Finder, or using a keyboard shortcut (see below), or using Alfred, etc.

<img width="668" alt="Screen shot 2021-12-21 at 16 26 09" src="https://user-images.githubusercontent.com/49612/146964471-bb994762-22d0-46d4-8ff9-ae620a5fcda0.png">

**Comment by gingerbeardman** [comment]
For "Upload to WordPress" there is this: 
- https://github.com/JenniferMack/Upload-to-WordPress
- or https://github.com/JenniferMack/Ulysses-post-to-WP
 
...which makes me think a more useful option for FSNotes would be one to "open note in external app" then we could do anything.
