### ISSUE TITLE
Clicking menu bar icon no longer opens FSNotes window

### ISSUE THREAD

**Issue by markmonroy** [glushchenko/fsnotes#1267]
### Description

Hi. I had grown accustomed to left-clicking on the FSNotes menu bar icon to open the application window. Now when I click on it, it opens the same context menu as if I had right-clicked. Can the old behavior be restored, or turned into an option for people who prefer the context menu?

### To Reproduce

1. Close FSNotes window without quitting
2. Click on menu bar icon

### Expected behavior

FSNotes window should open, ready to search or compose.

### FSNotes version

5.1.3 (506)

### macOS/iOS version

12.1 macOS Monterey

**Comment by glushchenko** [comment]
Works as before, can not reproduce it.

**Comment by markmonroy** [comment]
Hmm, strange. Are you on the latest Monterey as well? On my work computer running Big Sur the app window still opens as expected. That's the only big difference I can think of, and I did just recently update to 12.1.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5.4.0/FSNotes_5.4.0.zip
