### ISSUE TITLE
Hitting cmd+delete in Find/Replace field trashes active note

### ISSUE THREAD

**Issue by hpaves** [glushchenko/fsnotes#1268]
### Description

In macOS, cmd+delete has two main behaviors: 
1) while in a text field, it deletes everything from the cursor to the beginning of the line
2) while having file(s) selected, it trashes the file(s)

This all works in FSnotes as expected, EXCEPT when you're in the Find/Replace fields. In there, hitting cmd+delete trashes the active note instead of deleting the text field content.

### To Reproduce

1. Open any note
2. Hit cmd+f
3. Write something into the find field
4. Hit cmd+delete
5. See the active note disappear (into the trash)

### Expected behavior

In step 5: The content of the find field is deleted from the cursor to the beginning of the line. The active note is NOT trashed.

### FSNotes version

5.2.0 (507)

### macOS/iOS version

macOS 10.15.7 (19H1519)

### Additional context

Identical issue is present in the Replace field.

**Comment by glushchenko** [comment]
Fixed, thanks!

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.0/FSNotes_5.3.0.zip

**Comment by hpaves** [comment]
Perfect! Thank you so much.
