### ISSUE TITLE
Code block in preview mode

### ISSUE THREAD

**Issue by Babelfisch** [glushchenko/fsnotes#1269]
### Description

Code in preview mode is displayed completely differently than in the editor. Font, colors, line height, and more are different.

Simple example in edit mode:

<img width="359" alt="Bildschirmfoto 2021-12-29 um 10 23 42" src="https://user-images.githubusercontent.com/1218405/147647284-bb268b40-0d04-4c6f-bd10-d555389d5aab.png">

And the same in preview mode:
<img width="360" alt="Bildschirmfoto 2021-12-29 um 10 23 51" src="https://user-images.githubusercontent.com/1218405/147647320-e24cb067-30b6-41dd-a390-a6d0d6732487.png">

### To Reproduce

Create a simple code example:

```swift
func test() -> Double {
  return 0.0
}
```

And then switch to preview mode.

### Expected behavior

The code in preview mode should have the same settings as in editor mode or it should be possible to change the settings for preview easily.

### FSNotes version

5.2.0 (507)

### macOS/iOS version

12.1

**Comment by glushchenko** [comment]
Bug related to external library and fixed here https://github.com/raspu/Highlightr/pull/88

Thanks for bug report.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5.3.0/FSNotes_5.3.0.zip
