### ISSUE TITLE
Display does not respect end of fenced code block

### ISSUE THREAD

**Issue by RickCogley** [glushchenko/fsnotes#127]
When I enter three tildes to start a fenced code block in a markdown doc in FSNotes, FSNotes doesn't respect the end three tildes. As I type, it starts formatting as a fenced block should when I enter three tildes and a carriage return, then I enter/paste some code, then put three more tildes on a new line, per the screenshot below. 

FSNotes doesn't detect the end of the fence and just formats stuff below the fenced block, in grey. You can see the "format date in Japanese" part is highlighted grey, where it should not be. Sometimes, more than just the next block gets formatted incorrectly, and the formatting just continues down the document. 

It resolves if I quit FSNotes and Restart. 

* MacOS Version 10.13.3 (17D102)
* FSNotes Version 1.2.11 (106)

<img width="1087" alt="jrc screenshot 2018-03-15 at 12 38 59" src="https://user-images.githubusercontent.com/512328/37443210-fa545d62-284d-11e8-876d-d167ba610033.png">

**Comment by gingerbeardman** [comment]
To reproduce, type a code block and then delete and retype one of the lower backticks. The highlighting does not refresh.

AGIF: 
![new](https://user-images.githubusercontent.com/49612/37458431-f1a82ede-283c-11e8-9c9a-3cee0c8570e8.gif)

When typing to reproduce this I also noticed that
1. if I use the cursor keys to step away from that last back tick, the highlighting is honoured (start of below GIF). 
2.  if I press enter when the final backpack is highlighted (which macOS does to see if I want to type an accented character) the code is not highlighted until I move my cursor back over that section (end of below GIF). 

AGIF:
![more](https://user-images.githubusercontent.com/49612/37458559-49385f7a-283d-11e8-85a7-a45a67735599.gif)

You can fix it without restart by cutting and pasting the whole note.

I think the app needs to force highlighting refresh more frequently.

**Comment by RickCogley** [comment]
Thanks @gingerbeardman. Meanwhile I will do the cmd-a, cmd-x, cmd-v and feel rather emacs-y. 😸

**Comment by gingerbeardman** [comment]
Do you use any software that could map that key combo to a single function/hotkey? 

I use [Keyboard Maestro](https://www.keyboardmaestro.com/main/) and/or [Alfred](https://www.alfredapp.com/) depending on what I want to achieve. Many options.

**Comment by hanche** [comment]
This is such a long standing bug, and really annoying – though a workaround does exist. It would be nice if received some attention, or at least a comment by the developer.

**Comment by buddax2** [comment]
@hanche I will try to debug the issue later today

**Comment by hanche** [comment]
@buddax2 Thanks! Did you find out anything useful? Event based programming can be quite tricky, I suppose; so I wouldn't be surprised if this one is hard to get to the bottom of.

**Comment by hanche** [comment]
@buddax2 Well, understanding the problem is a good first step towards fixing it. Thanks again!

Here is an idea for one possible fix: Inspect the *change* and, if it involves triple backquotes, reparse the entire text. Otherwise, do as before. It might be a bit simplistic, but at least it is slightly less simplistic than the current approach.

**Comment by hanche** [comment]
I just thought I might mention a workaround I found, for the benefit of others coming here:

Type *six* backquotes on a fresh line. Backspace into the middle and start typing.

**Comment by glushchenko** [comment]
You can insert codeblock from menu too.

**Comment by glushchenko** [comment]
Finally implemented!
