### ISSUE TITLE
Slide menu restoration issue.

### ISSUE THREAD

**Issue by RoyRao2333** [glushchenko/fsnotes#1270]
### Description

If I shrink the slide menu all the way to the left, it can't be easily restored since you can't click right onto the edge of it. Especially the notes list.

<img width="1119" alt="Screen Shot 2021-12-30 at 10 28 00" src="https://user-images.githubusercontent.com/31413093/147717077-a6b23c8a-87a9-4e7a-bf97-6bcb856d242f.png">

<img width="1117" alt="Screen Shot 2021-12-30 at 10 28 10" src="https://user-images.githubusercontent.com/31413093/147717080-2ce72c6d-c72e-4003-b9d6-41e91bcf7b73.png">

Can you add a toolbar button to toggle these slide menus? It would be a lot easier to use.

Thanks for the great app!

### To Reproduce

Just slide the edge of each split view and shrink them to the minimum size.

### FSNotes version

Version 5.2.0 (507)

### macOS/iOS version

macOS 12.0.1

**Comment by gingerbeardman** [comment]
There are already toggles, check the View menu.

**Comment by RoyRao2333** [comment]
> There are already toggles, check the View menu.

Yes, I've found it. Thanks!
