### ISSUE TITLE
not sync data between iOS and macOS

### ISSUE THREAD

**Issue by phantuanvi** [glushchenko/fsnotes#1273]
### Description

when i add data on iPhone FSNote on Macbook has no data

### To Reproduce

case 1:
1. Go to  FSNotes on iOS
2. Add a new note
3. Go to FSNotes on macOS
4. can't see a new note on macOS
-----

case 2:
1. Go to  FSNotes on macOS
2. Add a new note
3. Go to FSNotes on iOS
4. can't see a new note on iOS

### Expected behavior

sync data between ios and macos

### FSNotes version

Version 5.2.0 (507) on macOS, Version 4.8.6 (229) on iOS

### macOS/iOS version

iOS 15.0.2, macOS 12.1

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/wiki/iCloud-Drive-syncing-between-iOS-and-macOS
