### ISSUE TITLE
Editor does not highlight URL with unicode domain

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1274]
### Description

A URL can have non-ASCII characters in both host and path parts. While the preview turns both kinds into link, the editor will only highlight unicode paths, not unicode hosts.

### To Reproduce

1. Paste https://brückentage.info into a note (no special Markdown around it)

### Expected behavior

Highlighted as a clickable link.

### FSNotes version

5.3.0

### macOS/iOS version

macOS 10.14.6

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.3/FSNotes_5.3.3.zip

**Comment by tewe** [comment]
Works for me. Thanks!
