### ISSUE TITLE
Crash in 5.3.1

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1275]
### Description

[FSNotes_2022-01-09-230749_matt.crash.zip](https://github.com/glushchenko/fsnotes/files/7836167/FSNotes_2022-01-09-230749_matt.crash.zip)

### To Reproduce

Happened launching or quitting.

### FSNotes version

5.3.1

### macOS/iOS version

11.6.2 (20G314)

**Comment by glushchenko** [comment]
how to reproduce this?

**Comment by gingerbeardman** [comment]
It happened when quitting the app.

Not sure about exact repro.

Crash seems to be in menu handler?
