### ISSUE TITLE
Blank note created automatically

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1276]
### Description

When switching back from another app to FSNotes a blank note is created.

### To Reproduce

1. Open FSNotes
2. Switch to other apps for a while
3. Switch back to FSNotes using Cmd+Tbs
4. Blank note is created

### Expected behavior

- notes should only be created by user

### FSNotes version

5.3.1

### macOS/iOS version

11.6.2 (20G314)

**Comment by glushchenko** [comment]
Can anyone confirm? Very strange behavior.

**Comment by gingerbeardman** [comment]
I am back on 5.2.0 for now and it's not happening.

**Comment by glushchenko** [comment]
I believe Matt, but maybe you modified the shortcuts? It looks like this only happens on your computer.

**Comment by gingerbeardman** [comment]
Let's wait to see, 5.3.1 only just released.

I'll keep using it tomorrow.

**Comment by gingerbeardman** [comment]
Closing until I see it happen again!

Thanks
