### ISSUE TITLE
Momentary beach ball after focusing the window (consistent)

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1277]
### Description

If you're using another application, you can't just click on FSNotes and start typing. Have to wait for the beach ball first

### To Reproduce

1. Open FSNotes and another application
2. Click on the other application window
3. Click on FSNotes and start typing
4. It doesn't let you start typing right away.  There's a lag and beach ball every time. The bug is consistent

### FSNotes version

5.2.0

### macOS/iOS version

12.0.1

### Additional context

2020 M1 Mac

**Comment by glushchenko** [comment]
5.2.0 or 5.3.0?

**Comment by nth-chile** [comment]
Oh I didn't see that there was a new release. I'm on 5.2.0

**Comment by glushchenko** [comment]
Please try last version https://github.com/glushchenko/fsnotes/releases/download/5.3.1/FSNotes_5.3.1.zip

**Comment by nth-chile** [comment]
Oh, we can close this. It doesn't have anything to do with FSNotes. I can repro it for other applications too. My computer is just slow
