### ISSUE TITLE
iOS and desktop not syncing at all

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1278]
### Description

Editing a note on desktop doesn't update mobile, and editing a note on mobile doesn't update desktop.

### To Reproduce

My guess is that the steps to repro are more complicated than this. At the moment, though, nothing will sync. No conflict files get created or anything.

1. Edit the same note on desktop and mobile. For me, no syncing of any kind happens :/.

### FSNotes version

macos: 5.3.1; ios: 4.8.6

### macOS/iOS version

macos: 12.0.1 ios: 14.7.1

**Comment by glushchenko** [comment]
Please use this https://github.com/glushchenko/fsnotes/wiki/iCloud-Drive-syncing-between-iOS-and-macOS

Sync layer is iCloud Drive, and i can not fix it.
