### ISSUE TITLE
the problem about display in chinese[ Code block in edit mode ]

### ISSUE THREAD

**Issue by P4ck** [glushchenko/fsnotes#1279]
### Description

When I am in the editing mode, I directly enter Chinese and Chinese comments in the code block, the Chinese is not displayed, and it will be displayed when I return to the preview mode. I tried changing a lot of code fonts and still no solution. Thank you very much for helping me.

### To Reproduce

1、Code block in edit mode
![image](https://user-images.githubusercontent.com/26513808/149280979-79cfcc0a-3d5f-4389-906f-666112efc6ed.png)

2、Press enter：the text is not displayed at this time
![image](https://user-images.githubusercontent.com/26513808/149281211-0164b440-660c-425f-bb3a-d225a385dc20.png)

3、Preview mode
![image](https://user-images.githubusercontent.com/26513808/149281050-d8de2ebc-0d50-416d-a90e-e1198e5a73c1.png)

4、Return to the code block in edit mode, the text will be displayed
![image](https://user-images.githubusercontent.com/26513808/149281696-bdab4426-80d3-4234-b797-8c8cbad3f142.png)

### Expected behavior

Chinese can be displayed normally in code blocks in edit mode.

### FSNotes version

Version 5.3.4 (513)

### macOS/iOS version

macos Big Sur 11.2.3

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.7/FSNotes_5.3.7.zip

**Comment by P4ck** [comment]
Thank you very much for your selfless help.
