### ISSUE TITLE
Untitled Notes that are in folder are not displayed?

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#128]
Reproduce:
1. create new note
2. enter some content
3. quit `FSNotes`
4. relaunch `FSNotes`
5. Untitled Note is not there
6. view `FSNotes` folder, `Untitled Note X` is there

**Comment by gingerbeardman** [comment]
Actually, it seems that sometimes they are displayed. Not sure why right now.

**Comment by glushchenko** [comment]
Fixed in #133
