### ISSUE TITLE
Windows not updating (change TextBundle-note in external editor)

### ISSUE THREAD

**Issue by crash-bash** [glushchenko/fsnotes#1280]
### Description

A note in TextBundle format is not updated in the FSNotes window after being modified and saved in an external editor.

At the same time, if the note format is markdown, then everything is fine. The text in the FSNotes window is immediately updated.

### To Reproduce

1. Find note in TextBundle format
2. Double click on a note to open it in an external editor
3. Make changes to the note, save and close the external editor
4. The note in the FSNotes remained unchanged.

It is possible to mistakenly change this note again and lose all the changes that were made in the external editor

### FSNotes version

5.3.4

### macOS/iOS version

12.1

### Additional context

External text editor: "CotEditor"

**Comment by glushchenko** [comment]
Can not reproduce, seems this problem on your side.
