### ISSUE TITLE
How does one build the project?

### ISSUE THREAD

**Issue by keshaaaaav** [glushchenko/fsnotes#1281]
I really want to contribute to FSNotes but can't really seem to figure out how to build the project? Steps I've taken so far:

- Re-initiated the podfile
- Installed pods

<img width="1552" alt="Screen Shot 2022-01-14 at 2 29 18 PM" src="https://user-images.githubusercontent.com/65015627/149487830-f4c478b0-dc66-466d-b251-eaaffc5de3d7.png">

<img width="1552" alt="Screen Shot 2022-01-14 at 2 34 51 PM" src="https://user-images.githubusercontent.com/65015627/149488795-d838ea79-7a46-443a-ba51-24145ff2b6f1.png">

I'm on a arm64 machine btw

**Comment by gingerbeardman** [comment]
did you try:

```
$ pod deintegrate
$ pod install
```

**Comment by keshaaaaav** [comment]
No, I didn't previously tried to deintegrate pods but once I do: 

<img width="1792" alt="Screen Shot 2022-01-14 at 11 35 41 PM" src="https://user-images.githubusercontent.com/65015627/149563880-01b0a34e-9069-4d6d-8473-f9d0e57518f4.png">


and I have checked that both Highlightr and NightNight are specified in the podfile

<img width="794" alt="Screen Shot 2022-01-14 at 11 31 51 PM" src="https://user-images.githubusercontent.com/65015627/149563339-4d45b534-9754-4559-829d-bb3ae1ca1890.png">

**Comment by keshaaaaav** [comment]
Anything I can do to fix this? @gingerbeardman

**Comment by glushchenko** [comment]
@keshaaaaav pod install

**Comment by keshaaaaav** [comment]
@glushchenko I already tried running pod install, still the same issue

**Comment by keshaaaaav** [comment]
@glushchenko any help would be massively appreciated.

**Comment by gingerbeardman** [comment]
Please delete your files and start again.

Keep an note of what you do, step by step, until you get stuck. Then post them here.

I would like to stress again that you need to open the Xcode workspace file, not the project file.
