### ISSUE TITLE
`direction in subgraph` syntax for `mermaid` is not supported

### ISSUE THREAD

**Issue by mind1949** [glushchenko/fsnotes#1282]
### Description

[`direction in subgraph` syntax](https://mermaid-js.github.io/mermaid/#/flowchart?id=direction-in-subgraphs) for `mermaid` is not supported.

<img width="476" alt="图片" src="https://user-images.githubusercontent.com/19871320/149607271-b1402593-db1b-487e-ad04-1c20320cdfd6.png">

### To Reproduce

1. Write a simple mermaid flowcharts
```mermaid
flowchart TD
    A --> B
    subgraph TOP
      %% direction LR
      a --> b
   end
```
2. Open in preview mode
<img width="586" alt="图片" src="https://user-images.githubusercontent.com/19871320/149607377-4a60ed0c-60ba-4608-9c1a-6cc346877924.png">

3. Remote comment at line 4
```mermaid
flowchart TD
    A --> B
    subgraph TOP
         direction LR
	 a --> b
    end
````

4. Open in preview mode
<img width="476" alt="图片" src="https://user-images.githubusercontent.com/19871320/149607271-b1402593-db1b-487e-ad04-1c20320cdfd6.png">

### Expected behavior

<img width="338" alt="图片" src="https://user-images.githubusercontent.com/19871320/149607462-c76342cc-5f7f-4e42-bef4-2034e4804595.png">

### FSNotes version

Version 5.3.3 (512)

### macOS/iOS version

10.14.2

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
