### ISSUE TITLE
When entering "`" in a very large file, it will be severely stuck

### ISSUE THREAD

**Issue by marcocpt** [glushchenko/fsnotes#1283]
### Description

Articles are approximately 80,000 characters.

Starting to type anything is very stuttering, which is relieved by modifying the code in `EditTextView.swifg`:

```swift
     override func draw(_ dirtyRect: NSRect) {
         super.draw(dirtyRect)

         guard UserDefaultsManagement.inlineTags else { return }
         return // add
         if #available(OSX 10.16, *) {
                ...
         }
     }
````

But typing "`" still lags

### FSNotes version

5.3.4

### macOS/iOS version

11.2.1

**Comment by glushchenko** [comment]
Can not reproduce, seems it fixed.

**Comment by aoaim** [comment]
> Can not reproduce, seems it fixed.

There are still performance issues.

When I edit a Chinese blog post locally (461 lines, 12644 characters), which contains several basic Markdown structures such as multiple levels of headings `#`, code blocks ` ```code``` `, inline code `code` , blockquotes, etc., the editor becomes extremely sluggish.

I haven’t tested other cases yet, but I noticed that every time I edit a backtick ("`"), the software freezes for about 1 seconds, and the cursor turns into the spinning wheel.

**Comment by glushchenko** [comment]
I am working on it just now.
