### ISSUE TITLE
Visual bug: markdown headings treated as tags

### ISSUE THREAD

**Issue by tadamcz** [glushchenko/fsnotes#1284]
### Description

https://user-images.githubusercontent.com/43300673/150168997-a5e88b25-1f17-4d6b-93b3-7cd4b5628713.mp4

### To Reproduce

1. Type `#hello`
2. Insert a space after the `#`

### FSNotes version

5.2.0

### macOS/iOS version

11.6.2

**Comment by glushchenko** [comment]
Hi! 5.2.0 is an outdated version. Already fixed.

**Comment by tadamcz** [comment]
Confirmed fixed in 5.3.4. Thanks!
