### ISSUE TITLE
Tags on a separate line slow down rendering

### ISSUE THREAD

**Issue by umputun** [glushchenko/fsnotes#1288]
### Description

Adding tag(s) on the separate line makes the note extremely slow to render.

### To Reproduce

1. Create a new note
2. put something like this in:
```
# this is a test

blah
blah

#blah
```
3. Try to edit this note, for example, add a new line, or remove a line. 
4. See how visibly slow it refreshes the note

### FSNotes version

5.3.4 (513)

### macOS/iOS version

12.2

### Additional context

The issue reproducible on both macs I have  - iMac Pro (2017) 3.2 GHz 8-Core Intel Xeon W 64G and MacBook Pro M1 Max, 64G

**Comment by gingerbeardman** [comment]
@umputun please fill out the issue in detail, thanks.

**Comment by gingerbeardman** [comment]
@umputun please remove the "to reproduce" section as it is confusing

**Comment by glushchenko** [comment]
I know about this bug, I'll try to fix it before the release of the next Radio-T :)

**Comment by glushchenko** [comment]
Fixed: https://github.com/glushchenko/fsnotes/releases/tag/5.3.5

**Comment by umputun** [comment]
thx. Looks like it was fixed in 5.3.6 and I can't reproduce it anymore.
