### ISSUE TITLE
Still seeing previous bug "Sort by date doesn't always work #636"

### ISSUE THREAD

**Issue by lewallen** [glushchenko/fsnotes#1289]
### Description

This is the same bug described in https://github.com/glushchenko/fsnotes/issues/636. Quoting from the original issue:

> The notes are almost never in "modification date" order, even though that's what I have chosen ... this is a problem only when I am filtering the notes list by typing in the "Search or create" field.

That issue was closed, but I see the same bug. Before I search, the notes list is properly ordered (by modification date), but the order changes after searching. The same bug is present in the iphone app. Here is a screenshot of an incorrect sort, in case that is helpful.

<img width="74" alt="Screen Shot 2022-02-05 at 8 56 54 PM" src="https://user-images.githubusercontent.com/8147432/152657182-cfb1f348-c759-40c2-a5a7-fa55a170d550.png">

Thanks for any help/feedback on this!

### To Reproduce

See #636.

### FSNotes version

5.3.5

### macOS/iOS version

MacOS Monterey, Apple M1 chip

**Comment by glushchenko** [comment]
Hi, @lewallen 

This is by design, sorting doing with priority:

1) First showing notes with search query in title (sorted by date)
2) Then notes with query in body (sorted by date)
