### ISSUE TITLE
FS Note doesn't start when there are too many files on Google Drive

### ISSUE THREAD

**Issue by President** [glushchenko/fsnotes#1291]
### Description

I configured FS Note (OS X) to start from my Google Drive root folder (with many many files) and it cannot start.

### To Reproduce

1. Start FS Note
2. Recondigure it to use Google Drive folder with thousands of folders and files 
3. It will try ti restart and try starting forever - it seems it tries to read all the files - which means to download 1Tb from google

If it cannot work this way I'd expect to reset settings after it's restart. But no - it starts reading the whole google drive. So now the app cannot be started. Reinstall (via brew reinstall --cask fsnotes) didn't help.

### Expected behavior

1. App should work work Google Drive - doesn't matter how many files are there and w/o downloading them all
2. If #1 is not possible - at least there should be way to rollback to previous workable settings (initial configuration)

### FSNotes version

brew install --cask fsnotes

### macOS/iOS version

OS X 11.6.1

**Comment by glushchenko** [comment]
Hi, Konstantin!

Preferences location here:

https://github.com/glushchenko/fsnotes/wiki/Preferences-location

Just delete it and start again. Thank you for feedback.

**Comment by President** [comment]
Thank you.
It helped!

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
