### ISSUE TITLE
Pasting a URL with encoded URL parameter results in unexpected changes

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1292]
### Description

I have a URL which takes an encoded URL as parameter. Pasting this into FSNotes results in the parameter URL being changed.

### To Reproduce

1. paste the following URL into a note
   `https://www.example.com/?url=https%3A%2F%2Fexample.com%2Fp%3Dtest`
2. it is unescaped to the following: parameter URL contains both `://` and `%3A%2F%2F`
   `https://www.example.com/?url=https://%3A%2F%2Fexample.com%2Fp%3Dtest`

### Expected behavior

- text should remain as pasted

### FSNotes version

5.3.5 (514)

### macOS/iOS version

12.2 (21D49)

**Comment by glushchenko** [comment]
Hi, Matt, I am trying but no any changes in url. Can you record video? I will be grateful.

**Comment by gingerbeardman** [comment]
Here we go

https://user-images.githubusercontent.com/49612/163721949-67b8650b-4f42-4888-9632-58b99aea3f1e.mov

My text area "substitutions" settings
<img width="155" alt="Screen shot 2022-04-17 at 16 46 24" src="https://user-images.githubusercontent.com/49612/163721972-1df79df3-ccd8-4d09-99a2-a7a50bb91437.png">

**Comment by glushchenko** [comment]
https://user-images.githubusercontent.com/1089917/167186133-6ff5860a-2454-4c2c-98c9-91d89d5640db.mov

**Comment by glushchenko** [comment]
Same with substitutions:

https://user-images.githubusercontent.com/1089917/167186442-157ac21c-42b4-42ca-92c8-19b972bdd0c4.mov

**Comment by tewe** [comment]
I can't reproduce this, either. I'd ask where you are copying *from*, but the screen recording shows the text changing after insertion, so it must be something in the OS.
