### ISSUE TITLE
New Line on Lists Should Create new List Element

### ISSUE THREAD

**Issue by MyYogurt** [glushchenko/fsnotes#1299]
**Describe your feature request**
When creating a new line in a list, create a new list element of the text to the right of the cursor. Currently, the text right of the cursor on the line is not included in the list.

Example
```
- My (cursor here)list

After pressing enter, there should be two list elements:
- My
- list

Currently, this is the output:
-My
 list
```
**Additional context**
This affects both the macOS and iOS versions. I am currently using version 5.3.6 on macOS and version 4.8.8 on iOS.

**Comment by tewe** [comment]
Markdown allows multiple paragraphs in a list item, by requiring matching indentation. So if this is added there should be a modifier key you can hold to override it.
