### ISSUE TITLE
Change keyboard shortcut to select location/search bar

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#13]
Esc is a non-standard shortcut to select a search or location bar.

It's off the main keyboard so it's slower to hit, and it's missing entirely from the physical keyboards of the newest Macbooks.

I suggest you copy nv/ALT and use Cmd-L (which matches expectations from web browsers).

Esc is a good key to deselect the location bar (and empty the preview pane), because it's a less integratal part of the app's functionality.

**Comment by jeff-h** [comment]
Funny, I never knew about Cmd-L and for years have been hitting Esc to search my notes in nvALT! The muscle-memory is pretty strong on keyboard shortcuts in an app like nvALT. Perhaps we can have the following, as per nvALT:

* cmd-L — makes the search field active, and highlights the contents without removing them
* esc — makes the search field active, but empties it and consequently deselects any currently-selected note
