### ISSUE TITLE
List indentation jumps back and forth when typing text on iOS

### ISSUE THREAD

**Issue by NoNonsenseDev** [glushchenko/fsnotes#1300]
### Description

Please watch the video attached below
https://user-images.githubusercontent.com/1917237/154134943-d8a23450-15b4-4122-9363-6b707d4a62ff.mov

### To Reproduce

1. Open a note
2. Create a list with a couple of items
3. Introduce a second layer of the list underneath any list item
4. See how the indentation of the newly created list shifts to the right while typing

### Expected behavior

The indentation of lists should not change while typing

### FSNotes version

4.8.8 build 231

### macOS/iOS version

15.3.1

**Comment by glushchenko** [comment]
Nice catch, will be fixed ASAP.

**Comment by glushchenko** [comment]
Fixed in FSNotes 5.0
