### ISSUE TITLE
Git history broken?

### ISSUE THREAD

**Issue by tadamcz** [glushchenko/fsnotes#1301]
### Description

I think `Save revision` and `back up now` are not doing anything.

![image](https://user-images.githubusercontent.com/43300673/154453706-0b5fb1e2-0c96-464a-82d6-34909f313f83.png)
![image](https://user-images.githubusercontent.com/43300673/154453859-465f634e-ce49-42d6-a709-b694dd4b58a0.png)

### To Reproduce

1. Save revision
2. back up now
3. no new git commits are made

### FSNotes version

Version 5.3.5 (514)

### macOS/iOS version

11.6

**Comment by glushchenko** [comment]
Trying reproduce it, but works fine for me. And if you try to change the path to repositores?

**Comment by tadamcz** [comment]
Deleting the repo fixed it, which is good enough for me right now. Will investigate more if it happens again.

**Comment by smdnv** [comment]
Hello! Thank you for fsnotes, I think, it would be my new app for making notes))

I have the same issue with git backup.
How can I debug this problem? Does the app create any log file in system console.app or other place that I can read?
Can a different git version that is installed by brew be an issue?

What I tried to do:
1. Reinstall app and restart notebook
2. Change git repository path
3. Change auto/manual snapshots
    - I tried to save notes manually with the "Save revision" button, but it didn't work. I didn't get any error or popup message. New repository in dir wasn't created.
4. Init empty git repository in backup dir
    - Also after saving a note I didn't get new commits in repo.

My env:
- macos: 12.3.1 (m1)
- fsnote: v5.3.8 build 519 (installed from app store)
- git version in fsnote: 2.3.2
- git version in system (installed by brew): 2.35.1
