### ISSUE TITLE
Can't add an anchor link when header has spaces

### ISSUE THREAD

**Issue by kruperfone** [glushchenko/fsnotes#1302]
### Description

I've tried to create an anchor link in the following format
Link: `[some header](#some-header)`
Header: `## Some Header`
But it works only if I'll remove spaces from the header (and dashes from the link)

### To Reproduce

1. Go to a new or existing note editor
2. Type '## Some Header'
3. Type '[some header](#some-header)' on a new line
4. Tap on `[some header]`
5. Error message: `The application can't be opened. -50`

### Expected behavior

Should scroll to `## Some Header`

### FSNotes version

5.3.6 (515)

### macOS/iOS version

-

### Additional context

Maybe it should be a feature request since not every markdown editor supports this format, but I didn't find another way to create this link, so I chose bug report

**Comment by glushchenko** [comment]
Thank you for bug report, fixed.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5.4.0/FSNotes_5.4.0.zip
