### ISSUE TITLE
Clicking file: link does nothing

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1304]
### Description

The Markdown preview in FSNotes does not seem able to open file: links.

### To Reproduce

1. Edit a note
2. Insert `Click [here](file:///Users/...txt)` using a valid path to an existing file
3. Toggle preview
4. Click the link

Nothing happens.

### Expected behavior

The app handling that file type opens. Possible after a confirmation dialog like https://marked2app.com

### FSNotes version

5.3.6

### macOS/iOS version

macOS 12.2.1

### Additional context

A file URL not formatted as a link is not recognized, but most apps don't do that.

**Comment by CarlMangno** [comment]
Yes, I would appreciate this being implemented as well please.

**Comment by gingerbeardman** [comment]
Can you not use relative path inside your FSNotes structure?

Or is the link to a file that is not a note?

**Comment by tewe** [comment]
Yes. I want to be able to link to any file, anywhere.

**Comment by CarlMangno** [comment]
Same for me. I would like to point to a file anywhere in the filesystem. This is useful to link to a file or directory that does not logically belong in the notes directory.

As tewe has pointed out, this already works just fine in editing mode but does not work in preview mode.
It is part of the Markdown specification.

**Comment by CarlMangno** [comment]
Incidentally nvAlt which is inferior to FSNotes in many ways and which I migrated away from to take up (enthusiastically) FSNotes, does have one nice feature. When one drags a directory from Finder to the nvAlt widow, there is a pop-up which offers the option of creating an Alias (that is a link) to the directory.

**Comment by gingerbeardman** [comment]
Please add that one as an extra feature request

**Comment by tewe** [comment]
> Can you not use relative path inside your FSNotes structure?

Those don't work either, for anything that is not a note, e.g. a PDF file.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by tewe** [comment]
Works for me. Thanks!

Unfortunately I more often use automatic links for file: URIs, and those don't work. But they don't work for http: URIs, either, so I created #1413
