### ISSUE TITLE
Link in code block

### ISSUE THREAD

**Issue by kropochev** [glushchenko/fsnotes#1308]
### Description

An extra character is added to the link - `

### To Reproduce

1. Click on link
<img width="664" alt="Screenshot 2022-02-23 at 12 50 05" src="https://user-images.githubusercontent.com/8565494/155279393-bfa4dc33-f7af-4153-8f38-5227eb9c4f77.png">
2. Opening browser link with additional symbol 
<img width="412" alt="Screenshot 2022-02-23 at 12 51 36" src="https://user-images.githubusercontent.com/8565494/155279624-845ef98d-80d1-4ae6-8ade-bccb93896175.png">

### FSNotes version

v5.3.4 build 513

### macOS/iOS version

10.15.7

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.7/FSNotes_5.3.7.zip
