### ISSUE TITLE
Bug_2

### ISSUE THREAD

**Issue by vaistov** [glushchenko/fsnotes#1309]
### Description

1) Не работают в разметке верхние и нижние индексы.
2) Не отображает в предпросмотре табуляцию.

### FSNotes version

5.3.6 (515)

### macOS/iOS version

 Big Sur 11.6.4

**Comment by glushchenko** [comment]
1. Это не баг, а фича, но я подумаю что можно сделать.
2. Можно подробнее, какие индексы?
3. Табуляция в markdown и не будет отображаться, это по дизайну — таб или 4 пробела это блок кода.

**Comment by vaistov** [comment]
Про табуляцию понял спасибо.
Например верхний индекс: 10^-43.

**Comment by glushchenko** [comment]
Допустим вводу в редактор эе 10^-43, и что должно произойти с разметкой? И почему это баг?

**Comment by vaistov** [comment]
Получается только через MathJax в таком виде $10^{-43}$ можно работать?

**Comment by glushchenko** [comment]
Нельзя, можно так: $$10^{-43}$$
$$10^{-43}$$ два доллара.

-- 
Yours faithfully,
Oleksandr Hlushchenko

> 23 февр. 2022 г., в 15:26, Vadim Aistov ***@***.***> написал(а):
> 
> $10^{-43}$
