### ISSUE TITLE
Hard crash when renaming a note more than once in succession

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#131]
1. New note
2. Cmd+R to rename note
3. type something; press Enter to accept
4. Cmd+R to rename same note (focus will be in search bar)
5. edit not name to add or remove characters; press Enter to accept
6. **hard crash**

I can get this to reproduce “sometimes”, might take more than one attempt. Delete note and restart in between.

AGIF:
![2018-03-15 13_38_39](https://user-images.githubusercontent.com/49612/37466722-669ed238-2856-11e8-877d-127dd3664be2.gif)

crash dump:
https://privatebin.net/?8b2c023b6dd36440#PFH1A8XsHccmzbkJJzK79BYl8JfSJzOJL+Pi+AI6Oag=

**Comment by glushchenko** [comment]
Fixed in #133
