### ISSUE TITLE
Chinese characters disappear when written and can only be displayed when preview

### ISSUE THREAD

**Issue by farons** [glushchenko/fsnotes#1310]
### Description

When I add Chinese characters between ``````, Chinese characters disappear when written and can only be displayed when preview, ' ' has the same problem

### FSNotes version

5.3.5(514)

### macOS/iOS version

macos monterey

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.7/FSNotes_5.3.7.zip
