### ISSUE TITLE
Folders not discovered until manually rename in iCloud Drive

### ISSUE THREAD

**Issue by f1nnix** [glushchenko/fsnotes#1311]
### Description

After app is closed and re-opened, only notes in root path are shows. No folders with it's nested notes are shown. To make it visible again I need to go to iCloud Drive and rename it manually to something else, and the rename back to previous name.

I suppose it may be related to fsevents events or something similar, used in FSNotes to detect FS changes.

<img width="744" alt="Screenshot 2022-02-26 at 18 01 26" src="https://user-images.githubusercontent.com/3099788/155848046-cb01484c-5146-4111-b39b-ba3fb4a4f2aa.png">

### To Reproduce

I can't reproduce it stable, but I suppose it can be achieved after app is closed/re-opened in a few hours. Sorry, no more ideas.

### Expected behavior

Folders are correctly discovered including nested notes

### FSNotes version

--

### macOS/iOS version

Version 5.3.5 (514) (mac)

**Comment by glushchenko** [comment]
Take a look at macOS System Preferences -> Apple ID -> iCloud -> "Optimise Mac Storage" should be unchecked.
