### ISSUE TITLE
🇺🇦 FSNotes development continued 🇺🇦

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1312]
FSNotes project owner, Oleksandr Hlushchenko, lives in Ukraine and is currently fleeing during the Russian invasion.

> My city under fire from the Russian army. FSNotes development has been suspended indefinitely. We are in a bomb shelter. I hope they don't kill me and the release will still take place someday.

Ref: https://twitter.com/FSNotesApp/status/1496865592242016259

**Comment by gingerbeardman** [comment]
> Guys, i'm alive. Despite the fact that the Russian invaders destroyed my city, i managed to leave Kharkiv yesterday. Now I am in a safe place, still in Ukraine.

Ref: https://twitter.com/FSNotesApp/status/1499681219524575233

**Comment by glushchenko** [comment]
Thanks my friend. I managed to work on the weekend, i will try to release an FSNotes 5 for mobile this week, until we were surrounded.

**Comment by glushchenko** [comment]
FSNotes 5.3.7 released today for macOS. Further I plan several minor updates for iOS. 

Development is ongoing and will continue. Thanks to all!

**Comment by appscaptain** [comment]
Wow, crazy world! Good to hear you managed to escape from Kharkiv! Enjoying the iOS app that I just bought!

**Comment by valsha** [comment]
Hi, is this a native M1 application? Thank you.

**Comment by glushchenko** [comment]
Yes, native for M1
