### ISSUE TITLE
[REQ] Folding Headers

### ISSUE THREAD

**Issue by semicolonsnet** [glushchenko/fsnotes#132]
I use a number of long text files with headings, and would love a feature that allowed collapsing and expanding headers, as in apps like FoldingText or add-ons like https://atom.io/packages/markdown-folding

**Comment by gingerbeardman** [comment]
+1

**Comment by martingaik** [comment]
+1

**Comment by qiuhefeng** [comment]
+1

**Comment by webuniverseio** [comment]
I don't know if this is a good place or I should start a separate issue, but I would love to see collapsible sections. In Confluence you can add such sections where you can have any content hidden or expanded (with titles, tables, lists, images, etc)

Example https://support.atlassian.com/confluence-cloud/docs/insert-the-expand-macro/
![image](https://github.com/glushchenko/fsnotes/assets/911388/477204ab-dc13-47b9-b2a5-1227e0a39985)
Sample markup
```
{expand:This is my message}
This text is _hidden_ until you expand it.
{expand}
```

**Comment by gingerbeardman** [comment]
> I don't know if this is a good place or I should start a separate issue

Yes please, feel free to reference this one as being similar.

**Comment by glushchenko** [comment]
FSNotes is not about long text files. Sorry.
