### ISSUE TITLE
Japanese characters disappear in the code block

### ISSUE THREAD

**Issue by koryashkin** [glushchenko/fsnotes#1323]
Japanese characters disappear in the code block in edit mode and appear again in preview mode. 

Desctiption: 
Version 5.3.5 (514)
Expectation: Japanese characters are shown in the code block.  

How to reproduce: 
1. Create a new note
2. Put some Japanese text "私も今多分そのお話帰りという事のうちを云いたな。" 
3. Add it to the code block  
4. Japanese text disappears - not expected.  

Note: can be recovered if open preview mode and go back to the edit mode 

https://user-images.githubusercontent.com/3971742/158518660-1948479e-683c-4144-afa0-e01e68fbd21a.mov

**Comment by glushchenko** [comment]
Already fixed in iOS, will try to release update ASAP

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5.3.7/FSNotes_5.3.7.zip

**Comment by koryashkin** [comment]
Hi @glushchenko, 

Thank you so much! I checked this build and looks like there are no issues. 
Thank you again! 

PS I hope you and your family are safe... Please stay safe...
