### ISSUE TITLE
Question about part of the wiki - how to hide directories?

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1325]
### Description

I saw in the wiki that there is an option to hide the directories, but I'm not sure what is meant by `path/To/DirName`. Would that be `/Users/jared/Library/Mobile Documents/iCloud~co~fluder~fsnotes`?

Link: https://github.com/glushchenko/fsnotes/wiki/Advanced-settings#hideshow-directories-in-sidebar-fsnotes-497

### To Reproduce

1. Go to https://github.com/glushchenko/fsnotes/wiki/Advanced-settings#hideshow-directories-in-sidebar-fsnotes-497
2. Read section: "Hide/show directories in sidebar (FSNotes 4.9.7+)"

### FSNotes version

5.3.7

### macOS/iOS version

12.2.1

### Additional context

I would be happy to edit the wiki to clarify, once I know what the right way to do it is

**Comment by glushchenko** [comment]
/Users/jared/Library/Mobile Documents/iCloud~co~fluder~fsnotes is root directory, of course you can not hide it. But you can hide subfolder i.e /Users/jared/Library/Mobile Documents/iCloud~co~fluder~fsnotes/subfolder
