### ISSUE TITLE
"Paste and Match Style" pastes content other than the current clipboard

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1326]
### Description

"Paste and Match Style" pastes unexpected content, content other than the current clipboard, old content

### To Reproduce

1. Select an image file in Finder
2. Copy it to the clipboard
3. Select some formatted text in Safari
4. Copy it to the clipboard
5. FSNotes > Edit > Paste and Match Style (Alt+Shift+Cmd+V)
6. link to image is pasted!

optional
1. FSNotes > Edit > Paste (Cmd+V)
2. text is pasted

### Expected behavior

- plain text should be pasted with Paste and Match Style

### FSNotes version

- 5.3.8 (519)

### macOS/iOS version

- 12.3.1 (21E258)

### Additional context

Screen recording:

https://user-images.githubusercontent.com/49612/162510969-ec9f3a10-0d76-49e3-ba56-ff30f19c8f03.mov

**Comment by glushchenko** [comment]
Thanks my friend, seems it fixed.
