### ISSUE TITLE
Note set as hidden file when renamed without base file name

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#133]
I do the following:

1) Select an existing note in the Notes List.

2) CMD+R to rename the file.

3) Backspace to remove the existing note name and--without typing a new note name--select the enter key.

This creates a hidden file in the notes folder with the name ".txt" and the file is not shown in FSNotes after restart. 

This is a small issue, but I accidentally did this while working on something and it took me a while to find the note. 

Thanks.

FSNotes 1.2.11

ADDITIONAL NOTES:

I have the default file extension set as txt. If I change this to md, then the file that results has the file name ".md".  

A simple workaround is to leave the hidden file in the notes folder, which has the name ".txt" or ".md" and from that point on FSNotes will not allow me to create a file with no base file name.

**Comment by gingerbeardman** [comment]
Maybe a dupe? https://github.com/glushchenko/fsnotes/issues/128#issuecomment-5

**Comment by peavine** [comment]
I installed FSNotes 1.3 and checked the above issue. Everything works great. Many thanks.
