### ISSUE TITLE
Clicking a link, to open in browser, and FSNotes makes a request to the server in the link

### ISSUE THREAD

**Issue by ngocphamm** [glushchenko/fsnotes#1330]
### Description

When I click a link in a note, it opens in browser (as intended). However, LittleSnitch (a firewall application) reports that FSNotes is trying to make a request to the server in the link.

Something likes this
![CleanShot 2022-04-21 at 09 06 05@2x](https://user-images.githubusercontent.com/395123/164464358-1b719f72-f80d-4dc0-8a25-d5e1f547e765.png)

And this is the popup by LittleSnitch
![CleanShot 2022-04-21 at 09 04 22@2x](https://user-images.githubusercontent.com/395123/164464270-d98df607-14fa-4147-a141-5e2ff49b7942.png)

I wonder why FSNotes seems to make such request? Or it's just a reporting issue from LittleSnitch? I think this happens since the last update or so. I didn't notice it before.

### To Reproduce

0. Have LittleSnitch firewall installed, in Alert mode. I'm sorry I'm not sure if this can be done at all, but I think LIttleSnitch does provide free trial for 14 days.
1. Create a note with some links, or one link
2. Go to preview mode
3. Click the link
4. See that LittleSnitch now alerts about a new connection made by FSNotes to the server in the clicked link

### Expected behavior

The link is handled/opened in the default browser of the system, so there shouldn't be any request to the server in the link made by FSNotes.

### FSNotes version

5.3.9

### macOS/iOS version

12.3.1

**Comment by glushchenko** [comment]
Hi! Very interesting. Can you provide note example?

**Comment by glushchenko** [comment]
Ah, stop, this happens when only click on link? Then is OK. At first click dispatched by WkWebView, then in browser.

**Comment by ngocphamm** [comment]
So is this an unintentional behavior or what? I'm confused. Is there anything to prevent this?

**Comment by glushchenko** [comment]
Of course not, it's seems by design in WkWebView.

You can find opening method here and track all before:
https://github.com/glushchenko/fsnotes/blob/c9826984492178819defa509be6c48c526b88ebb/FSNotes/View/MPreviewView.swift#L136

**Comment by ngocphamm** [comment]
I see so this is just because of the way the click event dispatched by WkWebView. I'm still not sure how I can get rid of this annoying popup by LittleSnitch without just globally allowing all connections to 443 and 80 ports for FSNotes. Thanks for your explanation!

**Comment by glushchenko** [comment]
What's going on if fully block FSNotes from internet? App completely autonomous and not need any access.

**Comment by ngocphamm** [comment]
You are right that I can just do that, and I just noticed another app having the same behavior, Mailmate. It probably uses the same WkWebView (to view the email content), and when I click a link in the email, the same happen with LittleSnitch popping up.
