### ISSUE TITLE
Folder icon is different style to new icons

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1331]
### Description

New icons like iOS are great, but folder icon does not match.
The lines in it are much thinner, so it feels different.

<img width="123" alt="Screen shot 2022-04-22 at 20 38 10" src="https://user-images.githubusercontent.com/49612/164782737-f843b48b-50c1-4bcf-9a3b-fde1adb711aa.png">

### To Reproduce

- Compare folder icon to new inbox icon

### Expected behavior

- folder icon should feel the same as other icons

### FSNotes version

5.3.9 (521)

### macOS/iOS version

12.3.1 (21E258)

**Comment by glushchenko** [comment]
@helenka1812 this task for you ;-)

**Comment by gingerbeardman** [comment]
I'll do it :)

**Comment by glushchenko** [comment]
Matt, @helenka1812 – author of new icons, so Project icons was already requested :)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5.4.0/FSNotes_5.4.0.zip
