### ISSUE TITLE
masOS: table preview

### ISSUE THREAD

**Issue by sunjiabin17** [glushchenko/fsnotes#1334]
**Describe your feature request**
I've been tried FSNotes a few days, it's really impressive. I like your design and theme, it's beautiful. I will appreciate it if there's a table preview function.
Also, If I copy a table from website, it seems doesn't convert to markdown format table.
Thanks.😊
**Additional context**
macOS

**Comment by tewe** [comment]
What table syntax do you want to preview? FSNotes already shows MultiMarkdown tables.

Converting non-plain text formats (from the pasteboard) to Markdown seems scope-creepy to me.

(I use https://tableflipapp.com)
