### ISSUE TITLE
Preview of links is broken

### ISSUE THREAD

**Issue by cpisto** [glushchenko/fsnotes#1336]
### Description

The preview view of links, including the "2. Links" entry in the Welcome project, appears to be broken. Screenshot included.

![Screen Shot 2022-04-26 at 11 14 12 AM](https://user-images.githubusercontent.com/1212028/165356092-3fdc766e-8ebe-4c3e-adb9-87a1c1af6fd6.png)

Editing looks correct.

### To Reproduce

1. Go to the "2. Links" entry from the Welcome project.
2. Click on the eye icon to view it in preview.
3. Notice the odd unmatched brackets and inability to click the links

### FSNotes version

5.4.0 (522) Mac App Store

### macOS/iOS version

12.3.1

**Comment by glushchenko** [comment]
Holy cow. Will be fixed ASAP

**Comment by glushchenko** [comment]
Hotfix https://github.com/glushchenko/fsnotes/releases/download/5.4.1/FSNotes_5.4.1.zip
