### ISSUE TITLE
Menu items should be in title case

### ISSUE THREAD

**Issue by rmcmelo** [glushchenko/fsnotes#1337]
### Description

Certain menu items are not in Title Case.

As per the HIG, Menu items should be written in Title Case. E.g.: Instead of "Toggle preview" should be "Toggle Preview", "Sort by" should be "Sort By".

<img width="323" alt="Screenshot 2022-04-27 at 15 03 48" src="https://user-images.githubusercontent.com/8457992/165537868-561ba6ff-69d5-428e-b8f0-6f52b5d830d3.png">

### To Reproduce

In the Mac app, choose a menu item.

### Expected behavior

Menu items should be written in Title Case. 
Instead of "Toggle preview" should be "Toggle Preview", "Sort by" should be "Sort By".

### FSNotes version

v5.4.1 build 523

### macOS/iOS version

macOS 12.3

### Additional context

Further information can be found here:

[Menu Anatomy - Menus - macOS - Human Interface Guidelines - Apple Developer](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/)

> "Use title-style capitalization. Title-style capitalization is used consistently for menu and menu item titles throughout the system"

**Comment by gingerbeardman** [comment]
This one would be a fairly easy PR, at least for English. 

Are there other rules for different languages?

**Comment by glushchenko** [comment]
Dupe https://github.com/glushchenko/fsnotes/issues/1172
