### ISSUE TITLE
Toggled Menu Items should be two menu items or change title to reflect the current state

### ISSUE THREAD

**Issue by rmcmelo** [glushchenko/fsnotes#1338]
### Description

Curently, in the menu bar of the mac app, toggled items are combined into only one item: "Hide/show note list" and "Hide/show sidebar". 

According to the HIG, these should be two different menu items, or only one item that changes the title to reflect current state.

<img width="323" alt="Screenshot 2022-04-27 at 15 28 10" src="https://user-images.githubusercontent.com/8457992/165543349-c8068eac-112b-41dc-91b0-cbda2afad31e.png">

### To Reproduce

1. Go to "View" in the menu bar

### Expected behavior

The menu bar item should only show what the expected behaviour should be.
E.g.: When the Note list is visible, it should only say: "Hide Note List", and vice-versa. 

This is what is implemented in first-party macOS apps (see, for example, Show or Hide Favorite Bar" in Safari.

<img width="346" alt="Screenshot 2022-04-27 at 15 32 45" src="https://user-images.githubusercontent.com/8457992/165542784-ee90cdea-c416-416c-8869-8d8b5d0f9c4b.png">

### FSNotes version

v5.4.1 build 523

### macOS/iOS version

macOS 12.3

### Additional context

[Menu Anatomy - Menus - macOS - Human Interface Guidelines - Apple Developer](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/) 

> Toggled Menu Items
> A toggled menu item switches between two states when chosen. There are three types of toggled menu items:
>  
> * A set of two menu items with titles that indicate opposite actions or states; for example, Grid On and Grid Off. People know which menu item is currently in effect because it displays a checkmark or appears disabled.
> * **A menu item whose title changes to reflect the current state; for example, Show Ruler and Hide Ruler.**
> * A menu item that has a checkmark next to it when in effect; for example, a text attribute like Bold.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
