### ISSUE TITLE
Restore cursor position

### ISSUE THREAD

**Issue by fguada** [glushchenko/fsnotes#134]
Hello,

When I select a note (either via keyboard or pointer), I'd like the cursor position to be restored to what it was the last time this note was used.
(Right now, if I select a note via the keyboard, the note is focused, with the cursor positioned at the top of the note; if I select a note via the pointer, and if the new option "Focus in editor when select note" is enabled, the cursor is positioned at the bottom of the note.)
This can be done quite easily using xattrs (this worked well for me: https://stackoverflow.com/questions/38343186/write-extend-file-attributes-swift-example).

Many thanks for this app.

**Comment by peavine** [comment]
I'm sure restoring the cursor position would be a desired feature for many, although, just for me, it would not be helpful. If this is added to FSNotes, I hope there will be an option to disable it in preferences.

BTW, apologies to fguada if the above seems contrary. I use FSNotes a lot and wanted to get in my two cents.

**Comment by glushchenko** [comment]
Coming soon ;)
