### ISSUE TITLE
Paste broken since 5.3.8

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#1342]
### Description

Paste (cmd-v) does not work in 5.3.8 and subsequent. It works fine in 5.3.7 and earlier.

### To Reproduce

1. Go to any app and copy some text (cmd-c)
2. In FSNotes, attempt to paste the text (cmd-v)

The text is not pasted. The menu item in the menu bar flicks, and the note jumps vertically slightly, indicating the command *was* received, but the paste did not occur.

### FSNotes version

5.3.8

### macOS/iOS version

12.3.1

### Additional context

This only seems to appear when running FSNotes on an m1 Mac. The problem does not seem to occur on my Intel Mac.

I realise this means I should really get off my * and debug this 🤣 However I thought I would put this into the queue first and see if anyone else is experiencing the issue.

**Comment by glushchenko** [comment]
pasteAsPlainText function was changed in 5.3.9, but I can not reproduce it on Intel Mac. 

Can you debug this function? https://github.com/glushchenko/fsnotes/commit/12cca1d7b02b76ae31c9197db92069e56b0da107

**Comment by jeff-h** [comment]
Crazy thing is, I can no longer replicate this on any build. Sorry for the noise.
