### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by hasantahir** [glushchenko/fsnotes#1345]
**Emoji Support**
Is it possible to enable emoji support based on Github markdown?

**Additional context**
A complete list of Github emoji markup is [here](https://gist.github.com/rxaviers/7360908).

Thanks for making FS Notes!

**Comment by tewe** [comment]
Out of curiosity, what is your use case? Composing text you will copy to GitHub? I just use the operating system "keyboard" features to insert emoji as unicode characters.

**Comment by hasantahir** [comment]
> Out of curiosity, what is your use case? Composing text you will copy to GitHub? I just use the operating system "keyboard" features to insert emoji as unicode characters.

At the moment, I am using Raycast's Emoji extension to insert emojis into the document. My use case is mostly to emphasise a certain line in a list with icons such as 🔴. Silly but grabs the attention upon revisiting the document.

**Comment by tewe** [comment]
There seems to be more than one emoji extension for Raycast, and they all insert Unicode characters, so I still don't understand why you'd need those placeholders.

**Comment by hasantahir** [comment]
Found [Espanso](https://espanso.org/) that enables injecting emojis in text.

**Comment by gingerbeardman** [comment]
MacOS has such text shortcuts/expansion built in, but you would need to add the emoji.

Alfred has it built-in, and includes or has an easily added list of emoji shortcuts.

**Comment by hasantahir** [comment]
Thanks. I had been using Raycast's emoji extension but there were always some additional steps required to insert the emoji. With espanso, the emojis can be injected into the text ala Github markdown editor.

**Comment by tewe** [comment]
To be clear for posterity: the request was not to store the five ASCI characters `:joy:` and have the preview render an emoji. But to type `:joy:` and have that immediately converted to an emoji, to be stored as Unicode.
