### ISSUE TITLE
Wikilinks won't work if the notes are in subfolders

### ISSUE THREAD

**Issue by StJudeWasHere** [glushchenko/fsnotes#1347]
### Description

Wikilinks won't work when the notes are in subfolders.

### To Reproduce

1. Create a new folder "Folder A" in Documents
2. Create a couple of subfolders inside Folder A. "Subfolder A1" and Subfolder A2"
3. Create a note in Subfolder A1. "Note 1"
4. Create a note in Subfolder A2. "Note 2"
5. Create a wikilink in Note 1 to Note 2. [[Note 2]]
6. Click on the [[Note 2]] wikilink

### Expected behavior

Clicking on the wikilink [[Note 2]] should open "Note 2". What happens instead is a view with the FSNotes logo is opened.

### FSNotes version

5.4.1

### macOS/iOS version

12.3.1

**Comment by glushchenko** [comment]
Thank you for bug report! Fixed.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5.4.2
