### ISSUE TITLE
Adding a separator breaks the markdown rendering

### ISSUE THREAD

**Issue by StJudeWasHere** [glushchenko/fsnotes#1348]
### Description

Adding a separator breaks the markdown rendering of the next element:

This note:
<img width="165" alt="Screenshot 2022-05-07 at 10 25 40" src="https://user-images.githubusercontent.com/707925/167246055-1eba8452-df56-48e0-807d-a1451f337fdc.png">

Renders like:
<img width="179" alt="Screenshot 2022-05-07 at 10 24 58" src="https://user-images.githubusercontent.com/707925/167246075-bdc9bd8d-575d-4f7a-bedf-2f938d8313f6.png">
 

### To Reproduce

1. Create a new note with this contents:
```Markdown
# Title

---

## Subtitle
```

2. Toggle Preview 
4. Subtitle is not rendered as HTML and it displays the markdown text

### Expected behavior

The subtitle should be rendered as HTML but it is displayed as markdown instead.

### FSNotes version

5.4.1

### macOS/iOS version

12.3.1

### Additional context

This happens with anything immediately after the separator, whether it is a subtitle, a link or a list. It is always displayed as markdown text instead of being rendered as HTML.

**Comment by glushchenko** [comment]
Triple minus is equal ruler in markdown syntax, so not bug here:

https://www.markdownguide.org/basic-syntax/#horizontal-rules

**Comment by StJudeWasHere** [comment]
Yes, the ruler works as expected, what doesn't work is the element after the ruler. See the screenshot I attached, the ## subtitle is not rendered.

**Comment by glushchenko** [comment]
Definitely, thank you for clarification.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/5.4.3
