### ISSUE TITLE
Inline links

### ISSUE THREAD

**Issue by greiggy** [glushchenko/fsnotes#1349]
### Description

Inline links are not working for me
I'm using the CommonMark syntax [Linkheading](link heading) and I have tried a few variations e.g. Multimarkdown.

Colour changes to indicate link but it doesn't navigate. Error message sometimes appears 'Unable to open application...'

### Expected behavior

I expect navigation from the anchor to the link

### FSNotes version

Version 5.4.2 (525)

### macOS/iOS version

10.15.7

**Comment by greiggy** [comment]
Hi, I tried that again. Exactly as you stated. Shows as link in edit and rendered view. Edit throws the error message. Rendered view does not navigate.

I have tried various headings including one-word ones

Thanks for your help so far

—Ian Greig

**Comment by glushchenko** [comment]
Interesting, can you provide note example?

**Comment by glushchenko** [comment]
I'm sorry, proper syntax is [Linkheading](#link-heading) Hash # is important and - for spaces.
