### ISSUE TITLE
dont save to icloudkit?

### ISSUE THREAD

**Issue by andyferriby** [glushchenko/fsnotes#135]
Just tested your app and set it up to my own icloudkit but when i use simulator on my mac the notes i add there aint saving for some reason?

**Comment by glushchenko** [comment]
You should enable icloud in simulator.

**Comment by andyferriby** [comment]
Do you happen to have a list of your Capabilities?

Like:

FSnotes - icloud Container & App Group
FSNotes (iCloud Documents) - icloud Container & App Group
FSNotes iOS - icloud Container & App Group
FSNotes iOS Share Extension -icloud Container & App Group

**Comment by glushchenko** [comment]
No, no list and no plans.
