### ISSUE TITLE
add the custom Image Hosting  function on the Mac side

### ISSUE THREAD

**Issue by sumulige** [glushchenko/fsnotes#1352]
Hello author, I am a user. For the Fsnote APP, is it possible to add the custom Image Hosting  function on the Mac side, and the copied pictures can be automatically uploaded to the Image Hosting  and converted to .MD connection.

**Comment by gingerbeardman** [comment]
This is a cool idea.

Something like uploading them as hidden images on imgur? Would need account details to be added.

**Comment by sumulige** [comment]
> This is a cool idea.
> 
> 
> 
> Something like uploading them as hidden images on imgur? Would need account login or API details to be managed.

add API-related links to different  image Hosting , so that users can choose to join. Similar to the figure above. At present, typora on Mac supports such functions.
![image](https://user-images.githubusercontent.com/30450613/169359295-4390894f-b1bc-4921-882e-08f3b5de36f1.png)
![image](https://user-images.githubusercontent.com/30450613/169359355-6ccf3710-af7c-45a3-8cf0-5a72ab051985.png)

**Comment by glushchenko** [comment]
In FSNotes 6 you can host notes web pages on free FSNotes server or use custom server with one shortcut ⌘ + option + u.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
