### ISSUE TITLE
Tag tree collapses when you select a folder or other sidebar button

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1354]
### Description

The tag tree collapses when you select a sidebar item, like a folder or Notes, Inbox, Trash, etc.

I would be happy to take a look at the code and see about submitting a PR, but first I wanted to confirm that you guys agree that this is a bug, or to hear any comments about why this is happening.

### To Reproduce

1. In the tag tree, if you click the ">" symbol next to a tag to reveal its child tags
2. Click a different sidebar button, like Inbox, or click on a folder
3. The tag tree collapses

### Expected behavior

Tag tree should only collapse if user clicks on the V icon to collapse it, or when the app launches. If you select a different folder that has notes with different tags, the tag list should update but not collapse unnecessarily.

### FSNotes version

5.4.2 (525)

### macOS/iOS version

12.3.1 (21E258)

**Comment by glushchenko** [comment]
Hi, @nth-chile!

Tags loaded on select any project or sidebar item. Of course we can improve it and save state for child tags, but this is not a bug.

I think state should be resetted on ESC pressing.

**Comment by nth-chile** [comment]
Hi!

Ok. For me it's a little unexpected, and I think it prevents me from using the tree as often as I would if it stayed open. Curious to see what other people think. I just checked Bear and it looks like theirs stays open, even when the note list is empty
