### ISSUE TITLE
Note list doesn't collapse if it has a scrollbar

### ISSUE THREAD

**Issue by sarmentow** [glushchenko/fsnotes#1355]
### Description

If a note list has enough note to make a scrollbar appear, it is impossible to collapse it completely.
![Screen Shot 2022-05-19 at 10 52 41 AM](https://user-images.githubusercontent.com/48866794/169311068-22a844a1-f1e8-4486-8a9a-ef68ee874b88.png)
![Screen Shot 2022-05-19 at 10 52 47 AM](https://user-images.githubusercontent.com/48866794/169311119-fc1c1a48-ad13-4fa5-8296-0149ef4d3a05.png)

### To Reproduce

1. Open a folder with enough notes to make a scrollbar appear in the note list
2. Collapse note list with CMD + Shift + B
3. See error: note list doesn't collapse completely

### Expected behavior

I expected the note list to completely vanish from view, but a small part of it remains.

### FSNotes version

5.3.8

### macOS/iOS version

10.15.7

**Comment by glushchenko** [comment]
Please select this radio box: System Preferences -> General -> Show scroll bars -> When scrolling

**Comment by sarmentow** [comment]
That's it. 

Thanks a lot.
