### ISSUE TITLE
Footnote, TOC Support

### ISSUE THREAD

**Issue by Brin-o** [glushchenko/fsnotes#1356]
**Describe your feature request**
I've been testing out iA Writer a little bit I prefer FS Notes over it, however there are some additional markdown features it has (I think it's from [MultiMarkdown](https://fletcherpenney.net/multimarkdown/)) that I ended up quite liking.

These features are the ability to add footnotes and TOC Support. The syntax for them is `{{TOC}}` to generate a TOC and `word[^1]    [^1]footnote comment later in the page` to generate a footnote.

These are fantastic additions especially for academic writing where both TOCs and footnotes are common.

I am not sure what your stance is on markdown processing and if you'd be willing to stray from vanilla markdown so sorry if this is out of the question for you!

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
