### ISSUE TITLE
Lists with only some checkboxes are rendered without bullets

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1357]
### Description

Lists with all checkboxes as well as lists without checkboxes are rendered correctly. Mixed lists are missing the bullets.

<img width="929" alt="Preview mixed 2022-05-25 at 16 54 54" src="https://user-images.githubusercontent.com/645412/170297344-79a8d49e-b99b-4182-8b7c-5a2b2f102aba.png">

### To Reproduce

```markdown
- a
- [ ] b
```

### Expected behavior

Both renderers built into https://marked2app.com yield the following screenshot.

<img width="860" alt="CleanShot 2022-05-25 at 17 17 42" src="https://user-images.githubusercontent.com/645412/170297666-d41916f7-0867-4296-b0a6-43016320bb16.png">

### FSNotes version

5.4.3

### macOS/iOS version

macOS 12.3.1

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5.4.4/FSNotes_5.4.4.zip

**Comment by tewe** [comment]
I would have expected the fix somewhere in [the HTML rendering](https://github.com/NightFlyer/cmark-gfm/blob/85d895289c5ab67f988ca659493a64abb5fec7b4/extensions/tasklist.c#L115), but this works for me.
