### ISSUE TITLE
Nested checkboxes render with extra indentation

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1358]
### Description

<img width="1061" alt="CleanShot 2022-06-06 at 10 20 32@2x" src="https://user-images.githubusercontent.com/645412/172124290-e4da5de6-ebb0-4beb-a688-39069b75f194.png">

### To Reproduce

```markdown
- [x] foo
    - [ ] bar
    - [x] baz
- [ ] bim
```

### Expected behavior

<img width="997" alt="CleanShot 2022-06-06 at 10 25 51@2x" src="https://user-images.githubusercontent.com/645412/172124369-426664e0-e34b-4e5c-aad9-c71c1d866abe.png">

### FSNotes version

5.4.4 (528)

### macOS/iOS version

macOS 12.4

### Additional context

This seems to be [fixed upstream](https://github.com/github/cmark-gfm/issues/168), but the [fork used in FSNotes](https://github.com/KristopherGBaker/libcmark_gfm) hasn't been updated in 3 years.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by tewe** [comment]
Works for me. Thanks!

Although vendoring the dependency and cherry picking one of the many changes from upstream looks like more technical debt to me.
