### ISSUE TITLE
Notes disappearing from list

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#136]
Certain notes (but not all) in my collection disappear from the notes list as soon as I edit them, or sometimes even as soon as I click somewhere in the note. The notes are still in the filesystem thankfully, but I have to restart FSNotes to see them again inside the app.

I'm struggling to identify what's different about the notes that cause this behaviour. I did notice a few oddities in tracing through the code during an instance of the above behaviour. Unsure if any of it's relevant.

* flow goes inside [`event.fileRenamed`](https://github.com/glushchenko/fsnotes/blob/master/FSNotes/ViewController.swift#L203) immediately after typing a single character in any note, even though no rename occurred (at least not as a result of user action). 
* I noticed that the FSEvents system appeared to be monitoring `index.lock` inside my `.git` directory (I keep notes in a git repository, as per discussion [here](https://github.com/glushchenko/fsnotes/issues/51#issuecomment-339562403)) — perhaps there's been a regression in this area?

Overall I am really unsure where to look to see what's going on, but happy to dig into it further if you're able to give me any pointers?

**Comment by glushchenko** [comment]
Key point – isRemoved property, stored in core data. isRemoved now has no special meaning, after removing CloidKit. I will rewrite this part soon, so that we forget about this problem.

**Comment by glushchenko** [comment]
Please try 1.3.1

**Comment by jeff-h** [comment]
Thanks for looking into this! Unfortunately the problem still persists for me.

**Comment by jeff-h** [comment]
So many of my notes are basically un-editable that I started downloading old versions of FSNotes and trying them each in turn, to find where the bug was introduced. I traced it right back to commit `3077575f`, specifically [this code](https://github.com/glushchenko/fsnotes/blob/master/FSNotes/ViewController.swift#L206-L208).

I'm actually a little lost as to what that code is for, but it definitely appears to be the source of the issue I'm experiencing. I'm very hopeful I've isolated the steps needed to reproduce this:

* open FSNotes and edit a note; assuming everything's good at this point, do the following:
* quit FSNotes
* locate the note in the finder. I expect it will have its file extension hidden ie the file will be displayed as `My Note` not `My Note.rtf` or `My Note.md` or whatever
* "Get Info" (cmd-i) and untick "Hide extension" so that the finder shows the note's extension 
*  relaunch FSNotes, and re-edit the note

For me, the note immediately disappears from the notes list, because the code mentioned above incorrectly sets `isCaseInSensitiveEqualOnly` to `true`.

**Comment by gingerbeardman** [comment]
Good detective work! 

I'm wondering... are you saving on an HFS+ or APFS format drive? Case sensitive or not?

**Comment by jeff-h** [comment]
APFS, not case-sensitive.

**Comment by jeff-h** [comment]
@gingerbeardman are you able to replicate the problem via the steps above? I think this is primarily about whether the file is set to show its extension or not, which is a layer of macOS abstraction above the filesystem, I expect.

**Comment by glushchenko** [comment]
Hi @jeff-h, ш reproduced everything you described and i'm trying to resolve this annoying bug in commit above. Please checkout.

**Comment by jeff-h** [comment]
Sorted! Beautiful :) https://github.com/glushchenko/fsnotes/commit/aa7e7df47266c5d72f13600627069ff98e1cd3f4 fixes this for me.
