### ISSUE TITLE
Not all subdirectories are recognized

### ISSUE THREAD

**Issue by xplosionmind** [glushchenko/fsnotes#1365]
### Description

If I add a folder with many Markdown notes inside the fsnotes storage folders, they do not show up, even after rebooting the app.

### To Reproduce

1. Go to the storage folder
2. Create a folder and move there many various Markdown files
3. Open FSNotes
4. whole folders not appearing
5. rebooting the app
6. problem is still there

### Expected behavior

Every folder inside the root storage folder for FSNotes should be appearing.

### FSNotes version

5.4.4

### macOS/iOS version

12.4

**Comment by glushchenko** [comment]
How many folders was added? Mark-down files not limited at all.

**Comment by xplosionmind** [comment]
> How many folders was added?

Four, only one appeared. Nevertheless, if I added some new folders while FSNotes was opened, they appear, but after closing and re-opening the app, they do not appear anymore.

<br>

> Mark-down files not limited at all.

I know! Yet I do not see all of them.

**Comment by glushchenko** [comment]
Can you provide reproducible folder?

**Comment by tewe** [comment]
This may not be related, but I had just added 5169 files to a folder while FSNotes was running, and it only showed 474. Re-launching helped.

**Comment by xplosionmind** [comment]
I am sorry @glushchenko, I thought I replied, but I did not.

> Can you provide reproducible folder?

among others, I imported [this folder](https://github.com/xplosionmind/tommi.space/tree/main/content/notes 'notes folder in tommi.space repository, on GitHub').

**Comment by glushchenko** [comment]
@xplosionmind tried and no any problems for me:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/1089917/184549477-ff8a5762-0526-4aba-9303-a22902d49b9f.png">
