### ISSUE TITLE
actor name with hyphen in mermaid sequence diagram fails to render

### ISSUE THREAD

**Issue by csgtree** [glushchenko/fsnotes#1368]
### Description

Add the below code block and toggle preview. It will complain syntax error.
<img width="528" alt="iShot_2022-06-15_18 00 17" src="https://user-images.githubusercontent.com/4638466/173801205-c579d3f0-bf5c-48b0-a38a-76a618378b11.png">

Remove the hyphen in `John-Wick` will make it work.

### To Reproduce

It is an editor error. Use the content in description will reproduce the issue.

### FSNotes version

Version 5.4.1 (523)

### macOS/iOS version

12.3.1 (21E258)

**Comment by glushchenko** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/1089917/192105492-6f0cfa22-f383-4ed3-ae5c-c2fdad49cd3b.png">

FSNotes 6
