### ISSUE TITLE
Files support on iOS

### ISSUE THREAD

**Issue by Duderichy** [glushchenko/fsnotes#137]
Try integrating it like the app Textor (open source, MIT license) has

https://www.macstories.net/reviews/textor-the-ios-equivalent-of-textedit-integrated-with-files/

https://github.com/louisdh/textor

**Comment by glushchenko** [comment]
FSNotes is not app for everything. If you need access for documents, just put files in FSNotes folder.

**Comment by gingerbeardman** [comment]
Isn't this as simple as adding one key/value pair to the Info.plist?

```
<key>UISupportsDocumentBrowser</key>
	<true/>
```

**Comment by glushchenko** [comment]
@gingerbeardman for what?

**Comment by gingerbeardman** [comment]
So that it gets Files support for free

**Comment by glushchenko** [comment]
iOS fsnotes UI do not have document browsers. I do not know how to add this.

**Comment by glushchenko** [comment]
And how to index all files?

**Comment by gingerbeardman** [comment]
I'll take a look at this soon then

**Comment by jeff-h** [comment]
I just installed Textor and agree — its file handling is a good illustration of access to any folder inside iCloud. I'd really like to see FSNotes iOS allow the same rather than being restricted only to its own `iCloud Drive / FSNotes` folder.

**Comment by gingerbeardman** [comment]
I just use Pretext on iOS now instead of FSNotes

**Comment by jeff-h** [comment]
Interesting, but a useless toy without RTF (lol, just joking, but seriously of no use to me since I only use RTF).

> Pretext integrates directly with iOS 11's Files app, making it easy to create or edit Markdown and plain text files stored across any of your file providers.

How are they doing that, I wonder? Does the iOS Files app provide an API that will give any app access to any "file provider" that works with Files app? If so, what's https://github.com/dropbox/SwiftyDropbox for?

**Comment by glushchenko** [comment]
> How are they doing that, I wonder?

https://developer.apple.com/documentation/uikit/uidocumentbrowserviewcontroller

But this very limited, no search highlighting, no full text search.

**Comment by gingerbeardman** [comment]
Does it solve all our problems in one hit? No. 

Does it provide a solid base to build on? Absolutely yes. 

It's extendable. Just take a look at how Textor is different to Pretext, both are built on top of this base. There are many more varied examples. 

This is what I was thinking of: 

https://www.appcoda.com/files-app-integration/ (Swift code)

This example adds text editing to the boilerplate code (which can already view images). 

As far as I know it does provide read-write access to a whole folder, and tags. And I'm am pretty sure sort order could be overridden/subclassed to support pinned files, as could other aspects of its design. 

> While DocumentViewController is “just” a subclass of a UIViewController, a view controller is very powerful — an open slate that can be customized extensively.

**Comment by gingerbeardman** [comment]
A great example of what is possible using iOS Document Browser and customisation

https://itunes.apple.com/us/app/id1120099014

**Comment by fuzzy76** [comment]
Was this fixed in #147 ?
