### ISSUE TITLE
Editor URL highlighting consumes formatting

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1370]
### Description

The URL highlighting in the editor will make the trailing asterisks of a bold address part of the link, leading to 404.

<img width="713" alt="CleanShot 2022-06-16 at 15 23 45@2x" src="https://user-images.githubusercontent.com/645412/174163691-629e7971-eab6-448d-966a-9a61a5d667de.png">

### To Reproduce

`**https://github.com/bauman/libgeohash**`

### Expected behavior

The preview works fine.

<img width="809" alt="CleanShot 2022-06-16 at 23 07 57@2x" src="https://user-images.githubusercontent.com/645412/174163800-ac7c9d6b-0a48-4d5d-ac80-8fffa10e2a0c.png">

### FSNotes version

5.4.4 (528)

### macOS/iOS version

macOS 12.4

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by tewe** [comment]
Works for me. Thanks!
