### ISSUE TITLE
Crashes after pasting multiple hyphens (--) from clipboard

### ISSUE THREAD

**Issue by cedecode** [glushchenko/fsnotes#1371]
### Description

Sometimes I want to write two or more hyphens, e.g. `--`, `---`, …
A double-hyphen is automatically converted into a dash (`–`). As a workaround, I copy the hyphens to clipboard for using it several times. After inserting from clipboard, FSNotes crashes.

### To Reproduce

1. Write `- -` _(hyphen space hyphen)_
2. Remove the space between the hyphens to make sure it doesn‘t get converted to `–` (dash)
3. Copy `--` to clipboard
4. Paste `--` from clipboard
5. After first or second attempt the app crashes without error message. The text was _not_ being inserted.

### Expected behavior

It should paste `--`, `---` or `----` from clipboard without crashing.

### FSNotes version

5.0.3 version 244 from App Store

### macOS/iOS version

iPadOS 15.5 and iOS 15.5

### Additional context

If I switch off Smart Punctuation in iOS‘ keyboard settings there is no crash. If I reenable it the crashes appear again.

**Comment by glushchenko** [comment]
5.0.3 is outdated soft, cannot reproduce bug in 5.4.5
