### ISSUE TITLE
.git is shown on mobile version, but hidden on desktop as expected

### ISSUE THREAD

**Issue by kamilsk** [glushchenko/fsnotes#1372]
### Description

Hi! First, thanks for the great tool. I'm using it with joy.

I prefer to backup my notes in git manually and store it on GitHub and Bitbucket. For that reason, I inited a git repository inside the FSNotes' directory. On desktop, it works well, but on mobile, it shows me internals of `.git` directory.

For example, I use the same repository of notes for Obsidian and it works the same on desktop and mobile.

### To Reproduce

1. Go to FSNotes' directory
2. `git init`
3. Open mobile app
4. See something like on the screenshot

<details><summary>details under the cut</summary>

![photo_2022-06-22 12 04 24](https://user-images.githubusercontent.com/1165416/174989880-e987503a-8416-4645-8c1e-f0ab10c8e5c3.jpeg)
</details>

### Expected behavior

It doesn't show internals of `.git` or other `dot` directories.

### FSNotes version

5.0.3-244

### macOS/iOS version

iOS 15.5

**Comment by kamilsk** [comment]
> But I want to point out that iCloud Drive works very badly with git repositories. And as the repository grows, sync will stop working on macOS and iOs. Therefore, FSNotes makes all backups to external folders.

Thanks for the information! I don't use it frequently. Also, I make a snapshot yearly by squashing the history.
And thanks for the quick fix, especially. I will be waiting it in App Store ☺️👋

But is it possible to exclude all `dot` folders from view?

**Comment by glushchenko** [comment]
@kamilsk update already available in the AppStore ;)

**Comment by kamilsk** [comment]
🙌
