### ISSUE TITLE
Text display distorts when working with front matter

### ISSUE THREAD

**Issue by kamilsk** [glushchenko/fsnotes#1376]
### Description

Recently I started writing articles in FSNotes. I'm using Hugo to convert them into a static site. But FSNotes doesn't support "front matter" (see https://gohugo.io/content-management/front-matter/). It's not a problem, but the text display distorts when I'm working with it.

### To Reproduce

See the record https://www.loom.com/share/96041575bf2a4b1e9576c8b2312e443f.

### Expected behavior

The text display doesn't distort.

### FSNotes version

5.4.4 (528)

### macOS/iOS version

12.4 (21F79), Monterey

### Additional context

Typora and Obsidian work well with the front matter. Maybe it will be great to support it too? It's related to feature request #1238.

**Comment by kamilsk** [comment]
@glushchenko, hi! I'm sorry for the ping. Do we have any news here? Is it relevant, or won't it be fixed?

**Comment by kamilsk** [comment]
Could you also take a look at this #1375 too, please?

**Comment by glushchenko** [comment]
Hi, @kamilsk. I am busy on FSNotes 6 development atm. May be sometime...
