### ISSUE TITLE
Changed mtime does not appear in notes list

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1378]
### Description

The modification date shown in the notes list is not updated when a file's mtime is changed (but not its content). Re-launching helps.

### To Reproduce

1. Create a new note (I only tried TextBundle)
2. Wait a minute
3. `touch` the note in Terminal

### Expected behavior

The time in the notes list changes.

### FSNotes version

5.4.4 (528)

### macOS/iOS version

macOS 12.4

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by tewe** [comment]
It now works for the `.textbundle` directory, but not for the `text.*` file inside. So if you `Open External` in e.g. BBEdit and just hit ⌘S, FSNotes will not show the correct time.

**Comment by glushchenko** [comment]
> It now works for the .textbundle directory, but not for the text.* file inside. So if you Open External in e.g. BBEdit and just hit ⌘S, FSNotes will not show the correct time.

Checked Open External with TextMate, the modification date is reloaded without problems. Perhaps you've tried changing the creation date?

**Comment by glushchenko** [comment]
Released: https://github.com/glushchenko/fsnotes/releases/download/6.9.2/FSNotes_6.9.2.zip

**Comment by tewe** [comment]
I can no longer reproduce this with `touch` and BBEdit. Thanks!

> Checked Open External with TextMate, the modification date is reloaded without problems. Perhaps you've tried changing the creation date?

No. That's actually hard to do.
