### ISSUE TITLE
 Excuse me, how is the support for apple pencil in this software?

### ISSUE THREAD

**Issue by baboon-king** [glushchenko/fsnotes#1379]
**Describe your feature request**
I often use the apple pencil on my iPad to write something. I wish I could support this

**Additional context**
Add any other related information here. macOS or iOS?

**Comment by tewe** [comment]
What exactly do you want to do? Pixels? Vectors? Editable? Character Recognition?

**Comment by baboon-king** [comment]
> What exactly do you want to do? Pixels? Vectors? Editable? Character Recognition?
Thanks for your reply
Maybe like goodnotes
