### ISSUE TITLE
Cannot eliminate wide white-space column to left of note text

### ISSUE THREAD

**Issue by desmond-dsouza** [glushchenko/fsnotes#1380]
### Description

![image](https://user-images.githubusercontent.com/4407158/177611715-34c9ee8b-d556-43cb-839a-21537f84efc1.jpeg)

### To Reproduce

For me, in any view (including Hide / Show note list and Hide / Show sidebar) I cannot get rid of that wide column of whitespace.

### FSNotes version

5.3.5 (514)

### macOS/iOS version

11.6.2

**Comment by glushchenko** [comment]
Preferences - Editor - Line width
