### ISSUE TITLE
URL parameter divider is wrongly escaped

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1381]
### Description

For some URLs, the question mark dividing the parameter from the path is escaped to `%3F`, leading to 404 when following the link. This only happens in the editor.

![CleanShot 2022-07-08 at 12 32 51@2x](https://user-images.githubusercontent.com/645412/177976499-31d828bd-9b0d-4797-b041-821568c6e886.png)

### To Reproduce

1. New Note
2. Paste `https://www.example.org/buergerservice/verwaltung/verwaltungsaussenstelle.html?titel=Verwaltungsaußenstelle`
3. Click the highlighted URL (or hover to see the tooltip)

### Expected behavior

Pass the URL as-is to the browser.

### FSNotes version

5.4.4 (528)

### macOS/iOS version

macOS 12.4

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by tewe** [comment]
Works for me. Thanks!
