### ISSUE TITLE
Nextcloud integration (directly or via files app)

### ISSUE THREAD

**Issue by Duckbilled** [glushchenko/fsnotes#1382]
**Describe your feature request**
I would love to be able to connect my existing markdown database stored in Nextcloud. Either by connecting directly to Nextcloud or using the Files app integration of the Nextcloud app. 

**Additional context**
To clarify the files app part. The Nextcloud app is already visible in the files app.

**Comment by tewe** [comment]
Have you tried Settings > Storage > Add External Folder?

**Comment by Duckbilled** [comment]
The 'Done' button is greyed out. I guess I can only add folders that are stored on the phone itself.

**Comment by glushchenko** [comment]
This limited by iOS API, so no

**Comment by foss-** [comment]
Can you elaborate on the iOS API limitation? Just ran into the same situation - would love to sync via Nextcloud but Nextcloud (as well as OneDrive) is greyed out in Storing Location option.

**Comment by glushchenko** [comment]
I don't know why that is.
