### ISSUE TITLE
After pin random note, the preview title doesn't navigate to the right note.

### ISSUE THREAD

**Issue by Pilchark** [glushchenko/fsnotes#1383]
### Description

After pinning random note, Click one preview title in the middle, but the right window are not the actual content of the title.It seems run into a chaos.
![截屏2022-07-18 22 37 38](https://user-images.githubusercontent.com/77473658/179538749-5d02bec7-eee6-4c8a-a8d2-f1b20653f5cb.jpg)

 

### To Reproduce

1. Go to a note folder, such as "Welcome".
2. Right Click on random note, click `pin/unpin`.
3. Click on any other preview title.
![屏幕录制2022-07-15 18 27 14](https://user-images.githubusercontent.com/77473658/179535288-73780cd7-a311-4e19-ae64-d0c4958fbb11.gif)

### Expected behavior

![截屏2022-07-18 22 40 30](https://user-images.githubusercontent.com/77473658/179536523-96d38f48-9029-4857-b7de-36cadd89f5b4.jpg)

### FSNotes version

5.4.5(530)

### macOS/iOS version

12.2.1

### Additional context

1. If I turn on "`Hide images preview`" or "`Hide preview`" or both of them, the bug does NOT occur.
![屏幕录制2022-07-18 22 45 41](https://user-images.githubusercontent.com/77473658/179538015-6f8d5ffd-56b6-46a9-a010-1e31e1c720b2.gif)

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
