### ISSUE TITLE
Can't access encrypted notes on iOS after changing master password on macOS

### ISSUE THREAD

**Issue by eserdk** [glushchenko/fsnotes#1387]
### Description

Problem: "Invalid Password" in iOS app after changing the master password in macOS app.

I've double checked that the password also has been changed in keychain access. 

However, I can't now access encrypted notes on iOS since looks like it has "memorized" my old password but can't retrieve the newer one.

I tried reinstalling the app and it doesn't seem to solve the problem.

It's also impossible now to open notes created and encrypted from iOS app in macOS app.

### To Reproduce

1. Set the master password in macOS app.
2. Create and encrypt a note in macOS app.
3. Open iOS app.
4. Open the encrypted note, entering the password from step 1.
5. Go back to macOS app.
6. Change master password in macOS app.
7. Create a new note in macOS app and encrypt it.
8. Try opening the same encrypted note in iOS app.
9. In my case it says "Incorrect password" with no option to enter the new one.

### Expected behavior

iOS app either retrieves the new password automatically or provides an option to re-enter it after showing the "Incorrect password" message.

### FSNotes version

macOS: Version 5.4.5 (530); iOS: Version 5.0.4 build 245

### macOS/iOS version

macOS: 12.4 (21F79); iOS: 15.5

**Comment by glushchenko** [comment]
Hi, app saves last entered password and use it in biometric. Just close FaceID and reenter new password on iOS.
