### ISSUE TITLE
How to build and sideload iOS app using XCode

### ISSUE THREAD

**Issue by exislow** [glushchenko/fsnotes#1388]
Can you provide a short how to, that describes how the app is being build and sideloaded to an iPhone with just an free Apple developer account (not a paid account)?

I have issues so far, especially with signing. It fails because of the bundle identifier, missing profile iCloud compatibility etc. What am I doing wrong?

I really like your effort here. These project is just amazing. Thank you very much so far!

**Comment by tewe** [comment]
It looks like FSNotes is using iCloud document storage, which is [not available](https://help.apple.com/developer-account/#/dev21218dfd6) to Apple Developers outside the Program. So you'd have to make extensive modifications to the code for it to build.

I've come to see the $99/year as just part of using a Mac professionally. Without it you can't even write scripts that access certain files.

**Comment by exislow** [comment]
Thank you for the fast clarification. 

Maybe you could also help me to get this straight: The FSNotes macOS apps can also make use of git to backup the notes. But I could not try the FSNotes iOS app so far. Do you know if the iOS app can also use a git remote repository to backup / exchange data? Or is this what the highly dependance on iCloud is for?

I would actually love, if I simply could use any remote git server to exchange my data between my macOS and iOS using the FSNotes apps.

**Comment by tewe** [comment]
I don't see any Git support in FSNotes for iOS.

(It can however use the cross-app file system, and there may be apps to sync folders with various services.)

I don't consider Git a good sync backend. If you want to avoid having old data on whatever machine you are using at the moment, you'll have to do many many tiny commits and pushes. I also don't know of any clients with automatic conflict resolution.

**Comment by exislow** [comment]
Conflict resolution is a good point...

Do you have any suggestion what would be the best way to sync the notes between macOS and iOS?

**Comment by tewe** [comment]
I don't currently sync my notes.

If you're not tied to any particular feature of FSNotes for iOS, there are many similar apps with support for various sync services. As long as the macOS version of that service can sync a folder full of text files, it should work with FSNotes there.

**Comment by glushchenko** [comment]
I dont know how to sideload it on free account, sorry.
