### ISSUE TITLE
Duplicate Note Names

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#139]
If I rename a note and give it the name as an existing note, FSNotes 1.3 displays two notes with the same name. Then, after FSNotes is restarted:

* The renamed note reverts to its original name.

* Edits to the renamed note are lost if those edits were made after the note was renamed and without selecting the note's name in the note list.

**Comment by peavine** [comment]
I installed FSNotes 1.3.1 but the issue remains. To duplicate this:

1) Create two notes named Note 1 and Note 2. 

2) Click on Note 1 in the Notes List.

3) Use CMD+R to rename Note 1 to Note 2. The Notes List now shows two notes with the name Note 2 and the cursor is in what used to be Note 1 (I have enabled the focus-in-editor preference).

4) Type some text and exit FSNotes

5) After restarting FSNotes, the note that I renamed to Note 2 in 3 above now has the name Note 1, and the text I typed in 4 above is gone.

Thanks.

**Comment by peavine** [comment]
I installed FSNotes 1.3.1 but the issue remains. To duplicate this:

1) Create two notes named Note 1 and Note 2. 

2) Click on Note 1 in the Notes List.

3) Use CMD+R to rename Note 1 to Note 2. The Notes List now shows two notes with the name Note 2 and the cursor is in what used to be Note 1 (I have enabled the focus-in-editor preference.

4) Type some text and exit FSNotes

5) After restarting FSNotes, the note that I renamed to Note 2 in 3 above now has the name Note 1, and the text I typed in 4 above is gone.

Thanks.

**Comment by glushchenko** [comment]
Fixed in 1.3.2

**Comment by peavine** [comment]
I installed FSNotes 1.3.2, and this issue is fixed except under one unlikely circumstance, which is illustrated as follows:

1) Create three notes with the names Books, Post, and Work. 

2) Attempt to rename the Books note to Work and then the People note to Work. In both instances, a dialog notifies that this action is not allowed, and, as expected, the Notes List shows Books, Post, and Work.

3) Create a new note. The notes list now shows four notes with the names Untitled Note, Work, Work, and Work.

4) Restart FSNotes and the notes shown are Books, Post, Untitled Note, and Work.

Thanks for all your hard work on this issue.

**Comment by glushchenko** [comment]
Fixed in 1.4

**Comment by peavine** [comment]
I installed 1.4 and everything works great. Thanks.
