### ISSUE TITLE
iOS App: Is it possible to define / access custom notes location?

### ISSUE THREAD

**Issue by exislow** [glushchenko/fsnotes#1391]
I would like to either by an Apple developer Programm subscription to build the app myself or the FSNotes app from AppStore but before I do so I would like to know the following:

1. Is it possible to access custom notes location on my iPhone using the app? Or is the notes location save path predefined and not changeable?

Background of my question: I would like to sync my notes with a specific app to my iPhone (no I do not want to use iCloud) and afterwards access the synced notes with the FSNotes iOS app. 

Thank you in advance!

**Comment by exislow** [comment]
@glushchenko could you maybe answer this question?

**Comment by glushchenko** [comment]
You can add external folder like in FSNotes for macOS app.

**Comment by exislow** [comment]
But I cannot manage the content of the external folder in the macOS app. E.g. I cannot create new sub-folders within an external folder, correct?

My question was rather, if I can freely chose the "Default Storage" location in the iOS app the same way I do it in the macOS app?

**Comment by glushchenko** [comment]
No, you can not change root storage and it is by design. iOS API limited to detect changes only in app root storage. So if file changed outside, you cannot know about it if you use external storage.
