### ISSUE TITLE
Search changes cursor and corrupts the opened note

### ISSUE THREAD

**Issue by IvanKostyuk** [glushchenko/fsnotes#1394]
### Description

Difficult to reproduce. Happens a lot. I'm trying to figure out all preconditions.

I have FSNotes opened for long time with one open note for view or edit. After some time I need notes and I know the context. Going directly to search (without using Esc because I have no intention to close current one if I'm wrong in my guess). Typing in search a word/phrase `git rebase`
While typing (fast typing) the first letter `g` remains in the search but others are added somewhere in the opened note.

### To Reproduce

1. Go to FS Notes from another application while there is an open note.
2. Click on 'Search or create' text field
3. Type in a world or phrase
4. The first letter is in search, while the rest are in the open note and cursor is there.

### Expected behavior

The whole typed in text is in search and only relevant notes are shown under the search field.

### FSNotes version

Version 5.4.5 (530)

### macOS/iOS version

macOS 12.4 (21F79)

**Comment by gingerbeardman** [comment]
I've encountered this before, but was also unable to reproduce it.

**Comment by glushchenko** [comment]
"Preferences -> Editor -> Focus in editor when selecting note" is enabled?

**Comment by IvanKostyuk** [comment]
It is disabled
[image: image.png]
I've got the latest version a week ago. First hour the issue was not
reproducible. Then it started to mess with my notes again.

**Comment by IvanKostyuk** [comment]
Just reproduced in Version 6.6.5 (609)

**Comment by glushchenko** [comment]
This problem is on your side, can't help you.

**Comment by gingerbeardman** [comment]
@IvanKostyuk can you reporodice on a new/blank user account on your mac?

**Comment by IvanKostyuk** [comment]
@gingerbeardman, I tried on brand new laptop without restoration from Time Machine.

I'm trying to reproduce the behavior similar to my experience.
