### ISSUE TITLE
Mermaid update required

### ISSUE THREAD

**Issue by unrzn0** [glushchenko/fsnotes#1396]
### Description

The Mermaid version in FSNotes (8.6.3) is outdated and does not reflect the syntax as described in the Mermaid documention. On macOS I‘ve tried myself to replace mermaid.min.js with unpkg.com/mermaid@9.1.6/dist/mermaid.min.js - which worked well. The only drawback I see is that this new version doesn‘t show an error image, but that‘s minor I‘d say. Otherwise big benefits, such as subgraph directions etc.

### FSNotes version

5.4.5

### macOS/iOS version

12

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
