### ISSUE TITLE
Change shortcut to delete note

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#14]
Delete note should be `Cmd-Delete`, not `Delete`.

Visually it's currently very difficult to tell if the cursor is in the note edit pane or the note list pane. That makes it very easy to delete a note by mistake, since pressing delete in one pane deletes a character, while pressing it another deletes the entire note. 

Not only is it an easy mistake to make. It's serious because it results in permanent data loss. There's no undo for Delete Note, either inside the app, or by dragging the file from the Trash (it's deleted completely, not moved from trash).

**Comment by jeff-h** [comment]
Might be worth throwing up a confirmation dialog before the app deletes anything. I think I may have a corrupt user defaults file or something, but fsnotes just deleted *everything* inside my Documents folder :o (I had set the fsnotes directory to ~/Documents/fsnotes). Lucky I use time machine!!!

**Comment by glushchenko** [comment]
Checkout https://github.com/glushchenko/fsnotes/releases/download/0.8/FSNotes.app.zip

**Comment by jeff-h** [comment]
I think this can be closed?
