### ISSUE TITLE
Large file stutter

### ISSUE THREAD

**Issue by lzyjxqt** [glushchenko/fsnotes#1402]
### Description

when .md file is larger than 110K
preview markdown or back to code mode would be very slow, it takes more 5 seconds to get a response.
Dear author, would you like fix this? 
Much Thanks

### To Reproduce

1. create a .md file large than 110K
2. preview markdown

### FSNotes version

Version 5.4.5 (530)

### macOS/iOS version

macOS Monterey 12.6 and iOS 16.1

**Comment by glushchenko** [comment]
I can not fix it, performance limited by NSTextView and cmark parser.
