### ISSUE TITLE
fuzzy search for wikilink insertion does not work when note title includes an emoji

### ISSUE THREAD

**Issue by dcd-arnold** [glushchenko/fsnotes#1404]
### Description

If the note to link includes an emoji in the title it is not included as suggestion.

### To Reproduce

1. Create a note and name it "🐡 blowfish"
2. Activate the setting `Auto rename by title`
3. Open another note and type `[[fish`

### Expected behavior

I expect the the note called "🐡 blowfish" to be the first suggestion, but it is not included.

### FSNotes version

Version 5.4.5 (530)

### macOS/iOS version

macOS 12.6 (21G115)

### Additional context

Thank you for FSNotes.

**Comment by glushchenko** [comment]
Fixed. Will be available in next beta.

**Comment by dcd-arnold** [comment]
Nice. Thank you very much.

**Comment by dcd-arnold** [comment]
Tested [FSNotes 6.0.0 Beta 5](https://github.com/glushchenko/fsnotes/releases/tag/v6.0.0b5). Notes with Emoji in their title are included in the suggestion list. Thanks.
