### ISSUE TITLE
Invoking System-wide Custom Key Combo shortcuts results in deleted text

### ISSUE THREAD

**Issue by MMontelimar** [glushchenko/fsnotes#1405]
### Description

Invoking user shortcuts that I've created to trigger system-wide events such as "Insert Date" or "Make Uppercase" results in deletion of text only. 

### To Reproduce

1. **Select** placeholder text or place insertion point. 
2. **Press** user created shortcut to insert current date - in this case - "command-shift-[" 
3. **No date is inserted** and **placeholder text is deleted** (if selected)
4. See attached screen recording. 

https://user-images.githubusercontent.com/53455153/197271634-7ca053ae-8ccf-44e6-8918-52432f0d10da.mov

### Expected behavior

Expected behaviour is **insert date**

### FSNotes version

Version 6.0.0 (540)

### macOS/iOS version

Catalina - 10.15.7 

### Additional context

Other user created shortcuts "Make Uppercase" produce the same result.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.4.1

**Comment by MMontelimar** [comment]
Thank you!
