### ISSUE TITLE
Rendering of a parentheses pair

### ISSUE THREAD

**Issue by hasantahir** [glushchenko/fsnotes#1408]
### Description

A pair of parentheses `()` is rendered with a weird font:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/11236148/198341164-c2122ff2-96dd-4c28-8050-0ac76c3639b0.png">

Note how the text in the parenthesis (short intro videos) is displayed in the preview.

Thanks

### To Reproduce

Type:
Lecture 0       everyone else (short intro videos) - _asynchronous_
**Intro to Moodle**
~~Lecture 1 	Introduction to Computers and C Programming	AT~~

and then toggle Preview. 

Using `SFProText-Medium 16.0pt` as the Note font with a preview font size set to `medium`.

### Expected behavior

It should be something like this:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/11236148/198341813-356cdfe5-19df-4a28-abec-80ebc4cb986c.png">

as rendered by this GitHub preview.

### FSNotes version

6.0.0 (541)

### macOS/iOS version

macOS 13

**Comment by glushchenko** [comment]
View -> Preview MathJax disabled
