### ISSUE TITLE
6.0 has broken code signature, cannot be launched without disabling gatekeeper

### ISSUE THREAD

**Issue by core-code** [glushchenko/fsnotes#1412]
### Description

previous releases were properly codesigned with a developer ID codesignature  ( `Developer ID: Oleksandr Glushchenko (866P6MTE92)` ).

6.0.0 is incorrectly signed with an 'Apple Development' signature which can only be used for uploading to the Mac App Store and is not valid for distributing downloadable software ( `Apple Development: Oleksandr Glushchenko (ZR77T7WNC3)` )

consequently the app cannot be launched without disabling gatekeeper:
<img width="372" alt="Screenshot 2022-10-30 at 13 21 54" src="https://user-images.githubusercontent.com/1261954/198878344-e7980cac-79e1-4695-860e-59dc98147062.png">

### To Reproduce

download 6.0.0
try to launch it

### Expected behavior

expect it to launch

### FSNotes version

6.0.0

### macOS/iOS version

any

**Comment by glushchenko** [comment]
Thank you, zip file has been updated, please re-download.

**Comment by core-code** [comment]
thanks confirmed fixed
