### ISSUE TITLE
The editor allows standard macOS rich text editing

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1414]
### Description

When editing a plain text note, the context menu of a text selection offers the standard macOS rich editing controls, like Font > Bold or Make Link. They even work, making stuff actually bold (rather than inserting Markdown formatting) and causing the file modification time to change. But of course the results do not persist.

To avoid confusion, I think those controls should be hidden.

### To Reproduce

1. ⌘ N
2. Type some text
3. Control/right-click on a word
4. Select Font > Bold

### Expected behavior

Nothing should happen. The menu item shouldn't even be there.

### FSNotes version

6.0.0 (542)

### macOS/iOS version

macOS 12.6

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.0.1/FSNotes_6.0.1.zip

**Comment by tewe** [comment]
The menu items are gone. The usual shortcuts don't work, either. Thanks!
