### ISSUE TITLE
Menu bar icon still shows "New RTF"

### ISSUE THREAD

**Issue by scaba** [glushchenko/fsnotes#1415]
### Description

There is still an option to create an RTF document in the menu bar icon

Incidentally, when you click it, it opens a new doc in FSNotes, but then you can't click on anything for a bit. After a while I could edit the doc normally, but it behaves very strangely, e.g., the Preview shortcut doesn't work

<img width="195" alt="image" src="https://user-images.githubusercontent.com/1500865/198904456-5763e034-704f-4f08-8b75-b9ac731b6778.png">

### To Reproduce

Launch FSNotes, right click the menu bar icon

### FSNotes version

6.0.0 (542)

### macOS/iOS version

13.0

**Comment by glushchenko** [comment]
Thanks, fixed

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.0.1/FSNotes_6.0.1.zip
