### ISSUE TITLE
FSNotes 6 won't open

### ISSUE THREAD

**Issue by techieshark** [glushchenko/fsnotes#1416]
### Description

This is all I see when opening the app and it appears stuck here

<img width="775" alt="image" src="https://user-images.githubusercontent.com/1072292/198913773-e64c299f-b57c-47d5-be5a-abf06ce571a9.png">

### To Reproduce

1. Download from https://github.com/glushchenko/fsnotes/releases or App store
2. Open app
3. See that it halts on splash screen

### Expected behavior

App opens and shows all existing notes

### FSNotes version

6.0.0

### macOS/iOS version

12.6 Monterey

### Additional context

On Apple Silicon; downgrading back to version 5.4.5 works

**Comment by glushchenko** [comment]
You hid the notes list and the sidebar. Click View -> Show Note List and View -> Show Sidebar.
