### ISSUE TITLE
Notes out of sync after delete

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#142]
I'm using FSNotes 1.3.1, and I have set it to sort notes by title in ascending order.

When I delete a note, all of the notes below it are out of sync with the content shown in the editor. Thus, if I delete the first note, then the second note shows the content of the first note, the third note shows the content of the second note, and so on. Restarting FSNotes fixes this until I delete another note.

**Comment by glushchenko** [comment]
Fixed in 1.3.2

**Comment by peavine** [comment]
I installed FSNotes 1.3.2 and this issue is fixed. Many thanks!
