### ISSUE TITLE
SSH Error: The operation couldn’t be completed. (Shout.SSHError error 1.)

### ISSUE THREAD

**Issue by gitatmax** [glushchenko/fsnotes#1420]
### Description

After adding my SSH configuration & selecting my SSH keys I'm getting the titular error, `SSH Error: The operation couldn’t be completed. (Shout.SSHError error 1.)`.

### To Reproduce

1. Go to Preferences > Web
2. Fill in your SSH credentials (in my experience I have been unsuccessful using my SSH keys, so the server should be configured to use those)
3. Press the "Upload and test initial data" button
4. See the error

### Expected behavior

The test should complete successfully. Using the same credentials I'm able to access my server in apps like Transmit & Cyberduck

### FSNotes version

6.0.0 (542)

### macOS/iOS version

12.6 (21G115)

### Additional context

Loving 6.0, otherwise!

**Comment by glushchenko** [comment]
Hi, @gitatmax 

There are several options:

1) The permissions of the "Path" folder must allow writing.
2) Have you entered a username?

**Comment by gitatmax** [comment]
Hi @glushchenko, thanks you. Yes, the "Path" appears to be writable & I have entered a username.

**Comment by glushchenko** [comment]
Did you set private and public rsa key? Can you attach screen? Thanks for report.

**Comment by glushchenko** [comment]
Dupe #1425

**Comment by gitatmax** [comment]
@glushchenko Sorry for the slow reply here. I have added the Private & Public key. I will check out #1425; sorry about the dupe-age.

**Comment by glushchenko** [comment]
Did you try 6.0.3? Can you provide settings screenshot?

**Comment by gitatmax** [comment]
Ah, that did the trick—I thought I had the latest but didn't on this machine. Thanks for digging in with me!
