### ISSUE TITLE
Quick note window does not have focus

### ISSUE THREAD

**Issue by tadamcz** [glushchenko/fsnotes#1421]
Many thanks for the new quick note feature! 
### Description

When opening a quick note, it does not have focus.

### To Reproduce

1. Press quick note shortcut
2. Type words, they do not appear in the window

### Expected behavior

1. Press quick note shortcut
2. Type words, they appear in the window

### FSNotes version

6.0.0 (543)

### macOS/iOS version

12.6

**Comment by glushchenko** [comment]
Can not reproduce it. Any additional info?

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.0.2/FSNotes_6.0.2.zip

**Comment by tadamcz** [comment]
The problem still persists in 6.0.2.

I'm not really sure how best to demonstrate the problem. Here's a video:

https://user-images.githubusercontent.com/43300673/200492162-c291ec4d-793c-46bd-9078-e2bb504f6d5b.mov

1. FSNotes is the active application
2. I press the quick note shortcut `ctrl+option+shift+o`
3. The quick note window appears
4. I type text, but it does not appear in the window

The behaviour is the same if FSNotes is not the active application at the start.

**Comment by glushchenko** [comment]
One more try https://github.com/glushchenko/fsnotes/releases/download/6.0.3/FSNotes_6.0.3.zip

If that doesn't work, try resetting all the settings https://github.com/glushchenko/fsnotes/wiki/Preferences-location#how-to-reset-all-settings
