### ISSUE TITLE
Outline Mode with tab and shift-Tab

### ISSUE THREAD

**Issue by dircadmin** [glushchenko/fsnotes#1423]
The possibility to intend rows in an unordered list with the simple press of the tab key and outend it by pressing shift-tab would be a big productivity feature

**Comment by nth-chile** [comment]
There is `cmd + [` and `cmd + ]`

**Comment by dircadmin** [comment]
Beautiful! Exactly what I need, just that I can't use it with a German Keyboard. Just doesn't work, even with the combination for [ which is option + 5

**Comment by dircadmin** [comment]
So my request would be to create a possibility to use this fantastic feature on a German Keyboard. 
If it would be a menu item, then I could use a custom keyboard shortcut to run it for example.

**Comment by dircadmin** [comment]
And now I found out that in German there is a Menu item and that the shortcut is cmd + ö or cmd + ä
SUPER!
Issue closed :)
