### ISSUE TITLE
Note List Hiararchy: Do not aggregate notes on  top level

### ISSUE THREAD

**Issue by exislow** [glushchenko/fsnotes#1424]
I really like your app and it works well (already did the purchase). Thank you for your effort.

I think what is rather annoying for me is, that in the very left lit (file tree) the notes are getting displayed in the whole hierarchy upwards, despite they reside in any random sub-folder. 

Is it possible to have an option, which allows me
1. to see the note count per folder
2. only see the notes (tree leaves) which are actually in this very particular sub-folder and not all the notes, which are living in a sub-sub-sub-folder or whatever.

Let me explain this further with this screenshot:

<img width="225" alt="grafik" src="https://user-images.githubusercontent.com/6794066/199978045-5d933c08-0ae2-4aa7-9871-bb46b5b67264.png">

As you can see my top folder is called "Invest", which has some sub-folders. "Invest" does NOT contain any notes, only sub-folders. If I use FSNotes and click on "Invest" all the notes will be displayed to me, which are contained in this file hierarchy. But this is somehow annoying, since I cannot distinguish at first glance, if the notes are saved in "Invest" or in "Invest -> Crypto" or whatever.

So I would really like basically only to see the leafs (notes) of a node (folder), which are actually the leafs (notes) of the clicked node (folder) of a tree.

Is it possible to get there options implemented? Thanks in advance!

**Comment by glushchenko** [comment]
Right click on the folder -> Show Options -> Show nested folders content

**Comment by exislow** [comment]
Amazing... Maybe I was overwhelmed of this new app and thus was to blind to see this option. Would it still be possible to have a "count badge" next to each folder?

**Comment by glushchenko** [comment]
> Would it still be possible to have a "count badge" next to each folder?

No, this feature not implemented

**Comment by exislow** [comment]
Yes, I know. But is this possible for you to implement this?

**Comment by glushchenko** [comment]
There's no such thing in the plans.

**Comment by exislow** [comment]
Would it be possible to get this on the "plan"?

**Comment by glushchenko** [comment]
You can create a request, and if people vote for it, maybe I'll do it in the future.

**Comment by exislow** [comment]
@glushchenko: How do I create a request and where? I am lost right now...

**Comment by glushchenko** [comment]
You already create one, here. Just open new issue.
