### ISSUE TITLE
Can't setup custom web server to publish note as webpage

### ISSUE THREAD

**Issue by dondia-lab** [glushchenko/fsnotes#1425]
### Description

fsnotes uses port 22 evenif I set port 10223

firewall log:
Nov  4 15:57:04 escoffier kernel: Firewall: *TCP_IN Blocked* IN=eth0 OUT= MAC=*** SRC=***.***.***.*** DST=***.***.***.*** LEN=64 TOS=0x00 PREC=0x00 TTL=53 ID=0 DF PROTO=TCP SPT=65432 DPT=22 WINDOW=65535 RES=0x00 SYN URGP=0

### FSNotes version

6.0.1 (545)

### macOS/iOS version

13.0 (22A380)

**Comment by glushchenko** [comment]
Thank you! Fixed.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.0.2/FSNotes_6.0.2.zip

**Comment by dondia-lab** [comment]
Hi, now I get the Upload error "Set private and public key", but I set (and I want to use) user/password login method...

**Comment by dircadmin** [comment]
..same for me

**Comment by glushchenko** [comment]
Point taken, corrected.

**Comment by glushchenko** [comment]
Guys, please try new build https://github.com/glushchenko/fsnotes/releases/download/6.0.3/FSNotes_6.0.3.zip

**Comment by dondia-lab** [comment]
Great! It works!
