### ISSUE TITLE
Unable to unset ssh private key for git

### ISSUE THREAD

**Issue by Garbee** [glushchenko/fsnotes#1427]
### Description

If you set the SSH private key file, there is no clear way to unset it.

I use 1Password to manage my keys, didn't realize at first this was private only for the target. Rather than an Identity File to lookup in the agent. So I set it to my public key and can't remove the value to use a personal access token to sync with git.

### To Reproduce

1. Go to 'Git preferences'
2. Set the key to any file
3. Try to remove key
4. Notice no obvious way to do it

### Expected behavior

Some button to be available to unset the key file.

### FSNotes version

Version 6.0.1 (545)

### macOS/iOS version

macOS 13

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.0.2/FSNotes_6.0.2.zip

**Comment by Garbee** [comment]
Just dropped that over my app store version. The button works right, thank you.
