### ISSUE TITLE
Выделение формулы жирным

### ISSUE THREAD

**Issue by evgeny-nazarov** [glushchenko/fsnotes#1429]
### Description

**P = v * (p2 - p1)** - такая формула некорректно отображается при включении режима предпросмотра (cmd + /). 
Выделение только наполовину

### To Reproduce

1. написать: **P = v * (p2 - p1)** 
2. нажать cmd+/

### FSNotes version

6.0.2

### macOS/iOS version

12.6

**Comment by glushchenko** [comment]
Треба або екранувати, або вимикати MathJax, а взагалі пішов нахуй кацап. Росія — гній.

**Comment by glushchenko** [comment]
Треба або екранувати, або вимикати MathJax
