### ISSUE TITLE
Canceling a Rename Operation

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#143]
I have noticed a possible issue with rename, which is described as follows:

1) Select a note in the Notes List.

2) CMD+R to rename the note and then immediately press the escape key.

3) FSNotes responds with a dialog stating that a note with the file name already exists.

Thanks.

**Comment by glushchenko** [comment]
Fixed in 1.4

**Comment by peavine** [comment]
I installed 1.4 and everything works great. Thanks.
