### ISSUE TITLE
Open note disappears when you press escape, even when sidebars are hidden

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1430]
### Description

Sometimes when I'm editing a note, I accidentally press escape and the note disappears from the editor pane. This is especially frustrating when the sidebars are hidden. I know that pressing escape moves the cursor to the search field, but I don't see why it should clear the editor pane. It's also a little chaotic that typing in the search field selects notes and makes them show up in the editor. As I type more letters into the search field, the notes in the editor are flashing by. Usually at this point I just remember the name of the note I was working on and type it in to get it to show up again.

Sometimes I want to use the search field but I don't want my current note to disappear until I click on the next note that I'm searching for.

### To Reproduce

1. Select a note
2. Hide sidebars
3. Press escape
4. Screen goes blank. If you press any letter key, a different note opens

### Expected behavior

- Pressing escape shouldn't close the open note
- Typing in the search bar should not open notes

### FSNotes version

6

### macOS/iOS version

13

**Comment by tewe** [comment]
Typing in the search bar should definitely open notes, that's the whole point of the thing.

You can use ⌘ L instead of ESC to jump to the search bar without clearing the editor.

**Comment by nth-chile** [comment]
Why can't it work like Xcode, VSCode, Sublime Text, Notion. Bear, Apple Notes, etc. by not flashing notes across the editor?

**Comment by nth-chile** [comment]
Alright, true. But I would say two changes could be made to make it more intentional, since I seem to do it accidentally and lose my note:

- pressing escape could select and highlight the current search (highlight so if you type then it goes away) but, like Apple Notes, don't clear the editor. Only replace the current note once user starts typing and search query selects another notes
- user should not be able to interact with the sidebars unless they are hidden. or, if you guys don't want to open the sidebar just to enable the hotkeys, then the sidebar should open when you press the hotkey. That's what Bear does. For example, pressing escape while notes list is hidden would be the equivalent of pressing cmd + shift + b, esc

**Comment by tewe** [comment]
As I said, ⌘ L fulfils both of your requirements, though there seems to be a bug where it sometimes shows a pop-up menu and you have to hit it again to unhide the notes list.

**Comment by nth-chile** [comment]
True.

🤔 
I'll have to pay attention next time to see why I press escape and expect something else. Maybe to deselect text?

Is it strange that it's even possible to use the sidebars while they are hidden?
