### ISSUE TITLE
Separate windows do not support all features

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1434]
### Description

At least renaming, deleting and converting the container only work in the main window, not on notes in separate windows.

### To Reproduce

1. Select a note in the Main Window
2. File > Open In New Window
3. Open File menu

<img width="285" alt="CleanShot 2022-11-24 at 09 21 13" src="https://user-images.githubusercontent.com/645412/203730033-33017526-4d2a-45c5-b995-9dc7a0f88b62.png">

### Expected behavior

<img width="285" alt="CleanShot 2022-11-24 at 09 20 54" src="https://user-images.githubusercontent.com/645412/203729966-2471ee6d-926d-4f3b-ba96-a191304cfe94.png">

### FSNotes version

6.0.4

### macOS/iOS version

macOS 12.6.1

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.4.1

**Comment by tewe** [comment]
Renaming was removed from the menu. Deleting is always unavailable. Converting is now available.

**Comment by glushchenko** [comment]
Yes, "Delete" shortcucts intersects with string removing, so it is by design. Renaming doesn't make sense, the default is auto-rename.

But, thank you for response and right questions.

**Comment by tewe** [comment]
> Yes, "Delete" shortcucts intersects with string removing, so it is by design. Renaming doesn't make sense, the default is auto-rename.

That's fine. Just for any usage statistics: I use neither "First line as title" nor "Auto Rename By Title", but File > Rename.
