### ISSUE TITLE
Link at top line of a file can rename the current file and link to itself

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1439]
### Description

When you have the setting where note filenames match whatever is in the first line, and the first line is a [[Link]], the file gets renamed to "Link 1" and if you click the link, instead of taking you to "Link.txt" it takes you to "Link 1.txt"

### To Reproduce

1. Set "Files naming" setting to "Auto Rename By Title"
2. Create a file with the first line to say "Test". The filename will become "Test"
3. Create a file with the first line to say "Link". The filename will become "Link"
4. In "Test", replace the first line with [[Link]]. Filename becomes "Link 1". Assuming the "1" is added because there is already a file named "Link"
5. Click on the link. It links to itself

### Expected behavior

Shouldn't [[Link]] link to "Link" instead of "Link 1"?

### FSNotes version

6.0.0

### macOS/iOS version

macOS Ventura

**Comment by glushchenko** [comment]
Available in 6.1.0
