### ISSUE TITLE
Notes with tags created in desktop v.6 are not recognised on mobile app v.5.0.4

### ISSUE THREAD

**Issue by halyph** [glushchenko/fsnotes#1441]
### Description

Notes created in desktop app (v.6.0.4) with tags without spaces after the tags or not recognised by mobile iOS app v.5.0.4.

What does it mean? When you select a folder with dedicated notes (i.e. define context) the related tags will not be rendered (see details below)

### To Reproduce

1. Go to desktop app v.6.0.4
2. Create folder "MyFolder"
3. Create two notes (see below)

```
# Title
#tag

Text
```

```
# Title 2
#foo #bar

Text text2
```

please note, I haven't added spaces at the end of `tag` and `bar` tags

<img width="1037" alt="Screenshot 2022-11-30 at 20 40 30" src="https://user-images.githubusercontent.com/241654/204892807-5cfc650a-56e0-4bdb-a56c-9918ba14668e.png">

As you can see desktop app rendered all tags for "MyFolder"
5. Go to mobile app v. 5.0.4
6. Select "MyFolder" folder
<img src="https://user-images.githubusercontent.com/241654/204893309-1d2133c8-b97f-47f1-9949-ffe9cda1284e.png" width="400" />

As you can see mobile app didn't render any tags for "MyFolder".
7. Go to note with title "Title" and add a space at the end of `#tag` tag, like this `#tag `
8. Check rendered tags on mobile app again
<img src="https://user-images.githubusercontent.com/241654/204894534-a9738bfd-9079-46c6-8dd4-a6bde34521fa.png" width="400" />
9. Go to note with title "Title 2" and add a space at the end of `#bar` tag, like this `#bar `

<img src="https://user-images.githubusercontent.com/241654/204895136-b67a2055-f915-4ac6-817a-161e781f63a9.png" width="400" />

All expected tags have been rendered by FSNotes mobile app 

### Expected behavior

All tags are rendered for both apps: mobile and desktop.

### FSNotes version

iOS 5.0.4 build 245, macOS Version 6.0.4 (551)

### macOS/iOS version

macOS 12.6 (21G115), iOS 16.1.2

**Comment by postprivee** [comment]
@halyph tried to reproduce. tags showed up on iphone without adding space/editing notes but it took some time. I guess its related to icloud sync

**Comment by glushchenko** [comment]
Did you try FSNotes 5.1 for iOS?

**Comment by postprivee** [comment]
reproduced the issue
macOS v6.1.1
iOS v5.1.0

**Comment by glushchenko** [comment]
Feel free to reopen, this seems to have been fixed a long time ago.
