### ISSUE TITLE
Code execution in notes

### ISSUE THREAD

**Issue by tsyganov-ivan** [glushchenko/fsnotes#1442]
### Description

Currently, we don't have the possibility to save notes, containing some code instructions. I found only print statements. Potentially executing code here may be a security issue in some cases.

### To Reproduce

1. Go to any node in edit mode
2. Put the code, contains `{print(1+1+1)}`
3. Enable view mode
4. You will see `3`

### Expected behavior

Code block should be equal to entered text without execution.

In this case - `{print(1+1+1)}`

### FSNotes version

Version 6.0.4 (551)

### macOS/iOS version

12.5 (21G72)

### Additional context

From some points of view it may be an interesting feature. But IMHO this feature should be optional and disabled by default for security reasons.

**Comment by glushchenko** [comment]
This is a part of SoulverCore feature:

https://twitter.com/FSNotesApp/status/1593356642455896064

You can disable it in View -> Preview Soulver Calculator
