### ISSUE TITLE
Git error

### ISSUE THREAD

**Issue by sepy97** [glushchenko/fsnotes#1443]
### Description

Impossible to use git versioning with the app: it doesn't create .git in the directory mentioned in "Git" section of the settings. 
![Screenshot 2022-12-13 at 11 20 30 AM](https://user-images.githubusercontent.com/8863017/207425349-d68424e6-88f1-4c26-94cb-f5af9089c3be.png)
![Screenshot 2022-12-13 at 11 20 47 AM](https://user-images.githubusercontent.com/8863017/207425391-8a9b2acd-064b-46fd-8e2a-fcf810435b43.png)

When I try to save a note, I get an error:
![Screenshot 2022-12-13 at 11 21 18 AM](https://user-images.githubusercontent.com/8863017/207425488-e5e83a15-2dd5-49e5-aff4-f113d8cd2cf1.png)

### To Reproduce

1. Go to any note from "Welcome" directory
2. Click on 'Save Revision'
3. See error

### Expected behavior

It should create .git repo, make a commit with some default message (unless toggle "Ask commit message" is set)

### FSNotes version

6.0.5 (553)

### macOS/iOS version

macOS 13.0.1

### Additional context

git version 2.39.0

The app was installed from MacAppStore, but same issue was appearing when it was installed from homebrew or binary you've provided on github.

**Comment by micheldebree** [comment]
I experience the same issue. Tried to move my git repo to a new location. Now it won't pick up the repo.
I would like to start over with a new clean repo but when I try to do that, I also encounter the Git error 7.

Is there a way to force fsnotes to create a new git repo when there is nothing there?

**Comment by glushchenko** [comment]
Thanks, guys! Fixed. Update tomorrow.

**Comment by glushchenko** [comment]
Please check https://github.com/glushchenko/fsnotes/releases/download/6.0.6/FSNotes_6.0.6.zip

**Comment by sepy97** [comment]
Thank you, local git versioning is working now! However, pushing to the remote repo is not working for me :( Gonna open another ticket for that.
