### ISSUE TITLE
App doesn't push commits to the remote repository

### ISSUE THREAD

**Issue by sepy97** [glushchenko/fsnotes#1446]
### Description

The latest release fixed local git versioning. But now it seems to be impossible to add remote origin: when I do that in the settings page, it's not being saved ('Origin for main project' is empty again after I restart the app) and commits are not being pushed.
<img width="546" alt="Screenshot 2022-12-25 at 11 32 19 AM" src="https://user-images.githubusercontent.com/8863017/209479972-3f71d3cd-b18b-413e-b806-0a5fcf04d44d.png">

Even adding git remote url to the repository being created by FSNotes is not helpful: app doesn't see that and I have to push local modifications manually (by executing command 'git push -u origin')

### To Reproduce

1. Go to 'Preferences/Git'
2. Save your github repo url
3. Try to save a note (make a commit)
4. Observe the absence of any modifications on the github page (while there are new commits at the local repo)

### FSNotes version

6.0.6

### macOS/iOS version

13.0.1

**Comment by glushchenko** [comment]
Did you try paste origin and press Return?

**Comment by sepy97** [comment]
That's the settings page after I press Return:
<img width="548" alt="Screenshot 2022-12-25 at 12 05 25 PM" src="https://user-images.githubusercontent.com/8863017/209480706-e26f925a-0985-445f-8688-99ed2816c8c9.png">

That's what happens to the note (no versioning at all):
<img width="578" alt="Screenshot 2022-12-25 at 12 05 33 PM" src="https://user-images.githubusercontent.com/8863017/209480695-47e6bbd7-c7b3-4fdc-a952-33e87dfd8016.png">

**Comment by glushchenko** [comment]
I need more information, is the repository being created, is pushing from the console working?

**Comment by sepy97** [comment]
I have a repository on github, I can add remote 'from the console' and push it myself, but I can't do that using the app (by adding the url in the settings page).
I think, also worth noting that the repo is private.

**Comment by glushchenko** [comment]
"Remote origin" added automatically on "push", you dont need to add it manually. I still can't reproduce it.

**Comment by sepy97** [comment]
Here is a step-by-step follow up of actions I did:

1. Reset the app (remove ~/Library/Containers/co.fluder.FSNotes/ ; killall cfprefsd )
2. Open the app (all settings are restored to the default); change the 'Default Storage' to local (empty) directory (without moving any notes there)
<img width="549" alt="Screenshot 2022-12-25 at 12 21 36 PM" src="https://user-images.githubusercontent.com/8863017/209481055-22fd2fe4-b859-4cf4-9e25-ff34b26408fd.png">

3. Go to 'Git' settings, set ssh key and add origin
<img width="534" alt="Screenshot 2022-12-25 at 12 25 28 PM" src="https://user-images.githubusercontent.com/8863017/209481133-422241c9-62b3-495d-b7b1-f8ea617d7641.png">

4. Create new note, do some modifications and commits, no history is showing (no .git repository being created)
<img width="495" alt="Screenshot 2022-12-25 at 12 26 46 PM" src="https://user-images.githubusercontent.com/8863017/209481152-bbd01cb6-fa6e-4f93-af63-ce3e1a21ab66.png">

**Comment by glushchenko** [comment]
You need some time after repository will be pushed. Please check whats going on in terminal. Try to resave note a little bit later and check commit push. -- Yours faithfully,Oleksandr HlushchenkoOn 25 Dec 2022, at 21:35, Semen-Pyankov ***@***.***> wrote:﻿
Assigned #1446 to @glushchenko.

**Comment by sepy97** [comment]
Here is another way of me trying to make it work:

1. Reset the app (remove ~/Library/Containers/co.fluder.FSNotes/ ; killall cfprefsd )
2. Open the app (all settings are restored to the default); change the 'Default Storage' to local (empty) directory (without moving any notes there)
3. Go to 'Git' settings, change 'Repositories' to 'Separate .git in project dir'
<img width="551" alt="Screenshot 2022-12-25 at 12 30 56 PM" src="https://user-images.githubusercontent.com/8863017/209481233-e69ddb9e-c460-43e4-96c5-ddf2ffa9a522.png">

4. Add remote origin and set ssh key
<img width="546" alt="Screenshot 2022-12-25 at 12 31 45 PM" src="https://user-images.githubusercontent.com/8863017/209481255-d32c0eaa-3abf-426a-beea-c74f1d6f493b.png">

5. Create a new note and try to do several commits -- no history, no .git repository in the 'Default storage' directory

**Comment by sepy97** [comment]
> You need some time after repository will be pushed. Please check whats going on in terminal. Try to resave note a little bit later and check commit push. -- Yours faithfully,Oleksandr HlushchenkoOn 25 Dec 2022, at 21:35, Semen-Pyankov ***@***.***> wrote:﻿ Assigned #1446 to @glushchenko. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

The thing is, .git repo is not being created when I add remote origin. If I ignore this setting and work only locally, .git is created. When I enter the url and press 'Return', it looks like it's removing .git

**Comment by sepy97** [comment]
> "Remote origin" added automatically on "push", you dont need to add it manually. I still can't reproduce it. Please try to create new test repository on GitHub, add origin and try to clone it from FSNotes.

This new test repository can be empty?

**Comment by glushchenko** [comment]
> Create a new note and try to do several commits -- no history, no .git repository in the 'Default storage' directory

Works fine for me, no any problems, .git repository was created and pushed.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/1089917/209482585-07cf7a94-bc86-450f-8978-9a59c0ed61ef.png">

**Comment by sepy97** [comment]
Yet on my machine it doesn't work...  If I just enter the remote, it doesn't allow the push (gives me gitError code 1), if I clone, it tells me that current .git repo will be removed and the new one will be created instead, although, no .git repo is in the directory after I do 'clone'

**Comment by glushchenko** [comment]
> Yet on my machine it doesn't work...  If I just enter the remote, it doesn't allow the push (gives me gitError code 1), if I clone, it tells me that current .git repo will be removed and the new one will be created instead, although, no .git repo is in the directory after I do 'clone'

Can't help you, sorry.
