### ISSUE TITLE
Shortcuts override input methods

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1447]
### Description

macOS input methods usually take over the keyboard until some text is "committed" to the app you're typing in. FSNotes seems to break that.

### To Reproduce

1. Start a new note
2. Using the Japanese input method, hit the five keys K A N J I

The display will jump from かんじ to 漢字

4. Hit ESC

What you typed will disappear from the note and the focus will jump to the search field.

### Expected behavior

The display jumps back to かんじ and you continue editing.

### FSNotes version

6.0.5

### macOS/iOS version

12.6.2

### Additional context

This works in nvALT.

**Comment by glushchenko** [comment]
Available in 6.1.0

**Comment by tewe** [comment]
Works for me. Thanks!
