### ISSUE TITLE
How to Insert Indent in Fsnotes？

### ISSUE THREAD

**Issue by zyben04** [glushchenko/fsnotes#1448]
I want to make the format of my text just as below by using  FSNotes:

First Text
_&ensp_ Second Text
_&ensp_ Third Text
Fourth Text

Without using lists or numbered lists.
 I wonder how to write the markdown file.

**Comment by zyben04** [comment]
I mean
First Text
&ensp Second Text
&ensp Third Text
Fourth Text

**Comment by zyben04** [comment]
I mean
`First Text
&enspSecond Text
&enspThird Text
Fourth Text`

**Comment by zyben04** [comment]
I mean
`First Text \n &ensp Second Text\n &ensp Third Text \n Fourth Text`

**Comment by zyben04** [comment]
I mean

First Text
_&ensp_ Second Text
_&ensp_ Third Text
Fourth Text

**Comment by gingerbeardman** [comment]
Markdown largely ignores whitespace so it's not really possible to do this. Even if you use tabs or spaces to indent they will be removed during Markdown processing/preview/export.

Unordered lists are the only way.

If you don't like the bullets, you can remove them using "Markdown Preview CSS" in Preferences > Advanced.
