### ISSUE TITLE
Add Alfred Workflow to the new Alfred Gallery

### ISSUE THREAD

**Issue by iandol** [glushchenko/fsnotes#1449]
**Describe your feature request**

Alfred is beta testing a new built-in gallery for workflows: https://alfred.app/workflows/

The benefits are much higher visibility and auto-updating etc. It would be helpful perhaps for people to "discover" FSNotes or make it easier for existing FSNotes users to manage their installed workflow.

See https://www.alfredforum.com/forum/51-submit-your-workflows-to-alfred-gallery/ for details. The main issue I see is that "New titled note from clipboard" uses python which is not installed by default anymore, but the code is easy to change (the only function it uses is `urllib.quote`).

**Additional context**
This concerns macOS.

**Comment by iandol** [comment]
I rewrote "New titled note from clipboard" to remove the python dependency (in fact url encoding is not required anymore as Alfred can do that for you). I also updated the icon etc. @gingerbeardman as the original author do you want to host it in a new repository or do you mind me making a repo to host it?

**Comment by iandol** [comment]
[FSNotes.alfredworkflow.zip](https://github.com/glushchenko/fsnotes/files/10323312/FSNotes.alfredworkflow.zip)

**Comment by gingerbeardman** [comment]
Thanks for taking the time to do these changes. I'll host it if that's OK. 

May I add your credit for these changes?

**Comment by gingerbeardman** [comment]
Added! Your credit in the changelog for 2.2

https://www.alfredforum.com/topic/19551-fsnotes/

**Comment by iandol** [comment]
@gingerbeardman — brilliant, and much appreciated! I do wonder if the auto-update will work as i assumed it needed its own github repo, but I may very well be wrong. Let's see what they say on the forum.

**Comment by gingerbeardman** [comment]
I'm not a fan of the Alfred forum, their mods are really passive aggressive which is why I'm not very active there.

Anyway, I'll watch the topic and if it needs a dedicated repo I can create one.

**Comment by iandol** [comment]
@gingerbeardman — currently the location of the FSNotes folder is hard coded in the `fsf` action. Alfred 5 has a nice new user config system, and one potential tweak would be to offer your existing default (which is iCloud IINM) but an option to change it. The only issue is how to use the user config variable in the file filter scope?

**Comment by gingerbeardman** [comment]
I'll have a think on this

**Comment by iandol** [comment]
Thanks to @gingerbeardman and @vitorgalvao this is now added. We should probably edit the wiki page to point to https://alfred.app/workflows/gingerbeardman/fsnotes/ ?

**Comment by gingerbeardman** [comment]
I've edited the wiki page to turn the "Download" section into "Installation" and explained why the Alfred Gallery is recommended (auto updates). 

Cheers!
