### ISSUE TITLE
Upload Attachment Functionality. [PDF/TEXT files]

### ISSUE THREAD

**Issue by vijaycoderkube** [glushchenko/fsnotes#1451]
Is any feature available to add document attachments like (pdf and text files) to upload in text view?

**Comment by gingerbeardman** [comment]
Not currently.

Do you see it working the same as images, or different?

**Comment by glushchenko** [comment]
Its disabled at this moment, but maybe in future. Still testing server performance.

**Comment by vijaycoderkube** [comment]
In this repo only image attachment functionality is available but I need document selection like pdf or other docs and display preview in text view.
