### ISSUE TITLE
Macos Markdown not rendering

### ISSUE THREAD

**Issue by willxie** [glushchenko/fsnotes#1453]
### Description

I did a fresh install of MacOS 11 recently when it came out (currently on 11.3). And I installed FSNotes with brew. 

Since this migration, I was not able to get FSNotes to render markdown notees when not in edit mode (note selected, but not pressed enter to edit the cursor). The preview CSS in "Preferences" happened to be an empty file. Deleting it FSNotes would create another empty `preview.css`. Replacing it with a markdown CSS file I found online also does not change the behavior. 

<img width="1304" alt="Screenshot 2023-01-07 at 9 07 32 PM" src="https://user-images.githubusercontent.com/4821081/211181466-c0ce40ca-c5c2-4e9e-b4a5-0b880b38bc2d.png">

### To Reproduce

See above.

### Expected behavior

Markdown properly rendered, similar to https://fsnot.es/#features (It was working before the fresh install). 

### FSNotes version

v6.0.6 build 554

### macOS/iOS version

11.3

**Comment by glushchenko** [comment]
What do you do for rendering?

**Comment by willxie** [comment]
Sorry I don't understand the question. 

Maybe I am using the wrong word. I can't get markdown preview to work.

**Comment by glushchenko** [comment]
Whats going on if you press "⌘ + /" ?

**Comment by willxie** [comment]
Oh it's working as intended! I did not know that it's shortcut activated. Thanks!
