### ISSUE TITLE
Crash on "About FSNotes" click

### ISSUE THREAD

**Issue by amarendra** [glushchenko/fsnotes#1454]
### Description

Whenever  "About FSNotes" is clicked, app crashes.

### To Reproduce

Open latest FS Notes Mac (downloaded from Github). 
From the `FSNotes` menu (Top left) option click on `About FSNotes`. 
App crashes.

### FSNotes version

6.1.0

### macOS/iOS version

10.15.7 (19H2026)

**Comment by amarendra** [comment]
[crash.log](https://github.com/glushchenko/fsnotes/files/10373133/crash.log)

**Comment by glushchenko** [comment]
[FSNotes_6.1.1.zip](https://github.com/glushchenko/fsnotes/files/10416265/FSNotes_6.1.1.zip)

**Comment by glushchenko** [comment]
Please check FSNotes 6.1.1

**Comment by amarendra** [comment]
Works fine.
