### ISSUE TITLE
String in parenthesis rendered wrongly

### ISSUE THREAD

**Issue by IvanKostyuk** [glushchenko/fsnotes#1455]
### Description

Created a note.
Add a string with something in parenthesis like
simple (do not use on system level)

When rendered shown in surprising way

### To Reproduce

1. Go to 'Search or create'
2. type any new name for a note
3. Paste string `simple (do not use on system level)`
4. Toggle Preview (button, menu, or shortcut) 

See surprising render

![image](https://user-images.githubusercontent.com/17881160/211940448-c744a11a-c2d0-46a8-984b-5ef52a1f15c2.png)

### Expected behavior

the string shown as
`simple (do not use on system level)`

### FSNotes version

Version 6.1.0 (555)

### macOS/iOS version

macOS 13.1 (22C65)

**Comment by glushchenko** [comment]
View -> Preview MathJax

**Comment by Koloth** [comment]
Isn't this non-standard behavior for MathJax?  Typically, MathJax enters math mode by `\( f(x) = x^2 \)` not just `( f(x) = x^2 )`.
