### ISSUE TITLE
FS Notes is not available in Russian App Store for iPhones

### ISSUE THREAD

**Issue by bikulov** [glushchenko/fsnotes#1457]
Hello! FS Notes is not available in Russian App Store for iPhone. Is it bug or it was made on purpose?

**Comment by glushchenko** [comment]
The app is not available in the Mac App Store and App Store for Russian users, Russia is under sanctions for terrorist activities in Ukraine.

![2796803-2](https://user-images.githubusercontent.com/1089917/212570194-c61455d1-d412-4260-a9ab-d8187e30391a.jpg)

All Russians are responsible for this war, without exception.
