### ISSUE TITLE
Using X button to clearing search that came from URL scheme does not refresh matches

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1459]
### Description

Using X button to clearing search that came from URL scheme does not refresh matches

> https://github.com/glushchenko/fsnotes/wiki/Finding-&-creating-documents-via-URLs

Yes, I'm still using FSNotes! 🙌

### To Reproduce

1. Use URL scheme to search FSNotes, [fsnotes://find/test](fsnotes://find/test)
2. FSNotes will open with search term and matching results
3. Click X button in search field

## Screen recording
https://user-images.githubusercontent.com/49612/213243633-1c5e951e-a2f6-4ef9-b16d-1044c7f000c5.mov

### Expected behavior

- clicking X should refresh search results

### FSNotes version

6.1.1

### macOS/iOS version

12.6.2

### Additional context

- Pressing **Escape** key to clear the search _does refresh the search_

## Screen recording
https://user-images.githubusercontent.com/49612/213243807-e619519e-2ec3-4ec5-99e9-1489d5be2221.mov

**Comment by glushchenko** [comment]
Seems it fixed, thanks, Matt
