### ISSUE TITLE
Per-folder sort options

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1469]
**Describe your feature request**
It would be useful to sort some folders differently to others.

- folder of journal entries, or folder of surnames, etc: sort by title (so they would maintain chronological order)
- but the default for other folders would be modified time

**Additional context**
From: https://github.com/glushchenko/fsnotes/issues/1296#issuecomment-1402772956 by @adamshand

**Comment by glushchenko** [comment]
Did you try "Show options"?

<img width="318" alt="image" src="https://user-images.githubusercontent.com/1089917/216678695-792a26da-3b15-493e-a98a-9f57f5bd52ec.png">

**Comment by gingerbeardman** [comment]
AHA! Nice.

Thanks.
