### ISSUE TITLE
Feature Request: alternate or multiple note locations on iOS

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#147]
For syncing between FSNotes on macOS and iOS, I'd much rather keep my notes in Dropbox than iCloud Drive. I am wondering if you'd consider adding into the iOS version either the option of adding multiple note locations like the Mac version has, or choosing an alternative location instead of iCloud Drive.

**Comment by maccius** [comment]
I second this.  At the very least it would be nice to be able to select a folder other than the "FSnotes" folder in iCloud drive.  I keep my plaintext notes in a dedicated "notes" folder, which multiple clients then dip into.

**Comment by glushchenko** [comment]
At this moment only UIDocumentBrowserViewController grant permissions for read/write non app folders in iCloud Drive. UIDocumentBrowserViewController very limited ...

**Comment by jeff-h** [comment]
I'm a little confused. In your iOS screenshot (on https://github.com/glushchenko/fsnotes) you appear to have numerous Folders: iCloud Drive, Cheatsheets, Movies Review, FSNotes, and Test. How are you adding those?

**Comment by glushchenko** [comment]
Just make folder inside iCloud Drive:

<img width="778" alt="screen shot 2018-06-20 at 17 30 13" src="https://user-images.githubusercontent.com/1089917/41665024-af49f526-74af-11e8-9dc6-b1bed68dd16d.png">

**Comment by jeff-h** [comment]
Ah! In that case it's a little unexpected that the subfolders are listed underneath iCloud Drive rather than nested as per the macOS version. However, I don't really use iOS a lot so it could just be me.

**Comment by glushchenko** [comment]
Folders working in same way as macOS. Just listed in sidebar without any hierarchy.

**Comment by zaromedia** [comment]
I would add the idea that has been used extremely effectively in the iA Writer App... in iA, one is given the option to "Add Location", whereupon clicking, you see your iCloud Drive with all of the folders in it. You then select and open the folder you want (such as a dedicated notes folder or the notes folder of a different App), and presto... it now appears in your Location in the main screen, meaning you're only 1 click away from all your notes... just as with the Desktop version... so far iA is the only App on the market that I've seen that handles this in this way (others get close but not as elegantly). I've stopped using FSNotes specifically for this reason (DropBox is not an option for me).. but if this functionality or better is added, I guarantee I won't be the only one to return! Thank you!

**Comment by glushchenko** [comment]
Good news guys!

https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories

> With iOS 13, users can select a directory from any of the available file providers using a UIDocumentPickerViewController. The document picker returns a security-scoped URL for the directory. Security-scoped URLs permit your app to access content outside its container. In this case, the URL lets your app recursively access the directory and all of its contents. This includes accessing any new items added to the directory in the future. Your app can even save a bookmark for this URL, letting it access the directory the next time it launches.

That means we can implement feature request 😎

**Comment by fuzzy76** [comment]
@glushchenko According to that link, you should be able to select folders inside other providers than just iCloud?

```With iOS 13, users can select a directory from any of the available file providers using a UIDocumentPickerViewController```

If my assumption is correct, that would let me select folders inside Onedrive or Dropbox as long as I have those apps installed?

**Comment by r3a1d3a1** [comment]
It will be great to have alternative cloud solutions than iCloud, as it eliminates the burden of a _paid_ developer account to benefit from the iOS app.

**Comment by Jon-Schneider** [comment]
@glushchenko was support for other cloud providers ever implemented? This ticket is marked as done but I can't find support inside the iOS app.

**Comment by glushchenko** [comment]
@Jon-Schneider this is not working for cloud providers. Apple restricted it.

**Comment by fuzzy76** [comment]
@glushchenko but the page specifically says "With iOS 13, users can select a directory from any of the available file providers"?

**Comment by gingerbeardman** [comment]
Also see #432

**Comment by r3a1d3a1** [comment]
2Do is an example app which can rely on DropBox for storage and syncs well between Mac & iPhone.
Maybe if user data is encrypted before storage, Apple wouldn't mind, as it's usually picky on the issue of privacy.
Case in point, 2Do applies encryption.

**Comment by Jon-Schneider** [comment]
iOS eng here. I took a look at ```UIDocumentPickerViewController``` and after a brief look I don't think it will do what you want. What FSNotes requires is continuous access to a directory managed by another app while it's running. UIDocumentPickerViewController allows a user to manually (via an on-screen view) import and export documents from another app integrated into Files, but this doesn't take place in the background.

To the best of my knowledge what FSNotes needs doesn't exist within iOS - Apple keeps things sandboxed except with clear user permission and (frequently) interaction. Since iOS doesn't offer native functionality each cloud provider's SDK would have to separately integrated, or what may work is replacing the current syncing layer with a single lib like https://github.com/amosavian/FileProvider that handles multiple cloud providers. I can't speak to the quality of this one, it was the first one I saw come up on Google. Currently it claims to support iCloud, Dropbox, and OneDrive (a nice option for a lot of people locked into the Microsoft Ecosystem but don't love OneNote).

**Comment by gingerbeardman** [comment]
Thanks @Jon-Schneider !

**Comment by fuzzy76** [comment]
@Jon-Schneider what about

> The document picker returns a security-scoped URL for the directory. Security-scoped URLs permit your app to access content outside its container. In this case, the URL lets your app recursively access the directory and all of its contents. This includes accessing any new items added to the directory in the future. Your app can even save a bookmark for this URL, letting it access the directory the next time it launches.

**Comment by Jon-Schneider** [comment]
Whoops. Thanks @fuzzy76 for reading it better than I did!

**Comment by fuzzy76** [comment]
@glushchenko if this has been available for 5 years, any chance of getting this issue reopened?

**Comment by glushchenko** [comment]
@fuzzy76 i am completely satisfied with iCloud Drive.

**Comment by fuzzy76** [comment]
That is a sharp change from your statement in 2019, and noted.

**Comment by glushchenko** [comment]
del

**Comment by fuzzy76** [comment]
You absolutely do not owe me anything. I just assumed you still wanted to get this functionality, but somehow had missed the posts since your last comment. You feeling differently about this is perfectly fine. :)

**Comment by glushchenko** [comment]
Can you explain clearly what you want? As I see it, you can now even connect folders from Dropbox, and it works (it didn't work before), but Apple has fixed that. 

Thank you for your interest in any case.

**Comment by fuzzy76** [comment]
Like many others, I am not allowed to keep any work-related information outside of work-approved (and administered) storage systems. This means that my work notes can be in OneNote or OneDrive, but not in iCloud or Dropbox.

But I'm sorry if I came off as entitled. I hoped FSnotes could be a solution for my work notes, but you are fully in your right to determine the direction of the project.
