### ISSUE TITLE
Wiki latest release bitly link is broken

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1470]
### Description

Wiki latest release bitly link is broken

### To Reproduce

1. https://github.com/glushchenko/fsnotes/wiki
2. click link to latest release
3. broken link (server not found for me)

<img width="689" alt="image" src="https://user-images.githubusercontent.com/49612/214553564-9aae6615-fe5c-4fe7-9c5d-c2ad84d94521.png">

### Expected behavior

- should go to latest release

### FSNotes version

- n/a

### macOS/iOS version

- n/a

### Additional context

- I did not want to change it without you knowing about it

**Comment by glushchenko** [comment]
Interesting, i dont see any broken links. This https://github.com/glushchenko/fsnotes/releases/latest works fine for me.

**Comment by glushchenko** [comment]
Are you sure you don't use any plug-ins in your browser?

**Comment by gingerbeardman** [comment]
Well, somebody else changed it a few days ago.

https://github.com/glushchenko/fsnotes/wiki/Home/_compare/0f93722cb66a4a95546fe9697342d040327aa4ff


Was the bit.ly link yours?

**Comment by glushchenko** [comment]
OMG, I didn't see that.

**Comment by glushchenko** [comment]
Now this allowed for collaborators only. Thanks, Matt!

<img width="329" alt="image" src="https://user-images.githubusercontent.com/1089917/215599930-85f67516-8d0b-4a1b-8a2b-a77bd94691e9.png">

**Comment by gingerbeardman** [comment]
OK.

So the bit.ly link... was added by @brlbr but this user no longer exists. Very strange!

https://github.com/glushchenko/fsnotes/wiki/Home/3ebf6ba90790268651184b52b48c29d8fbbea6b2
