### ISSUE TITLE
Opening the Notes List context menu locks up the app

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1477]
### Description

Opening the context menu on a Notes List item reliably beachballs the app, until force quit.

[Spin dump](https://github.com/glushchenko/fsnotes/files/10670061/spindump.txt)

A workaround is using the File menu, which has most of the same items.

### To Reproduce

1. Two-finger tap on any note in the list

### Expected behavior

Have the context menu not just open, but also allow a selection from it, without locking up the app.

### FSNotes version

6.1.3 (559)

### macOS/iOS version

macOS 12.6.2

### Additional context

One difference between the File menu and the context menu is that History is a sub-menu. The spin dump shows a lot of Git. The version I first noticed this with included some changes to the Git code. So that's where I'd look.

**Comment by glushchenko** [comment]
Ho many commits do you have?

**Comment by tewe** [comment]
`git --git-dir=a7cf...git rev-list --count HEAD` says 776.

**Comment by glushchenko** [comment]
It's not much, it's very strange why that is.

**Comment by tewe** [comment]
`time git --git-dir=a7cf...git/ log -- Some.textbundle/text.md` takes 1.6 seconds, which seems long but is much much less than what the app needs.

**Comment by glushchenko** [comment]
I think I reproduced it, looking for a solution

**Comment by glushchenko** [comment]
Please try this https://github.com/glushchenko/fsnotes/releases/download/6.1.4/FSNotes_6.1.4.zip

**Comment by tewe** [comment]
Unfortunately that didn't help.

[Spin dump](https://github.com/glushchenko/fsnotes/files/10819347/Sample.of.FSNotes.txt.gz)

I noticed that notes pages take longer than others. This seems more related to how long ago the first revision was than to how many there are.

**Comment by tewe** [comment]
I can no longer reproduce this in FSNotes 6.8.0 for macOS. Thanks!
