### ISSUE TITLE
Mathematical formulas are not supported on the computer

### ISSUE THREAD

**Issue by holton-jiang** [glushchenko/fsnotes#1478]
**Request support for mathematical formulas on desktop**
The computer does not support mathematical formulas, but the mobile phone can.

![IMG_6771](https://user-images.githubusercontent.com/88922715/217459874-cd19fbbb-bcf6-4a07-8d13-a0ab29bc03aa.PNG)

<img width="655" alt="截屏2023-02-08 15 14 52" src="https://user-images.githubusercontent.com/88922715/217460110-fea83699-e56f-486d-9412-b7ccf97f73e8.png">

**Additional context**
macOS and iOS.

**Comment by tewe** [comment]
Try enabling Preview MathJax in the View menu.

**Comment by holton-jiang** [comment]
> Try enabling Preview MathJax in the View menu.

Thanks, it's settled.
<img width="469" alt="截屏2023-02-11 13 56 25" src="https://user-images.githubusercontent.com/88922715/218243134-f1f0ae32-950f-4d5a-9532-5a52009d75c3.png">
