### ISSUE TITLE
iCloud Drive accepted file-types

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#148]
It seems iCloud Drive contains functionality to limit the files that can be dragged into each app's iCloud Drive folder. For example, you can't drag a `.mov` file into the `Preview` folder, but you can drag it into the `TextEdit` folder (and several others).

Unfortunately I can't drag a `.txt`, `.md` nor `.rtf` file into the `iCloud Drive/FSNotes` folder.

![demo](https://user-images.githubusercontent.com/841871/38358732-35cc5e94-391a-11e8-9176-83f1ad6f76f4.gif)

**Comment by glushchenko** [comment]
Can not reproduce :(

**Comment by jeff-h** [comment]
Is anyone else unable to drag those types of files into your FSNotes folder? I just deleted my iCloud FSNotes folder, and opened iOS FSNotes, which immediately regenerated it, but the new version still behaves exactly as per the screencast above.

**Comment by glushchenko** [comment]
I'll try it on another computer, but I'm not sure. Current behavior:

https://f001.backblazeb2.com/file/og-files/Screen-Recording-2018-06-25-10-32-17.mp4
