### ISSUE TITLE
different backgroud color between menu items and backgroud in the sidebar

### ISSUE THREAD

**Issue by scplwq** [glushchenko/fsnotes#1480]
### Description

see this picture

Color A is darker than color B

<img width="244" alt="screenshot" src="https://user-images.githubusercontent.com/2369029/217481480-275158e0-54e4-43b5-94da-aa3654e67f53.png">

I am not sure it's a bug or feature...

### To Reproduce

1. Go to 'Preferences' -> 'Advanced' -> 'Appearance'
2. Click on 'Appearance' options
3. Scroll down to 'Dark'

<img width="365" alt="Screen Shot 2023-02-08 at 4 55 38 PM" src="https://user-images.githubusercontent.com/2369029/217481964-4a514a91-1aae-4211-92ae-1d6797af39d5.png">
4. See Sidebar

### Expected behavior

i hope the siderbar has only one backgroud color

### FSNotes version

6.1.3

### macOS/iOS version

10.15.7

**Comment by glushchenko** [comment]
Fixed in #1574
