### ISSUE TITLE
Possible password exposure in Settings > Git

### ISSUE THREAD

**Issue by StormCraft** [glushchenko/fsnotes#1481]
### Description

In the greyed out text intended as an example for the user, it appears as if you may have included your own push credentials:

<img width="553" alt="Screenshot 2023-02-13 at 10 47 58" src="https://user-images.githubusercontent.com/4216916/218633989-8362df2d-2ac9-41c8-b031-b175bf24661e.png">

### FSNotes version

6.1.3

### macOS/iOS version

macOS 13.1

**Comment by glushchenko** [comment]
Thanks, but no, this is random generated key :)
