### ISSUE TITLE
Menu bar items should be reordered

### ISSUE THREAD

**Issue by dylanseeger** [glushchenko/fsnotes#1482]
### Description

The current order is:

"**FSNotes** File Sidebar Edit Format View Window Help"

For the sake of consistency with the rest of the system, the items listed under "Sidebar" should be moved to the "File" menu and the menu bar's order should be as follows:

"**FSNotes** File Edit View Format Window Help"

### To Reproduce

Look at the menu bar. Compare with other apps, like Finder, Safari, and Mail.

### FSNotes version

6.1.3 (559)

### macOS/iOS version

macOS 13.2

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.2.3
