### ISSUE TITLE
Todo strikethrough displays inconsistently

### ISSUE THREAD

**Issue by dylanseeger** [glushchenko/fsnotes#1484]
### Description

When a todo is marked as complete, the associated text doesn't display with a strikethrough until the text is edited again. This issue is especially common when the CMD-T keyboard shortcut is used to mark a todo as complete.

### To Reproduce

Mark a todo as complete using the CMD-T keyboard shortcut.

### FSNotes version

6.1.3 (559)

### macOS/iOS version

macOS 13.2

**Comment by dylanseeger** [comment]
The strikethroughs also disappear frequently on indented todos.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.4.1
