### ISSUE TITLE
Saving revision doesn't work

### ISSUE THREAD

**Issue by Diadlo** [glushchenko/fsnotes#1485]
### Description

I wanted to use automatic snapshot creation, but it does nothing. Then I enabled manual to check it. And clicking "Save revision" and "Cmd + S" does nothing. "History" shows only one revision (the first one).

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/6306608/219363171-1bdb7c36-0ede-4fca-bc7f-eb9b4f0ed857.png">

### To Reproduce

1. Change text in "Introduction" note
2. Click right mouse button on "Introduction" note
3. Click "Save revision"
4. Check "History" section of "Introduction" note

### Expected behavior

New line in "History" menu should appear

### FSNotes version

6.1.3 (559)

### macOS/iOS version

macOS Ventura 13.1 (22C65)

**Comment by tewe** [comment]
Git does not support commits where nothing changes. If you add a step 2½ where you type some text, it will work as expected.

**Comment by glushchenko** [comment]
@tewe git supports zero commits when no changes in a tree, but this is disabled by me.

**Comment by Diadlo** [comment]
@tewe Is step 1 not enough? I have already changed the content of the original note, but despite clicking "Save revision" multiple times and making several changes to the text, nothing seems to have been updated

**Comment by glushchenko** [comment]
@Diadlo please try this https://github.com/glushchenko/fsnotes/releases/download/6.2.2/FSNotes_6.2.2.zip

**Comment by Diadlo** [comment]
@glushchenko Now, at least I have some error message
<img width="372" alt="image" src="https://user-images.githubusercontent.com/6306608/229686036-68ee9df7-778b-48d1-8efd-bfb9aa603e42.png">

But I don't see "Init/commit" button 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/6306608/229686213-aeeb6c45-f325-4659-8e03-f27db29016ed.png">

When I open directory in terminal I see this
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/6306608/229686542-bdc16ca6-015e-4e69-a098-0c64403ac666.png">

It looks like sometimes saving works because there are some commits with "Usual commit" message. But right now it doesn't work again.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.2.3

**Comment by Diadlo** [comment]
@glushchenko Now it works. Thank you!

FYI it looks like tag is placed on the incorrect commit

```
» git show --summary 6.2.3
commit a1c0d9a2b955dffa63c1841cdccc72df0ea24f78 (tag: 6.2.3, tag: 6.2.2, tag: 6.2.1, tag: 6.2.0, origin/master, origin/HEAD, master)
Author: glushchenko <fluder@icloud.com>
Date:   Mon Feb 20 23:26:27 2023 +0200

    - Bump versions

» git show --summary fsnotes6-ios
commit a40c7a5a8adcb052b8fce3e2dd0a003057211c10 (HEAD -> fsnotes6-ios, origin/fsnotes6-ios)
Author: glushchenko <fluder@icloud.com>
Date:   Wed Apr 5 00:50:24 2023 +0300

    #1485

```
