### ISSUE TITLE
Context menu references the wrong item in the notes list

### ISSUE THREAD

**Issue by dylanseeger** [glushchenko/fsnotes#1486]
### Description

When using CTRL+Click to pull up a context menu for an item other than the currently active one in the notes list, the context menu and all of its listed actions actually reference the currently active note.

For example, "Note 1" is active. I CTRL+Click "Note 2" in the note list. I select "Delete" from the context menu. "Note 1" is deleted. This can lead to data loss and general disorientation in the application.

### To Reproduce

1. CTRL+Click any item other than the currently active note
2. Select an action from the context menu, like "Pin" or "Delete"
3. Observe

### FSNotes version

6.1.3 (559)

### macOS/iOS version

macOS 13.2

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.2.3
