### ISSUE TITLE
Tag doesn't work in sublists

### ISSUE THREAD

**Issue by Diadlo** [glushchenko/fsnotes#1488]
### Description

When you create sublist (list element intended with 4 spaces) tag in this line doesn't work. But if you toggle preview tags works fine.

But the most important issue is that this tag isn't shown in tag list in bottom left corner.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/6306608/219714903-04bd272c-ce07-4476-95d2-cee27bf5dc6b.png">

<img width="569" alt="image" src="https://user-images.githubusercontent.com/6306608/219715436-dcc8b01d-3b34-4afa-8cbe-83b0f8f734e0.png">

<img width="429" alt="image" src="https://user-images.githubusercontent.com/6306608/219716365-2ae0509f-03e9-4200-9f70-76e15d396301.png">

### To Reproduce

1. Create node with the following text:
```
# Tag test

Tag that #works/fine
* This is also #fine
    * But this one doesn't #work
* And works #again
```

2. Check `#work` tag in text
3. Check `#work` tag in tag list

### Expected behavior

Tag is highlighted in editor and shown in tag list

### FSNotes version

Version 6.1.3 (559)

### macOS/iOS version

macOS Ventura 13.1 (22C65)

**Comment by Diadlo** [comment]
Found that it works fine when elements are intended with 3 spaces (but not with 6)

**Comment by glushchenko** [comment]
I'm not going to make tagging support for lists.
