### ISSUE TITLE
Feature Request: create a duplicate copy of a note

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#149]
I often need to create a duplicate copy of a note and haven't been able to find a keyboard shortcut or menu item that performs this function directly. Please consider this for inclusion in a future version of FSNotes.

BTW, I installed FSNotes 1.4.1 and it's excellent. I can usually find some issue to complain about but 1.41 has me stumped  :)

**Comment by jeff-h** [comment]
Sorry to be off-topic, but I agree — 1.4.1 is feeling really great! It's a credit to your intensive hard work. I didn't actually realise you'd released it as I usually check here on Github first, assuming the App Store review will hold it up, but I went and updated via the App Store and there it is :)

**Comment by peavine** [comment]
Installed 1.9 and this works great. I can now create time-stamped versions of a note and store older versions as needed in the archive. Really a nice enhancement.
