### ISSUE TITLE
ios app won't open without crashing

### ISSUE THREAD

**Issue by catraf** [glushchenko/fsnotes#1490]
### Description

I just installed the app on iOS 12.5.7.

When I go to open FSNotes, it crashes straight away before opening the app.

### To Reproduce

1. Go to homescreen
2. Click on FSNotes icon
3. FSNotes opens for a brief second and then crashes

See video:
https://user-images.githubusercontent.com/93711577/220797594-8bdce449-fa28-492a-97b1-ea02493fd50a.MP4

### Expected behavior

The app would open and not crash

### FSNotes version

5.1.0

### macOS/iOS version

12.5.7

### Additional context

I'm using an iPhone 6. 

iCloud Drive is already enabled in the settings.

**Comment by glushchenko** [comment]
Did you try to move all notes from iCloud Drive to another folder and try again? Crash report will be appreciated too.

**Comment by catraf** [comment]
I tried moving out all my notes out of iCloud Drive so it was emptied and it still crashed.

I've sent you a crash report to your email.

If you have any more ideas, that would be great but it could just be that my old iPhone is not up to it.

**Comment by glushchenko** [comment]
Sorry, but iOS 14 is minimum for continue development on my setup, so i cannot help.
