### ISSUE TITLE
Note font color changes will not work and may invalidate the theme

### ISSUE THREAD

**Issue by cycle2zhou** [glushchenko/fsnotes#1491]
### Description

<img width="607" alt="image" src="https://user-images.githubusercontent.com/33155330/220826336-1d0031bb-b343-4f30-b6a5-d8757185ef60.png">

### To Reproduce

1. Preferences - Layout 
2. Change note font color and background color 
3. Restart the app

### Expected behavior

Note font and background color changed to correct Settings

### FSNotes version

6.1.4

### macOS/iOS version

macOS 13.2.1

### Additional context

![Uploading image.png…]()

**Comment by cycle2zhou** [comment]
The network problem has been submitted repeatedly😓

**Comment by glushchenko** [comment]
You can not use custom backgrounds for dark mode
