### ISSUE TITLE
Note font color changes will not work and may invalidate the theme

### ISSUE THREAD

**Issue by cycle2zhou** [glushchenko/fsnotes#1492]
### Description

<img width="607" alt="image" src="https://user-images.githubusercontent.com/33155330/220826336-1d0031bb-b343-4f30-b6a5-d8757185ef60.png">

### To Reproduce

1. Preferences - Layout 
2. Change note font color and background color 
3. Restart the app

### Expected behavior

Note font and background color changed to correct Settings

### FSNotes version

6.1.4

### macOS/iOS version

macOS 13.2.1

### Additional context

<img width="607" alt="image" src="https://user-images.githubusercontent.com/33155330/220826352-29dfc48d-ac2d-4c11-a366-7c827cfe7063.png">

**Comment by cycle2zhou** [comment]
dark mode font colors still don't work

**Comment by glushchenko** [comment]
Yep, by design. Only one color suitable for dark mode

**Comment by cycle2zhou** [comment]
Is there no way to customize the font color in dark mode? The current colors are too harsh for dark mode

**Comment by glushchenko** [comment]
No!
