### ISSUE TITLE
Automatically crashes at intervals

### ISSUE THREAD

**Issue by cycle2zhou** [glushchenko/fsnotes#1496]
### Description

The app runs for a random amount of time and then crashes itself

### To Reproduce

1. Open FSNotes
2. do nothing
3. After a random period of time
4. FSNotes crashed on its own

### FSNotes version

6.1.4

### macOS/iOS version

macOS 13.2.1

### Additional context

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               FSNotes [3858]
Path:                  /Applications/FSNotes.app/Contents/MacOS/FSNotes
Identifier:            co.fluder.FSNotes
Version:               6.1.4 (559)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-03-06 11:36:39.5479 +0800
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Anonymous UUID:        FF7C864C-F69A-65F7-7B69-A00754661604

Time Awake Since Boot: 7500 seconds

System Integrity Protection: enabled

Crashed Thread:        2  Dispatch queue: NSOperationQueue 0x139633eb0 (QOS: UNSPECIFIED)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Exception Codes:       0x0000000000000001, 0xfffffffffffffff8

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [3858]

VM Region Info: 0xfffffffffffffff8 is not in any region.  Bytes after previous region: 18446638520056414201  
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)
--->  
      UNUSED SPACE AT END

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1930ca050 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1930dc11c mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1930d2c24 mach_msg_overwrite + 452
3   libsystem_kernel.dylib        	       0x1930ca3cc mach_msg + 24
4   CoreFoundation                	       0x1931e9bb0 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1931e849c __CFRunLoopRun + 1232
6   CoreFoundation                	       0x1931e7878 CFRunLoopRunSpecific + 612
7   HIToolbox                     	       0x19c8c7fa0 RunCurrentEventLoopInMode + 292
8   HIToolbox                     	       0x19c8c7de4 ReceiveNextEventCommon + 672
9   HIToolbox                     	       0x19c8c7b2c _BlockUntilNextEventMatchingListInModeWithFilter + 72
10  AppKit                        	       0x19646d84c _DPSNextEvent + 632
11  AppKit                        	       0x19646c9dc -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 728
12  AppKit                        	       0x196460e0c -[NSApplication run] + 464
13  AppKit                        	       0x196438250 NSApplicationMain + 880
14  FSNotes                       	       0x100a1577c main + 12
15  dyld                          	       0x192ddfe50 start + 2544

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1930ca050 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1930dc11c mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1930d2c24 mach_msg_overwrite + 452
3   libsystem_kernel.dylib        	       0x1930ca3cc mach_msg + 24
4   CoreFoundation                	       0x1931e9bb0 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1931e849c __CFRunLoopRun + 1232
6   CoreFoundation                	       0x1931e7878 CFRunLoopRunSpecific + 612
7   AppKit                        	       0x19659819c _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x19310a06c _pthread_start + 148
9   libsystem_pthread.dylib       	       0x193104e2c thread_start + 8

Thread 2 Crashed::  Dispatch queue: NSOperationQueue 0x139633eb0 (QOS: UNSPECIFIED)
0   FSNotes                       	       0x100a6fc50 __swift_project_boxed_opaque_existential_1 + 0
1   FSNotes                       	       0x100a6fbb8 specialized closure #1 in setAuthenticationCallback(_:authentication:) + 112
2   FSNotes                       	       0x100f0c4fc request_creds + 120
3   FSNotes                       	       0x100f0be34 _git_ssh_setup_conn + 1600
4   FSNotes                       	       0x100f0b6a0 ssh_uploadpack_ls + 100
5   FSNotes                       	       0x100f0b2f8 _ssh_action + 100
6   FSNotes                       	       0x100f05d8c git_smart__connect + 388
7   FSNotes                       	       0x100ed51a0 git_remote__connect + 572
8   FSNotes                       	       0x100ed5fd8 git_remote_fetch + 280
9   FSNotes                       	       0x100a80d90 Remote.fetch(authentication:progress:) + 332
10  FSNotes                       	       0x100a80ed0 Remote.pull(signature:remote:authentication:progress:project:) + 68
11  FSNotes                       	       0x100b650cc Project.pull() + 668
12  FSNotes                       	       0x100b61ee4 closure #1 in EditorViewController.pull(_:) + 664
13  FSNotes                       	       0x100a249e0 thunk for @escaping @callee_guaranteed () -> () + 28
14  Foundation                    	       0x1940d5d50 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
15  Foundation                    	       0x1940d5c10 -[NSBlockOperation main] + 104
16  Foundation                    	       0x1940d5ba0 __NSOPERATION_IS_INVOKING_MAIN__ + 16
17  Foundation                    	       0x1940d4fb8 -[NSOperation start] + 708
18  Foundation                    	       0x1940d4cec __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
19  Foundation                    	       0x1940d4bdc __NSOQSchedule_f + 172
20  libdispatch.dylib             	       0x192f9163c _dispatch_block_async_invoke2 + 148
21  libdispatch.dylib             	       0x192f82504 _dispatch_client_callout + 20
22  libdispatch.dylib             	       0x192f85994 _dispatch_continuation_pop + 504
23  libdispatch.dylib             	       0x192f84ffc _dispatch_async_redirect_invoke + 584
24  libdispatch.dylib             	       0x192f93f94 _dispatch_root_queue_drain + 396
25  libdispatch.dylib             	       0x192f947c0 _dispatch_worker_thread2 + 164
26  libsystem_pthread.dylib       	       0x1931060c4 _pthread_wqthread + 228
27  libsystem_pthread.dylib       	       0x193104e20 start_wqthread + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x193104e18 start_wqthread + 0

Thread 2 crashed with ARM Thread State (64-bit):
    x0: 0x0000600001ccd890   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000193135650
    x4: 0x0000000000000001   x5: 0x0000000000003700   x6: 0x0000000000000074   x7: 0x0000000161c88148
    x8: 0x0000000000746967   x9: 0x0300000000000000  x10: 0xe000000000000000  x11: 0xe000000000000000
   x12: 0x0000600000444f53  x13: 0x0000000000000010  x14: 0x00000000000007fb  x15: 0x00000000c4a0d0b1
   x16: 0x0000000193135700  x17: 0x00000001ef735e98  x18: 0x0000000000000000  x19: 0x0000600001ccd880
   x20: 0x000000016f4764f8  x21: 0x000060000252f700  x22: 0xf000000000000021  x23: 0xe300000000000000
   x24: 0x0000000000746967  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000100a80e8c
   x28: 0x00000001ef7330d0   fp: 0x000000016f4764e0   lr: 0x0000000100a6fbb8
    sp: 0x000000016f476490   pc: 0x0000000100a6fc50 cpsr: 0x40001000
   far: 0xfffffffffffffff8  esr: 0x92000004 (Data Abort) byte read Translation fault

Binary Images:
       0x1930c9000 -        0x193102feb libsystem_kernel.dylib (*) <3dcd49b9-b3c5-3d90-be40-a3b807cb9cd7> /usr/lib/system/libsystem_kernel.dylib
       0x193168000 -        0x19363ffff com.apple.CoreFoundation (6.9) <18260df4-69a8-30d3-8175-fb8ae7ae7709> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19c896000 -        0x19cbc9fff com.apple.HIToolbox (2.1.1) <c68fe2e2-e0f3-3caf-ada3-bcc72fba79d0> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x196434000 -        0x19733ffff com.apple.AppKit (6.9) <88722053-0df0-3d4f-bf55-7e3c2d2c8e29> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x100a10000 -        0x100fd3fff co.fluder.FSNotes (6.1.4) <904910d6-e25b-3743-adb8-c28726c9c84c> /Applications/FSNotes.app/Contents/MacOS/FSNotes
       0x192dda000 -        0x192e64ba3 dyld (*) <191e84f1-4b95-39c8-b253-1c1ef56c0fa8> /usr/lib/dyld
       0x193103000 -        0x19310fffb libsystem_pthread.dylib (*) <9f3b729a-ed04-3e65-adac-d75ad06ebbdc> /usr/lib/system/libsystem_pthread.dylib
       0x194095000 -        0x194acefff com.apple.Foundation (6.9) <c62e0110-c636-396a-9cb6-c3c08392b3fa> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x192f7e000 -        0x192fc5fff libdispatch.dylib (*) <4d52c3a5-32e6-37a2-9d6c-23c612038354> /usr/lib/system/libdispatch.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)
Writable regions: Total=6.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=6.3G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 4800K        8 
CG image                          1072K       35 
ColorSync                          576K       28 
CoreAnimation                    123.7M       96 
CoreGraphics                        48K        3 
CoreUI image data                 2816K       19 
Foundation                          48K        2 
Image IO                          6640K        3 
Kernel Alloc Once                   32K        1 
MALLOC                           442.7M       79 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)           1.1G       10         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        4 
Stack                             9808K        4 
VM_ALLOCATE                      128.8M       22 
VM_ALLOCATE (reserved)             3.9G        1         reserved VM address space (unallocated)
WebKit Malloc                    224.1M        5 
__AUTH                            1827K      348 
__AUTH_CONST                      24.0M      565 
__CTF                               756        1 
__DATA                            12.1M      565 
__DATA_CONST                      27.7M      577 
__DATA_DIRTY                      1944K      221 
__FONT_DATA                        2352        1 
__LINKEDIT                       773.7M       11 
__OBJC_CONST                      4532K      314 
__OBJC_RO                         65.5M        1 
__OBJC_RW                         1988K        1 
__TEXT                           578.2M      599 
dyld private memory                256K        1 
mapped file                      477.3M       98 
shared memory                      912K       16 
===========                     =======  ======= 
TOTAL                              8.3G     3654 
TOTAL, minus reserved VM space     2.9G     3654 

-----------
Full Report
-----------

{"app_name":"FSNotes","timestamp":"2023-03-06 11:36:41.00 +0800","app_version":"6.1.4","slice_uuid":"904910d6-e25b-3743-adb8-c28726c9c84c","build_version":"559","platform":1,"bundleID":"co.fluder.FSNotes","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.2.1 (22D68)","roots_installed":0,"name":"FSNotes","incident_id":"2A24253E-AB5E-437D-BA24-87000F275447"}
{
  "uptime" : 7500,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,2",
  "coalitionID" : 2270,
  "osVersion" : {
    "train" : "macOS 13.2.1",
    "build" : "22D68",
    "releaseType" : "User"
  },
  "captureTime" : "2023-03-06 11:36:39.5479 +0800",
  "incident" : "2A24253E-AB5E-437D-BA24-87000F275447",
  "pid" : 3858,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-03-06 09:58:48.1955 +0800",
  "procStartAbsTime" : 39271526585,
  "procExitAbsTime" : 180185030879,
  "procName" : "FSNotes",
  "procPath" : "\/Applications\/FSNotes.app\/Contents\/MacOS\/FSNotes",
  "bundleInfo" : {"CFBundleShortVersionString":"6.1.4","CFBundleVersion":"559","CFBundleIdentifier":"co.fluder.FSNotes"},
  "storeInfo" : {"deviceIdentifierForVendor":"CC38740B-80C3-5461-BEB0-C29069FDFA67","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "co.fluder.FSNotes",
  "crashReporterKey" : "FF7C864C-F69A-65F7-7B69-A00754661604",
  "throttleTimeout" : 2147483647,
  "sip" : "enabled",
  "vmRegionInfo" : "0xfffffffffffffff8 is not in any region.  Bytes after previous region: 18446638520056414201  \n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-\/rwx SM=NUL  ...(unallocated)\n--->  \n      UNUSED SPACE AT END",
  "exception" : {"codes":"0x0000000000000001, 0xfffffffffffffff8","rawCodes":[1,-8],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0xfffffffffffffff8"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":3858},
  "vmregioninfo" : "0xfffffffffffffff8 is not in any region.  Bytes after previous region: 18446638520056414201  \n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-\/rwx SM=NUL  ...(unallocated)\n--->  \n      UNUSED SPACE AT END",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 2,
  "threads" : [{"id":46432,"queue":"com.apple.main-thread","frames":[{"imageOffset":4176,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":78108,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":39972,"symbol":"mach_msg_overwrite","symbolLocation":452,"imageIndex":0},{"imageOffset":5068,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":531376,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":1},{"imageOffset":525468,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":1},{"imageOffset":522360,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":1},{"imageOffset":204704,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":2},{"imageOffset":204260,"symbol":"ReceiveNextEventCommon","symbolLocation":672,"imageIndex":2},{"imageOffset":203564,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":2},{"imageOffset":235596,"symbol":"_DPSNextEvent","symbolLocation":632,"imageIndex":3},{"imageOffset":231900,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":728,"imageIndex":3},{"imageOffset":183820,"symbol":"-[NSApplication run]","symbolLocation":464,"imageIndex":3},{"imageOffset":16976,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":3},{"imageOffset":22396,"symbol":"main","symbolLocation":12,"imageIndex":4},{"imageOffset":24144,"symbol":"start","symbolLocation":2544,"imageIndex":5}]},{"id":46529,"name":"com.apple.NSEventThread","frames":[{"imageOffset":4176,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":78108,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":39972,"symbol":"mach_msg_overwrite","symbolLocation":452,"imageIndex":0},{"imageOffset":5068,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":531376,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":1},{"imageOffset":525468,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":1},{"imageOffset":522360,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":1},{"imageOffset":1458588,"symbol":"_NSEventThread","symbolLocation":172,"imageIndex":3},{"imageOffset":28780,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":7724,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"triggered":true,"id":135199,"threadState":{"x":[{"value":105553146468496},{"value":0},{"value":0},{"value":6762485328},{"value":1},{"value":14080},{"value":116},{"value":5935497544},{"value":7629159},{"value":216172782113783808},{"value":16140901064495857664},{"value":16140901064495857664},{"value":105553120743251},{"value":16},{"value":2043},{"value":3298873521},{"value":6762485504,"symbolLocation":0,"symbol":"_platform_strlen"},{"value":8312282776},{"value":0},{"value":105553146468480},{"value":6161917176},{"value":105553155258112},{"value":17293822569102704673},{"value":16357073846609641472},{"value":7629159},{"value":0},{"value":0},{"value":4305981068,"symbolLocation":0,"symbol":"Remote.pull(signature:remote:authentication:progress:project:)"},{"value":8312271056,"symbolLocation":0,"symbol":"value witness table for Builtin.UnknownObject"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4305910712},"cpsr":{"value":1073745920},"fp":{"value":6161917152},"sp":{"value":6161917072},"esr":{"value":2449473540,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4305910864,"matchesCrashFrame":1},"far":{"value":18446744073709551608}},"queue":"NSOperationQueue 0x139633eb0 (QOS: UNSPECIFIED)","frames":[{"imageOffset":392272,"symbol":"__swift_project_boxed_opaque_existential_1","symbolLocation":0,"imageIndex":4},{"imageOffset":392120,"symbol":"specialized closure #1 in setAuthenticationCallback(_:authentication:)","symbolLocation":112,"imageIndex":4},{"imageOffset":5227772,"symbol":"request_creds","symbolLocation":120,"imageIndex":4},{"imageOffset":5226036,"symbol":"_git_ssh_setup_conn","symbolLocation":1600,"imageIndex":4},{"imageOffset":5224096,"symbol":"ssh_uploadpack_ls","symbolLocation":100,"imageIndex":4},{"imageOffset":5223160,"symbol":"_ssh_action","symbolLocation":100,"imageIndex":4},{"imageOffset":5201292,"symbol":"git_smart__connect","symbolLocation":388,"imageIndex":4},{"imageOffset":5001632,"symbol":"git_remote__connect","symbolLocation":572,"imageIndex":4},{"imageOffset":5005272,"symbol":"git_remote_fetch","symbolLocation":280,"imageIndex":4},{"imageOffset":462224,"symbol":"Remote.fetch(authentication:progress:)","symbolLocation":332,"imageIndex":4},{"imageOffset":462544,"symbol":"Remote.pull(signature:remote:authentication:progress:project:)","symbolLocation":68,"imageIndex":4},{"imageOffset":1396940,"symbol":"Project.pull()","symbolLocation":668,"imageIndex":4},{"imageOffset":1384164,"symbol":"closure #1 in EditorViewController.pull(_:)","symbolLocation":664,"imageIndex":4},{"imageOffset":84448,"symbol":"thunk for @escaping @callee_guaranteed () -> ()","symbolLocation":28,"imageIndex":4},{"imageOffset":265552,"symbol":"__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__","symbolLocation":24,"imageIndex":7},{"imageOffset":265232,"symbol":"-[NSBlockOperation main]","symbolLocation":104,"imageIndex":7},{"imageOffset":265120,"symbol":"__NSOPERATION_IS_INVOKING_MAIN__","symbolLocation":16,"imageIndex":7},{"imageOffset":262072,"symbol":"-[NSOperation start]","symbolLocation":708,"imageIndex":7},{"imageOffset":261356,"symbol":"__NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__","symbolLocation":16,"imageIndex":7},{"imageOffset":261084,"symbol":"__NSOQSchedule_f","symbolLocation":172,"imageIndex":7},{"imageOffset":79420,"symbol":"_dispatch_block_async_invoke2","symbolLocation":148,"imageIndex":8},{"imageOffset":17668,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":8},{"imageOffset":31124,"symbol":"_dispatch_continuation_pop","symbolLocation":504,"imageIndex":8},{"imageOffset":28668,"symbol":"_dispatch_async_redirect_invoke","symbolLocation":584,"imageIndex":8},{"imageOffset":90004,"symbol":"_dispatch_root_queue_drain","symbolLocation":396,"imageIndex":8},{"imageOffset":92096,"symbol":"_dispatch_worker_thread2","symbolLocation":164,"imageIndex":8},{"imageOffset":12484,"symbol":"_pthread_wqthread","symbolLocation":228,"imageIndex":6},{"imageOffset":7712,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":6}]},{"id":135980,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6762041344,
    "size" : 237548,
    "uuid" : "3dcd49b9-b3c5-3d90-be40-a3b807cb9cd7",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6762692608,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5079040,
    "uuid" : "18260df4-69a8-30d3-8175-fb8ae7ae7709",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1953.300"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6921216000,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3358720,
    "uuid" : "c68fe2e2-e0f3-3caf-ada3-bcc72fba79d0",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6815956992,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15777792,
    "uuid" : "88722053-0df0-3d4f-bf55-7e3c2d2c8e29",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299.40.118"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4305518592,
    "CFBundleShortVersionString" : "6.1.4",
    "CFBundleIdentifier" : "co.fluder.FSNotes",
    "size" : 6045696,
    "uuid" : "904910d6-e25b-3743-adb8-c28726c9c84c",
    "path" : "\/Applications\/FSNotes.app\/Contents\/MacOS\/FSNotes",
    "name" : "FSNotes",
    "CFBundleVersion" : "559"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6758965248,
    "size" : 568228,
    "uuid" : "191e84f1-4b95-39c8-b253-1c1ef56c0fa8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6762278912,
    "size" : 53244,
    "uuid" : "9f3b729a-ed04-3e65-adac-d75ad06ebbdc",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6778605568,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 10723328,
    "uuid" : "c62e0110-c636-396a-9cb6-c3c08392b3fa",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1953.300"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6760685568,
    "size" : 294912,
    "uuid" : "4d52c3a5-32e6-37a2-9d6c-23c612038354",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6758318080,
  "size" : 3447455744,
  "uuid" : "835716ae-b363-3187-b065-cf94139bfc85"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)\nWritable regions: Total=6.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=6.3G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 4800K        8 \nCG image                          1072K       35 \nColorSync                          576K       28 \nCoreAnimation                    123.7M       96 \nCoreGraphics                        48K        3 \nCoreUI image data                 2816K       19 \nFoundation                          48K        2 \nImage IO                          6640K        3 \nKernel Alloc Once                   32K        1 \nMALLOC                           442.7M       79 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)           1.1G       10         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        4 \nStack                             9808K        4 \nVM_ALLOCATE                      128.8M       22 \nVM_ALLOCATE (reserved)             3.9G        1         reserved VM address space (unallocated)\nWebKit Malloc                    224.1M        5 \n__AUTH                            1827K      348 \n__AUTH_CONST                      24.0M      565 \n__CTF                               756        1 \n__DATA                            12.1M      565 \n__DATA_CONST                      27.7M      577 \n__DATA_DIRTY                      1944K      221 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       773.7M       11 \n__OBJC_CONST                      4532K      314 \n__OBJC_RO                         65.5M        1 \n__OBJC_RW                         1988K        1 \n__TEXT                           578.2M      599 \ndyld private memory                256K        1 \nmapped file                      477.3M       98 \nshared memory                      912K       16 \n===========                     =======  ======= \nTOTAL                              8.3G     3654 \nTOTAL, minus reserved VM space     2.9G     3654 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "NSOperationQueue 0x139633eb0 (QOS: UNSPECIFIED)"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,2, BootROM 8419.80.7, proc 10:8:2 processors, 32 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Display: M241FJ, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Nov 30 2022 02:17:16 version 20.10.965.13.8.7.131 FWID 01-1251c18d
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: AX88x72A, Ethernet, en7
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by cycle2zhou** [comment]
Yes, I'm using git to push my notes regularly @gingerbeardman

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/6.2.2/FSNotes_6.2.2.zip

**Comment by cycle2zhou** [comment]
6.2.2 It has been used for a few days and there is no crash for the time being. I will give you feedback when it happens again

**Comment by tjmcewan** [comment]
My FSNotes (6.7.0) was hanging repeatedly.  I installed previous versions back to 6.6.2 until I found a working version.  Still a little confused, but it seems the hangs were caused by iCloud offloading most of my notes when my drive space got low.  Now that I've cleared some space & set them all to local (unfort. seemingly can't persist this) it is working fine.

**Comment by gingerbeardman** [comment]
Could this be the recent change in Sonoma 14.4?
