### ISSUE TITLE
Soulver shouldn't be evaluated in code blocks

### ISSUE THREAD

**Issue by ambv** [glushchenko/fsnotes#1497]
### Description

Soulver looks great as a feature, I like it a lot!

However, I agree with the original reporter of #1442 that this feature should be omitted in code blocks. Code blocks are special, they literally mean "leave the content inside alone because it's got its own internal structure".

Braces are used very commonly in programming languages so this will trip people up who didn't see your tweet or the closed issue #1442.

Please reconsider and only parse Soulver outside of code blocks.

### To Reproduce

Type into a note:

<pre>
This is a JSON code snippet:

```json
{a: 1}
```
</pre>

Then press "Preview".

### Expected behavior

<img width="345" alt="Screen Shot 2023-03-08 at 11 23 27" src="https://user-images.githubusercontent.com/55281/223687940-fb00e243-0a7a-45b9-9ad9-844de3cbdea7.png">

## Actual behavior
<img width="341" alt="Screen Shot 2023-03-08 at 11 24 01" src="https://user-images.githubusercontent.com/55281/223688059-20b47423-f8bc-46d0-b1fb-e9d83964391f.png">

### FSNotes version

6.1.4

### macOS/iOS version

12.6.3

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.2.3

**Comment by MiracleXYZ** [comment]
I'm sorry but I am still experiencing this issue with version 6.3.0.

Before Preview:

<img width="724" alt="image" src="https://github.com/glushchenko/fsnotes/assets/30370926/3e8149aa-3273-480d-bb17-5f444611447b">

After Preview:

<img width="724" alt="image" src="https://github.com/glushchenko/fsnotes/assets/30370926/556521fd-15f5-421d-a4ee-c4e096f15f7d">

Version Info:

<img width="482" alt="image" src="https://github.com/glushchenko/fsnotes/assets/30370926/c782b927-e8e1-441d-98ff-c33556a20849">

**Comment by glushchenko** [comment]
Feel free to open when you have the steps to reproduce it
