### ISSUE TITLE
Syntax highlighting confused by periods

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#1499]
### Description

Emphasis and strong emphasis are not highlighted while editing if followed by a period, unless that is followed by a newline.

### To Reproduce

1. New Note
2. Type `*emphasis*` (will be highlighted correctly)
3. Type a `.` (no longer highlighted)
4. Hit return (highlighted again)

### Expected behavior

Highlighting of spans is not influenced by what follows.

### FSNotes version

6.1.4

### macOS/iOS version

macOS 13.2.1

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.4.1
