### ISSUE TITLE
News: FSNotes for macOS

### ISSUE THREAD

**Issue by glushchenko** [glushchenko/fsnotes#150]
Hi, guys!

At first big thanks @jeff-h for pull requests, @peavine, @gingerbeardman and other guys for bug reports.

I have some news for our community:

Last release stable enough to share with everyone. FSNotes for macOS now completely free in mac app store too.

Development does not stop, i will continue write code for make best macOS notes manager ever ;)

Cheers 🍺

**Comment by jeff-h** [comment]
Have to be honest, I'm unsure if this is good news! I'd rather hoped that the app store versions might have given you a little extra motivation to do your great work on an ongoing basis. Or at the very least enough to buy you a nice coffee or something every now and then :coffee: You've put a huge amount of time into this and I for one am super-grateful and thought the ability to "donate" through the app store was a neat idea. Can I ask what your motivations were in making it free?

**Comment by glushchenko** [comment]
1500 free copies distributed in MAS, now the app is again paid.

**Comment by gingerbeardman** [comment]
Great idea to get more users.
