### ISSUE TITLE
Cursor jumps to top of note when switching applications

### ISSUE THREAD

**Issue by dylanseeger** [glushchenko/fsnotes#1500]
### Description

When I'm editing the middle of a note and I click or CMD+Tab away from FSNotes, the editor view and my cursor jumps to the top of the note.

When "Restore cursor position" is enabled (which I have disabled due to other bugs), the editor still jumps to the top before returning to its previous position.

This sort of bug is extremely disorienting and makes referencing long notes cumbersome.

### To Reproduce

1. Select a note
2. Scroll down and type in the middle of the note
3. Switch to any other application, such as Finder or Safari
4. Switch back to FSNotes and notice cursor position

### FSNotes version

6.1.4 (559)

### macOS/iOS version

13.2.1

### Additional context

I have FSNotes set to Vertical layout, a la Notational Velocity.

**Comment by glushchenko** [comment]
Can not reproduce ...

https://user-images.githubusercontent.com/1089917/227652448-ff4bb693-e76e-414c-8f1b-8ee593c05385.mov

**Comment by dylanseeger** [comment]
@glushchenko You have to type new text before switching applications. This bug is consistent in my testing across multiple machines.

**Comment by gingerbeardman** [comment]
I can also not reproduce.

If possible, could you please make a screen recording with keyboard overlay (using [Keycastr](https://github.com/keycastr/keycastr), or [other](https://superuser.com/questions/407334/how-can-i-see-a-visual-overlay-of-shortcut-keys-ive-pressed))?

**Comment by dylanseeger** [comment]
See below for a screen capture. This happens when typing in any note and using CMD+Tab to switch applications.

https://user-images.githubusercontent.com/2807899/227779825-e4f01e20-f211-4454-8440-ee13b8bd515a.mov

**Comment by glushchenko** [comment]
Indeed, very strange behavior. I do not have it.

**Comment by dylanseeger** [comment]
Is your Mac on Ventura? The issue is present on my Intel iMac, M1 MacBook Air, and my wife's MacBook Air, all of which are running Ventura. I even tried setting up a new user with stock FSNotes settings and was able to immediately replicate this.

**Comment by gingerbeardman** [comment]
I'm still on Monterey, so I'll remove myself from this discussion.

**Comment by gingerbeardman** [comment]
OK! I can reproduce it on Monterey.

Happens in any layout (Top/Vertical or Side).

What I am seeing is the cursor position jumping to the middle of the window, which I guess on your small window seems a lot worse than on my long window.

- It only does it if I Cmd+Tab very soon after editing.
- If I wait a moment for the note to save/update it's position, and then Cmd+Tab it does not do it.

In this video I show:
1. reproduce/happens
2. wait, does not happen
3. reproduce/happens

https://user-images.githubusercontent.com/49612/228052311-a7fe8c5e-0414-43f7-b0f9-9813094470ac.mov

**Comment by glushchenko** [comment]
Finally, i reproduce it too!

**Comment by dylanseeger** [comment]
Excellent! This is the bug I run into the most frequently. Is there anything else I can do to help get it fixed?

**Comment by dylanseeger** [comment]
Thank you!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.2.3
