### ISSUE TITLE
Disabling "First line as title" doesn't work in 6.2.0

### ISSUE THREAD

**Issue by dylanseeger** [glushchenko/fsnotes#1503]
### Description

I have "First line as title" disabled, however in 6.2.0, the titles of all my notes are their first lines.

### To Reproduce

N/A

### FSNotes version

6.2.0

### macOS/iOS version

Ventura

**Comment by glushchenko** [comment]
Fixed, thank you!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.2.1

**Comment by dylanseeger** [comment]
Thank you!
