### ISSUE TITLE
Can't set External Editor to Visual Studio Code – problem with spaces in the name?

### ISSUE THREAD

**Issue by franciscolourenco** [glushchenko/fsnotes#1504]
### Description

I'm trying to use 'Visual Studio' Code as the external editor, but the settings get reverted to TextEdit after the preferences pane is closed. It works fine with other applications that don't contain spaces in the name.

### To Reproduce

1. Open to the Preferences pane
2. Set 'Open External Editor' to 'Visual Studio Code' 
3. Close the Preferences pane
4. Re-open the Preferences pane
5. Observe that the 'Open External Editor' configuration has been reverted to the previously configured value

### Expected behavior

'Visual Studio Code' should be accepts as a valid external editor value.

### FSNotes version

6.2.1 (565)

### macOS/iOS version

13.2.1 (22D68)

**Comment by glushchenko** [comment]
Works fine with Visual Studio Code for me.

**Comment by franciscolourenco** [comment]
@glushchenko you can't reproduce, but it doesn't mean that the bug doesn't exist :) 

Is your Visual Studio Code named like this? 
<img width="193" alt="image" src="https://user-images.githubusercontent.com/208149/229346077-2e0b082e-3531-4949-9859-df01dd7b626f.png">


I've re-installed FSNotes and still experiencing the same problem.

**Comment by glushchenko** [comment]
Please make preferences screen:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/1089917/229346176-563cc03c-6cdd-48c3-9f49-9e075f5219ef.png">

**Comment by franciscolourenco** [comment]
It works with other apps which don't have spaces in the name though.


https://user-images.githubusercontent.com/208149/229347142-dcd3ed0b-cd9b-486b-8f82-efef1616d59e.mp4

**Comment by glushchenko** [comment]
Did you press Return when you finished entering the field?

**Comment by franciscolourenco** [comment]
Didn't expect that to be necessary as it is normally not necessary, but it fixed the problem, thanks.

**Comment by glushchenko** [comment]
Auto saving was added by commit above, thank you for feedback.
