### ISSUE TITLE
Imported Folders & Notes Disappear after restart of FSNotes App

### ISSUE THREAD

**Issue by ruby-lorenze** [glushchenko/fsnotes#1505]
### Description

I have 100 + small RTF (and also plain text TXT) files exported from another notes application that is sun setting.
I can import them all successfully into a target folder - in fact anything it was over zealous in creating a folder for each an every note BUT it never the less worked well and looked good.
However after closing and reopening FSNotes I found that all the imported notes and the generated folders were no longer there? Completely disappeared. I re-imported the notes and tested it again by closing and reopening FSNotes - again after reopening all the imported notes and the generated folders were absent. 

### Expected behavior

I expect the notes to be preserved - there is no 'save feature in FSNotes so assume it should be writing continuously. 

### FSNotes version

Version 6.1.4 (560)

### macOS/iOS version

OSX 13.3 Ventura

**Comment by gingerbeardman** [comment]
Where is your default stoage set to in the app preferences?
And what is there if you go there manually?

If you create a new note and choose _File > Reveal in Finder_ what do you see there?
