### ISSUE TITLE
Sudden pop-up - Repostiry not found

### ISSUE THREAD

**Issue by IvanKostyuk** [glushchenko/fsnotes#1506]
### Description

It started to happen today. When I try to "save" (_Save Revision_ - ⌘ + S) the pop-up appears

![image](https://user-images.githubusercontent.com/17881160/229188414-10b596fb-1899-4450-8fe4-149b6b7a92e3.png)

I did not do any change in the Preferences nor restarted the application.

After I checked the Preferences I noticed, that the repository is located in an odd directory
![image](https://user-images.githubusercontent.com/17881160/229189055-767ed49d-ca79-458b-98d4-eb8d26c2bf41.png)
`$home/Library/Containers/co.fluder.FSNotes/Data/Library/Application Support/Repositories/f508 - Fsnotes.git/`

I suspect something went wrong and now it is wrong.

### To Reproduce

1. Edit a note
2. Press ⌘ + S

### Expected behavior

No issue.

### FSNotes version

Version 6.2.1 (565)

### macOS/iOS version

Version 13.2.1 (22D68)

### Additional context

What should be done as a workaround?

**Comment by glushchenko** [comment]
This means that repository is not exist. You should create it before by pressing Init/commit button:

<img width="162" alt="image" src="https://user-images.githubusercontent.com/1089917/229198198-eba5f8ea-bd5d-41b2-bfdf-a0c640b4764d.png">

**Comment by IvanKostyuk** [comment]
Does bellow picture mean it was created?
<img width="713" alt="image" src="https://user-images.githubusercontent.com/17881160/230222601-5c12b14b-9450-4193-91f1-c12cf7df1ca6.png">

It is really interesting. Today morning (I still automatically press ) it was failing, but it it works. You can see that the file `index` and the directory `objects` were updated today.

It kind of resolved itself.

**Comment by glushchenko** [comment]
It was fixed in parallel issue ;)
