### ISSUE TITLE
Replace iconography with SF Symbols

### ISSUE THREAD

**Issue by dylanseeger** [glushchenko/fsnotes#1509]
**Describe your feature request**
Changing the iconography in FSNotes to SF Symbols would provide a degree of polish and consistency with other system programs, improving usability and aesthetics for new and existing users.

The (rough) mockups below contain the following symbols from [Apple's library](https://developer.apple.com/sf-symbols/):
- **Main Window:** square.and.pencil, magnifyingglass, tray, note.text, archivebox, trash, folder, tag
- **Settings:** gearshape, sidebar.left, doc.plaintext, lock, arrow.triangle.pull, globe, slider.vertical.3

![2023-04-05 SF Symbols Proposal, Main - FSNotes](https://user-images.githubusercontent.com/2807899/230148046-33f5cea3-6136-48fe-8527-e6e3851c50ba.jpg)

![2023-04-05 SF Symbols Proposal, Settings - FSNotes](https://user-images.githubusercontent.com/2807899/230148080-c713f146-a00d-419f-bb6e-25cbdc16e756.jpg)

**Additional context**
N/A

**Comment by gingerbeardman** [comment]
I'd love to see this.

Another benefit is that any changes made to the symbols and macOS would come for free to FSNotes.

**Comment by glushchenko** [comment]
I like it :)

**Comment by gingerbeardman** [comment]
Thanks @dylanseeger for the thoughtful suggestions and excellent mockups!

**Comment by dylanseeger** [comment]
@glushchenko @gingerbeardman Glad to help!

**Comment by glushchenko** [comment]
<img width="1115" alt="image" src="https://github.com/glushchenko/fsnotes/assets/1089917/e447e019-c91a-41fb-9a2e-62221416c7dd">

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.4.0/FSNotes_6.4.0.zip

**Comment by foss-** [comment]
It seems the settings panal icons were updated. Are you still planning on also switching the left sidebar icons to SF Icons?

**Comment by glushchenko** [comment]
@foss- no
