### ISSUE TITLE
Update application icon?

### ISSUE THREAD

**Issue by dylanseeger** [glushchenko/fsnotes#1512]
**Describe your feature request**
With respect to the original designer, I took a shot at designing a new icon for FSNotes, previewed below.

If @glushchenko wants, I'll happily contribute it to the project. If not, glad to share with anyone who wants to use it themselves.

![2023-04-05 SF Symbols Proposal - FSNotes](https://user-images.githubusercontent.com/2807899/230214986-6e7f2a31-6e24-439e-81cb-d3538cf27720.png)

**Additional context**
N/A

**Comment by gingerbeardman** [comment]
I think this would be the third or fourth icon.

I think it would be in-keeping with the SF Symbols introduction.

The older icons are usually kept as options in the app for the more steadfast of users.

**Comment by glushchenko** [comment]
I've been thinking about an icon update for a long time, and I like this one. We can start by adding it to the iOS version update, which I'm doing now.

**Comment by dylanseeger** [comment]
Excellent! I’ll prepare the high-resolution assets and post them here shortly.

**Comment by dylanseeger** [comment]
Here you are!

[fsnotes-icon.zip](https://github.com/glushchenko/fsnotes/files/11165361/fsnotes-icon.zip)

**Comment by dylanseeger** [comment]
Here you are!

[updated-fsnotes-icon.zip](https://github.com/glushchenko/fsnotes/files/11170474/updated-fsnotes-icon.zip)

(Updated on 2023-04-06 to include files formatted specifically for Mac + iOS.)

**Comment by glushchenko** [comment]
Seems it looks good.

![image](https://user-images.githubusercontent.com/1089917/230694894-f7e46e55-d4dd-4a19-9a77-87411d712389.png)

May be you have idea how to do same with dark colors?

**Comment by dylanseeger** [comment]
Great! A dark variant should be relatively easy, I'll make it tomorrow.

**Comment by dylanseeger** [comment]
@glushchenko See below for updated icons, including bolder strokes, refined spacing, and a new dark variant:

[2023-04-08-fsnotes-icon.zip](https://github.com/glushchenko/fsnotes/files/11183292/2023-04-08-fsnotes-icon.zip)

![2023-04-08 Icon Proposal - FSNotes](https://user-images.githubusercontent.com/2807899/230721629-d3474bb5-c9c6-4f0b-aced-1641618c2475.png)

I'm not sure what your UI plans are for v6 on iOS, but let me know if you're open to feedback on this, as I have a handful of ideas that would help bring its interface closer in step with the polish of the Mac version.

**Comment by glushchenko** [comment]
No big changes to the user interface are planned, but any suggestions are welcome.

I can add you to the beta testers, then it will be clear what the state of development is.

**Comment by dylanseeger** [comment]
@glushchenko I haven't had a chance to mock anything up yet, but I intend to do so.

I find the genius of FSNotes on the Mac — and Notational Velocity, its forerunner — to be its implementation of the "search and create" field as the primary interface, particularly when the vertical layout is enabled. This modeless design is simple and intuitive, refreshingly fast, and wonderfully powerful, even when working with thousands of notes. There's simply nothing else like it.

The iOS version, in many ways, feels like a completely different program. Search is obfuscated — you can't even refine your query from the editor view! — and many controls are slow and finicky. Menus pop up in the wrong places, movement between multiple screens is required to perform common functions, iconography is inconsistent, and a dull blue is pervasive throughout.

All of this means that, while FSNotes is my most frequently used application on the Mac, I choose not to use it on iOS. For now...

Do you agree with this assessment?

**Comment by gingerbeardman** [comment]
I do, it's also why I do not use it on macOS currently.

**Comment by dylanseeger** [comment]
> I do, it's also why I do not use it on **macOS** currently.

I presume you meant iOS? 🙂

**Comment by glushchenko** [comment]
I use the iOS version as a place where I can quickly add information and later, on a Mac, sort and catalog the data.

The time budget for the development of the iOS version is limited, so there is as it is.

**Comment by dylanseeger** [comment]
Makes sense. Considering these reasonable constraints, I would prefer to see a sharp focus on the basics — speed and search — than on power features like Git integration on iOS.

I think positioning it as a distilled yet consistent companion to the Mac app would be a better experience for all and would set expectations accordingly for new users.

**Comment by glushchenko** [comment]
I really wanted the iOS version to keep up with macOS, so porting git was necessary, which I did.

Yes, I agree, it wasn't the best idea to spend so much time on it, but there's no point in discussing git anymore, the work on it is finished. 

If you have any ideas on how to improve the iOS version, maybe a new ticket should be created? 

I appreciate your ideas, thanks!

**Comment by dylanseeger** [comment]
Understood, I didn’t mean to disparage your hard work on Git integration. Any time you spend on this project is sincerely appreciated.

I’ll open a new ticket once I have time to outline practical, actionable suggestions for improvement.

**Comment by dylanseeger** [comment]
@glushchenko Do you need anything else from me in order to add this to the Mac app?

**Comment by glushchenko** [comment]
No, it's OK, I'll update the icon on the mac along with the iOS update coming out.
