### ISSUE TITLE
Attachments in file level

### ISSUE THREAD

**Issue by schwantuschke** [glushchenko/fsnotes#1516]
### Description

When I drag an image into a note, a new folder is created in the same folder where it is located. It simply has the name "i". In an older version, a folder was created for this, which was called e.g. ".attachments.199151". This folder was then directly invisible on file level. Is this a bug?

### To Reproduce

1. Drag a file (link .png) in a new note
2. See where the file is located at the file level.

### FSNotes version

6.2.4

### macOS/iOS version

macOS 13.3.1

**Comment by schwantuschke** [comment]
Still relevant

**Comment by schwantuschke** [comment]
Is there any news on this yet?

**Comment by glushchenko** [comment]
No any news, and this not planned. FSNotes has never created attachments like .attachments.199151.

**Comment by schwantuschke** [comment]
@glushchenko FSnotes creates folders that are simply named _i_ and inside them are the images. Is this behavior intentional?

**Comment by glushchenko** [comment]
Yes, it is by design.

**Comment by schwantuschke** [comment]
Ahh ok. Then it would probably be good to be able to give the folder name yourself.

**Comment by glushchenko** [comment]
> Ahh ok. Then it would probably be good to be able to give the folder name yourself.

Did you try textbundle container?

**Comment by schwantuschke** [comment]
No. I use one md-files without container.
