### ISSUE TITLE
Unordered list items indented more than 2 levels are rendered as code block if "Highlight indented code blocks" is enabled

### ISSUE THREAD

**Issue by tjuerge** [glushchenko/fsnotes#1519]
### Description

If in editor preferences "Highlight indented code blocks" is enabled then indenting an unordered list item more than 2 levels creates a code block.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/2626998/235370004-f303b843-9d4a-41b9-bc4d-a94674f7bd9b.png">
<img width="601" alt="image" src="https://user-images.githubusercontent.com/2626998/235369987-8106b6b0-67bd-4d81-b7f8-dcba2a54cc14.png">

This effect is discussed in #125.

### To Reproduce

1. In editor preferences disable "Highlight indented code blocks" 
2. Create an unordered list with 3 level
3. In editor preferences enable "Highlight indented code blocks"

### Expected behavior

All list items of unordered lists are rendered as normal text despite of the editor setting "Highlight indented code blocks".

### FSNotes version

6.2.4 (570)

### macOS/iOS version

Ventura 13.2.1

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.4.1

**Comment by tjuerge** [comment]
Thanks for taking care of this - works as expected 👍
