### ISSUE TITLE
Feature Request: Auto-closing pairs

### ISSUE THREAD

**Issue by owensource** [glushchenko/fsnotes#152]
Loving the app - this is honestly the closest thing to what I've been looking for tirelessly for a long time.

It's missing one thing, for me, though.  If it had auto-pairs, it would supersede most of my other note-taking applications.

By auto-pairs, I'm referring to: when type, ' " { ( all automatically add their closing counterpart.  I.e: when ( is typed, you get ( | ) with the cursor in the middle.

I'm not sure how labor-intensive this would be, but it turn this into the perfect app for me.  Thank you for your development and for making this free.

As a side note, another user noted that folding headers would be awesome.  I agree. Thanks

**Comment by jeff-h** [comment]
Pretty happy with that :) You can also select some text, and press one of the opening bracket characters. Instead of replacing the selected text, it will wrap it in an opening and closing bracket.

**Comment by owensource** [comment]
Awesome addition - I didn't mention that, but that was also part of what I was referring to (with the wrapping of brackets around selected text).  Thanks! Now hoping it gets merged!

**Comment by peavine** [comment]
The auto-close-bracket feature is great, but including the apostrophe (single quote) makes things difficult when using FSNotes for casual word processing. For example, just type the words I'm, don't, won't and peavine's to see what I mean. 

I guess this issue varies, depending on how a person uses FSNotes. I really like the auto-bracket feature but have to turn it off when word processing and, FWIW, would prefer that the apostrophe be excluded from auto-bracket.

Thanks.

**Comment by jeff-h** [comment]
Lol, man that's bad. Thanks for the heads-up! PR #166 fixes this.

**Comment by glushchenko** [comment]
Fixed in 1.5.2

**Comment by peavine** [comment]
Thanks jeff-h. I installed 1.5.2 and this feature works great.
