### ISSUE TITLE
Notes in encrypted folder vanishing

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1520]
### Description

I made my first encrypted folder recently, but the notes I add to it keep disappearing.

Also, while writing this issue, I noticed that when I try to decrypt the folder, application crashes

### To Reproduce

1. Create a new folder
2. Encrypt the folder
3. Add a note
4. Close the app
5. Open the app, unlock the encrypted folder
6. File is gone. There is just an empty file that has the same name as the folder itself
7. Lock the folder back up, then try the decrypt option. App crashes

### Expected behavior

Notes should not vanish; app should not crash

### FSNotes version

6.2.4 (570)

### macOS/iOS version

13.3.1

**Comment by glushchenko** [comment]
Hi, i found it on iOS, so on mac it fixed too.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.2.5r/FSNotes_6.2.5.zip

**Comment by nth-chile** [comment]
Tests well for me! Shall I close the issue?

**Comment by nth-chile** [comment]
Actually, I just hit an issue again. I have a few files in an encrypted folder. When I lock and unlock, the most recent one becomes empty and becomes the name of the folder.

**Comment by glushchenko** [comment]
Can not reproduce it, can you attach a crash report?

**Comment by nth-chile** [comment]
I didn't repro the crash, I just meant the file still disappears

**Comment by glushchenko** [comment]
I found problem, fixed. Release soon.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.3.0/FSNotes_6.3.0.zip
