### ISSUE TITLE
Do not create empty git commits if there are no changes

### ISSUE THREAD

**Issue by Flameborn** [glushchenko/fsnotes#1522]
### Description

It there are no changes in any of the created documents, FSNotes creates empty git commits if Git support is enabled and notes are pushed to a custom repository.

### To Reproduce

1. Go to 'Preferences -> Git'
2. Make sure *Commit/Push every* is selected.

### Expected behavior

FSNotes should create commits if there are changed notes only, i.e. disallow empty commits.

### FSNotes version

6.2.4 (570)

### macOS/iOS version

MacOS 12.6.5 (untested on iOS)

**Comment by glushchenko** [comment]
I think it fixed now

**Comment by Flameborn** [comment]
Yes, it looks like it is. Thank you very much!

**Comment by glushchenko** [comment]
Please try this https://github.com/glushchenko/fsnotes/releases/download/6.2.5r/FSNotes_6.2.5.zip

**Comment by Flameborn** [comment]
Just like the PR, the release works as well. No empty commits or pushes were made.

Thank you very much for the quick fix!
