### ISSUE TITLE
Note content deleted without undo option.

### ISSUE THREAD

**Issue by VladyslavDmitriiev** [glushchenko/fsnotes#1523]
### Description

Note content is deleted without undo option after following the link to a file and pressing `cmd + [` and `cmd + /` 

### To Reproduce

1. Open a note that has a link to another note -> [[filename]]
2. Click on the link
3. Press `cmd + [`
4. Press `cmd + /`

Actual result:
Opened note content was deleted without undo option.

### Expected behavior

The note content should not be deleted.

### FSNotes version

Version 6.2.4 (570)

### macOS/iOS version

13.2.1 (22D68)

**Comment by tewe** [comment]
I cannot reproduce this.

⌘ [ as in Shift Left and ⌘ / as in Toggle Preview?

**Comment by glushchenko** [comment]
> I cannot reproduce this.

me too

**Comment by VladyslavDmitriiev** [comment]
Sorry, it was `]` (Shift Right)  not `[` (Shift Left)

    Open a note that has a link to another note -> [[filename]]
    Click on the link
    Important: The note opened in a preview mode
    Press cmd + ]
    Press cmd + /

**Comment by gingerbeardman** [comment]
Are you able to post a screen recording?

**Comment by glushchenko** [comment]
Reproduced and fixed. Thanks @VladyslavDmitriiev, nice catch!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.3.2
