### ISSUE TITLE
SSH Error: The operation couldn’t be completed. (Shout.SSHError error 1.)

### ISSUE THREAD

**Issue by uPagge** [glushchenko/fsnotes#1526]
### Description

I checked that I can log in to the server through the terminal from the created key. That I can create folders and files on behalf of this user in the folder specified for fsnotes.

### To Reproduce

1. Go to Preferences > Web
2. Fill in your SSH credentials. My key is RSA 3072. With another type of key the problems are reproduced.
3. Press the "Upload and test initial data" button
4. See the error

### FSNotes version

6.2.6 (572)

### macOS/iOS version

13.4 (22F66)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.4.1
