### ISSUE TITLE
Note content is not displayed or has been lost

### ISSUE THREAD

**Issue by maximzasorin** [glushchenko/fsnotes#1529]
### Description

I had an encrypted note with several screens of text and some pictures. I used this note as a diary. When I inserted a new photo into the note, the content of the entire note disappeared and I can't undo it.

If I look at the note file, it's taking up some space:
```
-rw-r--r--@  1 maxim  staff  4960946 May 28 12:14 Дневник.etp
```

I got this behavior once before on one of the previous versions of FSNotes (it was some of version 6.1.*), I had to restore from backup. Yesterday I updated FSNotes to version 6.2.6 and got this behavior again.

<img width="310" alt="2" src="https://github.com/glushchenko/fsnotes/assets/13367689/30799433-5a23-4f83-a68b-fbaadb244a34">

### To Reproduce

1. Run FSNotes
2. Unlock the encrypted note.
3. Start editing the note, put the cursor on a new line and paste a picture using Command+V
4. Note content is no longer displayed or is lost

### FSNotes version

6.2.6

### macOS/iOS version

macOS 10.15.7

**Comment by glushchenko** [comment]
Did you try last build? 6.3.0 its dupe #1520
