### ISSUE TITLE
Extra system alert when unlocking encrypted folder

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1534]
### Description

When you unlock a folder, first you get a system alert that looks like this:

<img width="259" alt="Screenshot 2023-05-30 at 12 29 27 AM" src="https://github.com/glushchenko/fsnotes/assets/22358233/3f1bf2ce-99c1-4d3e-a9cb-9c91d8ef779e">

You can authenticate if you want, or you can just click cancel. In either case, it goes to the second alert that asks you for your FSNotes master password

<img width="322" alt="Screenshot 2023-05-30 at 12 40 00 AM" src="https://github.com/glushchenko/fsnotes/assets/22358233/a95f2a09-1caf-4920-afe9-3a7e1854ca2a">

### To Reproduce

1. Unlock an encrypted folder
2. When you see an alert that says "FSNotes is trying to access secure data", click cancel.
3. On the second alert, enter your FSNotes password
4. Folder unlocks

### Expected behavior

I think there should only be one alert, but I don't know which one. The question is, do we want to unlock encrypted notes with TouchID/Mac password, or do we want a password that is specific to the app?

On one hand, TouchID is nice. On the other hand, anyone who knows your mac password could theoretically access your notes.

### FSNotes version

6.3.0

### macOS/iOS version

Ventura 13.3.1 (a)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.4.1

**Comment by nth-chile** [comment]
@glushchenko When you scan your finger, your Mac's login password gets passed to RNCryptor instead of the folder password. I found a workaround too

1. Go to Keychain Access and delete FSNotesApp from all keychains
2. In Xcode, clean build folder
3. Launch app and create a new folder called test. When it asks you for fingerprint, scan your finger. Then it should say "Enter an encryption password". Enter "test"
4. Try to unlock the folder. First, it will ask for fingerprint. But fingerprint won't work, and then it will ask you to enter a password. Enter "test" to unlock
5. Go to FSNotes Settings > security > change master password. For the current password, type in the Mac's login password. For the new password, type "test"
6. Now you can unlock the folder with fingerprint

**Comment by glushchenko** [comment]
Released: https://github.com/glushchenko/fsnotes/releases/download/6.9.2/FSNotes_6.9.2.zip
