### ISSUE TITLE
[iOS] Crash upon Share

### ISSUE THREAD

**Issue by hasantahir** [glushchenko/fsnotes#1536]
### Description

The app (v 6.0.1 build 263) crashes as soon as I try to share a note. 

### To Reproduce

1. Long Press a note to invoke the menu
2. Tap the `Share` button
3. The app crashes

### FSNotes version

6.0.1 build 263

### macOS/iOS version

IpadOS 16.5

**Comment by glushchenko** [comment]
Reproduced and fixed, thank you for detailed bug report.

**Comment by glushchenko** [comment]
6.0.2 released in the AppStore

**Comment by hasantahir** [comment]
Thank you very much for your swift response :-).
