### ISSUE TITLE
URL Scheme search is cleared when clicking note in list

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1537]
### Description

URL Scheme search is cleared when clicking note in list, which is unexpected and wrong

### To Reproduce

1. Open FSNotes using URL scheme `fsnotes://find/{query}`
2. Notice that the search has executed and the results are correct
3. Click in the first result in the list
4. Search is cleared and an different note is selected!

### Expected behavior

- search should not clear when clicking a note in the search results
- correct note should be selected

### FSNotes version

- 6.3.0

### macOS/iOS version

- macOS

### Additional context

- workaround is to click into the search field to deselect the search query, which leaves the search intact, then click on an item of the results list

**Comment by tewe** [comment]
This also affects double square bracket `[[links]]`.

**Comment by gingerbeardman** [comment]
> This also affects double square bracket `[[links]]`.

@tewe do you mind explaining how it affects it?

**Comment by tewe** [comment]
If you click a `[[link]]` for which no exact match exists, it starts a search. When you click one of the results, they all disappear. Just like you described. IIRC double square brackets actually use the URL scheme internally, so this is to be expected.

**Comment by gingerbeardman** [comment]
Thanks!

**Comment by glushchenko** [comment]
Guys, please test it out. If it doesn't work, I'll try to fix it after holiday (need a couple of weeks to recharge).

https://github.com/glushchenko/fsnotes/releases/download/6.3.3/FSNotes_6.3.3.zip

**Comment by tewe** [comment]
Works for me. Thanks!
