### ISSUE TITLE
Can't save revision in git after upgrading to 6.3.0

### ISSUE THREAD

**Issue by michaelrrrrrr** [glushchenko/fsnotes#1538]
### Description

After upgrading to 6.3.0, any edits will not be saved by Ctrl+S, while an error message is prompted: 
The operation couldn’t be completed. (FSNotes.GitError error 7.)

I have never changed the default settings of git. Everything in Preference>Git remained intact.

### To Reproduce

1. Do any edits
2. Click Ctrl+S
3. An error prompt will be shown immediately

### FSNotes version

6.3.0

### macOS/iOS version

macOS Monterey 12.6.3

**Comment by glushchenko** [comment]
Looks like a hotfix is required, thank you.

**Comment by michaelrrrrrr** [comment]
> Looks like a hotfix is required, thank you.

No worries.

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/6.3.2/FSNotes_6.3.2.zip

And post here a new error message.

**Comment by michaelrrrrrr** [comment]
> Please try https://github.com/glushchenko/fsnotes/releases/download/6.3.2/FSNotes_6.3.2.zip
> 
> And post here a new error message.

I already updated the app to 6.3.2 via App Store. 

Now the prompt message is changed to 
"Unable to save index -14 the index is locked; this might be due to a concurrent or crashed process“.

**Comment by michaelrrrrrr** [comment]
Did nothing after receiving the last prompt message, but a new message came up when I clicked 'Ctrl+S' as usual.

`Unable to open repository, url: file:///Users/michaelren/Library/Containers/co.fluder.FSNotes/Data/Library/Application%20Support/Repositories/b1ae%20-%20Changelogs.git -3 failed to resolve path '/Users/michaelren/Library/Containers/co.fluder.FSNotes/Data/Library/Application Support/Repositories/b1ae - Changelogs.git': No such file or directory`

**Comment by glushchenko** [comment]
This means there is no repository in the specified path, you can create a new one or put the old one.

**Comment by michaelrrrrrr** [comment]
> This means there is no repository in the specified path, you can create a new one or put the old one.

I found some auto-generated git repos under that path, and they are FSNotes.git, Trash.git, Notes.git and two Archive.git repos. 

The "Changelogs" of the missing Changelogs.git in the prompt message refers to a folder, which I created in the FSNote app. I've seen none of the folders I created in the app had a corresponding git repo under the path. And I have no idea how to create a git repo refering to the folder.

Plus, I found there was always a similar error msg if I tried to save revision (Ctrl+S) in other folder of the app. I'm wondering if "save revision" is a proper way to save/sync my edits to the iCloud/some server/local store path?

I am sure my edits would be synced across all my devices, even if I couldn't "save revision". I guess this is due to the iCloud sync.

**Comment by pessinafederico** [comment]
Hello Michael, let me know if you have found a solution, I have the same issue

**Comment by PeterGumball** [comment]
Have the same problem, see (https://github.com/glushchenko/fsnotes/issues/1544) 

Nothing works for me, even when I remove the `Repositories` folder and init a new for project/global. I always get the same error.

I'm not creating a repository for now and use FSNotes without git now.

**Comment by glushchenko** [comment]
@PeterGumball @pessinafederico @michaelrrrrrr please try this build https://github.com/glushchenko/fsnotes/releases/download/6.3.3/FSNotes_6.3.3.zip

**Comment by PeterGumball** [comment]
@glushchenko 

Great, that works for me. Now I only get the message that there are no new files if I don't change anything and press `⌘ S`, but I can live with that. It is in my developer head that I always have to press `⌘ S`. 

Thanks for your quick help.

**Comment by glushchenko** [comment]
@PeterGumball agree, this is a temporary solution, I will remove this nag in the next releases, now there is no time. Thank you!

**Comment by michaelrrrrrr** [comment]
> @PeterGumball @pessinafederico @michaelrrrrrr please try this build https://github.com/glushchenko/fsnotes/releases/download/6.3.3/FSNotes_6.3.3.zip

![image](https://github.com/glushchenko/fsnotes/assets/7134939/ba46e351-c4c8-4517-8810-e571364047ff)

ouch
I drag the new app into the Application folder, replace the old one with new app, and all my notes are gone...

**Comment by glushchenko** [comment]
@michaelrrrrrr github version dont use icloud by default, you should select storage in settings manually.

**Comment by michaelrrrrrr** [comment]
@glushchenko All good now. I remove the original git settings in the Preferences and initialize a new one. Git works fine then. Thanks for the help.

@pessinafederico Try the new app published by @glushchenko. Everything works fine now.

**Comment by pessinafederico** [comment]
Thank you! Have a good one Sent from my iPhoneOn 10 Jun 2023, at 13:51, glushchenko ***@***.***> wrote:﻿
@michaelrrrrrr github version dont use icloud by default, you should select storage in settings manually.
