### ISSUE TITLE
[TODO] Addressing issues raised in App Store reviews

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#154]
I used this site to show all reviews:
https://fnd.io/#/us/mac-app/1277179284-fsnotes-by-oleksandr-glushchenko

You can respond to them through _iTunes Connect Dashboard_: _App Name_ –> _Activity_ –> _Ratings and Reviews_

It would be worth responding to any that have been solved, and any that result in new issues being created.

**Comment by glushchenko** [comment]
I answer periodically

**Comment by gingerbeardman** [comment]
I think we should do this again before or at V3
