### ISSUE TITLE
crash on mac

### ISSUE THREAD

**Issue by JonathanMair** [glushchenko/fsnotes#1540]
### Description

Hi — I love this app and used to use it frequently. I haven't for at least a couple of years because of a change of workflow but would like to begin using it again. However, when I tried to open it on my Mac it crashed straight away. I updated using the App Store and it does the same. Any tips for getting it working?

MB Pro 14" 2021 M1 Pro
16 GB
Ventura 13.4

Thanks!

### To Reproduce

1. try to open the app!

### FSNotes version

6.3.2

### macOS/iOS version

macOS 13.4

**Comment by glushchenko** [comment]
I have two options:

1) You can provide crash report
2) You can reset the settings https://github.com/glushchenko/fsnotes/wiki/Preferences-location

**Comment by JonathanMair** [comment]
Excellent, thanks. (2) worked for me.
