### ISSUE TITLE
Git error when saving 

### ISSUE THREAD

**Issue by PeterGumball** [glushchenko/fsnotes#1544]
### Description

When I modify an note or create a new note, I get the following error:

<img width="298" alt="Bildschirmfoto 2023-06-10 um 11 11 28" src="https://github.com/glushchenko/fsnotes/assets/324176/acd5baf1-5c5f-42fe-9cdf-45c946de2442">

This happens since version 6.3.0. With version 6.2.6 it works fine.

When I look in the folder `/Users/peter/Library/Containers/co.fluder.FSNotes/Data/Library/Application Support/Repositories` there are two subdirectories `ca39 - Documents.git` and `tmp`. 

I never changed any settings for git.

### To Reproduce

1. Create a new note or modify an existing note
2. Save Revision ⌘S

### FSNotes version

6.3.3

### macOS/iOS version

macOS Monterey 12.6.6

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/issues/1538
