### ISSUE TITLE
Creating a check box, going to preview and then going back to edit leaves the check box there

### ISSUE THREAD

**Issue by apastuszak** [glushchenko/fsnotes#1546]
### Description

I'm not sure if this is "as designed" behavior, or a bug.

If I am in the editor and I make a check box by typing `- [ ]`, the screen displays `- [ ]`. If I type ⌘+/ to go into preview, this gets converted to a check box. But when I turn off preview, the checkbox remains.

![image](https://github.com/glushchenko/fsnotes/assets/3401054/8153830a-b110-4cae-a80d-cc308695f8f0)

### To Reproduce

1. Create a check box by typing `- [ ]` followed by some text
2. Type ⌘+/ to go into preview
3. Type ⌘+/ to get out of preview
4. Check box stays and does not revert to `- [ ]`

### Expected behavior

I think it should revert back to `- [ ]`

### FSNotes version

6.3.2

### macOS/iOS version

MacOS 13.4

**Comment by apastuszak** [comment]
Слава Україні!

**Comment by glushchenko** [comment]
This is not a bug
