### ISSUE TITLE
FS Notes New Update Crashes on launch on iphone 

### ISSUE THREAD

**Issue by ruby-lorenze** [glushchenko/fsnotes#1548]
### Description

So the recent release with the updated App icon ... works fine on my mac but on my iphone 11 pro (128GB) IOS 16.5 it fails almost immediately on launching -- the app con expands to fill the screen and half second later its gone 

### To Reproduce

1. Launch the App. either by [1] search for the name until it appears and press the app icon [2[ pressing the app icon @ its  location on the hime screen.

### Expected behavior

i would it to open so I could read and edit text

### FSNotes version

Version 6.3.3 (578) on Mac . Can't findVersion on iOS app

### macOS/iOS version

Ventura Beta 3 | IOS 16.5

### Additional context

No its very simple but nothing about about debugging console logs for kernel panics etc that I would do on the mac. IOS I know very little.

**Comment by glushchenko** [comment]
It works fine for me, as it does for many other people. I need a crash report.

**Comment by glushchenko** [comment]
Any news with crash report?

**Comment by glushchenko** [comment]
Fixed in FSNotes 6.0.4
