### ISSUE TITLE
Appearance System (dark/light) is not working as expected

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1551]
### Description

Appearance System (dark/light) is not working as expected

### To Reproduce

1. Set Preferences > Advanced > Appearance = System 
2. Wait for dark mode to activate or toggle it manually
3. FSNotes stays white

### Expected behavior

- FSNotes should go dark automatically

### FSNotes version

- 6.3.3

### macOS/iOS version

- 12.6.6

### Additional context

- manually setting Appearance to be light/dark works as expected
- but it requires the app to restart

- Even starting the app whilst dark mode is active and Appearance is set to System does not work, the app stays white

**Comment by glushchenko** [comment]
Honestly, Matt, I don't know how to reproduce this.

**Comment by gingerbeardman** [comment]
Trying it now, and it is working OK

🤪

**Comment by glushchenko** [comment]
Good news, thanks! :)
