### ISSUE TITLE
Note scrolls up and down of its own volition

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1552]
### Description

During editing and repositioning of the  cursor the note scrolls up and down with as mind of its own. 

### To Reproduce

1. Edit a long note
2. Reposition the cursor
3. Type new text
4. cursor disappears off screen as document scrolls

### Expected behavior

- cursor should stay on screen
- note should not scroll  automatically

### FSNotes version

- 6.0.2

### macOS/iOS version

- iOS 16.5

### Screen recordings

Typing backspace

https://github.com/glushchenko/fsnotes/assets/49612/7bc57b01-edf1-4154-85ae-bafabc15a062

Dismissing lookup

https://github.com/glushchenko/fsnotes/assets/49612/4afd1917-5776-455a-a608-f609d0f0cf55

**Comment by aerbil313** [comment]
Same issue happens to me. If it’s of interest, it happened in the official iOS Notes app in iOS15 too, with especially long notes. Seems like a memory issue but idk.

**Comment by rayanamal** [comment]
Hello? iOS18 Public Beta, latest FSFile. Issue persists. The app is unacceptably frustrating since years due to this one bug. At this point I started considering even  using official Notes app even though it’s lock-in with no import or export.

**Comment by glushchenko** [comment]
@rayanamal sorry got this, but i think it's fixed by commit above.

**Comment by glushchenko** [comment]
@rayanamal check FSNotes  6.6.2 from App Store.
