### ISSUE TITLE
Pandoc integration

### ISSUE THREAD

**Issue by apastuszak** [glushchenko/fsnotes#1555]
**Describe your feature request**
I would like to be able to export a note in a format I can distribute to less technical people in a format other than Markdown.

**Additional context**
Though Markdown is a great format for the technically savvy people, trying to share a note with someone less technical, such as my wife is not always easy.  I usually go to the zsh prompt and use pandoc to convery to PDF, HTML, RTF or ODF.

It would be nice if fsnotes detected it pandoc was installed and offered an right-click export option and let you pick which format you want. Then it just passes the command to pandoc and the file is converted.

**Comment by gingerbeardman** [comment]
Current options:
- File > Create web page (hosted at https://p.fsnot.es for easy sharing)
- Preview > Copy HTML (up to you what you do with it)

Do either of these fit your use case?

**Comment by gingerbeardman** [comment]
Another option could be to use a system-wide macOS Service to convert your Markdown to whatever.

I previously created one: 

- https://github.com/glushchenko/fsnotes/issues/1265#issuecomment-998919987

**Comment by apastuszak** [comment]
I installed the docx service you created. How do I get it to work?

In my perfect use case, I would like to get my note in a format that I can easily paste it into the body of an email or Apple Notes.

Is that web page temporary? I don't want to leave my notes as an open URL someone else can open? Can I possibly self-host something like that?

**Comment by gingerbeardman** [comment]
> I installed the docx service you created. How do I get it to work?

That one I believe worked from Finder, you would enable it, then right click or press a hotkey with a markdown file selected to produce a docx alongside it. But my intention was not to get you to use that particular solution, but rather raise awareness of alternative solutions to your problem.

If all you want is something to cut and paste that isn't Markdown then the solution is easy: use FSNotes Preview!

- FSNotes > View > Toggle Preview > Select All > Edit > Copy (or Cmd+C)

This will give you rich text on the clipboard. You can paste into any app that supports Rich Text and if the app doesn't macOS clipboard is clever enough to paste plain text instead.
