### ISSUE TITLE
No more editor?

### ISSUE THREAD

**Issue by igr** [glushchenko/fsnotes#1556]
### Description

After clicking on `Esc` my editors are gone.

It is confusing when the notes list is missing.

### To Reproduce

I am not sure what I did, I believe I clicked just `Esc`, and this happened:

![CleanShot 2023-06-20 at 18 28 42](https://github.com/glushchenko/fsnotes/assets/2280001/1ec93f4e-2483-476d-a649-bb48f260e4b5)

### FSNotes version

Version 6.3.3 (578)

### macOS/iOS version

latest

**Comment by gingerbeardman** [comment]
ESC put the focus on the search field in the notes list, but you have the notes list hidden.

So, Cmd+Shift+B to show Notes list and then you can select a note.
