### ISSUE TITLE
Note list is not properly hidden

### ISSUE THREAD

**Issue by igr** [glushchenko/fsnotes#1557]
### Description

When there are more messages and the note list is hidden, it is still visible:

![CleanShot 2023-06-20 at 18 32 42](https://github.com/glushchenko/fsnotes/assets/2280001/35193baa-f015-40c6-b271-f7371fcfa07d)

### To Reproduce

1. Add enough notes so the scroll bar appears
2. hide the notes, hide the panel

### FSNotes version

Version 6.3.3 (578)

### macOS/iOS version

latest

**Comment by glushchenko** [comment]
There's nothing to fix, it's your problem.

![image](https://github.com/glushchenko/fsnotes/assets/1089917/d16c528e-5f15-44af-a412-2e1ccdee1b2a)
