### ISSUE TITLE
Bold does not get bold (same for italic)

### ISSUE THREAD

**Issue by igr** [glushchenko/fsnotes#1558]
### Description

The following example:

```
**Development approach**:
```

does not get bold:

![CleanShot 2023-06-21 at 08 12 35](https://github.com/glushchenko/fsnotes/assets/2280001/c6b5faa5-9501-43a4-8b46-dcd9d764a03e)

but this works (space added before the `:`):

```
**Development approach** :
```

![CleanShot 2023-06-21 at 08 15 02](https://github.com/glushchenko/fsnotes/assets/2280001/3c4010f4-6289-4d04-80d1-bad8f54ea52b)

### To Reproduce

Type `**foo**: hello`

### Expected behavior

UI should make text bold (or italic)

### FSNotes version

Version 6.3.3 (578)

### macOS/iOS version

latest

**Comment by gingerbeardman** [comment]
Markdown is handled by a library, Markdown.swift which uses libcmark_gfm which is the stringent Common Mark spec.

You can try it here: https://spec.commonmark.org/dingus/

And if the problem still exists it will be because of Common Mark.

**Comment by igr** [comment]
@gingerbeardman It works on the dingus example:

![CleanShot 2023-06-21 at 23 50 16](https://github.com/glushchenko/fsnotes/assets/2280001/52304fd9-1551-4bd8-abf5-d19587d1531d)

**Comment by gingerbeardman** [comment]
Great! Then over to @glushchenko when he returns

**Comment by glushchenko** [comment]
@gingerbeardman exactly :)
@igr thank you for report, fixed.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.4.0/FSNotes_6.4.0.zip
