### ISSUE TITLE
[BUG] Main window resized to dimensions and position of Preferences window

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#156]
**Steps to reproduce**  
1. Open _FSNotes_
2. <kbd>cmd</kbd>+<kbd>,</kbd> to open Preferences (do not close!)
3. Press <kbd>shift</kbd>+<kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>L</kbd> (default shortcut to hide _FSNotes_)
4. Press <kbd>shift</kbd>+<kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>L</kbd> (default shortcut to show _FSNotes_)
5. Quit _FSNotes_
6. Launch _FSNotes_

**Expected**  
Main window should be size it was before _FSNotes_ was quit

**Actual**  
The Main window is the size of the _Preferences_ window!

**Comment by jeff-h** [comment]
Ah, you've replicated this! I get it every now and then but haven't known exactly what steps reproduce it. I thought it might have been the "Autosave" field (Interface Builder > Attributes > Autosave) but no, these two windows are set up correctly there.

**Comment by gingerbeardman** [comment]
I did it by accident when playing with the "Search shortcut" oddness. Phew!

**Comment by glushchenko** [comment]
Tried on 1.5.6, can not reproduce :(

**Comment by glushchenko** [comment]
Сould record a video?

**Comment by gingerbeardman** [comment]
I have simplified the steps to reproduce.

Video: https://youtu.be/e0xDgXbydbg

**Comment by glushchenko** [comment]
Shit, i don know how to reproduce it :(

https://f001.backblazeb2.com/file/og-files/Screen-Recording-2018-04-22-11-03-11.mp4

**Comment by jeff-h** [comment]
Very odd that this doesn't reproduce for you. I just tried it and the "Steps to reproduce" in the first comment do replicate the issue for me.

**Comment by jeff-h** [comment]
I've been meaning to pitch the idea of implement [MASPreferences](https://github.com/shpakovski/MASPreferences) for the prefs window — perhaps doing so would bring the double-benefit of squashing this weird issue.

**Comment by glushchenko** [comment]
Tried in 10.13.4 and new account.

**Comment by gingerbeardman** [comment]
Still happening for me.

**Comment by glushchenko** [comment]
I think that's fixed already
