### ISSUE TITLE
Multiple versions of a note automatically generated 

### ISSUE THREAD

**Issue by vastlander** [glushchenko/fsnotes#1560]
When I'm creating and editing a note in my folder, multiple versions of this note are always automatically generated, and I have to manually delete these versions every time. 

And when I created and edited a note in Inbox and moved it from Inbox to my folder, another note exactly the same with the one i created was automatically generated in the folder.

Is this a bug?

Platform: iOS 16.5.1
FSNotes Version: 6.0.3 Build 265

**Comment by bluebird2046** [comment]
I have the same issue. It happens frequently when I use both my MacBook and iPhone.

**Comment by sorokin2718** [comment]
I have the same issue. Also use MacBook and iPhone clients but not simultaneously. Automatically created notes have `CONFLICT XXX` in the title. A new file generated every few seconds, so editing a note is tedious.

**Comment by glushchenko** [comment]
Conflicts occur when unsynchronized notes are edited on different devices. I can make an option to disable this, but then there is a chance that you will lose data.
