### ISSUE TITLE
Can iOS mobile support Simplified Chinese.

### ISSUE THREAD

**Issue by holton-jiang** [glushchenko/fsnotes#1564]
I have finished translating the simplified Chinese string, Can iOS mobile support Simplified Chinese.

iOS

**Comment by glushchenko** [comment]
Released in 6.0.4, thanks!

**Comment by glushchenko** [comment]
Available in TestFlight!

**Comment by holton-jiang** [comment]
> Available in TestFlight!

Thank you for your help.
