### ISSUE TITLE
Mathjax symbol is rendered wrong.

### ISSUE THREAD

**Issue by dofine** [glushchenko/fsnotes#1566]
### Description

Input $ y_{t-1} $ and the preview is wrong.

### To Reproduce

Input $y_{t-1}$. Click preview. 
![CleanShot 2023-06-30 at 21 55 58@2x](https://github.com/glushchenko/fsnotes/assets/440101/09559ee2-096f-4bf7-974e-df06ad3662cf)

### Expected behavior

Correct, from mathjax official website.

![CleanShot 2023-06-30 at 21 54 03@2x](https://github.com/glushchenko/fsnotes/assets/440101/7b07c781-182f-4b75-a5c6-166eba3452fc)

### FSNotes version

Version 6.3.3 (578)

### macOS/iOS version

macOS 13.4.1 (22F82)

**Comment by glushchenko** [comment]
Try to uncheck View -> Preview Soulver Calculator
