### ISSUE TITLE
Code block live highlighting (app restart required) option is no longer true?

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1568]
### Description

Code block live highlighting (app restart required) option is no longer true?

### To Reproduce

1. Go to Preferences > Editor
2. Check "Code block live highlighting (app restart required)"
3. Change happens immediately

### Expected behavior

- label says an app restart is required but that seems to not be the case?

### FSNotes version

6.3.3

### macOS/iOS version

12.6.7

### Additional context

![Screen shot 2023-07-01 at 16 03 01](https://github.com/glushchenko/fsnotes/assets/49612/210d382b-45c8-4e75-8c9d-a8f6b715993b)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.4.0/FSNotes_6.4.0.zip
