### ISSUE TITLE
“First line as title” option is not working

### ISSUE THREAD

**Issue by bradydjohnson** [glushchenko/fsnotes#1571]
### Description

![IMG_2101](https://github.com/glushchenko/fsnotes/assets/6741590/1ac38e11-40fe-416f-9a64-2f82b15ec50f)
First line as title option is greyed out/non-functional. 

### To Reproduce

iOS > Options in top right > View Settings 

### FSNotes version

6.3.3 on Mac

### macOS/iOS version

iOS 16.5.1

**Comment by bradydjohnson** [comment]
I was inpatient. It fixed after it finished syncing.

**Comment by glushchenko** [comment]
You cannot edit the settings for a virtual directory. Notes are just all notes, if you want to change the visibility or title for notes go to the settings of the directory where the note is located.
