### ISSUE TITLE
Sidebar background color (dark mode)

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1574]
**Describe your feature request**
In the screenshot below, notice that the sidebar background color is grey, but below the last tag, it is brown. I don't know which color the sidebar should be, but I think it should be one color.

**Additional context**
macOS
App Version: 6.3.3 (578)

![](https://user-images.githubusercontent.com/22358233/253099119-fc8ea1be-ef25-478c-a396-5d3aeb72177f.png)

**Comment by glushchenko** [comment]
Fixed. Thank you!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.4.0/FSNotes_6.4.0.zip
