### ISSUE TITLE
Encrypted folder icon is black 

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1575]
**Describe your feature request**
The encrypted folder icon is black but it should match the other icons in color

**Additional context**
macOS
App Version: 6.3.3 (578)

![](https://user-images.githubusercontent.com/22358233/253099119-fc8ea1be-ef25-478c-a396-5d3aeb72177f.png)

**Comment by glushchenko** [comment]
App version?

**Comment by glushchenko** [comment]
Can you update app to last version at first? I cannot reproduce it.

**Comment by nth-chile** [comment]
I just updated and still see the issue

**Comment by glushchenko** [comment]
macOS version?

**Comment by glushchenko** [comment]
Fixed. This happens only when multicolor selected here:

<img width="507" alt="image" src="https://github.com/glushchenko/fsnotes/assets/1089917/2c2f196e-47fb-478b-b6c1-eb315fa69317">

**Comment by nth-chile** [comment]
Oh cool, I never realized FSNotes uses system accent color

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.4.0/FSNotes_6.4.0.zip
