### ISSUE TITLE
One-off colors could be changed to a transparent grayscale color to work with dark and light mode

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1578]
**Describe your feature request**
The green lock and the blue lightning bolt use colors that I don't see anywhere else in the app. To maintain a consistent color scheme, maybe we should pick a transparent color that will look good on dark and light modes. Maybe 60% black for light mode and 60% white for dark mode?

**Additional context**
macOS
App Version: 6.3.3 (578)

![](https://user-images.githubusercontent.com/22358233/253099988-c884eab4-72bc-4501-8afd-142565503643.png)

![](https://user-images.githubusercontent.com/22358233/253100427-31c723a3-198b-4a25-aec3-f86431328917.png)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.4.0/FSNotes_6.4.0.zip
