### ISSUE TITLE
[BUG] Import files by dragging onto sidebar

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#158]
1. Accept a file dragged onto the Sidebar
2. If file is supported extension
    1. Copy file to FSNotes document folder
    2. Refresh Sidebar

**Comment by gingerbeardman** [comment]
Can only drop them on certain places on the sidebar even though + on mouse cursor indicates you can drop anywhere?

![screen shot 2018-04-17 at 19 30 11](https://user-images.githubusercontent.com/49612/38889200-e24a05e0-4275-11e8-9f70-409f21f29da8.png)

**Comment by glushchenko** [comment]
Fixed https://github.com/glushchenko/fsnotes/commit/9077e18851ee77f5b73c67802ddaba409c7a1119

**Comment by gingerbeardman** [comment]
Fixed in 1.5.8
