### ISSUE TITLE
6.4.1 is not 'univeral' but intel-only

### ISSUE THREAD

**Issue by core-code** [glushchenko/fsnotes#1588]
### Description

previous releases were also apple-silicon-native, newest 6.4.1 is intel-only:

<img width="529" alt="Screenshot 2023-07-29 at 21 02 19" src="https://github.com/glushchenko/fsnotes/assets/1261954/818a280c-e120-404c-a564-259df339eff7">

### FSNotes version

6.4.1

### macOS/iOS version

any

**Comment by glushchenko** [comment]
Release updated

**Comment by core-code** [comment]
confirmed fixed
