### ISSUE TITLE
[REQ] Support for tags

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#159]
tags are metadata attached to a note that can be used for purposes of searching and categorising

Might make sense to use the macOS Finder tags rather than reinventing the wheel? Not sure how that would work on iOS?

Should also support:  
- autocompletion of tags as you type one

Optionally:  
- import tags from nvALT?

Might also need another window UI (split sidebar?) for tag browser to manage of tags:  
- rename tag would rename tag in all documents that contain it
- delete tag would delete tag from all documents that contain it

**References**   
- http://christiantietze.tumblr.com/post/1480460350/mass-edit-notes (detailed tags use cases)
- http://brettterpstra.com/2017/08/09/regarding-punctuated-tags/ (macOS Finder tags)
- http://rocketink.net/2013/01/my-nvalt-setup.html (example use of @ tags)
- https://github.com/scrod/nv/issues/6 (talk about tag editor)

**Comment by gingerbeardman** [comment]
Nice! Not sure the app store will let through the "sex, drugs, rock and roll" placeholder text?

**Comment by glushchenko** [comment]
> Not sure the app store will let through the "sex, drugs, rock and roll" placeholder text?

Who knows ¯\_(ツ)_/¯

**Comment by gingerbeardman** [comment]
Working well.

Should the extra tag features have new issues?

**Comment by iandol** [comment]
Hi, I cannot migrate to FSNotes as I don't yet know how we can preserve NVAlt tags when importing notes from it? NVAlt stores tags in `kMDItemOMUserTags` but it seems FSNotes does not yet read this in even for notes copied into the Archive folder?

**Comment by jeff-h** [comment]
I wonder if a sufficiently clever shell script based on `mdfind` might be able to do the conversion?

Otherwise, perhaps FSNotes should provide an "Import from nvALT" feature? If so, I guess it would use https://developer.apple.com/documentation/foundation/nsmetadataitem to fetch the tag metadata and apply them as finder tags like FSNotes does.

Your specific mention of `kMDItemOMUserTags` suggests you might have a good knowledge of this stuff. Hope so :) Any chance you know whether nvALT uses other metadata attributes other than this 'user tags' one?

**Comment by iandol** [comment]
Actually I found a simple script to do this: https://gist.github.com/scottstanfield/683fcf4a16ed39ff4e0711be05e5d77a 

All it does is copy `kMDItemOMUserTags` to `kMDItemUserTags` and FSNotes can now read and use the tags fine (I applied it to the FSNotes Archive folder directly then restarted FSNotes). I still think getting FSNotes to support NVAlt tags by default (considering it aims to be a successor to it) would be useful for new potential users like me coming from NVAlt.

**Comment by iandol** [comment]
Actually I would have said do it automatically, but your important point about unexpected behaviour makes me realise that this probably should be optional. I suspect most users who have tagged their notes **would** want them searchable by macOS, but who knows?

**Comment by gingerbeardman** [comment]
I'd like tags to be more visible, and perhaps optionally choose to display a list of tags rather than a list of folders in the sidebar?

**Comment by lukaskawerau** [comment]
Would it be possible to show nested tags as a nested list? [Notable](https://github.com/notable/notable) and Bear do this and I find it very helpful.
