### ISSUE TITLE
Can't get Soulver to work anywhere

### ISSUE THREAD

**Issue by eyelessjerry** [glushchenko/fsnotes#1593]
### Description

Can't get Soulver calculations to work anywhere (macos or ios) – "Preview Soulver" appears to not have any effect on anything. Maybe I am missing I need to click some secret shortcut to make it work or something, but no hint anywhere for all I can see ... .

### To Reproduce

Write 3+4 = in a note or use the example supplied in the help section ... .

### Expected behavior

Maybe some Soulver functionality ... .

### FSNotes version

latest

### macOS/iOS version

latest stable Ventura Apple Silicon

### Additional context

Not sure what is the point with the FSnotes icon in the menu bar as it does nothing else than show FSnotes ... .

**Comment by gingerbeardman** [comment]
Does it work in the sample note?

Please read the docs, you need to wrap the calculation in brackets

```
# Soulver test

{ 1+1 }
```

**Comment by eyelessjerry** [comment]
Ah, see I have to toggle the Preview to see it – not used to Markdown ;-). I was really only looking for a Notes software that synced plain text notes between macOS & iOS and I have found no meaningful other product doing that ... but ok, seems to work so please close it! Nothing much happens in Markdown notes when preview is being used unless one actually do some markdown coding ...

**Comment by eyelessjerry** [comment]
The example for Soulver was in the Notes for the latest - Meet FSNotes 6! And it says there that it displays in Preview mode, so my bad.
