### ISSUE TITLE
Problems with properties

### ISSUE THREAD

**Issue by luislopezlezcano** [glushchenko/fsnotes#1597]
### Description

1 problem
When I include properties in the note, it correctly changes color in the properties, but when I put the title below the properties, the title is not seen in the list of notes, the dashes are seen.
If I put the title above the properties, it doesn't recognize the properties.

2 problem
When I set a time I extend the property to the second : and part of the time is shown in red.

<img width="1496" alt="Captura de pantalla 2023-08-12 a las 8 46 36" src="https://github.com/glushchenko/fsnotes/assets/58525841/356c13f3-3d5f-4e40-8a89-a8896f0c7176">

### To Reproduce

1. Go to 'MacOs ; Ipad; Iphone'

### FSNotes version

6.4.1

### macOS/iOS version

Ventura 13.4.1C/ iOS 16.6

**Comment by glushchenko** [comment]
Fixed here:

https://github.com/glushchenko/fsnotes/releases/download/6.6.7/FSNotes_6.6.7.zip
