### ISSUE TITLE
Error in conversion of type textbundle

### ISSUE THREAD

**Issue by luislopezlezcano** [glushchenko/fsnotes#1598]
### Description

When in a document with .textbundle and you convert it to plain text, the PDF attachments that have a link type (When the page icon appears, similar to the PDF) in assets do not change the folder. The images that are rendered, if it modifies them.

### FSNotes version

6.4.1

### macOS/iOS version

Ventura 13.4.1C

**Comment by glushchenko** [comment]
Can't reproduce
