### ISSUE TITLE
iOS app crashing

### ISSUE THREAD

**Issue by Subsonic-Modal** [glushchenko/fsnotes#1601]
### Description

iOS app will not open, just shows logo and then quits after a few seconds. Tried reinstalling and restarting phone.

iOS 16.6
iPhone 13 Pro

### To Reproduce

1. Open iOS app
2. See error

### FSNotes version

6.1.1

### macOS/iOS version

16.6

**Comment by glushchenko** [comment]
Please provide reproducible steps. As first I recommend try to delete all files from FSNotes root directory and determine which file is causing the crashes.

**Comment by Aetles** [comment]
I'm seeing this too on iOS 16.6. Launches with the logo only on white background, and crashes after a while. 

I've not yet tried to remove all files from my iCloud drive (I have well over thousand files synced), but the all worked fine up until recently.

**Comment by Subsonic-Modal** [comment]
Issue has returned for me as well. Moving all files to a new iCloud folder and moving them back fixed it temporarily, but now the app keeps crashing on launch again.

I think it may have something to with the face that

**Comment by Aetles** [comment]
Ah, interesting. If I use the Files app and open a document that is downloaded locally it works fine, but if I try to open one that is only in iCloud then FS Notes just shows the loading screen and the crashes.

**Comment by Aetles** [comment]
Well, that did not work on other files downloaded. I deleted the app and re-installed it, still crashes.

**Comment by gingerbeardman** [comment]
> Please provide reproducible steps. As first I recommend try to delete all files from FSNotes root directory and determine which file is causing the crashes.

Use to reiterate we are waiting on steps and/or files.

To check files, move half out of FSNotes, repeating with the half that contains the problem file until you eventually have a small enough set of files to figure out the individual file. (or binary search/bisect).

Alternatively, if it's not related to a file then reproducible steps to trigger the bug without a file.

**Comment by Aetles** [comment]
I understand the need to have reproducible steps from a developers point of view, but I have no steps, I just start the app as I always do, with the same files as I always have, and I just get the logo and crash. I don't think anything has changed on my end. (The app works fine if start by going to Files and opening some files from there, but I cant launch it from the app icon). 

I'll try to find some time to investigate, maybe do the bisect thing, but I'm also weary of messing up my files on iCloud by moving things around. It works fine on Mac where I mostly use FS Notes, so I'll just stick to that for now.

**Comment by gingerbeardman** [comment]
A crash log would also be useful. To find them, open the macOS Console.app and you should see them listed. Right click one and "Show in Finder" zip it up and add it to a reply in this thread.

**Comment by glushchenko** [comment]
Hi guys, I know about the problem, my wife complained to me about this error yesterday. The application really crashes when loading.

As soon as I connect my iPhone and start Xcode, everything works. This is total crap :(

Try removing all files from iCloud Drive and start the program, then add the files back in. That might help.

**Comment by gingerbeardman** [comment]
Interestingly, I am using the iOS app without this problem

**Comment by bradydjohnson** [comment]
I also experienced the crash. Going to Files app then downloading all contents of the FSNotes folder (inside iCloud Drive) resolved the issue.

**Comment by iandol** [comment]
Also have this problem; given that @glushchenko's wife had this problem, was there any chance for some debugging? Thank you for all your work on this great app, once it doesn't work I realise how important it has become to me!!!

**Comment by glushchenko** [comment]
@iandol please try to update to 6.2.0, in TestFlight right now.

**Comment by iandol** [comment]
How do i get a Testflight link to the beta?

**Comment by glushchenko** [comment]
Email me to support@fsnot.es

**Comment by gingerbeardman** [comment]
I get this crash, too.

```
Application Specific Backtrace 0:
0   CoreFoundation                      0x0000000193ed50b8 __exceptionPreprocess + 240
1   libobjc.A.dylib                     0x0000000193c1f8dc objc_exception_throw + 60
2   AppKit                              0x0000000196add1e4 -[NSTableRowData _availableRowViewWhileUpdatingAtRow:] + 0
3   FSNotes                             0x0000000104f6db78 $s7FSNotes18SidebarOutlineViewC6insert7projectyAA7ProjectC_tF + 1988
4   FSNotes                             0x0000000104f6cc88 $s7FSNotes18SidebarOutlineViewC10insertRows8projectsySayAA7ProjectCG_tF + 128
5   FSNotes                             0x0000000104eda07c $s7FSNotes14ViewControllerC19preLoadProjectsDatayyFyyYbcfU_yyYbcfU_ + 144
6   FSNotes                             0x000000010502dc84 $sIegh_IeyBh_TR + 28
```

full crash log
[FSNotes-2023-12-09-192057.ips.zip](https://github.com/glushchenko/fsnotes/files/13625434/FSNotes-2023-12-09-192057.ips.zip)

**Comment by glushchenko** [comment]
The update has been released on the App Store.

**Comment by glushchenko** [comment]
Guys, please check 6.2.1 from TestFlight.

**Comment by iandol** [comment]
Hi, great news, can confirm 6.2.1 crashing is gone! Thanks so much! Was this some sort of iCloud issue (I still have some fsnotes files that have not downloaded properly, but at least no crash)...

**Comment by Aetles** [comment]
The latest update (6.3.0) finally solved the crash on launch issue for me.
