### ISSUE TITLE
Markdown in Mermaid nodes does not render. (Probably due to outdated Mermaid version)

### ISSUE THREAD

**Issue by dezdichado** [glushchenko/fsnotes#1603]
### Description

Currently Mermaid v9.1.7 is used in FSNote, while 10.4.0 is the latest version. Due to that some documented Mermaid features may not work in FSNotes. The one I encountered is Markdown does not work in node text. 

### To Reproduce

1. Type the following in the note:
````
```mermaid
flowchart TB
    greeting("`**hi**`")
```
````
2. Toggle preview

### Expected behavior

A node displayed with the text `hi` in bold

### FSNotes version

6.4.1

### macOS/iOS version

10.15.7

**Comment by glushchenko** [comment]
Released: https://github.com/glushchenko/fsnotes/releases/download/6.9.2/FSNotes_6.9.2.zip
