### ISSUE TITLE
Underscores in title auto-removed when "Auto Rename By Title" is on

### ISSUE THREAD

**Issue by jawwad** [glushchenko/fsnotes#1605]
### Description

I've been having this weird issue in which notes I've created would have their underscores removed. This happens as soon as I add something to the content of the note. I just noticed that the problem when away when I turn off "Auto Rename By Title".

<img width="916" alt="Screenshot 2023-08-31 at 11 28 50 AM" src="https://github.com/glushchenko/fsnotes/assets/202240/ad88863c-1eda-4313-b582-9ea6318acc24">

I'm also not sure how the "Auto Rename By Title" feature is supposed to work since I have not seen any notes renamed. For example if I add a new note with Command-N it will add a note named "B6CC9843-E50A-43A7-A4BD-38DA9437C92C.markdown". But when I add some text either with a leading # or without it will rename the note to be without underscores or dashes.

Note added with Command-N:
<img width="1146" alt="image" src="https://github.com/glushchenko/fsnotes/assets/202240/337e0b70-4450-4dce-993f-0d0af17f760f">

After:
<img width="1146" alt="image" src="https://github.com/glushchenko/fsnotes/assets/202240/3a22e4a6-41b8-416c-b56b-a5591dedbbea">

### To Reproduce

1. Preferences > General > File Naming: "Auto Rename By Title"
2. In the "Search or create field" type "my_new_note" and press enter.
3. Observe note gets created. Wait a few seconds and note that title hasn't changed.
4. Type anything in the note like "hello"
5. Note that the title has changed to "my new note".

### Expected behavior

Underscores should not be removed from note titles i.e. "my_new_note.markdown" should not become "my new note.markdown"

### FSNotes version

Version 6.4.1 (581)

### macOS/iOS version

13.4.1 (c) (22F770820d)

**Comment by ozgurirmak** [comment]
I have the same issue with periods (.)

**Comment by avtraino** [comment]
I have the same issue with a hyphen (-) 

FSNotes Version 6.4.3 (586)

**Comment by avtraino** [comment]
This isn't a _bug_ per se, as it appears to be expected behavior:

**Comment by ozgurirmak** [comment]
> It appears this may not be a _bug_ per se, as it seems to be expected behavior: see [this function](https://github.com/glushchenko/fsnotes/blob/master/FSNotes/View/EditTextView.swift#L1551) which calls [this method](https://github.com/glushchenko/fsnotes/blob/master/FSNotesCore/Shared/Extensions/String%2B.swift#L114).
> 
> I do agree that FSNotes should allow any character that macOS allows in a file name, but Oleksandr may have set it up this way for a reason. We'll have to wait and see -- until then I'll just be manually managing file names in Finder.

Previously this was not the case, after one of the updates this issue occurred.

**Comment by glushchenko** [comment]
Guys, this is the standard "Auto Rename by Name" behavior. Save all alphanumeric characters and delete all others.

**Comment by avtraino** [comment]
@glushchenko what do you mean by "standard"? 

This behavior seems as though it is meant to make the file name more user-friendly. 
But since file is being renamed based on user input (first line of the file), I have to imagine that the user is entering those "special" characters (slash, underscore, apostrophe) intentionally and they _want_ those characters in the name.

I really can't figure out what problem this alphanumeric behavior is trying to solve.

What is the rationale for not allowing characters that macOS allows in a file name?

**Comment by glushchenko** [comment]
@avtraino implemented in 6.6.0

**Comment by avtraino** [comment]
I just downloaded 6.6.2 and it's working as expected. 

@glushchenko thanks so much!
