### ISSUE TITLE
画像のサイズ (Image Size)

### ISSUE THREAD

**Issue by nishiyama-nobuo** [glushchenko/fsnotes#1609]
**Describe your feature request**

**Additional context**
Add any other related information here. macOS or iOS?

iMac_2019からです｡
添付画像が編集画面の中央に配置されますが､
テキストと同じように､編集画面の左サイドにそろえることはできないのでしょうか？
それと､長い画面サイズの画像も､実際のサイズで編集画面に表示することができれば､
より使いやすいのですが､いかがでしょうか？

From Japan
nisiyama_nobuo
tsurumi.nobuo@gmail.com

**Comment by gingerbeardman** [comment]
Translation:

> It is from iMac_2019.
> The attached image is placed in the center of the edit screen,
> Isn't it possible to align it to the left side of the editing screen like text?
> Also, if you can display a long screen size image in the actual size on the editing screen,
> It's easier to use, what do you think?
