### ISSUE TITLE
[REQ] Undo Delete

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#161]
nvALT has this, very useful.

The note is sent to Trash, so an undo should be possible?

`mv "~/.Trash/Untitled Note.md" "~/Library/Containers/co.fluder.FSNotes/Data/Documents/"`

**Comment by gingerbeardman** [comment]
We're almost there with this one! Trash is working very well.

**Comment by glushchenko** [comment]
I think we can close this issue?

**Comment by gingerbeardman** [comment]
I expect to be able to Undo the action of sending note to Trash, either by Edit > Undo or Cmd+Z?

**Comment by glushchenko** [comment]
Added in 1.6

**Comment by glushchenko** [comment]
@gingerbeardman what build did you use?

**Comment by gingerbeardman** [comment]
1.6.0 release

**Comment by glushchenko** [comment]
Last build 132

**Comment by gingerbeardman** [comment]
I'll try again

**Comment by glushchenko** [comment]
I found bug, not worth it

**Comment by glushchenko** [comment]
Fixed in 1.6.1
