### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by hy-zhao23** [glushchenko/fsnotes#1612]
### Description

I am syncing files with iCloud drive. Every time I try to update a file, several duplicated files would be saved. And these files are clearly the intermediate files between original version and final version. 

It has been like this for quite a while, which means it is not related to system version. Maybe there is something wrong with the sync mechanism.

### To Reproduce

1. Go to 'Inbox'
2. Edit a file on your phone or laptop

### FSNotes version

Version 6.4.1 (582)

### macOS/iOS version

14.0 (23A339) / 17.0 (21A329)

**Comment by glushchenko** [comment]
Conflicts are created through no fault of the app, all questions to Apple iCloud Drive sync.

**Comment by hy-zhao23** [comment]
I don't know if it is like this, but I haven't encountered the same issue with any other apps that use iCloud Drive sync.

**Comment by glushchenko** [comment]
> I don't know if it is like this, but I haven't encountered the same issue with any other apps that use iCloud Drive sync.

Because others haven't implemented conflict resolution. I think it is better to have conflict files than to lose important files.

**Comment by hy-zhao23** [comment]
Got it. Thank you so much for clarification!

Quite annoying though. I understand FSNotes is designed for iOS/MacOS, but why not provide support to webdv to solve it and the cloud management can be more extensible too.

**Comment by glushchenko** [comment]
> Quite annoying though. I understand FSNotes is designed for iOS/MacOS, but why not provide support to webdv to solve it and the cloud management can be more extensible too.

How webdav can solve it? When you edit files without synchronization in two places there will be conflicts anyway.

**Comment by hy-zhao23** [comment]
I see. I thought it is due to iCloud drive mistakenly. Maybe only keep the final state would be a little easier to manage files. Then sync files when the network is on.

Thanks for your patience!

**Comment by glushchenko** [comment]
This is disabled by default in last build.
