### ISSUE TITLE
[macOS] Default storage location reverts from iCloud

### ISSUE THREAD

**Issue by glottisfaun0000** [glushchenko/fsnotes#1614]
### Description

I have an FSNotes folder at `iCloud Drive > FSNotes` created by FSNotes on iOS. When opening FSNotes.app installed via `brew install --cask fsnotes` on macOS, it creates an On My Mac folder at `Library/Containers/FSNotes/`. When I change the default storage location to the iCloud folder, delete the On My Mac folder, it works fine for a little while even after relaunch, but coming back to it later and launching FSNotes.app causes the On My Mac folder to be created again and my settings to revert from the iCloud location.

### To Reproduce

1. Have FSNotes folder at `iCloud Drive/FSNotes`
2. Install FSNotes on macOS via `brew install --cask fsnotes`
3. Open FSNotes, creates On My Mac folder at `Library/Containers/FSNotes/`
4. Change default storage location to `iCloud Drive/FSNotes` in settings
5. Quit FSNotes.app
6. Reopen it sometime later
7. `On My Mac` folder is created again and default storage location reverts to `Library/Containers/FSNotes`

### Expected behavior

FSNotes settings keep the default storage location in iCloud Drive

### FSNotes version

6.4.1

### macOS/iOS version

Ventura 13.5.2

**Comment by glottisfaun0000** [comment]
To add to this, I've been leaving FSNotes open to avoid the issue but it managed to still create the On My Mac folder while the iCloud Drive folder was open in the app. Maybe the gap between immediately closing/opening and coming to it later to find the default location switched is when that folder gets created in the background? Speculating.

**Comment by glottisfaun0000** [comment]
I think this is an instance of the same problem as https://github.com/glushchenko/fsnotes/issues/1014 , but I don't understand why the preferences rollback after manually setting the Default storage location? It reverts all preferences like .md/.markdown

**Comment by glushchenko** [comment]
FSNotes does not create "On My Mac" folder. If iCloud Drive path is not available, then Local folder from Library/Container used.

iCloud Drive path always used in Mac App Store FSNotes version, not from GitHub. GitHub version is Notarized and does not have access to iCloud Drive by default. If you select it manually, no any guaranties.
