### ISSUE TITLE
Implementation of #1525 interfers with tag names consisting of characters "a..f" only

### ISSUE THREAD

**Issue by tjuerge** [glushchenko/fsnotes#1615]
### Description

After resolving #1525 (via `if tag.allSatisfy({ $0.isHexDigit }) { return false; }`) it's not possible anymore to use tag names which are consisting of hex code characters "a..f" only, e.g. the abbrevation of Domain-Driven Design "ddd".

How about improving the hex color code check, e.g. by expecting a length of 6 characters?

### To Reproduce

1. Create note
2. Add tag `#ddd`

### Expected behavior

The tag `#ddd` should be recognized as a valid tag name instead of a hex color code.

### FSNotes version

6.4.1

### macOS/iOS version

13.5.1

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.5.0
