### ISSUE TITLE
Document how to use Soulver expressions

### ISSUE THREAD

**Issue by jasonekratz** [glushchenko/fsnotes#1617]
**Describe your feature request**

You've got a killer feature in here that basically has no documentation. SoulverCore features are a fantastic resource and just pointing to the "getting started" page for the library itself will put anyone off using this functionality. Soulver itself has great documentation (I know, I've been a user for years). FSNotes should have much better documentation for a feature that is quite unique among notes apps.

**Additional context**
None

**Comment by gingerbeardman** [comment]
This is true, every time I go to use it I have to spend time trying to find out how.

**Comment by tryonkus** [comment]
Yes, please! I am stumped. Do I use a Soulver code block? Inline code? Plain text?

**Comment by gingerbeardman** [comment]
From "Meet FSNotes" sample file:

> ## Soulver core
> 
> In collaboration with Zac Cohan, SoulverCore syntax has been added. This calculator now displays in Preview mode. Read more about its functions here: https://github.com/soulverteam/SoulverCore#getting-started
> 
> Example: 9:35am in New York to Japan = {9:35am in New York to Japan}

so: use { and } and toggle Preview mode to see the results.

**Comment by tryonkus** [comment]
I’d read through the Readme pretty thoroughly but had missed that. Thanks!

**Comment by tryonkus** [comment]
Being in IT but not a programmer, I’m not seeing where the {} come from—I’m not even seeing that example on the linked page. Is that Markdown syntax? I’m not finding it in the GFM spec. 

Also, is there a way to do multiline calculations as in the standalone Soulver app? I tried a few variations and none worked.

**Comment by tryonkus** [comment]
Hrmmmm, not seeing that sample note in the version of FSNotes I just purchased from the Mac App Store. Maybe it’s in the website version.

**Comment by gingerbeardman** [comment]
Perhaps it only appears in the initial blank install?  

But it's definitely included in the app.

https://github.com/glushchenko/fsnotes/blob/master/Resources/Initial/Meet%20FSNotes%206.textbundle/text.markdown?plain=1

**Comment by tryonkus** [comment]
I just installed yesterday on both iOS and macOS. There are nine notes in the Introduction folder, and I have two copies of each (I set the base folder in iCloud to be the same for both versions). 

The iOS page on the FSNotes site looks very similar to what you sent and includes a reference to Soulver, sans the braces example. 
https://fsnot.es/fsnotes6-for-ios/

Soulver support (probably the author) told me about the braces, but I’m not finding it in the FSNotes documentation. My guess is that Oleksander (sorry if I’m remembering that wrong) rewrote the documentation for the new release and just missed that bit. Sounds like life has been hectic, being in a war zone and all. I’m impressed that he was able to get a major revision released under the circumstances.

**Comment by tryonkus** [comment]
The document you linked is almost identical to the iOS notes, but they don’t include the Soulver example. Odd, but thanks for your help. 🙂

**Comment by tryonkus** [comment]
FWIW, this is the Introduction folder that FSNotes created (hopefully it will open for you—if not, I can share it from Dropbox).
https://www.icloud.com/iclouddrive/04e6WZkOsX-z24Unx3IGCP0mA#Welcome

**Comment by tryonkus** [comment]
FWIW, this is a copy of the Welcome folder that FSNotes installed: https://www.dropbox.com/scl/fo/qvfko0d46qqcizwk8x4c9/AL1OBWzNQz9C4Df3HZfBmu4?rlkey=v9sxzvnn7nvx9mj60k3jkouic&dl=0

**Comment by glushchenko** [comment]
Hi guys and @tryonkus, saw your email, replying here:

The code in curly braces { } is currently interpreted as Soulver code if you enable this in the View menu.

There are some examples here:
https://soulverteam.github.io/SoulverCore/documentation/soulvercore/gettingstarted

I don't use it, so there's nothing to document.

**Comment by tryonkus** [comment]
OK—I had asked the Zac Cohan about Soulver's intended use (natural language calculator with some text capability) versus a note taking app with a calculator, and he pointed me to FSNotes. I'm all over Markdown apps, and I was just exploring features and breaking stuff. 😏

**Comment by birlorg** [comment]
On FSNotes desktop Version 6.6.8 (615)

I have to put `{calculator.calculate()}` at the end of my document to get Soulver to actually calculate anything before the {calculator.calculate()}

This is with View/Preview Soulver Calculator turned on. With it off, it acts just like I didn't put {calculator.calculate()} at the end of the document. 

Note: `{calculator.calculate()}` shows as normal text and is shown.

Example markdown:
```md
 9:35am in New York to Japan = {9:35am in New York to Japan}
{10% of 5000}
{$25/hour * 14 hours of work}
{January 30 2020 + 3 months 2 weeks 5 days}

Compound Interest:

{$25k over 10 years at 7.5%}

{123 + 456}
{65 kg in pounds}

{$10 for lunch + 15% tip}
{calculator.calculate()}
```

returns this in preview mode(alt+/)
```md
9:35am in New York to Japan = 10:35 PM
500
$350.00
May 19, 2020

Compound Interest:

$51,525.79

579
143.3004704202 lb

$11.50
{calculator.calculate()}
```
