### ISSUE TITLE
Display name of file for attachments (macOS)

### ISSUE THREAD

**Issue by jasonekratz** [glushchenko/fsnotes#1618]
**Describe your feature request**
Love the fact that I can drag literally any type of file to a note. Please keep this ability. But right now FSNotes only displays the same icon style regardless of the file type and no indication of what the file name is. Don't care so much about the icon but knowing the name of a file is essential. Don't even care about previews, just would love to see the file name so I know what I've attached.

**Additional context**
This is on macOS where I can at least then double-click on one of the file icons and it brings be to a folder where I can see all of the attachments. On iOS I just get some icons that don't do anything so not sure if the actual attachments are syncing or not.

**Comment by glushchenko** [comment]
Implemented

**Comment by jasonekratz** [comment]
Oh sweet. thank you!
