### ISSUE TITLE
Crash in Sonoma with M1 Pro

### ISSUE THREAD

**Issue by gsong** [glushchenko/fsnotes#1621]
### Description

v6.4.1 upon launch in Sonoma 14.0 running on M1 Pro immediately crashes.

[See crash report](https://gist.github.com/gsong/edb68fb9d6720adadf67c7a733048f47).

Possibly related to #1620.

### To Reproduce

Launch app.

### Expected behavior

For the app to run.

### FSNotes version

6.4.1

### macOS/iOS version

14.0

### Additional context

M1 Pro

**Comment by concr** [comment]
Can confirm this bug on MacBook Pro M1 Pro (2021)

**Comment by ruby-lorenze** [comment]
Its effecting my intel Macbook Pro as well.

**Comment by glushchenko** [comment]
Any solution and PR will be appreciated

**Comment by glushchenko** [comment]
Please check https://github.com/glushchenko/fsnotes/releases/download/6.4.2/FSNotes_6.4.2.zip

**Comment by lukestein** [comment]
> Please check https://github.com/glushchenko/fsnotes/releases/download/6.4.2/FSNotes_6.4.2.zip

Unfortunately issue persists for me with this new download (OS Sonoma 14.0, MacBook Pro M1 Max)

**Comment by glushchenko** [comment]
@lukestein please redownload. New build 584.

**Comment by lukestein** [comment]
> @lukestein please redownload. New build 584.

And we're back in business. Thank you!!

**Comment by concr** [comment]
For me it's fixed with 6.4.2, many thanks!

**Comment by gsong** [comment]
Version 6.4.2 (584) has fixed the issue for me as well.
