### ISSUE TITLE
Created web page is not synced across device

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1623]
### Description

Created web pages are not synced across devices, which results in multiple web pages that can only be kept in sync from their respective devices.

### To Reproduce

1. Create note on iOS
2. Publish to web page
3. Open same note on macOS
4. Note shows with no published web page
5. Publish to web page
6. Now we have two web pages, out of sync, one for iOS and one for macOS

### Expected behavior

- Web page status should be synced across devices, somehow

### FSNotes version

- 6.4.2

### macOS/iOS version

- 12.7

**Comment by glushchenko** [comment]
Yes, this feature is not implemented.
