### ISSUE TITLE
Conflict every few seconds

### ISSUE THREAD

**Issue by neilscott** [glushchenko/fsnotes#1624]
### Description

If I am writing in FS Notes, the app creates separate conflict versions every few seconds e.g. 

(CONFLICT 20231005T070858)
(CONFLICT 20231005T070905)

I don't understand what is happening here. It happens in both ios 17  and on macos sonoma, but not on Ventura.

### To Reproduce

1. Go to 'App'
2. Write
3. See a new conflicted duplicate page created

### Expected behavior

Only create a conflict if there is a conflict

### FSNotes version

Version 6.4.2 (584)

### macOS/iOS version

Sonoma/17

### Additional context
I use iCloud Drive for storage.
I have tried resetting GIT but would happily remove it.

_No response_

**Comment by f1nnix** [comment]
Definitely the same issue, I'm struggling last week. Almost every change raises conflict constantly.

For now just moved out of iCloud Drive.

Also experimenting now with fresh copy in iCloud from scratch.

**Comment by willxie** [comment]
I can also very consistently reproduce this.

**Comment by f1nnix** [comment]
I've noticed that every conflicted version is always out of date. So actually the last version (without CONFLICT mark in file name) is the most recent one.

**Comment by f1nnix** [comment]
> Also experimenting now with fresh copy in iCloud from scratch.

Tested on a fresh copy of iCloud, the same result. 14 duplicated while writing a letter.

<img width="897" alt="Screenshot 2023-10-06 at 17 57 04" src="https://github.com/glushchenko/fsnotes/assets/3099788/b63cdc31-592f-46db-81e1-9746e9c6c433">

**Comment by markmonroy** [comment]
Same here. FSNotes 6.4.2 (584), macOS 14.0 on an M1 Max Mac Studio. Notes stored in iCloud Drive. I've turned off iCloud's "Optimize Storage" so all files are always local. 

For me, when the conflict occurs there's also a split-second hang with a beach-ball cursor.

Would strongly prefer not to have to move my notes out of iCloud, so I hope there's a solution. Thank you.

**Comment by glushchenko** [comment]
Thanks to all for feedback. A dont know whats going on under the hood in the iCloud Drive, so conflicts resolution is disabled by default in FSNotes 6.4.3

<img width="662" alt="image" src="https://github.com/glushchenko/fsnotes/assets/1089917/664f8736-6ffe-4615-9b6c-641fd76a3de4">

https://github.com/glushchenko/fsnotes/releases/tag/6.4.3

**Comment by willxie** [comment]
I updated to FSNotes 6.4.3 with the conflict resolution option turned on. I am still getting constant conflicts as I type on any notes. 

<img width="905" alt="Screenshot 2023-10-09 at 2 19 39 PM" src="https://github.com/glushchenko/fsnotes/assets/4821081/eaef033e-2749-419e-90e6-ac4ba5ae27b4">

**Comment by glushchenko** [comment]
@willxie this is not FSNotes issue. Conflicts generates on the iCloud Drive side.

**Comment by glushchenko** [comment]
@willxie this is not FSNotes issue. Conflicts generates on the iCloud Drive side.

**Comment by glushchenko** [comment]
@willxie this is not FSNotes issue. Conflicts generates on the iCloud Drive side.

**Comment by f1nnix** [comment]
@glushchenko Thank you, last version seems to be working as expected 👍

@willxie What'd worked for me is to switch **off** conflicts resolution. Since I've turned it off in latest version of FSNotes, no more duplicates are created:

<img width="449" alt="Screenshot 2023-10-10 at 01 20 28" src="https://github.com/glushchenko/fsnotes/assets/3099788/73328971-c4c9-4c7a-bd4d-024edc1ca9f3">

**Comment by willxie** [comment]
Turning off conflict resolution worked for me. Thanks for the suggestion!

**Comment by glushchenko** [comment]
Automatic conflicts resolution is disabled by default in the last build. You don't have to do anything.

**Comment by markmonroy** [comment]
Should we report this bug to Apple? I haven't been able to find much info but after reading [this blog post](https://www.dominikmayer.com/2023/09/icloud-drive-silently-deletes-your-content/) I'm slightly concerned that turning off conflict resolution could result in the loss of data.

**Comment by glushchenko** [comment]
> Should we report this bug to Apple? I haven't been able to find much info but after reading [this blog post](https://www.dominikmayer.com/2023/09/icloud-drive-silently-deletes-your-content/) I'm slightly concerned that turning off conflict resolution could result in the loss of data.

Do you know how to reproduce the problem sustainably? I, for example, do not have this behavior.

**Comment by markmonroy** [comment]
If I check the box, then it happens without fail. Steps:

- Enable "Automatic iCloud Drive Conflicts Resolution"
- Type a few lines
- Watch conflict file be created
- Type a few more lines
- Watch another conflict file be created

And repeat. I notice that when the new file is created, in Finder, a cloud icon with a little exclamation point briefly appears on the main doc.

![Screenshot 2023-10-10 at 6 42 11 PM](https://github.com/glushchenko/fsnotes/assets/32033503/c55ae5f6-70c9-4794-895d-0e722701cd66)

Notes are stored in ~/Library/Mobile Documents/iCloud~co~fluder~fsnotes/Documents

Permissions on all my regular notes are set to 644, but the CONFLICT files are set to 777.

On the plus side, so far I haven't seen any CONFLICT files that contain *newer* data than the original file.

**Comment by f1nnix** [comment]
> On the plus side, so far I haven't seen any CONFLICT files that contain newer data than the original file.

-+1, so do I. I've tested a lot, and each time the most recent version is in original file, not in conflict one.

**Comment by nth-chile** [comment]
I'm experiencing this with iOS app, but I don't see a conflict resolution setting in the iOS app

**Comment by neilscott** [comment]
I find when I use the iOS app and I am typing, it sends me to the bottom of the page I am writing in. Possibly the moment it syncs with iCloud?

**Comment by nth-chile** [comment]
@neilscott exactly. I was meaning to add mention of that

**Comment by glushchenko** [comment]
@nth-chile this is fixed long time ago. Just update macOS and iOS apps.

**Comment by nth-chile** [comment]
I updated my iPhone to 17.1 and it seems to have fixed the issue @neilscott
