### ISSUE TITLE
MacOS Version 6.4.2 (584) launches with no notes displayed

### ISSUE THREAD

**Issue by millerim** [glushchenko/fsnotes#1625]
### Description

Upon launch FSNotes displays no notes in the sidebar.

### To Reproduce

1. Launch FSNotes
2. No notes are displayed in the sidebar
3. Click the "New Note" button and all the notes appear in the sidebar, including a new note.
See video for a better explanation.
https://github.com/glushchenko/fsnotes/assets/30205020/8e9ef740-e761-44c0-ad8c-2f28a55a55a7

### Expected behavior

All the notes in the default folder should appear at launch.

### FSNotes version

MacOS Version 6.4.2 (584)

### macOS/iOS version

Sonoma 14.0 (23A344)

**Comment by glushchenko** [comment]
Can not reproduce this.

**Comment by millerim** [comment]
Must be a setting. Is there a way to reset to the defaults?On Oct 5, 2023, at 5:54 AM, Oleksandr H. ***@***.***> wrote:﻿
Can not reproduce this.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/wiki/Preferences-location#how-to-reset-all-settings

**Comment by millerim** [comment]
Thanks, I’ll check the wiki going forward.  I think I see the issue.  It happens when the sidebar is hidden.  It seems that it doesn’t find the notes folder if the sidebar is hidden.  The notes appear if I show the sidebar and click the folder name.  If I launch with the sidebar not hidden it finds the folder and shows the notes list properly.  I hope you can replicate now.  Thanks!

**Comment by glushchenko** [comment]
@millerim please check this https://github.com/glushchenko/fsnotes/releases/tag/6.4.3

**Comment by millerim** [comment]
Resolved, thanks!
