### ISSUE TITLE
iOS: No option to update web page

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1626]
### Description

There's no option to update a web page  after it's created. 

![IMG_4560](https://github.com/glushchenko/fsnotes/assets/49612/4634d40f-b6bc-4adb-abf7-e6178c0d940f)

### To Reproduce

1. FSNotes iOS
2. Create note
3. Create web page
4. Change note
5. Look for option to update web page

### Expected behavior

Create web page should become Update web page

### FSNotes version

6.1.1 iOS

### macOS/iOS version

16.7

### Additional context

Also the apostrophe is missing in the note title at the top of the menu.

**Comment by Koloth** [comment]
I'll also add that the option to create a webpage errors out if you have already created a webpage, so this is somewhat annoying behavior.  The Mac version works, so the workaround is to just change devices to press update, but this behavior seems subpar.

**Comment by gingerbeardman** [comment]
> Update: that actually doesn't work. The Mac version didn't know about the web published version from the phone, so I had to publish a new link to update it.

Yes, I noticed that but forgot to add to issue

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/commit/20424354cc0230670e22a155c5cd758eff11ddf0

**Comment by glushchenko** [comment]
Update with sync released for macOS and iOS.
