### ISSUE TITLE
Pinch To Zoom

### ISSUE THREAD

**Issue by r3a1d3a1** [glushchenko/fsnotes#1633]
Would be great to have a pinch to zoom on Mac similar to the builtin Text Editor app or Chrome when using a trackpad.
Thanks.

**Comment by glushchenko** [comment]
You can use ⌘+ and ⌘-, touchpad should not be used in a text editor on mac in my understanding.

**Comment by glushchenko** [comment]
> So...?? Wanna leave this closed just because you don't have a trackpad, or do you have a better reason?

FSNotes is a keyboard-oriented application, and it makes no sense to use it with a trackpad or mouse. The way I see it. 

If you're not happy with it, you can spend your time, implement trackpad support and send a pull request. I'll take it.

I'll spend my free time with my family, if you don't mind.

**Comment by glushchenko** [comment]
I've been using vim for the last 20 years on linux, trackpad for 10 years. But in this case I don't need it.
