### ISSUE TITLE
iOS: Duplicate notes on autosave

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1634]
### Description

I don't know how to reproduce this, but it's been happening quite often for the past two or three weeks. I think it's just on iOS. You edit a note and then it creates like five copies. One for each autosave I assume. Anyone else experiencing this?

### To Reproduce

1. On iOS, edit note
2. See duplicates in note list

### FSNotes version

6.1.2

### macOS/iOS version

17.0.3

**Comment by glushchenko** [comment]
iOS app does not create duplicates.

**Comment by nth-chile** [comment]
![Screenshot 2023-10-29 at 9 29 24 AM](https://github.com/glushchenko/fsnotes/assets/22358233/73db30f7-95e9-42a5-b312-429c0565a4f9)

**Comment by nth-chile** [comment]
Just noticed a similar issue created recently here https://github.com/glushchenko/fsnotes/issues/1624

**Comment by glushchenko** [comment]
@nth-chile https://github.com/glushchenko/fsnotes/blob/master/FSNotes%20iOS/CloudDriveManager.swift#L182
