### ISSUE TITLE
TaskPaper support

### ISSUE THREAD

**Issue by danblondell** [glushchenko/fsnotes#1635]
**Describe your feature request**
Support for TaskPaper format and commands.

**Additional context**
Add any other related information here. macOS or iOS?
There are currently no excellent TaskPaper apps on iOS, so this would address an opening the same way FSNotes has filled the gap left by nvAlt. Previously, Editorial had by far the best TaskPaper integration of any iOS application.

Here's information from the developer for integrating TaskPaper into other apps: https://support.hogbaysoftware.com/t/what-is-taskpapers-open-source-model-layer/2148

**Comment by gingerbeardman** [comment]
I just read into it and if my understanding is correct TaskPaper is the app, whose format is called "Birch Outline". It's a plain text todo list format with support for Outlines. Created 2006.

```
Welcome:
	- TaskPaper knows about projects, tasks, notes, and tags.
	- It auto-formats these items so that your lists are easier to read.
	- Delete this text when you are ready to start your own lists.
To Create Items:
	- To create a task, type a dash followed by a space.
	- To create a project, type a line ending with a colon.
	- To create a tag, type '@' followed by the tag’s name.
To Organize Items:
	- To indent items press the Tab key.
	- To un-indent items press Shift-Tab.
	- To mark a task done click leading dash.
To Fold, Focus, and Filter Items:
	- To fold/unfold an item click the dot to the left of the item.
	- To focus on a single project select it in the sidebar.
	- To filter your list enter a search in the toolbar search field.
```

Also created that year is Todo.txt http://todotxt.org which is the one I use. No support for outlines, but has support for dates, marking complete, etc. https://github.com/todotxt/todo.txt

```
To create a task, type anything on a line.
To create a project, type a '+' followed by the project's name
To create a tag, type '@' followed by the tag’s name.
```

FSNotes supports Markdown because it's quite ubiquitous. But which todo format meets that criteria? I don't know.

**Comment by danblondell** [comment]
Unlike Markdown, I don’t think there’s a clear ubiquitous one between the two, though if I had to guess you made the right choice with todo.txt if ubiquity is the goal. 

Taskpaper is a bit more powerful and, in my opinion elegant, and it’s also typically implemented with commands like Archive that move all the completed tasks to the bottom of the list under a new header Archive.

**Comment by gingerbeardman** [comment]
I agree with your sentiment. 

FSNotes uses third-party packages to cope with MarkDown, so I guess the task would be to find one that works for TaskPaper/Todo.txt/etc that could be integrated in a way that can co-exist with the Markdown parser.

**Comment by gingerbeardman** [comment]
There is Taskpaper/Birch Outline framework written in Swift, either it's complete (I hope) or abandoned for 7 years (maybe)

https://github.com/jessegrosjean/BirchOutline

Perhaps this could somehow be an alternate document mode? or interface with Markdown?

**Comment by danblondell** [comment]
Programming is not my domain, but I believe it's meant to coexist with Markdown. The developer is active and generous and I'm sure he'd answer questions if you're interested in adding it. Also his Mac app is still supported and great if you want to test-drive it first.

**Comment by danblondell** [comment]
Yes! The archive is wonderful
