### ISSUE TITLE
Crash when using URI scheme to create note with contents when title is not supplied

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1636]
### Description

Crash when using URI scheme to create note from contents when title is not supplied

### To Reproduce

1. Paste this link into Safari and allow it to open FSNotes: fsnotes://new/?title=Title&txt=Test
2. ok

vs

1. Paste this link into Safari and allow it to open FSNotes: fsnotes://new/?title=&txt=Test
2. crashes

Crash Logs: [archive.zip](https://github.com/glushchenko/fsnotes/files/13252513/archive.zip)

### Expected behavior

- should not crash

### FSNotes version

- 6.4.3 Mac App Store

### macOS/iOS version

- 12.7.1 (21G920)

**Comment by glushchenko** [comment]
Confirmed and fixed. Thank you for report!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.5.0
