### ISSUE TITLE
Menubar icon interaction request

### ISSUE THREAD

**Issue by GrugBe** [glushchenko/fsnotes#1638]
Menubar icon interaction request : 

In NVAlt a little thing  : when you click on the menubar icon, the window appears.
If you click again, the window hiding. In NSNotes nothing appends :(

That a tiny thing, but useful. 

 MacOS 10.14

**Comment by glushchenko** [comment]
Implemented, thanks.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/v6.6.0
