### ISSUE TITLE
Error installing Highlightr: reference is not a tree

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1640]
### Description

I tried building the app for the first time in a while, and here is one issue I'm facing.

I did `rm -rf ./Pods && pod install`

```
[!] Error installing Highlightr
[!] Failed to download 'Highlightr': [!] /opt/homebrew/bin/git -C /var/folders/ld/99c6pl9539x5n5m22lypl44m0000gn/T/d20231117-48292-1obx9l checkout --quiet efbb3052f550f2a77f4df35102475e1046afec7b

fatal: reference is not a tree: efbb3052f550f2a77f4df35102475e1046afec7b
```

### To Reproduce

1. `cd` to project
2. `rm -rf ./Pods && pod install`

### FSNotes version

Latest commit

### macOS/iOS version

Latest commit

**Comment by nth-chile** [comment]
Deleting the package from my `Podfile.lock` seems to have resolved the issue. I wonder if we should commit the lockfile

**Comment by glushchenko** [comment]
lockfile is for local usage only
