### ISSUE TITLE
Accidentally make a note disappear

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1641]
### Description

There is a way to accidentally make a note disappear. The only way I've found to retrieve it is from the backup git repo.

### To Reproduce

1. Create a note in an encrypted folder
2. From the note list, drag the note into the encrypted folder that it's already in
3. Note disappears

### FSNotes version

Version 6.4.1 (582)

### macOS/iOS version

14.1.1 (23B81)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/v6.6.0

**Comment by glushchenko** [comment]
@hasantahir The application does not delete notes. You may have changed the title as well, and you may have auto-renaming enabled. In any case, look for the note in the folder selected for storage.

**Comment by hasantahir** [comment]
Thanks for your reply. The storage location is iCloud Drive. I was working on it when this happened and unfortunately, I only see a file of zero bytes.
