### ISSUE TITLE
Lost Data

### ISSUE THREAD

**Issue by ruby-lorenze** [glushchenko/fsnotes#1644]
### Description

Mate I don't know whats gone wrong but I seem to have lost a load of data - stuff I'm searching for just doesn't appear anymore. Can I be doing something wrong or how can I debug it? The data should be stored in iCloud Drive as well as the User/Library. Ive tried searching in the filesystem for known text but much of its encrypted> Sorry I? can't be of more help. Up till now i thought your 1:2:3 data replications was bombproof!

### FSNotes version

Version 6.5.0 (589)

### macOS/iOS version

Sonoma 14.2

**Comment by gingerbeardman** [comment]
1. create a new note

Q: do you see it in the window? If not, have you hidden the sidebar?

2. right click the new note and choose "Show in Finder"

This will reveal the note in the filesystem, alongside all the other notes.

If you're still having problems, please post a screenshot or some information on what you're trying and why it's not matching your expectations.

**Comment by ruby-lorenze** [comment]
Yes. All files seem to be there on iCloudDrive which is the good news but most are .markdown wrapped in textbundle which I had to admit I don't really understand. I have note with text "YES YES YES" at the top which I can find on the iclouddrive but when I search for it in the app its not appearing. I thought i would remove the textbundle container from Settings to None. and now most of them are now .rtfd, although some are still .markdown, .textbundle &.txt. Weirdly I was going to attach an example of the iclouddrive.markdown file and screenshot of FSNotes but when as you don't accept .markdown files for upload I duplicated the file intending to rename to file type to .txt and hey presto both the original and duplicate popped up in FSNotes!!! I'm afraid I'm at a loss....

**Comment by ruby-lorenze** [comment]
Thanks

**Comment by ruby-lorenze** [comment]
I thought I would add a screenshot on the iCloudDrive/FSNotes Dir although this in only fraction of it. 
![Phil Long - FSNotes - iCloudDrive](https://github.com/glushchenko/fsnotes/assets/40770180/2e00f597-de08-4eb2-8e2b-169984aa376c)

**Comment by ruby-lorenze** [comment]
Oh and I forgot. there showing up in the iPhone App!!

**Comment by gingerbeardman** [comment]
> It sounds like you have selected a subfolder and so are filtering the search only to that folder. 

Please show a screenshot of your FSNotes sidebar.

**Comment by ruby-lorenze** [comment]
Well I seem to have duplicated a load of notes because when I couldn't see any data in a  folder I selected Add External Folder?! Opps. These look to be all zero bytes so I guess I can delete them from iCloudDrive can I? But then only a few of the other notes  .txt .rtfd although hery show bytes are also empty?
![FS Notes Sidebar](https://github.com/glushchenko/fsnotes/assets/40770180/11d3c574-f968-4ad1-850c-6099c2fbd053)

**Comment by ruby-lorenze** [comment]
This isn't the whole side menu

**Comment by ruby-lorenze** [comment]
Yeah but as i understand it if you click on Notes you should get all the notes. I've only got a fractions of the hundreds I had previously. I could try restoring from Timemachine but I'm not sure if I should be restoring the iCloudDrive/FSNotes folder or there is also files in /User/Library/Containers/FSNotes? oh dear....
![FSNotes - All Notes Selected](https://github.com/glushchenko/fsnotes/assets/40770180/cf8c82db-9546-42b7-81b7-5b5464314c36)

**Comment by gingerbeardman** [comment]
Personally, I wouldn't try to solve the problem until we figure out exactly what the problem is. 

If they are all on iCloud Drive, then click the "iCloud Drive" header (it doesn't look clickable but it is)

> FSNotes only does what you ask of it. It doesn't create or delete or move notes unless you command it to. Never ever will it do anything without you asking because it's programmed that way.

Regardless, it sounds that you have got your notes into a bit of a mess. If it helps, forget about FSNotes and work in Finder if you are more familiar with that. FSNotes preferences and/or right click "Reveal" will let you know which folder the notes are in, and you can organise them manually.

**Comment by glushchenko** [comment]
I think it was a bug related to caching, 6.6.5 resolves all this.
