### ISSUE TITLE
FSNotes crashes when showing/hiding sidebar

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#165]
FSNotes 1.5 crashes whenever I select "Hide/show sidebar" from the menu. The shortcut key for this seems to work OK. I deleted the FSNotes preference files after installing 1.5, thinking that might make a difference, but it didn't. 

Thanks for the great update; it's a big change but I'm going to like it a lot. :)

[peavine_report.txt](https://github.com/glushchenko/fsnotes/files/1910563/peavine_report.txt)

**Comment by glushchenko** [comment]
Fixed in 1.5.1

**Comment by peavine** [comment]
I installed 1.51 and all is well. Thanks.
