### ISSUE TITLE
6.6.0 crash on open

### ISSUE THREAD

**Issue by foss-** [glushchenko/fsnotes#1650]
### Description

Whenever the app is opened, it instantly crashes.

### To Reproduce

Open app -> crash

Crash log (1 month): https://bin.disroot.org/?f0232d4de9ac7192#DqVfFGe4W9uVZvPw5cN9hxf29ym1XjnT8rzSmNYjefvz

### Expected behavior

no crash

### FSNotes version

6.6.0

### macOS/iOS version

13.6.1

### Additional context

Just updated and with the update the crashes started. GitHub version on an intel mac.

**Comment by gingerbeardman** [comment]
Dupe #1649
