### ISSUE TITLE
Blank items in note list when searching

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1651]
### Description

Blank items in note list when searching

### To Reproduce

1. Search for a word across notes.
2. Look for blank entries in note list

### Expected behavior

Each cell of note list should have text in it

### FSNotes version

6.6.0 (601)
6.6.1

### macOS/iOS version

12.7.1

### Additional context

6.6.0 vs 6.5.0
![image](https://github.com/glushchenko/fsnotes/assets/49612/e17fdec5-a8c5-4ee4-8d60-70714b1bebde) vs ![image](https://github.com/glushchenko/fsnotes/assets/49612/4949ca26-f172-4399-a26f-b2814aabb15e)

**Comment by glushchenko** [comment]
Please check this build:

https://github.com/glushchenko/fsnotes/releases/download/6.6.1/FSNotes_6.6.1.zip

Settings -> Advanced -> Reset Caches

**Comment by gingerbeardman** [comment]
No, still broken.

I did click the reset cache button.

![image](https://github.com/glushchenko/fsnotes/assets/49612/173471f8-27f8-48f1-a9f3-2eac67176357)

**Comment by nth-chile** [comment]
Yeah, I'm getting lots of blank notes after updating

**Comment by gingerbeardman** [comment]
> I also noticed that most, but not all, of my pinned notes have been unpinned

@nth-chile please file a new issue about that one, cheers!

**Comment by glushchenko** [comment]
@nth-chile no need, pins are stored in iCloud now, unify the Mac App Store version with the GitHub version.

**Comment by gingerbeardman** [comment]
So my MAS version just updated to this 6.6.1 which still has this missing list item issue?

**Comment by gingerbeardman** [comment]
I can't tell if this is still broken or if it's a different issue #1671 

But, still impossible to use the notes list as it is mostly blank.
