### ISSUE TITLE
GitHub Sponsor

### ISSUE THREAD

**Issue by yene** [glushchenko/fsnotes#1652]
Please apply for GitHub Sponsor
so I can give you money

**Comment by gingerbeardman** [comment]
See:
- You can Patreon https://github.com/glushchenko/fsnotes/issues/798
- there used to be Sponsor button https://github.com/glushchenko/fsnotes/issues/617
- or buy the App Store versions

**Comment by glushchenko** [comment]
I used to have Patreon, but honestly, I don't feel very comfortable taking money and not being able to give anything in return. So it's better to just buy the program from the App Store, it's more than enough.

**Comment by yene** [comment]
> not being able to give anything in return

In return you have to support this app, forever. 😁
