### ISSUE TITLE
v6.6.2 including hidden json files

### ISSUE THREAD

**Issue by jackcheng** [glushchenko/fsnotes#1653]
### Description

My FSNotes folder is the same one as my Obsidian archive. In the latest version, FSNotes is picking up all the .json files in the .obsidian folder. This means that whenever I update a text file with Obsidian, those updated .json files get bumped to the top.

<img width="336" alt="Screenshot 2023-12-14 at 10 04 49 AM" src="https://github.com/glushchenko/fsnotes/assets/164722/595992b6-8e53-4c06-8be2-c3022235b685">

### To Reproduce

1. Create a hidden folder in the FSNotes folder
2. Add a .json file in the hidden folder
3. Open FS Notes

### Expected behavior

I expect those json files to be hidden, which they seemed to be in previous versions

### FSNotes version

6.6.2

### macOS/iOS version

Sonoma 14.1.2

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.6.3
