### ISSUE TITLE
Grammar Issue In error message + localization error  

### ISSUE THREAD

**Issue by theomiddleton** [glushchenko/fsnotes#1654]
### Description

When you get the popup of moving your old database to icloud, it has some grammar issues. It reads "We are detect that you are install FSNotes from Mac App Store with default storage in iCloud Drive, do you want to move old database in iCloud Drive?"
This is on [line 11304 of Localizable.xcstrings ](https://github.com/glushchenko/fsnotes/blob/d81980efd9236d3e8ac68102852576415d2b6757/FSNotes/Localizable.xcstrings#L11304) 

![image](https://github.com/glushchenko/fsnotes/assets/59509832/fad851ec-4e02-44f2-b9f0-5ad415315144)
Better wording/ proper English would something like:
"We have detected that you have installed FSNotes from Mac App Store with default storage in iCloud Drive, do you want to move old database into iCloud Drive?"
Also on the Dutch translation for this error it is in English, not Dutch. [Line 11357](https://github.com/glushchenko/fsnotes/blob/d81980efd9236d3e8ac68102852576415d2b6757/FSNotes/Localizable.xcstrings#L11357).

### To Reproduce

1. Update FSNotes with old database on drive, but have the default storage settings to be in icloud.
2. Open
3. See error

### FSNotes version

6.6.2 (605)

### macOS/iOS version

13.6.1

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.6.3
