### ISSUE TITLE
Search and create should order notes with title match first

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1656]
### Discussed in https://github.com/glushchenko/fsnotes/discussions/1655

<div type='discussions-op-text'>

<sup>Originally posted by **gal064** December 14, 2023</sup>
Pretty simple. When I search for a note, I want to first see notes that their title match my search and only then, notes where the content match my search</div>

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/commit/4e5bfcf47f4039fe50a64c02b6b0b5818a8f6fa0

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.6.3

**Comment by glushchenko** [comment]
Current implementation assume search query .startsWith(string:. I think that's good enough. But I'm open to discussion.
