### ISSUE TITLE
Encrypted folder for the same Apple Account Id devices with different passcodes

### ISSUE THREAD

**Issue by hackmajoris** [glushchenko/fsnotes#1658]
### Description

Thank you for your commitment!

I have an issue with using FSNotes on two different devices with the same iCloud account but different passcodes. I'm not quite sure at this point if it's an issue for Apple or for you guys.

### To Reproduce

1. Go to an iOS device with FaceID capability.
2. Set up encryption for a folder in FSNotes. enable FaceID.
3. Go to a macOS device with the same iCloud ID but a different passcode.
4. Try to access the encrypted folder with Touch ID on the macOS device.
5. See error.
![Screenshot 2023-12-15 at 22 09 26](https://github.com/glushchenko/fsnotes/assets/3758212/a3d91739-7c26-4dc6-a77a-7338c1a8b4c3)

(the decryption works for the master password)

### Expected behavior

The folder is decrypted

### FSNotes version

latest

### macOS/iOS version

Monterey v12.7.1(not upgraded to M3 yet)

**Comment by glushchenko** [comment]
You enter the password that encrypted the note, to decrypt the same note you must enter the password that encrypted the note.

**Comment by hackmajoris** [comment]
> You enter the password that encrypted the note, to decrypt the same note you must enter the password that encrypted the note.

Then why it work on iOS device without entering the password but just with FaceID unlock?
