### ISSUE TITLE
Embedded images mess up the preview

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#1659]
### Description

Embedded images mess up the preview. An example (taken from the notes provided with the app):

- Preview without images (OK):

    ![Screen Shot 2023-12-16 at 13 55 35](https://github.com/glushchenko/fsnotes/assets/30050534/b8657c93-ad33-4f3a-bcdc-a2be4c7fc667)

- Preview with images (look at font size and color, tags and headings):

    ![Screen Shot 2023-12-16 at 13 54 44](https://github.com/glushchenko/fsnotes/assets/30050534/29555d1a-52ff-45de-b5b6-195710579866)

### To Reproduce

1. Open any note containing images
2. Click on the Preview icon
3. See the preview

### Expected behavior

Embedded images don't mess up the note preview.

### FSNotes version

6.6.2 (605)

### macOS/iOS version

macOS 10.15

### Additional context

To my experience this affects both plain-text Markdown notes and notes using Text Bundle container format.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.6.3
