### ISSUE TITLE
Automatic pull and push doesn't work

### ISSUE THREAD

**Issue by gal064** [glushchenko/fsnotes#1660]
### Description

I have these git settings.

My understanding that the app should automatically commit and push ever 1 hour. But it doesn't happen. If I click cmd+s it does commit.

<img width="576" alt="image" src="https://github.com/glushchenko/fsnotes/assets/50427415/a9cbb655-3bb2-41ca-8fb9-e7f677ac9d9b">

### To Reproduce

Setup auto push/pull per above

### Expected behavior

Every hour, if there are changes, FSnote commits and push changes to github

### FSNotes version

6.6.2 

### macOS/iOS version

13.5 (22G74)

**Comment by glushchenko** [comment]
Not every hour. In your case:

00:05
01:05
...
23:05

**Comment by gal064** [comment]
Yeah so that doesn't happen

**Comment by glushchenko** [comment]
Are there any changes to the file system at all at the moment of auto-commit?

If there is nothing to commit, there will be no commit.

I'll be able to try and reproduce more details this weekend.

**Comment by gal064** [comment]
Yes there are changes to the file system. It works when I manually commit with cmd+save (both the commit and the push). 

What are the advantages BTW to use FSNotes git feature vs. setting up a cron job to run? I might just go that route

**Comment by glushchenko** [comment]
> Yes there are changes to the file system. It works when I manually commit with cmd+save (both the commit and the push). 
> 
> 
> 
> What are the advantages BTW to use FSNotes git feature vs. setting up a cron job to run? I might just go that route 

Settings syncs with iOS. No more advantages.

**Comment by glushchenko** [comment]
Can not reproduce it.
