### ISSUE TITLE
Search Result got bad

### ISSUE THREAD

**Issue by yene** [glushchenko/fsnotes#1661]
### Description

Did between 6.4.3 and 6.6.1 the search behaviour change?

It started to feel wrong since last updates.
For example I search "postgres" and the top result is an **older** file named "golang links" that is put before my postgres notes file.

![image](https://github.com/glushchenko/fsnotes/assets/63942/554286f3-6f6b-410f-a5f6-eecb630b5f21)

I can not provide a full reproduction steps right now, but can set one up later on a separate mac.
 

### FSNotes version

6.6.1

### macOS/iOS version

14.2

**Comment by glushchenko** [comment]
Nice catch, fixed, thank you!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.6.3
