### ISSUE TITLE
Deselecting note after syncing

### ISSUE THREAD

**Issue by fmkizz** [glushchenko/fsnotes#1663]
### Description

After updating to version 6.6.3 (macos) notes are automatically deselected after syncing. When a change is made to a note in the edit window, within a few seconds the content of the note dissappears and instead a the message 'none selected' shows up. To bring back the content, the note has to be selected again. Kind of annoying. This doesn't seem to happen when offline. Is this a bug or something that could be avoided by setting some preference?

### To Reproduce

1. Select any note in note list
2. Make change to note
3. After syncing, note is deselected

### Expected behavior

I would expect the note to stay selected, like before the update.

### FSNotes version

6.6.3

### macOS/iOS version

macos 12.7.2

**Comment by glushchenko** [comment]
What file format are you using?

**Comment by fmkizz** [comment]
Settings > general > format is set to .markdown, probably what you're referring to. Never changed that, so it must be the default setting. Looks like the above mentioned behavior doesn't occur when I change the format to .txt..

**Comment by glushchenko** [comment]
Right click on the problem note -> Show in Finder. You can see extension.

**Comment by fmkizz** [comment]
Found out it also happens with .txt format, unfortunately. Like I said, this issue was introduced after updating to the latest version (6.6.3).

**Comment by xiaofeng1986** [comment]
The same issue on me and the file name will add a number 2 in the end after deselecting , back to 6.5.0 is OK.

**Comment by glushchenko** [comment]
What if disable "Auto rename by title"?

<img width="579" alt="image" src="https://github.com/glushchenko/fsnotes/assets/1089917/9afd5b3c-be5a-4785-9e02-18b7e0b0140a">

**Comment by fmkizz** [comment]
Not sure if this entirely eliminates the issue, but it sure makes a big difference. Thanks for the useful workaround.

**Comment by glushchenko** [comment]
Fixed here:

https://github.com/glushchenko/fsnotes/releases/download/6.6.7/FSNotes_6.6.7.zip

**Comment by fmkizz** [comment]
Thnx 👍
