### ISSUE TITLE
v1.5.1 sidebar shows hidden folders

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#167]
Firstly — love the new UI! Congrats. Much fresher and up-to-date feeling, and also better UX I think eg the new size for the "search and create" field is plenty wide enough for my usage, and frees up space to view more of my notes, which is after all what I'm in the app for.

The issue: I keep my notes directory as a git repository. As a consequence of this, there's a `.git` folder in my notes directory, and the new sidebar is showing this `.git` folder and every folder it contains. Hopefully an easy fix.

<img width="106" alt="screen shot 2018-04-15 at 2 57 46 pm" src="https://user-images.githubusercontent.com/841871/38774463-d4842ae4-40bd-11e8-9bb1-4a72d703fa0d.png">

**Comment by jeff-h** [comment]
In 1.5.2 the `.git` folder is not shown, but unfortunately the subfolders of the `.git` _are_ still showing (I'm currently working on the `nv` URLs or I'd have a poke at this — happy to do so later if you like)

**Comment by glushchenko** [comment]
Please download again, fixed couple minutes ago

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/commit/368fb55424b2d1126dd946c8b9f8678dc332f82c

**Comment by jeff-h** [comment]
Fixed indeed :)
