### ISSUE TITLE
Blank items in FSNotes macOS list when note is created on iOS

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1671]
### Description

I'm seeing blank items in the latest version 6.6.3 (607) Mac App Store.

These seem to be notes that I created on iOS and have not edited on macOS.

But there are other notes that have existed for a long time that no do not have list item previews.

Editing the note on macOS creates the preview.

16 notes affected in my setup.

### Screenshot

This shows a set of blank items. The top two I edited to get the preview to appear.

![image](https://github.com/glushchenko/fsnotes/assets/49612/4ed00b1d-4b35-40a3-953c-abb2a9be2a3e)

### To Reproduce

1. Create note on FSNotes iOS
2. Let it sync to iCloud
3. Open FSNotes macOS
4. Notice blank items in list
5. Click note to verify contents
6. Edit note to cause list item to show something

### Expected behavior

- there should always be a preview list item for every note

### FSNotes version

- 6.6.3 (607)

### macOS/iOS version

- 12.7.2

### Additional context

- reset cache does not help

Related: #1651

**Comment by glushchenko** [comment]
Finally i found the problem!

https://github.com/glushchenko/fsnotes/releases/tag/6.6.4

**Comment by gingerbeardman** [comment]
1. was still bad
2. Reset Caches
3. works OK!

**Comment by glushchenko** [comment]
@gingerbeardman seems i found why this is not reproducible for me. Did you enable "Hide images preview" option in the settings? In this case not all data loaded.

<img width="662" alt="image" src="https://github.com/glushchenko/fsnotes/assets/1089917/4ebbf217-2c13-4ddf-a11c-643d02c6fb89">

**Comment by gingerbeardman** [comment]
Yes, I have "hide images preview" = checked

**Comment by glushchenko** [comment]
Its about notes list, when note contains image:

<img width="323" alt="image" src="https://github.com/glushchenko/fsnotes/assets/1089917/09ebf8f7-811a-4420-ae26-03dfc7be2906">

But this fixed too, here https://github.com/glushchenko/fsnotes/releases/download/6.6.5/FSNotes_6.6.5.zip

Sorry for inconveniences 🙏
