### ISSUE TITLE
Cannot create a folder/project once all projects have been removed

### ISSUE THREAD

**Issue by radionoise** [glushchenko/fsnotes#1672]
### Description

Once all folders/projects have been removed it's not possible to create a new folder/project anymore even by using a Shift-Option-N shortcut.

### To Reproduce

1. Install the fresh version
2. Remove the Welcome folder/project
3. Try to create a new folder/project in the UI or by using a Shift-Option-N shortcut
4. Nothing happens

### FSNotes version

6.6.3 (607)

### macOS/iOS version

13.6.3

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.6.4
