### ISSUE TITLE
⌘+ and ⌘- conflicts at German keyboard layout

### ISSUE THREAD

**Issue by schwantuschke** [glushchenko/fsnotes#1675]
### Description

The new feature for increase/decrease font size with ⌘+ and ⌘- works on German keyboard with the keys ß and ´. This keys are in position of + and - with English layout.
Now I can't use the preview with ⌘ß :(

### To Reproduce

Switch preview with ⌘ß with English keyboard layout.

### FSNotes version

6.6.4

### macOS/iOS version

macOS 14.2.1

**Comment by glushchenko** [comment]
@nth-chile

**Comment by nth-chile** [comment]
@schwantuschke When other apps use these +/- for zoom, how does that work on a German keyboard? These are the keycodes I used: `kVK_ANSI_Equal` for plus, and `kVK_ANSI_Minus` for minus.

I'll do some research

**Comment by schwantuschke** [comment]
In other apps I use the + and - at its position on German keyboard layout.

**Comment by nth-chile** [comment]
When I change my keyboard to German, the zoom still works for me for some reason, so I don't know if I am able to test properly. But I made a code change that may fix the issue. Are you able to test a PR?

**Comment by nth-chile** [comment]
Hang on ... I have too many commits in that PR

**Comment by nth-chile** [comment]
Wait, it won't work because "+" and "=" are on separate keys in German layout. So I need to detect language first.

**Comment by glushchenko** [comment]
@schwantuschke sorry for inconveniences, please check new release:

https://github.com/glushchenko/fsnotes/releases/download/6.6.5/FSNotes_6.6.5.zip

**Comment by schwantuschke** [comment]
Now it's working. Thank you @glushchenko and @nth-chile for quick fix ❤️
