### ISSUE TITLE
New zoom options mask other functions

### ISSUE THREAD

**Issue by chrissexton** [glushchenko/fsnotes#1679]
### Description

When not on a qwerty layout, the new `⌘+` and `⌘-` shortcuts seem to be tied to the physical key instead of the layout. They also ignore other modifiers. This means that `⌘⬆[` and `⌘⬆]` get masked on Dvorak and change font size instead of going back and forward. Same for `⌘[` and `⌘]` getting converted to the zoom functions. For reference, zoom should be tied to the `=` and `-` keys for Dvorak users.

### To Reproduce

1. Go to a note
2. Ensure your operating system keyboard layout is set to Dvorak
3. Attempt to move forward or backward by one note
4. See your text change size

### Expected behavior

1. Go to a note
2. Ensure your operating system keyboard layout is set to Dvorak
3. Attempt to move forward or backward by one note
4. See the note previous or forward in history

### FSNotes version

6.6.4 (608)

### macOS/iOS version

14.2

**Comment by glushchenko** [comment]
Fixed in 6.6.5
