### ISSUE TITLE
Cursor jumps to the beginning of the Note

### ISSUE THREAD

**Issue by nburyak** [glushchenko/fsnotes#1683]
### Description

The cursor jumps to the beginning of the Note every time, when the title of the Note gets updated

### To Reproduce

1. Create new Note
2. Start typing the text
Actual Result: Every time, when the title of the Note gets updated, the cursor jumps to the beginning of the Note

https://github.com/glushchenko/fsnotes/assets/2462403/d121acfa-2f93-4060-8774-fad46d6c00d3

### Expected behavior

The cursor should never be automatically moved during typing

### FSNotes version

Version 6.6.6 (610) - (AppStore version)

### macOS/iOS version

macOS 14.2.1 (23C71)

**Comment by glushchenko** [comment]
Try to change storage path to path without emoji.

**Comment by nburyak** [comment]
Unfortunately, neither changing the location to default (which was actually set), nor removing the  emojis in the path didn‘t help. Let me debug, maybe I‘ll find the rootcause

**Comment by nburyak** [comment]
I've debugged the code and figured out the following: while typing the text the Note gets reloaded and the cursor changes its position to 0 or previously saved depending on the `restoreCursorPosition`. I assume, this happens every time when the Note is saved to the file.

Here's the stack trace and the exact place of code, which causes cursor jumping during typing:
<img width="1323" alt="image" src="https://github.com/glushchenko/fsnotes/assets/2462403/0e92084e-7265-43d3-91ce-963f9746d36f">

**Comment by nburyak** [comment]
As long, as the whole `restoreCursorPosition` is triggered by `event.fileChange`, would it be correct to assume, that it's somehow related to the iCloud sync of the files?

**Comment by nburyak** [comment]
I have a suspicion, the issue is related to the iCloud backup. Once I moved the Notes Storage outside of the iCloud folder, the issue was gone. Obviously, it doesn't help much because I want to sync my notes with the mobile phone. But this narrows down the problem

**Comment by glushchenko** [comment]
What about this option in the Settings? Did you try to enable it?

<img width="218" alt="image" src="https://github.com/glushchenko/fsnotes/assets/1089917/10e14324-e678-4b62-a72b-63fe4dc4ef58">

**Comment by nburyak** [comment]
> What about this option in the Settings? Did you try to enable it?
> 
> <img alt="image" width="218" src="https://private-user-images.githubusercontent.com/1089917/299828283-10e14324-e678-4b62-a72b-63fe4dc4ef58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjIzNzUsIm5iZiI6MTcwNjI2MjA3NSwicGF0aCI6Ii8xMDg5OTE3LzI5OTgyODI4My0xMGUxNDMyNC1lNjc4LTRiNjItYTcyYi02M2ZlNGRjNGVmNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMDk0MTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlhMzI0ZjZlMmRhZjljY2NkZmUxOWFkYWQ2OGY1MGQwOTZkMmYxNmM3ZWJlMGY3ZDljMDMxNTE1NDIwM2MyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-ewHIKMj9v1WvVDb4SR5ik6YyhsPe0cI5c5XsQQnQaM">



https://github.com/glushchenko/fsnotes/assets/2462403/f53d590e-05b0-4270-a3fd-63cb14144e94

With the `Restore cursor position` setting ON the cursor jumps a few symbols to the right, which is even worse, than jumping to the beginning of the Note.

I've posted the logs above: the cursor position in the `func restoreCursorPosition()` isn't same, as the last saved value in `func saveCursorPosition()`. It's definitely related to the iCloud sync but I can't find out how to fix this.

**Comment by glushchenko** [comment]
@nburyak please check this experimental build:

[FSNotes_6.6.7.zip](https://github.com/glushchenko/fsnotes/files/14069667/FSNotes_6.6.7.zip)

**Comment by nburyak** [comment]
Hi @glushchenko, thanks for the fix. I've just tested it - works much better now and doesn't mess with the text anymore 👍

Although, you may still notice a small glitch: in the word `fixedI` I type the `x` character, then it disappears and re-appears again. I'd consider it a minor issue.

https://github.com/glushchenko/fsnotes/assets/2462403/45bbebe9-8436-4b4d-857f-5713ffcb4a92

**Comment by glushchenko** [comment]
OK, another try. Please test it and let me know.

[FSNotes_6.6.7.zip](https://github.com/glushchenko/fsnotes/files/14117247/FSNotes_6.6.7.zip)

**Comment by nburyak** [comment]
@glushchenko Thanks for the build - I can confirm, that in the latest build the issue is completely gone ✅

**Comment by glushchenko** [comment]
> Is this fix planned for any of the upcoming AppStore releases?

Yes

**Comment by glushchenko** [comment]
Fixed here:

https://github.com/glushchenko/fsnotes/releases/download/6.6.7/FSNotes_6.6.7.zip
