### ISSUE TITLE
FSNotes manual

### ISSUE THREAD

**Issue by xxxAleksandrxxx** [glushchenko/fsnotes#1684]
### Description

Hi!
Thank you for the app!
I am a new user and now trying to switch from Obsidian to FSNotes. I've read your wiki page https://github.com/glushchenko/fsnotes/wiki/Backup-&-Versioning-of-Notes
but still don't understand what are 
- inbox
- notes
- todo
How do I control them (rename, delete, create new one)? How to create folder-in-folder structure and so on?
Could you share more detailed user manual for those who just started to use this application and don't understand probably well-known intuitive things. 

Best regards

### FSNotes version

6.2.2 build 277

### macOS/iOS version

iOS

**Comment by gingerbeardman** [comment]
These standard are filters and should be discoverable through small amount of use:

Inbox = all notes that are not in any folders
Notes = all notes across all folders
Todo = all notes containing todo items (Format > Toggle Todo)

You cannot create or rename them, but you can avoid using them and hide them (View > Show in Sidebar)

To create new filters use folders (Library > Create Folder) or tags (type # followed by tag name)

Folder-in-folder structure is not currently supported. Tags may be an alternative.

**Comment by xxxAleksandrxxx** [comment]
Thank you!

**Comment by xxxAleksandrxxx** [comment]
Hi!
Am I correct that MacOS version of FSNotes supports nested folders while iOS version doesn't?

**Comment by gingerbeardman** [comment]
@xxxAleksandrxxx yes, macOS version gained this in the most recent version. iOS version needs to catch up soon.
