### ISSUE TITLE
Git error: Unable to save index -14 the index is locked; this might be due to a concurrent or crashed process

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1685]
### Description

When I press `CMD` + `S`, an alert says `Git error: Unable to save index -14 the index is locked; this might be due to a concurrent or crashed process`. When I go to the repo and do `git status`, terminal says:

```
fatal: Unable to create '/Users/jared/Library/Containers/co.fluder.FSNotes/Data/Library/Application Support/Repositories/abc7 - Fsnotes.git/./index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

Deleting `index.lock` fixed the issue

### To Reproduce

I'm not sure, but sometimes these git errors happen by pressing `CMD` + `S` repeatedly

### FSNotes version

6.6.5 (609)

### macOS/iOS version

14.1.2 (23B92)

**Comment by glushchenko** [comment]
This is not related to FSNotes app.

https://stackoverflow.com/questions/23229404/libgit2sharp-the-index-is-locked-error
