### ISSUE TITLE
Attempting to Git Clone results in App Crash

### ISSUE THREAD

**Issue by James-Firth** [glushchenko/fsnotes#1686]
### Description

I attempted to set up a git repository via github, and every time I've tried it crashes the app entirely.

### To Reproduce

1. Open FS Notes
2. Click on FS Notes in the menubar
3. Click on Settings...
4. Click on the Git tab
5. Set the private key under "Git repository"
6. Set origin for main project
7. Click "Clone/push" button
8. Note brief spinner
9. MacOS crash report dialog appears

<img width="585" alt="image" src="https://github.com/glushchenko/fsnotes/assets/485809/0e634c80-fe01-49e7-b661-9fbeb0894d67">

### Expected behavior

To be prompted to clone the private github repo to my local machine. (This is my 2nd time launching the app so I updated to the latest version, I've never used this feature so this is just what I presume would happen)

### FSNotes version

Version 6.6.6 (610) - installed via GitHub Releases

### macOS/iOS version

macOS Sonoma 14.3 (23D56)

### Additional context

From the dialog

```
[...]
Crashed Thread:        5  Dispatch queue: NSOperationQueue 0x1581e6c30 (QOS: UNSPECIFIED)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Exception Codes:       0x0000000000000001, 0xfffffffffffffff8

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [16241]

VM Region Info: 0xfffffffffffffff8 is not in any region. [...]
```

**Comment by glushchenko** [comment]
This question should be addressed not to me, FSNotes uses https://github.com/libgit2/libgit2
