### ISSUE TITLE
Option to Minimise the Repos folder in the IpadOS app

### ISSUE THREAD

**Issue by hasantahir** [glushchenko/fsnotes#1687]
**Describe your feature request**

In the MacOS app, one can minimise the Repos folders in the Sidebar. However, this is not possible in the iPadOS app. After messing up with my git repo, I have several folders showing up in the Repos section:
<img width="834" alt="Screenshot 2024-01-29 at 15 21 40 jpeg" src="https://github.com/glushchenko/fsnotes/assets/11236148/67ff8da5-e172-42a3-bb40-09874afee989">

On the Mac version, I can hide the Repos:
<img width="165" alt="image" src="https://github.com/glushchenko/fsnotes/assets/11236148/286c9459-1fef-42bd-989f-85903d912cc7">

**Additional context**
I am on versions on 6.2.2 (ipadOS) and 6.6.6 (macos)

**Comment by glushchenko** [comment]
Dupe https://github.com/glushchenko/fsnotes/issues/1208
