### ISSUE TITLE
Brackets followed by brackets make all brackets gray

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1688]
### Description

Bracket pair immediately followed by another bracket pair causes all brackets in line to turn grey

<img width="571" alt="Screenshot 2024-01-30 at 10 49 45 PM" src="https://github.com/glushchenko/fsnotes/assets/22358233/02fcde8e-4d95-4793-b054-2762c2cb5a1b">

### To Reproduce

1. Type "[] []"
2. On next line, type "[] test []"
3. First line has grey brackets

### Expected behavior

Brackets should only be grey if you're making a markdown link or footnote or something.

### FSNotes version

Version 6.6.5 (609)

### macOS/iOS version

14.1.2 (23B92)

**Comment by glushchenko** [comment]
Released: https://github.com/glushchenko/fsnotes/releases/download/6.9.2/FSNotes_6.9.2.zip
