### ISSUE TITLE
Ability to access `all notes` as on desktop app

### ISSUE THREAD

**Issue by spenat28** [glushchenko/fsnotes#1689]
**Describe your feature request**

I would like to have same behavior on both: desktop and mobile.

It means: ability to access `root folder` to display all notes i have.

**Additional context**

I am using it daily for more than 2 years now?
When nested folders were introduced and Inbox, etc. added, `All notes` was removed for some reason, but not entirely (i am glad) - i am almost always in mode where i view complete list of notes.

On desktop - i can access it by pressing `ESC` in search bar. Since i am using `ESC` everywhere all the time, i always end up there ...

So: i am would like to see same list on iOS when i open my notes, but i didn't find any way how to get there. `Inbox` is always active and cannot be "deselected" - to skip above to root to view all notes.

I assume, this could be rather small change - and even better if it's optional eq. `Display root folder in menu: true|false` and it would make my life easier ...

**PS**

❤️ i love this app (i was using nvALT before for 8 years or so), thanks for work you are doing

**Comment by spenat28** [comment]
Maybe related to: https://github.com/glushchenko/fsnotes/issues/1208

**Comment by spenat28** [comment]
Man. That's why it's "request" ... i know it's not there, and you are right also - what we need.

(Disclaimer; i am a dev.)

**Comment by glushchenko** [comment]
Added in 6.5.0 for iOS
