### ISSUE TITLE
sidebar: how to add root folders?

### ISSUE THREAD

**Issue by aseygo** [glushchenko/fsnotes#169]
love the new sidebar and subfolder support. great!

maybe i'm just too stupid, how can I add/change root document folders? (what previously was done in the preferences).

**Comment by glushchenko** [comment]
Hover mouse on Library in Sidebar and click "+"

**Comment by aseygo** [comment]
ok, me too stupid. thanks a lot.

**Comment by glushchenko** [comment]
All ok, i should add option in menu ;)
