### ISSUE TITLE
Drag and drop URL from Browser to create Link

### ISSUE THREAD

**Issue by juliaanvaneijndt** [glushchenko/fsnotes#1691]
**Describe your feature request**
Most browser allow to drag and drop a shortcut link to a website straight to the desktop from the address bar.
Textedit convert this directly to a link, which is very useful when writing notes while browsing.
Do you think something similar could be implemented in FSnotes ?

**Additional context**
macOS

**Comment by eyelessjerry** [comment]
The ONLY reason to use FSNotes (for me) is that links are not converted to clickable links! The only reason I got FSNotes is because it is the only Notes app that can handle links in a professional and helpful manner. Worst suggestion I have ever heard of in my life.

**Comment by juliaanvaneijndt** [comment]
I wouldn't want you to lose any sleep... But perhaps you've been reading too fast. The suggestion was mainly about being able to drag and drop url's from a browser. Converting them into clickable links isn't absolutely essential (even though I'm one of those freaks who would find that handy in a note-taking application).

**Comment by eyelessjerry** [comment]
Alright, thanks for the comforting words! Focussed a bit too much on the second part. Dragging links in would be helpful for sure. Think FSNotes is ideal for an independent URL manager from where you can open links in different browsers across iOS and macOS. I see now that the links becomes clickable in the iOS app (not too much a problem there though) and I wonder if you can’t do that already in the macOS app too by changing the format or using markup. Anyway, main point with FSNotes is that it is the only app that can sync notes as non-formatted text.

**Comment by eyelessjerry** [comment]
Hi, I see now that to make links clickable you just choose to do so in Settings! 'Clickable links' it is called under the Editor settings. Now if there only was such a setting in the iOS app to make them non-clickable, but less of a problem. My best tip otherwise with links is that you can drag two or more links at once from FSNotes to the tab bar in Safari to open both links at once in the browser!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.7.0
