### ISSUE TITLE
Table Of Content (created using {{TOC}}) links don't work in some cases 

### ISSUE THREAD

**Issue by dmrlx** [glushchenko/fsnotes#1692]
### Description

Table Of Content (created using {{TOC}}) links don't work in some cases and open strange windows instead of following the link.

<img width="934" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/0a2a308c-f0ac-47e8-85da-c7a4b525db40">

### To Reproduce

1. Create new note
2. Place following structure there

```plaintext
# Header

## New 1

## New 2
```

3. Place `{{TOC}}` instruction after 1st level header

```plaintext
# Header

{{TOC}}

## New 1

## New 2
```

4. Toggle preview (⌘+/)

5. Click to any 2nd level link

6.
<img width="934" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/6d659dd4-064a-4e6e-837f-fe9b8a50fd63">

### Expected behavior

A jump to the appropriate header is expected to occur

### FSNotes version

Version 6.6.7 (614) from store

### macOS/iOS version

macOS 14.2.1

**Comment by glushchenko** [comment]
Thank you for detailed bug report, will be fixed ASAP.

**Comment by glushchenko** [comment]
Fixed here: https://github.com/glushchenko/fsnotes/releases/download/6.6.8/FSNotes_6.6.8.zip
