### ISSUE TITLE
Renaming a directory may result in strange behaviour

### ISSUE THREAD

**Issue by dmrlx** [glushchenko/fsnotes#1693]
### Description

Renaming a directory may result in duplicate directories at first, and after closing and opening the app, they won't show up, although they will be visible in iCloud

### To Reproduce

1. Create top level directory, e.g. "Test"
2. Create another directory inside, e.g. "New folder"

<img width="252" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/eb9f4e72-45f3-41b0-b40f-12d7ae390d62">

<img width="227" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/f6cf278b-4736-458b-90c2-4fba53ac84a6">

3. Rename directory to "New Folder"

<img width="307" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/3e413678-fcc8-4219-9bf5-0138b08f1f10">

<img width="231" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/2e71d4d2-074f-4fee-bebf-a9e59d4656cd">

4. Folder was duplicated

<img width="226" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/d75fc031-0cf0-463b-ad44-f0a96f6689b4">

In iCloud (obviously) we have only one dir

<img width="154" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/6c89e5e1-77e3-4c68-80b6-e22305d9905b">

5. Close fsnotes app and open again. The "Test" dir is empty

<img width="211" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/47566298-4285-46d1-9398-95f4668cd532">

But "New Folder" dir exists in iCloud

<img width="153" alt="image" src="https://github.com/glushchenko/fsnotes/assets/7214773/91afad1f-1e81-4e01-bce4-1a916d5cc044">

### FSNotes version

Version 6.6.7 (614)

### macOS/iOS version

macOS 14.2.1 (23C71)

**Comment by glushchenko** [comment]
Can you reliable reproduce it? Me not.

**Comment by dmrlx** [comment]
Yes, I can. I'd say close to 100% of the time.

**Comment by dmrlx** [comment]
Reproduced the same issue on personal mac (M1 Pro) and 14.3 (23D56)

**Comment by glushchenko** [comment]
Nice catch! Reproduced. Will be fixed ASAP.

**Comment by glushchenko** [comment]
Please check this: https://github.com/glushchenko/fsnotes/releases/download/6.6.8/FSNotes_6.6.8.zip

**Comment by glushchenko** [comment]
Case sensitive renaming is disabled (no more "a" to "A" renaming). You can rename from "a" to "b" and then "b" to "A". This is  a cheap technical solution.

**Comment by dmrlx** [comment]
Is it temporary “cheap technical solution”?

**Comment by glushchenko** [comment]
APFS is case insensitive by default, so there's no reason to implement this. So no, this is a permanent solution.
