### ISSUE TITLE
The same dirs structure looks different in macOS and iOS apps

### ISSUE THREAD

**Issue by dmrlx** [glushchenko/fsnotes#1694]
### Description

The same dirs structure looks different in macOS and iOS apps.

### To Reproduce

1. Install masOS app
2. Create dirs / files structure
3. Sync everything using iCloud
4. Install iOS app

<img width="234" alt="SCR-20240209-kpvc" src="https://github.com/glushchenko/fsnotes/assets/7214773/1c69120b-9b80-4b89-bc2a-ae8d681c8bf0">

![IMG_6103](https://github.com/glushchenko/fsnotes/assets/7214773/ba80a4a1-73a8-4acc-8bb3-75d0c1578e6c)

### FSNotes version

macOS 6.6.7 (614), iOS 6.2.2 (277)

### macOS/iOS version

macOS 14.3 (23D56), iOS 17.3.1

**Comment by dmrlx** [comment]
And in general some weird problems in syncing notes between phone and laptop. Create a note on the phone, add a photo from the gallery, everything is OK on the phone, but on the computer the photo is visible in edit mode, but not visible in view mode. 🤯

**Comment by glushchenko** [comment]
> And in general some weird problems in syncing notes between phone and laptop. Create a note on the phone, add a photo from the gallery, everything is OK on the phone, but on the computer the photo is visible in edit mode, but not visible in view mode. 🤯

Fixed here: https://github.com/glushchenko/fsnotes/releases/download/6.6.8/FSNotes_6.6.8.zip
