### ISSUE TITLE
Vision OS support

### ISSUE THREAD

**Issue by gigq** [glushchenko/fsnotes#1695]
Curios why the ipad app isn't available on VisionOS. I compiled it in xcode and it seems to work fine.

**Comment by glushchenko** [comment]
Are there any visionOS users here?

**Comment by gigq** [comment]
At least one, I just figured since it runs fine why opt out.

**Comment by gingerbeardman** [comment]
You say it "seems" to run fine...how much did you check? 

Are you already familiar with FSNotes user on iOS to MacOS? Then we can give you suitable guidance for testing. 

It's risky to release software on a platform it difficult or impossible for it to be tested on. Apple Vision Pro is currently USA-only, right?

**Comment by gigq** [comment]
I currently use it on Mac and iOS, honestly if there is no interest outside of one user I don't blame you. Since it's open source I can just run my own build on it. Being open source is one of the main reason I chose FSNotes honestly. Feel free to close this ticket if there are no plans to support it. Just wanted an official stance on it before I went off running my own build.

**Comment by glushchenko** [comment]
@gigq 

I'm just glad you were able to run FSNotes on visionOS.

But I just can't test it in Ukraine yet. Maybe later I'll make a build.

If not difficult, it will be interesting to hear about your experience after a couple of weeks.

Thank you!
