### ISSUE TITLE
When you change the title of a note, you lose access to the history

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1698]
### Description

When you change the title of a note, you lose access to the history

### To Reproduce

1. Create note called "Test 1"
2. Save
3. Edit note without changing title
4. Save
5. Right click on note in note list, see two history items
6. Edit title of note
7. Save
8. History items are gone

### FSNotes version

Version 6.6.5 (609)

### macOS/iOS version

14.1.2 (23B92)

**Comment by glushchenko** [comment]
That's the way it's designed, I'm not going to do it
