### ISSUE TITLE
[REQ] Allow selecting font and size for code blocks

### ISSUE THREAD

**Issue by eddyg** [glushchenko/fsnotes#170]
It would be great to be able to specify the font and size used in code blocks.

I use a condensed monospace font ([Essential Pragmata Pro](https://www.myfonts.com/fonts/fsd/essential-pragmata-pro/)) for my notes, and currently the code blocks "stand out" because they are big/wide:

![screen shot 2018-04-16 at 12 46 11](https://user-images.githubusercontent.com/3235109/38823664-f776cc02-4174-11e8-90d5-63f93de51968.png)

**Comment by glushchenko** [comment]
Release in FSNotes v3
