### ISSUE TITLE
Note gets overwritten by old version

### ISSUE THREAD

**Issue by nth-chile** [glushchenko/fsnotes#1700]
### Description

On iOS app, when I see that it's displaying an older version of a note, I usually tap to view a different one, and then go back to the first one and that makes it load the new version. But if I accidentally start editing before doing that, it updates iCloud and thus the newest version (updated at an earlier time via desktop app) is lost

### To Reproduce

1. Open a note on iOS and then minimize the app/send to background 
2. On desktop, edit that note
3. Open the iOS app and it will show the old version of the note. Start typing
4. New note is gone

These steps might not be perfect, but I'm not home right now to test

### Expected behavior

I can think of a few solutions, but ideally we can prevent the user from editing a note that is not synced

### FSNotes version

(iOS) 6.2.3

### macOS/iOS version

17.3.1

**Comment by glushchenko** [comment]
Settings -> General -> Automatic iCloud Drive conflicts resolution

**Comment by nth-chile** [comment]
Now that I've done that, on desktop app notes get duplicated on autosave
