### ISSUE TITLE
Won't open any content on 17.4 beta

### ISSUE THREAD

**Issue by gliush** [glushchenko/fsnotes#1702]
### Description

Hello.

I'm not sure if this is related to my beta version of iOS or not.
I have quite a lot of notes there, I configured iCloud sync, and on my MacOS it works fine.

While it doesn't work on iOS: it shows the empty welcome page (white page with a logo in the center) for some time and then exits.

Long tap and using any item from it won't help either.

### To Reproduce

1. Click the app icon on iOS
2. See the white page
3. It hangs for ~8 seconds and then exits

### Expected behavior

I expect it to start and show the notes.

### FSNotes version

Probably, 6.2.3, I cannot check it from the App, while the AppStore doesn't suggest to update it and shows the 6.2.3 there.

### macOS/iOS version

iOS-17.4, macOS-14.2.1

### Additional context

I'm not sure about FSNotes version, probably, 6.2.3.
I cannot check it from the App as I cannot start it.
The AppStore doesn't suggest to update it and shows the 6.2.3.

**Comment by glushchenko** [comment]
Try to move all notes outside of storage and run it again.

**Comment by gliush** [comment]
Do you mean to move it in the app on MacOS? Or do you mean move the files in the "Files.app" on iOS?

**Comment by glushchenko** [comment]
Where doesn't it work? In iOS? Move all files out of storage and try running the app.
