### ISSUE TITLE
iOS app continues to freeze when iCloud files offloaded

### ISSUE THREAD

**Issue by bradydjohnson** [glushchenko/fsnotes#1704]
### Description

When I open the iOS app, it never shows my notes, and only shows the FSNotes icon. 

![IMG_7671](https://github.com/glushchenko/fsnotes/assets/6741590/01004c6d-355a-4da6-ae14-5fd9bfe82f30)

It appears to be related to when iCloud Drive offloads files within the FSNotes folder. If I force iCloud Drive to download all files in that folder, the app will open successfully. Invariably, in a few days, iCloud Drive will offload some of those files again (even though I have 10-20GB of free space on my iPhone!), and then the app won’t open again. It appears like there is no setting to prevent iCloud from offloading files.  

![IMG_7673](https://github.com/glushchenko/fsnotes/assets/6741590/6058eab7-2454-4c6d-9876-b6da1a5b4440)
![IMG_7672](https://github.com/glushchenko/fsnotes/assets/6741590/c0615a21-32a5-4e4c-93e5-35189d5dbc4c)

There was a similar issue (#1601) that is now closed. 

Is there another way to save files to iCloud that prevents offloading?

### To Reproduce

1. Ensure some of the notes in the FSNotes folder within iCloud Drive are offloaded
2. Open FSNotes app

### FSNotes version

6.2.3

### macOS/iOS version

17.3.1

**Comment by glushchenko** [comment]
I can't reproduce this and fix it, sorry.
