### ISSUE TITLE
Syncing notes via iCloud when not on Wi-Fi?

### ISSUE THREAD

**Issue by eyelessjerry** [glushchenko/fsnotes#1705]
**Describe your feature request**
I would want notes to sync when using mobile data and not only when using Wi-Fi. It seems not to work (at least not today when I tested). Syncing worked again as soon as I connected to Wi-Fi.

**Additional context**
Restarted the app etc. but could not get notes to sync while on Mobile data (and, yes, it is turned on on the iPhone).

**Comment by glushchenko** [comment]
No any problems with sync on 3G/LTE. You may have data saving enabled or low power mode, please check.
