### ISSUE TITLE
iOS - note shows like duplicated right after creating 

### ISSUE THREAD

**Issue by xxxAleksandrxxx** [glushchenko/fsnotes#1707]
### Description

Created new now note, switched view, closed the note and the app shows two of them in the folder. But in the reality Files app shows that there is only one note with such name in the folder.

[Video demo](https://we.tl/t-CCX1W8KGOJ)

### To Reproduce

Better to check video
But in text it is like:
- create new note
- write something 
- switch to view mode
- close note 
- now the app shows two notes but if you check folder with File app, you will see only one file.

### FSNotes version

6.2.3

### macOS/iOS version

iOS

**Comment by glushchenko** [comment]
Can not reproduce it
