### ISSUE TITLE
Igore dot directories

### ISSUE THREAD

**Issue by pdxmph** [glushchenko/fsnotes#1710]
Not sure if "feature" or "bug." Opinions will vary

**Describe your feature request**
I'd like FSNotes to ignore hidden `.files` in note directories. 

**Additional context**
I use Syncthing to sync, and I version my Syncthing stuff so I know I can recover from conflicts. Syncthing makes a `.stfolder` and `.stversions` folder in each shared directory. FSNotes picks these up, then treats versions as if they're legitimate notes. 

Ignoring dot files would be more in keeping with how they tend to operate in other applications. 

Fix for anyone dealing with this: You can at least tell Syncthing to store versions in a folder outside the shared one, which removes the duplicate content problem.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.7.0
