### ISSUE TITLE
Emphasis which is not flanked by whitespaces doesn't work on editor view

### ISSUE THREAD

**Issue by Stauboid** [glushchenko/fsnotes#1718]
### Description

Emphasis such as `fan*tas*tic` or `fan**tas**tic` don't show themselves as italicized/boldened (as `fan*tas*tic` or `fan**tas**tic`), if you turn the preview off.
If your turn the preview on, then you see them correctly emphasized (as fan*tas*tic or fan**tas**tic). This latter behaviour conforms to commonmark.js dingus (https://spec.commonmark.org/dingus/?text=fan*tas*tic%0A%0Afan**tas**tic).

### To Reproduce

1. Create new file
2. Type `fan*tas*tic`

### FSNotes version

Version 6.7.0 (618)

### macOS/iOS version

13.6.6

### Additional context

In european languages, emphasis which aren't flanked by whitespaces are often called "intraword emphasises" and are rare cases. But in asian languages they are common (often not "intraword").

**Comment by glushchenko** [comment]
Released: https://github.com/glushchenko/fsnotes/releases/download/6.9.2/FSNotes_6.9.2.zip
