### ISSUE TITLE
pressing enter for new line creates new line but moves caret back to end of current line

### ISSUE THREAD

**Issue by pablo-esteban** [glushchenko/fsnotes#1721]
### Description

when i type something, and then decide to create a new line by pressing enter, the caret jumps to the new line and back to the end of the line i was just typing. by explicitly moving the caret with the down key i see that the new line was created.

there seems to be a problem of the caret jumpint to strange locations when typing

### To Reproduce

1. start typing and then press enter 

### Expected behavior

the caret should be at the begining of the new line, but it is at the end of the line when the enter button was pressed

### FSNotes version

6.7.0 (618)

### macOS/iOS version

sonoma 14.4.1

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/issues/1701

**Comment by svladek** [comment]
Happens to me on Macosx 14.4.1 and latest : 6.7.1 (672). Same behavior

**Comment by glushchenko** [comment]
Fixed here https://github.com/glushchenko/fsnotes/releases/tag/6.8.2
