### ISSUE TITLE
MathJax formatting issue

### ISSUE THREAD

**Issue by tryonkus** [glushchenko/fsnotes#1723]
### Description

I was just playing with the MathJax example note and changed the last bit to this (double dollar signs around the first equation):

```
## MathJax example

Documentation: https://www.mathjax.org

> Please choose: View > Preview MathJax

When $$((a \ne 0))$$, there are two solutions to $$ax^2 + bx + c = 0$$ and they are
$$x = \{-b \pm \sqrt{b^2-4ac} \over 2a\}.$$
```

When it rendered, the 2a at the bottom was partially cut off (see screen grab below):

<img width="452" alt="MathJax formatting bug" src="https://github.com/glushchenko/fsnotes/assets/167592851/6b1b6399-9d0d-4013-988b-930a54256ea9">

When I entered just the equation text into a new note, it rendered correctly.

### To Reproduce

Edit text as described above 

### Expected behavior

Full equation should be rendered

### FSNotes version

6

### macOS/iOS version

14.4.1

**Comment by tryonkus** [comment]
# 6. Mermaid and MathJax

## Mermaid example

Documentation: https://mermaidjs.github.io

```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```

## MathJax example

Documentation: https://www.mathjax.org

> Please choose: View > Preview MathJax

When $$((a \ne 0))$$, there are two solutions to $$ax^2 + bx + c = 0$$ and they are
$$x = \{-b \pm \sqrt{b^2-4ac} \over 2a\}.$$

**Comment by tryonkus** [comment]
The costs are $40 dollars and $30 dollars.

**Comment by tryonkus** [comment]
Not any criticism here—I just like playing with new software, and I'm good at breaking stuff. My nephew is a software tester, and I may have missed my calling (I'm in IT support and admin).

**Comment by glushchenko** [comment]
> If I type
> 
> 
> 
> The costs are $40 dollars and $30 dollars.
> 
> 
> 
> it renders as
> 
> 
> 
> <img width="260" alt="Screenshot 2024-04-20 at 6 21 06 PM" src="https://github.com/glushchenko/fsnotes/assets/167592851/6d0589ae-2ac8-4867-a86d-f7a754845567">
> 
> 

Yes.

Believe me, I know a lot more FSNotes problems, and not just in the parser. Pull requests would be much more useful, but no.

**Comment by tryonkus** [comment]
If I were a programmer, I’d be happy to dive in and debug. Sadly, I’m better at finding bugs than fixing them.  I think it’s a great app, and I’m pushing some of the more obscure features.

**Comment by glushchenko** [comment]
> If I were a programmer, I’d be happy to dive in and debug. Sadly, I’m better at finding bugs than fixing them. I think it’s a great app, and I’m pushing some of the more obscure features.

I am aircraft engines engineer, but occasionally i write the code. If you have ideas on how to improve the code, welcome to pull requests.

Thanks for the feedback, but i can't devote any more time to this task, sorry.
