### ISSUE TITLE
Syntax highlighting is not updated when language is changed

### ISSUE THREAD

**Issue by thommeo** [glushchenko/fsnotes#1725]
### Description

Syntax highlighting is not updated when language is changed

### To Reproduce

1. Create new note
2. Add code block with language "javascript"

<img width="1035" alt="image" src="https://github.com/glushchenko/fsnotes/assets/598840/7d5b5c33-6103-4995-8e58-35af301e1846">

3. Change language to bash. Observe syntax highlighting unchanged

<img width="1033" alt="image" src="https://github.com/glushchenko/fsnotes/assets/598840/1af35e57-33b0-4cb6-9ee1-d51a9196a0af">

4. Edit the code. E.g. add a new line. Observe syntax updated.

<img width="1000" alt="image" src="https://github.com/glushchenko/fsnotes/assets/598840/e68910ff-58ee-4309-a02a-6a39abdeb2ef">

After edit the syntax is updated for just the changed line

<img width="1024" alt="image" src="https://github.com/glushchenko/fsnotes/assets/598840/9b6cc038-96bc-4fa9-897e-b9645f51c58b">

### Expected behavior

The syntax highlighting is changed right after I press the "h" key as the last letter of "bash" word when replacing "javascript" with "bash" in the beginning of the code block.

### FSNotes version

6.7.1 (621)

### macOS/iOS version

14.2.1 (23C71)

**Comment by glushchenko** [comment]
This is by design, sorry.
