### ISSUE TITLE
Synology Drive Support on iOS

### ISSUE THREAD

**Issue by mfilippov** [glushchenko/fsnotes#1727]
I would like to sync support over Synology Drive right now it is not possible on iOS.

**Comment by gingerbeardman** [comment]
If you check https://fsnot.es

You'll see: "NO Dropbox, WebDAV, Google Drive sync."

I think Synology Drive can also be included on this list. The best thing to do is get them to integrate with Apple Files, then you will get support for free in most iOS apps.

**Comment by mfilippov** [comment]
Synology Drive already have integration with Files.app and I see my notes. But I not understand how to set FSNotes location to this folder.

**Comment by gingerbeardman** [comment]
Try the "Add External Folder" option.

**Comment by glushchenko** [comment]
This should be implemented in the iOS API by Apple, can't help with that.
