### ISSUE TITLE
FSNotes 6.7.1 Fails To Open

### ISSUE THREAD

**Issue by gitglub** [glushchenko/fsnotes#1728]
### Description

MacOS AppStore install, nor Github Release 6.71 open on MacOS Sonoma 14.4.1 (23E224), MacBook Air M2. FS Notes icon just continues to bounce in dock ‘Application Not Responding’. Same application works fine on Macbook M1 Pro with same software. Uninstall, reinstall from MacApp Store, restarts, nothing works.

### To Reproduce

1. Go to ‘Dock'
2. Click on ‘FS Notes'
3. n/a
4. See icon bounce in Dock and App never opens.

### Expected behavior

I expect the app to open so I can use it.

### FSNotes version

6.7.1

### macOS/iOS version

Sonoma 14.4.1 (23E224)

**Comment by glushchenko** [comment]
Try deleting all files from iCloud Drive / FSNotes

**Comment by gitglub** [comment]
There's nothing in the iCloud Drive. No folders are visible. This is what it is doing. Nothing shows up in iCloud Overview in System Preferences. EasyFind shows FSNotes folder in iCloud Drive but zero bytes. Attempt to delete it causes EasyFind to hang. Same with Funter. Full Disk Access. Made iCloud Drive visible via terminal command but still not showing contents. Wish there was an open source alternative to Finder. Apple sucks.




----- Original message -----
Van: "Oleksandr H." ***@***.***>
Aan: glushchenko/fsnotes ***@***.***>
Cc: gitglub ***@***.***>, Author ***@***.***>
Onderwerp: Re: [glushchenko/fsnotes] FSNotes 6.7.1 Fails To Open (Issue #1728)
Datum: zondag 5 mei 2024 10:59



Try deleting all files from iCloud Drive / FSNotes

**Comment by gitglub** [comment]
Fixed. Ran EasyFind as Root, removed all FSNotes related folder/files. Reinstalled FSNotes via MacAppStore (I bought both Mac app and iOS app to support you)

Ultimately, the culprit was the FSNotes toggle in iCloud/iCloud Drive/Apps Syncing to iCloud. When that is toggled 'on' - FSNotes app will not start. Toggle it to off, starts up no problem. It does not matter if FSNotes iOS iCloud option is toggled on or off, same result.

Stay safe in Kharkiv, Oleksandr. Hope that awful war will soon be over.

Jente

----- Original message -----
Van: "Oleksandr H." ***@***.***>
Aan: glushchenko/fsnotes ***@***.***>
Cc: gitglub ***@***.***>, Author ***@***.***>
Onderwerp: Re: [glushchenko/fsnotes] FSNotes 6.7.1 Fails To Open (Issue #1728)
Datum: zondag 5 mei 2024 10:59



Try deleting all files from iCloud Drive / FSNotes
