### ISSUE TITLE
Preview not visible when note list is on top

### ISSUE THREAD

**Issue by jacobweber** [glushchenko/fsnotes#1729]
### Description

When "Note List Location" is "Top", and "Hide preview" isn't checked, there are still no previews in the note list. I can only see them when the note list is on the side.

### To Reproduce

1. Settings > Layout > Note List Location: Top
2. Settings > Layout > Hide preview (turn off)
3. Settings > General > Container > None
4. Settings > General > Format > .txt
5. In the note list, I see the title and date of each note, but no preview.

### Expected behavior

Was expecting a one-line preview, similar to Notational Velocity.

### FSNotes version

Version 6.7.1 (621)

### macOS/iOS version

MacOS 14.4.1 (23E224)

### Additional context

Sorry if this has been reported already; I couldn't find it.

**Comment by glushchenko** [comment]
This is an outdated interface, no development is planned
