### ISSUE TITLE
Hard to read text on quick entry - Gray on Black! (With Comparison Images for GoogleKeep and Upnote) 

### ISSUE THREAD

**Issue by ReessKennedy** [glushchenko/fsnotes#1730]
### Description

In dark mode, the text of quick addition appears gray making it very hard to read (and italic too, which seems strange) 

See image comparis

<img width="1014" alt="Screenshot 2024-05-08 at 7 13 09 PM" src="https://github.com/glushchenko/fsnotes/assets/3970267/1e825169-3e26-4fc4-b668-d5c622030e99">
on

### To Reproduce

Just go share an image to FS Notes and you'll get the popup quick add prompt and the text will be like this. 

### Expected behavior

Would just like standard text style without italics and white on black during dark mode to make it easy to read. I use this every day to add stuff to my notes and would love to see this just in white and not italics so it looks like the rest of my notes on entry. 

### FSNotes version

6.3.2

### macOS/iOS version

iOS 16.7.5

### Additional context

Amazing work on this app, @glushchenko. Thanks for all your hard work!

**Comment by glushchenko** [comment]
Thanks fixed, will be released later.

**Comment by ReessKennedy** [comment]
> Thanks fixed, will be released later.

You the man now dawg! https://yourethemannowdog.ytmnd.com/
