### ISSUE TITLE
Dropbox ios - yes, again…

### ISSUE THREAD

**Issue by marcpops** [glushchenko/fsnotes#1732]
### Description

Hi,
I've read a lot of things saying that for iOS "Dropbox is not supported and is not planned.".
Yet on the home page of the fsnotes website it says "Access anywhere. Sync with iCloud Drive or Dropbox".

So what's the score?
I purchased the iOS version and in the "external folder" preferences, access to the dropbox is grayed out.
Hence this message in the bug report and not in the feature request.

Why is it grayed out?
If Dropbox isn't supported, why does the website say otherwise?
Thanks

### Expected behavior

Access to dropbox files

### FSNotes version

6.3.2 build 284

### macOS/iOS version

15.8.2

**Comment by glushchenko** [comment]
Screen from the fsnot.es site:

![image](https://github.com/glushchenko/fsnotes/assets/1089917/cc6dc3e3-ace5-478e-9eb2-67464062906e)

**Comment by marcpops** [comment]
well, screen from fsnot.es website
![Capture-ecran 2024-05-10 à 14 53 11](https://github.com/glushchenko/fsnotes/assets/75844886/c9e71c9f-b415-4b48-a36c-472228d70832)

**Comment by marcpops** [comment]
Issue is, who could imagine that the ios and mac versions cannot be synched using dropbox since the "access anywhere" boast dropbox as a way to sync files?
Yes I've seen (now) that the text in the ios part of the page is not the same.
But it's misleading and you should put it clearly.
"you can't acces your files anywhere" if you use both ios and mac versions of fsnotes and dropbox.
So at least it would save some frustration…

**Comment by glushchenko** [comment]
I removed that from the description, not going to mislead anyone. If you bought this app, you can refund money through the App Store's report system.

Thank you for feedback.
