### ISSUE TITLE
When typing ,screen periodically flickers and moves caret

### ISSUE THREAD

**Issue by svladek** [glushchenko/fsnotes#1734]
### Description

When writing a note pressing enter and then write again screen will periodically flicker and move carret
See screen recording attached
Fsnotes 6.8.0 Macosx Sonoma 14.4.1
This makes editing impossible

https://github.com/glushchenko/fsnotes/assets/8627833/151d166c-67c1-4dae-a7d1-6aea57cfef22

### To Reproduce

See description and screen recording

### FSNotes version

6.8.0

### macOS/iOS version

14.4.1

**Comment by bugpowder** [comment]
Also happens to me 14.5 (23F79)

Currently just went on Version 6.8.1 (628) from MAS, not sure if the BUG is still here, but it has been bothering me for at least 3-4 previous updates.

Maybe related to some kind of periodic re-parsing / formatting

**Comment by svladek** [comment]
I have re-tested this on 6.8.1 (628) from AppStore and this is still happens with pretty much same behavior.
Same Mac version : 14.4.1

**Comment by glushchenko** [comment]
Please check test build here https://github.com/glushchenko/fsnotes/issues/1701

Closed as dupe.
