### ISSUE TITLE
LanguageTool plug (AddOn)

### ISSUE THREAD

**Issue by powmeister** [glushchenko/fsnotes#1735]
Including [LanguageTool](https://dev.languagetool.org/software-that-supports-languagetool-as-a-plug-in-or-add-on.html) as a plugin would be so wonderful and game changing for some of us. It’ll greatly improve UX — I currently have to copy text back and forth to clean up my writing.

→ 1.5 years of using FS Notes, and it is a distraction-free precision tool for me. I have never used anything else, despite trying around 20 other apps.

**Comment by gingerbeardman** [comment]
Might be possible to make a global macOS Service using [pyLanguagetool](https://github.com/Findus23/pyLanguagetool) if you can get by with no UI

https://github.com/glushchenko/fsnotes/wiki/Services-(macOS)

**Comment by gingerbeardman** [comment]
I'm happy to assist.

**Comment by gingerbeardman** [comment]
I think it's probably best to wait until iOS 18 etc which will have this built in at the system level for all apps.
