### ISSUE TITLE
Screen stutters and flickers when nearing the edit of the editing window

### ISSUE THREAD

**Issue by smcavoy** [glushchenko/fsnotes#1743]
### Description

When editing a document and scrolled down to the bottom of the screen there is a flicker / stutter.

This is with the test 6.8.2 GitHub download release on a system with Falcon agent running 

video attached

https://github.com/user-attachments/assets/0dcd5a7f-0577-4644-81f1-e148ad48716f

### To Reproduce

1. Go to bottom of edit screen
2. begin typing 
3. notice the text above flickers

### FSNotes version

6.8.2

### macOS/iOS version

14.5

**Comment by glushchenko** [comment]
Can not reproduce

**Comment by smcavoy-vercara** [comment]
as of 6.9.2 this no longer happens
