### ISSUE TITLE
Search content remains unchanged after pressing Command + G

### ISSUE THREAD

**Issue by lhrkkk** [glushchenko/fsnotes#1745]
### Description

After performing a global search in FSNotes, pressing Command + G does not update the search box content to reflect the current search query; it continues to display the previous search history instead of the current query "test".

### To Reproduce

* Open FSNotes.
* Press Esc to initiate a search.
* Enter a search query in the search box (e.g., "test") and wait for the search results to appear.
* Press Command + G to attempt to search for the next keyword within notes.
* Notice that the search box content remains unchanged, displaying the previous search history instead of the current "test".

### Expected behavior

Expected Behavior:
After pressing Command + G, the search box content should update to display the current search query ("test") so that users can seamlessly navigate through search results without confusion.

Actual Behavior:
After pressing Command + G, the search box content remains unchanged, displaying the previous search history.

Temporary Workaround:
Press Command + F to load the current search content properly, then press Command + G to navigate to the next search item.

### FSNotes version

6.8.1

### macOS/iOS version

macOS 14.5 (23F79)

**Comment by glushchenko** [comment]
Released: https://github.com/glushchenko/fsnotes/releases/download/6.9.2/FSNotes_6.9.2.zip
