### ISSUE TITLE
Indent for hanging lists using 2 spaces is broken

### ISSUE THREAD

**Issue by apweisskopf** [glushchenko/fsnotes#1747]
### Description

In edit mode, left alignment of hanging lists when using 2 spaces for indentation is broken. There is no left alignment with the list at all, the text wraps at col0.

It works for lists with 4 spaces or tabs:

<img width="634" alt="Screenshot 2024-07-17 at 09 55 46" src="https://github.com/user-attachments/assets/2ce93e28-0344-4d64-bbd3-c69dc34ca119">

As using 2 spaces for indentation is an option in the settings, I would expect this to work in a similar way as for e.g. tabs.

No issues with that in preview mode.

### To Reproduce

Create a note with the following text

```
  - Indent 2 Spaces: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```

### Expected behavior

The rendering in edit mode of the above list should look like

<img width="629" alt="Screenshot 2024-07-17 at 09 57 31" src="https://github.com/user-attachments/assets/e842f49f-db1e-423f-9783-20304c0b6868">

### FSNotes version

6.8.2

### macOS/iOS version

14.5

### Additional context

The following code change should fix the issue

[`NSTextStorage++.swift`](https://github.com/glushchenko/fsnotes/blob/702fa8253667b53eb1b6733efdadc8507611af82/FSNotesCore/Shared/NSTextStorage%2B%2B.swift#L78) 

```diff
                 value.starts(with: "    ")
+                || value.starts(with: "  ")
                 || value.starts(with: "\t")
                 || value.starts(with: "* ")
                 || value.starts(with: "- ")
```

If it helps, I can also create a PR for this change

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.9.3/FSNotes_6.9.3.zip
