### ISSUE TITLE
App icons are not set on iPad

### ISSUE THREAD

**Issue by idnovic** [glushchenko/fsnotes#1755]
### Description

I can set an app icon on iOS but the same does not work on iPadOS.

### To Reproduce

1. Go to Settings
2. Click on Icon Menu
3. Choose any icon
4. Icon is not set

### Expected behavior

The icon should be set.
It does work on iOS.
It does not work on iPadOS.

### FSNotes version

6.7.1 build 299

### macOS/iOS version

17.6.1

**Comment by glushchenko** [comment]
Please check 6.8.0 from App Store
