### ISSUE TITLE
Unable to properly display bold Chinese text

### ISSUE THREAD

**Issue by geshaowen** [glushchenko/fsnotes#1759]
### Description

Unable to properly display bold Chinese text
![2024-09-06-000102](https://github.com/user-attachments/assets/861d2850-d2a4-4b12-8fcc-128666318f5e)

### To Reproduce

/

### FSNotes version

v6.9.4 build 641

### macOS/iOS version

14.6.1 (23G93)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.9.7
