### ISSUE TITLE
Mermaid diagrams don't render in the Preview

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#1760]
### Description

Mermaid diagrams don't render in the Preview showing Mermaid markup instead:

![Screen Shot 2024-09-10 at 15 35 38](https://github.com/user-attachments/assets/7485de77-c579-4cc7-b050-7a4976ff4fe1)

### To Reproduce

1. Open "6. Mermaid and MathJax" note from the "Welcome" directory
2. Click on the Preview icon
3. See the Mermaid example diagram displayed as markup instead of rendered graphics

### Expected behavior

Fenced code blocks containing valid Mermaid syntax and `mermaid` language identifier appear the Preview as rendered Mermaid diagrams.

### FSNotes version

6.9.5 (644)

### macOS/iOS version

macOS 10.15.7

**Comment by glushchenko** [comment]
Its disabled by default

**Comment by saf-dmitry** [comment]
> Its disabled by default

As far as I remember, it was working before the last update, and I didn't change the settings since then.

How can I enable it again?

**Comment by saf-dmitry** [comment]
When I enter your example in FS Notes it looks as following.

Editor mode screenshot:

![Screen Shot 2024-09-10 at 16 16 36](https://github.com/user-attachments/assets/709dd55c-fe44-4712-a464-220cacf1db20)

Preview mode screenshot:

![Screen Shot 2024-09-10 at 16 16 18](https://github.com/user-attachments/assets/e8e5d3d8-d45f-45f7-90e8-d39a9d094fbd)

As you can see, Preview shows me just centered markup text, but no rendered image. Strange...
