### ISSUE TITLE
Keyboard color not altering in dark mode

### ISSUE THREAD

**Issue by ReessKennedy** [glushchenko/fsnotes#1762]
## Issue
- When using dark mode (or system default) the keyboard color seems to always display as white background, at first. 
- When the keyboard is opened a second time the app seems to recognize the theme and switch to dark mode. 

See screencast video below for example of how things work for me. Notice white background at first and then I refreshed and load again and it goes to dark mode. But this happens each time I open the app, it's not that the app needs to learn that it's in dark mode once and remembers, it persists to just default to show the white keyboard each session. 

## Video of behavior

https://github.com/user-attachments/assets/988771a8-41bf-4c01-8d09-54d1006d27fa

### To Reproduce

See video

### Expected behavior

Dark keyboard if in dark mode -- or just have keyboard background color match preference. 

### FSNotes version

6.9.5

### macOS/iOS version

iOS = 16.7.10

**Comment by ReessKennedy** [comment]
> I've encountered the problem but couldn't reproduce it. Fixed it, thank you very much for the detailed bug report.

Nice!!!

**Comment by glushchenko** [comment]
The fix is available in TestFlight
