### ISSUE TITLE
Missing contents in notes list

### ISSUE THREAD

**Issue by tonilampela** [glushchenko/fsnotes#1766]
### Description

Some of the notes I have are missing any content in notes list. What I have gathered, those notes do not have anything particular in common. No images or attachments of sorts.
![CleanShot 2024-09-19 at 09 35 17@2x](https://github.com/user-attachments/assets/97518294-accc-4d5e-bfb2-813e9377117c)

### To Reproduce

1. Sroll through notes list 
2. Observe that some list entries have no text content at all

### FSNotes version

6.9.5

### macOS/iOS version

macOS 15.0 (24A335)

**Comment by glushchenko** [comment]
I'll try to update the system this weekend and see what the problem is.

**Comment by tonilampela** [comment]
@glushchenko I found out the difference after all. There was one empty row in the beginning of those notes that were empty in the list view. I don't know how that row got there, but removing it populated the list views preview text.

**Comment by glushchenko** [comment]
An empty string in Sonoma does not cause problems. We need to look at it.

Thank you for report.

**Comment by glushchenko** [comment]
Same on Sequoia, sadly cannot reproduce :(
