### ISSUE TITLE
Links no longer clickable

### ISSUE THREAD

**Issue by desmond-dsouza** [glushchenko/fsnotes#1767]
### Description

Links in the Mac app (which I just paid for ... that was unexpected but ok) used to be clickable. Just hold the Cmd key and click. Now that does not work any more.

### To Reproduce

1. Enter 'https://www.apple.com' into a note
2. Press Cmd and click on the that URL

### Expected behavior

The URL should highlight in blue and become a clickable link. The click should open the browser at that URL.

### FSNotes version

6.9.4 (641)

### macOS/iOS version

11.7.10

**Comment by glushchenko** [comment]
Please enable checkbox here: Settings -> Editor -> Clickable links
