### ISSUE TITLE
Errors in Spanish translation.

### ISSUE THREAD

**Issue by camifran** [glushchenko/fsnotes#1770]
### Description

_Vizualización_ → Visualización
Also _Ocultar/Mostrar barra lateral_ works backwards.

### To Reproduce

See/Open Menu.

### FSNotes version

6.9.5, 6.9.6

### macOS/iOS version

Mac

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.9.7
