### ISSUE TITLE
Old notes are locked but should not be

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#1771]
### Description

Old notes shown as locked but they are not locked, user interface is confused.

### To Reproduce

1. Go to an old note
2. Padlock in title bar shows locked
3. No padlock in notes list
4. Note does seem locked

### Expected behavior

Old notes should not be locked

### FSNotes version

- 6.9.6 (646)

### macOS/iOS version

- 14.7

## Screenshot

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/42a205e5-c7d6-418c-b209-d11034f24a89">

## Ref
- https://github.com/glushchenko/fsnotes/issues/1591#issuecomment-2372479923

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.9.7

**Comment by eyelessjerry** [comment]
Version 6.9.7 (647) – Tested dragging text in old Notes and it does not work still, but if one opens the old note in a seperate window one can drag text around … .

**Comment by shimeike** [comment]
I observe the same as @eyelessjerry . The lock status in user interface is now consistent, but dragging text only works in the first note opened in any FSNotes window.

**Comment by glushchenko** [comment]
@eyelessjerry read the ticket carefully.

**Comment by eyelessjerry** [comment]
Ok, I guess the dragging of text was not fixed, but the locked status was fixed and one could edit the notes even if one could not drag text around without opening it in a separate window. Dragging of text would be another issue maybe.

**Comment by gingerbeardman** [comment]
@eyelessjerry have turned #1591 into a bug report to track the text dragging there
