### ISSUE TITLE
Soulver inline calculation results not shown on preview on version 6.9.7

### ISSUE THREAD

**Issue by poksme** [glushchenko/fsnotes#1774]
### Description

New and old notes do not display soulver inline calculation (example: `{10% of 5000}`) results when previewed on version 6.9.7. I cannot confirm when the regression was introduced but I remember using this feature a lot beginning of September without problem.

### To Reproduce

1. Create a new note
2. Type a soulver formula enclosed in brackets : `{10% of 5000}`
3. Toggle preview
4. The soulver formula did not resolve and displays `{10% of 5000}`

### Expected behavior

1. Create a new note
2. Type a soulver formula enclosed in brackets : `{10% of 5000}`
3. Toggle preview
4. The soulver formula resolved and should display `500`

### FSNotes version

6.9.7

### macOS/iOS version

macOS Sequoia Version 15.0 (24A335) / iOS 18.0

### Additional context

Recent regression, I was not having this problem early September.

**Comment by glushchenko** [comment]
Soulver incompatible with macOS 10.14 and was removed from FSNotes.
