### ISSUE TITLE
[REQ] Clarify behaviour of Library vs Local

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#178]
I'm not 100% sure how it is supposed to work.

Notes -> View all notes from local and all projects?
Local -> View all notes from all local projects?
Project -> View project notes?

Also: strange that Local heading can be highlighted but not Library?

Notes
![screen shot 2018-04-17 at 19 32 36](https://user-images.githubusercontent.com/49612/38889270-1c2a3fa0-4276-11e8-9ef0-65f3bb81053b.png)

Local
![screen shot 2018-04-17 at 19 27 29](https://user-images.githubusercontent.com/49612/38889247-07859202-4276-11e8-82be-7c0ef75b626d.png)

Project
![screen shot 2018-04-17 at 19 18 06](https://user-images.githubusercontent.com/49612/38888958-124d61b6-4275-11e8-8fc7-c68f8073a104.png)

FSNotes 1.5.4 (127)

**Comment by glushchenko** [comment]
After refactoring:

Notes -> View all notes except Trash
Next default storage, next projects.
