### ISSUE TITLE
Help with Setting Up Git in FSNotes for iOS

### ISSUE THREAD

**Issue by TanyuuKaribusa** [glushchenko/fsnotes#1783]
Hi everyone,

I’m currently using FSNotes on iOS, and I noticed that there is a Git feature available. However, I’m not sure how to set it up properly. Could someone please guide me through the steps or provide any helpful resources?

Thanks in advance for your help!

Best regards

**Comment by gingerbeardman** [comment]
Here we go: https://github.com/glushchenko/fsnotes/wiki/Git-configuration

**Comment by glushchenko** [comment]
git settings are automatically synchronised between iOS and macOS
