### ISSUE TITLE
Send checked items in a "To Do" list to the top/bottom of the list

### ISSUE THREAD

**Issue by aleith** [glushchenko/fsnotes#1784]
**Sort any given To Do list based on checkmark status (discrete sorting of individual lists, not all lists)**
It might be easiest to describe this feature in terms of the Apple Notes feature it resembles. (I looked for an existing FSNotes FR but couldn't find one).

Previously, Notes just had the Settings option to "Automatically sort ticked items" (to the bottom of a list). I disliked this for interacting with long shopping lists on my iPhone so had it disabled all the time. (if you accidentally check the wrote item its a pain to find it again in a long list)
![Screenshot 2024-10-25 at 7 34 11 pm](https://github.com/user-attachments/assets/f6c368fd-53d3-40c9-93af-a01e556c7083)

Occasionally I **do want to** sort a list by `checked` status.  Which is where this menu items come in handy.

![Screenshot 2024-10-25 at 7 41 42 pm](https://github.com/user-attachments/assets/0c834fcc-778f-441f-895a-984ee2e851e0)

It simply moves all the checked/ticked items to the bottom of the list. The cursor must be located in the list to enable the menu items. 
 
**Additional context**
For **macOS** this would require the addition of a menu item to the Format menu (i.e. `Format Menu > Move Ticked to Bottom`).

For **iOS/iPadOS** it would require the edition of a `Move Ticked to Bottom` item to the Format submenu in the contextual menu that comes up when text is highlighted.

Implementation details:

- This feature moves all items that are checked in the selected list, not just item on the line of the cursor or highlighted lines.
- The moved items keep their previous order relative to one another and get moved on top of any existing checked items at the bottom of the list.
- No alphanumeric sorting gets applied anywhere. 
- Other lists in the note and elsewhere remain unaffected.
- The other items in the Apple Notes submenu for "Format > More > …"  such as `Delete Ticked`, `Tick all` and `Untick All` would be “nice to have” but are unnecessary to enable this FR.
- Ditto for the Apple Notes shortcuts under the `Move List Item` submenu ie. `Up` and `Down`.

**Comment by gingerbeardman** [comment]
FWIW TaskPaper app also has this, which is what I use for my work todo lists.

**Comment by aleith** [comment]
> FWIW [TaskPaper app](https://www.taskpaper.com) also has this, which is what I use for my work todo lists.
> 
> 

thx but i need iPhone syncing with whatever Notes apps i'm using. stick with Apple Notes for checklists i guess. would rather have a single platform for everything.
