### ISSUE TITLE
Unable to move folder into another folder on MacOS

### ISSUE THREAD

**Issue by hackmajoris** [glushchenko/fsnotes#1786]
### Description

It's impossible to move a folder inside another folder via drag & drop.
It's only possible to create a new folder at the required location.

### To Reproduce

1. Go to FSNotes
2. Try to move a folder inside another folder via Drag & Drop

### Expected behavior

The folder is moved

### FSNotes version

Not relevant

### macOS/iOS version

6.9.7

**Comment by gingerbeardman** [comment]
You have to do this in Finder, made easier by choosing "Show in Finder" on the folder in the app.

**Comment by hackmajoris** [comment]
> You have to do this in Finder, made easier by choosing "Show in Finder" on the folder in the app.

Now I have another issue: the nested folder are shown only on MacOs. On iOS only the parent folder is shown.

**Comment by gingerbeardman** [comment]
Yes, at least for now.

Development time and energy is short.
