### ISSUE TITLE
How does the Git integration commit/push automatically?

### ISSUE THREAD

**Issue by Zettt** [glushchenko/fsnotes#1790]
### Description

Maybe I'm misunderstanding how this feature is supposed to work. But for me the automatic pushing/pulling is just not working. I have to manually save a version, which then makes the app commit and push to GitHub. 

### To Reproduce

1. Configure Git.
2. See the attached screenshot.
3. Compare with activity on GitHub.
4. For me there are no updates, even when waiting longer. 

<img width="536" alt="Screenshot 2024-11-23 at 18 48 32" src="https://github.com/user-attachments/assets/c46d437a-472b-4674-a803-cebc90369041">

### Expected behavior

When changing a note, I expect FSNotes to commit and push automatically in the background according to the times set in the Git configuration. 

### FSNotes version

Version 6.9.7 (647)

### macOS/iOS version

15.1.1 (24B91)

**Comment by glushchenko** [comment]
minimum commit/push interval is 1 hour

**Comment by Zettt** [comment]
In that case any of these would be nice to have:

- disallow users to set less than a 1-hour interval
- add a label that describes the minimum commit/push interval is 1 hour
- add documentation to the GitHub Wiki page that expalins the minimum wait time is 1 hour

Thank you for considering these.
