### ISSUE TITLE
Git message is hardly legible in dark mode

### ISSUE THREAD

**Issue by besi** [glushchenko/fsnotes#1797]
### Description

When I hit the "Pull/push" in the GIT Settings menu then I get a label that is white on a light grey background which is hardly legible:

The message in dark mode:
<img width="542" alt="Screenshot 2024-12-22 at 18 45 19" src="https://github.com/user-attachments/assets/507243fe-0887-455d-bafc-ac0ad870d280" />

In light mode it's not a problem:
<img width="532" alt="Screenshot 2024-12-22 at 18 46 07" src="https://github.com/user-attachments/assets/ee407c82-68d4-43a1-9558-c71f56c71f36" />

I would suggest to simply remove the light grey background.

### To Reproduce

1. Go to Settings / Git
2. Hit "Pull/push"
3. Review the log message to the left

### Expected behavior

Legible text

### FSNotes version

Version 6.9.7 (647)

### macOS/iOS version

14.6 (23G80)

**Comment by glushchenko** [comment]
I saw this today too, thank you, I'll fix it in the next release.
