### ISSUE TITLE
Notes only span 10% of the actual window

### ISSUE THREAD

**Issue by besi** [glushchenko/fsnotes#1798]
### Description

The problem:
<img width="1406" alt="Screenshot 2024-12-22 at 20 04 29" src="https://github.com/user-attachments/assets/5137d0d1-2907-45a5-b0b3-7885c328d230" />

Also the text can completely disappear which is very confusing when you encounter this issue. 
This is hinted on the next image by letting the text appear by some pixels:
<img width="1019" alt="Screenshot 2024-12-22 at 20 09 35" src="https://github.com/user-attachments/assets/6ca36be4-0ff7-4a5b-9e78-74de323e0720" />

In this state the Sidebar and the Notes List can no longer be properly toggled:
<img width="365" alt="Screenshot 2024-12-22 at 20 12 16" src="https://github.com/user-attachments/assets/c95654cf-f679-4425-9844-fae976e2ccc9" />

### To Reproduce

1. Install a window organizer such as [Magnet](https://magnet.crowdcafe.com)
2. Resize the window using the Window manager and some shortcuts
3. See how the layout of the window is mixed up

### FSNotes version

Version 6.9.7 (647)

### macOS/iOS version

Mac OS Sonoma 14.6 (23G80)

**Comment by besi** [comment]
I just updated the App to the latest version `6.9.8 (651)` and the bug seems no longer present.

**Comment by gingerbeardman** [comment]
also, note line width is adjustable in the FSN Settings
 
<img width="662" alt="Screen shot 2024-12-23 at 11 08 34" src="https://github.com/user-attachments/assets/e1db0219-2d4a-4304-bd9a-ba29e9a35a47" />
