### ISSUE TITLE
[BUG] tags used by a deleted note persist until relaunch

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#182]
![screen shot 2018-04-17 at 19 39 10](https://user-images.githubusercontent.com/49612/38889600-1f8b3388-4277-11e8-968f-300f580ac8e7.png)

FSNotes 1.5.4 (127)

**Comment by gingerbeardman** [comment]
Improved in 1.5.5

Tags are removed when item is trashed?
If you move it out of the trash, the tags are not restored.

Will leave this open for now.

**Comment by glushchenko** [comment]
> Tags are removed when item is put into Trash?
> If you move it out of the Trash, the tags are not restored?

Yes

**Comment by gingerbeardman** [comment]
Unexpected loss of data 😱

**Comment by gingerbeardman** [comment]
Any more thoughts on this?

Note in Documents has tags
Note in Trash has tags
When note is deleted permanently tags are refreshed?

Deleting tags on Trash seems too heavy handed?

**Comment by gingerbeardman** [comment]
Fixed in 1.6.2
