### ISSUE TITLE
[REQ] immediate permanent delete

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#184]
Maybe using:
- Cmd+Shift+Backspace?
- Cmd+Option+Backspace?

These both currently delete, see: https://github.com/glushchenko/fsnotes/issues/186

FSNotes 1.5.4 (127)

**Comment by chharland** [comment]
Yes please. Also, when I Cmd+delete I get 2 popups. Each says "This action cannot be undone", but they're just moving notes to the internal "Trash" folder. Personally, I'd rather see the internal trash removed and put the notes in the Mac's trash... but if I could skip the internal trash that'd be enough.

**Comment by glushchenko** [comment]
@chharland this fixed in 1.5.5

**Comment by chharland** [comment]
Great! Any idea when that'll be pushed to the App Store? Thanks!

**Comment by glushchenko** [comment]
@chharland i dont know, from hours to weeks sometimes.

**Comment by gingerbeardman** [comment]
> Personally, I'd rather see the internal trash removed and put the notes in the Mac's trash... but if I could skip the internal trash that'd be enough.

@chharland fsnotes trash is a subset of system trash

**Comment by gingerbeardman** [comment]
<kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>Backspace</kbd> is the shortcut Finder uses for this.

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1
