### ISSUE TITLE
[REQ] hierarchy of nested folders should be shown in sidebar

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#188]
![screen shot 2018-04-17 at 20 04 24](https://user-images.githubusercontent.com/49612/38890875-913d5fc6-427a-11e8-87e4-725f4fc76e5b.png)

![screen shot 2018-04-17 at 20 04 14](https://user-images.githubusercontent.com/49612/38890864-8af624ea-427a-11e8-9802-6025ebd46a82.png)

FSNotes 1.5.4 (127)

**Comment by gingerbeardman** [comment]
@glushchenko please do not be dismayed with this set of issues - the new UI is super great!

**Comment by glushchenko** [comment]
This is not bug, it is feature ;)

**Comment by gingerbeardman** [comment]
I thought it might be. In that case, I think the nesting should also be shown in sidebar?

**Comment by gingerbeardman** [comment]
Currently, with ordering of sidebar, subfolders can appear far away from the parent folder

![screen shot 2019-02-05 at 17 59 14](https://user-images.githubusercontent.com/49612/52293950-f7fa5e80-296f-11e9-8300-81b8ed9ae74f.png)

**Comment by r3a1d3a1** [comment]
It would also be great to allow seeing all notes within that directory and all its subdirectories. 
This feature could potentially be added as an option when right clicking on that directory.

**Comment by TofPlay** [comment]
Current version 4.0.25 and no subfolder support on the sidebar 😢

**Comment by BeWe11** [comment]
> This is not bug, it is feature ;)

Just to be clear, is there any chance that this is being worked in the future on or is this a design decision that is going to stay?

**Comment by glushchenko** [comment]
@BeWe11 so many requests. I think it possible.

**Comment by stefandesu** [comment]
I only now discovered FSNotes, and it seems like it would be the perfect Markdown notes application, if it only handled folder hierarchies. What my expectation would be:
- Have good support for folder hierarchies (like discussed in this and other issues)
- Add extensive support for smart folders

I think I'll still try to make it work for me. I've moved from Bear to a plain text nested folder structure a few months ago, but I've barely added any notes, and the Bear notes use nested hashtags which is supported by FSNotes, so it should work seamlessly.

Thanks for the hard work on this app!

**Comment by gingerbeardman** [comment]
Can I put a $Bounty$ on this one?

**Comment by gingerbeardman** [comment]
11 dupes so far.

**Comment by ksdomino** [comment]
> 11 dupes to here.

Show that this should definitely be priority #1 but mustn't make demands, we really appreciate everything the developer does to improve this app, would really love to see this bug fixed though: currently I can't use the app because of all subfolders in the sidebar.

**Comment by ksdomino** [comment]
Just had a thought on a possible solution: 
Add option in settings to chose between:
a: use single storage location (ie the current system in the app right now: shows subfolders as folders) 
b: use multiple locations added by user (ie show only folders SPECIFICALLY added by the user AND turn off show subfolders. 

I believe this would be the fastest solution to implement while keeping all users happy.

**Comment by glushchenko** [comment]
OK. New branch started today! I'll let you know as soon as the first beta is ready.

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by peavine** [comment]
I was just testing this new feature and everything appears to work well. I wondered, however, about the sort order of added folders, which seems to be from most-recently-added to least-recently-added. Is there any way the user can change this sort order? Just as a matter of personal preference, I would prefer that the folders sort by name.
