### ISSUE TITLE
[REQ] Drag notes from list to sidebar folders to organize

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#190]
Would be nice to be able to drag notes to organise them, rather than use the Move Menu

**Comment by glushchenko** [comment]
Added for tags and folders

**Comment by peavine** [comment]
This is an excellent new feature. Dragging selected notes to a folder is so much easier than using move in the contextual menu or menu bar. Thanks.

**Comment by gingerbeardman** [comment]
Awesome!

**Comment by sven-gh** [comment]
Does this still work for you guys? 
I was about to log a feature request asking for the exact same functionality but then saw this thread so looks like it was already implemented - however I'm not able to make it work for me

**Comment by gingerbeardman** [comment]
Yes, it works for me.

- drag a note from note list to sidebar folder or tag
- it is moved 

- drag to "Documents" header to not be in any folder

**Comment by sven-gh** [comment]
Thanks for confirming - that made me realize you guys are talking about Mac while I was trying it on iOS

Will create a request for iOS
