### ISSUE TITLE
No way to change default storage directory

### ISSUE THREAD

**Issue by chharland** [glushchenko/fsnotes#191]
The readme says you can change the default storage location, but there are no instructions on how to do that and although I've looked through all menus, preferences, and context menus I can find no place to update the default storage location. Am I just blind or is this feature missing?

**Comment by gingerbeardman** [comment]
Try

_Folder_ > _Attach storage_ > _Choose a new location_

You can have multiple, and even add iCloud drive or Dropbox etc

**Comment by jeff-h** [comment]
Hmm, but how do you select the one you want as the default for new notes?

**Comment by gingerbeardman** [comment]
All notes will be created in whatever locations is highlighted/selected in the sidebar.

**Comment by jeff-h** [comment]
What then when you have "Library > Notes" selected?

**Comment by gingerbeardman** [comment]
Indeed, no idea 🤣

**Comment by chharland** [comment]
They then go in "Local". I don't have Folder -> Attach storage. I thought maybe Folder -> Add root folder... but no - That works like your Attach storage option I think. I expected to see an option in Preferences. The wording could be better and more consistent on all these.

**Comment by glushchenko** [comment]
Added in 1.5.6
