### ISSUE TITLE
[REQ] Support for Dropbox / folders in iOS version

### ISSUE THREAD

**Issue by acrostich** [glushchenko/fsnotes#195]
In the MacOS one can add directories, including that of Dropbox folders, however in the iOS version it seems that it can only see the iCloud Drive folder. It would be useful to support other shared file systems such as Dropbox.

**Comment by acrostich** [comment]
Sorry to have missed that earlier feature request and thank you for the kind words.

**Comment by glushchenko** [comment]
Spent some time in dropbox branch https://github.com/glushchenko/fsnotes/tree/ios-dropbox

Sadly, but dropbox deprecate Sync API, and propose api v2. 

Many questions for new api, no any examples. I see that this requires a lot of time for proper implementation. 

Therefore i stopped research. Dropbox now not developer friendly service.

**Comment by jeff-h** [comment]
As it happens, I looked at https://github.com/dropbox/SwiftyDropbox just yesterday and have to agree — that looks like a LOT of work. Shame :(

**Comment by acrostich** [comment]
That's a shame as Dropbox has a feature, not present on iCloud, I find really helpful which is offline files. I was looking forward to be able to use both. 

Are you going to drop support of Dropbox on macOS too then if they make it too hard to work with?

**Comment by jeff-h** [comment]
Hmm, strange — my FSNotes documents stored in iCloud are accessible to me in iOS when offline.

Re the macOS FSNotes — Dropbox support is provided by the OS, and is not a feature coded into FSNotes. So it won't be going away :)

**Comment by acrostich** [comment]
Re Dropbox on iOS. As Files supports Dropbox, maybe support will be provided by iOS.

Re iCloud offline access, I need to investigate that. I think there's some caching but I am not aware of how you ensure it remains offline. This is really useful when traveling and roaming is too expensive.

**Comment by fuzzy76** [comment]
Was this fixed in #147 ?

**Comment by glushchenko** [comment]
Dropbox not supported and never be supported.
