### ISSUE TITLE
[BUG] Cant delete note - when enabled: Focus in editor when selected note

### ISSUE THREAD

**Issue by ambrosso** [glushchenko/fsnotes#199]
Cant delete note neither with hotkey or right click menu,
when option enabled "Focus in editor when selected note" in preferences.

**Comment by glushchenko** [comment]
command-shift-delete?

**Comment by ambrosso** [comment]
command-shift-delete  and  command-delete
But sometimes it work

**Comment by peavine** [comment]
My experience is the same as ambrosso's. With the focus-in-editor preference set on, I am not able to delete a note by way of the top menu, right-click menu, or either of the two shortcuts. With the focus-in-editor preference set off, then delete works fine.
