### ISSUE TITLE
[REQ] Add some Text Styles and Shortcuts  for *.RTF - like in default Notes.app

### ISSUE THREAD

**Issue by ambrosso** [glushchenko/fsnotes#204]
Add some text styles, shortcuts ant text menus for *.rtf files - like in default macOS Notes.app

[![note-app-5.png](https://s7.postimg.cc/xdltqbeyj/note-app-5.png)](https://postimg.cc/image/4nyxtoayf/)
[![note-app-4.png](https://s7.postimg.cc/j762v3bt7/note-app-4.png)](https://postimg.cc/image/9zduee4qv/)
[![note-app-2.png](https://s7.postimg.cc/50qbzvgdn/note-app-2.png)](https://postimg.cc/image/beff34l9j/)
[![note-app-3.png](https://s7.postimg.cc/u6ra6ppdn/note-app-3.png)](https://postimg.cc/image/3lorb5n07/)
[![note-app-1.png](https://s7.postimg.cc/iueooybjv/note-app-1.png)](https://postimg.cc/image/ey1csyqk7/)

**Comment by gingerbeardman** [comment]
Can you please explain this a little more? for those of us that don't use macOS Notes.app

**Comment by ambrosso** [comment]
In Notes.app you can set text styles with Shortcuts and Menus: can add Checklists and check them with UI, can mark text as Title/Heading, etc, like in screenshots.

When you use .md - of course can make it with markdown syntax.
But when you use .rtf you cant make this things. In other words - implement some markdown features for .rtf text with Shortcuts and Text/UI menus.

**Comment by gingerbeardman** [comment]
Ah, OK. Good suggestion.
