### ISSUE TITLE
can`t install in app store

### ISSUE THREAD

**Issue by hfq-mayouzi** [glushchenko/fsnotes#206]
![](https://ws2.sinaimg.cn/large/006tKfTcly1fqnjo6fkkoj3083086glo.jpg)

others can install normally

**Comment by hfq-mayouzi** [comment]
it`s the last version

**Comment by hfq-mayouzi** [comment]
it`s the latest version

**Comment by hfq-mayouzi** [comment]
![](https://ws4.sinaimg.cn/large/006tKfTcly1fqnjur5wnrj30nc076t9n.jpg)

**Comment by hfq-mayouzi** [comment]
@glushchenko @greendog99

**Comment by glushchenko** [comment]
Try remove app and rebooting the system. I do not think this is an application problem.

**Comment by glushchenko** [comment]
Perhaps this will helpful:

https://apple.stackexchange.com/questions/54441/how-to-remove-an-app-stuck-in-waiting-mode-from-the-mac-app-store

**Comment by hfq-mayouzi** [comment]
@glushchenko  same old, can you send an pkg file to my email?

**Comment by gingerbeardman** [comment]
@hfq-mayouzi you can download the latest version of the app from the [Releases](https://github.com/glushchenko/fsnotes/releases) section.

But to get your App Store version, try using [App Cleaner](https://freemacsoft.net/appcleaner/) to remove the app? And then reinstall.

**Comment by hfq-mayouzi** [comment]
@gingerbeardman thx 🌺🌺
