### ISSUE TITLE
Note deletion prompt

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#219]
The release notes for 1.6.0 identifies the following change:

* Disables deletion prompt for non trashed notes

I no longer get a deletion prompt when removing a file using File > Delete. Is this intentional?

**Comment by glushchenko** [comment]
Note deletion from text editor removed. Now remove available from notes list, with ⌘-z undelete.

**Comment by peavine** [comment]
Thanks for explaining that.
