### ISSUE TITLE
[Feature Request] Simplenote Sync support

### ISSUE THREAD

**Issue by iandol** [glushchenko/fsnotes#22]
The killer feature of NVAlt for me is the Simplenote integration. The Simplenote app is great on phones and tablets, very nice to use. So the NVAlt+Simplenote combination is a great and flexible workflow. Except that NVAlt has lots of unfixed bugs.

Now, if someone tells me there is somethings faster and better than Simplenote for iOS dealing with a Dropbox/iCloud folder of notes then...

**Comment by glushchenko** [comment]
https://simplenote.com/developers/

**Comment by iandol** [comment]
> The current version of the Simperium API does not allow for third party development of Simplenote apps at this time. We will update this page if this changes. Thanks for your interest!

Oh dear, well that solves this feature request then! Thanks anyway and good luck with this project.

**Comment by sepich** [comment]
> Some older applications may still be using the legacy Simplenote API at https://simple-note.appspot.com. Note that this API has been deprecated and will no longer function after October 1, 2018.

BTW, it still works. I can provide you the token ;)

**Comment by sepich** [comment]
Researched a little and can provide `X-Simperium-API-Key` too.
