### ISSUE TITLE
Highlighting in notes list

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#220]
It would be better if the current note highlight colour was that chosen by the user in System Preferences > General > Highlight colour, rather than hardcoded to blue.

Also, and more importantly, it would be great if the highlight colour went grey when the note list loses focus (firstresponder status?). This would clearly visually indicate whether the notes list has focus, or the note area itself. Both Mail.app and Notes are good examples of this behaviour; in Mail.app when you select an email in the list of emails, it is highlighted in colour, but when you click in the email body itself, the selected email highlight goes grey.

**Comment by peavine** [comment]
It's a great idea to use color to indicate whether the sidebar, note list, or editor has the focus.

I have the highlight color in system preferences set to blue. I looked at the notes app included with macOS Sierra and the color scheme appears to be:

* Selected folder with focus: dark gray (or black)
* Selected folder without focus: medium gray
* Selected note with focus: yellow
* Selected note without focus: medium gray

I have no expertise in interface design, but I do think it's a good idea to give some thought to all of the colors used in FSNotes.

**Comment by gingerbeardman** [comment]
FYI in Xcode you can pick from all the system colours. So should be an easy fix.

**Comment by jeff-h** [comment]
> It would be better if the current note highlight colour was that chosen by the user in System Preferences > General > Highlight colour, rather than hardcoded to blue.

Seems I got this wrong; it seems the table selection highlight is actually arbitrary in macOS!? For me it's blue in Mail.app but yellow in Notes.app (as you said, @peavine), irrespective of any setting I'm aware of in System Preferences. So the first half of my issue above is irrelevant. The second is still useful though.

@gingerbeardman much of the FSNotes UI is done in code not with Interface Builder but still, I agree, not too hard to find :) I think the resigning of firstresponder is likely to be less fun though.

**Comment by glushchenko** [comment]
Accent colours implemented in FSNotes 5
