### ISSUE TITLE
Deleting two or more notes

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#222]
I installed FSNotes 1.6.1, and I have the Focus-in-Editor option enabled. When I select two or more notes in the note list, the delete command in the menu bar and the corresponding keyboard shortcut are not available. Instead, I have to use the contextual menu. Can the menu-bar delete and shortcut delete be enabled when multiple notes are selected? Thanks.

**Comment by glushchenko** [comment]
When focus in editor, we can not use ⌘-return, because it is default shortcut for string deletion.

I dont know how to solve it. Anyway you can drag and drop notes to trash, or move from right click menu.

**Comment by peavine** [comment]
Thanks for letting me know that--what you say makes sense. I seldom delete more than one note at a time and when I do I'll use the right-click menu.

**Comment by peavine** [comment]
The new keyboard shortcut works great when deleting single and multiple notes when the focus is in the editor. Thanks.
