### ISSUE TITLE
[REQ] deleted folder containing notes does not appear in FSNotes Trash folder

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#224]
1. Create folder
2. Add a note to it
3. Delete it to Trash

**Expected**
- Folder should be visible in Trash

**Actual**
- nothing shown in Trash

**Comment by peavine** [comment]
@gingerbeardman. I don't mean to hijack this issue, but I think we may have the same issue stated in different ways.

When I delete a folder (as distinguished from a project), it is removed from the sidebar but is not deleted from the file system. However, when I delete a project, it is removed from the sidebar and is also deleted from the file system. I was just curious why it worked this way.

**Comment by peavine** [comment]
If I create a folder with "attach storage" and then delete that folder, it is removed from the sidebar but not deleted from the file system. So, I would not expect it to be in the trash.

If I create a folder with "new folder" and then attempt to delete that folder, I receive a dialog that the action cannot be undone. So, once again, I would not expect the folder to be in the trash.

It seems like this is more a feature request (and one I would like to see) then a bug. Or am I missing something?

**Comment by gingerbeardman** [comment]
I didn't read the alert message (oops) so you may be correct! I'll check again later.

**Comment by gingerbeardman** [comment]
@peavine you are quite correct! changed from [BUG] to [REQ] 👍

**Comment by glushchenko** [comment]
Long standing issue. Already git backups implemented, so i dont think that this is needed. Sorry, Matt :)
