### ISSUE TITLE
FSNotes Freezes when using "Attach Storage"

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#226]
I have a 2012 Mac mini running Sierra with all updates. It boots from a partition named "Macintosh Boot" on the internal hard drive.

I do the following:

1) Select "Attach storage" from the FSNotes menu bar.

2) Select "Robert's Mac mini" under devices.

3) Select "Macintosh Boot" in the right pane and click on "open".

After doing the above, I got a beach ball and had to force quit FSNotes. I then rebooted and tried to run FSNotes but I still got a beachball. The only way I could get FSNotes to run was by deleting the FSNotes container files.

I repeated the above with other partitions on my hard drive and external drives and did not encounter any issue. Also, on one occasion after selecting "Macintosh Boot", I waited about 10 minutes to see if FSNotes would finish whatever it was doing but the beach ball was still present.

I've attached the crash report.

Thanks.

[peavine_report.txt](https://github.com/glushchenko/fsnotes/files/1963970/peavine_report.txt)

**Comment by glushchenko** [comment]
How many files on "Macintosh Boot"?

**Comment by peavine** [comment]
There are 455,000 files on "Macintosh Boot".

**Comment by peavine** [comment]
I installed 1.6.2 and once again tried to add "Macintosh Boot" as attached storage. FSNotes added a bunch of folders and was finished within a few seconds. 

I originally added Macintosh Boot by accident and would never do this intentionally. So, I immediately deleted it and continued on my way. Thanks.
