### ISSUE TITLE
[BUG] folders in sidebar not ordered

### ISSUE THREAD

**Issue by aseygo** [glushchenko/fsnotes#228]
the folders in the sidebar (per storage location) are not ordered. I would expect that they are ordered alphabetically. this is a regression, in previous versions the folders were ordered.

steps
- create folder 'b', 'a' and 'c'

actual result
- sidebar shows
  - documents
    - b
    - a
    - c

expected result
- sidebar shows:
  - documents
    - a
    - b
    - c

![s](https://user-images.githubusercontent.com/33933918/39577117-52465a74-4ed8-11e8-966d-d20317399420.png)

**Comment by glushchenko** [comment]
Folders in sidebar never been ordered

**Comment by gingerbeardman** [comment]
I guess to would be good to either allow manually ordering, or alphabetical sorting.

There's another issue somewhere about showing any nested folders in the sidebar also.

**Comment by aseygo** [comment]
I now tried to reproduce the regression with an older versions, because I'm quite sure my folders were ordered with e.g. 1.5.8. (not while creating them, but after the first restart of fsnotes). wasn't able to find a pattern or reproduce it consistently ;)

but never mind, yes would be great to have this feature and get alphabetical sorting.

**Comment by aseygo** [comment]
suggested fix see PR https://github.com/glushchenko/fsnotes/pull/264
