### ISSUE TITLE
[Bug] If query matches file name, select file with that name

### ISSUE THREAD

**Issue by octos** [glushchenko/fsnotes#231]
When searching, FSNotes should determine if a filename matching the search query exists and select it accordingly. Some of my files have a single-letter filename, and I would like to be able to select them without using the mouse. nvALT calls this feature "Auto-select notes by title when searching."
![screen shot 2018-05-05 at 10 30 24](https://user-images.githubusercontent.com/3092142/39664829-5abe0f30-504f-11e8-8968-c8797683a9cb.png)

**Comment by glushchenko** [comment]
Added in 1.6.3
