### ISSUE TITLE
[Cosmetic Issue] Attached storage, folders, and projects

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#235]
When the sidebar was first added to FSNotes, I did not initially understand the terminology used in two respects.

First, there is a preference option for "Default storage" and a menu item for "Attach storage". The use of the term storage (or storage area or storage location) is simple enough, but the word attach conveys the idea of external storage, which is not always the case. Perhaps the menu item could be changed to Add storage or New storage location or something similar.

Secondly, folders within storage areas are referred to both as folders and projects. There may be some difference, but if so I don't understand what it is. FWIW, I would prefer to stick with the term folder.

Thanks.

**Comment by gingerbeardman** [comment]
I keep meaning to rewrite/unify all labels and UI text. I'll do it soon!

**Comment by peavine** [comment]
@gingerbeardman. A rewrite of all labels and UI text will be great. I just tried to use System Preferences to change the keyboard shortcut to File > Delete and, when it didn't work, I discovered that I had created a keyboard shortcut to Edit > Delete.

**Comment by gingerbeardman** [comment]
@glushchenko to make this easy to manage, and scalable, we'll need to pull all labels out into a localisable strings file? https://github.com/glushchenko/fsnotes/issues/251

**Comment by glushchenko** [comment]
Unblocked here  https://github.com/glushchenko/fsnotes/issues/251

**Comment by gingerbeardman** [comment]
@glushchenko beautiful, thank you

**Comment by glushchenko** [comment]
@gingerbeardman hmm ... 3 years ago :) May be time to close it?
