### ISSUE TITLE
[Bug] Escape key shows all notes in storage area

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#236]
Pressing the escape key causes FSNotes 1.6.3 to show all notes in the selected storage area rather than just the notes in the selected folder. This is similar and may be the same issue as #230. 

Also, after pressing the escape key as described above, and before restarting FSNotes, any new notes are saved in the storage area folder instead of the selected folder.

Thanks.

**Comment by glushchenko** [comment]
ESC resets sidebar and selected notes, it is a normal behaviour.

**Comment by peavine** [comment]
Thanks for explaining that.
