### ISSUE TITLE
1.6.3 regression—filtered note list order

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#238]
When searching, the order of the notes in the resulting list seems to have changed. In 1.6.2 and earlier, I think some weight must have been given to notes with the search words in their note title (ie filename)? 

For example, I have several notes with the keyword NSTask in them. However only one of those notes has nstask in the note title. In 1.6.2 and earlier, the latter was top of the list. In 1.6.3 and later it's not clear to me what the search result order is. Even pinned notes don't always come first.

**Comment by peavine** [comment]
I ran a test and notes appear to be ordered as follows:

1) Notes that have names that have the potential to exactly match the search string.

2) Notes that have a name that cannot exactly match the search string but have the search string in their name or text.

Within each of the above categories, the search string appears to be  ordered according to the sort order set by the user by the menu item "View > Sort By".

So, if the sort string is xx, then the first two of the following would fall in category 1 and the third would fall in category 2:

xxa
xxb
cxx

The ordering of notes when searching make sense, and any change from 1.6.2 would appear to be a result of the changes made in response to issue #231. Are you asking a different question?

**Comment by jeff-h** [comment]
Sorry, I looked deeper and think I was confused, but the issue remains — I just stated it poorly. Earlier versions of the app correctly sorted the results by modification date, which is what I've selected in the "sort by" menu.

For me, in 1.6.3 (140) the results list is definitely not sorted by modification date, which is what I've selected in the "sort by" menu.

**Comment by peavine** [comment]
@jeff-h. It's easier for me to explain by example. Also, I haven't tested this when notes are sorted by modification date.

I have set FSNotes 1.6.3 to sort by title (from a to z). Assume the search string is xx and the notes before the search have the following names:

aaa  --this note contains xx in text
axx
bbb  --this note does not contain xx in text
bxx
xxa
xxb

After the search, the following notes are shown:

xxb --category 1 (potential for exact match)
xxa --category 1
aaa --category 2 (contains xx in name or text)
axx --category 2
bxx - category 2

I would expect xxa to come before xxb and I don't know why it doesn't.

So, I distinguish between notes that have the potential to match the search string exactly as the user continues to add letters to the search string and those that do not. I assume this was done to implement the feature to auto-select notes when searching (#231).

**Comment by glushchenko** [comment]
Hello, guys. Please try FSNotes 1.6.5

At first FSNotes search notes which contain the search terms in their title, then in body.

**Comment by jeff-h** [comment]
Fixed! 👍

**Comment by peavine** [comment]
I just tested search/note-filtering in 1.6.5 and it works great. This was always one of the best features of FSNotes and now it's even better. Thanks.

**Comment by jeff-h** [comment]
I agree — so far 1.6.5 feels like the best release ever :)
