### ISSUE TITLE
Feature Request: Renaming and Deleting Notes

### ISSUE THREAD

**Issue by proksch** [glushchenko/fsnotes#24]
I really like how the app is starting to shape up! I think it would be very useful to have the means to rename a file (= note title) and to delete it, e.g., by adding a context menu to the list of notes. I realized that the renaming already works sometimes by clicking on an item, but not always... and this functionality seems to stop working after the app runs for some time.

**Comment by glushchenko** [comment]
You can select note and press “cmd-r” for rename, or “cmd-delete” for remove.

**Comment by jeff-h** [comment]
There do seem to be a few scenarios where the shortcuts don't work. For example, I suspect that when the `EditTextView` is first responder, the key shortcuts never go into the `keyDown` func in `NotesTableView` (and vice-versa).

Could the `keyDown`'s of `NotesTableView` and `EditTextView` be merged into one method on the `ViewController`?

**Comment by glushchenko** [comment]
Now (cmd-r/delete) shortcuts works in edit text view too:
https://github.com/glushchenko/fsnotes/releases/download/0.12/FSNotes.app.zip

**Comment by jeff-h** [comment]
Excellent!

**Comment by jeff-h** [comment]
Nice consolidation of all that keyboard event code! I had a quick try but couldn't get all the events to flow through the `ViewController` — I was missing your calls to `NSEvent.addLocalMonitorForEvents`.

**Comment by glushchenko** [comment]
Try new build https://github.com/glushchenko/fsnotes/releases/download/0.15/FSNotes.app.zip
