### ISSUE TITLE
iOS wiki/internal links not followable in text/edit mode

### ISSUE THREAD

**Issue by jrjones** [glushchenko/fsnotes#241]
In text/edit mode, internal/wiki links [[Like this]] are clearly recognized as such, but are not followable. Long-press brings up a menu showing Open/Copy/Share options, but open doesn't appear to do anything.

Since wiki/internal links are also not visible in preview mode (#239) this means that wiki links are not usable in iOS at all. (Tested only on iPad version.)

**Comment by glushchenko** [comment]
Fixed long time ago
