### ISSUE TITLE
BUG: Cannot move notes to other folders.

### ISSUE THREAD

**Issue by phmullins** [glushchenko/fsnotes#244]
What: User cannot move notes from one folder to another. Expected: Selected note to be moved to selected folder. What Happens: Trying to move a selected note to another folder results in an error. "Note with name "note.md" already exists in selected storage"

**Comment by peavine** [comment]
I agree with @gingerbearman. You might also want to look at #229 to see if that would address your issue.

**Comment by phmullins** [comment]
It's actually working now. No idea what happened, but it works just fine. ¯\_(ツ)_/¯
