### ISSUE TITLE
BUG: Notes not being saved properly via iCloud Sync

### ISSUE THREAD

**Issue by phmullins** [glushchenko/fsnotes#245]
Expected: Fsnotes to save my *many* notes to iCloud. What Happened: Only three of ten folders were saved and one had no notes inside at all. I have essentially lost all of my notes.

**Comment by phmullins** [comment]
The FSNotes and iCloud drive folder contain the same three folders. The other seven have disappeared.

**Comment by phmullins** [comment]
I'm using v1.6.5 (141). I'm starting to think it was just an issue with iCloud. I've since moved my data to Dropbox and haven't had any issues.

**Comment by glushchenko** [comment]
Can not reproducible
