### ISSUE TITLE
can not hidden in dock?

### ISSUE THREAD

**Issue by ghost** [glushchenko/fsnotes#247]
the preference not find `hidden in dock`

**Comment by hfq-mayouzi** [comment]
@gingerbeardman @gingerbeardman

**Comment by gingerbeardman** [comment]
There currently isn't a preference to not show FSNotes in the Dock.

**Comment by glushchenko** [comment]
Added in 1.7

**Comment by hfq-mayouzi** [comment]
@glushchenko great upgrade, 👍
a suggestion: hidden FSNotes in the Dock and show FSNotes in the menu

**Comment by gingerbeardman** [comment]
@hfq-mayouzi what menu?

**Comment by jakemkc** [comment]
I think @hfq-mayouzi  is talking about the menu bar
https://support.apple.com/kb/ph25077?locale=en_US

I am a new FSNotes user (used nvalt for a while). Yesterday I tried to hide the dock icon but then I found no way to go to preference again -- ended up using "find any file" app to remove all traces of FSNotes and reinstall it.

A little icon of FSNotes in the menu bar with an option to go to preference would be nice.

**Comment by glushchenko** [comment]
Preferences shortcut: ⌘ + ,

**Comment by gingerbeardman** [comment]
How do I get the app back if I hide from Dock and then hide the app?

**Comment by hfq-mayouzi** [comment]
@gingerbeardman 

as the @jakemkc described

**Comment by hfq-mayouzi** [comment]
@gingerbeardman 
i can back app use  custom `key shortcut` when it hide from dock

**Comment by DenisLanz** [comment]
There should be an option in the setting to define a global hot-key. I used alt+^ as a global hotkey to have nvalt always available when needed.

**Comment by glushchenko** [comment]
You can define global shortcut in preferences.

**Comment by DenisLanz** [comment]
Could you guide me into the right direction. I want a global shortcut, no matter which application is active, tha FSNotes App should become active and visible, if I hit the shortcut again it should be hidden again. Similar to the "Bring to Front" Hotkey Preference in NValt - afaik that is not possible in preferences.

**Comment by DenisLanz** [comment]
Okay, behaviour is what I expected but why can't I use `⎇+^`
