### ISSUE TITLE
International character in search field causes stray character after auto-complete

### ISSUE THREAD

**Issue by Aetles** [glushchenko/fsnotes#248]
If I write something in the search field that causes auto-complete to fill a word (or multiple words) that contains an international character (in my case the Swedish "å", "ä" or "ö") the last character will be un-selected. Even if I delete everything else that last character remains and can't be access by the arrow key or overwritten (unless I select everything and delete).

Example: if I start writing "kan" and it auto-completes to "kanarieöarna" the the last character, the "a" wont be selected will remain at the end even if I continue to type:
<img width="311" alt="auto-complete with un-selected character" src="https://user-images.githubusercontent.com/429202/40487428-6e3688b6-5f64-11e8-83a0-7598d83ca553.png">

If I delete everything then the stray character remains but I can't move the insert point to the right of it with the arrow key:
<img width="323" alt="remaining stray character" src="https://user-images.githubusercontent.com/429202/40487439-71d63822-5f64-11e8-95b3-4e3219903260.png">

**Comment by glushchenko** [comment]
Thank you for bug report. Fixed in 1.7

**Comment by Aetles** [comment]
That was fast! I can confirm that it is indeed fixed in 1.7, thank you!
