### ISSUE TITLE
[BUG] Keyboard list oddity (iOS app)

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#249]
I use multiple keyboards: 
![GitHawk Upload by gingerbeardman](https://i.imgur.com/O31UgG8.jpg)

This is what FSNotes shows: 
![GitHawk Upload by gingerbeardman](https://i.imgur.com/23G10YO.jpg)

Notice how selecting the top one (actually TouchPal) it also selects the bottom one (actually Gboard).

The list should use unique names rather the language, which as we can see may not always be unique.

**Comment by glushchenko** [comment]
Fixed in 1.5
