### ISSUE TITLE
[BUG] iOS app only sees notes at root level of storage location

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#250]
Desktop
1. create new folder
2. create new note in folder

iOS
1. view contents of FSNotes

--- 

Expected
- should see folder and/or note

---

Actual
- only see notes at storage root level

**Comment by gingerbeardman** [comment]
I'm using [Pretext](Pretext by Sam Oakleyhttps://itunes.apple.com/gb/app/pretext/id1347707000?mt=8) to edit my notes on iPhone at least for now

**Comment by glushchenko** [comment]
@gingerbeardman hmm, interesting, where news folders created, in iCloud Drive?

**Comment by gingerbeardman** [comment]
I copied the folder structure onto iCloud Drive manually using Finder on MacOS. 

All files throughout the folders appear on Desktop FSNotes. 

Only the one note I have a top level appears on FSNotes iOS.
![GitHawk Upload by gingerbeardman](https://i.imgur.com/Lrhryp0.jpg)

All notes and structure appears in Pretext.

![GitHawk Upload by gingerbeardman](https://i.imgur.com/wPgjtHr.jpg)

**Comment by gingerbeardman** [comment]
I've not been able to figure out how to open it?

**Comment by glushchenko** [comment]
Swipe from left to right with 2 fingers gesture.

**Comment by gingerbeardman** [comment]
I cannot get that to work.

**Comment by jeff-h** [comment]
Ha — well, well... I did not know that was there!

So clearly the left-to-right 2-finger swipe does work for me, but I wonder how many people, like me, would not have discovered it?

**Comment by gingerbeardman** [comment]
I'm on an iPhone 6s

**Comment by glushchenko** [comment]
Fixed in 1.5
