### ISSUE TITLE
Auto-continue numeric lists broken

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#253]
Auto-continuing numeric lists are broken for me (the auto bullet list still works fine).

**Comment by jeff-h** [comment]
Ah, it's the inconsistent requirement for the trailing full stop (or other accepted delimiter) that confused me. I actually never use the numeric lists feature, but occasionally it would trigger when I didn't want it eg when entering a list of events beginning with a four-digit year (eg `2008 Something`).

The problem seems to be that the auto-numeric list code looks for one of the triggering delimiters (full stop etc) after the number, but only when the number is single-digit.

Try these scenarios:

* `1 Something` then hit enter. FSNotes will do nothing.
* `10 Something` then hit enter. FSNotes will automatically start the next line with `11`

**Comment by glushchenko** [comment]
Fixed in 1.7
