### ISSUE TITLE
Local images are not displayed in preview mode

### ISSUE THREAD

**Issue by lowski** [glushchenko/fsnotes#254]
Hi!
When I attach image by drag & drop, it's displayed in normal mode but when I switch to preview mode, I can only see image's description.

### Screenshots:

**Normal mode**

<img width="844" alt="normal_mode" src="https://user-images.githubusercontent.com/1379988/40580155-71510d38-6139-11e8-8411-903f6bf36aca.png">

**Preview mode**

<img width="844" alt="preview_mode" src="https://user-images.githubusercontent.com/1379988/40580154-6eff3b40-6139-11e8-8e2b-2b83508b809b.png">

When I use remote paths for images then they are displayed correctly in preview mode. It seems only local paths are not handled correctly.

Would you mind looking into that, please?

**Comment by glushchenko** [comment]
I know about this problem. Will try to fix it in next releases.

**Comment by glushchenko** [comment]
Added in 1.7

**Comment by lowski** [comment]
@glushchenko thank you very much! Works well.
