### ISSUE TITLE
[REQ] Hierarchical Tags

### ISSUE THREAD

**Issue by cuddawudda** [glushchenko/fsnotes#257]
Is hierarchical tagging on the roadmap?

It really allows a clean and organised hierarchy imho, without resorting to hacks as i had to use in evernote (ie create a pseudo hierarchy by prefixing tags e.g. ref.comp.vba, or recipe.vegetarian etc)

Bear has a nice implementation of this.

**Comment by glushchenko** [comment]
I think it is possible later.

**Comment by glushchenko** [comment]
Addes in 4.0.0
