### ISSUE TITLE
iOS Dark Mode Text Unreadable

### ISSUE THREAD

**Issue by prenagha** [glushchenko/fsnotes#258]
I like Dark Mode on iOS in general, but the text color vs the background in note view is too hard to read. Black text on dark grey background is near impossible for me to read. I think the text color needs to be lighter
![fullsizeoutput_c1a7](https://user-images.githubusercontent.com/194250/40588628-58f78134-61ae-11e8-9764-0facde250d8a.jpeg)

**Comment by glushchenko** [comment]
Thank you for feedback, will be fixed in next release. Before that time you can use markdown.

**Comment by glushchenko** [comment]
Fixed in 1.5
