### ISSUE TITLE
Indent multiple lines with partial first line selection

### ISSUE THREAD

**Issue by keymasterr** [glushchenko/fsnotes#259]
1. Select multiple lines like this:
  >Lorem `ipsum`  
  >`dolor` sit amet 
2. Press `Tab` / `Shift+Tab`
↓
The first line breaks with a tab or doesn't indent instead of moving.

**Comment by gingerbeardman** [comment]
I cannot reproduce on 1.7 (145)?

Both lines indent for me (although they should stay selected after indenting, so I filed https://github.com/glushchenko/fsnotes/issues/261 )

Also related: https://github.com/glushchenko/fsnotes/issues/243

**Comment by keymasterr** [comment]
1.7 (145)
Lines are selected after indenting.
![screencast 2018-05-30 14-14-56](https://user-images.githubusercontent.com/6844067/40717599-9d081596-6415-11e8-92cd-29433d1f0d73.gif)

**Comment by gingerbeardman** [comment]
Weird.

![2018-05-30 14_08_48](https://user-images.githubusercontent.com/49612/40721995-051c3692-6413-11e8-80bf-009f926cafca.gif)

**Comment by glushchenko** [comment]
Fixed, will be available in next release.
