### ISSUE TITLE
Selected lines should remain selected after indenting using keyboard

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#261]
1. Select multiple lines
2. Press Tab to indent (Shift+Tab to unindent)
3. Observe selection

Expected
- selection should remain for successive indenting

Actual
- selection is lost

![2018-05-30 14_08_48](https://user-images.githubusercontent.com/49612/40722101-489edaf0-6413-11e8-8bfe-e021ee1a52b6.gif)

**Comment by gingerbeardman** [comment]
This works but formatting and linespacing is lost?

![2018-06-27 11_02_56](https://user-images.githubusercontent.com/49612/41967551-c2723e20-79f9-11e8-8b26-66085e84168c.gif)

Version 1.8 (152)

**Comment by glushchenko** [comment]
Fixed in build 154. Release file updated.

**Comment by gingerbeardman** [comment]
Ah, I see! Thanks

I'm not sure how I feel about markdown being parsed to show markdown code blocks? But that's another issue

**Comment by gingerbeardman** [comment]
Sorry another problem:

![2018-06-27 15_53_03](https://user-images.githubusercontent.com/49612/41981985-33c06dc2-7a22-11e8-9adb-99a4fdcb28f3.gif)

**Comment by glushchenko** [comment]
Please post original text here, i can not reproduce.

**Comment by gingerbeardman** [comment]
## Masters '98: Harukanaru Augusta
MASTERS '98 遥かなるオーガスタ
1997, N64

**Comment by glushchenko** [comment]
Fixed
