### ISSUE TITLE
Allow configuration of line spacing

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#262]
Compare...

## Ulysses
![screen shot 2018-05-30 at 12 21 03](https://user-images.githubusercontent.com/49612/40717377-01378518-6404-11e8-877d-5343e365f153.png)

## FSNotes
![screen shot 2018-05-30 at 12 21 50](https://user-images.githubusercontent.com/49612/40717405-1ca981d4-6404-11e8-9d81-0fc980effb41.png)

**Comment by gingerbeardman** [comment]
Very grateful, thanks!

**Comment by peavine** [comment]
I like this feature a lot. My vision is not the best and increasing the line spacing helps. I did have a question, though.

Right now, the size of the cursor is proportionate to the line height and, at the upper end of the line-spacing range, the cursor becomes quite large. Should the size of the cursor be proportionate to text size or line height? I suspect there's some convention for this but I couldn't find an app on my computer where I can adjust line spacing.

Thanks.

**Comment by jeff-h** [comment]
@peavine you can adjust line spacing in TextEdit, and the cursor behaves the same was as in FSNotes.

In my screen shot the line spacing is set to 2.0 in the dropdown second-from-the-right. You can see the tall cursor on the end of line 2.

![screen shot 2018-06-28 at 10 53 58 am](https://user-images.githubusercontent.com/841871/42003914-b2fa1b5c-7ac1-11e8-9392-e57b0b37dc60.png)

**Comment by peavine** [comment]
Thanks @jeff-h. I had looked at textedit but missed that, and it is exactly the same.

**Comment by glushchenko** [comment]
@peaine you are right completely, and i fixed cursor margin.

**Comment by peavine** [comment]
Installed 1.9 and the cursor size with large line spacing works well. Thanks.
