### ISSUE TITLE
iOS fsnotes: offline usage?

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#266]
Hi,

From what I read, macOS version of fsnotes can sync with the iOS version.  However, I wonder can iOS fsnotes do offline viewing and editing?

I have this question because I was testing a more heavy-weighted app Boostnote. It has macOS and iOS version and you can sync through Dropbox. However, there is no offline capability in iOS -- you need to be online to view the notes.

Would be great if someone with iOS fsnotes installed to clarify this.

Jake

**Comment by glushchenko** [comment]
Really? Lol. 

Electron = crap. Boostnote is electron app, FSNotes written on native Swift.

P.S. Of course FSNotes working offline with thousands notes.
