### ISSUE TITLE
search / filtering leniency

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#27]
I am used to nvALT's searches, which are pretty lenient. I think it searches across all notes for any which contain all the words entered in the search field, regardless of the order they appear.

For example, searching on "npm install" in FSNotes returns just four of my notes (which contain exactly those two words side-by-side), whereas nvALT returns nine results, including notes containing both the words but in any order.

Perhaps an even better idea would be fuzzy searching, which could take FSNotes well beyond nvALT. Have you seen FuseJS before?
http://fusejs.io

They now have an official Swift implementation, which might be interesting for FSNotes:
https://github.com/krisk/fuse-swift

**Comment by jeff-h** [comment]
Also, nvALT searches include the note title.

**Comment by glushchenko** [comment]
Thanks for pull request, @jeff-h. I have idea. Perhaps we should highlight searched words?
