### ISSUE TITLE
Todo Shortcut

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#272]
On the FSNotes Github page under releases the following is listed as a new feature:

Adds todo shortcut with toggle shortcut: ⌘ + g

On my computer the shortcut is ⌘ + 0

Thanks.

**Comment by glushchenko** [comment]
Sorry, "⌘ - 0" of course :)

**Comment by jeff-h** [comment]
Love this!

Just wondering though, is there a precedence or other rationale for using - and + for this? There's a few options in the "Emoji & Symbols" window that would be more attractive, to me at least eg  ☐ and ☑︎
