### ISSUE TITLE
[BUG] Context menu missing check marks

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#273]
select "smart quotes" context menu:

![screen shot 2018-06-27 at 15 54 52](https://user-images.githubusercontent.com/49612/41982107-7d022e76-7a22-11e8-974b-dd54da21bf34.png)

that menu should have check marks?

![screen shot 2018-06-27 at 15 58 29](https://user-images.githubusercontent.com/49612/41982303-ffe4bdfe-7a22-11e8-8c63-2084956d3184.png)

**Comment by peavine** [comment]
This doesn't seem to work for me. If I select the "Show Substitutions" menu item, the selections I make (remove check marks from Smart Links and Text Replacement) don't seem to stick after restarting FSNotes. Also, I don't see any check marks as shown in @gingerbeardman's graphic above.

**Comment by gingerbeardman** [comment]
I see this:
![screen shot 2018-07-09 at 22 48 55](https://user-images.githubusercontent.com/49612/42477775-589439c4-83ca-11e8-87a9-19e71a698719.png)

and this:
![screen shot 2018-07-09 at 22 49 21](https://user-images.githubusercontent.com/49612/42477783-60320012-83ca-11e8-919d-83490d4e6fa0.png)

**Comment by peavine** [comment]
This is what I see.

![fsnotes](https://user-images.githubusercontent.com/35905279/42478701-8b88310e-838a-11e8-8eab-d6b6443cccf3.gif)

**Comment by peavine** [comment]
@gingerbeardman. In your screenshot above of the context menu, there are check marks next to four items. If you remove these check marks and then restart FSNotes, do the settings stick? I'd like to disable all substitutions but haven't found a way to do this. Thanks.

**Comment by peavine** [comment]
I installed FSNotes 2.0 and all three of the issues noted in my post above have been fixed. Thanks.

**Comment by gingerbeardman** [comment]
Thanks!
