### ISSUE TITLE
Can't change external editor

### ISSUE THREAD

**Issue by davistech** [glushchenko/fsnotes#274]
Is there a way to change the external editor to something other than TextEdit? I use MultiMarkdown Composer and would like to select this. Other options would include bbEdit and Atom.

**Comment by peavine** [comment]
You can change the external editor in FSNotes preferences under the General tab. I don't have the editors you mention and can't say for sure if they would work.

**Comment by gingerbeardman** [comment]
I have mine set to BBEdit, works a treat.

![screen shot 2018-07-02 at 20 56 17](https://user-images.githubusercontent.com/49612/42183622-69c0f92a-7e3a-11e8-9093-73276bb4e889.png)

**Comment by glushchenko** [comment]
Just type editor name in preferences.

**Comment by davistech** [comment]
Thanks. I tried several of my editors and it works with bbEdit and Atom. Unfortunately does not work with MultiMarkdown Composer which is what I use on a daily basis.

**Comment by peavine** [comment]
I was curious and installed the standard (free) version of MultiMarkdown Composer from the app store. After changing the external editor in FSNotes preferences to "MultiMarkdown Composer" (no  quotes), I opened a txt and then an md note using the "open external" file command and both notes opened as expected. Perhaps the paid version of MultiMarkdown Composer works differently?

**Comment by jeff-h** [comment]
What would you hope for in Bitwriter that you're not seeing in FSNotes? @glushchenko is commendably receptive to ideas, and since its initial release FSNotes has added some really valuable features (to me) that nvALT doesn't have (eg the notes archive feature, and multiple note filesystem folders).

**Comment by gingerbeardman** [comment]
At this point Bitwriter is one screenshot on a tweet, so what it will be able to do is largely unknown.

**Comment by glushchenko** [comment]
I waited Bitwriter for three years. I do not think that this is a good idea anymore. If Brett wanted to do it, he would have done it for a long time ago.
