### ISSUE TITLE
[REQ] Handling ToDos across all Notes. 

### ISSUE THREAD

**Issue by dircadmin** [glushchenko/fsnotes#277]
I would love to be able to view all To Dos across all notes (or across notes within a folder).

Ideally it would show the ToDo line items in an extra note with a link to the note itself.

**Comment by clayreimann** [comment]
@dircadmin How will we be able to To-Done things? From what I can see both the edit and preview views are just webviews that show markdown. AFAIK the checkbox list on GH is not part of the general markdown spec.

I love the idea of being able to check things off (it's the major reason I'm not all in from Notes.app) but I'm not sure what the UX would look like.

Thoughts @gingerbeardman @CameronBanga?

**Comment by dircadmin** [comment]
@clayreimann for me, it's not about having a checkbox or not (where a checkbox would be nice indeed), but more about the visibility of ToDos in general. I'd love to see if there's open ToDos anywhere. I have many many notes, but without an indicator, I can't work with ToDos as I can't see them anywhere. 

A number in the list view of the count of open ToDos would be a beginning. And/Or a way to search for open ToDos.

**Comment by clayreimann** [comment]
Could any list item be a todo? Or do you use a particular character to make a todo?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Take look at this https://blog.github.com/2013-01-09-task-lists-in-gfm-issues-pulls-comments/

[X] OK
[ ] Maybe
[ ] No

**Comment by clayreimann** [comment]
Sure, but that's GFM; it's not in the commonmark spec. It's also not how todos are currently handled in FSNotes.

https://github.com/glushchenko/fsnotes/blob/fb7938de34b7f38b02af9c71a28dc0e6706f71ed/FSNotes/Helpers/TextFormatter.swift#L515-L531

**Comment by glushchenko** [comment]
I think it is possible to implement - [ ] and render checkboxes in textStorage. Added in personal roadmap.

**Comment by dircadmin** [comment]
How about listing open todos in the notes list? Would this also be possible to implement?
I really like the idea of todos, I just need a way to find them among all the notes.

**Comment by dircadmin** [comment]
Please, if possible also provide a way to search for notes with open todos.

**Comment by glushchenko** [comment]
“Open todos” is all notes started with “\n - “, right?

**Comment by dircadmin** [comment]
If you can toggle list items as todos, then every list item can be a open todo. So I would recommend to show the number of the todos (list items beginning with a "+") in the notes list and make a shortcut to list all notes with open todos, like searching for "+ ", just with a quick shortcut.

Of course if you change the todo to "- [ ]", then this would be the snippet to search for.

**Comment by gingerbeardman** [comment]
list items can also be specified with `-` or `*` or `+` or numerical, and maybe more

**Comment by dircadmin** [comment]
That's true, but if I "toggle todo", it changes to "+"

**Comment by glushchenko** [comment]
Added here: 

https://github.com/glushchenko/fsnotes/releases/tag/2.0

**Comment by dircadmin** [comment]
That was quick.. 

An Option to only show open ToDos in the sidebar item would be beneficial.

**Comment by thiemehennis** [comment]
Am I the only one having difficulties understanding the todo feature? I see brackets but don't see how they come back in the Todos view. There seems to be no documentation about this feature.

**Comment by gingerbeardman** [comment]
You use `- [ ]` in any note, and the Todos view just lists any notes containing that.

**Comment by thiemehennis** [comment]
ok, thanks for the clarification. In my installation they do not show up in the Todos view. This time I already restarted and checked and still not visible. No biggy, but just wanted to mention here.

**Comment by gingerbeardman** [comment]
![screen shot 2018-08-02 at 14 49 23](https://user-images.githubusercontent.com/49612/43587962-52750c20-9663-11e8-9b21-688d8595878e.png)


contents of note
```
- [ ] OK
- [ ] this is a test

- [X] done
- [ ] next
```

**Comment by thiemehennis** [comment]
this works if I paste it exactly as it is



but if I make a couple of todos myself, exactly as stated here (space
between brackets etc), then it does not show up.



should show up right? but it doesn't.

**Comment by gingerbeardman** [comment]
What locale is your mac set to? What language keyboard? Any other unique aspects to your setup?

**Comment by thiemehennis** [comment]
Dutch. Nothing particular I think. Normal QWERTY keyboard.
Cirkelmarkt - circulaire markt in Amsterdam Oud-West - And The People
<http://andthepeople.org>

**Comment by clayreimann** [comment]
Does it work as expected of you use the keyboard shortcut? (cmd+0)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
