### ISSUE TITLE
[REQ] Don't show the file path for storage when it's iCloud

### ISSUE THREAD

**Issue by clayreimann** [glushchenko/fsnotes#280]
I don't know, nor do I care, where the iCloud directory is on my Mac. If we're storing things in iCloud just say so and only show me the file path if I customize the default or archive storage locations.

**Comment by glushchenko** [comment]
Did you mean storage path in preferences?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
