### ISSUE TITLE
Desktop focus

### ISSUE THREAD

**Issue by iskrisis** [glushchenko/fsnotes#286]
Is there a way to have fsnotes work as overlay (iterm works this way)? 

When i run FSnotes it remembers desktop it is at and when i use shortcut to show it switches desktops if fsnotes are in different one. I am big user of desktops and i have FSnotes open all day and it would be so much more useful if it showed on all desktops since i wouldn't have to switch back to my original desktop to get back to work.

Thank you!

**Comment by jeff-h** [comment]
Control-click the FSNotes dock icon and tick Options > Assign To: All Desktops.

Or am I totally misunderstanding the problem? :)

**Comment by iskrisis** [comment]
OMG! Thank you so much!
My life is complete now. Please close this issue. I will take time to learn how to use MAC.
