### ISSUE TITLE
Night Mode setting in iOS has only a "Cancel" button

### ISSUE THREAD

**Issue by lorenzschmid** [glushchenko/fsnotes#290]
When choosing ti change the Night Mode from the setting menu in the iOS app, there is only a "Cancel" button in order to go back. This is confusing as one doesn't know if changes in the setting will be stored. Better would be to have either:

- No "Cancel" button but a "< Settings" lable insted

or:

- A "Cancel" button in the upper right corner
- A "Done" button in the upper left corner

The following screenshot indicates the current (confusing) state:

![img_2018-07-23t08-28-23](https://user-images.githubusercontent.com/3830671/43060860-02dde230-8e53-11e8-88d1-042c3a8dc01f.JPG)

**Comment by lorenzschmid** [comment]
The same actually counts for all settings with a menu ("Default Extension", "Default Keyboard In Editor" or "Font").

**Comment by glushchenko** [comment]
I think v2.0 fixed all this.
