### ISSUE TITLE
Improved Navigation in 2.0

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#291]
One of the new features in 2.0 is:

"Improves navigation (cmd and cmd-enter in sidebar, notes list and editor)"

I looked at the shortcuts readme file but didn't see anyting new. What is the improved navigation?

Thanks.

**Comment by gingerbeardman** [comment]
I think keyboard shortcuts file needs updating?

https://github.com/glushchenko/fsnotes/blob/master/Resources/Initial/FSNotes%20-%20Shortcuts.md

**Comment by glushchenko** [comment]
Maybe someone help with shortcuts readme?

**Comment by peavine** [comment]
I'll work on updating the keyboard shortcut readme. I'm a bit slow on stuff like this but I'll upload the updated readme in a few weeks.
