### ISSUE TITLE
FSNotes 2.0 quits when I click on a link.

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#292]
FSNotes 2.0 quits when I click on a link in a note. The following is one link I used as a test:

https://github.com/glushchenko/fsnotes

I've uploaded a text file with the report.

[crash_report.txt](https://github.com/glushchenko/fsnotes/files/2221428/crash_report.txt)

**Comment by peavine** [comment]
I installed FSNotes 2.0.1 and this issue is fixed. Thanks.

**Comment by glushchenko** [comment]
Thank you for bug report 🍻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
