### ISSUE TITLE
[REQ] cmd + delete should clear line when editor is focused, not delete the note

### ISSUE THREAD

**Issue by matthewmueller** [glushchenko/fsnotes#297]
I'd love to see the behavior to be closer to how nvalt / other editors currently works. If you're typing, `cmd + delete` will clear the line. Right now it's a bit too easy to delete a note.

If you're focused on the sidebar, I think it makes sense for `cmd + delete` to delete the note. This is the same behavior as nvalt. Though nvalt provides a helpful confirmation message.

Keep up the great work!

**Comment by glushchenko** [comment]
⌘ - return already removes current paragraph ... or not? Try fsnotes 2.0

**Comment by matthewmueller** [comment]
you are absolutely right! just pulled the latest tags and it's working exactly as I'd expect. Thanks a lot!
