### ISSUE TITLE
[REQ] open note in new window

### ISSUE THREAD

**Issue by wyaqoob** [glushchenko/fsnotes#301]
It would be great to be able to open a note in a new window, as in Apple's Notes app. This could be done through double-clicking a note on the list, and with a cmd+shift+o keyboard shortcut.

Also, I support someone else's suggestion that you provide a link for donations - I would like to support development beyond paying for the app store version.

**Comment by fturcheti** [comment]
This would be extremely useful in the situations where you're working on a note and need to pick references from other one(s).

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
