### ISSUE TITLE
[REQ] reduce height of notes list when 'Hide Preview' is on

### ISSUE THREAD

**Issue by wyaqoob** [glushchenko/fsnotes#302]
There is wasted space in the notes list when 'Hide Preview' is selected in preferences: each note in the list still takes up as much space as when the preview is on. Reducing the height of the display for each note title when Hide Preview is on would be great. It would allow the notes list to show more information, which I think is one of the main advantages of turning off the preview.

**Comment by glushchenko** [comment]
You can specify height for notes list in preferences.

**Comment by wyaqoob** [comment]
Apologies - my bad.
