### ISSUE TITLE
Pressing tab changes the font & colour

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#305]
The same issue as described in https://github.com/glushchenko/fsnotes/issues/113 has returned. When you press tab, the text changes and the background colour changes. This may be specific to RTF, not sure.

The screenshot in https://github.com/glushchenko/fsnotes/issues/113#issuecomment-366280505 probably describes it best.

**Comment by glushchenko** [comment]
Fixes in 2.0.4
