### ISSUE TITLE
v2.0: search changed

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#308]
Since v2.0 it seems that search words are additive; notes are filtered depending on whether they contain *any* of the search words.

Prior versions were subtractive; notes were only matched when they contained *all* the search words.

For me, this is a major regression; searching for a note containing multiple common strings is virtually impossible the current way. For example, using v2 a search in my notes for "@ # !" results in a huge number of matches, when really only five of my notes contain all those characters. V1.9 shows just the five results.

**Comment by glushchenko** [comment]
Sorry, search broken in this pull request :( https://github.com/glushchenko/fsnotes/commit/66b2d98bf2c518c7a404c7adeee3246f384add1b#diff-901d72d1a5a6e878d26e55f819542f8f

**Comment by jeff-h** [comment]
Thanks for digging that out 👍 Not fun, I'd guess.

**Comment by glushchenko** [comment]
Sorry, i uploaded wrong build. Please redownload and try again.

**Comment by jeff-h** [comment]
Fantastic, fixed! Thanks.
