### ISSUE TITLE
FSNotes 2.0.4 - screen elements hidden

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#309]
In FSNotes 2.0.4 elements of the interface are partially hidden. For example:

* When the sidebar is open, the search and create bar and the share menu are mostly hidden.

* When the sidebar is closed, the search and create bar is fully visible but the share menu is mostly hidden.

Also, the margin recently added at the bottom of the editor window is a gray color instead of the white color of the rest of the editor window.

I can upload a screenshot if that would be helpful.

Thanks.

**Comment by jeff-h** [comment]
> Also, the margin recently added at the bottom of the editor window is a gray color instead of the white color of the rest of the editor window.

Incidental to this issue, but don't assume the note background is white. It can be changed in prefs. The newly-added bottom margin should really take on that colour, not white.

**Comment by peavine** [comment]
This issue merged in #310
