### ISSUE TITLE
FSNotes Title Bar and Hidden Window Elements

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#310]
I installed FSNotes 2.0.4 and it appears that a title bar has been added. If so, this is awesome news for me, as I've wanted something that would more clearly indicated when FSNotes has the focus (my closed issue 189). 

I often work with the sidebar closed but I often wish there was some indication as to the folder that I'm currently in. Perhaps this could be included in the title bar, much like macOS Mail (e.g. the name of the folder and the number of notes it contains).

My knowledge of interface design is sorely lacking but I'll be interested to see how this works out.

**Comment by jeff-h** [comment]
Could you take a screenshot of what you mean? My 2.0.4 looks the same as usual.

**Comment by peavine** [comment]
I have included a screen video of FSNotes 2.0.4. I did a video, rather than a screenshot, so that I could show FSNotes with the sidebar open and closed.

The video shows about 4 seconds of 1) the sidebar is open and FSNotes does not have the focus, 2) the sidebar is open and FSNotes has the focus, and 3) the sidebar is closed and FSNotes has the focus.

The changes from earlier versions are:

* There is a title bar extending across the entire top of the app.

* The search and create bar, the name of the note in the edit window, and the share menu are partially hidden when the sidebar is open.

* The name of the note in the edit window and the share menu are partially hidden when the sidebar is closed.

Surprisingly, the margin at the bottom of the edit window is shown in the video as the same color as the rest of the edit window (I have set it to be white). Normally the margin is a light gray. 

Thanks.

![fsnotes_screen](https://user-images.githubusercontent.com/35905279/43356983-241826ce-922f-11e8-8666-c3f78f8cc655.gif)

**Comment by peavine** [comment]
I installed FSNotes 2.0.0 and this is a screen video with the same views (1 thru 3) noted above.

![fsnotes_200](https://user-images.githubusercontent.com/35905279/43357665-054a6f30-923a-11e8-8af1-14335485fa98.gif)

**Comment by jeff-h** [comment]
Wow, so weird. There is not supposed to be a title bar in 2.0.4. I wonder how that happened! Did you build it yourself, or download from from the App Store or Github?

**Comment by peavine** [comment]
That's unfortunate--I was excited about getting a title bar. I downloaded 2.0.4 from Github. I'm running Sierra, which shouldn't make a difference.

**Comment by peavine** [comment]
I installed 2.0.5 and this works fine. Thanks.
