### ISSUE TITLE
Tabs cause unpredictable line wrapping

### ISSUE THREAD

**Issue by jrcii** [glushchenko/fsnotes#311]
I frequently use tab-based tables in my documentation. FSNotes, like nvALT, and several other note-taking applications, are using an editor that makes this impossible because of seemingly arbitrary line-wrapping on lines that use tabs.

Here's an example of what I need to do (attached as example.txt)
[example.txt](https://github.com/glushchenko/fsnotes/files/2238129/example.txt)
:

![picture1](https://user-images.githubusercontent.com/6308848/43357845-9fba95d4-9255-11e8-91ff-6b465570e2e9.png)

Here is how this tab-based list is rendered in FSNotes:

<img width="758" alt="screen shot 2018-07-28 at 11 02 55 am" src="https://user-images.githubusercontent.com/6308848/43357858-e158be30-9255-11e8-8378-96ca48045dad.png">

I don't know anything about OS X development, but it may be related to this:
https://stackoverflow.com/questions/14278119/premature-line-wrapping-in-nstextview-when-tabs-are-used
or
https://github.com/ForkIssues/Tracker/issues/189#issuecomment-357166284

I see that even the original Notational Velocity is doing this in High Sierra whereas in El Capitan it did not.

**Comment by jrcii** [comment]
I've been checking every update for a year hoping I could finally use my tab-based tables in FSNotes. Does anyone know if it's on the roadmap?

**Comment by gingerbeardman** [comment]
Thanks for bringing this back up! I'll look into it.

Just to confirm, you don't actually want your tab-based layout to render as a table in preview mode, you just want the tabs to be honoured in edit mode. Right?

**Comment by jrcii** [comment]
@gingerbeardman Thank you so much! That is correct.

**Comment by jrcii** [comment]
Hi,

So -- lol -- another year has gone by and another year that I still don't have a usable note taking app on OS X which died the day Notational Velocity stopped working. FSNotes is AMAZING! I've been tracking the progress, and wow, so much work has gone into it. It's really impressive.

Sadly, there's only one feature I've needed for years and no note-taking app including FSNotes even with the updates can do. I need tab-based tables to work right. Ever since El Capitan, most text editors on OS X do this weird thing where, when a line contains too many tabs, it starts wrapping at an inexplicable place.

Although every single note-taking app I've used has this behavior, somehow TextEdit does not. Look at the comparison.

I know you're busy and no one else seems to want this but I swear if you can fix this for me I will buy you a case of beer. Thank you!!
![example](https://user-images.githubusercontent.com/6308848/101730012-3a6ab600-3a87-11eb-8dc5-395e3cb9563d.png)
[example.txt](https://github.com/glushchenko/fsnotes/files/5670695/example.txt)

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by jrcii** [comment]
Hi, I'm still seeing this in macOS 10.14.6. Maybe the updated frameworks are changing (positively) the behavior in newer versions of OS X?
![tabs](https://user-images.githubusercontent.com/6308848/125201966-70e7f980-e23f-11eb-804c-97c62e3bf41d.png)

**Comment by glushchenko** [comment]
Ah, actually only for markdown ATM. RTF on screen?

**Comment by jrcii** [comment]
Here's the result after pasting this tab format into a "New" (plain) vs "New RTF". The format is in the note title:
![Screen Shot 2021-07-11 at 12 07 31 PM](https://user-images.githubusercontent.com/6308848/125202240-accf8e80-e240-11eb-8934-c705421f9f41.png)
![Screen Shot 2021-07-11 at 12 07 11 PM](https://user-images.githubusercontent.com/6308848/125202241-accf8e80-e240-11eb-903b-5839a64ee968.png)

**Comment by glushchenko** [comment]
What is "New"? Please open Preferences, change file format to markdown and try again. Thank you.

**Comment by jrcii** [comment]
Sorry I meant "File > New" (versus "File > New RTF"). In preferences, the format was already set to Markdown:
![Screen Shot 2021-07-11 at 12 21 12 PM](https://user-images.githubusercontent.com/6308848/125202665-8579c100-e242-11eb-891d-b9b59380bb90.png)

Thank you by the way for your time and attention to this issue. FSNotes is my favorite editor and I've been looking forward to this use case for a while.

**Comment by glushchenko** [comment]
At this moment tab interval = 40, tabs quantity = 12

Example:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/1089917/125202717-8e3bb880-e27d-11eb-9b0f-8629fea7a7d1.png">

If old docs tab != 40, then you can have troubles. Just reformat it.

**Comment by jrcii** [comment]
In this example I use only tabs (no spaces) to separate the mock words, typing them from scratch (no copy/paste or old file)
![Screen Shot 2021-07-11 at 12 34 16 PM](https://user-images.githubusercontent.com/6308848/125203011-7a279500-e244-11eb-8036-1e701014e869.png)
:

If you see the comparison shot in my original post, this prevents you from constructing arbitrarily-sized tab-based tables. From what I've seen, my hunch is that this is rooted in some issue with macOS's UI SDKs although I don't do that type of programming so that's just a wild guess.

**Comment by glushchenko** [comment]
I see extra tab on second line, nothing strange. Can you post file sample from the screen?

**Comment by jrcii** [comment]
Yes, it was only one tab on my keyboard but the editor is formatting it that way. Note I also didn't insert any line breaks. Here's the file in question (zipped
[plain test.markdown.zip](https://github.com/glushchenko/fsnotes/files/6797423/plain.test.markdown.zip)
)

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/5b2/FSNotes_v5b2.zip
