### ISSUE TITLE
Margins in editor window do not match color setting in preferences

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#313]
In preferences, I have set the note color to black and the background to white. As shown in the screenshot below, there are gray margins in the editor window above and below the note name and at the bottom of the editor window. Thanks.

FSNotes 2.0.5

![fsnotes](https://user-images.githubusercontent.com/35905279/43424286-c2f6182a-9403-11e8-87c8-c1e7f1036524.png)

**Comment by gingerbeardman** [comment]
> I have set the note color to black and the background to white

these are defaults?

FWIW I do not see these grey margins

**Comment by glushchenko** [comment]
How to reproduce? Tests in Sierra and High Sierra.

**Comment by peavine** [comment]
I'm running Sierra. I've included below a screen video in which I change note color/background from black/white to blue/yellow and the margins mentioned above remain gray. 


![screen](https://user-images.githubusercontent.com/35905279/43426597-0e10248e-940b-11e8-9db0-9e83e3a87f16.gif)

**Comment by gingerbeardman** [comment]
I was just wondering if you were using defaults or had changed to some other black/white?

Does this happen with trashed prefs?
Does this happen on a new/guest account?

Very odd nonetheless!

**Comment by peavine** [comment]
I tried the following without success:

* Delete preference files.
* Log in as guest.
* Disable all accessibility display options (I had enabled a few).

I appear to be the only user with this issue. So, just for now, I went back to FSNotes 2.0.3 from the app store, which works fine.

**Comment by peavine** [comment]
I just upgraded to Mohave and this issue is fixed. :)
