### ISSUE TITLE
CMD + BACKSPACE does not work (to delete a note)

### ISSUE THREAD

**Issue by thiemehennis** [glushchenko/fsnotes#315]
Running High Sierra on an MBP Mid 2010. deleting a note using the trackpad or mouse is clearly not desired :)

**Comment by thiemehennis** [comment]
I tried delete as well. So CMD + fn + ← and normal delete fn + ←.

**Comment by gingerbeardman** [comment]
I think perhaps current focus could be better represented?

<kbd>Return</kbd> steps towards the right (into)
<kbd>⌘</kbd>+<kbd>Return</kbd> steps towards the left (out of)

but it's not easy to see where which column you are in (except if you can see the cursor in the note)

left (folders/tags)
![screen shot 2018-08-01 at 13 39 36](https://user-images.githubusercontent.com/49612/43522317-eb34e0c6-9590-11e8-8420-ab84d067a752.png)

middle (notes)
![screen shot 2018-08-01 at 13 39 40](https://user-images.githubusercontent.com/49612/43522322-edcb0806-9590-11e8-95d5-fee9027a17a3.png)

right (note)
![screen shot 2018-08-01 at 13 40 15](https://user-images.githubusercontent.com/49612/43522327-f08587e2-9590-11e8-862b-8b98ee2f8e4b.png)

**Comment by thiemehennis** [comment]
nope. unfortunately not successful. I do have the focus on the middle column, but indeed you would expect that focus (like in NValt) in the note itself (right) should also allow deleting. Anyhow, I do have the focus in the middle column on the note I want to delete.

![image](https://user-images.githubusercontent.com/2821939/43522930-18b2a95c-959b-11e8-9054-01a62a5248d8.png)

**Comment by thiemehennis** [comment]
sorry guys. Closing the app and reopening it... seems to solve most problems. Like this one.. :-/
