### ISSUE TITLE
[REQ] Improve selected/focus highlights

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#316]
From: https://github.com/glushchenko/fsnotes/issues/315#issuecomment-409561580

<kbd>Return</kbd> steps towards the right (in)
<kbd>⌘</kbd>+<kbd>Return</kbd> steps towards the left (out)

but it's not easy to see which column you are in (except if you can see the cursor when in the note)

I think perhaps current focus could be better represented through highlight colours?

- blue = "selected with focus"
- grey = "selected _without_ focus"

**left** (folders/tags list)
- current folder should be blue

![screen shot 2018-08-01 at 13 39 36](https://user-images.githubusercontent.com/49612/43522317-eb34e0c6-9590-11e8-8420-ab84d067a752.png)

---

**middle** (note list)
- OK, focus is obvious and correct (note)
- this is what you are looking for to delete using <kbd>⌘</kbd>+<kbd>Backspace</kbd>

![screen shot 2018-08-01 at 13 39 40](https://user-images.githubusercontent.com/49612/43522322-edcb0806-9590-11e8-95d5-fee9027a17a3.png)

---

**right** (note content)
- middle should be grey?
- arguably you should be able to delete the note you are in, if you can copy the note you are in?

![screen shot 2018-08-01 at 13 40 15](https://user-images.githubusercontent.com/49612/43522327-f08587e2-9590-11e8-862b-8b98ee2f8e4b.png)

**Comment by jeff-h** [comment]
I think it would also be cool if you could use <kbd>⌘</kbd>+<kbd>left/right arrow</kbd> to navigate — I never realised <kbd>return</kbd> and <kbd>⌘</kbd>+<kbd>return</kbd> did anything in this context.

**Comment by peavine** [comment]
I like @gingerbeardman's suggestion:

blue = selected with focus
grey = selected without focus

Keyboard shortcuts to navigate are important but I'm not sure Command-Left Arrow and Command-Right Arrow would be the best choice. I say that because these shortcuts are commonly used (including in FSNotes) as a document shortcut:

Command–Left Arrow: Move the insertion point to the beginning of the current line.

Command–Right Arrow: Move the insertion point to the end of the current line.

https://support.apple.com/en-us/HT201236

**Comment by gingerbeardman** [comment]
Good point! If we think of each column as tabs, how about (from previous apple link)

> Command–Left Bracket ([): Go to the previous folder.
> Command–Right Bracket (]): Go to the next folder.
> Command–Up Arrow: Open the folder that contains the current folder.
> Command–Control–Up Arrow: Open the folder that contains the current folder in a new window.
> Command–Down Arrow: Open the selected item.
>

**Comment by peavine** [comment]
My preference would be to use Command-Left/Right Bracket to navigate. Currently they are shortcuts for Format > Shift Left/Right, but perhaps these could be changed to something different.

Command-Up/Down Arrow are fairly important document shortcuts that move the cursor to the beginning and end of a document. I wouldn't change those.

**Comment by gingerbeardman** [comment]
In Safari, I change between tabs using Cmd+Shift+Left/Right it just occurred to me now that might be suitable?

**Comment by peavine** [comment]
That's certainly a possibility. If the FSNotes menu bar contained a menu item for this (as there is in Safari), then users would have the option to change the shortcut to whatever they like.

**Comment by jeff-h** [comment]
> My preference would be to use Command-Left/Right Bracket to navigate. Currently they are shortcuts for Format > Shift Left/Right, but perhaps these could be changed to something different.

In code editors at least, these shortcuts are very widely expected to do exactly what they currently do in FSNotes — ie indent / de-indent. Even Xcode has this... thus I'd strongly hope they stay as-is because I write code a lot lol

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1
