### ISSUE TITLE
[REQ] Ability to delete the note you're currently editing

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#317]
From: https://github.com/glushchenko/fsnotes/issues/315#issuecomment-409561580

Also see: https://github.com/glushchenko/fsnotes/issues/303

<kbd>Cmd</kbd>+<kbd>Backspace</kbd> should delete note being edited when note has focus. 

Currently it is disabled.

**Comment by peavine** [comment]
The shortcut key to delete a note varies depending on whether the preference option "Focus in editor when select note" is enabled and whether the focus is in the notes list or editor. Thus:

1) Preference option "Focus in editor when select note - enabled
Focus - notes list
Shortcut to delete note - Command-Option-Delete

2) Preference option "Focus in editor when select note - enabled
Focus - editor
Shortcut to delete note - Command-Option-Delete

3) Preference option "Focus in editor when select note - disabled
Focus - notes list
Shortcut to delete note - Command-Delete

4) Preference option "Focus in editor when select note - disabled
Focus - editor
Shortcut to delete note - None (instead first move focus to notes list then use Command-Delete).

It makes sense that Command-Delete should delete the note in situation 4 but that shortcut is already in use to delete from the cursor to the beginning of the line.

**Comment by gingerbeardman** [comment]
I usually use Backspace not delete. Are they interchangeable in these circumstances?

**Comment by peavine** [comment]
It had been my understanding that Apple defines the backspace key as the delete key? The FSNotes shortcut readme takes this approach. 

https://support.apple.com/en-us/HT201236

**Comment by gingerbeardman** [comment]
Interesting, it seems that at some point since my keyboard was new they have unified both keys.

My keyboard has both backspace and delete (which interestingly has the chunky arrow pointing the other way) and looks a bit like this:

![screen shot 2018-08-01 at 20 31 05](https://user-images.githubusercontent.com/49612/43544127-e3bd40c0-95c9-11e8-8e15-f78c201bf88a.png)

**Comment by peavine** [comment]
It was always so simple in the PC world--there was a backspace key and a delete key and everyone knew which did what. Anyways, just to clarify, I'll change delete to backspace in what I wrote above.
