### ISSUE TITLE
[BUG] Deleting notes should keep cursor in position

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#320]
1. Select a bunch of notes to delete, working your way _down_ the list of notes
2. Delete the notes

Expected
- cursor should maintain position (move up) in the notes list

Actual
- cursor stays way down the list

Animation
- select notes
- delete notes
- cursor should be on the one remaining "untitled" note

![2018-08-02 14_20_52](https://user-images.githubusercontent.com/49612/43586370-617951ee-965f-11e8-8aa6-e295db991e9f.gif)

**Comment by peavine** [comment]
@gingerbeardman. After "expected" did you mean to say that the cursor should move down in the notes list?

**Comment by gingerbeardman** [comment]
No, but maybe my animation isn't so clear? I kind of suspected that which was why I summarised what it showed.

But if you consider the cursor moves as follows:
1. Untitled Note 7
2. Untitled Note 1
3. Tips

I'd expect it to be:
1. Untitled Note 7
2. Untitled Note 1
3. Untitled Note (the note that was directly below Untitled Note 7 before the mass delete)

Does that make any more sense?
