### ISSUE TITLE
barriers to adoption: import from nvalt or simplenote? encryption?

### ISSUE THREAD

**Issue by jonchui** [glushchenko/fsnotes#321]
I've been using NvAlt backed by simplenote, with locally encyrpted notes. 

Is there any way to 
- import from nvalt / simplenote
- encrypt the notes/files before we saved them to icloud?

**Comment by gingerbeardman** [comment]
- nvalt: Select All and Export, then drag the resulting files onto FSN
- iCloud is encrypted in transit and on the server: https://support.apple.com/en-gb/HT202303

**Comment by flowchartsman** [comment]
Point of clarification: you need to drag to a particular document **folder**.

**Comment by perifer** [comment]
Here is a very rough PHP-script I used to rename the files in a simplenote export (e.g `0a43df45-0519-4947-90a0-8c4a0ef16e1d.txt` -> `my title.txt`). Might be useful for someone who also have a lot of notes:

https://gist.github.com/perifer/2a12a6b5e9e250cb4d8200aaf04185b7

**Comment by bradydjohnson** [comment]
Which folder?
