### ISSUE TITLE
Note list appears blank until escape is pressed

### ISSUE THREAD

**Issue by edwardloveall** [glushchenko/fsnotes#323]
When opening FSNotes, the note list will initially be empty. If I escape, the notes appear again.

**Comment by peavine** [comment]
If you have selected an empty folder in the sidebar, then no notes will be shown in the notes list. Typing the escape key shows every note in every folder in the current storage area. There could be other reasons for what you're seeing, but this is most likely.

You can set the default storage area in FSNotes preferences, and you may want to see what that is set to.

**Comment by edwardloveall** [comment]
Thanks for the response @peavine 😄 I have it currently set to a folder with lots of notes inside of it, so I don't _think_ that's it. Happy to try other things, send videos, or share a screen.

**Comment by gingerbeardman** [comment]
a screenshot of your initial FSN window would help :)

**Comment by edwardloveall** [comment]
Absolutely! I resized it a little, but otherwise this is what it looks like:

![fsnotes](https://user-images.githubusercontent.com/49549/43680251-efa336ec-9803-11e8-9e65-8c986df15a32.png)

**Comment by peavine** [comment]
A screenshot with the sidebar visible would be better. From the top menu bar select:

View > Hide/show sidebar

**Comment by edwardloveall** [comment]
Ah ha! I believe I just figured it out. Apologies @peavine you were right all along. I had `ToDo` selected in the sidebar and I didn't know it. I thought you meant Folder like a directory in the path that I store all my notes. Not sure how I got here. Thanks for the assist.

**Comment by edwardloveall** [comment]
Screenshot with sidebar for posterity

![fsnotes with sidebar](https://user-images.githubusercontent.com/49549/43680477-92891d04-9809-11e8-9dc7-a3cba358aaba.png)

**Comment by jeff-h** [comment]
I reckon it could be cool to have the sidebar folders listed in a dropdown at the top of the notes column when you hide the sidebar.
