### ISSUE TITLE
[REQ] Indication of current folder 

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#324]
At the end of closed issue #323, @jeff-h wrote as follows:

"I reckon it could be cool to have the sidebar folders listed in a dropdown at the top of the notes column when you hide the sidebar."

Because I normally use FSNotes with the sidebar closed, it would be helpful to have some indication of the currently-selected folder. A dropdown list, as suggested by @jeff-h, would be great. Another option might be an unobtrusive popover that provides pertinent information about a note including its folder.

I don't know enough about interface design to offer something specific, but just wanted to raise this as a possible enhancement.

**Comment by jeff-h** [comment]
Great idea! Though I've realised you wouldn't want to obscure the very topmost matching notes while you enter search words — after all, the notes at the top of the list are the ones you most likely want to open. Tricky one though — I can't think of a nicer solution.

**Comment by gingerbeardman** [comment]
Yes, I don't want the drop down either. I just included the image for reference that GitHub has solved a similar problem

**Comment by peavine** [comment]
Apparently I misunderstood what @jeff-h was proposing or perhaps I don't understand what @gingerbeardman is proposing.

My thought was a simple one--that FSNotes should show in some way the currently-selected folder (or item) when the sidebar is closed. A very basic example of this would be to show both the name of the folder and the note name at the top of the editor window when the sidebar is not visible. Thus, if the selected folder is "Addresses" and the note name is "Peavine", the following would be shown at the top of the editor window:

Addresses/Peavine

I didn't understand what @jeff-h was proposing and shouldn't have quoted him. Sorry about that.

**Comment by gingerbeardman** [comment]
Here's a _mockup_ of my suggestion:

![fsn-blog](https://user-images.githubusercontent.com/49612/43721140-eaf9fd88-9989-11e8-9a2c-3f8fe85a1d43.png)

and with Alt held down:

![fsn-all](https://user-images.githubusercontent.com/49612/43721150-efb795a6-9989-11e8-9669-3037fe3ec0c7.png)

**Comment by gingerbeardman** [comment]
I think this mockup is the approach @peavine is suggesting?

![screen shot 2018-08-06 at 15 05 13](https://user-images.githubusercontent.com/49612/43721373-7ea9434a-998a-11e8-8ab4-2189c458b601.png)

**Comment by peavine** [comment]
@gingerbeardman. Thanks for clarifying that and for the mockups, which are very helpful.

I like your suggestion. It provides the folder information and enhances search.

Your first mockup of my approach is exactly what I had in mind. I hadn't give any thought to what would be shown if there was no notes list.

**Comment by jeff-h** [comment]
@gingerbeardman do you think there'd be any implication that if you hold down <kbd>alt</kbd> then the note search/creation will happen in the folder but if you don't hold it down it will go somewhere else?

FWIW this pic hopefully illustrates my previous suggestion. I don't hold strongly to it though.

![screen shot 2018-08-07 at 10 38 04 am](https://user-images.githubusercontent.com/841871/43744509-72414ed2-9a2e-11e8-8e64-5b51b7ad9ec2.png)

**Comment by gingerbeardman** [comment]
<kbd>Alt</kbd> is the key that changes the behaviour of lots of commands from Finder onwards. It would have to be in the documentation along with <kbd>Cmd</kbd>+<kbd>Enter</kbd> etc.

Maybe we could've a lozenge in the search field like Finder?

![screen shot 2018-08-06 at 23 51 54](https://user-images.githubusercontent.com/49612/43744828-cb41f104-99d3-11e8-973d-cf9366972bbf.png)

**Comment by buddax2** [comment]
how about showing the current project in the title but only when the mouse cursor is over it?

![preview](https://media.giphy.com/media/1qbkcFnKcFl0mWjky8/giphy.gif)

**Comment by glushchenko** [comment]
Looks good, but here not enough space for  tags IMO

**Comment by buddax2** [comment]
@glushchenko I do not insist. Maby you're right and this may look too messy. But I would like to see here is some preview mode indicator. Just for example:

![tags](
https://duaw26jehqd4r.cloudfront.net/items/3x2l103t1A2s092L1w3d/Screen%20Shot%202018-10-27%20at%2015.08.02.png?v=b024dffe)

**Comment by buddax2** [comment]
@peavine it can be something like this:

![folders](
https://duaw26jehqd4r.cloudfront.net/items/0K1y1S140E2B37341e1P/Screen%20Shot%202018-10-28%20at%2018.42.13.png?v=4b48e9c5)

**Comment by peavine** [comment]
@buddax2. That's excellent--especially combined with the hidable view to have the clean UI.

**Comment by gingerbeardman** [comment]
Aside: I'm trying transition to a flat,single folder structure. Using only tags to navigate.

**Comment by buddax2** [comment]
@gingerbeardman I also like the idea of using just tags. That's why I think we need to add filtering by tags. Type into the search field: #tag1, #tag2 will show only notes with such tags and notes with such text inside.

**Comment by glushchenko** [comment]
@buddax2 i think title height should be equal search height and sidebar top margin. After last merge it's not equal.

Before:
<img width="1299" alt="screen shot 2018-10-29 at 22 33 21" src="https://user-images.githubusercontent.com/1089917/47678594-de0beb80-dbca-11e8-9bb7-8b4f0b7f6324.png">

After:
<img width="1242" alt="screen shot 2018-10-29 at 22 35 52" src="https://user-images.githubusercontent.com/1089917/47678679-072c7c00-dbcb-11e8-8dd9-14d29d10a639.png">

**Comment by buddax2** [comment]
@glushchenko I will fix that

**Comment by glushchenko** [comment]
Thank you for contribution.

**Comment by buddax2** [comment]
does it look OK?

![](
https://duaw26jehqd4r.cloudfront.net/items/2q2w3Z2b2H3j0j0C2L2j/Screen%20Shot%202018-10-29%20at%2022.44.26.png?v=9f98b031)

![](
https://duaw26jehqd4r.cloudfront.net/items/2b0R070T0w0g081T2a14/Screen%20Shot%202018-10-29%20at%2022.43.35.png?v=8ce9796a)

![](
https://duaw26jehqd4r.cloudfront.net/items/0l1f3I1r0Z242O2H0k1s/Screen%20Shot%202018-10-29%20at%2022.43.25.png?v=a9fec599)

Please see this screenshot. Here the title bar has the same height as the search bar.
![](
https://duaw26jehqd4r.cloudfront.net/items/3s2p2j3Z2k143R3P1Y1C/Screen%20Shot%202018-10-29%20at%2022.48.25.png?v=78dc4aa0)

**Comment by glushchenko** [comment]
Excellent 👍🏻

**Comment by buddax2** [comment]
btw, I had an idea to set editor view's appearance to Light when we are in preview mode. And then switch back to the current appearance in edit mode. What do you thing?

![](
https://duaw26jehqd4r.cloudfront.net/items/041b0T2e2y2F2G3W232C/Screen%20Shot%202018-10-29%20at%2022.57.41.png?v=72658403)

**Comment by glushchenko** [comment]
#1127
