### ISSUE TITLE
[REQ] Window to change width as sidebar and note list visibility is changed

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#329]
it would be great if the note pane could maintain the same width as I hide the sidebar and/or notes list

Currently the note pane width is reduced as sidebar and/or notes list visibility is changed.

**Comment by peavine** [comment]
@gingerbeardman. Right now the overall width of FSNotes remains static when the sidebar and notes list are shown or hidden. If I understand correctly, you would change this behavior.

I looked at some other apps--including macOS Notes, Safari, Preview, and the Finder--and they all maintain the same overall width when a sidebar or similar window component is opened or closed. I think (but am not sure) that I would like FSNotes to work in the same manner, just as it does now.

**Comment by gingerbeardman** [comment]
I see your point. Agreed
