### ISSUE TITLE
iOS companion app

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#33]
I've looked at many iOS apps hoping to find a good companion for FSNotes, but without purchasing numerous different apps it's hard to find anything that will work well with an iCloud folder full of document files.

Can anyone recommend one? Till now I used Simplenote for iOS but that was never ideal for me because:

a) it required me to sync my notes to a proprietary service which contradicts one of the major reasons I preferred nvALT (and now FSNotes) in the first place.
b) it looks like it might be going to slowly die (no new developer signups allowed now) which is exactly why I don't want a proprietary format for all my notes
c) it constantly removed all my RTF formatting, even from my originals on my Mac

If nobody can recommend an app — @glushchenko any chance you'd consider an FSNotes iOS version? 👍 Now that would be awesome :) I for one would gladly buy it even if it were also open source.

**Comment by glushchenko** [comment]
Yep, @jeff-h, iOS FSNotes planned with iCloud sync. I think it is possible in future, with symbolic price.

**Comment by jeff-h** [comment]
sounds awesome :)
