### ISSUE TITLE
Search text input pauses on first character

### ISSUE THREAD

**Issue by donpark** [glushchenko/fsnotes#331]
When I type into search text input box, there is a delay of sort after first character that prevents subsequent characters from being typed.

So typing "Now" a character at a time, "N" is accepted but "ow" is ignored. If I wait a bit then typing "ow" is accepted. In contrast, there is no delay if I paste in the word "Now".

Moving search task to another thread should help. Also delaying search until a reasonable interval without key activity will reduce need to spawn searches only to abort few hundred milliseconds later.

**Comment by peavine** [comment]
FWIW, I do not experience this on a base 2012 mac Mini running Sierra. 

I wonder if this issue is dependent on the number or length of notes in the selected folder. I seldom exceed 20 notes in a folder and most notes are between 10 and 50 lines in length.

**Comment by donpark** [comment]
> I wonder if this issue is dependent on the number or length of notes in the selected folder. I seldom exceed 20 notes in a folder and most notes are between 10 and 50 lines in length.

Could be. I have 5000 notes from nvALT, about 10mb in size. But then I had no problem searching them with my own JS-based clone of nvALT that stored the notes in IndexedDB.

**Comment by jeff-h** [comment]
@donpark I really doubt this is due to you having 5K notes. I only have 1.5K but they're 10MB total like yours and search is instant for me. Are you in a position to build FSNotes on your own machine, by any chance? It might be possible to pin down the issue that way.

Alternatively, can you clone just half your library to another location and try FSNotes with the subset?

**Comment by donpark** [comment]
will do when I get some hacktime. for now, I've gone back to nvALT.

**Comment by glushchenko** [comment]
Hello, guys! Vacation ended and i continue FSNotes development.

In 2.0.6 search working in background thread. @donpark, please try new build.

https://github.com/glushchenko/fsnotes/releases/download/2.0.6/FSNotes_2.0.6.zip

**Comment by donpark** [comment]
@glushchenko 2.0.6 fixed it. No more pause after first character.
