### ISSUE TITLE
[BUG] Keyboard shortcut to external editor doesn't work while in FSNotes Mobile sync

### ISSUE THREAD

**Issue by akufta** [glushchenko/fsnotes#332]
Double clicking + shortcut doesn't open external editor when it's saved like this:
![screen shot 2018-08-13 at 5 35 47 pm](https://user-images.githubusercontent.com/9098929/44061758-534f6c2a-9f1f-11e8-83fe-2b1c79c701e4.jpg)

If you go manually to File Open external, it works. 

Great app and work on this!
 I bought it on both platforms and am excited for its progress.

**Comment by glushchenko** [comment]
Please provide more details. Double clicking "+" ? For external editor works only one shortcut and it is "command + control + e".

**Comment by akufta** [comment]
all good now! I think I messed up the shortcut when I tried again. My bad!!!
