### ISSUE TITLE
[REQ] nvAlt search semantics for [[wiki links]]

### ISSUE THREAD

**Issue by gmenzel** [glushchenko/fsnotes#333]
Hi there!

Both nvAlt and [The Archive](https://zettelkasten.de/the-archive/) implement wiki links with the following logic:

 - clicking on a link of the form [[foo]] means execute a search for "foo"
 - If the name of one of the notes in the search results begins with "foo", select that note; otherwise select no note.

This allows groups of notes to be referenced by a wiki-link search. It also allows you to implement stable links by prefixing the name of each note with a unique id, and then using that id as the wiki-link text. This means you can rename a note without breaking links to that note.

For example, if I have a note named "201808151059 Snippets", I can link to that note with the link 
"[[201808151059]]". If I then later rename the note to "201808151059 Swift Snippets", the link "[[201808151059]]" will continue to link to that note.

**Comment by glushchenko** [comment]
What's wrong with the current implementation?

**Comment by gmenzel** [comment]
Huh, it wasn't working when I posted this request. Clicking on a wiki-link that didn't correspond exactly to a note's name did nothing. After today's update it's working as desired — thanks!

**Comment by gmenzel** [comment]
Actually I'm now noticing that as of 2.0.7, the search is interrupted by white space. I.e., clicking on 

[[2018-08-16 #log]]

only initiates a search for "2018-08-16", not for "2018-08-16 #log". It would be great if it simply search for whatever was in the brackets.

**Comment by brianwood2782** [comment]
Hey @glushchenko, thanks for committing your time to such an awesome app! This is my first time ever making a comment on Github.

I love FSNotes so much, and this feature is a godsend. However, I believe it still isn't implemented properly or broke after an update (I'm using 4.2.3): if you click on a `[[Link]]` inside a note, FSNotes will populate the search box with `Link` but all notes containing `[[Link]]` will be hidden. Not only all notes with links are themselves hidden, it "overpowers" normal text if they have the same text and FSNotes will hide both. 

For example, if I have note A mentioning `Bill Gates` somewhere and I click on a `[[Bill Gates]]` link on note B, it will find note A. But if I add `[[Bill Gates]]` to note A and click on it, FSNotes won't find note A neither note B when the point would be to find _both_ notes.

I think links are the most contextual element of a search (other than maybe the first line) as the point to use them is to allow proper cross-linking between notes. I used words to facilitate the example, but in reality I also employ OP's method of assigning unique IDs to notes:

When I click on a `[[201808151059]]` link, I expect it to populate the search box and to see notes that have `201808151059` on the first line (title) as a result (in case of unique IDs, that would be just one note, such as `201808151059 Swift`), followed by notes with `[[201808151059]]` links in their body, then normal body text if applicable.

**Comment by glushchenko** [comment]
@brianwood2782 please try https://github.com/glushchenko/fsnotes/releases/tag/4.2.5

**Comment by brianwood2783** [comment]
Using 4.2.6: 

Yep, the feature itself is working perfectly. FSNotes is able to find the wiki links if you search for them. 

But now there's a bug: if you click on a link, it doesn't return any result. Instead, it shows every note on the directory and populates the search with the top note title. However, if you manually type in a term on the search box, FSNotes will be able to search the text within brackets and  return the correct notes.

**Comment by glushchenko** [comment]
@brianwood2783 seems is fixed.

**Comment by brianwood2783** [comment]
Yes, can confirm. As of 4.3.3 this seems like it has been fixed. Thanks, @glushchenko! Incredible work, really :-)
