### ISSUE TITLE
[REQ] Menu item to copy note title

### ISSUE THREAD

**Issue by gmenzel** [glushchenko/fsnotes#334]
Currently you can copy a note's URL, but if you use wiki links you'd rather be able to copy a note's name. As far as I can tell this is only possible by selecting the note, hitting ⌘R, and then ⌘C. It would be great if there were a "Copy Note Title" option just under "Copy Note URL".

**Comment by glushchenko** [comment]
If you are use wiki links, you don't need "copy title" just press ⌘ - f5 [[here]] and select note.

**Comment by gmenzel** [comment]
This can get problematic with a large number of notes. Say I have 1000 notes, and I can't remember the note's name, so I have to go searching for it. After I find it I'd like to just copy the note's title rather than having to remember the note's title, going back, and then selecting it from the (potentially very large) completion list.

**Comment by glushchenko** [comment]
No problem, i am add feature in next release. Thank you for feedback.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/commit/a13958d3e6cef8354148969ab9758a57f5742c9a

**Comment by glushchenko** [comment]
Added in 2.1.0
