### ISSUE TITLE
[REQ] Time-stamped version of note

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#338]
One of my primary uses of FSNotes is to create documents, and I often want to keep copies as I work on a particular document. Right now, I use the duplicate command and I then move the duplicate note to the archive. This works well but I wondered if there might be something better.

One option, which I think I would prefer, is to create a command that effectively combines the duplicate and move-to-archive commands in one. TextEdit has a browse-all-versions command, but I don't like that as much. Perhaps there is another option that would be best?

Thanks.

**Comment by gingerbeardman** [comment]
You could create your own command using AppleScript, if support was added. 

Externally, you could use Keyboard Maestro to create a macro to do Duplicate&Move and bind it to a shortcut key. 

TextEdit "browse all versions" is a system function that works come largely for free, if @glushchenko adds support.

**Comment by clayreimann** [comment]
Have you considered putting your notes in git? This would let you track revisions manually

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glushchenko** [comment]
Dupe https://github.com/glushchenko/fsnotes/issues/207

**Comment by peavine** [comment]
I missed the earlier issue; sorry about that. I'll close this. 

@clayreimann. Thanks for the suggestion. I'm not familiar with git but will look into it.

@gingerbeardman. Thanks for the ideas. I had given some thought to doing this with applescript (without FSNotes suppport) or bash. Adding a time stamp to the note's file name and then moving it to the archive folder would be simple. The hard part is getting the name of the currently-selected note. I guess an alternative--which is a bit of a kludge and prone to error--is to archive the most-recently-modified file in the note folder, although I think my current two-step process is better than that.
