### ISSUE TITLE
[REQ] Search PDFs

### ISSUE THREAD

**Issue by ariporad** [glushchenko/fsnotes#339]
Hi!

FSNotes looks super awesome, and I really appriciate how it respects open standards (like the file system) to not tie your important notes to one applcation (**\*cough\***Evernote**\*cough\***). I just wanted to propose one idea that I think could make the application even more awesome: It would be great if I could search the contents of PDFs. Ideally, the app could even OCR PDFs that don't have their text embedded. Personally, this is one feature that I use quite heavily, but I also think that it really adds to the utility of an app in general.

Thanks for your time!
Ari

**Comment by gingerbeardman** [comment]
I assume you store reference PDFs along with your notes? I know DevonThink, a kind of similar app, has PDF storage and searching.

In theory, FSN could leverage macOS native PDF search via Spotlight/Finder. But I guess it's up to @glushchenko if he wants to make it more than an editor? 

At its simplest, PDFs could be listed in folders and open in an embedded Preview pane? 

Note: OCR is best done with FineReader or Acrobat in my recent experience. There are lots of options that are less good.

**Comment by ariporad** [comment]
Yep! I basically want something similar to DevonThink (which I've actually adopted in the mean time), but I really like the open-source and standards-compliant nature of FSNotes. I really hate giving my data to something which won't give it back to me.

**Comment by kerim** [comment]
The ability to search PDFs would make this a reasonable replacement for Evernote. One thing I like in Evernote though is the ability to also easily browse preview thumbnails of the embedded PDFs.

**Comment by jasonekratz** [comment]
> Yep! I basically want something similar to DevonThink (which I've actually adopted in the mean time), but I really like the open-source and standards-compliant nature of FSNotes. I really hate giving my data to something which won't give it back to me.

Just to be clear, DEVONthink stores data locally and in regular folders so you are not "giving my data to something which won't give it back to me" in the case of DEVONthink. There is zero lock-in with that product.
