### ISSUE TITLE
rtfd documents are incorrectly handled

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#341]
RTFD documents are RTF which contain graphics. Since forever FSNotes has shown my one-and-only RTFD doc as a folder in the sidebar, because RTFD docs are actually macOS "packages".

I started debugging this and added a check as per the PR, which does stop FSNotes showing packages in the sidebar, but it also highlights the need for work in other areas eg where the notes list is shown.

I'm unsure what the editor implications would be to support RTFD, so if that's too difficult, I guess the easiest option is not to support RTFD at all. In this case they would need to be explicitly removed from any notes lists, and never treated as a folder.

If it helps at all, to create a sample `rtfd`:

* open TextEdit
* create a new rtf doc
* drag a PNG or other image file into the note edit area
* save it as "Rich Text with attachments"

**Comment by glushchenko** [comment]
Thank you for pull request! Merged.
