### ISSUE TITLE
[Bug] Opening a file with MacVim as the external editor launches two MacVim windows

### ISSUE THREAD

**Issue by gmenzel** [glushchenko/fsnotes#344]
Title pretty much says it. If MacVim is the external editor, launching the external editor opens up two MacVim windows. The second window then complains that the file is already open. Not a huge issue, but kind of annoying.

This seems to be specific to MacVim. TextEdit, Emacs, Sublime Text, and Byword all open only one window.

**Comment by gingerbeardman** [comment]
Seems to be a bug with the Open External shortcut key.

if you use the menu command (main or context menu) only one MacVim window is opened.

**Comment by glushchenko** [comment]
Dupe https://github.com/glushchenko/fsnotes/issues/223
