### ISSUE TITLE
Spelling and grammar settings are not preserved across restarts

### ISSUE THREAD

**Issue by lowski** [glushchenko/fsnotes#346]
Hi,
Thank you for the app - it's my daily driver for taking notes. Great job!

I've noticed one issue with spelling and grammar checking - if I turn them on and restart the FSNotes, it won't preserve the settings so basically I have to enable them again.

Is it possible to store the changes so they go back to previous state? Thank you in advance.

**Comment by gingerbeardman** [comment]
This issue was addressed in a recent version. Can you confirm which version you're using?

**Comment by jeff-h** [comment]
It's still broken for me in 2.0.9.

**Comment by lowski** [comment]
The latest one (2.0.9).
