### ISSUE TITLE
[Bug] Edit -> Substitutions are reset when FSNotes restarts

### ISSUE THREAD

**Issue by gmenzel** [glushchenko/fsnotes#347]
I'm finding that if I unselect Edit -> Substitutions -> Smart Quotes, smart quotes will not be used as expected. However, when I restart FSNotes, I find that Edit -> Substitutions -> Smart Quotes is selected again. So I have to unselect Edit -> Substitutions -> Smart Quotes every time I start FSNotes. Same with Edit -> Substitutions -> Smart Dashes, and I assume with the other substitutions, though I have not tested them.

**Comment by peavine** [comment]
This and related issues  were reported and fixed in #273, althought they do seem to be back. The same issues are present in the context menu.
