### ISSUE TITLE
Is there any way to develop SimpleNote sync?

### ISSUE THREAD

**Issue by mblode** [glushchenko/fsnotes#35]
I am currently using nvAlt for my notes and I'm waiting for BitWriter but in the mean time, I found this awesome project 👍 I noticed there was a branch for CloudKit development and I am wondering if it is possible to implement sync with SimpleNote? The simperium sign up seems to be closed: "Registration is Closed. We're not accepting new accounts at this time. Thanks for your interest in Simperium."

So is it just impossible at the moment? I have an Android device so should I just use Google Drive to sync from Mac to Android?

Thanks! You have done great work

**Comment by jeff-h** [comment]
You're correct — Simperium is not currently accepting new developers. I don't know if it's fair to reach the conclusion that it's dead but there has certainly been very little activity on their site for years.

I really believe in the notion of a simple folder of documents — it's easy for apps to consume, highly portable and compatible, and should sync just fine with every sync service. I think the world just needs a few more solid clients, such as this one.

However, it seems there's genuinely no nvALT-minded notes apps for iOS. I certainly haven't found one, and I've looked several times over the past few years. Is it the same in Android?

**Comment by mblode** [comment]
Yeah, it is pretty much the same on Android with the best option being iA Writer 4 for Android (Which sadly isn't very good). I am using SimpleNote on Android as it is very snappy, has offline notes (unlike iA) and the syncing is super simple. If I had an iPhone, I'd probably use Bear for my notes or Ulysses which are both in Markdown and sync via iCloud

**Comment by jeff-h** [comment]
For the life of me I don't understand the popularity of markdown in notes apps... but obviously lots of people do. However I definitely don't, which vastly limits the choices I have on iOS (and the Mac).

Both Bear and Ulysses have very nice UI's, but they both:

* mandate the use of markdown and neither provide for RTF (that I can see anyway)
* use their own proprietary notes storage database; neither are based on straightforward `.md` or `.rtf` files, although Ulysses can utilise `.md` files stored in Dropbox it's largely irrelevant because its iOS client doesn't even do full-text search
* require a monthly or yearly subscription

**Comment by mblode** [comment]
Yeah those are some great points! What are your thoughts on Evernote? And the whole reason I'm in this quest for notes app is because I was using Dropbox paper which is super nice but is awful awful awful on Android. The sync took 30 seconds some time. I like Evernote a bit I just can't deal with their shitty formatting that always breaks

**Comment by khalido** [comment]
> genuinely no nvALT-minded notes apps for iOS

I finds apps like [1writer](http://1writerapp.com/) and [Byword](https://bywordapp.com/ios/index.html) do a pretty good job of being able to search for and edit files on the iphone. They are not quite the nvalt of ios apps but close enough to get the job done.

**Comment by jeff-h** [comment]
Thanks for the suggestions, but unfortunately (for me) neither of those support anything other than plain text or markdown files.
