### ISSUE TITLE
iOS app: cut does not copy

### ISSUE THREAD

**Issue by hanche** [glushchenko/fsnotes#350]
When I select some text on iOS and then select “Cut”, I expect the selected text to be copied to the clipboard before the text is deleted.

What happens instead, is that the clipboard remains unchanged.

The behaviour would more properly be called “Delete”. There is no such choice, as it is also easily accomplished by typing a backspace.

I run the iOS 12 public beta, in case that matters.

**Comment by glushchenko** [comment]
Fixed in 1.8
