### ISSUE TITLE
Bullet-Number List Needs Fix

### ISSUE THREAD

**Issue by ebsmv** [glushchenko/fsnotes#351]
The list features are not working well. The 1st level works fine, but indenting to next levels are not working. Tab indent doesn't continue to next level. Two pics below are same. 2nd one is in preview mode which shows the indent as IV which is also a problem. Thanks for work on this. 

![image](https://user-images.githubusercontent.com/39436360/44795916-aea41880-ab60-11e8-8677-4ff26da00bde.jpeg)
![image](https://user-images.githubusercontent.com/39436360/44795849-861c1e80-ab60-11e8-98d0-90e5247681c4.jpeg)

**Comment by glushchenko** [comment]
Second level rendered as ordered second level. This is not bug.
