### ISSUE TITLE
[Bug] Nested lists are rendered as code

### ISSUE THREAD

**Issue by gmenzel** [glushchenko/fsnotes#354]
Apologies if this is a duplicate, but I notice that nested lists are rendered as code in the editor. To reproduce:

1. Open a new note
2. Enter this text into the note:

```
- foo
[TAB]- bar
```

`- bar` will be rendered as a code block in fixed-width font.

**Comment by gmenzel** [comment]
Any estimates or progress on this?

**Comment by glushchenko** [comment]
What are you propose? Tab is code block separator in markdown.

**Comment by gmenzel** [comment]
...Unless the previous line is a list item (or is a blank line following a list item).

Below, "bar" is incorrectly marked up as code in the editor:

<img width="126" alt="screen shot 2018-10-08 at 3 20 19 pm" src="https://user-images.githubusercontent.com/3878535/46614469-d4ccb900-cb0d-11e8-8a6d-74ea38e222ed.png">

But if you look at the Markdown preview, the list is rendered correctly as a nested list, not as code:

<img width="93" alt="screen shot 2018-10-08 at 3 20 27 pm" src="https://user-images.githubusercontent.com/3878535/46614495-edd56a00-cb0d-11e8-980e-373985f01de2.png">

**Comment by glushchenko** [comment]
Thank you for clarification. Will be fixed soon.

**Comment by glushchenko** [comment]
Please try 2.2.3 https://github.com/glushchenko/fsnotes/releases/tag/2.2.3

**Comment by gmenzel** [comment]
It's definitely improved. Still has some edge cases, which don't affect me, but you should tackle if you want the editor and preview to be in sync. For example, editor:

<img width="146" alt="screen shot 2018-10-09 at 9 47 38 pm" src="https://user-images.githubusercontent.com/3878535/46697650-037d8900-cc0d-11e8-9fac-af513a127070.png">

Preview:

<img width="111" alt="screen shot 2018-10-09 at 9 47 50 pm" src="https://user-images.githubusercontent.com/3878535/46697658-08423d00-cc0d-11e8-94c0-8f1b20cd9cee.png">

But there are more urgent matters, like https://github.com/glushchenko/fsnotes/issues/353.

**Comment by glushchenko** [comment]
Sorry, but preview not in priority. For proposals and requests issue should be opened here https://github.com/iwasrobbed/Down

**Comment by gmenzel** [comment]
In this case the preview is correct. The editor is incorrect.

**Comment by glushchenko** [comment]
What did you mean?
