### ISSUE TITLE
“Done” button almost off the screen

### ISSUE THREAD

**Issue by hanche** [glushchenko/fsnotes#356]
When in edit mode, the “Done” button above the keyboard gets pushed off the screen so only the “D” shows. See attached screenshot.

- Version 1.9, updated from the App store today
- iPhone 6s (portrait orientation)
- iOS 12.0 public beta (if it matters)

<img width="375" alt="img_89621692cf13-1" src="https://user-images.githubusercontent.com/518961/45421170-8d791700-b68c-11e8-9b73-e385957422f7.png">

**Comment by glushchenko** [comment]
Yep, you can scroll right
