### ISSUE TITLE
Preview pane appearance

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#36]
This is the preview of FSNotes's Hello World note in nvALT (left) and FSNotes (right)

![screen shot 2017-09-11 at 09 36 08](https://user-images.githubusercontent.com/370930/30286002-e764137e-96d4-11e7-91d0-b01e46d76a45.png)

The FSNotes preview takes up slightly more space but shows *much* less information. I much prefer the nvALT layout. Seems like they are:

 - replacing all groups of whitespace with a single space (so no double spaces in the preview)
 - showing two lines of preview and getting rid of a bunch of linespacing and other vertical whitespace

I'd love to see these both added.

Also, you can't see it here, but it seems like FSNotes is ignoring macOS's Language & Region setting and using US format for dates regardless. This is a bug. Would be great if this could be fixed.

(Also, fwiw, I find the fixed width font very spidery and difficult to read at this size. I see the argument for it in a window you can edit, but for a small preview I think something proportionial would be more legible.)

**Comment by jeff-h** [comment]
👍 

Also agree re the fixed-width font. The choice of note font is arguably very user-specific; I don't store (much) code in my notes, and strongly prefer a proportional font for my notes, but I can see why someone else might differ.

However, I think the sidebar preview and date are part of the app's UI and I feel shouldn't reflect the font chosen in the prefs.

@glushchenko — if you agree and give me the go-ahead I'm happy to make the font changes. I'd like to also make the changes described in the post above but the app's use of code to lay everything out puts me off a bit. Was there a reason you chose that instead of using IB/autolayout?

**Comment by glushchenko** [comment]
Check last build: https://github.com/glushchenko/fsnotes/releases/tag/1.1.6

**Comment by williamsmj** [comment]
@glushchenko it looks different but it doesn't solve the problems:

 - there's still some wasted white space where more preview could be shown
 - the date still ignores my local setting, and uses US format instead

![screen shot 2017-10-27 at 15 25 01](https://user-images.githubusercontent.com/370930/32127344-04a6413a-bb2b-11e7-960a-cbf896985a6b.png)

Should I open a new issue?

**Comment by glushchenko** [comment]
I think this is a bug, on high sierra all fine:
 
<img width="532" alt="screen-shot-2017-10-28-10-36-51" src="https://user-images.githubusercontent.com/1089917/32132436-238c9a3a-bbcc-11e7-9092-3f612d9e55ef.png">

How i can reproduce this? What FSNotes build/OS/resolution you are use?

**Comment by williamsmj** [comment]
That screenshot is Version 1.1.7 (49) on macOS 10.12.6.

Is your system set to use US date format too? If not, seems like the date format bug is present for you too.

**Comment by glushchenko** [comment]
Fixed in 1.1.8 https://github.com/glushchenko/fsnotes/releases/download/1.1.8/FSNotes.app.zip

Yes, my locale en_UA. And this is default macOS formatting:  https://github.com/glushchenko/fsnotes/blob/aaa02b0c2fb390df674eaa8059ab7eb9f51690f5/FSNotes/Model/Note%2BCoreDataClass.swift#L133

**Comment by williamsmj** [comment]
The text is now very fuzzy and difficult to read, like it's been rescaled and pixelated:

![screen shot 2017-10-28 at 14 17 49](https://user-images.githubusercontent.com/370930/32138641-df427fc4-bbea-11e7-9e4d-d4486f51e686.png)

Re: the date format, Apple Mail, Calender, nvALT, etc. all respect my region preferences (under Language and Region in System Preferences). FSNotes does not.

**Comment by jeff-h** [comment]
@williamsmj  Strange that your date isn't formatting correctly. My system is set to dd/mm/yy and that's what FSNotes gives me (currently using v1.1.7)

**Comment by williamsmj** [comment]
Apple Mail

![screen shot 2017-10-28 at 14 23 36](https://user-images.githubusercontent.com/370930/32138673-a3aa7222-bbeb-11e7-93b9-ea4a482d3b19.png)

nvALT

![screen shot 2017-10-28 at 14 22 51](https://user-images.githubusercontent.com/370930/32138675-abccf7fe-bbeb-11e7-8b29-bded2cce8fd2.png)

**Comment by glushchenko** [comment]
Please show ```defaults read -g AppleLocale```

**Comment by jeff-h** [comment]
I'm a little confused — your system is set to `en_US` but your date formatting is year-month-day? Did you rearrange that yourself?

**Comment by williamsmj** [comment]
Yes. "United States" is fine for most things but I override a couple under "Advanced":

![screen shot 2017-10-28 at 15 36 20](https://user-images.githubusercontent.com/370930/32139126-e31026aa-bbf5-11e7-88d6-b8f40469a046.png)

**Comment by glushchenko** [comment]
Custom date formatting fixed in commit above.  Fuzzy text in preview I'll try fix tomorrow.

**Comment by glushchenko** [comment]
@williamsmj please checkout https://github.com/glushchenko/fsnotes/releases/download/1.1.8/FSNotes.app.zip

**Comment by williamsmj** [comment]
Perfect! Date and preview looking good. Thank you!

![screen shot 2017-10-30 at 13 53 21](https://user-images.githubusercontent.com/370930/32195150-b5d7ab42-bd79-11e7-932c-a6aecb57d71b.png)

**Comment by jeff-h** [comment]
Bit sad to see the "no preview" option gone — I personally have never found the tiny previews useful at all and really liked the whitespace I could achieve around the note list items in 1.1.7 and earlier. Was there a specific reason you removed it?

**Comment by glushchenko** [comment]
“No preview” option moved to option above, cell note height.

**Comment by jeff-h** [comment]
Hmm, that's not really the same result. I liked the whitespace above and below my note titles (ie wide note list spacing) but with no note preview at all.
