### ISSUE TITLE
Cursor invisible while moving or typing (macOS Mojave)

### ISSUE THREAD

**Issue by greendog99** [glushchenko/fsnotes#360]
Since upgrading to MacOS Mojave 10.14 (via a clean install), the cursor in fsnotes (2.1.0 172) becomes invisible when typing or using arrow keys. That means, for example, that when using the arrow keys to move around in a document, you have to hold a key for a while and then let go to see where your cursor is, which makes it difficult to move to a specific line or character -- it's all guesswork.

On MacOS High Sierra (10.13) the cursor is visible and solid (not blinking) when typing or using the arrows.

**Comment by glushchenko** [comment]
Thank you for feedback, will be fixed coming soon.

**Comment by glushchenko** [comment]
Fixed https://github.com/glushchenko/fsnotes/releases/tag/2.1.1

**Comment by peavine** [comment]
I installed FSNotes 2.1.1 and the cursor issue is fixed for me. FSNotes runs great under Mojave :)

**Comment by glushchenko** [comment]
Dark mode not added yet, it is mojave bug. But i think that dark mode will be done on weekend.

**Comment by braunsb** [comment]
I want my cursor to disappear while I type and reappear when I move it again.
