### ISSUE TITLE
Find window enter vs. click 

### ISSUE THREAD

**Issue by ulab** [glushchenko/fsnotes#363]
When I try to find something and type a term plus `enter`, the find window closes and I have to reopen it to search for the next element. 

If I use the (marked) `Next` button instead, it goes to the next element, but keeps the window open.

I'd expect the same behaviour on `enter` since I'm triggering the selected button which is `Next`.

**Comment by ulab** [comment]
Isn't it common GUI behavior that enter executes the focused element? The default focused element is the `next` button. 

If I click `next` with a mouse, it goes to the next found phrase but keeps the window open. 
If I press `enter` on the keyboard, it goes to the next found phrase and closes the search window.

That's not what I'd expect. nvALT and TextEdit have an extra `done` button to close the search instead.

**Comment by glushchenko** [comment]
This is not best approach, but is default behavior for nstextview.

**Comment by ulab** [comment]
I don't have any experience with AppKit, but the first thing I read when searching for "nstextview" was an option to use a "Find Bar" instead of a "Find Panel" which seems to be what you switched to now? :)

I do like this variant better, but I see two things: 

1. The Find Bar seems to overlay the first few lines of text. nvALT seems to add some kind of margin on top so it still shows the whole edit window, while TextEdit overlays but allows you to scroll down.

2. The ESC issue I had in #364 happens here too. The document is being closed instead of the Find Bar.

**Comment by glushchenko** [comment]
Thank you for feedback, will be fixed soon.

**Comment by glushchenko** [comment]
@ulab, please try build 181.

**Comment by ulab** [comment]
Tried 182, works for find, but needs a tiny bit more margin for replace. I can't seem to be able to upload an image at the moment here, but I've uploaded a screenshot to [Imgur](https://i.imgur.com/f2fogq3.png).

ESC works as expected.

**Comment by glushchenko** [comment]
Fixed in build 183, please checkout.

**Comment by glushchenko** [comment]
And ⌘-f works in notes list now.

**Comment by ulab** [comment]
Works perfect. Thanks for taking your time to update this, it was driving me crazy :)

**Comment by glushchenko** [comment]
Welcome! :)

**Comment by peavine** [comment]
I just noticed that FSNotes 2.2.3 now has a find bar rather than a find panel. This is a nice change--I never used the find panel because it was too busy and cumbersome but the find bar is very easy to use. Thanks.
