### ISSUE TITLE
Note content is deleted when you press the keys in preview mode

### ISSUE THREAD

**Issue by dseter** [glushchenko/fsnotes#367]
1. Create a new note
2. Switch to preview mode
3. Press a few keys (try to write something)
4. The contents of the note is cleared (in the version 2.2.1)

**Comment by dseter** [comment]
The error has been partially fixed. The problem persists when restarting the program. List of steps:
1. Create a new note
2. Switch to preview mode
3. **Close and reopen the program**
4. Press a few keys (try to write something)
5. The content of the note is cleared (in version 2.2.2)

**Comment by glushchenko** [comment]
Please try 2.2.3 https://github.com/glushchenko/fsnotes/releases/tag/2.2.3

**Comment by dseter** [comment]
This bug is still present in version 2.2.3.

**Comment by glushchenko** [comment]
I can not reproduce.

**Comment by dseter** [comment]
I deleted the ~/Library/Containers/co.folder.fluder.FSNotes. The program has created this folder again, but I can not check the error, because switching to view mode does not work. I created a new error message. Let's check this error when switching to preview mode is fixed.

**Comment by dseter** [comment]
.md
