### ISSUE TITLE
Font handling (in rtf docs)

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#37]
At present you can paste text in from elsewhere and the formatting is maintained. You can end up with notes with different fonts, sizes (and colours) than what you've chosen in the prefs.

Also, some RTF docs appear to specify the font intrinsically, and others not. Changing the font in the prefs changes it (temporally) for the current note, and it takes effect on *some* other notes, but not all.

For me there's a philosophical angle to this; I want my notes devoid of distraction, both when entering and when reading. It's purely about the content. There are dozens of notes apps that allow full typographical control, and I dislike them all because of it :) 

I propose:

* when a note is displayed, set its font and size to that chosen in the prefs
* when text is pasted in, remove any formatting and make them conform to the font prefs

(incidentally both are how nvALT handles it, so maybe I just can't handle change lol)

@glushchenko let me know if you'd like me to have a crack at this.

**Comment by glushchenko** [comment]
I think it is a good idea.

**Comment by glushchenko** [comment]
Please check new build: https://github.com/glushchenko/fsnotes/releases/tag/1.1.2

**Comment by jeff-h** [comment]
It's working great! Awesome work as always!
