### ISSUE TITLE
Bug: Text is white on white during file renaming

### ISSUE THREAD

**Issue by gmenzel** [glushchenko/fsnotes#370]
When I hit ⌘R to rename a file, and then hit → to move to the end of the file name, the file name is displayed as white on white until I am finished editing the file name:

<img width="318" alt="screen shot 2018-10-08 at 2 55 44 pm" src="https://user-images.githubusercontent.com/3878535/46613167-6d613a00-cb0a-11e8-9c90-4c9bf9da8921.png">

**Comment by glushchenko** [comment]
Please try 2.2.3 https://github.com/glushchenko/fsnotes/releases/tag/2.2.3
