### ISSUE TITLE
Autocomplete does not show capitalization of matched note names

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#371]
Autocomplete no longer shows the capitalization of matched note names. 

For example, I have an existing note with the name Peavine and it is the only note beginning with a p. If I type the letter "P" in the search and create bar, autocomplete shows peavine rather than Peavine. Is this the way it's supposed to work?

This becomes an issue if it is my intent to create a new note with the name People and I instead get people.

Thanks.

**Comment by glushchenko** [comment]
Please try 2.2.3 https://github.com/glushchenko/fsnotes/releases/tag/2.2.3

**Comment by peavine** [comment]
This seems like a simple issue, but it's a tiny bit complicated because the search and create bar is used both to find existing notes (where capitalization should not matter) and to create new notes (where capitalization needs to be retained). Anyways, it works perfect in 2.2.3. Thanks.
