### ISSUE TITLE
[REQ] Show number of matches in find bar.

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#372]
The new find bar in 2.2.3 is great, but I wanted to suggest one small enhancement. Several apps that I use--such as TextEdit--have a find bar just like FSNotes, but they show the number of text matches in the find bar just to the left of the delete symbol. This is helpful in determining whether to scroll through a document to view matches in context or to refine the search string. Thanks.

**Comment by glushchenko** [comment]
Added in 2.7.4

**Comment by peavine** [comment]
Installed 2.7.4 and this works great. Many thanks.
