### ISSUE TITLE
Bug: links to partial file names are not working

### ISSUE THREAD

**Issue by gmenzel** [glushchenko/fsnotes#375]
In 2.2.3, links to partial file names aren't working.

I use "Zettelkasten" style note names and links, where file names start with a unique timestamp id, such as 201810112121. So I might name a note `201810112121-client-notes`. I then link to this note using links that only contain the ID — in this case `[[201810112121]]`. I notice in 2.2.3, clicking these links executes a search for "201810112121", but does not select the `201810112121-client-notes` note. This means I have to then click the note from the notes list.

I have noticed this a number of times over the past versions, and sometimes whether the note would be selected or not seemed to have to do with the linking and linked notes' relative order in the results list. But as of 2.2.3 it seems to just not be working at all.

Please let me know if I can provide any more info!

**Comment by glushchenko** [comment]
Fixed in 2.3.2
