### ISSUE TITLE
WebDAV Sync?

### ISSUE THREAD

**Issue by 23n** [glushchenko/fsnotes#376]
Are there any plans for WebDAV sync (e.g. Nextcloud) instead of iCloud?

**Comment by glushchenko** [comment]
no

**Comment by gingerbeardman** [comment]
Related review

> zenzor 🇩🇪 
> Toll und da geht noch was
> Da wäre sie, die Ablösung meines sehr geliebten nvALT. Viele Dinge die ich dort immer vermisst hab, gibt es mit FSNotes, Sync mit dem iPhone ist nur eines davon.
> Was aber wirklich fehlt:
> - Sync-Möglichkeit mit WebDAV (Nextcloud und Co.)
> Soll allerdings nicht implementiert werden, daher: wieder deinstalliert.
> Rating
> ★★★☆☆
> App Version
> 2.3.4

**Comment by tobx** [comment]
Hm, why would I want to use FSNotes instead of the big players (e.g. Evernote) if I cannot decide where to store my data? Isn't the main reason for most people to use "synced" open source software that generally comes with more configuration effort and syncing issues to keep their data out of the big cloud services?

**Comment by cmer** [comment]
I agree, it's quite a shame that we can't use our own storage. Webdav would be the first thing to implement to support this IMO. It would allow us self-hosters to store our data on Nextcloud.

**Comment by xplosionmind** [comment]
I totally agree, please, **do reconsider** implementing this feature!

**Comment by xplosionmind** [comment]
@glushchenko did you have the chance to reconsider implementing this feature, in light of your great work for version 6?

**Comment by glushchenko** [comment]
@xplosionmind hi, no any chances. I don't use webdav.
