### ISSUE TITLE
Smaller font size in editor

### ISSUE THREAD

**Issue by erikrose** [glushchenko/fsnotes#377]
Just bought FSNotes on both iOS and Mac. Good work! :-D

I would love to be able to shrink the text in the editor, probably via a setting, since you'll never get everyone to agree on a single size.

Thanks for a great piece of software!

**Comment by gingerbeardman** [comment]
You can do this on MacOS through app preferences. 

I'm not sure but I suspect that the iOS app honours system text sizing?

**Comment by erikrose** [comment]
It was indeed iOS I was talking about. In my case, I want to shrink it way, way further than the system size allows. I have a lot of long notes and want to fit a lot on the screen. :-) (Also, there’s no Find command within a not on iOS, so I can’t use that to navigate.)

**Comment by gingerbeardman** [comment]
Understood. 

FWIW I actually use Pretext and/or Textor to edit my FSNotes files, the both offer this feature.

**Comment by glushchenko** [comment]
In iOS implemented Dynamic Type, it's system wide setting for font changing.

![img_e41dab66f7a5-1](https://user-images.githubusercontent.com/1089917/47024792-104d3000-d16b-11e8-8d62-f61fae271348.jpeg)

But, that's not difficult, will be added in next releases.

**Comment by erikrose** [comment]
Fantastic! Thank you! :-D

**Comment by glushchenko** [comment]
Now you can change font size too.
