### ISSUE TITLE
Code Highlighting displaying non-mono spaced serif fonts

### ISSUE THREAD

**Issue by samullen** [glushchenko/fsnotes#380]
Just purchased yesterday on both Mac and iOS. FSNotes looks like a great alternative to NVAlt, which I've used for years. Unfortunately, code highlighting is showing as a non-mono spaced font with serifs for the Mac version (purchased from the Mac App Store).

<img width="597" alt="screenshot 2018-10-18 08 11 09" src="https://user-images.githubusercontent.com/59711/47156776-704bef80-d2ad-11e8-95d4-4bd30aaec458.png">

I don't know what other information I can provide here, but I'll be happy to.

**Comment by samullen** [comment]
10.13.6

**Comment by samullen** [comment]
I think I figured this out. Because I've been using NVAlt for so long, a lot of my files have a `.txt` extension. When I change them to a `.md` extensions the code preview starts using a monospaced font.

Recommending to my team and local user group. Thanks!

**Comment by glushchenko** [comment]
No, thats High Sierra bug. In mojave all fine. Will be fixed in next release.

**Comment by glushchenko** [comment]
Fixed in 2.3.2
