### ISSUE TITLE
Trying to use "Pin" crashes FSNotes on Mac

### ISSUE THREAD

**Issue by tjluoma** [glushchenko/fsnotes#385]
Trying to use the "Pin" feature makes the app crash

Here's a video showing it in action:

https://www.dropbox.com/s/cmpb8yayk8g9ety/FSNotes-Pin-equals-Crash.mov?dl=0

Here are some crash logs:

[FSNotes-Pin-Crash.zip](https://github.com/glushchenko/fsnotes/files/2498656/FSNotes-Pin-Crash.zip)

**Comment by glushchenko** [comment]
Thank you for bug report, fixed
