### ISSUE TITLE
Markdown preview appears to be broken - MAS 2.3.2, Mojave 10.14

### ISSUE THREAD

**Issue by danseely** [glushchenko/fsnotes#386]
I'm on Mojave (10.14) with the latest FSNotes update from the MAS (2.3.2).

MBP mid-2015, 15".

![fsnotes-preview](https://user-images.githubusercontent.com/2266893/47367822-7e837c80-d6ae-11e8-87c5-0333c8e96f30.gif)

**Comment by glushchenko** [comment]
What document type did you use?

**Comment by danseely** [comment]
`.txt`, which has always worked previously.

**Comment by danseely** [comment]
Ok, good to know, thanks!. Can I expect that to be expected behavior moving forward? I can work with it, just wondering.

**Comment by glushchenko** [comment]
I can revert changes, if it's necessary, but markdown in editor highlighting works only with md, markdown and text bundle files.

**Comment by danseely** [comment]
Eh, I'm fine with the changes, I already renamed all my files and changed the default extension in FSNotes prefs.

As far as what makes the most sense for the product, that's a tough one. It sort fo feels like MD parsing/preview in general should work in any plain-text situation, and it's maybe a little arbitrary to narrow the scope of the preview parser to only target `.md` files. But, ultimately, it feels like a fair-enough product choice.
