### ISSUE TITLE
Renaming a note with notes pane hidden causes hard crash

### ISSUE THREAD

**Issue by Jarrid** [glushchenko/fsnotes#387]
This is fairly specific, and I have a video that recreates the issue.  I can work around the issue, and it's not a deal-breaker.  I just wanted to provide more information.

**What I'd Expect**
Anytime I type cmd + r, I can rename a file

**What is happening**

- If I have the notes pane open, and hit cmd+r, I can rename a note just fine.
- If I close the notes pane (after renaming), I can rename it one time.
- If I try to rename it AGAIN, after the second time, the application crashes.
- When the application re-opens, if I try to rename it instantly crashes again.
- If I show the notes pane again, and then hit cmd + r, it renames the note again.

Here is the link to a video I created, as that might help:
[Link To Google Drive Video](https://drive.google.com/file/d/1WuW-hFIMaGtZmMRve0EKh4B4NnMzc9PD/view?usp=sharing)

**Comment by Jarrid** [comment]
Hi!
I just wanted to confirm that the latest update to 2.3.4 (196) resolved this issue for me.

**Comment by glushchenko** [comment]
Hi, jarrid. Thank you for bug report.
