### ISSUE TITLE
"Show in Finder" (cmd-ctrl-O) should be "Reveal in Finder" (cmd-shift-R)

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#39]
"Show in Finder" (currently bound to `cmd-ctrl-O`) should be relabeled "Reveal in Finder" (and bound to `cmd-shift-R`). This follows macOS conventions, e.g. iTunes, Omnigroup software, nvALT, etc.

**Comment by glushchenko** [comment]
fixed
