### ISSUE TITLE
Lost notes after setting storage location

### ISSUE THREAD

**Issue by donguijote** [glushchenko/fsnotes#40]
I've just start writing my first note. After several minutes and lines, I wanted to set the location for storage notes; I've selected my Dropbox folder... I'VE LOST MY NOTE. Where's is it? Can I recover it? It was stored in any folder in my computer? THIS IS AN ISSUE. You must set the folder before you write, or you lost all notes when yo set the folder. Please help and fix it for upcoming versions.

**Comment by glushchenko** [comment]
Markdown files default directory:

~/Library/Containers/co.fluder.FSNotes/Data/Documents/

**Comment by donguijote** [comment]
Thank you very much. I think you may add any way to transfer that note/s
to the next location, ask if you want to do it or not, before that change,
that makes the message list to be empty (and the scare of the user).



2017-09-17 19:35:03 +0000 Oleksandr <notifications@github.com> :

**Comment by glushchenko** [comment]
Good idea, will be fixed in next releases. Thank you for feedback :)
