### ISSUE TITLE
[WISH] Quick search

### ISSUE THREAD

**Issue by buddax2** [glushchenko/fsnotes#402]
What do you think about such search?:

![quick search](https://media.giphy.com/media/1iqgrViUmW9lejJxOd/giphy.gif)

I'm also in the middle of implementing search by `#tags`. We can also add search by projects (folders) with a pattern like this: `@projectname`. So, as a result, I would like to be able to search like that: `@projectName #tag1 #tag2 and some text`.

I see this way as more oriented on shortcuts

**Comment by glushchenko** [comment]
Not bad, but gray margins seems not ok.

**Comment by buddax2** [comment]
I've made it in 30 minutes just to show my idea.

**Comment by gingerbeardman** [comment]
This is cool

**Comment by manangatangy** [comment]
Very nice idea +1

**Comment by sweenzor** [comment]
Keyboard navigation on the results would be fantastic also!

**Comment by gingerbeardman** [comment]
you can also ready do quick search using cmd+L, type, cursor up/down

this issue is more about the popup display UI

**Comment by quinncomendant** [comment]
This looks great! 

I wouldn't mind being able to hide my notes list completely, and access notes only via a hotkey-popup. It would need to allow performing other actions on notes such as deleting, moving, renaming, tagging – and ideally with multi-note-selections.

**Comment by gingerbeardman** [comment]
I have been able achieve something close to this using a third party application called Alfred — it is kind of like Spotlight on steroids.

https://github.com/glushchenko/fsnotes/wiki/Alfred-Workflow

It can search FSNotes storage folder for note titles and contents, and open/focus them in FSNotes. It can also create new notes, with or without title.

**Comment by sloria** [comment]
I like the idea of a go-to anything shortcut. Copying from https://github.com/glushchenko/fsnotes/issues/885 :

> An increasingly popular pattern in editor apps is the ability to fuzzy-find items with a keyboard shortcut (usually Cmd+P or Cmd+T). It would be useful to have something similar shortcut in FSNotes for fuzzy matching files and folders.
>
> As an example, here's what the Cmd+P menu looks like in Notion:

![Image 2020-05-10 at 3 21 50 PM](https://user-images.githubusercontent.com/2379650/81508416-08675a80-92d2-11ea-8292-9806970da9f2.png)

> I'm unsure whether FSNotes should search...
> 
> 1. Everything
> 2. Folders and files
> 3. Folders only
> 4. Folders and tags
> 
> Personally, I'd like the ability to jump to folders quickly, so I'd rather have number 3 or 4 if it meant that the search would be noticeably faster than 1 and 2, but this is not a strong preference.

As @gingerbeardman [pointed out](https://github.com/glushchenko/fsnotes/issues/402#issuecomment-455184544), there's already a global _content_ search. What's missing is a way to jump to a folder/project or tag.
