### ISSUE TITLE
move from archive back to notes

### ISSUE THREAD

**Issue by pvinis** [glushchenko/fsnotes#405]
this is not possible right now.

**Comment by peavine** [comment]
I suspect that you're asking a different question but, FWIW, you move a note from the archive to another folder by:

1) Select the archive in the sidebar.

2) Select the note to be moved in the Notes List.

3) Select the File > Move command from the top-level menu.

4) Select the destination folder.

In step 3 above, you can instead use the Command-T keyboard shortcut or the contextual (right-click) menu.

If you are asking if there is a shortcut to move a note from the archive to its original folder, I don't know of one.

**Comment by pvinis** [comment]
this is possible, true. but dragging the note doesn't work. also no shorter way exists.

**Comment by peavine** [comment]
I dragged several notes from the archive to other folders and back, and that worked fine for me. I don't know why that wouldn't work for you.

**Comment by peavine** [comment]
Moving a note from the archive to another folder is easily done with either the mouse or the move command. Perhaps this issue should be closed?
