### ISSUE TITLE
[REQ] Check for updates

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#407]
Sparkle can work with GitHub releases to provide an in-app update mechanism.

**Comment by jeff-h** [comment]
I reckon if people want an auto-updating FSNotes they should buy it from the MAS.

**Comment by gingerbeardman** [comment]
@jeff-h very good point

but what about those of us on the bleeding edge? maybe just  a gentle prod and open the latest release page in browser?

**Comment by gingerbeardman** [comment]
Could we not parse https://github.com/glushchenko/fsnotes/releases.atom (XML) for the first entry and compare?

**Comment by gingerbeardman** [comment]
Ny workaround is to manually choose `Help` > `FSNotes Help` to get to GitHub and then click Release :/

**Comment by glushchenko** [comment]
Guys, let me know, if anyone want i will send free promo codes for all contributors.

**Comment by jeff-h** [comment]
@glushchenko I'm just grateful for the amount of work you've put in and continue to put into this! I've kind of gone quiet, but only because FSNotes already does pretty much everything I need it to :)

**Comment by gingerbeardman** [comment]
I don't have the iOS app so I'd appreciate one for that. Thanks!

Whilst I do have the Mac App Store version, I'm usually on the GitHub build.
