### ISSUE TITLE
[BUG] Scala markdown not highlighting in preview mode

### ISSUE THREAD

**Issue by patrickf3139** [glushchenko/fsnotes#409]
Scala markdown has syntax highlighting in editor mode but not preview mode.

See screenshots. I'm on the latest version of FSNotes.
<img width="1073" alt="screen shot 2018-11-14 at 3 21 14 pm" src="https://user-images.githubusercontent.com/1967248/48519208-fa419680-e820-11e8-909b-4449ee605294.png">
<img width="1071" alt="screen shot 2018-11-14 at 3 21 19 pm" src="https://user-images.githubusercontent.com/1967248/48519209-fa419680-e820-11e8-879b-ef22bcd6e4ba.png">

**Comment by glushchenko** [comment]
Thank you for bug report. Fixed in 2.4

**Comment by patrickf3139** [comment]
Nice, it works now! Thanks
