### ISSUE TITLE
[BUG] When I input "#" for header 1 , it can't show the text

### ISSUE THREAD

**Issue by Quorafind** [glushchenko/fsnotes#410]
![bug](https://user-images.githubusercontent.com/13215013/48659927-d89c1580-ea93-11e8-9202-d2f8456cf58d.gif)

And then if I switched another notes , it would show the text.
![bug2](https://user-images.githubusercontent.com/13215013/48659945-49dbc880-ea94-11e8-92bd-f288bba245da.gif)

**Comment by glushchenko** [comment]
Sorry but i don't know how to reproduce.

**Comment by glushchenko** [comment]
Please try new release https://github.com/glushchenko/fsnotes/releases/tag/2.5.2
