### ISSUE TITLE
deleting notes in iOS does not work.

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#414]
When I delete a note in iOS and then click back to **Notes** or my custom folder the note is still there. 

It also is remaining in my iCloud folder.

**Comment by glushchenko** [comment]
Did you turn on icloud drive? (Settings -> Apple ID -> iCloud -> FSNotes)

**Comment by hellonoko** [comment]
Yes I did, and it now seems to work. Might have had something to do with I cloud not being complete set up yet but I can't remember.
