### ISSUE TITLE
[REQ] Different way of deleting notes in iOS

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#415]
For me clicking the *** menu, selecting a note, then pressing the new menu and choosing 'delete' feels odd.

I think a more standard pattern is a left swipe on the table cell that represents the item that shows a Delete  / Move button.

Take a look at how: http://www.karelia.com/products/the-hit-list/iphone.html does this.

They also have functionality for if you need to do bulk delete / move.

**Comment by glushchenko** [comment]
Please make more detail bug report. Cell swipe already implemented long time ago.

![png- 4](https://user-images.githubusercontent.com/1089917/48967429-024fc200-efe9-11e8-902e-e78099cce295.png)
