### ISSUE TITLE
Can't delete notes macOS

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#416]
When right clicking a note and choosing delete the note disappears, but after relaunch the note is back and still in iCloud folder.

**Comment by glushchenko** [comment]
Anyone can confirm bug?

**Comment by semicolonsnet** [comment]
I can confirm same issue

**Comment by glushchenko** [comment]
Very strange. Will try to reproduce.

Notes not deleted only in iCloud or at any place on disk?

**Comment by semicolonsnet** [comment]
Tested on a subdirectory of my home directory and delete was successful. I can't delete either from iCloud directories associated with specific apps on iOS or from the general iCloud Drive space (~/Library/Mobile Documents/com~apple~CloudDocs). Interestingly, no issues creating new files or editing & saving them as far as I can tell.

**Comment by glushchenko** [comment]
Thank you for feedback! I reproduce it, will be fixed today.

**Comment by luckman212** [comment]
I am experiencing this bug on iOS - even with today's version 2.1.2

**Comment by glushchenko** [comment]
Please enable iCloud Drive and try again.

**Comment by luckman212** [comment]
I do already have iCloud Drive enabled.

**Comment by glushchenko** [comment]
Anyone can confirm and reproduce bug for iOS?

**Comment by glushchenko** [comment]
@luckman212 what iOS and iPhone version did you use?

**Comment by luckman212** [comment]
iPhone XS, iOS 12.1 (16B92)
