### ISSUE TITLE
macOS - dark mode flashes on launch.

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#417]
I have Mojave set to dark mode, and FSNotes set to light mode, on launch of FSNotes it will start in dark mode very briefly, just a flash, then change to light mode.

**Comment by glushchenko** [comment]
How can i reproduce the bug?

**Comment by hellonoko** [comment]
Set Mojave to Dark Mode
Set FSNotes to appearance: Light
Open FS Notes.

See attached screen capture.
[fs_notes.mov.zip](https://github.com/glushchenko/fsnotes/files/2612720/fs_notes.mov.zip)

**Comment by glushchenko** [comment]
I set Mojave in Dark Mode, FSNotes in Light and all works fine. May be something else i should know?

**Comment by buddax2** [comment]
I see this issue too. Will try to debug it
