### ISSUE TITLE
[REQ] - title and file name automatically take on the first line on the note.

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#418]
It would be nice if when I create a new note and type in something like 'grocery list' the title  and file name of the note becomes whatever i typed in on the first line.

It would also be nice if a double click of the notes title activated the title editing dialog.

**Comment by gingerbeardman** [comment]
Agreed.

Dupe of #279

**Comment by peavine** [comment]
Renaming a note by double-clicking the note name at the top of the editor window is an excellent idea. 

As to the other matter, and FWIW, I wrote in the thread referenced by gingerbeardman that:

"In the past I have used note apps in which the note name was automatically set to the first heading in the note, and I never found this to be helpful. If this feature is implemented, I hope there will be an option to disable it in preferences."

**Comment by buddax2** [comment]
I implemented double-clicking today here #419

**Comment by glushchenko** [comment]
Merged, thanks @buddax2

**Comment by glushchenko** [comment]
"Title from first line and preview from second" will be roll out with next update.

**Comment by peavine** [comment]
I just installed FSNotes 2.5 and the new feature to rename a note by double-clicking the note name works great. @buddax2 does nice work. Also, thanks for including a projects-view setting whether to use the first line of a note as the note title.
