### ISSUE TITLE
Search results are not highlighted

### ISSUE THREAD

**Issue by tuxtlequino** [glushchenko/fsnotes#42]
I am not sure if this is an issue or just an oversight, but when someone searches from a word, the pane only shows the files without highlighting the search keyword within the files. This is an unexpected UI behavior. 

Thanks for the work. This looks very promising.

**Comment by glushchenko** [comment]
Thank for feedback, @tuxtlequino. Planned in next releases.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/1.1.2
