### ISSUE TITLE
Sort-by-title setting not working as expected

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#420]
In FSNotes 2.5, project view settings include 1) sort by title, and 2) use first line as title. If I enable both of these settings, the note titles in the note list are sorted by file name rather than note title. I wondered if this is intentional.

**Comment by glushchenko** [comment]
Fixed in 4.0.18

**Comment by peavine** [comment]
I installed 4.0.18 and this issue is fixed. Thanks.
