### ISSUE TITLE
Show current note title in window title

### ISSUE THREAD

**Issue by Wholistic** [glushchenko/fsnotes#423]
**Desired Behaviour Request:**
Please make the app 'Window Title' reflect the currently selected note.

This is for compatibility with another app called http://timingapp.com 

I have also contacted that developer to also visit this issue request so that he can be clear and specific for how the app could improve compatibility. 

**Current Behaviour**

The current situation 'appears' to do this, but I don't think it is reported as part of the normal 'Window Title" value. 

![screen shot 2018-11-29 at 2 26 37 pm](https://user-images.githubusercontent.com/19315922/49197561-686e8780-f3e3-11e8-8afb-cb96ad5e6e72.jpg)

**Comment by glushchenko** [comment]
Thanks, @buddax2

**Comment by markabur** [comment]
Nice -- works for me with a similar app, Time Sink

**Comment by Wholistic** [comment]
Awesome work!
