### ISSUE TITLE
[Bug] Bouncing FSNotes icon can't be hidden

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#427]
I have enabled the macOS preference under "Dock" to automatically hide the dock. Beginning with 2.5.1, every time I load FSNotes, I see the FSNotes icon bouncing up and down at the bottom of my screen. This happens even if the dock is hidden and the cursor in not anywhere close to the dock. No other app does this.

Thanks.

**Comment by gingerbeardman** [comment]
This is related to #422

**Comment by glushchenko** [comment]
Please try 2.5.1 build 2.0.6

**Comment by peavine** [comment]
That works great--thanks.
