### ISSUE TITLE
Type to search

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#429]
If nvALT, typing immediately begins a search (unless the cursor is currently positioned in a document). Thus there is no *need* to do Cmd-L (although you can if you want to). This makes using the app quicker and simpler. Could we have this behaviour in fsnotes?

**Comment by peavine** [comment]
I've encountered a small issue with this new feature. If I capitalize the first letter of the search string, that letter is not shown in the Search or create bar. Thus, for example, typing Peavine yields eavine. If I first place the cursor in the Search or create bar, then Peavine is shown as expected. Thanks.

**Comment by glushchenko** [comment]
Fixed
