### ISSUE TITLE
`Cmd` + backspace triggers note deletion instead of standard Mac text-editing functionality (delete to beginning of line)

### ISSUE THREAD

**Issue by danseely** [glushchenko/fsnotes#43]
When focus is in the text editing pane, keyboard shortcuts should target the standard Mac platform functions; i.e. `Cmd` and `Alt` should address by-line and by-word movement respectively. While `Alt` works as expected for cursor movement and backspacing, and `Cmd` works as expected for cursor movement, the expected `Cmd` + backspace functionality is bypassed in lieu of note deletion. Example:

- create note, type a line of text
- with the cursor at the end of the line, hold `Cmd` and press the backspace key
  - expected: the line should be deleted with the cursor left at the beginning of the now-blank line
  - actual: note deletion is triggered, and the confirmation modal pops up

**Comment by glushchenko** [comment]
Thank for feedback, @tuxtlequino. I'll try to fix in next releases.

**Comment by danseely** [comment]
It's @danseely 😜

**Comment by glushchenko** [comment]
Of course, danseely🤦‍♂️😝
