### ISSUE TITLE
Click to rename

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#430]
I know the Cmd-R keyboard shortcut exists, but it would be nice to be able to click the title of a note in the sidebar and rename it (see nvALT for this behaviour).

**Comment by glushchenko** [comment]
Just click on title under edit area.

**Comment by williamsmj** [comment]
I'm sorry, I can't figure out what this means. Could you clarify? I've clicked pretty much everywhere in this UX, including both occurrences of the note title.

![image](https://user-images.githubusercontent.com/370930/49323519-769ad180-f4d1-11e8-93a7-aec198cf18a2.png)

**Comment by floodfish** [comment]
On desktop, double-clicking the note title over the note itself (not the list) seems to work.

I agree that retitling directly in the list would also be nice.

**Comment by peavine** [comment]
The note file name is present at the top of the editor window. If you double-click on this file name, it should go into edit mode and allow you to change the file name. I do this on a regular basis and it works as expected. This was a feature introduced with FSNotes 2.5, so you should check the version you are using.

**Comment by williamsmj** [comment]
Got it. Thanks.
