### ISSUE TITLE
FSNotes telegram group

### ISSUE THREAD

**Issue by glushchenko** [glushchenko/fsnotes#437]
Hello, guys! I want to share new communication channel in Telegram. 

https://t.me/joinchat/Aqckw1ZxoIGZkpmAvCh1cQ

**Comment by gingerbeardman** [comment]
What are the benefits?

**Comment by glushchenko** [comment]
I think it’s a good place for take fast answer on any question. GitHub for bugs and requests, Telegram about user experience.
