### ISSUE TITLE
[REQ] Support for publishing notes online

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#438]
I'm coming here as a Simplenote user, and I love their feature to be able to publish a note and get a link to a page with the contents of the note formatted using Markdown, e.g.: http://simp.ly/publish/8YHwcT

Building an internally-hosted tool for FSnotes would be a lot of work, and not necessary since there are so many existing platforms. Perhaps FSnotes could use a plugin system to send text content to a command line script. This could be a simple as adding a field in the Preferences to specify a shell script that accepts the body of the note as stdin. The script would contain code written by the user to send the text to a publisher service/pastebin of their choice, and return the URL for FSnotes to display. Perhaps by default, FSnotes could include a default script so the feature works “out of the box”. (My personal preference would be to use the awesome [Write.as](https://developers.write.as/) publishing platform.)

**Comment by gingerbeardman** [comment]
You can already do this using standard, inbuilt operating system features.

On macOS use Services. [Example](https://gist.github.com/rwilcox/1233190) 

On iOS using Apple's Shortcuts app. 

(PS: it drives me crazy that the same words mean completely different things when moving between iOS and macOS)

Let us know if you're successful, or need more help.

**Comment by quinncomendant** [comment]
Oh yes, so true. Services/Shortcuts can do this if a helper app is installed.

But if I want all changes to a note to be applied to the same published URL, like how Simplenote does it, that wouldn't work through Services/Shortcuts. FSNotes would need to send the changed note content and file ID to the script so it can update the post automatically without invoking Services/Shortcuts.

**Comment by gingerbeardman** [comment]
Ah, OK. Understood

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by webuniverseio** [comment]
Hello, I'm trying to understand what I can do with web sharing. I realize I can post to an "official" site for now and I can setup a custom server. For custom server do I need to install anything specific to be able to display notes? Or notes get uploaded in html format (based on what I see for one of the notes I posted it definitely is in html format with styles and everything). Is publishing supported both from iOS and from Mac?

Thank you!

**Comment by gingerbeardman** [comment]
I have published from iOS and macOS, but they published URL was not synced. So I had two URLs for the same note, which is obviously not ideal.

Custom server is any web server with SSH and SFTP support.
FSNotes uploads HTML and any associated images.
Code is at: https://github.com/glushchenko/fsnotes/blob/master/FSNotes/ViewController%2BWeb.swift
