### ISSUE TITLE
Notes List doesn't scroll when using ⌘J/⌘K to navigate

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#439]
When using `⌘J` to navigate down the list of notes (or `⌘K` to go up), when the selected note goes below the visible area, the list of notes doesn't scroll. The result is that the selected note is off the visible area. 

Using `↓` and `↑` to navigate doesn't have this problem; in that case the notes list scrolls correctly, always keeping the selected note visible.

Expectation: using `⌘J` and `⌘K` should have the same behaviour as `↓` and `↑`.

**Comment by peavine** [comment]
I installed FSNotes 2.5.2 and this works great now. Thanks.
