### ISSUE TITLE
Korean Characters are not appeared on main editor.

### ISSUE THREAD

**Issue by kainwet** [glushchenko/fsnotes#440]
![screen shot 2018-12-10 at 5 28 50 pm](https://user-images.githubusercontent.com/14261305/49719639-1100cf00-fca1-11e8-9287-ae04c1e7e420.png)

**Comment by buddax2** [comment]
@kainwet can you please paste those characters here so I can debug the issue?

**Comment by soycamo** [comment]
I had a similar problem when typing in Japanese. If I type something like これはノートです, the これは part disappears, but you can see it in the preview. If I type anything else, it completely disappears!

I think the Korean sentence is 한국아는 픞현이  안됨 (but I don't understand Korean).

**Comment by glushchenko** [comment]
Thank you for feedback, fixed in 2.5.2 https://github.com/glushchenko/fsnotes/releases/tag/2.5.2
