### ISSUE TITLE
Problem displaying unicode characters in code

### ISSUE THREAD

**Issue by hanche** [glushchenko/fsnotes#441]
I use the unicode character `⬥` (U+2B25 BLACK MEDIUM DIAMOND) as my shell prompt. This causes all sorts of trouble when I paste snippets of a terminal session into FSNotes.

To duplicate:
- Start a new file, put a code sample in it. Either inline or multiline, it doesn't matter.
- Paste in a single `⬥`, or some text containing that character, inside the code. It will display fine.
- Edit the code sample, inserting or deleting a character somewhere: The `⬥` character disappears from view
- Toggle into preview mode: All is well
- Toggle back: All is well, until the next edit of the source snippet
- However, adding a new empty line at the end of a multiline source code snippet restores the troublesome characters, until the next edit.
- Curiously, this happens both on macOS and on iOS.

**Comment by gingerbeardman** [comment]
I believe this is an issue in Down, the editor component that FSNotes uses

**Comment by hanche** [comment]
Okay. Is there an easy way to check that? Perhaps via some other app that also uses Down? I suppose [this](https://github.com/iwasrobbed/Down) is the editor in question? If we could be reasonably sure, it would certainly make sense to post the issue there.

**Comment by gingerbeardman** [comment]
Does the problem also happen when editing an RTF file?

**Comment by hanche** [comment]
It does not seem to happen with RTF files. (But then I never edit RTF files in FSNotes, except just now, to see if the problem happens there.)

**Comment by glushchenko** [comment]
Thank you for feedback, fixed in 2.5.2 https://github.com/glushchenko/fsnotes/releases/tag/2.5.2

**Comment by glushchenko** [comment]
Fixed in build 208

**Comment by hanche** [comment]
Indeed, it seems to work now. Thanks!
