### ISSUE TITLE
Hide dates in notes list

### ISSUE THREAD

**Issue by wyaqoob** [glushchenko/fsnotes#445]
Could a UI preference be added to hide the dates in the notes list?

Also I have a (very) minor grammatical correction for the preferences. In 'Editor', 'Focus in editor when select note' should be 'Focus in editor when **selecting** note'.

**Comment by peavine** [comment]
I installed FSNotes 3.0 and hiding note dates works great. Thanks. 👍

**Comment by glushchenko** [comment]
Added in FSNotes v3
