### ISSUE TITLE
[REQ] Customising Notes List and Side Bar

### ISSUE THREAD

**Issue by schlavinho** [glushchenko/fsnotes#449]
Hi! 
For me, the notes list and the side bar are a bit too cluttered.
Would it be possible to include an option to not show small previews of images in the notes list?
And in the Side Bar, I'd like to get rid of the folders "Todo" and "Archive" because I won't use them. Can that easily be made possible?
Thanks for all your wonderful work!

**Comment by luckman212** [comment]
I came here to suggest these same things.

Especially the option to **_NOT_** show the small images in the note list. Very important, as sometimes there are sensitive images contained, and I don't want them displaying all the time on my view.

**Comment by glushchenko** [comment]
From FSNotes 4.1.2 you can hide Todo/Archive etc.
