### ISSUE TITLE
[REQ] Show version number in settings window

### ISSUE THREAD

**Issue by keymasterr** [glushchenko/fsnotes#450]
When the dock icon is hidden, there is no way to check the version number.

It would be nice to see a humble gray text line at the very bottom of the settings window.
E.g. that could be needed when one wants to check if he has the latest version of the app.

**Comment by peavine** [comment]
I strongly suspect that @keymasterr is aware of this but, FWIW, you can check the FSNotes version by selecting from the top menu:

FSNotes  > About FSNotes

Perhaps I don't understand @keymasterr's request.

**Comment by keymasterr** [comment]
@peavine, when you uncheck “Shown dock icon” in the settings, there is no top menu for the app.

So, if you prefer FSNotes without the dock icon and want to check the version number, your scenario will be:

1. open the Settings window with the hotkey
2. check the “Shown dock icon” box
3. change the focused app (otherwise, the top menu will be not clickable, at least on macos 10.12)
4. call FSNotes again
5. top menu FSNotes > About FSNotes
6. [ hurray! ]
7. close the About window
8. open the Settings window
9. un-check the “Shown dock icon” box to return to your preferable state

Pretty too much, huh? :—)

**Comment by peavine** [comment]
@keymasterr. Thanks for the explanation, which makes everthing clear. I knew I was missing something but couldn't figure out what that was--especially what the dock had to do with the version number.

**Comment by keymasterr** [comment]
Actually, there is another (common) way to solve the problem: App can show its icon with an expanding menu in the menu bar like nvAlt does. But this step should have its own ticket and demands more reflection, I believe

**Comment by glushchenko** [comment]
Added in 2.9.0 (Preferences -> Advanced)
