### ISSUE TITLE
[BUG] Archive function breaks after changing default storage

### ISSUE THREAD

**Issue by manangatangy** [glushchenko/fsnotes#453]
With a cleanly installed FSNotes;
1. Start app for the first time
2. App prompts for initial storage location, => "~/Documents/Notes"
3. App creates this file structure;
![image](https://user-images.githubusercontent.com/5906257/50827181-e5513180-1391-11e9-86bb-e6edcdada37f.png)
4. Using FSNotes/Preferences, change "Default storage" => "~/Documents/Notes/NewDefault", app restarts itself
5. select FSNotes/FSNotes-CodeHighlighting and then from the menu File > Move > Archive
6. The selected note is not moved; it remains in the original folder, and the Archive remains empty even after exit/restart app.

**Comment by glushchenko** [comment]
Fixed in 2.6.0
