### ISSUE TITLE
Local images visible in edit mode with live image preview, but not in preview mode

### ISSUE THREAD

**Issue by ruffkat** [glushchenko/fsnotes#457]
i am using the App Store version of FSNotes and i use local relative image image links like the following:
```
![WIP Unbounded](media/scrum/wip-unbounded.png)
```
when in edit mode and the live image preview preference is enabled, the image is indeed visible. however, when switching to preview mode, only the alt text is displayed.

![image](https://user-images.githubusercontent.com/845997/51212054-f42d6c00-18dc-11e9-96d6-78882a985222.png)

![image](https://user-images.githubusercontent.com/845997/51212101-2048ed00-18dd-11e9-936d-98511aba71a5.png)

**Comment by glushchenko** [comment]
Fixed, thank you!
