### ISSUE TITLE
Right clicking on multi-selected notes fails

### ISSUE THREAD

**Issue by sweenzor** [glushchenko/fsnotes#458]
When you select several notes in the sidebar, while holding command (⌘) and then attempt to right click this group of notes, only the note under the mouse is selected

Three notes selected:
<img width="912" alt="screenshot 2019-01-16 at 3 28 58 pm" src="https://user-images.githubusercontent.com/212338/51285531-0f16e380-19a4-11e9-8442-cfb349262dfb.png">

Only bottom note will be deleted:
<img width="912" alt="screenshot 2019-01-16 at 3 29 17 pm" src="https://user-images.githubusercontent.com/212338/51285536-10481080-19a4-11e9-90f8-b1ac267cab4c.png">

**Comment by peavine** [comment]
I don't use the mouse much with FSNotes, but, FWIW, this seems a worthwhile change. I guess some items in the context menu--such as rename and print--would have to be grayed out?

**Comment by gingerbeardman** [comment]
Related (closed/completed) issue: 
https://github.com/glushchenko/fsnotes/issues/326

**Comment by glushchenko** [comment]
Please try 2.8.2

**Comment by peavine** [comment]
I installed 2.8.2 and everything works as expected. Thanks.
