### ISSUE TITLE
Strip markdown from note previews

### ISSUE THREAD

**Issue by sweenzor** [glushchenko/fsnotes#459]
Markdown formatting doesn't convey much information in the note previews. Suggest stripping it out.

Current note preview:
<img width="912" alt="screenshot 2019-01-16 at 3 34 50 pm" src="https://user-images.githubusercontent.com/212338/51285693-b562e900-19a4-11e9-8d85-805b2ce0c0e9.png">

Suggested modification:
<img width="912" alt="screenshot 2019-01-16 at 3 35 00 pm" src="https://user-images.githubusercontent.com/212338/51285694-b562e900-19a4-11e9-8653-94990200c5a8.png">

**Comment by sweenzor** [comment]
May also consider only showing one line of preview text

**Comment by gingerbeardman** [comment]
1. Markdown headings are stripped in the preview
2. size of preview text is now adjustable
