### ISSUE TITLE
"Exiting" a note should reset cursor (and scroll position)

### ISSUE THREAD

**Issue by sweenzor** [glushchenko/fsnotes#460]
When "Restore-Cursor-Position" preference option is **disabled**:

When a note has been edited, or the edit field clicked, the cursor location defines the scroll position of that note. Even after navigating to another note and returning.

Suggest that when this option is disabled, notes default to opening at the top, matching behavior of Apple Notes, etc.

<img width="912" alt="screenshot 2019-01-16 at 3 28 02 pm" src="https://user-images.githubusercontent.com/212338/51285876-6b2e3780-19a5-11e9-9b3e-f26e6db9bd14.png">

**Comment by glushchenko** [comment]
Please try 2.8.2

**Comment by peavine** [comment]
I installed 2.8.2 and this works great for me. Thanks.
