### ISSUE TITLE
Expand padding around text fields

### ISSUE THREAD

**Issue by sweenzor** [glushchenko/fsnotes#461]
For ease of readability and user comfort, suggest increasing the padding around text fields in the UI.

FSNotes vs. Apple notes for comparison:
<img width="912" alt="screenshot 2019-01-16 at 3 43 44 pm" src="https://user-images.githubusercontent.com/212338/51286163-ae3cda80-19a6-11e9-8d1e-880ec3798730.png">
<img width="911" alt="screenshot 2019-01-16 at 3 48 52 pm" src="https://user-images.githubusercontent.com/212338/51286164-ae3cda80-19a6-11e9-9662-77922d83f0de.png">

**Comment by gingerbeardman** [comment]
I agree

**Comment by peavine** [comment]
Just my 2 cents but I find the padding in both the notes list and editor to be just about right. I use a courier font in the editor, and I suspect that makes some difference as compared with the default font.

**Comment by sweenzor** [comment]
Appreciate the perspective @peavine!

**Comment by gingerbeardman** [comment]
@peavine if you fiyouthe current lack of margins right, what is wrong about the Notes margins? 

Fwiw: margins are proven to improve readability, eg. https://uxmovement.com/content/how-margins-and-line-lengths-affect-readability/

**Comment by peavine** [comment]
@gingerbeardman. I don't understand your question. For me, the margins in the notes list are fine and the margins in the editor are fine. The margins I'm referring to are the green lines in @sweenzor's post.

**Comment by gingerbeardman** [comment]
Please try gain, I have edited my post above (Notes to Notes.app)

**Comment by peavine** [comment]
@gingerbeardman. I find nothing wrong with the margins @sweenzor has proposed. My personal preference is for smaller margins and less white space; that's all.

**Comment by glushchenko** [comment]
For text editor added in 2.9.0

**Comment by quinncomendant** [comment]
Can the margins be dynamic, i.e., a percentage of the window width? When using very narrow windows on small screens, it's nice to maximize use of the window's limited size.

Screenshots: [this one](https://i.imgur.com/SZeUrOp.png) should have wide margins, but [this one](https://i.imgur.com/JA1Kmmg.png) should not.

**Comment by gingerbeardman** [comment]
What do I have to do to see this in 2.9.0?

**Comment by jeff-h** [comment]
@gingerbeardman prefs > editor > line width

**Comment by gingerbeardman** [comment]
This is not quite what I was hoping for

**Comment by glushchenko** [comment]
> When using very narrow windows on small screens, it's nice to maximize use of the window's limited size. ...

@quinncomendant you can.

**Comment by peavine** [comment]
I leave the new line-width preference option set at its maximum, but I was curious about something. The line-width slider from its midpoint to maximum does not change the line width even a little bit. Is there a reason for this?

For the editor, I  use a fixed-width courier font at a large size and I thought this might be the reason for this behavior.

BTW, I like this new feature, as it allows everyone the ability to change the margins to their own preference.

**Comment by gingerbeardman** [comment]
> I leave the new line-width preference option set at its maximum, but I was curious about something. The line-width slider from its midpoint to maximum does not change the line width even a little bit. Is there a reason for this?

Your window needs to be bigger.

**Comment by peavine** [comment]
@Gingerbeardman. I maximized FSNotes to the entire screen and retested.

The line-width slider was set at the maximum and I moved it just a tiny bit away from maximum. The editor took on a really-large margin. I guess that's the issue being discussed above. 

Thanks for the clarification.

**Comment by glushchenko** [comment]
@peavine, maximum width is equal to max size.

**Comment by peavine** [comment]
I've added two screenshots to demonstrate what I'm talking about. Both screenshots were taken with FSNotes maximized. The first screenshot is with the line-width slider at its maximum and the second screenshot is with the slider perhaps 5 percent away from maximum. It seems like the slider should be more granular.

Perhaps I don't understand the issue. I'll leave the slider at maximum size, which I prefer. 

<img width="1920" alt="maximum" src="https://user-images.githubusercontent.com/35905279/52578740-11712f80-2de2-11e9-8416-03c6d66d41db.png">

<img width="1920" alt="reduced" src="https://user-images.githubusercontent.com/35905279/52578757-19c96a80-2de2-11e9-9dd5-9bdcd0e7c961.png">

**Comment by gingerbeardman** [comment]
This does not work well for me.

I expect the margins to remain the same when window size changes.

Current option limits length of line regardless of window size.

Also see #260

**Comment by jeff-h** [comment]
> I expect the margins to remain the same when window size changes.

I think this captures it perfectly. This setting should adjust the number of pixels of whitespace on the left and right side of the text. It could possibly even be renamed margin width.

**Comment by gingerbeardman** [comment]
Perhaps there's a use case for both? I'm not sure...

**Comment by glushchenko** [comment]
@gingerbeardman new settings added ;)

**Comment by glushchenko** [comment]
Please try last build.

**Comment by peavine** [comment]
I installed FSNotes build 248 and the new margin-size setting works great.

**Comment by peavine** [comment]
FSNotes build 249 has a preference for line width but it doesn't seem to do anything. I was curious as to its purpose. 

BTW, the margin-size setting still works great in build 249.

**Comment by gingerbeardman** [comment]
@peavine I also see that problem

@glushchenko seems to be an issue

**Comment by glushchenko** [comment]
Added in FSNotes v3
