### ISSUE TITLE
Printing white pages in Preview mode

### ISSUE THREAD

**Issue by ulab** [glushchenko/fsnotes#462]
Hello,

printing a formatted (previewed) note results in an empty white page.

It'd be nice if we could print a formatted page :).

**Comment by quinncomendant** [comment]
I just noticed the same problem. 

**Printing while in edit mode:**

<img width="1003" alt="screen shot 2019-02-07 at 17 56 42" src="https://user-images.githubusercontent.com/6884276/52450760-1001e780-2b02-11e9-9125-bb8436616e80.png">

**Printing while in preview mode:**

<img width="1000" alt="screen shot 2019-02-07 at 17 57 00" src="https://user-images.githubusercontent.com/6884276/52450776-1beda980-2b02-11e9-9101-936e5a9e44c4.png">

**Comment by glushchenko** [comment]
Hi, guys. You all definitely should try FSNotes 2.9.2. Thanks for feedback.

**Comment by ulab** [comment]
Seems to work here. Thank you for fixing it.
