### ISSUE TITLE
[BUG] note row shows outdated text contents as note is edited

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#469]
Not sure when this started happening.

In this screenshot the note row shows the old contents, which has since been deleted and replaced with "OK"

I have to restart the app to get it to display correctly.

![screen shot 2019-01-24 at 16 05 49](https://user-images.githubusercontent.com/49612/51691070-f5a01800-1ff1-11e9-9c70-1d17404ae73b.png)

**Comment by glushchenko** [comment]
Fixed in 2.7.4

**Comment by gingerbeardman** [comment]
Still broken for me.

**Comment by glushchenko** [comment]
Fixed

**Comment by peavine** [comment]
I installed 2.9.3 and this works well. Thanks.
