### ISSUE TITLE
url scheme to create file

### ISSUE THREAD

**Issue by voltaireodactyl** [glushchenko/fsnotes#471]
Is there a current working URL scheme to create a new file? I found references to a non-working version but can't find anything current. Thanks for any info.

**Comment by jeff-h** [comment]
The following all work:

fsnotes://new
fsnotes://new/?title=URI-escaped-title&html=URI-escaped-HTML-data
fsnotes://new/?title=URI-escaped-title&txt=URI-escaped-plain-text
fsnotes://new/?txt=URI-escaped-plain-text

@glushchenko is this documented anywhere? If not, I'm not sure where would be best — perhaps a WIKI here on github?

**Comment by glushchenko** [comment]
@jeff-h can you write wiki docs here?

**Comment by jeff-h** [comment]
At present I personally can't write in the wiki for this project — you'd have to change the wiki permissions. I've contributed to several other projects' wikis on Github and thought the concept worked pretty well for documentation.

**Comment by glushchenko** [comment]
You can now, please try. Wiki opened for all.

**Comment by jeff-h** [comment]
Thanks :) I have added a brief note reflecting the above, but it's hardly inspiring content :) I will flesh it out further when I have a little more time. Hopefully others will contribute also.

**Comment by jeff-h** [comment]
Got inspired and fleshed it out now :) Please let me know (and/or improve it directly) if it doesn't explain things sufficiently.

**Comment by glushchenko** [comment]
Awesome, thank you @jeff-h
