### ISSUE TITLE
Find submenu items disabled while focus is in find field

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#472]
As of FSNotes 2.7.2, while searching in a note (`⌘F`), if the focus is the find field, the _Find_ submenu items are disabled (see first screenshot), so you cannot run _Find Next_, etc (actually, the _Jump to Selection_ item is enabled, but shouldn't be since there is no selection). 

You can experience this issue:

1. Open a note
2. Type `⌘F` and enter a search string.
3. Type `Return/Enter` to execute the search.
4. Type `⌘G` to do find next – _nothing happens_ 🙀

If the focus is in the note content, the submenu items are available (second screenshot). These menu items should be enabled so they can be executed without needing to put the cursor in the note content.

These find submenu items should be available in the following contexts:

- _Find…_ – all contexts, if a note is open.
- _Find and Replace…_ – all contexts, if a note is open.
- _Find Next…_ – all contexts, if a note is open and a search string exists in the _Find_ field or _Search and create_ field.
- _Find Previous…_ – (same as _Find Next_).
- _Use Selection for Find…_ – any context where text can be selected (even if _no text is selected_, which can be used to reset the search string).
- _Jump to Selection…_ – all contexts, if a selection exists in the note content.

<img width="562" alt="screen shot 2019-01-27 at 10 19 27" src="https://user-images.githubusercontent.com/6884276/51803848-2add7d80-221f-11e9-84fa-3794c148e94c.png">
<img width="560" alt="screen shot 2019-01-27 at 10 20 04" src="https://user-images.githubusercontent.com/6884276/51803850-32048b80-221f-11e9-99ff-150a7f43fa92.png">

**Comment by glushchenko** [comment]
Implemented in 2.7.4

**Comment by quinncomendant** [comment]
Thanks for getting to this so quickly, @glushchenko!

Can we also have the Find submenu items enabled when the cursor context is set in the _Search and Create_ field? That would allow immediately searching inside a note without first needing to move the context to the note content area:

1. Launch FSNotes.
2. Invoke _Search and Create_ (`⌘L`).
3. Type a search string, e.g., “lorem ipsum”.
4. Type `⌘J` to select the first matching note.
5. Type `⌘G` to locate “lorem ipsum” in the note contents – **nothing happens because the _Find Next_ command is disabled**

I notice when you do _Search and Create_, the search string is automatically copied to the _Find_ field – which is great, because it facilitates the above workflow. We just need to be able to execute the find submenu commands in more contexts. I would suggest them to _always_ be enabled, if a note is selected, irregardless of the cursor context.

**Comment by glushchenko** [comment]
Please checkout FSNotes 2.8.0
