### ISSUE TITLE
Unexpected gap at the top of content when using find 

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#473]
As of FSNotes 2.7.2, while searching in a note (`⌘F`), a large space appears at the top of the content area (see first screenshot). Otherwise, when the find function is hidden, the top of the content area has a suitable margin (second screenshot).

<img width="560" alt="screen shot 2019-01-27 at 21 19 33" src="https://user-images.githubusercontent.com/6884276/51813081-1c707f80-227a-11e9-9bcf-87609ada087f.png">
<img width="560" alt="screen shot 2019-01-27 at 21 19 25" src="https://user-images.githubusercontent.com/6884276/51813082-1d091600-227a-11e9-8af4-cf82f5948b8c.png">

**Comment by glushchenko** [comment]
Fixed in 2.7.4
