### ISSUE TITLE
Paste command should be pushed onto the undo stack

### ISSUE THREAD

**Issue by erikrose** [glushchenko/fsnotes#474]
Right now, when you paste, you cannot undo it via command-Z or whatever. That throws me off because it's different from TextEdit, BBEdit, Firefox, etc. It's a common need for me: I paste, discover the wrong thing was on the clipboard, and then want to undo it.

**Comment by glushchenko** [comment]
FSNotes build?

**Comment by erikrose** [comment]
2.6.0 (215)

**Comment by jeff-h** [comment]
@erikrose you should grab the latest version. This bug is already fixed in that, as far as I can see :)

2.7.3 is available on the Mac App Store, and from https://github.com/glushchenko/fsnotes/releases

**Comment by erikrose** [comment]
Right you are! :-D Sorry to noise up the channel. Thanks!
