### ISSUE TITLE
Dragging in a note

### ISSUE THREAD

**Issue by writerguy** [glushchenko/fsnotes#475]
I often have lists in FSNotes and want to rearrange them. It would be a huge help if I could highlight and drag text within a note to rearrange it. Any chance that functionality can be added? Thanks.

**Comment by writerguy** [comment]
I often have lists in FSNotes and want to rearrange them. It would be a huge help if I could highlight and drag text within a note to rearrange it. Any chance that functionality can be added? Thanks.

**Comment by glushchenko** [comment]
Will be added soon

**Comment by quinncomendant** [comment]
Even better would be a way to move selected line(s) up or down using _only the keyboard_. I have macros in Textmate that do this using `⌘⌃↑` and `⌘⌃↓` – it's really useful. 😁

<img width="472" alt="screen shot 2019-01-29 at 19 43 41" src="https://user-images.githubusercontent.com/6884276/51952482-4baff980-23fe-11e9-81c6-36029455e755.png">

**Comment by glushchenko** [comment]
Added in 2.7.5
