### ISSUE TITLE
Find text highlighting artifacts when switching notes

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#476]
The yellow-highlighted text during a find don't function correctly if switching notes while doing a find.

1. Here is a screenshot of the result of doing a find for “lorem” after selecting the first note in the list. The highlights work as expected.

<img width="560" alt="screen shot 2019-01-29 at 13 47 55" src="https://user-images.githubusercontent.com/6884276/51936584-273c2900-23ce-11e9-8829-06f39a616e35.png">

2. Now, if you move to another note (I use `⌘J` and `⌘K`), the positional offsets of the highlights remain the same in the other notes, and they no longer correspond to the location of the text “lorem”:

<img width="560" alt="screen shot 2019-01-29 at 13 48 12" src="https://user-images.githubusercontent.com/6884276/51936753-839f4880-23ce-11e9-9db9-d089f791acc0.png">

To fix that, I think it the find routine needs to be reinitialized and the text analyzed again.

3. The next strange thing: if you cancel the find operation (click _done_ in the find bar), _then_ navigate back to the note that I originally started the find from, the matching text are still highlighted even when no find function is running:

<img width="560" alt="screen shot 2019-01-29 at 13 48 50" src="https://user-images.githubusercontent.com/6884276/51937031-28ba2100-23cf-11e9-8763-8560518d13b3.png">

[Here's a video showing this issue.](https://github.com/glushchenko/fsnotes/files/2809481/FSNotes.-.find.string.highlighting.mov.zip)

**Comment by quinncomendant** [comment]
The position offsets of the highlights are now matching the correct strings when selecting other notes (issue #2 from above). However, I'm still seeing highlights when the find bar is gone, as per the below screenshot. Is this expected behavior? How to make the highlights go away?

<img width="560" alt="screen shot 2019-01-29 at 13 48 50" src="https://user-images.githubusercontent.com/6884276/51937031-28ba2100-23cf-11e9-8763-8560518d13b3.png">

**Comment by glushchenko** [comment]
Yep, it's expected behaviour
