### ISSUE TITLE
[REQ] New app icon for v3?

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#477]
I think the app has come a long way, I'd be happy to submit a new logo for the next big milestone v3!

Old thread: https://github.com/glushchenko/fsnotes/issues/197#issuecomment-383888900

Thoughts?

**Comment by peavine** [comment]
I've always liked the current icon because it's distinctive. However, it does lack a bit in the polish department, and FSNotes is no longer the brash upstart and is instead a fairly polished app. I'll be interested to see what you design.

**Comment by glushchenko** [comment]
@gingerbeardman i think this is a good idea

**Comment by peavine** [comment]
The earlier thread contained a link to Apple's Human Interface Guidelines for app icons. Just for background information, I thought it might be helpful to repost that link, which is:

https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

One point raised in the linked document is:

"Your macOS app icon should be recognizable, but not an exact copy of your iOS app icon. In particular, the macOS icon shouldn’t use the same rounded rectangle shape that the iOS icon uses."

It probably makes sense to first design the macOS icon?

**Comment by peavine** [comment]
@gingerbeardman. I'll look forward to the icon you design. It's absolutely OK if it incorporates none of my ideas. FSNotes is a good app and deserves a nice icon.

**Comment by gingerbeardman** [comment]
What about this lightning bolt shaped notepad?

(first draft: I'm not happy with the metallic look of the rings)

![icon](https://user-images.githubusercontent.com/49612/52127774-06244400-262b-11e9-9d54-8a41fe13be6d.png)

**Comment by gingerbeardman** [comment]
Another good "guide" on icon style http://martiancraft.com/blog/2014/07/inspecting-yosemite-icons/

Here is where I am right now:

![512](https://user-images.githubusercontent.com/49612/52168889-cdb66000-2727-11e9-93b1-1bcf0883ffee.png)

**Comment by peavine** [comment]
The new icon looks nice but it seems that the lightning bolt is too prominent compared with the note.

**Comment by gingerbeardman** [comment]
Here it is with just one lightning bolt, without the "stack". Also managed to get a subliminal F in there so it read "F⚡️" which is quite close to "FS"

![512](https://user-images.githubusercontent.com/49612/52185352-b5713e80-2816-11e9-9ccd-d21261f34e66.png)

Icon file for those who want to live with it [AppIcon.icns.zip](https://github.com/glushchenko/fsnotes/files/2826189/AppIcon.icns.zip)

**Comment by peavine** [comment]
I installed the new icon file and then looked at the FSNotes icon in launchpad. It looks very nice and gets my vote so far. The subliminal F is a great touch. 

BTW, have you tried different colors for the lightning bolt? The reason I ask is that you had a yellowish one in the text of your previous post and I wondered how that would look.

**Comment by gingerbeardman** [comment]
Will give it a go, I do like yellow. And blue.

**Comment by jeff-h** [comment]
Nice work @gingerbeardman :) I reckon it's a good direction and worth fine-tuning.

I tried it in my dock; I have too many apps in my dock so the icon ends up being ~32x30px (albeit 2x retina). Unfortunately when it's that tiny it's a little undistinguished, so when you have settled on the overall direction, I'm hoping you might take a peek at it tiny and see if there are some optimisations that might be made for small sizes.

(Ironically my first thought (at this size) is in contradiction with the consensus above — I feel the lightning bolt could be larger at this dimension).

**Comment by gingerbeardman** [comment]
Mellow Yellow: [AppIcon.icns.zip](https://github.com/glushchenko/fsnotes/files/2828247/AppIcon.icns.zip)

![512](https://user-images.githubusercontent.com/49612/52212134-b1c7d100-2883-11e9-91dc-e3c7ddc44f22.png)

![untitled 2](https://user-images.githubusercontent.com/49612/52212113-a70d3c00-2883-11e9-80fe-92d8b4d49e2e.png)

**Comment by peavine** [comment]
I installed the new icon (yellow thunderbolt) and viewed it in launchpad and dock. It gets my vote.

**Comment by gingerbeardman** [comment]
Ooh that does look good.

**Comment by glushchenko** [comment]
Difficult to see yellow on white, my vote goes for blue :)

**Comment by gingerbeardman** [comment]
I think I will be able to call in a favour and have the app considered for a Mac App Store feature. @glushchenko it will require some coordination help from you regarding the release. What do you think?

**Comment by glushchenko** [comment]
> I think I will be able to call in a favour and have the app considered for a Mac App Store feature. @glushchenko it will require some coordination help from you regarding the release. What do you think?

I'm ready to go. What do we have to do?

**Comment by quinncomendant** [comment]
> I installed the new icon (yellow thunderbolt) and viewed it in launchpad and dock. It gets my vote.

It's nice that the yellow is the same as the Apple Notes app. Also a nod to old-style yellow-paper legal pads.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/issues/481

**Comment by gingerbeardman** [comment]
Let's get in contact on Telegram/Whatsapp/iMessage etc.

**Comment by glushchenko** [comment]
@gingerbeardman https://t.me/og_ua

**Comment by gingerbeardman** [comment]
Latest (in yellow only for now) [AppIcon.icns.zip](https://github.com/glushchenko/fsnotes/files/2832297/AppIcon.icns.zip)

![512](https://user-images.githubusercontent.com/49612/52277213-0a62a100-294c-11e9-9626-13eb86512cb4.png)

**Comment by peavine** [comment]
The yellow thunderbolt icon looks good on a blue screen background but not on white. The blue thunderbolt icon looks good on a white screen background but not on blue. I wonder if a deep-red thunderbolt icon (like the Fastscript's color) might look good on both both blue and white screen backgrounds? In all of these cases we would keep the notepad background for the macOS icon.

BTW I installed the latest yellow thunderbolt icon and it looks great.

**Comment by gingerbeardman** [comment]
I think the visibility of the icon on white an be mostly solved using some tweaks to the outlines and adding contrast. 

A quick rearrange for iOS gives this (not happy with it so I will probably keep the sentiment of the icon but do a bespoke arrangement)

![roundedicon](https://user-images.githubusercontent.com/49612/52280789-9082e580-2954-11e9-930a-efbfaa147999.png)

**Comment by keymasterr** [comment]
I really like the idea of lightning and hidden letters FS.

Yet I'll put my two cents:
In its current state icon looks more like a document type than the app. It's totally ok when the idea of the app is _to create a document_. But I believe FSNotes is mostly utility app, unique not with its filetype but with the way it's working itself.
Possible solve is to draw a stack of paper (or some kind of an _app block_ with note in it) instead of a single sheet.
I really don't like an existing icon of v2 but I see it is much more solid as an idea.

And small visual buts:
1. The spike of the lightning below the bottom border of note is too thin and sharp, making uncomfortable tremble
![image](https://user-images.githubusercontent.com/6844067/52289716-44956800-2977-11e9-94f4-03e01ee184ad.png)
2. While text lines and list bullets aren't meaningless, they are too thin and low-contrast. I guess, there is no need in that amount of lines to draw F letter
![image](https://user-images.githubusercontent.com/6844067/52290262-5aeff380-2978-11e9-984b-b5fcd7a747bc.png)

**Comment by gingerbeardman** [comment]
Another iOS idea

![simulator](https://user-images.githubusercontent.com/49612/52291579-94216700-296a-11e9-9c2a-5ed9062171cd.png)

**Comment by gingerbeardman** [comment]
@keymasterr thanks for the feedback — much appreciated!

My inspiration for the macOS icon were TextEdit and Pages. Both feature a "pen" and "paper".

- spike
- low contrast lines
= I agree, will take a look.

Not sure what you mean about amount of lines needed? Can you demonstrate?

**Comment by keymasterr** [comment]
@gingerbeardman Yep, I had a thought about the roots of your inspiration :-) But there is a catch: and the idea of TextEdit is to be the most common OS default text editor, and Pages have unique filetype which is clearly demonstrated in its icon.
And both are working with certain _“files”_ while FSNotes' context is something like _“database”_ (something you don't mind until you want to backup or sync :-)

About lines and F
Both higher contrast and fewer lines. Also, bullets have to be a bit bigger than the text line for visual compensation needs. Roughly and a little bit hyperbolic:
![image](https://user-images.githubusercontent.com/6844067/52293757-50395c80-2980-11e9-90c2-05a916024754.png)

**Comment by gingerbeardman** [comment]
OK, I see, the latest icon is more like what you describe. You're using a very early version of the revised icon. Try the one in 
https://github.com/glushchenko/fsnotes/issues/477#issuecomment-460642409

**Comment by gingerbeardman** [comment]
Meanwhile, latest: 
[AppIcon.icns.zip](https://github.com/glushchenko/fsnotes/files/2833391/AppIcon.icns.zip)

![512](https://user-images.githubusercontent.com/49612/52296391-21b68400-2976-11e9-97e8-2e8ac21a220d.png)

**Comment by gingerbeardman** [comment]
Meanwhile, latest: 
[AppIcon.icns.zip](https://github.com/glushchenko/fsnotes/files/2833391/AppIcon.icns.zip)

![512](https://user-images.githubusercontent.com/49612/52296391-21b68400-2976-11e9-97e8-2e8ac21a220d.png)

**Comment by sweenzor** [comment]
dang that looks great!

**Comment by sweenzor** [comment]
wow that looks great!

**Comment by keymasterr** [comment]
Just a quick sketch of a little bit modified idea of the proposed icon. Few thoughts behind this image:
- Not just _lightning_ but _lightning-fast_ and those strings of text can also be a swoosh of speed
- Rounded corners and a little bit of volume of background to make it more solid (more of an app than the schematical sheet of a document)
- Keeping hidden F
- Keeping the angle of the icon
- Text/swoosh/F is on the same layer with lightning
- The left border of background plate with protruding bars of text can look like a notepad spring
- Yellow on white is too bright, making mess in small sizes. Therefore yellow lightning should be darker, have a border or be of different color. Here I choose the latter

What do you think?


![image](https://user-images.githubusercontent.com/6844067/52486873-f675a400-2bc4-11e9-8b1d-483483c0321a.png)

**Comment by gingerbeardman** [comment]
I love it, great improvements. I'll pursue this direction

**Comment by quinncomendant** [comment]
Don't forget to make a dark theme icon too! 😜

But seriously, don't get too focused on finding the exact color right away, just make sure the icon looks good with any color choice. Perhaps someday you'll want to provide multiple icon choices for the user to choose. E.g., here's what the Apollo and PCalc apps offer (with some icons unlocked via in-app purchase):

<img src="https://user-images.githubusercontent.com/6884276/52497169-037d9d80-2b9b-11e9-952f-da1d20507151.PNG" width="300"><img src="https://user-images.githubusercontent.com/6884276/52497179-09737e80-2b9b-11e9-9d67-c48cdd395c74.jpeg" width="300">

**Comment by keymasterr** [comment]
@quinncomendant yep, take a look at dark-mode Dock on the right of my image. There is the same icon in the real-life small size for testing purpose. (And readability on dark is why text bars are brighter from the left)

**Comment by gingerbeardman** [comment]
Will resume work on this on Monday.

**Comment by glushchenko** [comment]
@gingerbeardman see menu bar icon in 2.9.5. May be we can improve it?

**Comment by gingerbeardman** [comment]
> @gingerbeardman see menu bar icon in 2.9.5. May be we can improve it?

Definitely, will include a "monochrome" version for there.

**Comment by peavine** [comment]
I had earlier posted screen shots of launch pad with the then-current FSNotes replacement icon and thought I would do this again with the most recent replacement icon. I think it looks great, but it's important to see how it would look on backgrounds other than blue. 
<img width="411" alt="fsnotes" src="https://user-images.githubusercontent.com/35905279/53427349-03a4d800-39a6-11e9-8163-c4c647113391.png">

**Comment by gingerbeardman** [comment]
Yes, the yellow really becomes a problem at small sizes.

**Comment by peavine** [comment]
@gingerbeardman. You have a tough job. You not only have to draw a nice icon but one that works on different backgrounds and at varous sizes. It's a lot of work.

BTW, I posted above the Fastscripts icon, which I think is very nice looking. It's hard to discern what the Fastscripts menu-bar icon really is. So, at really small sizes, there's probably only so much that can be done.

**Comment by keymasterr** [comment]
@gingerbeardman
I can help with the final icon creation. (i don't want to interrupt your work if you started it already though).

Just in case, my telegram is @keymasterr and mail is kmstrr@gmail.com

**Comment by gingerbeardman** [comment]
Hi, feel free to go for it. We're actually having a baby today/tomorrow!

**Comment by gingerbeardman** [comment]
@keymasterr did you make any progress?  I have some time today to pick it up.

**Comment by keymasterr** [comment]
Yep. I was going to show it in a little bit more complete view, though I can take some comments already. I tried several completely different mockups and returned back to what I showed here. Now searching for the best elements forms and colors.

Dark Dock icon, iOS one and big icon on white. Small icons for lists in Finder (like filetype ones) and black-and-white for menubar are coming. What do you think about this? @glushchenko ?
![image](https://user-images.githubusercontent.com/6844067/54741467-3a49c900-4bc7-11e9-8d37-6239005010b6.png)

**Comment by keymasterr** [comment]
Not the final version yet, but the one that can be tried on
https://www.dropbox.com/s/l4qlwiqp87cpsab/AppIcon.icns?dl=1

**Comment by peavine** [comment]
I downloaded and installed the new icon, and I've posted a screenshot below to compare with that which I posted above. I **strongly acknowledge** that one icon may look better than the other depending on icon size and background. 


<img width="402" alt="FSNotes" src="https://user-images.githubusercontent.com/35905279/54936441-b7cf4b00-4edf-11e9-8b50-71321a8f19c2.png">

**Comment by gingerbeardman** [comment]
Looking good! @keymasterr 

I'm not able to download the icon yet, but there seems to be a purple highlight around it in @peavine  screenshot?

**Comment by keymasterr** [comment]
Yes, there is a purple shadow. Maybe I overdid it a little bit though :-) I'll fix the color in next iteration.

As you could see from my previous screenshot, I also want to try to add more volume and skeuomorphism.

More of the current version screenshots in the Dock, Cmd+Tab panel and small-sized icon in Finder's list:
![image](https://user-images.githubusercontent.com/6844067/54946983-ef6edf00-4f41-11e9-8109-bdaad92e090e.png)
<img width="1419" alt="Screen Shot 2019-03-25 at 21 04 57" src="https://user-images.githubusercontent.com/6844067/54947000-f7c71a00-4f41-11e9-84e1-81335fd9cb2a.png">
![image](https://user-images.githubusercontent.com/6844067/54947014-01e91880-4f42-11e9-8d68-57f1ea4fee38.png)

**Comment by gingerbeardman** [comment]
Great work!

The colours of symbol, shadow and page all look very pink/purple to me.

**Comment by gingerbeardman** [comment]
I see we need more icons for prefs dialog

:)

**Comment by glushchenko** [comment]
@keymasterr icon added in last release.

**Comment by gingerbeardman** [comment]
I am finishing new icons, please do not release final 3.0 until I send them

also, we need to submit for possible app store feature.

**Comment by glushchenko** [comment]
@gingerbeardman ok, i will wait your icon

**Comment by glushchenko** [comment]
@gingerbeardman any news?

**Comment by glushchenko** [comment]
I think we should release v3. So many time without updates is not good

**Comment by gingerbeardman** [comment]
I will upload icons tomorrow :) we've just had a baby so I am finding time in between.

**Comment by gingerbeardman** [comment]
today is icon day :)

**Comment by gingerbeardman** [comment]
I tried blue so much, but it kept clashing with the default macOS highlight colour blue in various places (like Finder selected rows)

So I am now as below, back to a dark yellow with more shading. Barring any serious complaints, I'll complete all icons and get them merged in ready for submission of V3.

![256](https://user-images.githubusercontent.com/49612/56867041-75b29100-69d8-11e9-843f-e8e6b326f893.png)

![Untitled](https://user-images.githubusercontent.com/49612/56867051-a692c600-69d8-11e9-9a63-1d2c96239405.png)

![Screen shot 2019-04-28 at 17 11 13](https://user-images.githubusercontent.com/49612/56867054-a7c3f300-69d8-11e9-9575-b44ee218632d.png)

**Comment by luckman212** [comment]
Sorry to be late to the icon party, but as 3.0GM nears I wanted to put in a comment:

Something about the shape of the lightning here just doesn't feel right. (1) why is the very bottom "cut off"? It doesn't look sharp/clean/fast due to that. (2) the way the middle segment slopes downward is a little out of line with typical lightning bolts. I think something like [this](http://www.iconarchive.com/show/small-n-flat-icons-by-paomedia/lightning-icon.html) style would look better:

![image](https://user-images.githubusercontent.com/1992842/56898513-32e7cc00-6a5f-11e9-9a3a-88798827f158.png)

Actually scrolling up, I see an older style from @gingerbeardman [here](https://github.com/glushchenko/fsnotes/issues/477#issuecomment-460642409) that looks much nicer to me.

**Comment by gingerbeardman** [comment]
@luckman212 the issue thread is so long now GitHub is hiding part of it (at least for me) the disunion about the "point" of the bolt is at https://github.com/glushchenko/fsnotes/issues/477#issuecomment-460719136 and was essentially that the point became indistinguishable and more of a tremble/annoyance were it produced, especially at smaller sizes. I took the point as constructive critics and changed it. I don't have a strong preference either way, but I do appreciate that point... about the point.

**Comment by gingerbeardman** [comment]
Congrats with V3 launch! @glushchenko 

I feel we ran out of steam on the icon towards the end. The solution of including two icons is good. Hopefully we can refine icons as we go on, menu bar icon, prefs icons, etc.

Onwards! 👍

**Comment by glushchenko** [comment]
Thanks, guys, think we can close ticket. For suggestions and improvements I am always available in Telegram or Mail.
