### ISSUE TITLE
Shortcut Hide/show sidebar does not work when Notes list is closed 

### ISSUE THREAD

**Issue by nauta** [glushchenko/fsnotes#479]
The shortcut to show/hide the sidebar  (^⇧⌘B) does function correctly when the Notes list is also showing, but when the Notes list is hidden the shortcut to show/hide the sidebar does not work.

**Comment by peavine** [comment]
The default keyboard shortcut doesn't work for me either when the Notes List is closed. A temporary workaround is to:

* Use the "Hide/show sidebar" menu item from the top menu bar.

* Assign a different keyboard shortcut using System Preferences (I tested the F9 key and it worked fine).

**Comment by glushchenko** [comment]
Please checkout FSNotes 2.8.0

**Comment by peavine** [comment]
Works great here with 2.8.0.
