### ISSUE TITLE
Navigate between note editor and search field

### ISSUE THREAD

**Issue by andreasnymark** [glushchenko/fsnotes#48]
Using the tab key after a search now focus on the note editor. I’d like to suggest using shift + tab – while in the note editor – to focus on the search field again.

**Comment by glushchenko** [comment]
Hello, @andreasnymark. Tab/shift + tab planned for indentation selected text. Try to use cmd+L instead.

**Comment by andreasnymark** [comment]
Hi @glushchenko. First off, great work with FSNotes. 

Since the tab key is commonly used to shift focus, I have a tendency to shift + tab trying to go back to search field. Indent/un-indent feels more in the line of a code editor, as opposed to a note editor. Just my two cents. Keep up the good work!
