### ISSUE TITLE
Copy Link from contextual menu doesn't work

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#480]
Using the _Copy Link_ contextual menu command doesn't copy the link. The clipboard contents are not changed.

<img width="561" alt="screen shot 2019-02-01 at 16 14 21" src="https://user-images.githubusercontent.com/6884276/52152652-be0e1d00-263c-11e9-85ca-1b18aba7be7f.png">

**Comment by glushchenko** [comment]
Please checkout FSNotes 2.8.0
