### ISSUE TITLE
Roadmap FSNotes v3

### ISSUE THREAD

**Issue by glushchenko** [glushchenko/fsnotes#481]
(please add issue number reference for each item)

Most important requests here:

1) Encryption
2) New icon
3) ...

**Comment by peavine** [comment]
My number-one request is back and forward navigation (issue # 335) including top-menu entries so that I can redefine the keyboard shortcut in System Preferences.

**Comment by gingerbeardman** [comment]
1. Locatisation check
2. Minor interface tweaks

I'll try to do both of these.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/issues/207

**Comment by gingerbeardman** [comment]
@glushchenko with encryption could we support finger print sensor on last MacBooks?

**Comment by jakemkc** [comment]
perhaps one-level nesting of folder, just as what implemented in the app "things"? (see attached)

Previously there was a discussion about nested folder. I think fsnotes fits to the light weight / agile app category and I agree unlimited nesting is not a good idea.

<img width="220" alt="screen shot 3" src="https://user-images.githubusercontent.com/18485734/52280819-ba271700-292a-11e9-84fa-d1ed799c18a7.png">
<img width="212" alt="screen shot 4" src="https://user-images.githubusercontent.com/18485734/52280837-c317e880-292a-11e9-9e8c-37dec2605c13.png">

**Comment by gingerbeardman** [comment]
@jakemkc which app is the screen grab from?

**Comment by gingerbeardman** [comment]
1. Import by drag and drop

https://github.com/glushchenko/fsnotes/issues/221

**Comment by gingerbeardman** [comment]
1. Improvement to tag setting/display/handling

I just finished going through my open issues and that is all from me.

**Comment by quinncomendant** [comment]
1. API for plugin/extensions support

To run arbitrary functions on note content/cursor context, e.g., text transformation, for sending text content to external API. Rather than build your own plugins API, perhaps FSNotes can adopt an existing plugins ecosystem (VIM, Visual Studio Code, Atom, Sublime Text, etc).

**Comment by gingerbeardman** [comment]
>1. API for plugin/extensions support ...

@quinncomendant kind of related is an old issue for AppleScript support. But I don’t mind whatever mechanism is used.

**Comment by quinncomendant** [comment]
2. Non-contiguous selections, rectangular selections, multiple cursors.

**Comment by rogeriomarques** [comment]
Support for mermeid charts in markdown: https://github.com/knsv/mermaid

**Comment by gingerbeardman** [comment]
I think new requests should have a related issue created?

@rogeriomarques 
@quinncomendant 
@jakemkc 

I'll do the same for mine.

**Comment by quinncomendant** [comment]
@gingerbeardman, did you add a reference to #378 in my comment suggesting a plugin API? That issue doesn't seem related.

**Comment by quinncomendant** [comment]
3. Context-aware word autocomplete - #499.

**Comment by gingerbeardman** [comment]
> @gingerbeardman, did you add a reference to #378 in my comment suggesting a plugin API? That issue doesn't seem related.

Sorry, typo! Fixed. Thanks for the headsup.

**Comment by lukaskawerau** [comment]
Autocomplete support for Wikilinks

#512

**Comment by sullevy** [comment]
* In App, drag a note to edit area with [[note name]] syntax.
* when drag one note out of fsnote, like to iThoughts, insert the note url just similarity of Devonthink.
* support #tags, when type #, then popmenu to show all #tags, and hold option key to be clickable.
* support to change previewer theme
* when search a keyword, the scrollbar could show the location like Chrome.
