### ISSUE TITLE
Main window minimum width < 700px

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#482]
I normally keep FSNotes in the right-third of my MBP 13" screen, [at a width of 560px](https://i.imgur.com/nR30VUl.png). FSNotes 2.8 seems to have changed, now[ I can't resize the window smaller than 700px](https://i.imgur.com/lQtfO1R.png). 😭

**Comment by gingerbeardman** [comment]
@quinncomendant I also keep mine on the right third, using Magnet app to control my window placements.
