### ISSUE TITLE
[Review request] MathJax support?

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#485]
Related review

> xavierg78 🇬🇧 
> **Constantly improving, has now become a great nvALT alternative**
> - The app is now a lot more stable and smooth, great work!
> - Love the possibility to add/manage several notes directories/drives (which nvATL did not have)
> - Lack the ability to change background color (was a nvALT plus)
> - Coloring for more programming languages needed
> - Importing color schemes needed (bridge with solarize and open source world)
> - MathJax support needed
> 
> Rating
> ★★★☆☆
> App Version
> 2.3.4

**Comment by gingerbeardman** [comment]
Ref https://stackoverflow.com/questions/35673764/ios-swift-syntax-for-mathjax

**Comment by glushchenko** [comment]
Added in FSNotes v3
