### ISSUE TITLE
[REQ] Option to not show documents section of sidebar

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#488]
I'm trying to move away from sorting things by folder, and just using tags.

So, I'd like to be able to hide the "Documents" section of the sidebar

**Comment by madranet** [comment]
You can drag the vertical divider all the way across to get rid of the sidebar.

![SS 2020-10-17 at 21 08 48](https://user-images.githubusercontent.com/669658/96352704-38a2f880-10bd-11eb-856a-3c8b3a711bbd.png)

**Comment by glushchenko** [comment]
Seems it implemented in FSNotes 5 or early.
