### ISSUE TITLE
[BUG] Setting tags on a note should not overwrite existing tags

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#490]
## I selected some notes
- Alpha
- Beta
- Gamma

I selected all 3 notes and tagged them: 

[swift]

I then selected only the first note, Alpha, and tagged it: 

[howto]

## Expected
- Alpha [swift, howto]
- Beta [swift]
- Gamma [swift]

## Actual
- Alpha [howto]
- Beta [swift]
- Gamma [swift]

I know this is probably "by design" but I think it results in unexpected data (tag) loss.

**Comment by glushchenko** [comment]
Seems like not actual anymore
