### ISSUE TITLE
⌘E for “Use Selection for Find”

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#494]
In all the programs on my computer, _Use Selection for Find_ is mapped to `⌘E`, not `⌘⌥E` as FSNotes currently uses. Can this be changed to `⌘E`?

**Comment by peavine** [comment]
I thought this was an issue with the selected shortcut, but "Use Selection for Find" doesn't work for me with the default shortcut or if the command is selected from the top menu bar?

FSNotes 2.8.2 on Mojave

**Comment by glushchenko** [comment]
Fix available in 2.9.0
