### ISSUE TITLE
[BUG] Pasting images results in various buggy outcomes

### ISSUE THREAD

**Issue by luckman212** [glushchenko/fsnotes#495]
One thing really blocking me from 100% leaving Evernote behind is working with images.

It would be so great to be able to hit ⌘V and have the editor do these things silently behind the scenes:

1.  save the PNG data from the clipboard to a `{guid}.png` file in an `/i` folder at the root level of local (synced) storage
2. create the relative markdown code to link the image in. E.g.
`![](/i/16ac95ce-1edd-483b-86d4-3f728b00d01f.png)`
3. paste this code into the editor at the cursor location

**Comment by glushchenko** [comment]
You can paste image with ⌘-v or drag and drop. Implemented long time ago.

**Comment by luckman212** [comment]
Is there a trick to using it? I can't get ⌘V to work, nothing is pasted.

**Comment by glushchenko** [comment]
Ah, yes, it's working only on iOS at this moment. Will be implemented in next release 🤝

**Comment by glushchenko** [comment]
Fix available in 2.9.0

**Comment by luckman212** [comment]
Thank you very much for this, but I've found this super buggy! Should I open a separate issue for that or just post my report here?

**Comment by gingerbeardman** [comment]
Keep it here for now.

**Comment by luckman212** [comment]
Ok, I have made some screen recordings and collected some good repro steps for 4 bugs. Here we go. (These aPNGs are set to only loop once, so if you need to replay, open them in a new tab and reload)

Bug A: **Images are shrunk to 85% in edit mode**
1. new note
2. type "catA" (return) (return)
3. paste an image e.g size=364x206
4. in edit mode, it is rendered at ==> 310x175
5. toggle between edit/preview to see the size difference

![cata](https://user-images.githubusercontent.com/1992842/52817121-f2d49800-3070-11e9-83ea-869c01a5c4f8.png)

Bug B: **Text justification - all text is left justified, all images are centered** (why?)
1. new note
2. type "catB" (return) (return)
3. paste an image - it's centered (why?)
4. no way to make the image left justified
5. click cursor just to the right of the image
6. hit "return"
7. type "hello kitty" - it's centered (why?)
8. toggle between preview / edit, now the text is somehow at the left again

![catb](https://user-images.githubusercontent.com/1992842/52817249-5232a800-3071-11e9-9896-176212294586.png)

Bug C: **When deleting multiple notes, even after deleting all notes, the editor/preview window displays a "ghost" of the last note if you were in Preview mode at the time of deletion**
1. new note
2. type "catC" (return) (return)
3. paste image
4. new note ... "cat2" ... new note, "cat3" etc
5. toggle preview mode
6. in note list, select all -> delete
7. you will see the ghost still on the right side, but you can't click on it or get rid of it.

![catc](https://user-images.githubusercontent.com/1992842/52817277-6a0a2c00-3071-11e9-99c0-8a23a53ee268.png)

Bug D: **Disappearing images and other bugginess**
1. new note
2. type "catD" (return) (return)
3. pop up preferences window
4. click "Editor" section
5. turn OFF "Live images preview"
6. now, paste the image
7. image appears anyway! (it should be code instead)
8. toggle into preview mode
9. image disappears now! (why?)
10. toggle back into edit mode
11. image is back (why? -- live preview is still OFF)
11. pop up preferences window again
12. click "Editor" section again
13. turn ON "Live images preview" (even though image is already showing)
14. nothing happens, but now the Prefs window title changed to "FSNotes - Untitled Note" (why?)
15. now, turn OFF Live images preview
16. editor now shows the Markdown code
17. click mouse on line JUST ABOVE the ![](/i...) code
18. watch the img code disappear! (why??)
19. toggle back to preview ... image is gone

![catd](https://user-images.githubusercontent.com/1992842/52817316-827a4680-3071-11e9-9617-e93d08aed436.png)

I also found a bug that I can't reproduce now but if you play around you will hit it. Paste in a lot of images and then use the up/down arrows to move the cursor around them, sometimes the images will just suddenly disappear from the editor completely while doing this.

**Comment by glushchenko** [comment]
> Bug A: Images are shrunk to 85% in edit mode

In edit mode images width defined in prederences. Preview is always 100% width

**Comment by luckman212** [comment]
> In edit mode images width defined in preferences. Preview is always 100% width

Where in prefs is this setting? I don't see anything about that.

**Comment by luckman212** [comment]
Another bug:

1. make new note (note1) in Folder**1**
2. paste image
3. FSNotes creates `/Folder1/i/1.jpg` and links it
4. now, make note (note2) in Folder**2**
5. paste image
6. FSNotes creates /i/1.jpg as well (in `/Folder2/i/...`)
7. now, move note2 into Folder1...
8. _poof_, images are gone

I think it is a bad idea to use such a basic naming scheme (1, 2, 3...). It should use GUID instead, tracked internally to avoid any duplication. That way, when note is moved, image can move with it as well, and keep folder structure correct and all links will still work, no risk of overwriting or collision.

**Comment by glushchenko** [comment]
@luckman212 move between folders not implemented. If you want move note with images you should use .textbundle format at this moment.

**Comment by glushchenko** [comment]
> Where in prefs is this setting? I don't see anything about that.

Preferences -> Editor -> Images width

**Comment by glushchenko** [comment]
In summary: 

A - will not be fixed
B - fixed
C - not reproducable for me
D - fixed
E - fixed

**Comment by glushchenko** [comment]
Please try 2.9.3

**Comment by luckman212** [comment]
I am on **2.9.5 (240)** now - sorry for the delay in testing, and thank you for the fixes—This is quite a lot better!

"Bug C" is definitely still reproducible for me - did you watch the video above and follow those exactly? It definitely still happens for me.

**Comment by glushchenko** [comment]
Bug C fixed I think
