### ISSUE TITLE
Formatting not saved with RTF notes

### ISSUE THREAD

**Issue by formulateca** [glushchenko/fsnotes#50]
FSNotes set to RTF extension (for existing NVAlt note compatibility, preference, etc.). Formatting is not saved with pre-existing or new RTF notes. Markdown notes work fine. OS X 10.13.

Upon further testing it appears as though underline is saved, but bold and italic are not. Headers, images and links don't work at all (presumably due to not being markdown). Tabs, breaks and spaces all seem to work as expected.

**Comment by glushchenko** [comment]
What version FSNotes you are use?

**Comment by formulateca** [comment]
Version 1.1.5 (45)

K.

**Comment by glushchenko** [comment]
Maybe this is fixed in 1.1.6, please checkout last release.

**Comment by glushchenko** [comment]
Fixed here https://github.com/glushchenko/fsnotes/releases/download/1.1.7/FSNotes.app.zip

**Comment by glushchenko** [comment]
Fixed here https://github.com/glushchenko/fsnotes/releases/download/1.1.6/FSNotes.app.zip
