### ISSUE TITLE
Markdown live preview in .txt files

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#502]
Is there a way to have FSNotes preview the markdown formatting of .txts files while in edit mode, like it does for files with a .md extension? If not, would you consider adding an option to enable markdown rendering for .txt files, as I use FSNotes to edit markdown-formatted notes from other other apps that use the .txt extension? Thanks!

**Comment by gingerbeardman** [comment]
Which apps use the .txt extension?

**Comment by maccius** [comment]
I would appreciate this feature as well.  I keep all of my notes files in *txt, even those using Markdown syntax, to ensure compatibility across programs.  

Replying to @gingerbeardman : nvALT,  Notable, Ulysses, iAWriter, and Byword all do this (or *can* do it), off the top of my head.  Ditto cli clients like Vim.

**Comment by glushchenko** [comment]
I think markdown is a key feature for FSNotes. I not see any problem for add one checkbox in preferences.

**Comment by maccius** [comment]
👍

**Comment by quinncomendant** [comment]
This was an issue for me too when switching to FSNotes. I had 500 .txt files, many of which contained Markdown. I just renamed the .txt files which appeared to contain at least some Markdown (my assumption: Markdown if file contains at least one level two header and list item):

```shell
#!/bin/bash
for f in *.txt; do 
    if grep -q '^##' "$f" && grep -q '^[*-] ' "$f"; then 
        mv -v "$f" "$(basename "$f" .txt).md"; 
    fi; 
done
```

**Comment by mfloreen** [comment]
Newbie question: I see this is marked as done, but assume we need to wait a little longer to see these updates in the Mac App Store version?

**Comment by peavine** [comment]
@mfloreen. The version shown in the app store is 2.9.3, which is one version earlier than the announced current version ( 2.9.4). Gluschenko is good about keeeping the app store version up to date but it's understandable there might be a small delay.

To always have the latest version without delay, it's a good idea to install the one contained here on Github. However, right now it appears that the version available on Github may be  2.9.3 (see issue #507).

**Comment by glushchenko** [comment]
FSNotes 2.9.5 uploaded in Mac App Store and awaited review.

**Comment by mfloreen** [comment]
@gluschenko @peavine Thank you!

**Comment by glushchenko** [comment]
Approved
