### ISSUE TITLE
A menu bar icon for quickly accessing notes?

### ISSUE THREAD

**Issue by woaidangyang** [glushchenko/fsnotes#503]
I like this feature of nvALT and hope Fsnotes can adopt it.
Thanks!

**Comment by gingerbeardman** [comment]
You can use [BitBar](https://github.com/matryer/bitbar/releases/tag/v1.9.2) with the following all script plugin

```
#!/bin/bash
# <bitbar.title>Open FSNotes</bitbar.title>
echo "📝" 
echo "---"
echo "Open FSNotes| terminal=false bash=/usr/bin/open param1=fsnotes://"
```

**Comment by woaidangyang** [comment]
Thanks! It would be nice if the icon has a few more functions, such as adding quick notes and listing the notes in the library.

**Comment by gingerbeardman** [comment]
You should be able to add to it quite easily, check the wiki for the URL Scheme @woaidangyang

**Comment by woaidangyang** [comment]
Thanks! It's fine. I'll use the dock.

**Comment by glushchenko** [comment]
Menu bar added in 2.9.5

**Comment by woaidangyang** [comment]
So cool! Thank you very much!
