### ISSUE TITLE
FSNotes_2.9.4.zip is actually FSNotes-2.9.3_238.zip

### ISSUE THREAD

**Issue by tjluoma** [glushchenko/fsnotes#507]
I downloaded https://github.com/glushchenko/fsnotes/releases/download/2.9.4/FSNotes_2.9.4.zip linked from https://github.com/glushchenko/fsnotes/releases but it actually shows this version information when installed:

/Applications/FSNotes.app:
	CFBundleShortVersionString: 2.9.3
	CFBundleVersion: 238

**Comment by glushchenko** [comment]
Sorry, 2.9.5 released.
