### ISSUE TITLE
Text cursor keeps jumping to the end

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#51]
I haven't worked out exactly why or when, but when I am editing a note, the text cursor keeps jumping to the end of the document—it happens every 2 or 3 keystrokes. Incredibly annoying!

My best theory is that it's to do with the code that moves the most recently-edited note to the top of the notes list... or perhaps the autosave or something?

Seeing this in MAS version 1.1.5 and 1.1.6

Is anyone else experiencing this?

**Comment by jeff-h** [comment]
I've narrowed it down to [commit #c3fce1465d1e18677cdca4e2a5ea346885eda940](https://github.com/glushchenko/fsnotes/commit/c3fce1465d1e18677cdca4e2a5ea346885eda940)

**Comment by glushchenko** [comment]
Hi @jeff-h, cursor jumping was fixed in 1.1.6 https://github.com/glushchenko/fsnotes/commit/2f7155409843249c20ec0b67c02497bce5d9818b

How to reproduce bug?

**Comment by jeff-h** [comment]
I have worked out the cause, but not the fix. The error occurs because I have made my notes folder a git repository, which for some reason FSNotes dislikes.

When built and run inside Xcode, the console spits out `The file “index.lock” couldn’t be opened because there is no such file.` every time the error occurs, and when I removed the git stuff from my folder (making it no longer a repository) the problem went away.

Git only creates an `index.lock` inside the `.git` folder, so is it possible that FSwatcher is watching files inside subfolders, not just in the notes directory root?

I actually liked having my notes backed up as a git repo, and it is pretty easy to reproduce this error so I'd be intrigued at your thoughts on it (though I understand it's definitely an edge case).

**Comment by jeff-h** [comment]
I have confirmed my guess is correct — FSwatcher is triggering on changes not just on files in the notes directory root but also inside its subfolders, and when this happens, FSNotes can't find the file to load and exhibits the error I've been talking about.

You can try this out without doing anything with git.

* edit an existing note, paying attention to where you left the text cursor
* create a new folder inside your notes folder.
* copy a note into that folder
* the text cursor position will now be at the end of the note you were editing

For even more weirdness;

* create subfolders inside the new subfolder; these now show up as notes in FSNotes, with the same name as the folder you created. 

eg if you have this directory structure: `~/Documents/my-notes/my-new-folder/` and inside that add a folder called `then-create-this-folder` (so the directory structure is `~/Documents/my-notes/my-new-folder/then-create-this-folder`) FSnotes will display a note in the notes list with the title `then-create-this-folder`.

**Comment by glushchenko** [comment]
Thanks for the clarifications, i reproduced bug. I'll try to fix it today.

**Comment by glushchenko** [comment]
Fixed here https://github.com/glushchenko/fsnotes/releases/tag/1.1.7

**Comment by jeff-h** [comment]
Brilliant! Thanks for such a quick fix — works perfectly 👍

**Comment by gglanzani** [comment]
Hi @glushchenko I am getting the same behavior with the latest (2.7.0) fsnotes on iOS.

Have other users reported it?
