### ISSUE TITLE
Don't create a new note when clicking in the "body" area

### ISSUE THREAD

**Issue by luckman212** [glushchenko/fsnotes#510]
Not sure if this is a new feature in recent builds or I'm just noticing it now but:

I am constantly accidentally creating empty notes now, by just clicking on the empty area highlighted below... I prefer to specifically hit ⌘N to make a new note. Hopefully a setting can be added to toggle this off.

![animated](https://user-images.githubusercontent.com/1992842/53268932-787dc680-36b5-11e9-9ad3-f98e764f163c.png)

related issue: #511

**Comment by glushchenko** [comment]
Fixed in FSNotes v3
