### ISSUE TITLE
Prefer that the search field is ONLY search (not create new note if nothing found)

### ISSUE THREAD

**Issue by luckman212** [glushchenko/fsnotes#511]
I would much prefer to only create new notes by explicitly pressing ⌘N ... (related to #510)

A setting to change the search box from "Search of create" to just "Search" would be excellent.

👎![image](https://user-images.githubusercontent.com/1992842/53269067-e1653e80-36b5-11e9-8b30-33e7a6f85eaf.png)

👍![image](https://user-images.githubusercontent.com/1992842/53269052-d3afb900-36b5-11e9-98cc-cfc0bc998974.png)

**Comment by possibleworlds** [comment]
Select "Note auto selection when body text matched" in the User Interface pref pane. I reckon that will fix both this issue and #510. 

With this set up, search selects top hit as you filter, and pressing enter then changes focus to the body of the selected note. Then the only way to create a note from search (or body area click) is to have filtered to an empty list or to have manually deselected in the list, which is why this type of interface is so good.

**Comment by luckman212** [comment]
@possibleworlds Thanks, but I already had that option enabled. No, this doesn't solve it for me. I strongly feel there should still be an option to not create new notes when clicking the empty space or hitting [Enter] on non-existent search terms.

**Comment by possibleworlds** [comment]
Fair enough @luckman212. I'm not going to speak on behalf of the dev, but since this was conceived as a Notational Velocity / NVAlt replacement search as primary interface is one of the foundational concepts behind the app and why people use it. Something like IAWriter functions exactly as you want, maybe that is a better option. Re #510 there is a new note icon and mouseover event in the empty body field telling you clicking there will create a new note... there is no reason to click there other than to create a new note, so I still don't really see how this is an issue. Just trying to be realistic about expectations of the dev.

**Comment by maccius** [comment]
I agree w/ @possibleworlds that this usage pattern is fundamental to the design of the app, and should stay.  It's well defined in precursor apps like nvALT and Notational Velocity.  Creation of a new note doesn't occur automatically, but must be explicitly triggered through either a key press or mouse click.  The speed and convenience of this process is an attractive feature.

**Comment by possibleworlds** [comment]
@maccius just in reference to initial issue, @luckman212 is asking for a user preference to disable search and create and not removal of the functionality altogether (I missed this initially as well). I guess if you were working in empty folders a lot the workflow we describe doesn't work.

**Comment by luckman212** [comment]
I understand what you guys are saying. I'm not asking for the feature be removed, merely an option added to disable it. This would satisty both nvALT users as well as new users who might not want it.

**Comment by luckman212** [comment]
@glushchenko Would a pull request be welcomed if I create this feature myself? Or is that not accepted?

**Comment by gingerbeardman** [comment]
> @glushchenko Would a pull request be welcomed if I create this feature myself? Or is that not accepted?

I would think it would be accepted, the reasons in this issue would convince at least me :)

**Comment by glushchenko** [comment]
Sure, no any problem with pull request acceptance :)

**Comment by peavine** [comment]
I use the search or create bar exclusively to create new notes and the search function occasionally interferes with this use. I wondered if the proposed preference setting could include an option to disable the search function--perhaps a drop-down list with the following options:

Search or create
Search only
Create only

This would be awesome useful for me and might not involve all that much addition work. Thanks.

**Comment by luckman212** [comment]
Are you saying you'd want that drop down to be at the right-hand side of the search field itself, or within the preferences dialog? Not quite sure I understand how you would use the "create only" mode, can you elaborate a bit on it?

**Comment by peavine** [comment]
I have no experience at interface design but with that understood I'll explain how I would do this.

In the FS Notes preference dialog in the "User interface" or "Advanced" tab, I would create a drop-down list (like the drop-down list for "Default file extension" in the General tab). The heading would be "Search or Create Operation" (or something similar) and the options in the drop-down list would include:

Search or Create
Search Only
Create Only

When the create-only option is enabled, I would type the name of the desired note in the create bar and hit the Enter key, which would make a new note with the specified name in the current folder. There would be no search, which slows and interferes with the creation of a new note.

There are other ways to create new notes in FSNotes but none of them is as convenient as the above IMO.

**Comment by luckman212** [comment]
And what if there is already a note with the identical name? It should add a "-1, -2, ... " etc?

**Comment by peavine** [comment]
I'm not certain of the answer but the following alternatives come to mind:

1) FSNotes notifies the user that a note with that name exists. In this instance, the only option would be to select Enter, which cancels the operation.

2) FSNotes automatically appends an integer or date stamp to the note name without prompting the user.

3) FSNotes prompts the user that the note name is already in use and the user can select to overwrite the existing note, keep both notes, or cancel.

Of the above, I think my preference would be the second one but I'd be OK with any of them.

Thanks.

**Comment by gingerbeardman** [comment]
It's annoying that you have to come up with a note title that has no matches before you can create a note from the search field.

How about Cmd+Enter (or whatever) on the search field creates a note of that title regardless of matching?
