### ISSUE TITLE
[REQ] Autocomplete of Wikilinks

### ISSUE THREAD

**Issue by lukaskawerau** [glushchenko/fsnotes#512]
It would be great if `[[Wikilinks]]` to other notes would allow autocomplete when entering them.

**Comment by glushchenko** [comment]
Added in 4.1.1 / Fn-F5 shortcut or drag and drop.

**Comment by JimmyLv** [comment]
@glushchenko You are amazing!!! I am just wondering whether you will add this but you already did it. hahaha, downloading...

**Comment by JimmyLv** [comment]
@glushchenko But it doesn't seem to be what I want, can we start searching by typing words after `[[`?

![image](https://user-images.githubusercontent.com/4997466/79473552-df87d880-8037-11ea-9e89-598e87437594.png)

**Comment by JimmyLv** [comment]
Sorry, just ignore me, I can type the words firstly then use the shortcuts to auto-complete the whole WikiLinks. :D

**Comment by JimmyLv** [comment]
@glushchenko could you please provide an option to update `Fn-F5`  shortcut?

**Comment by glushchenko** [comment]
No problem, will be added in menubar in next release.

**Comment by JimmyLv** [comment]
You are awesome, my best open source project owner! 😂

**Comment by thomaslissajoux** [comment]
I've got a problem with autocompletion
When I open the brackets I can see a large list of Notes to autoco;plete from
![Screenshot 2020-06-15 at 11 53 33](https://user-images.githubusercontent.com/1734825/84652125-69a2cf00-af0b-11ea-8f43-9ff93a37d914.jpg)
So say I want to link to a note starting with "C"
but then I **cannot** see most of them
![Screenshot 2020-06-15 at 13 21 02](https://user-images.githubusercontent.com/1734825/84652238-9a830400-af0b-11ea-9018-47705fc2ae5b.jpg)
It seems like it's only autocompleting amongst **Uppercase** !

Is there anything I'm missing or any way to fix that on my side ?
