### ISSUE TITLE
[REQ] Full Wikilink Syntax support

### ISSUE THREAD

**Issue by lukaskawerau** [glushchenko/fsnotes#514]
Wikilinks currently work in the basic syntax of `[[Name of Note]]`.  
This means they are always rendered with that name inside of text. Full support would mean that one could write `[[Description|Name of Note]]`.

**Comment by gingerbeardman** [comment]
This is not valid markdown, which is what FSN uses, but I wonder if it would be compatible.

**Comment by lukaskawerau** [comment]
Wikilinks are not included in the base Markdown spec and also not included in CommonMark. As far as I'm aware, Brett introduced them as a nvAlt-specific feature.  
And since it's already not standard markdown, I thought it would be great to add this.

**Comment by gingerbeardman** [comment]
Ah, I did not know they were in nvALT. Good suggestion

**Comment by wwtex** [comment]
> Full support would mean that one could write `[[Description|Name of Note]]`.

This is a good idea, but I believe the correct syntax is the other way around:
`[[Note|Label]]`

 https://en.wikipedia.org/wiki/Hyperlink#Wikis

**Comment by jeanm** [comment]
That’s a bit annoying though, because standard markdown links behave the other way around:
```
[description](target)
[[target|description]]
```
