### ISSUE TITLE
Note title and body preview are not aligned

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#515]
The title is a couple of pixels too far to the right. Not a lot, but looks a bit messy. Screenshot:

![screen shot 2019-02-26 at 16 09 23](https://user-images.githubusercontent.com/370930/53455909-0c66cf80-39e1-11e9-89e2-1b083f060a6d.png)

**Comment by glushchenko** [comment]
Fixed in 3.0
