### ISSUE TITLE
Customize the behavior of clicking the menu bar icon

### ISSUE THREAD

**Issue by woaidangyang** [glushchenko/fsnotes#517]
The new menu bar icon is great! Thank you!

But would it be more convenient if we can customize the behaviors after clicking it? For example, open the fsnotes main window immediately after left click and pop up the menu after right click.

**Comment by peavine** [comment]
I wondered how this feature works. I looked at FSNotes preferences and couldn't see any way to customize the behavior of the menu bar icon.

FSNotes 3.0.0 (244)
