### ISSUE TITLE
Cannot specify notes folder

### ISSUE THREAD

**Issue by RickCogley** [glushchenko/fsnotes#52]
Hello - I hope this is the right place to ask for help. A few days ago I bought FSNotes on the app store, and it has been working fine. 

Today I did a Cocktail run, which clears caches and so on, then when I rebooted, FSNotes would not start. I tried restarting FSNotes several times but, nothing. 

So I uninstalled and reinstalled FSNotes, after which, I can start FSNotes, but, I cannot specify the Notes folder I'd like, in its Preferences. When I select ``~/Dropbox/Notes``, the textbox where the path goes is blank. Probably needless to say, in that state, when I look at the UI, it simply shows the test note and nothing else. 

Please advise how I might troubleshoot? 

Sincerely,
RIck Cogley 

macOS High Sierra: 10.13
FSNotes: Version 1.1.6 (47)
Cocktail High Sierra edition: 11.0.1

**Comment by glushchenko** [comment]
Hi @RickCogley, at first thank you for feedback.

I think you should try build 1.1.7 https://github.com/glushchenko/fsnotes/releases/download/1.1.7/FSNotes.app.zip (in MAS will be available tomorrow).

And delete ~/Library/Containers/co.fluder.FSNotes/ directory. Then change directory to Dropbox folder.

**Comment by RickCogley** [comment]
Thank you @glushchenko; that worked!
