### ISSUE TITLE
New files not respecting default extension setting

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#521]
Even when I set the default default file type to be .txt, if I enable the "Recognize .txt as markdown" setting, new files are created as .md files instead of .txt

**Comment by glushchenko** [comment]
New files extension should be configured in Preferences -> General -> Default file extension.

**Comment by volt4ire** [comment]
Thanks I realized I had it set to .txt as opposed to "txt" (without the dot). After changing the setting to "txt", however, now when I create new files they have .rtf extensions rather than .txt.
![image](https://user-images.githubusercontent.com/8772017/53881425-ac27ed00-3fe1-11e9-818c-c3fed397da5a.png)

**Comment by volt4ire** [comment]
Thanks I have that preference set to .txt but new files are still created as .md 
![image](https://user-images.githubusercontent.com/8772017/53881761-71728480-3fe2-11e9-9d8d-bc58e45f94a0.png)

**Comment by jakemkc** [comment]
I have the same issue too.

**Comment by glushchenko** [comment]
Fixed in 3.0
