### ISSUE TITLE
Support hidden startup with `open -j /Applications/FSNotes.app`

### ISSUE THREAD

**Issue by wwtex** [glushchenko/fsnotes#522]
I'd like to be able to start FSNotes hidden with the terminal command `open -j "/Applications/FSNotes.app"`. But FSNotes opens with its window displayed anyways.

**Comment by peavine** [comment]
I added FSNotes to the log-in tab of "Users & Groups" of System Preferences and put a check mark in "Hide". After restarting my computer, FSNotes was loaded automatically but it was not hidden. I assume this is the same issue as @wwtex encountered.
