### ISSUE TITLE
Not possible to search if notes list not shown

### ISSUE THREAD

**Issue by williamsmj** [glushchenko/fsnotes#523]
Steps to reproduce:
 - Set Notes List position to "Side" in UI preferences
 - Hide "Notes" using menu or Cmd-Shift-B
 - Hit Cmd-L to enter search bar

Expected behavior: search box and note list reappears and you start typing in it (see nvALT behavior).

Actual behavior: nothing happens.

**Comment by glushchenko** [comment]
Added in FSNotes v3
