### ISSUE TITLE
Support for footnotes ?

### ISSUE THREAD

**Issue by semiopat** [glushchenko/fsnotes#525]
I know there's support for internal link, but the `[[]]`keys don't match the footnote feature (usually `[^x]` and `[^x]:` for the footnote itself). I thought that GFM support that ?

**Comment by lukaskawerau** [comment]
Footnote support is a great feature, would love that!

**Comment by Pusnow** [comment]
Footnotes are already supported in `cmark-gfm`.
However, `cmark-gfm-swift`, which is a swift wrapper for `cmark-gfm`, doesn't enable it by default, and there is no way to enable it.

I've recently issues PR for enabling it (GitHawkApp/cmark-gfm-swift#14).
When it merges, fsnotes supports footnotes without any changes in main source code.
