### ISSUE TITLE
Support for hidden startup (i.e. start minimized to tray icon)

### ISSUE THREAD

**Issue by wwtex** [glushchenko/fsnotes#529]
I'd like to be able to run FSNotes hidden in tray, just as NValt would be. This would allow running FSNotes on system login rather than manually each time.

**Comment by peavine** [comment]
I added FSNotes to the log-in tab of "Users & Groups" of System Preferences and put a check mark in "Hide". After restarting my computer, FSNotes was loaded automatically but it was not hidden. I assume this is the same issue as @wwtex encountered.

**Comment by peavine** [comment]
At least in part, this would appear to be the same issue as #522. Perhaps @wwtex started this issue to request an FSNote preference?

**Comment by glushchenko** [comment]
Added in FSNotes v3
