### ISSUE TITLE
When navigating note body, mouse scrolling does not work (but trackpad scrolling does)

### ISSUE THREAD

**Issue by danseely** [glushchenko/fsnotes#53]
Steps:

* select a note in the list that is long enough that the entire note does not fit in the note pane
* place focus in the note pane
* use a trackpad to 2-finger scroll the note body
    * note scrolls
* use a mouse with a scroll wheel to scroll the note body
    * note does not scroll

**Comment by glushchenko** [comment]
It is not possible to reproduce  :-/

**Comment by nirajd** [comment]
Hmm... I have the exact same issue. I'm running macOS 10.12.6.

Mouse scrolling works in the notes list and preview mode, but doesn't work in edit mode. Trackpad works like @danseely

**Comment by danseely** [comment]
I'm on 10.12.6 as well -- @glushchenko are you on 10.13 by chance? If so, do you have access to a machine that's still on 10.12 that you could attempt replication on?

**Comment by glushchenko** [comment]
I tried magic mouse on 10.12, and all work fine. Are you trying with mouse wheel?

**Comment by danseely** [comment]
Ahh, I bet that's it. Yes, I have a mouse with a wheel. I'd guess that macOS treats the scrolling events from a Magic Mouse the same as the events from a trackpad.

**Comment by nirajd** [comment]
Same, I use a mouse with a wheel as well. It seems like both trackpad and mouse send  ScrollWheel event.
![screen shot 2017-11-08 at 9 25 16 am](https://user-images.githubusercontent.com/44583/32554152-ea4b3968-c466-11e7-98b3-6c2319f52a50.png)

**Comment by glushchenko** [comment]
I found a mouse with a wheel and try to reproduce it soon ;)

**Comment by glushchenko** [comment]
Please try new build [1.1.9](https://github.com/glushchenko/fsnotes/releases/tag/1.1.9)

**Comment by nirajd** [comment]
Works! 👍

**Comment by danseely** [comment]
Yep, confirmed, looks good. Thanks @glushchenko !
