### ISSUE TITLE
Name of new note

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#530]
Whenever I creeate a new note in FSNotes 3.0 (242), using either the top menu item or the keyboard shortcut, the name of the note is a date/time stamp. Is this intentional?

**Comment by peavine** [comment]
Fixed in build 248. Thanks.

**Comment by glushchenko** [comment]
@peavine current file name is UUID, but in list it is Untitled Note. I think this is good point for UI, and good for file name collisions prevention. Let me know if you have any suggestions.

**Comment by peavine** [comment]
@glushchenko. What you say makes sense to me, especially since Untitled Note is just a temporary name that the user should change to a permanent name.

I do have two small reservations. FSNotes can have several notes all with the name Untitled Note, which doesn't seem good. Perhaps a number can be appended with multiple untitled notes, as in Untitled Note 1. Also, I sort notes by title, and untitled notes are not sorted as expected.
