### ISSUE TITLE
Each paste should be treated as separate event in undo stack

### ISSUE THREAD

**Issue by afaden** [glushchenko/fsnotes#531]
In FSNotes, a paste command is currently treated the same as if you actually typed the characters, for example:
start with ""
[type "test1 test2 "]
"test1 test2 "
[paste "test3"]
"test1 test2 test3"
[type " test4"]
"test1 test2 test3 test4"
[hit undo]
""

In other editors like TextEdit, each paste action gets treated as a separate event in the undo stack. For example:
start with ""
[type "test1 test2 "]
"test1 test2 "
[paste "test3"]
"test1 test2 test3"
[type " test4"]
"test1 test2 test3 test4"
[undo]
"test1 test2 test3"
[undo]
"test1 test2 "
[undo]
""

Also, in TextEdit when you switch focus to another window and then switch back, anything you type is put into a new separate undo event. For example:
start with ""
[type "test1 test2 "]
"test1 test2 "
[switch to another window then back]
[type "test3"]
"test1 test2 test3"
[undo]
"test1 test2 "
[undo]
""

Whereas the same flow in FSNotes currently works like this:
start with ""
[type "test1 test2 "]
"test1 test2 "
[switch to another window then back]
[type "test3"]
"test1 test2 test3"
[undo]
""

Treating these as separate undo events makes it a lot easier to go back just a little bit to correct a mistake (e.g. pasting a large chunk of text in the wrong place). The way that FSNotes currently handles undo means that you must often manually fix things or go back to the beginning and start over.

**Comment by afaden** [comment]
I just noticed another case where TextEdit creates a separate undo event: when you pause typing for >30 seconds.

**Comment by afaden** [comment]
I also keep running into an issue when pasting at or near the bottom of a document, where it appears as if it pasted the wrong text, and when I try to undo it appears to delete a bunch of text earlier in the document (not just the newly pasted text). But it turns out that what appears on the screen is not really what's happening, since if I trigger it to redraw the window (e.g. by resizing it), the text changes back to what I expected. Unfortunately, I haven't yet figured out a series of steps to reliably reproduce this issue.

**Comment by afaden** [comment]
Thanks, just tried this in v3beta2 and it looks like it's partially fixed. Here's how it behaves now:
start with ""
[type "test1 test2 "]
"test1 test2 "
[paste "test3"]
"test1 test2 test3"
[type " test4"]
"test1 test2 test3 test4"
[undo]
"test1 test2"
[undo]
""

So it seems to still be treating the paste and the subsequent typing as one unit, unlike TextEdit which treats the subsequent typing as separate. Maybe that could be fixed by adding another breakUndoCoalescing after the insertText?

**Comment by glushchenko** [comment]
Fixed

**Comment by glushchenko** [comment]
Please try last build.

**Comment by afaden** [comment]
Works perfectly in v3rc1, thanks so much for following up on this! The behavior around paste and undo seems perfect now.

I'd still like to see FSNotes follow the behavior of TextEdit where there's a separate undo event after you switch to another window/app or wait 30 seconds, but I can open a separate issue for that.
