### ISSUE TITLE
Pasting near bottom of document sometimes results in broken state

### ISSUE THREAD

**Issue by afaden** [glushchenko/fsnotes#533]
Sometimes when I paste text near or at the bottom of a document, it gets into this weird state where the editor pane scrolls up to earlier text, and shows a random part of an earlier line pasted. When I undo, it gets even stranger and shows part of that phantom text disappearing. Resizing the window seems to snap it out of this broken state, and it goes back to rendering the actual text I pasted in, with my cursor in the correct position.

Since this is hard to describe, I tried to reproduce it in a test document, but I wasn't able to reproduce it there so I took a video of my real document where this is happening (I blurred out the other parts of my note).

![fsnotes_paste_bug](https://user-images.githubusercontent.com/3763/54875057-659a0700-4dc5-11e9-86cd-b701e674bf9e.gif)

**Comment by glushchenko** [comment]
Fixed in FSNotes 4
