### ISSUE TITLE
FSNotes >= 2.9.1 does not launch on Sierra 10.12.6

### ISSUE THREAD

**Issue by dnowacki-usgs** [glushchenko/fsnotes#535]
I have a Sierra 10.12.6 machine that worked with releases up to and including 2.9.0. Going past this version to 2.9.1 or above results in an endless icon bounce in the dock. The app never launches and you have to force quit. Reverting to 2.9.0 results in a working app again. Was support for older OSes dropped?

**Comment by glushchenko** [comment]
2.9.1 adds UTI detection, if you have big files in FSNotes dir, icons may bounce long time. Workaround is remove some big files, in 3.0 that fixed.

**Comment by dnowacki-usgs** [comment]
OK, thanks. I tried again and waited longer for 2.9.5 to open. My notes directory is ~62 MB and it takes about 85 seconds for the bouncing to stop. Glad to hear it is fixed in 3.0, I'll give it a try when I have some time to test.
