### ISSUE TITLE
Incorrect Markdown parsing of lists

### ISSUE THREAD

**Issue by jeanm** [glushchenko/fsnotes#536]
I've noticed the following snippet of markdown will be parsed incorrectly when hitting preview mode <kbd>⌘</kbd>+<kbd>`</kbd>:

```
* > This is a quote
  
    <https://reference.link>
```

What I would expect to see:

* > This is a quote
  
    <https://reference.link>

---

What I actually see:

> * This is a quote
  
<https://reference.link>

---

So, two problems:
1. The block quote should be inside the list (instead it's shown as the other way around)
2. The link should be inside the list element (instead it's shown in a separate paragraph)

I am using 2.9.5 from the App Store.

**Comment by glushchenko** [comment]
Please report here:

https://github.com/iwasrobbed/Down
