### ISSUE TITLE
FSNotes keeps asking for default storage directory and won't accept any option

### ISSUE THREAD

**Issue by campbellcj11** [glushchenko/fsnotes#537]
I opened FSNotes after restarting my computer and it keeps asking for the default storage directory. I continue to select my FSNotes folder which contains my notes, however if just keeps popping back up. I also tried to change it via preferences.

**Comment by glushchenko** [comment]
Sorry I don't know how to reproduce it.

**Comment by gingerbeardman** [comment]
I would say remove fully, reboot, reinstall.
