### ISSUE TITLE
List bullet color issue

### ISSUE THREAD

**Issue by chaonan99** [glushchenko/fsnotes#538]
FsNotes Version 3.0.0
MAC version 10.14.3 (18D109)

The color of the bullet in list of items is normally gray. But if pasting after some non-list text, the bullet colors are black except the first one:
```
Try
* Something
* Something else
* Something else
```
Cut list items
```
Try
```
Paste back
```
Try
* Something
* Something else
* Something else
```
The bullet points before "Something else" will be black.

If paste together with non-list text, all bullet colors will be black:
```
Try
* Something
* Something else
* Something else
```
Cut all
```
```
Paste back
```
Try
* Something
* Something else
* Something else
```
All bullet points will be black.

If I type something after a list item, the bullet color of that single line will change to gray, but not others.

**Comment by glushchenko** [comment]
Please try last build.

**Comment by chaonan99** [comment]
With the [latest release](https://github.com/glushchenko/fsnotes/releases/tag/v3rc1) the issue is still there...

**Comment by chaonan99** [comment]
And also the note title is not showing on the list, instead the first heading is there. Is this the intended behavior?

**Comment by glushchenko** [comment]
Fixed, thank you. 

> And also the note title is not showing on the list, instead the first heading is there. Is this the intended behavior?

This is new settings. Preferences -> UI -> First line as title, now enabled by default.

**Comment by glushchenko** [comment]
Please re-download rc1

**Comment by chaonan99** [comment]
It works. Thanks!
