### ISSUE TITLE
Specific markdown text services throw error

### ISSUE THREAD

**Issue by jurb** [glushchenko/fsnotes#539]
Hi! I love Brett Terpstra's [Markdown Services](https://brettterpstra.com/projects/markdown-service-tools/) and [Searchlink](https://brettterpstra.com/projects/searchlink/). They work in most text fields, but not in fsnotes unfortunately. The error just points to the offending workflow, so I can't really debug it.

![Screenshot 2019-04-03 at 16 35 38](https://user-images.githubusercontent.com/913411/55487783-1064bd80-562f-11e9-8fbb-c9059a2f0a6e.png)

I tested this with 'numbered list', Searchlink, 'make code block', and a few others. Any idea what's up?

**Comment by gingerbeardman** [comment]
OK, sorry for the delay here.

You can Show Workflow, then right click it and Open With... Automator. This should also be the default double click action on the workflow.

@glushchenko any idea why FSNotes does not provide its text to such services? Is it because it's not a standard text field?

**Comment by spencerclrk** [comment]
Same issue here.

**Comment by glushchenko** [comment]
Thanks for bug reports. Bug fixed.
