### ISSUE TITLE
can't un-style text

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#54]
In RTF mode, I can apply bold and italics using the usual keyboard shortcuts or the format menu, but once applied, I can't un-apply the style. eg highlighting a word and pressing ⌘B bolds it, but if you then do another ⌘B it the bold doesn't turn off.

Thanks again for your ongoing great work on FSNotes!

**Comment by glushchenko** [comment]
I don't have this behaviour https://dsh.re/c8f9f

**Comment by jeff-h** [comment]
Wow, that's weird! If nobody else has this issue either then it must be due to something I've done somehow. It does happen both in my Xcode builds and in every MAS version I've used. I'll dig into the code at some point and hopefully find the culprit :)
