### ISSUE TITLE
Crash when opening the "boostnote cheat sheet"

### ISSUE THREAD

**Issue by Crembo** [glushchenko/fsnotes#540]
Latest Mac app (v2.9.5) crashes when opening the boostnote cheat sheet, available here:
https://raw.githubusercontent.com/TobseF/boostnote-markdown-cheatsheet/master/BOOSTNOTE_MARKDOWN_CHEAT_SHEET.md

**Comment by glushchenko** [comment]
Please try last build.

**Comment by Crembo** [comment]
Looking good. Thanks!
