### ISSUE TITLE
TODO list space inconsistent

### ISSUE THREAD

**Issue by chaonan99** [glushchenko/fsnotes#541]
FsNotes Version 3.0.0
MAC version 10.14.3 (18D109)

Reproduce:
1. Create a new note
2. Enter `- [ ]Item`
3. Click on the square bracket (would view as a TODO item)
4. Navigate to another note
5. Move back to the newly created note again

Problem: The space before `Item` become smaller. If I type something in the same line, this space become bigger again. This can be more obvious if you have several TODO items in a note.

**Comment by glushchenko** [comment]
I think fixed long time ago. Just use ⌘ + t for checkboxes.
