### ISSUE TITLE
Copy URL of current doc Keyboard Shortcut

### ISSUE THREAD

**Issue by csi-lk** [glushchenko/fsnotes#542]
At the moment you can copy URL from the File menu 

Proposal is to add a keyboard shortcut to trigger this action, I can't find any good prior art of what this shortcut should be, maybe:

* CMD+U (simple, not used?)
* CMD+Option+C (in line with current 'copy title' shortcut of CTRL+OPT+CMD+C)

<img width="203" alt="image" src="https://user-images.githubusercontent.com/2224266/55703646-cd706480-59f7-11e9-8e06-c186131076de.png">

**Comment by gingerbeardman** [comment]
You can assign your own using: System Preferences > Keyboard > Shortcuts

I'm not a fan of having keyboard shortcuts for every menu item, but at the same time all of the others have one so I guess why not.

**Comment by csi-lk** [comment]
Awesome thanks @gingerbeardman, didn't know I could do that, works well

<img width="403" alt="image" src="https://user-images.githubusercontent.com/2224266/55722777-cf045180-5a24-11e9-9423-0a2e1fd5c325.png">
