### ISSUE TITLE
unable to scroll via thumb/trough while in preview mode

### ISSUE THREAD

**Issue by tarogers** [glushchenko/fsnotes#545]
Version 3.0.0 (246) - Running MacOS 10.14.3

While a document is in preview mode, the scrollbar can not be interacted with when using the mouse to drag the scroll-thumb or to click in the scrollbar trough.  This works correctly while in edit mode. Using mouse scroll-wheel, trackpad gestures or page-down keys to scroll works as expected in both modes.

(I use a Wacom pen as my mouse, so grabbing the thumb or clicking the trough are the only options available for my preferred input device)

**Comment by glushchenko** [comment]
Please try last build
