### ISSUE TITLE
New notes don't appear in list, and no keyboard shortcuts working.

### ISSUE THREAD

**Issue by sibob** [glushchenko/fsnotes#547]
v.3.0.0 (246) on 10.14.4
New notes, created when typing into the search box and hitting return don't appear in list view until a restart.

Also no keyboard shortcuts are working for me e.g. CMD+DELETE. Just me?

Thanks

**Comment by glushchenko** [comment]
Yes it's only for you

**Comment by gingerbeardman** [comment]
@sibob try rebooting your Mac.

**Comment by sibob** [comment]
Thanks. I solved both issues by trashing the app and all support files. Something had gotten corrupted over time.
