### ISSUE TITLE
Attachment of picture and pdf

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#548]
Hi,

I am using Fsnotes 2.9.5 (240) on MacOS 10.14.4. I have 2 questions related to putting attachment to notes.

1) After I created a new note and pasted a *.png file in the note, I can see the note file was created in the storage location through Finder, and also an "i" folder with the renamed *.png in it.

However, if I delete the note, only the corresponding *.md file was deleted in the storage location. The associated image in the "i" folder is still there. Is there a setting I can adjust to delete them at the same time? Over time the "i" folder could be full of junk and it's hard to manually clean it.

2) If I repeat the same as what I did in #1 but attaching a *.pdf instead, I can see the 1st page pdf preview in the "note" view of that note (i.e. the middle column) and the *.pdf being renamed and copied into the "i" folder, but I don't see anything in the note corresponding to the pdf (i.e. the right column). May I ask is pdf attachment supported?

Thanks!
Jake

**Comment by BeWe11** [comment]
Concerning your first point, you might want to try out the textbundle container option (only available in fsnotes v3, see [the releases](https://github.com/glushchenko/fsnotes/releases)). Using textbundles, the attachments are stored together with the note inside a container, instead of being stores in the "i" folder. Deleting a note then deletes the whole container.

**Comment by jakemkc** [comment]
It looks like spotlight can't see the text inside *.textbundle.

Is there a way to make it searchable?

**Comment by gingerbeardman** [comment]
@jakemkc use this QuickLook plugin https://github.com/ttscoff/MMD-QuickLook

**Comment by jakemkc** [comment]
@gingerbeardman thanks for the link. Tried that but apparently it's not working anymore (at least in Mojave. quicklook can't see its content, spotlight can't search bundle content).

Perhaps I should stick with the "i" folder way.

**Comment by glushchenko** [comment]
I think this fixed long time ago
