### ISSUE TITLE
Todo list view disappears

### ISSUE THREAD

**Issue by dnowacki-usgs** [glushchenko/fsnotes#549]
I have a note with todo checkboxes. In Preview mode, they show up:
<img width="95" alt="Screen Shot 2019-04-17 at 10 31 19" src="https://user-images.githubusercontent.com/13837821/56308345-f7164380-60fb-11e9-8514-6d2d05df744a.png">
but they do not show up in edit mode. Each line should show a `- [ ]` at the beginning that you could X out, but now they are missing:
<img width="105" alt="Screen Shot 2019-04-17 at 10 32 16" src="https://user-images.githubusercontent.com/13837821/56308393-18772f80-60fc-11e9-944b-25d1641340db.png">
But if you open the .md file in an external editor (e.g. BBEdit) you can see the `- [ ]`:
<img width="162" alt="Screen Shot 2019-04-17 at 10 33 03" src="https://user-images.githubusercontent.com/13837821/56308450-3349a400-60fc-11e9-980e-e7e18c042861.png">
Also, I think in preview mode you used to be able to check the boxes and they would update, but that doesn't work any more. Clicking the boxes does nothing. This is on 3.0rc1, but it happened on 2.9.5 as well.

**Comment by glushchenko** [comment]
Please attach note here

**Comment by dnowacki-usgs** [comment]
Had to add a .txt extension for GitHub to allow it. But this is an example file that has the same behavior as the screenshots above. 
[todo_error.md.txt](https://github.com/glushchenko/fsnotes/files/3091396/todo_error.md.txt)

**Comment by glushchenko** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/1089917/56318957-0f707780-6169-11e9-9f57-4c30b63f8b4c.png">

**Comment by glushchenko** [comment]
Works fine for me

**Comment by glushchenko** [comment]
Anyone can reproduce it?

**Comment by peavine** [comment]
I opened the note  from @dnowacki-usgs and viewed it 1) in FSNotes (3.0 RC1) edit mode; 2) in FSNotes preview mode; and 3) in TextEdit. I took screenshots of all three and have included them below in the specified order. I'm not certain how FSNotes is supposed to work with ToDo notes but it seems to work OK to me.

<img width="370" alt="FSNotes in Edit Mode" src="https://user-images.githubusercontent.com/35905279/56328954-36fa1c80-6136-11e9-9bc7-f919489f7e9c.png">
<img width="370" alt="FSNotes in Preview Mode" src="https://user-images.githubusercontent.com/35905279/56328962-3b263a00-6136-11e9-8bcb-ffd9132ac015.png">
<img width="410" alt="FSNotes in TextEdit" src="https://user-images.githubusercontent.com/35905279/56328968-3f525780-6136-11e9-96b1-2cdd0e805213.png">

**Comment by dnowacki-usgs** [comment]
Thanks for your input, everyone. Todo lists **used to** work fine for me, but then stopped working. I can confirm that the same note works OK one one of my machines but not another, so I'm wondering if something got corrupted with my installation. Is there a preferences file or something I can delete?

**Comment by peavine** [comment]
@dnowacki-usgs. When I want to reset FSNotes preferences, I delete the following folder and file. There may be others but if so I don't know about them.

/Users/peavine/Library/Containers/co.fluder.FSNotes/

/Users/bob/Library/Preferences/co.fluder.FSNotes.plist

**Comment by gingerbeardman** [comment]
@dnowacki-usgs you can use [AppCleaner](https://freemacsoft.net/appcleaner/) to remove all traces of an app (but not your notes!)

**Comment by dnowacki-usgs** [comment]
@gingerbeardman thanks. I used AppCleaner to remove the app and did a fresh reinstall. Specified my notes folder and it loaded the notes. But the prefs pane is not respecting the location (it keeps going back to the default location). Any changes I make are only reflected in the default location and not my actual notes folder. Prefs pane is also not respecting the Container choice (I want None, it keeps going back to TextBundle). FYI this is not an admin account. Any other suggestions?

**Comment by jeff-h** [comment]
Perhaps try [Sloth](https://sveinbjorn.org/sloth) to confirm you're removing the correct preference files. Does any change in your prefs take effect, or none? If none, is the prefs file actually even being written?

**Comment by peavine** [comment]
@jeff-h. I had never hear of Sloth but downloaded it to have a look. Very useful.

I looked at the information provided by Sloth for FSNotes 3 and the results are:

/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_stdlib.metallib
/System/Library/Frameworks/CoreImage.framework/Versions/A/Resources/ci_filters.metallib
/private/var/folders/60/8sb76h7j73lf7m2fvt088z1c0000gn/C/co.fluder.FSNotes/co.fluder.FSNotes/com.apple.metal/3902/libraries.maps
/private/var/folders/60/8sb76h7j73lf7m2fvt088z1c0000gn/C/co.fluder.FSNotes/co.fluder.FSNotes/com.apple.metal/3902/libraries.data
/private/var/folders/60/8sb76h7j73lf7m2fvt088z1c0000gn/C/co.fluder.FSNotes/co.fluder.FSNotes/com.apple.metal/Intel(R) UHD Graphics 630/functions.maps
/private/var/folders/60/8sb76h7j73lf7m2fvt088z1c0000gn/C/co.fluder.FSNotes/co.fluder.FSNotes/com.apple.metal/Intel(R) UHD Graphics 630/functions.data
/Users/peavine/Library/Containers/co.fluder.FSNotes/Data/Library/Saved Application State/co.fluder.FSNotes.savedState/data.data
/Users/peavine/Library/Containers/co.fluder.FSNotes/Data/Library/Saved Application State/co.fluder.FSNotes.savedState/windows.plist
/Users/peavine/Library/Containers/co.fluder.FSNotes/Data/Library/Saved Application State/co.fluder.FSNotes.savedState/window_1.data

It looks like all FSNotes preference files are in the folder:

/Users/peavine/Library/Containers/co.fluder.FSNotes

If @dnowacki-usgs deleted this folder directly or indirectly with AppCleaner and still has the issue, I don't know what else to try.

**Comment by gingerbeardman** [comment]
Another good app is [FSMonitor](https://fsmonitor.com), which shows you filesystem events in realtime.

**Comment by dnowacki-usgs** [comment]
Thanks everyone. 

Re default folder, I'm setting the default folder in the Preferences pane (_Default storage_ option). Not sure if it was a restart or the upgrade to 3.0GM but the note location and Container setting seem to be sticking now. 

Re: todo lists disappearing @peavine, @jeff-h: this is the result from Sloth:

/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
/System/Library/Frameworks/CoreImage.framework/ci_kernels.metallib
/private/var/folders/55/1__x335d4_b9pnc1h5mkwggr58_c56/C/co.fluder.FSNotes/co.fluder.FSNotes/com.apple.metal/libraries.maps
/private/var/folders/55/1__x335d4_b9pnc1h5mkwggr58_c56/C/co.fluder.FSNotes/co.fluder.FSNotes/com.apple.metal/libraries.data
/private/var/folders/55/1__x335d4_b9pnc1h5mkwggr58_c56/C/co.fluder.FSNotes/co.fluder.FSNotes/com.apple.metal/AMD Radeon R9 M290X/functions.maps
/private/var/folders/55/1__x335d4_b9pnc1h5mkwggr58_c56/C/co.fluder.FSNotes/co.fluder.FSNotes/com.apple.metal/AMD Radeon R9 M290X/functions.data
/Users/dnowacki/Library/Containers/co.fluder.FSNotes/Data/Library/Caches/co.fluder.FSNotes/Cache.db
/Users/dnowacki/Library/Containers/co.fluder.FSNotes/Data/Library/Saved Application State/co.fluder.FSNotes.savedState/data.data
/Users/dnowacki/Library/Containers/co.fluder.FSNotes/Data/Library/Saved Application State/co.fluder.FSNotes.savedState/windows.plist
/Users/dnowacki/Library/Containers/co.fluder.FSNotes/Data/Library/Saved Application State/co.fluder.FSNotes.savedState/window_1.data

I've deleted the Library/Containers/co.fluder.FSNotes folder multiple times... wondering if it could be the other files. Bad idea to try to delete them? (especially the framework folders?) Finally, I didn't mention earlier that this is on macOS 10.12.6, which is getting a bit long in the tooth now. Another interesting screenshot is that the preview list shows the tick boxes but they don't appear in the editor window:

<img width="358" alt="Screen Shot 2019-04-29 at 10 31 14" src="https://user-images.githubusercontent.com/13837821/56914989-48aebe80-6a6a-11e9-90fe-578534109c83.png">

**Comment by dnowacki-usgs** [comment]
My machine was just upgraded to 10.14 and the issue has disappeared for me, with FSNotes 3.5.0. I never did figure it out when I was still on 10.12. Closing.
