### ISSUE TITLE
Note body not displayed

### ISSUE THREAD

**Issue by JesseAldridge** [glushchenko/fsnotes#55]
I was messing with the preferences and changed the "Search Bar Orientation" to Horizontal then back to Vertical.  The app crashes each time I make a preference change.  And now I can't seem to get the box with the note body to show up.

**Comment by JesseAldridge** [comment]
![screen shot 2017-11-07 at 12 31 30 pm](https://user-images.githubusercontent.com/191903/32516317-c61b28be-c3b7-11e7-9afc-ec7bce40b8a3.png)

**Comment by JesseAldridge** [comment]
Also I am trying this think out because Notational Velocity isn't working.  I imported all ~9K Notational Velocity notes I had.  It was working for a while I think, until I started messing with the preferences.

**Comment by JesseAldridge** [comment]
![screen shot 2017-11-07 at 12 36 22 pm](https://user-images.githubusercontent.com/191903/32516476-535defe0-c3b8-11e7-9c9e-9d41e2631514.png)
![screen shot 2017-11-07 at 12 36 29 pm](https://user-images.githubusercontent.com/191903/32516477-5376a0ee-c3b8-11e7-9339-f68b0a3430cd.png)

**Comment by glushchenko** [comment]
Workaround here: https://dsh.re/a5fe7

**Comment by JesseAldridge** [comment]
Oh, I see, that works.  Thanks for the quick response.

**Comment by jeff-h** [comment]
The auto-quitting thing after changing those prefs is very off-putting, but I suspect it would be a fair bit of work to have the UI re-lay out dynamically in response to the prefs change.

As a solution I'd go so far as to question whether the app even needs the vertical layout — to me it has always seemed kind of silly for a notes app (likewise in nvALT before this). Perhaps we could do a survey to see how many people actually use it?

**Comment by glushchenko** [comment]
@jeff-h, restart for UI, already removed by commit above ;)

**Comment by jeff-h** [comment]
@glushchenko Woah, you're doing a fabulous job on this app!

**Comment by glushchenko** [comment]
Fixed in [1.1.9](https://github.com/glushchenko/fsnotes/releases/tag/1.1.9)
