### ISSUE TITLE
crash/hang beta 3

### ISSUE THREAD

**Issue by reconstructed** [glushchenko/fsnotes#551]
latest mac beta of 3 crashed and now consistent hang and unable to open the application even after reboot

[2019-04-22 18.47.26.txt](https://github.com/glushchenko/fsnotes/files/3104138/2019-04-22.18.47.26.txt)

**Comment by reconstructed** [comment]
same issue now with v2 - last thing i did was click on the trash can in fsnotes. completely hung and hogging CPU fans going nuts. trashed plist. same result. will go for a complete reinstall and report back.

**Comment by glushchenko** [comment]
Try to move files from storage and trash, then run app

**Comment by reconstructed** [comment]
done 
fixed
i guess now = it's just matter of moving each one of the thousands of files back one by one and see if it causes it to hang again? 😳 ps dammit just as i was about to change over permanently from nvALT!

**Comment by glushchenko** [comment]
Move half, try, move half from broken part, try. Attach breaking file here. Will no problem to fix that.

**Comment by reconstructed** [comment]
any ideas about what could break it? a character in the filename? an extension?

**Comment by gingerbeardman** [comment]
Do a binary search, as @glushchenko says, do it half by half, keep dividing by half until you find the culprit :)

https://www.geeksforgeeks.org/binary-search/

**Comment by reconstructed** [comment]
i was lazy and restored all the files to see what would happen and it's been fine. maybe it wasn't a file that cause the problem? i'll keep you posted about any other weirdness. i might even be brave and try the v3 beta again... 😀

**Comment by reconstructed** [comment]
ps @glushchenko @gingerbeardman i am loving this very useful program. been waiting forever for bret terpstra to do something similar as he's been promising for ages... keep up the good work!
