### ISSUE TITLE
BUG Notes list is gone

### ISSUE THREAD

**Issue by spencercook** [glushchenko/fsnotes#558]
The v3 update, automatically downloaded from the mac app store, has killed the app- I can't get the notes list to appear. I've tried restarting and reinstalling. The button in the view menu and the shortcut don't work. I can't make or search for a new note with Cmd+L either. Please advise, I really loved this application.

**Comment by glushchenko** [comment]
macOS version?

**Comment by spencercook** [comment]
Yes. I just installed v3 from git and had the same issues.

**Comment by glushchenko** [comment]
Please remove settings and run in terminal “sudo killall cfprefsd”

**Comment by spencercook** [comment]
Thanks very much, that worked.
