### ISSUE TITLE
About mathjax support

### ISSUE THREAD

**Issue by BeWe11** [glushchenko/fsnotes#560]
I've seen that mathjax support was added in the latest release, but I'm not sure how to use it. I've tried the following brackets:

- `$...$`
- `$$...$$`
- `\(...\)`
- `\\(...\\)`
- `\[...\]`
- `\\[...\\]`

None of these render as math in preview mode. Am I missing something?

**Comment by glushchenko** [comment]
Example from MathJax site works fine for me:

```
When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$
```

**Comment by BeWe11** [comment]
Ok, the `$$...$$` now seems to work, don't know why it didn't before...
However, the other styles still don't. Here is my preview output of the example code that you've posted:

<img width="643" alt="Screen Shot 2019-05-02 at 15 55 30" src="https://user-images.githubusercontent.com/14355528/57080437-d0a6f980-6cf2-11e9-82f6-8e70f4028981.png">

The inline math is not being rendered.

**Comment by glushchenko** [comment]
Foxed in 3.0.2

**Comment by torralbofco** [comment]
The inline mode (with dollars "$") is not working in version 4.10.2. The syntax is `((formula))` which is not LaTeX standard and cause problems when migrating the notes to other apps or to produce a correct pdf file with pandoc. Please, support the standard syntax `$formula$` for inline math.

**Comment by glushchenko** [comment]
@torralbofco, added. Will be available with beta2.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5b2/FSNotes_v5b2.zip
