### ISSUE TITLE
Highlighting of numbers in lists broken

### ISSUE THREAD

**Issue by mikepqr** [glushchenko/fsnotes#561]
Numbers followed by periods (e.g. `1.0`) in lists are highlighted. They shouldn't be.

This is Github rendering (correct)

Test 1
Test 1.0
1
1.0

 - Test 1
 - Test 1.0
 - 1
 - 1.0

This is a screenshot from FSNotes (note `1.`)

![Screen Shot 2019-05-02 at 12 45 22](https://user-images.githubusercontent.com/370930/57102372-35088f80-6cd8-11e9-9788-9c38360669a0.png)

**Comment by glushchenko** [comment]
Seems it fixed long time ago.
