### ISSUE TITLE
Documentation: What is Container - TextBundle?

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#562]
I noticed FSNotes v3 has a new preferences setting for **Container:** `TextBundle` | `None`.  As an end user, why would I choose one format over the other? 

I see selecting *FSNotes Help* from the *Help* menu just opens the github issues page. Are there plans to create a documentation page? Github wiki would be just great.

**Comment by gingerbeardman** [comment]
This should be documented, I agree.

It's a bundle (think of it like a special folder that looks like a single file) that contains plain text and any referenced media. 

Read more http://textbundle.org/

**Comment by quinncomendant** [comment]
Ok, I get the gist. A couple questions:

- Do TextBundle packages persist, or are they only used temporarily when sharing a document with another program?
- If they persist, where are they saved? If I use iCloud Drive for my notes, will TextBundles appear on my other devices?
- TextBundles look awesome. Why would anyone choose *Container: None*?

**Comment by gingerbeardman** [comment]
1. They persist. 
2. Your notes folder. Yes with iCloud they'll appear on all your devices. 
3. If you don't use images/media there's no real need to use textbundles. If you don't have apps that can work with them easily maybe you'd my choose to use textbundles. 

Does that sound right @glushchenko

**Comment by quinncomendant** [comment]
Yep, TextBundles sure do appear on all devices via iCloud. It looks like this:

## The TextBundle folder:
![IMG_3420](https://user-images.githubusercontent.com/6884276/57159781-6783bc80-6dac-11e9-864d-d13a0042686d.jpg)

## The TextBundle folder contents:
![IMG_3421](https://user-images.githubusercontent.com/6884276/57159779-6783bc80-6dac-11e9-975c-a4f0584fa804.jpg)

That's a view from inside *iA Writer*, which doesn't "support" TextBundles (although, of course it can open the `*.textbundle/text.markdown` file inside).

Unless a user *only* uses the [supported apps](http://textbundle.org/) they will want to select the *Container: None* option. If they don't, they'll end up with a bunch of folders instead of regular text files.

Does FSNotes default to *Container: TextBundle* when it is installed? Since this could violate the user's expectations of a "pure" text-file-only workflow (it will create folders instead of files), the default setting should probably be *Container: None*.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/wiki/Containers

**Comment by gingerbeardman** [comment]
@glushchenko  I see that TextBundle is now indeed default, an unannounced changed and something I do not personally want for my notes (now I have to go back through recent notes and figure out how to convert them to plain .md files)

**Comment by sgoumaz** [comment]
It seems that v2.6.0 on iOS also defaults to using TextBundle, even though the 'default extension' setting is still 'md' in my case… that's a bug to me. And then note contents don't show on the MacOS app. (Please split into separate issue if needed.)
