### ISSUE TITLE
Corrupt undo stack

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#563]
For the past couple months (going back to at least version 2.7 , I have occasionally experienced a problem where repeating `Undo` and `Redo` will cause my note contents to get messed up. I tried a couple times to reproduce the problem in a new note and make a screen recording, but then the problem doesn't repeat. It seems to occur more frequently with older notes, and especially notes that have received lots of random edits and Copy/Paste. 

Here's a simulation of how the problem occurs:

1. Example text: a short paragraph, a link, and a list:

		Lorem ipsum dolor sit amet, consetetur sadipscing elitr.
		
		https://en.m.wikipedia.org/wiki/Saccade
		
		- one
		- two
		- three

2. Edit the note for a couple hours, with lots of copy-paste.
3. Use `Undo` several times (going back 5-20 steps).
4. Use `Redo` the same number of steps to return to the final state (as it was above). 
5. The text might now look like this:

		consetetur sadipscing elitr. - one 
		https://en.m.wikipedia.org/wiki/Saccade
	
		- two three.

The problem also manifests in another way: doing many repetitions of `Undo` and `Redo` might result in a state where the text is corrupted, and—what makes this a special case—no more `Undo` or `Redo` is possible. Selecting these commands does not result in any change in the text. The commands are not disabled (greyed-out in the menu bar), so you expect them to do something, but they do not.

Has anyone else experienced this?

I wonder if the problem has some relationship to iCloud document merge causing the document to go out-of-sync with FSNotes’ undo stack?

**Comment by gingerbeardman** [comment]
Do you think this is the same as #408

**Comment by quinncomendant** [comment]
Yes, probably – the behaviour reads the same to me. I couldn't reproduce the specific example mentioned there – at least, not until I copied-and-pasted several more bullet points, added some paragraphs, made some text bold, then did `Undo` to the beginning and `Redo` to the end – backwards and forwards a few times – before it did finally corrupt the text.

**Comment by glushchenko** [comment]
Fixed, please try 3.0.2
