### ISSUE TITLE
FS Notes doesn't respect Fullscreen

### ISSUE THREAD

**Issue by helmut72** [glushchenko/fsnotes#567]
When I exit FS Notes in Fullscreen, it doesn't respect that it was in Fullscreen and opens on my Desktop.

Every other app I use starts in his "last known area", Fullscreen or Desktop.

**Comment by helmut72** [comment]
Still exist in 3.7.1

**Comment by glushchenko** [comment]
Will be available in 3.8.0

**Comment by gingerbeardman** [comment]
I've never used fullscreen with FSNotes and on launching 3.8.0 beta it defaulted to fullscreen? Bug?

**Comment by glushchenko** [comment]
@gingerbeardman nice catch, fixed

**Comment by helmut72** [comment]
Sorry for the late reply, it's fixed for me. Thank you!! :-)
