### ISSUE TITLE
Resizing the "Preferences" window doesn't resize the contents

### ISSUE THREAD

**Issue by philwo** [glushchenko/fsnotes#57]
The Preferences window is resizable, but doing so doesn't seem to actually resize the contents:

<img width="910" alt="screen shot 2017-11-12 at 16 59 45" src="https://user-images.githubusercontent.com/504652/32700837-08ac467e-c7cb-11e7-95de-eed4dac43d4a.png">

Tested with FSNotes Version 1.1.9 (61) on macOS 10.13.1 (17B48).

**Comment by greendog99** [comment]
Submitted PR #60 to fix this by disabling resize of preferences window (like most MacOS apps).
