### ISSUE TITLE
[BUG] Slow operation when pasting markdown with lots of links

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#570]
1. create new note
2. paste in below text
3. wait

**Expected**
This should be faster

**Recommendation**
1. Paste raw text
2. Do delayed markdown processing and highlighting 

**Notes**
- Pasting this text into other editors is either
    1. instantaneous (eg. FoldingText)
    2. very fast (eg. Ulysses)
   3. error prone (eg. Keep It)

**Test Text**
[Link Archive.md.txt](https://github.com/glushchenko/fsnotes/files/3147435/Link.Archive.md.txt)

**Comment by glushchenko** [comment]
Please checkout FSNotes 3.0.4

**Comment by gingerbeardman** [comment]
Excellent, thanks
