### ISSUE TITLE
[BUG] File not refreshed when edited in External editor

### ISSUE THREAD

**Issue by derekvan** [glushchenko/fsnotes#577]
Files edited in external editor aren't refreshed in FS Notes

1. Open FS Notes. Create new file. Add content.
2. "Open External" menu command (I have my external editor set to FoldingText)
3. Edit file in other text editor. Save.
4. Return to FS Notes. No changes seen.
5. Select other notes. Return to edited note. No changes seen.
6. Choose "open external" menu command again, now changes are reflected in FS Notes and the external editor opens.

**Comment by glushchenko** [comment]
Please try TextEdit

**Comment by derekvan** [comment]
Sorry, should have tried that first. Same result as above.

**Comment by gingerbeardman** [comment]
Any idea which older build broke this?

**Comment by derekvan** [comment]
Not from me--this is the first build I've installed and used.

**Comment by glushchenko** [comment]
Do you have fseventsd process? Try sudo killall fseventsd for restart

**Comment by derekvan** [comment]
I do see fseventsd running, I issued that command, and the note still does not update. The only thing that seems to update it is to run "open external" command again. Before TextEdit open, the note is updated with the text added last time via TextEdit.

**Comment by pdanford** [comment]
@glushchenko @derekvan 
This bug only occurs when the Preview is being displayed, not when the Edit window is the one displayed - which updates correctly when changes are done in an external editor. The Preview version doesn't get the update until you toggle preview or select another note and return (which doesn't quite agree with #5 in the original to reproduce bug list).

**Comment by glushchenko** [comment]
Fixed
