### ISSUE TITLE
[Bug] Can't change default extension in iOS 

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#578]
Hi,

Previously I tried to change the default extension to *.textbundle in the iOS version of fsnotes, then I didn't think it fits my need and I changed it back to *.md.

Somehow no matter what other options I am choosing in the default extension, it is still saving *.textbundle format.

I am using iOS version of fsnotes (2.6) and iOS 12.2.

Thanks

**Comment by gingerbeardman** [comment]
Textbundle is the new default, but is there a setting for that on iOS @glushchenko ?

**Comment by jakemkc** [comment]
I think so.

![IMG_7430C0CB8CB5-1](https://user-images.githubusercontent.com/18485734/57343499-a2218800-7111-11e9-9c70-4eedb1d5588d.jpeg)

**Comment by glushchenko** [comment]
Thank you @jakemkc, fixed. Will be available in AppStore as soon as possible. Container option added.

**Comment by glushchenko** [comment]
2.6.1 available  in AppStore
