### ISSUE TITLE
[bug] text not saved when sharing screen cap to fsnote in iOS

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#579]
Hi,

I was trying to save a screen cap to fsnotes in iOS, but it didn't save my note but only the image.

Step to reproduce:
1. make a screen cap
2. open the image, press the share button on the lower left, and share to fsnotes
3. type something in the next screen, and click "new note".
4. go to fsnotes and I can only see the screen cap in the corresponding entry without the text entered in step 3.

I am using iOS version of fsnotes 2.6 and iOS 12.2.

Thanks

**Comment by glushchenko** [comment]
Thank you, fixed

**Comment by glushchenko** [comment]
Please try 2.6.1

**Comment by jakemkc** [comment]
just tried 2.6.1. It seems that the problem is still there. 

I typed something and clicked "New note", and the new note in fsnotes is still with the screencap only -- no matter I am checking that note in ios and in mac version of fsnotes.

![IMG_2107](https://user-images.githubusercontent.com/18485734/57626758-92b49b80-7564-11e9-8cb0-86693dec1c9b.JPG)
![Screen Shot 4](https://user-images.githubusercontent.com/18485734/57626823-b972d200-7564-11e9-91bf-3f24fa1e49b9.png)
