### ISSUE TITLE
"Choose Folder" dialog for the storage location lacks "New folder" button

### ISSUE THREAD

**Issue by philwo** [glushchenko/fsnotes#58]
The "Choose Folder" dialog that one can open to change the Storage folder in the Preferences doesn't have a "New Folder" button, so one can only pick an existing folder for the storage.

Would be cool if it had a "New Folder" button (seems to be a common thing, just checked against the "Save" dialog of TextEdit and it has that button). :)

Tested with FSNotes Version 1.1.9 (61) on macOS 10.13.1 (17B48).

**Comment by glushchenko** [comment]
Checkout https://github.com/glushchenko/fsnotes/releases/tag/1.1.11
