### ISSUE TITLE
Behaviour of the TAB key (would prefer it to block indent)

### ISSUE THREAD

**Issue by sdclee** [glushchenko/fsnotes#581]
Apologies for posting so soon after purchasing the app but it wasn't so obvious to me that a tab indentation was required for code syntax highlighting to work, but worse still, every editor I use has the default behaviour of TAB indentation for whatever is highlighted (or the default current line). Highlighting a block and hitting TAB effectively deletes what is highlighted (which you would expect in a word processor or simple editor). This isn't helpful in the context of code snippets i.e. when muscle memory over years kicks in to expect tab to function as an indent. I can't see any way to configure KBD behaviour but apologies if I appear to have been too impatient.
Thanks in advance.

**Comment by gingerbeardman** [comment]
<kbd>Cmd</kbd>+<kbd>]</kbd> and <kbd>Cmd</kbd>+<kbd>[</kbd> are the macOS standard for indenting/unindenting text and they are listed in the menu.

But you can change these yourself using _System Preferences > Keyboard > Shortcuts > App Shortcuts_

**Comment by sdclee** [comment]
Hey thanks for the quick reply Matt. I didn't know that sequence  (probably
because I work with Mac, Windows and Linux where my editors all behave the
same) - great to know there's a Mac-specific default.
