### ISSUE TITLE
FSNotes Translation 

### ISSUE THREAD

**Issue by glushchenko** [glushchenko/fsnotes#582]
At this moment FSNotes translated to Deutsch, Russian and Ukrainian. Anyone can help with translation to French, Spain or any other popular language?

**Comment by gingerbeardman** [comment]
@aonez what do you think about Spanish?

**Comment by aonez** [comment]
Y tanto! I’ll take a look tomorrow to see the magnitude 👍🏼

**Comment by gingerbeardman** [comment]
@aonez ref https://github.com/glushchenko/fsnotes/blob/master/FSNotes/uk.lproj/Localizable.strings

**Comment by glushchenko** [comment]
And https://github.com/glushchenko/fsnotes/blob/master/FSNotes/uk.lproj/Main.strings

**Comment by glushchenko** [comment]
Big thanks @aonez, I can help with Ukrainian translation for Keka. Let me know if interesting.

**Comment by aonez** [comment]
> I can help with Ukrainian translation for Keka

@glushchenko that would be awesome! Anytime you want, [here](https://github.com/aonez/Keka/tree/master/Translations) all the files. You can create an [issue](https://github.com/aonez/Keka/issues) if you need my help.

**Comment by glushchenko** [comment]
@aonez https://github.com/aonez/Keka/pull/417
