### ISSUE TITLE
"Use first line as title" hides existing note titles

### ISSUE THREAD

**Issue by cc1** [glushchenko/fsnotes#583]
When I checked "use first line as title" on iOS, the app hid the titles of my existing titled notes. (Revealed upon switching back -- thankfully not destroyed). This setting should change app behavior for new notes, not affect existing notes.

**Comment by glushchenko** [comment]
Really, bug? Why? Feature works for all notes in dir if "Use first line as title" enabled. And thats right IMO.

**Comment by gingerbeardman** [comment]
I guess this is unexpected behaviour for the user?

**Comment by cc1** [comment]
Unexpected for this user at least. Perhaps I am an edge case. The problem for me with current app behavior is that I have hundreds of existing titled notes. It is infeasible either to use them without titles or to manually change all of them.

**Comment by glushchenko** [comment]
Just change back settings globally or per project. You should disable “Use first line as title”
