### ISSUE TITLE
FSNotes using iClould Drive folder not iCloud Drive -> FSNotes -> Archive folder as storage for archived files.

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#584]
Not certain but it seems as if FSNotes on MacOS is using the root iClould folder as storage for archived files instead of a folder within the FSNotes folder. 

This also seems to prevent the archive folder from syncing to FSNotes on iOS

**Comment by gingerbeardman** [comment]
Thanks! 

This would be why recently I found an FSNotes folder inside my FSNotes folder.

**Comment by sven-gh** [comment]
> This would be why recently I found an FSNotes folder inside my FSNotes folder.

I've also been very confused at first why there was an FSNotes folder within an FSNotes folder on iCloud.
Guess I'm slow but took me a while to understand it's the example folder/project that contains the "FSNotes - Readme" etc. files.
Maybe to prevent confusion better to name that example folder something like "Read Me" or "Start Here"?

**Comment by glushchenko** [comment]
Seems like this fixed, i can not reproduce
