### ISSUE TITLE
[Bug] Losing focus from edit mode

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#589]
FSNotes often loses focus on the edit mode and switches to search mode, removing the contents of the note from view. This often happens in the middle of editing a note or when I switch apps and return to FSNotes. I am running the latest version on FSNotes and macOS.

**Comment by gingerbeardman** [comment]
Any chance you could supply steps to reproduce?

**Comment by volt4ire** [comment]
Whoops I realized it wasn't a fault of FSNotes, but rather with one of my Karabiner Elements customizations triggering the escape key in a frequently typed key sequence. Thanks for your help with this!
