### ISSUE TITLE
Unable to delete notes from within apps

### ISSUE THREAD

**Issue by mcuix** [glushchenko/fsnotes#59]
There needs to be some option to delete notes from within the app. Its way to easy to accidentally create a new Untitled note, and the only way of deleting them is by leaving the app.

**Comment by glushchenko** [comment]
⌘+delete not works?

**Comment by greendog99** [comment]
I use ⌘+delete but I don't think it's documented anywhere, so it'd be hard for someone new to discover that. The "Edit" menu has a "Delete" item but it only applies to text inside notes. Maybe add a "Delete Note  ⌘⌫" option to the "File" menu so people can discover the shortcut? Here's NVAlt's menu:

![ss-20171114-162511](https://user-images.githubusercontent.com/30274/32805959-fd404954-c958-11e7-83fd-8693d1a570f1.jpg)

**Comment by mcuix** [comment]
Discovered where the delete was hidden.
