### ISSUE TITLE
Preview template src="*.js" should be offline

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#590]
The preview template [includes an online resource](https://github.com/glushchenko/fsnotes/blob/e3ce185c4fd98aef54ca34e9e3120623de02c1bf/Resources/DownView.bundle/index.html#L9) for MathJax support:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML" async></script>

Can we change this so the file is available on the file system, so it works offline?

**Comment by glushchenko** [comment]
Available in FSNotes 3.2.0
