### ISSUE TITLE
Link Keyboard Shorcut

### ISSUE THREAD

**Issue by ghost** [glushchenko/fsnotes#593]
More typical for links in markdown apps is `⌘ + k`

I didn't see a conflict, but this would be appreciative.

**Comment by peavine** [comment]
The Command-K keyboard shortcut is already in use for navigating the Note list (see closed issue #83). I thought perhaps this could be changed in System Preferences, but that didn't seem to work.

**Comment by gingerbeardman** [comment]
I also use Cmd+K in other editors (Medium, Patreon, WordPress) so would appreciate this.

**Comment by gingerbeardman** [comment]
@spencerclrk you can remap the shortcut yourself 

You can assign your own using: System Preferences > Keyboard > Shortcuts

![Untitled](https://user-images.githubusercontent.com/49612/58702279-43ac9a00-839d-11e9-8d51-14aaf709cb0f.png)

![Screen shot 2019-05-31 at 12 11 15](https://user-images.githubusercontent.com/49612/58702285-460ef400-839d-11e9-9f58-6566f8425a75.png)

![Screen shot 2019-05-31 at 12 11 32](https://user-images.githubusercontent.com/49612/58702288-4909e480-839d-11e9-89e6-d5f84d9229d4.png)

**Comment by gingerbeardman** [comment]
I wonder if there's a bigger ask to make keyboard shortcuts more "universal"?

**Comment by spencerclrk** [comment]
For me, even after remapping ⌘ + K is still navigating the notes.

But yes, it would make more sense to have the keyboard shortcuts more in-line with what other markdown apps (or even Mail.app) does in handing basic shortcuts.

**Comment by gingerbeardman** [comment]
Not sure what I did earlier but I can confirm that Cmd+K still navigates notes even when set as custom key combo

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1
