### ISSUE TITLE
Note URLs break if note is renamed

### ISSUE THREAD

**Issue by gdbing** [glushchenko/fsnotes#598]
In the macOS app, if you right click on a note and select "Copy URL", the URL is like `fsnotes://find/note%20title` and will not find the note if the note is renamed.

**Comment by glushchenko** [comment]
Please provide more details, can not reproduce.

**Comment by gdbing** [comment]
The URL produced by Copy URL seems to be a URL for a search for the "name" of the note. (fsnotes://find/$name) If the name changes the search doesn't turn up the note.

I'm calling it the "name" because it is the field which you edit if you right click and select "Rename" or press ⌘R

The issue is more about Rename than it is about Copy URL I guess.

**Comment by glushchenko** [comment]
I don't understand what did you want? 

After file renaming, new URL updated and works fine for me:

![Untitled 2019-05-31 08_57_44](https://user-images.githubusercontent.com/1089917/58685216-97aa8500-8383-11e9-97df-9458a121d5ad.gif)

**Comment by gingerbeardman** [comment]
Those URLs are simply search shortcuts.

The URL is valid and working at the time it is generated. If the note is renamed then, yes, that will invalidate the old "Find" URLs. If you remove the matching text (title or body) then they will not find what they once did. Make sense?

So, I guess you are looking for a type of URL that works regardless of note title?

In that case you can craft your own note search URL to search contents of the note that will not change, for example some sort of hashtag or other text within the note. But the same caveat applies, if you change that text then the search URL will no longer work.

See "Finding existing notes" here: https://github.com/glushchenko/fsnotes/wiki/Finding-&-creating-documents-via-URLs

This is a simple, flexible solution that can require some user maintenance if notes and contents are changing frequently.

How could this "Find" URL system be better for you?
