### ISSUE TITLE
[REQ] Ability to create new note when title has search matches

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#599]
It's annoying that you have to come up with a note title that has no matches before you can create a note from the search field.

How about Cmd+Enter (or whatever) on the search field creates a note of that title regardless of matching?

**Comment by peavine** [comment]
I just installed FSNotes 3.3 but the Command-Enter keyboard shortcut doesn't seem to work for me. Does this work for anyone else or am I doing something wrong.
