### ISSUE TITLE
Open .md files from Finder to import into FSNotes

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#602]
**Is your feature request related to a problem? Please describe.**
Often I use Alfred/Spotlight to find a note .md file, which I know is managed by FSNotes. But I cannot open the note file itself, I have to remember to open FSNotes and then find the note.

**Describe the solution you'd like**
FSNotes register itself as being able to open .md (and other recognised filetypes)

- If note exists in FSNotes it will be opened.
- If note is outside of FSNotes then it will be imported.

**Describe alternatives you've considered**
Have tried, FSNotes opens but note is not opened/imported

**Additional context**
![Screen shot 2019-06-04 at 13 08 48](https://user-images.githubusercontent.com/49612/58877977-1710bf00-86ca-11e9-92e3-547046e22a2f.png)

**Comment by gingerbeardman** [comment]
My workaround is an Alfred Workflow to allow me to open FSNotes Search from Alfred

https://github.com/glushchenko/fsnotes/wiki/Alfred-Workflow

**Comment by glushchenko** [comment]
Implemented

**Comment by gingerbeardman** [comment]
AWESOME - thanks!
