### ISSUE TITLE
Notes list not appearing

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#603]
**Describe the bug**
Notes list not appearing

**To Reproduce**
Somehow the width of the notes list has been set to zero in prefs

**Expected behavior**
Showing notes list should always show it

**Expected behavior**
Showing notes list does not show it

**File**
[co.fluder.FSNotes.plist.txt](https://github.com/glushchenko/fsnotes/files/3253416/co.fluder.FSNotes.plist.txt)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 3.2.0

**Comment by bhb** [comment]
I ran into this as well. For me, the following worked as a workaround

1. Click `FSNotes, Preferences`
2. Click `Layout`
3. Under `Note list location`, click `Top`, then click `Side`

This restored my note list (on the side). If you prefer the note list on the top, just reverse the order of clicks in step 3.

**Comment by gingerbeardman** [comment]
@bhb nice!

**Comment by danseely** [comment]
I've found that @bhb's fix works, but it does periodically come back, and I have to perform the fix again.

**Comment by glushchenko** [comment]
Seems like it fixed
