### ISSUE TITLE
Bundle Alfred Workflow?

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#604]
**Is your feature request related to a problem? Please describe.**
I like to launch FSNotes from Alfred

Alfred Workflow is here https://github.com/glushchenko/fsnotes/wiki/Alfred-Workflow

![Screen shot 2019-06-04 at 18 27 55](https://user-images.githubusercontent.com/49612/58900163-8d2b1b00-86f6-11e9-981d-27a18bd27a5f.png)

![Screen shot 2019-06-05 at 16 31 15](https://user-images.githubusercontent.com/49612/58969319-6aa90880-87af-11e9-93e6-6900356d9a2c.png)

**Describe the solution you'd like**
Maybe it could be bundled with the app?

**Comment by glushchenko** [comment]
Duplicate? https://github.com/glushchenko/fsnotes/issues/602

**Comment by gingerbeardman** [comment]
Not really, I was thinking some way to include the Alfred integration inside the FSNotes app? Maybe there will be other integrations in the future?

Dash.app does it like this:

![Screen shot 2019-06-07 at 14 15 13](https://user-images.githubusercontent.com/49612/59106627-c6e66680-892e-11e9-8701-c43a8d6ec78f.png)

**Comment by gingerbeardman** [comment]
Revised workflow - V2.0

2.0
+ Added: Import... feature
+ Added: Encrypted TextPack .etp support
- Removed: Create blank note (use Create...)

1.0
+ Added: Open...
+ Added: Search...
+ Added: Create...
+ Added: Create from Clipboard...

**Comment by Xiao6** [comment]
> Revised workflow - V2.0
> https://github.com/glushchenko/fsnotes/wiki/Alfred-Workflow
> 
> 2.0
> 
> * Added: Import... feature
> * Added: Encrypted TextPack .etp support
> 
> * Removed: Create blank note (use Create...)
> 
> 1.0
> 
> * Added: Open...
> * Added: Search...
> * Added: Create...
> * Added: Create from Clipboard...

Very good workflow for Alfred. 
I think it will turn the workflow into awesome one if it can support grep search and shows results in alfred.
i.e. 1. search by file name showing in Alfred and open in FSNotes
2. search by file content showing in Alfred and open in FSNotes.

![image](https://user-images.githubusercontent.com/3309353/62846607-50474b80-bc86-11e9-9880-5766a172059c.png)

This probably needs combination of grep script and URLSchema to work together.
I think it will take some time to implement though.

I currently use great alfred grep workflow from ichitaro: https://github.com/ichitaro/alfred-grep
And define my own shortcut to search FSNotes folders. Then open using FSnotes. 

Feel this is great addition for productivity. And it seems FSNotes cannot search multiple folder, I can use this as workaround until it is implemented.

**Comment by gingerbeardman** [comment]
Thanks for using the workflow!

Already `fsf` (or `fs` > `Search...` option) can search by both file name and file contents. Example:

![Screen shot 2019-08-12 at 16 04 52](https://user-images.githubusercontent.com/49612/62875429-ecbb2d80-bd1a-11e9-87cb-99a8574d324d.png)

What searches are you trying to that `fsf` cannot achieve? If you give me examples, I can solve it.

**Comment by Xiao6** [comment]
> Thanks for using the workflow!
> 
> Already `fsf` (or `fs` > `Search...` option) can search by both file name and file contents. Example:
> 
> ![Screen shot 2019-08-12 at 16 04 52](https://user-images.githubusercontent.com/49612/62875429-ecbb2d80-bd1a-11e9-87cb-99a8574d324d.png)
> 
> Results in example:
> 
> 1. match in content
> 2. match in sub-folder name
> 3. match in file name
> 
> What searches are you trying to do that `fsf` cannot achieve? If you give me examples, I can solve it. Maybe it will need grep, maybe not. ✌️
> 
> > ps: You can add additional folders to `fsf` function using Alfred configuration (double-click `fsf` and add directory to list in _Scope_ panel)

Thanks! fsf works for me now. Nice workflow. This is big plus for FSNotes

**Comment by gingerbeardman** [comment]
Thanks for your kind words!

`fsf` is the quickest way to get to search in content, you can also choose `fs` then move cursor to "Search..." (some people prefer this)

**Comment by m0ll3art** [comment]
seems not to work with alfred4 anymore. Do not get any result back. `fsf` recognized as a keyword but giving a query does not build a result set back.

**Comment by gingerbeardman** [comment]
@m0ll3art can you share screenshot? I use it every day and it's fine in Alfred 4.

![Screen shot 2020-01-16 at 13 25 14](https://user-images.githubusercontent.com/49612/72528692-a2a71c80-3863-11ea-8b75-cd2073adcbaa.png)

**Comment by m0ll3art** [comment]
yeah sure .. 
till now ok 
![Screenshot 2020-01-16 at 14 27 58](https://user-images.githubusercontent.com/11415120/72529017-aee3a780-386c-11ea-8a0c-9f3bf50650ba.png)

and here a `code` query .. There is an outline in an md file named "Code highlighting" 

![Screenshot 2020-01-16 at 14 28 08](https://user-images.githubusercontent.com/11415120/72529123-e6525400-386c-11ea-98cc-a3013774db50.png)

**Comment by m0ll3art** [comment]
My setup involves Textbundle container so I switched to `None` recreated the same note and I got as filename "669D6B44-BF4D-4D70-B3D2-9C36D6C874B8.md" an UUID filename. How did you achieve to get as expected fo FS note based app a "human-readable" filename? I thought I saw such settings somewhere..

**Comment by m0ll3art** [comment]
getting better I changed the scope of the WF search and now find hits but textbundle seems not really supported as shown in the next figure 

![Screenshot 2020-01-16 at 14 51 28](https://user-images.githubusercontent.com/11415120/72530476-bb1d3400-386f-11ea-97a6-67a454f9c191.png)

but still not finding the UUID based file which also contains the example outline

**Comment by gingerbeardman** [comment]
> textbundle seems not really supported
This mechanism relies on Spotlight, so textbundle support may require a specific QuickLook plugin?

> still not finding the UUID based file which also contains the example outline
Need more information and example.

**Comment by m0ll3art** [comment]
my settings in Fsnotes were containers type=Textbundle so `.textbundle` generated. Then I switch to `None` i.e. no textbundle container and it created the new note I saved with the filename beeing an UUID, the one in my previous post

**Comment by m0ll3art** [comment]
ok now the situation is simple 

using `fsn title` will create a file named title.metadata in the notes root directory, **BUT** creating a **NEW** note in FSNOTEs (cmd-n) then a UUID based filename is generated. Would be interesting to not have such different behavior despite the fact that from a programmer point of view not always easy to use same workflow. One could delegate file creation to FSNotes and use the title (provided to `fsn`) as first outliner. 

I prefer to have a human-readable filename as your plugin creates as a kind of UUID..

**Comment by gingerbeardman** [comment]
When creating a new note (workflow just asks FSNotes to create it) I always rename the note (Cmd+R) which changes it from UUID to human readable of your choice.

**Comment by m0ll3art** [comment]
sure makes sense but perhaps FSNotes could think on how to update its filename e.g. take as filename the first written outline or how nvAlt (and perhaps in the future nvUltra) is doing ..

**Comment by gingerbeardman** [comment]
It used to - it resulted in some problems

**Comment by gingerbeardman** [comment]
Main install for this is now Alfred Gallery: https://alfred.app/workflows/gingerbeardman/fsnotes/
