### ISSUE TITLE
Encrypted TextPack bundle .etp needs to be registered in Info.plist

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#605]
File Types on macOS have their UI registered by their supporting apps, benefits are many including interoperability with other apps.

Here is what some UTIs look like (screen grab taken from Alfred):
![Screen shot 2019-06-04 at 18 30 29](https://user-images.githubusercontent.com/49612/58900326-e004d280-86f6-11e9-9c5c-8b426e64c5f4.png)

If you introduce a new filetype that you wish to be adopted or used in other apps then you need to register it's UTI in the Info.plist

Examples from Ulysses:
```xml
<dict>
	<key>CFBundleTypeExtensions</key>
	<array>
		<string>textbundle</string>
	</array>
	<key>CFBundleTypeIconFile</key>
	<string>TextBundle</string>
	<key>CFBundleTypeName</key>
	<string>TextBundle</string>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
	<key>LSHandlerRank</key>
	<string>Owner</string>
	<key>LSItemContentTypes</key>
	<array>
		<string>org.textbundle.package</string>
	</array>
	<key>LSTypeIsPackage</key>
	<integer>1</integer>
</dict>
<dict>
	<key>CFBundleTypeExtensions</key>
	<array>
		<string>textpack</string>
	</array>
	<key>CFBundleTypeIconFile</key>
	<string>TextPack</string>
	<key>CFBundleTypeName</key>
	<string>TextPack</string>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
	<key>LSHandlerRank</key>
	<string>Owner</string>
	<key>LSItemContentTypes</key>
	<array>
		<string>org.textbundle.compressed</string>
	</array>
	<key>LSTypeIsPackage</key>
	<integer>0</integer>
</dict>
```

**Comment by Genxster1998** [comment]
What about *.textpack file support .Its compressed textbundle but i can not import or open  it with FSNotes because it can not be recognised by FSNotes.
