### ISSUE TITLE
Import mangles filenames and titles with timestamp

### ISSUE THREAD

**Issue by deanishe** [glushchenko/fsnotes#608]
**Describe the bug**
When importing files, FSNotes adds the current timestamp to the filename and note title ("First line as title" option is ignored).

**To Reproduce**
1. Import Markdown files into FSNotes by dragging them into an iCloud Drive folder in the sidebar or via File > Import
2. Notice that every filename and note title has the current timestamp appended
3. Notice that toggling the "First line as title" has no effect

**Expected behavior**
Filenames should be left as-is unless a file of the same name already exists. In that case, a number should be appended to the filename, but not the title.

**Actual behavior**
Timestamp is appended to note filenames and titles.

**Workaround**
Copy files directly into FSNotes' iCloud folders using Finder instead of FSNotes' own import.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version 3.3.1 (268) from MAS

**Comment by glushchenko** [comment]
Fixed in 3.3.2
