### ISSUE TITLE
(iOS) reverts to “use first line as title” despite user setting

### ISSUE THREAD

**Issue by floodfish** [glushchenko/fsnotes#609]
**Describe the bug**
In iOS app, the “use first line as title” preference silently resets itself. When unchecking the option, it reverts to using the file names for some time (a few hours?) but then will reset to using the first line as title and the preference has been mysteriously reset with no user input. It can be manually unchecked, but will always reset again after an unknown interval. (I am using iCloud Drive for storage of .txt files. I have not tested with other file types or locations.)

**Desktop (please complete the following information):**
 - OS: iOS
 - OS version: 12.3.1
 - FSNotes version: 2.6.2 build 110 (but behavior has been similar in recent past versions)

**Comment by glushchenko** [comment]
May be that result of sync with macOS?

**Comment by floodfish** [comment]
The macOS setting is the same: I do not use the first line as the title for either one. My macOS version keeps the preference setting. 

I think the iOS preference resets even when my Mac is offline.

**Comment by sven-gh** [comment]
I'm running into the same issue:
- disable the "Use first line as title" on iOS
- kill the app and relaunch
- the setting has enabled itself again

The problem only seems to happen for me on the main "iCloud Drive" folder while the other folders work fine.
On Mac the setting is disabled so I don't think it's a sync issue.
Seems that on app launch the folder "iCloud Drive" will always default back to have the setting enabled.

**Comment by glushchenko** [comment]
Fixed in 2.7.0
