### ISSUE TITLE
Faster performance would be nice

### ISSUE THREAD

**Issue by JesseAldridge** [glushchenko/fsnotes#61]
Notational Velocity manages to search through all ~10K of my notes pretty much instantly.  There is a significant lag when searching with this tool.  It's not unbearable, but it does make me miss NV.

**Comment by jeff-h** [comment]
Wow, I thought *I* had a lot of notes! :) But anyway, I'm surprised to read your issue there. I have 1,200 notes and searching is basically instant. Could you try a folder with just a subset of your notes and see if it becomes "instant" at some point? I can't see why it wouldn't be instant even with 10,000 as it's an in-memory search.

**Comment by JesseAldridge** [comment]
Below is a python script which will generate a bunch of test notes.  It does indeed run near instantly if I set it to generate 1000 notes.  But fsnotes seems to error out and switch to its default directory if I try to load the full 10K:

```
import os, shutil

from random_words import RandomWords # pip install randomwords

dir_path = os.path.expanduser('~/Dropbox/test_notes')
if os.path.exists(dir_path):
  shutil.rmtree(dir_path)
os.mkdir(dir_path)

rw = RandomWords()

for i in range(10000):
  print i
  note_text = ' '.join([rw.random_word() for _ in range(100)])

  file_path = os.path.join(dir_path, '{}.txt'.format(i))
  with open(file_path, 'w') as f:
    f.write(note_text)
```

**Comment by JesseAldridge** [comment]
And yeah, it's multiple years worth of notes :)

**Comment by JesseAldridge** [comment]
Oh wait, it did eventually load them all.  But yeah, if I type in the word "testing" there is a noticeable lag.  It seems to take about .5 seconds per keystroke.

**Comment by glushchenko** [comment]
@jeff-h i think first problem here https://github.com/glushchenko/fsnotes/blob/master/FSNotes/ViewController.swift#L341

**Comment by glushchenko** [comment]
Try 1.1.9 build 61 please https://github.com/glushchenko/fsnotes/releases/download/1.1.9b61/FSNotes.app.zip

**Comment by jeff-h** [comment]
I created a folder with 5,000 notes in it, and oddly enough the current MAS 1.9 version searches just fine through that for me. Is this somewhat hardware dependent? My Mac's a 2015 MacBook Pro i5 / 8GB / 256 SSD (pretty common I'd imagine.)

I did also try the b61 download above and it was the same — both were good :)

**Comment by glushchenko** [comment]
And one more thing :) Improve search speed https://github.com/glushchenko/fsnotes/releases/tag/1.1.11
