### ISSUE TITLE
List of keyboard shortcuts?

### ISSUE THREAD

**Issue by sven-gh** [glushchenko/fsnotes#614]
Hi is there a list of keyboard shortcuts available somewhere?

I know we can see certain shortcuts in the menu but I'm looking for:
- keyboard shortcut to start editing the currently selected note i.e. put cursor in the note so I can type
- keyboard shortcut to jump back to the note list so I can continue navigate the note list with up/down error

Are these available?

Thanks!

**Comment by glushchenko** [comment]
Hi, no. You can fill wiki themselves.

1. enter 
2. cmd - enter

**Comment by gingerbeardman** [comment]
I've started such a page https://github.com/glushchenko/fsnotes/wiki/Hidden-keyboard-shortcuts

**Comment by gingerbeardman** [comment]
I've also added those two keys to the default file "FSNotes - Shortcuts.md"

https://github.com/glushchenko/fsnotes/blob/master/Resources/Initial/FSNotes%20-%20Shortcuts.md

**Comment by sven-gh** [comment]
OK awesome! Thanks guys!
Over time it might make sense to have a direct link in the menu for this e.g. Help > Keyboard Shortcuts

**Comment by gingerbeardman** [comment]
@sven-gh agreed. It'd be great if we could do a new pass over all shortcut keys for the docs, and combine the wiki pages into one

**Comment by sven-gh** [comment]
I want to go through them to get the max out of the app anyhow so will note them down as I do that - probably in the next couple days
