### ISSUE TITLE
[REQ] LaTeX support

### ISSUE THREAD

**Issue by AlJohri** [glushchenko/fsnotes#616]
**Describe the solution you'd like**

I would like LaTeX support to type math equations similar to Jupyter Notebooks or Quiver.

**Comment by BeWe11** [comment]
There is [mathjax](https://www.mathjax.org) support already if you didn't know that. Maybe that's sufficient for your needs?

**Comment by AlJohri** [comment]
I missed to see that, let me try it out- thanks!

**Comment by torralbofco** [comment]
The main problem with mathjax support is that, the inline math mode standard syntax (with dollars "$") is not working in version 4.10.2. The syntax is `((formula))` which is not LaTeX standard and cause problems when migrating the notes to other apps or to produce a correct pdf file with pandoc. Please, support the standard syntax `$formula$` for inline math.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5b2/FSNotes_v5b2.zip
