### ISSUE TITLE
Font size controls on Mac are broken

### ISSUE THREAD

**Issue by sven-gh** [glushchenko/fsnotes#619]
How do you increase font size on Mac?
I go to Preferences > Layout 
and click the "Set" button
which reveals the Fonts window
then I select the desired font size
but from there on how do I save this? 
Enter or double click does not work 

Is this a bug or am I missing something obvious?

Mac 10.14.5
FSNotes 3.3.1

**Comment by gingerbeardman** [comment]
I've tripped on this. The front panel can get into a state where it's detached from affecting the app. Try relaunching the app and doing it again without switching focus away from the font dialog.

**Comment by spencerclrk** [comment]
Having issues with fonts changes too. Is there a plist or something I could modify manually in the meanwhile?

MacOS 10.14.5
FSNotes 3.3.2

**Comment by gingerbeardman** [comment]
Yeah, coming back to my Mac this seems more broken that I remember.

Quit app and change:

`~/Library/Containers/co.fluder.FSNotes/Data/Library/Preferences/co.fluder.FSNotes.plist`

keys:
- font
- fontSize
- codeFont
- codeFontSize

**Comment by spencerclrk** [comment]
> Quit app and change:
> 
> `~/Library/Containers/co.fluder.FSNotes/Data/Library/Preferences/co.fluder.FSNotes.plist`

That did the trick.

**Comment by nabsiddiqui** [comment]
Doesn't seem to work for me.  Am I missing something?

<img width="625" alt="Screen Shot 2019-06-16 at 11 45 24 PM" src="https://user-images.githubusercontent.com/11954508/59577246-dd0fc780-9090-11e9-8bdf-d026f131e908.png">

**Comment by gingerbeardman** [comment]
@nabsiddiqui did you quit app and change it?

**Comment by nabsiddiqui** [comment]
@gingerbeardman yes, I did. I also reinstalled. The font shows up but not the size. I am using the brew version in case that matters.

**Comment by gingerbeardman** [comment]
@nabsiddiqui I've just done it here:

14pt
![Screen shot 2019-06-17 at 16 28 33](https://user-images.githubusercontent.com/49612/59616893-37566a00-911d-11e9-93af-795889511982.png)

16pt
![Screen shot 2019-06-17 at 16 28 46](https://user-images.githubusercontent.com/49612/59616894-37ef0080-911d-11e9-9839-d382723debfc.png)

**Comment by sven-gh** [comment]
I wasn't able to get this to work either. In my case the "font" and "fontsize" are not included in the plist file at
/Library/Containers/co.fluder.FSNotes/Data/Library/Preferences/co.fluder.FSNotes.plist

Not sure if this is because I'm running the version from the app store(?) or due to another reason

**Comment by nabsiddiqui** [comment]
Yes, I had to add them manually as well.

**Comment by sven-gh** [comment]
OK now I'm in the same place as you are: can update font, but font size stubbornly remains at 14

**Comment by gingerbeardman** [comment]
Perhaps them not being there means they have never been set? Possible.

You can add them manually in whatever plist editor you are using. Try that for now?

**Comment by sven-gh** [comment]
Yes adding manually works for font type, but for some reason does not work for font size.

**Comment by glushchenko** [comment]
Hi guys, I think thats annoying bug fixed in FSNotes 3.3.3. Sorry 🙃

**Comment by gingerbeardman** [comment]
Works for me!
