### ISSUE TITLE
Spaces to be used when doing *Shift Left* and *Shift Right* (when "Use 4 spaces…" is checked)?

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#622]
@glushchenko, would it be possible for spaces to be used when doing *Shift Left* and *Shift Right* (when "Use 4 spaces…" is checked)? Otherwise, I think this feature is broken: my documents are filling with a mix of spaces and tabs, like this:

<img width="92" alt="Screen Shot 2019-06-11 at 20 38 23" src="https://user-images.githubusercontent.com/6884276/59317560-18715700-8c89-11e9-85a2-397a04f6c761.png">

Also, the option in settings ("Use 4 spaces instead tab") should be written "Use 4 spaces instead of tab".

_Originally posted by @quinncomendant in https://github.com/glushchenko/fsnotes/issues/436#issuecomment-501086911_

**Comment by quinncomendant** [comment]
Thanks, @gingerbeardman

**Comment by glushchenko** [comment]
Please try FSNotes 3.3.3, thanks.

**Comment by peavine** [comment]
I've encountered a small oddity with this feature in FSNotes 3.3.3.  In the following video, I select Control-Right Bracket twice. I then select Control-Left Bracket and the indent is removed but the cursor changes position on the line.

![peavine](https://user-images.githubusercontent.com/35905279/59883806-269b3380-936b-11e9-8a6b-5370b98f610e.gif)

**Comment by glushchenko** [comment]
Thanks @peavine, fixed

**Comment by glushchenko** [comment]
Please try 3.3.4

**Comment by peavine** [comment]
I installed FSNotes 3.3.4 and that fixes the issue I raise. Thanks.
