### ISSUE TITLE
Notes list showing incorrect date

### ISSUE THREAD

**Issue by TannerTechnical** [glushchenko/fsnotes#623]
When sorting the notes list by Creation Date, the date displayed in the Notes List is the Modification Date.

Edit a note that was created sometime in the past. Run `touch <notename>` (or just edit and save the file) to change the Modified Date to today. Choose Creation Date as your Sort By criteria in FSNotes.

**Expected behavior**
The Notes List date should show the Creation Date.

**Actual behavior**
The Notes List shows the Modification Date.

**Workaround**
None 

**Note**
This really cripples the usefulness of sorting by Creation Date. I should mention that nvAlt handles this situation correctly.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - FSNotes version [3.3.1

**Comment by peavine** [comment]
This sounds like a good idea but I had a quick question.

If sort by creation date is selected, the date shown in the Note List would be the notes' creation date.

If sort by modification date is selected, the date shown in the Note List would be the notes' modification date.

What date would be shown in the Note List if sort by title is selected? FWIW, my preference would be modification date.

**Comment by TannerTechnical** [comment]
I hadn't thought about that. The date has much less relevance when sorted by title. Maybe it could display the last selected sort by: date.

Or perhaps the Hide Date in Title preference can be changed to a Show Date in Title preference and offer a choice between modified or created dates...

**Comment by glushchenko** [comment]
Fixed in 3.3.4

**Comment by peavine** [comment]
> I hadn't thought about that. The date has much less relevance when sorted by title. Maybe it could display the last selected sort by: date.

FWIW, the above is the approach taken in 3.3.4.

 It's nice to be able to show either creation or modification date.

**Comment by TannerTechnical** [comment]
Thank you for the fix! Much more usable now.

> Fixed in 3.3.4
