### ISSUE TITLE
iOS: drag to organize

### ISSUE THREAD

**Issue by sven-gh** [glushchenko/fsnotes#626]
Would be convenient if on iOS we can select a note and drag it to a folder or tag to organize the notes quicker (just like it's already in place on Mac).
e.g. putting your finger on the note for a brief moment will 'select' it so you can then drag to where the note needs to go.
See for example the Bear app 

also would be good if this worked with multi-select
i.e. select multiple notes with the current existing functionality and then allow to drag all these notes directly onto a folder or tag

**Comment by glushchenko** [comment]
Added in 2.9.0
