### ISSUE TITLE
[REQUEST] Use Tab to indent list level

### ISSUE THREAD

**Issue by BeWe11** [glushchenko/fsnotes#627]
Disclaimer: This is a suggestion based on personal preference.

Other editors (e.g. [typora](https://typora.io)) let you indent a list level by simply pressing \<Tab\>.

Example:

```markdown
* list item 1
* <cursor_is_here>
```
In this example, if you press \<Tab\> while the cursor is at the noted position, fsnotes will just insert some space (normal Tab behavior): 
```markdown
* list item 1
*     <cursor_is_here>
```
In some other editors, pressing \<Tab\> in that situation will indent the line that you are on the next list level:
```markdown
* list item 1
  * <cursor_is_here>
```
Additionally <shift+Tab> will move one list-level up, i.e. indent the line back by one level.

I think this greatly improves the workflow of writing multi-level lists. I know that there are the <cmd+]> and <cmd+[> shortcuts, but I like the usage of Tab here because it's very intuitive.

**Comment by gingerbeardman** [comment]
I like this.

**Comment by jochne** [comment]
It seems that this feature not works in 6.1.3

**Comment by gingerbeardman** [comment]
> It seems that this feature not works in 6.1.3

Confirmed, currently broken.

**Comment by franciscolourenco** [comment]
@glushchenko speaking of bugs, this is the other one I noticed right away when trying FSNotes.

**Comment by gingerbeardman** [comment]
Would love to see tis repaired, it annoys me daily.

**Comment by dylanseeger** [comment]
Same.

**Comment by rbansal42** [comment]
This is the 1 feature that I need so badly. I use tab to intend and out-intend daily. It is super intuitive.

Waiting for when this broken feature will be fixed.

**Comment by malmod** [comment]
Paying user here... This is currently one the biggest UX problems with this app.

**Comment by glushchenko** [comment]
Reimplemented. Thanks to all for patience.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/6.5.0
