### ISSUE TITLE
[REQUEST] Add option to customize keyboard shortcuts

### ISSUE THREAD

**Issue by BeWe11** [glushchenko/fsnotes#631]
I wonder if it might be possible to add a page to the options menu that lets users customize all the hotkeys (or at least a subset) used in the app. For example, a user might want to use Shift-Command-Delete for note deletion instead of Command-Delete. Right now, the only customizable hotkeys are the global ones, i.e. search and save clipboard.

**Comment by sven-gh** [comment]
Hi you can customise them - here's an example: https://github.com/glushchenko/fsnotes/wiki/Custom-keyboard-shortcuts

**Comment by BeWe11** [comment]
Ah thank you, I missed that!
