### ISSUE TITLE
Images disappear

### ISSUE THREAD

**Issue by sven-gh** [glushchenko/fsnotes#633]
I'm not able to reproduce this consistently 
but it often happens that images disappear:

- create new rtf note
- type some text
- on the next line, paste in an image from your clipboard 
- the line below the image, type some more text (*)

Then at some point the image will disappear. 
Either by navigating up/down with the arrow keys or sometimes just by clicking somewhere in the note.
But I'm not sure what it is exactly that causes it.

The image is still on the filesystem, just not being displayed anymore in the note

(*) notice how the font changed on this line compared to the text at the top

This is with v3.3.1

**Comment by glushchenko** [comment]
Image insertion is not supported for RTF files and support not planned

**Comment by sven-gh** [comment]
I see. Those nice app store screenshots in the "Diary" folder had me well fooled then. 
They make FSNotes look like a potential Apple Notes alternative, but I understand now that it are in fact .md files without syntax

**Comment by glushchenko** [comment]
For images storing please use markdown, textbundles and encrypted text bundles.

**Comment by sdrygalski** [comment]
What else is not supported but not clearly communicated to the user?

**Comment by gingerbeardman** [comment]
@sdrygalski that's enough

**Comment by sdrygalski** [comment]
you are losing users data
