### ISSUE TITLE
New folders being created in iCould > FSNotes > Archive

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#634]
FSNotes 3.3.1 on macOS 10.14.5
FSNotes 2.7.1 on iOS 12.3.1 iPad

Right clicked left panel area in FSNotes macOS.

Choose New Folder and created folder 'KITCHEN REMODEL'

Selected new folder and created rtf file inside.

Folder/File did not sync to iPad until force restart of iOS App.

Choose Reveal Folder and folder "KITCHEN REMODEL" is located inside: iCloud > FSNotes > Archive  

All other folders are in: iCloud > FSNotes

**Comment by glushchenko** [comment]
Fixed long time ago
