### ISSUE TITLE
Note list margins are too wide?

### ISSUE THREAD

**Issue by sepich** [glushchenko/fsnotes#635]
**Describe the bug**
I've upgraded from v2.9.5
![](https://habrastorage.org/webt/p6/v7/mw/p6v7mwejtptgjvx9aidiezixs_o.png)
to v3.3.4
![](https://habrastorage.org/webt/ed/jt/vb/edjtvbun9bbqds67plw-mihsek4.png)
And noticed that left/right margins of Note List are much wider.
How can I revert this?

**To Reproduce**
1. Set in Layout settings:
Note list location: side
Note list spacing: <tune to have 2 lines>
Preview font size: small

**Desktop (please complete the following information):**
 - OS: OSX
 - OS version: Mojave
 - FSNotes version 3.3.4

**Comment by peavine** [comment]
The margins in the Note List are clearly larger in 3.3.4 than in 2.9.5. My personal preference is for smaller  margins, but other users clearly disagree. For example, see issue #461 where @sweenzor requests expanded padding in both the Note List and Editor.

**Comment by gingerbeardman** [comment]
Personally I feel things should align for a harmonious interface.

So for me smaller margins so the text aligns to the width of the search box would be best.

**Comment by glushchenko** [comment]
Guys, left margin uses for Pin and Locked/unlocked notes icons. Right margin for symmetry. Sorry ;-)
