### ISSUE TITLE
Sort by date doesn't always work

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#636]
I'm finding it hard to determine when it works and when it doesn't, but the notes are almost never in "modification date" order, even though that's what I have chosen. Let me know if I can provide more info. Is the sorting correct for anyone else?

Also, does it reverse the sort order if you select the same menu item a second time? If so, that's very obscure! :)

**Comment by glushchenko** [comment]
If you are not changed project settings, “sort by” works with global settings, from menu bar.

**Comment by jeff-h** [comment]
Sorry, I forgot to mention that this is a problem only when I am filtering the notes list by typing in the "Search or create" field. I don't think the resulting filtered list is ever fully correctly sorted for me. It mostly is, but there are always random exceptions.

I don't use projects so it's not that — I've just chosen View > Sort by > Modification date. I also noticed that this setting is lost when I quit the app. When I reopen it, it's not ticked and the list isn't sorted by modification date. Is it possible I have a corrupted prefs perhaps? Anyway, I think that's a side issue.

I haven't had a lot of time to look at FSNotes' code for a while now (sorry!). I will probably need to check out the latest revision and do a bit of debugging. I was mostly curious that nobody else seems to be experiencing this issue!

**Comment by glushchenko** [comment]
Seems “Sort by” not implemented in search. I will check it later

**Comment by peavine** [comment]
When sort-by-title is enabled, the search order remains correct when a search is done. The search order appears askew when sort-by-date (either creation or modification) is enabled. This is with 3.3.4.

**Comment by peavine** [comment]
> Also, does it reverse the sort order if you select the same menu item a second time? If so, that's very obscure! :)

FSNotes has worked this way as long as I've been using it. I agree It is a bit obscure--I only noticed it because sort-by-title initially sorted from z to a.

**Comment by gingerbeardman** [comment]
> I'm finding it hard to determine when it works and when it doesn't, but the notes are almost never in "modification date" order, even though that's what I have chosen. Let me know if I can provide more info. Is the sorting correct for anyone else?
> 
> Also, does it reverse the sort order if you select the same menu item a second time? If so, that's very obscure! :)

Standard MacOS behaviour (at least in well-implemented apps whose developers care)

**Comment by jeff-h** [comment]
> Standard MacOS behaviour

Really! Not disputing it, but do any Apple apps do this? Mail certainly doesn't.

**Comment by peavine** [comment]
> > Standard MacOS behaviour
> 
> Really, I had no idea! :) Not disputing it, but do any Apple apps do this? Mail doesn't seem to.

The Finder doesn't.

**Comment by glushchenko** [comment]
Fixed in 4.0.18
