### ISSUE TITLE
subfolder support (again)

### ISSUE THREAD

**Issue by semiopat** [glushchenko/fsnotes#637]
**Describe your feature request**
I know you closed a similar request, but I have arguments to make you consider it again

**Additional context**
To make FSNotes my only notes app, I need to open old notes of other apps, which are stored in significant folders and subfolders; it would be great to open one of those folder and recover its hierarchy to easily find a note.
It could also be useful to share folders with subfolders to people who use FSNotes too (I have group of students in mind).

**Comment by gingerbeardman** [comment]
I would also still really like subfolders, because tags aren't good enough for me to replace my folder hierarchy with tags.

**Comment by glushchenko** [comment]
I am plan to implemented this feature in FSNotes 3.0. Like additional option, without current UI changes

**Comment by peavine** [comment]
FWIW, the earlier request mentioned by @semiopat is closed issue #69.

**Comment by semiopat** [comment]
> I plan to implement this feature in FSNotes 3.0. Like additional option, without current UI changes.
> 
> Search, pins and more will not working

Means you won't go this way anymore ?

**Comment by glushchenko** [comment]
This means that Apple does not allow index or pin for external files

**Comment by semiopat** [comment]
Sorry if I don't understand: you already make it possible to pin external file; when I use the `Folder>Attach Storage feature`, I can work with external folder, and pin or tag the files inside. Do you mean that it's not possible with file in subfolders ?

**Comment by glushchenko** [comment]
For iOS? Only for app documents folder. We dont have access to another apps

**Comment by semiopat** [comment]
No, macOS (sorry if I was not clear)

**Comment by gingerbeardman** [comment]
@semiopat in future please fill out the bug/request template to avoid confusion like this. 👍

**Comment by semiopat** [comment]
ok; it was not specified in the pre-filled field, and I'm not used to it, but I'll pay attention to this.

**Comment by Xiao6** [comment]
upvote. subfolder support will be big win for this app. I hold on fully switching my note taking app because of no such feature.

**Comment by gingerbeardman** [comment]
@Xiao6 subfolder is supported, just not displayed in sidebar.

**Comment by Xiao6** [comment]
> @Xiao6 subfolder is supported, just not displayed in sidebar.
I workaround this by adding multiple storage folders. Concept same as multiple notebooks in onenote. I only need one level folder, so this workaround solves all my daily usage.

**Comment by jakemkc** [comment]
In MacOS fsnotes, can you guys collapse the attached storage folder in the sidebar? (i.e., just showing storage folder name, not the subfolders)

**Comment by gingerbeardman** [comment]
@jakemkc please add that as new issue/feature request

**Comment by fuzzy76** [comment]
The open issue for this is #188

**Comment by glushchenko** [comment]
Implemented in #188
