### ISSUE TITLE
German GUI mistake

### ISSUE THREAD

**Issue by macologe** [glushchenko/fsnotes#638]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, iOS]
 - OS version: [e.g. 10.13.6]
 - FSNotes version [e.g. 3.2.0]

**Additional context**

**Comment by macologe** [comment]
Print (in File menu; German: Datei) should be Drucken (not »Drücken«).

**Comment by glushchenko** [comment]
Thank you, fixed
