### ISSUE TITLE
Move-to-trash command deletes text in editor

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#639]
**Describe the bug**
If the focus is in the editor, and if if I select File > Move > Trash, all text from the cursor position to the beginning of the line is deleted.

**To Reproduce**
1. Place the cursor in the editor.
2. Select File > Move > Trash.

**Expected behavior**
The selected note should be moved to the trash.

**Actual behavior**
All text from the cursor position to the beginning of the line is deleted.

**Workaround**
Place the focus in the Note List before selecting the move-to-trash command.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.5
 - FSNotes version: 3.3.4

**Comment by peavine** [comment]
I installed FSNotes 3.3.6 and this issue is resolved. Thanks.

**Comment by gingerbeardman** [comment]
@peavine fixed!
