### ISSUE TITLE
Search through all folders

### ISSUE THREAD

**Issue by sven-gh** [glushchenko/fsnotes#640]
Is there a way to instantly search through all folders?

When a folder has the setting "Show notes in Notes and ToDO list" disabled
then the CMD+L Search will ignore that folder
unless you point the search directly at the folder or the entire "iCloud Drive".

Is that intentional?

I was expecting to be able to hide notes from the main "Notes" view e.g. certain reference info which you don't want to be looking at all the time so therefore store it away from view - and this works fine

but then when you use the search (CMD+L) without first selecting the folder or the entire iCloud Drive, I was expecting the search to look into all folders (to avoid duplicates and keep everything within reach of a single keyboard shortcut)

**Comment by xRoker** [comment]
Somewhat related: it would be great to be able to search across all notes without selecting the "Notes" first (as it's in Evernote). A shortcut or a setting for a default search behaviour would be nice.

**Comment by glushchenko** [comment]
Implemented long time ago.
