### ISSUE TITLE
iOS What means "iCloud Drive support"?

### ISSUE THREAD

**Issue by helmut72** [glushchenko/fsnotes#641]
What means iCloud Drive support in iOS version exactly?

Can I link every file provider to FS Notes, which is shown in the Files App on iOS? For example Nextcloud, Dropbox, Google drive storage provider...? Means, every user of FS Notes can choose their preferred storage space?

https://www.textasticapp.com/v7/manual/integration_other_apps/external_files_folders.html#add-third-party-file-providers

Or is "iCloud Drive support" only the proprietary storage space from Apple? If yes, when will FS Notes supports common iOS features introduced 2 years ago?

Thank you.

**Comment by glushchenko** [comment]
Hi @helmut72, this feature planned to FSNotes v3.0

**Comment by helmut72** [comment]
Hi @glushchenko, great! Thanks for your information.

**Comment by helmut72** [comment]
Is this now possible with 3.x on iOS? Can I choose any Storage Provider from the Files app (eg. https://secureshellfish.app/) as my storage space/provider for FS Notes?

**Comment by glushchenko** [comment]
Dropbox not working, i think shellfish too. This is only for local files.

**Comment by helmut72** [comment]
Ok, thanks. Misunderstood.

My question is and my link shows a way for a self-hosted sync.
