### ISSUE TITLE
Italic highlighting with parentheses issue

### ISSUE THREAD

**Issue by spencerclrk** [glushchenko/fsnotes#642]
**Describe the bug**
Parentheses are formatted as italic when the parentheses open immediately precedes an italic markdown symbol (`*` or `_`)

**To Reproduce**
`Some text (*test* anything).`

`Sometext (_test_ any test blah blah).`

**Expected behavior**
Syntax highlighting should render a parentheses (*test*) without italicizing the parentheses.

**Supporting Files**
![Screen Shot 2019-07-01 at 11 39 54 AM](https://user-images.githubusercontent.com/10419624/60449243-36c9d300-9bf5-11e9-8f40-34df88ec6ffb.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.5 (18F132)
 - FSNotes version 3.3.4 (270)

**Comment by glushchenko** [comment]
Released in 3.5.0
