### ISSUE TITLE
iOS - cursor gets hidden behind keyboard

### ISSUE THREAD

**Issue by sven-gh** [glushchenko/fsnotes#643]
On iOS the cursor can get hidden behind the keyboard, so you don't see what you type.

Create a note and add some content at the top so the majority of the screen is filled. 
Close the note and open again.
Tap at the bottom of the note to start typing there.
The keyboard appears but the text sometimes gets hidden behind the keyboard.
Easiest way to see / reproduce this is by holding your device in landscape orientation.

**Comment by glushchenko** [comment]
Fixed in 2.8.1
