### ISSUE TITLE
Textexpander support?

### ISSUE THREAD

**Issue by idcrook** [glushchenko/fsnotes#645]
**Describe your feature request**

Is it possible to include Textexpander touch SDK support (from Smile software)?  If not, I'd at least want to record reasoning why not here in the issues list. I searched and did not find it mentioned. 

 it allows text expansion capability, macros, etc. and works with external bluetooth keyboards, e.g.

**Additional context**
- iOS SDK 
https://smilesoftware.com/textexpander-ios/sdk

it seems to be a stable API (latest 4.0 release in 2016), and many other editing and notes apps include it ([apps list](https://smilesoftware.com/textexpander-ios/apps))

on macOS, it works at OS level already.

**Comment by gingerbeardman** [comment]
Just to confirm this is a request for iOS?

**Comment by idcrook** [comment]
> Just to confirm this is a request for iOS?

Correct this would only apply to iOS. 
On macOS, it works at OS system level.

**Comment by stephencweiss** [comment]
@idcrook -- I just opened https://github.com/glushchenko/fsnotes/issues/765 because I couldn't get the system level text expansion to work. 

I suspect the difference is that I was trying to use Apple's variant and you're using the text expansion from Smile. 

Is that correct?

**Comment by idcrook** [comment]
@stephencweiss Textexpander works on macOS at the OS level. and nothing prevents it from performing expansions when using fsnotes on macOS.

Textexpander on iOS requires using either Textpander iOS app custom keyboard or incorporating Smile's API/SDK into app (which also has benefit of being able to work with hardware keyboards on iOS)
