### ISSUE TITLE
On demand sorting of text

### ISSUE THREAD

**Issue by carlca** [glushchenko/fsnotes#646]
macOS 10.14.5
FSNotes 3.0.0

Hello, is there any chance of providing a sort option within the right-click menu to be able to sort lines of text within a particular note. Thanks!

**Comment by gingerbeardman** [comment]
On macOS you can do this with Services.

https://coderwall.com/p/prke1w/sort-lines-of-text-in-any-osx-application

**Comment by carlca** [comment]
Thanks a lot, Matt! I created the service myself and installed your service as well. Both attempts gave errors when I tried to run them...

![Screenshot 2019-07-09 at 20 34 39](https://user-images.githubusercontent.com/260612/60917503-00d9be00-a289-11e9-826d-3bee462edc50.png)

**Comment by carlca** [comment]
It seems to be a problem with the FSNotes app itself. I tried testing the same services in TextMate and it worked perfectly. Any ideas?

**Comment by gingerbeardman** [comment]
Upgrade to latest FSNotes 3.3.5

**Comment by carlca** [comment]
Upgrading to 3.3.5 certainly improved things. However, in the example shown, rather than just sorting the 10 highlighted lines, it also included the 2 extra lines at the end. Not the end of the world, in this case, but a little unexpected, nonetheless!

**Comment by carlca** [comment]
Actually, no it didn't! The spacing of the lines fooled me for a moment. Panic over!

This has been useful. While I am no stranger to diving down to the command-line, I do forget how easy it is to join the more GUI aspects of macOS with the underlying nuts and bolts!
