### ISSUE TITLE
"Use first line as title" on even when not checked in 2.8.0

### ISSUE THREAD

**Issue by erikrose** [glushchenko/fsnotes#648]
**Describe the bug**
Upon upgrading to 2.8.0 from the immediately previous version, note titles are all taken to be the first line of the content. This occurs in both search result listings and in the titlebar when viewing a single note.

**To Reproduce**
1. Install the version previous to 2.8.0.
2. Have "Use first line as title" unchecked for at least some project. (I had it unchecked for all.)
3. Upgrade to 2.8.0.
4. Do a search. All titles in the search results are spuriously the first line of the contents.
5. Check Settings. The option is unchecked everywhere but still seems to take effect.
6. Try turning it on and off. That has no effect.

**Expected behavior**
The filename should still be used as the title.

**Actual behavior**
The first line is always used as the title.

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: iOS
 - OS version: 12.3.1
 - FSNotes version 2.8.0

**Additional context**
Also using on Mac desktop, version 3.3.4 on macOS 10.14.5. Noticed "Use first line as title" was on in macOS app's prefs, even though it's never acted like it was. Turned it off. No change.

Thanks for an eminently useful tool!

**Comment by erikrose** [comment]
Reminds me of #609, but that was apparently fixed in 2.7.0.

**Comment by glushchenko** [comment]
Thanks @erikrose, will be fixed soon

**Comment by erikrose** [comment]
Thank you very much! :-D

**Comment by glushchenko** [comment]
@erikrose please try 2.8.1 from AppStore, thanks
