### ISSUE TITLE
.MDX support and preview 

### ISSUE THREAD

**Issue by taydr** [glushchenko/fsnotes#650]
**Describe your feature request**
.MDX files let you use JSX / React components inline in Markdown. If FSNotes supported .MDX file editing and preview, it would be an incredibly powerful app.

**Additional context**
https://mdxjs.com/

**Comment by gingerbeardman** [comment]
@taydr do you know what files we would need to import to be able to support that rendering?

**Comment by glushchenko** [comment]
No. This is not about Swift
