### ISSUE TITLE
Cannot open links from preview

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#651]
**Describe the bug**
Clicking a URL works while editing but not in the Markdown preview.

**To Reproduce**
1. Create a markdown note
2. Paste an HTTP URL
3. Toggle to preview
4. Click the (blue and underlined) link

**Expected behavior**
Safari opens

**Actual behavior**
Nothing happens.

The context menu of the URL offers "open link", which loads the page in the FSNotes window. Personally I never want that. There also is "open in new window", which does nothing.

**Workaround**
Toggle the preview off and click the URL.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version 3.3.6

**Comment by glushchenko** [comment]
Please try 3.4.2 https://github.com/glushchenko/fsnotes/releases/tag/3.4.2

in MAS soon ...
