### ISSUE TITLE
Switch between Dark mode & Light Mode? 

### ISSUE THREAD

**Issue by MMontelimar** [glushchenko/fsnotes#652]
Is there a simple way to switch between Dark Mode & Light Mode (if there is one?)

**Comment by gingerbeardman** [comment]
Can you confirm macOS or iOS?

(please fill out the full report next time to prevent time wasting questions like this)

**Comment by MMontelimar** [comment]
I'm using macOS. But why not implement an iOS switch as well, to avoid time wasting questions like this entirely.

**Comment by gingerbeardman** [comment]
Please reconsider your conduct with regards to GitHub and this project.

https://github.com/glushchenko/fsnotes/blob/master/CODE_OF_CONDUCT.md

**Comment by MMontelimar** [comment]
Thanks for understanding. I have reviewed the CODE OF CONDUCT and will endeavour to do better in future. I certainly don't mean to waste anyone's time. I only contacted this forum as I didn't see any other means to get the information I was looking for. Thanks again.

**Comment by gingerbeardman** [comment]
The app adheres to the current system dark/light appearance. 

If you want to override this with your choice of appearance you can use a third-party app to specify it per app (this app just takes care of some low level preferences that you could do from the command line if so inclined).

https://github.com/zenangst/Gray

**Comment by MMontelimar** [comment]
Of course. Thank you again. I'm such an idiot. Very helpful.

**Comment by gingerbeardman** [comment]
My pleasure
