### ISSUE TITLE
Attach folders from iCloud drive 

### ISSUE THREAD

**Issue by aahmeti** [glushchenko/fsnotes#654]
**Describe the bug**
Attach a storage from iCloud by using different Applications folders. One can't rename it, they all end up being called 'Documents' and is hard to distinguish which folders you have attached.

**Expected behavior**
One should be able either to rename them, or not all be called Documents. 

**Actual behavior**
Every attached folder from iCloud is called Documents.

**Desktop (please complete the following information):**
 - FSNotes version 3.3.7

**Comment by glushchenko** [comment]
Thanks @aahmeti, fixed
