### ISSUE TITLE
"Inbox" for fsnotes in MacOS

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#656]
**Describe your feature request**
Recently I found out there is an "inbox" for fsnotes (iOS, v2.9.0 b127). It's pretty useful and is showing all the notes not in any folders. It is also the default view when I launch the app.

**Additional context**
Any chance that the MacOS version of fsnotes could get an "inbox" too to show notes not in any folders, and an option to set default view of the app -- now it is using the last view when launching the app. 

Thanks, and keep up the great work!

**Comment by glushchenko** [comment]
Yep, I like this proposal 👌

**Comment by guruprateek89** [comment]
A negative side effect seems to be - pressing Esc to clear a search; then attempting to search on a new keyword now only looks for items within Inbox, forcing me to click on 'Notes' first and then repeat my search.

**Comment by glushchenko** [comment]
@guruprateek89 agree, this will be improved in next release

**Comment by glushchenko** [comment]
@guruprateek89 fixed in 3.4.1

**Comment by guruprateek89** [comment]
Thank you very much for the quick change @glushchenko . Appreciate it!

If I may, while I do like the idea of an 'Inbox' (Im a mac-only user) my preference would be to make 'Notes' the default view (or have an option to make it the default). 
I've gotten so used to seeing a list of my most recently edited files when I press Esc. Also, pinned notes are now only visible when I specifically select 'Notes' which imo doesn't make them pinned anymore.

**Comment by glushchenko** [comment]
In FSNotes 4.1.2 you can hide Inbox.
