### ISSUE TITLE
Sorting order of the notes

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#657]
**Describe the bug**
In the MacOS version of fsnotes:
In the sidebar, right click on a folder, and select "view setting". Then sorting notes by title would have those beginning with "a" at the bottom; sorting notes by date (modification or creation) would have those with the latest date at the bottom.

This is also true for using the global setting (in the menu bar, view -> sort by)

**To Reproduce**
see above.

**Expected behavior**
It's sorted in normal order (i.e. first at the top). 

**Actual behavior**
It is in reverse order.

**Workaround**

**Supporting Files**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6, iOS 12.3.1
 - FSNotes: MacOS: 3.3.7 (273), iOS 2.9.0, build 127

**Additional context**
Apple note and iOS version of fsnotes are doing it as stated in the expected behavior.

**Comment by glushchenko** [comment]
Fixed and now in project settings you can disable sort by and select direction (ascending/descending). Thanks for patience

**Comment by jakemkc** [comment]
Just a note to share with the community:

I am using MacOS FSnotes 3.4.2 (281). I found that if I go to "view" ➙ "sort by" ➙ "creation date", notes are sorted, say, in ascending order. If you repeat the above steps, the notes are sorted in descending order.

**Comment by glushchenko** [comment]
Released in 3.5.0
