### ISSUE TITLE
fsnotes crashing as soon as focus placed in any note

### ISSUE THREAD

**Issue by davejonesstl** [glushchenko/fsnotes#658]
**Describe the bug**
Every time I open fsnotes and move focus onto the editing area of a note, fsnotes crashes. It happens for any note I choose, and whether I click on the body of the note with the mouse or tab into it. It's basically made it into read-only mode for me.

**To Reproduce**
1. Open fsnotes
2. Click on the title of any note in the list. Note displays in the panel on the right.
3. Click on the body of the note on the right.
4. fsnotes crashes

Fails with ANY note I have (dozens, not hundreds).

**Expected behavior**
When clicking on the body of any note, the focus should stay in the note, app shouldn't crash, and I can edit at will.

**Actual behavior**
fsnotes crashes with putting focus in the editor.

**Workaround**
Since the files are in plain text, I can edit them using any other editor. That basically means fsnotes is read-only mode for me.

**Supporting Files**
OSX crash dump info is attached.

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS version: 10.13.6
 - FSNotes version: 3.3.8

**Additional context**
I'm on 3.3.8 now, but it happened in the prior version I was running as well (3.something - can't remember).

[fsnotes-crash-log.txt](https://github.com/glushchenko/fsnotes/files/3483894/fsnotes-crash-log.txt)

**Comment by gingerbeardman** [comment]
Have you tried with zero notes?

**Comment by davejonesstl** [comment]
> Have you tried with zero notes?

I tried this also:
1. Changed fsnotes settings to point to a different directory
2. Deleted the 3 default notes that were created for me
3. fsnotes crashed again before I could even create another note
4. Start fsnotes and it crashes before the window even comes up

My notes folder name is ~/Documents/notes, and I also tried this:
1. Recreate bug again and let fsnotes crash
2. mv notes notes-backup
3. mkdir notes
4. Start fsnotes
5. Observe the 3 default notes that fsnotes creates
6. Click on the body of any of the notes
7. Watch fsnotes crash again.

Also tried this:
1. brew cask uninstall fsnotes
2. brew cask install fsnotes
3. Open fsnotes
4. Click on the body of any note
5. fsnotes crashes

Certainly seems like there's some poison in my laptop somewhere since this isn't a widely reported problem. I'll keep playing around to try to narrow down the problem more.

For whatever reason, github didn't show me the template when I first created this bug, but I edited it to provide the info the best I could. I wasn't trying to be lazy - I didn't see the template the first time. My bad.

**Comment by gingerbeardman** [comment]
No problem. Thanks for the details. 

Have you tried the latest version of FSNotes from the release page?

And have you tried installing using AppCleaner?

**Comment by davejonesstl** [comment]
I tried the latest version from the release page. Still crashes. 3.2.0 seems to work fine though.

I do have a MBP with Touch Bar.

I have not tried uninstalling with AppCleaner yet.

**Comment by gingerbeardman** [comment]
Thanks!

My feeling is that this is related to Touch Bar support that was added in 3.3.1

Can we get any closer with a bisect? What about testing 3.3.0 and 3.3.1?

**Comment by glushchenko** [comment]
> My feeling is that this is related to Touch Bar support that was added in 3.3.1

May be, may be. High Sierra installation in process. We should fix that

**Comment by gingerbeardman** [comment]
I only just upgraded to Mojave (but I do not have a Touch Bar)

**Comment by glushchenko** [comment]
@davejonesstl please try experimental build:

[FSNotes.zip](https://github.com/glushchenko/fsnotes/files/3488583/FSNotes.zip)

**Comment by glushchenko** [comment]
@davejonesstl any news?

**Comment by davejonesstl** [comment]
The experimental build 3.3.8 (274) works perfectly so far. Thanks for the quick responses!

Let me know if you need me to try anything else.
