### ISSUE TITLE
Disabling "First line as title" has no effect (3.3.8)

### ISSUE THREAD

**Issue by eddyg** [glushchenko/fsnotes#659]
**Describe the bug**
Turning off "First line as title" pref does not have any effect.

**To Reproduce**
1. Go to **Preferences...**
2. Click on **Layout**
3. Uncheck **First line as title**
4. Filenames do _not_ appear

**Expected behavior**
Should show filenames and not first line of the note.

**Actual behavior**
FSNotes shows the first line of the note all the time, even when searching. Also tried restarting, but it didn't make any difference. (For what it's worth, toggling **Hide date** works as expected.)

**Workaround**
None that I know of.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.5
 - FSNotes version: 3.3.8

**Comment by glushchenko** [comment]
Right click on project -> View settings -> Deselect "First line as title". This settings synced with iOS app.

![image](https://user-images.githubusercontent.com/1089917/62943082-58b49900-bde2-11e9-9fb6-57cff5484112.png)

![image](https://user-images.githubusercontent.com/1089917/62943058-46d2f600-bde2-11e9-8dac-d25d7c48603e.png)

**Comment by eddyg** [comment]
Thanks.

At first I didn't think this worked either, because after I _unchecked_ the **Use first line as title** option and clicked **Close**, nothing happened. But after quitting and restarting FSNotes, I see the filenames. 👍

**Comment by glushchenko** [comment]
Thats fixed on GitHub release 3.4.0, now settings updated right after click
