### ISSUE TITLE
Text selection in preview mode

### ISSUE THREAD

**Issue by Xiao6** [glushchenko/fsnotes#662]
**Describe your feature request**
Current released version macos 3.3.8 doesn't support selection of text in markdown preview mode.

When I have really long markdown note, I preview to view it in preview mode, then copy some useful texts. This can be achieved in many editor or note app even in nvalt, but cannot do this in FSNotes.

Current workaround is to use Typora or Marked as external editor. Open markdown, then preview and copy via 3p apps.

**Comment by Ayad0net** [comment]
I need this feature

**Comment by glushchenko** [comment]
Already done, will be available in 3.4.2

**Comment by Ayad0net** [comment]
Thanks a lot, ^_^

**Comment by glushchenko** [comment]
Please try 3.4.2 https://github.com/glushchenko/fsnotes/releases/tag/3.4.2

in MAS soon ...

**Comment by Ayad0net** [comment]
I tried it, it's worked awesome.
