### ISSUE TITLE
 fuzzy search support

### ISSUE THREAD

**Issue by Xiao6** [glushchenko/fsnotes#663]
**Describe your feature request**
Is there any plan to support fuzzy search? I didn't find existing issue, so create new one.
It seems FSNotes only support extract match search.

Fuzzy search is very helpful for markdown notes.
One Example:
markdown txt: `This is my **first** note.`
If search `my first note` under extract match, I get no matching. But fuzzy search will return the above txt.

Probably not MVP, but nice to have feature.

**Additional context**
MacOS.

Other note apps support fuzzy search: Quiver, notable

**Comment by glushchenko** [comment]
Example from issue works fine for me, seems it fixed long time ago.
