### ISSUE TITLE
Default display option in iOS ( Edit mode - Preview mode)

### ISSUE THREAD

**Issue by Ayad0net** [glushchenko/fsnotes#665]
Please add an option in the setting menu to choose which mode used when opening a file in iOS.

- If the selected option is preview => then always open file in the preview mode (then switch to edit mode if we want to do that).

- if the selected option is edit => then always open file in edit mode (then switch to preview mode if we want to do that).

**Comment by glushchenko** [comment]
Improved in FSNotes 4 for iOS
