### ISSUE TITLE
Mac App Store version has a trailing dot 

### ISSUE THREAD

**Issue by core-code** [glushchenko/fsnotes#668]
the Mac App Store version has the version "3.5.0." with a trailing dot instead of "3.5.0"

<img width="1112" alt="Screenshot 2019-08-22 at 11 10 46" src="https://user-images.githubusercontent.com/1261954/63502732-72cf3500-c4ce-11e9-9f9c-89906e9c6248.png">

**Comment by glushchenko** [comment]
Sorry for this mistake, next release will be without dot at the end
