### ISSUE TITLE
Search on iOS comes up empty

### ISSUE THREAD

**Issue by erikrose** [glushchenko/fsnotes#669]
**Describe the bug**
Search on iOS shows no results unless you manually select a sidebar item. This makes my main way of opening notes much slower.

**To Reproduce**
1. Quit FSNotes to get a fresh start.
2. Force-touch on the FSNotes icon. Pick Search from the resulting menu.
3. Type a word which appears in one or more of your notes.
4. The search results are empty. 

**Expected behavior**
I expected the note containing the search term to show. 

**Actual behavior**
No notes are listed in the search results. Upon examining the sidebar, I see that no sidebar items are selected. I would expect Search to default to selecting Notes, which can be set up to be a union of all available notes. After all, searching in *no containers* is useless.

**Workaround**
Boggle for a moment, then slide the sidebar open, tap Notes, and slide it closed again.

**Desktop (please complete the following information):**
 - OS: iOS
 - OS version: 12.4
 - FSNotes version: 2.9.0

**Comment by glushchenko** [comment]
Thanks @erikrose, same behavior fixed early in macOS app.

**Comment by glushchenko** [comment]
Fixed. We have to be patient while the Apple starts accepting updates for FSNotes iOS. All iOS updates currently rejected by shitty App Store Team. And I don't know when investigation will be finished

**Comment by erikrose** [comment]
Wow, thanks for the quick patch! :-D I'll look forward to the review succeeding, whenever it does.
