### ISSUE TITLE
Let Titlebar Inherit Note Background

### ISSUE THREAD

**Issue by manspeterson** [glushchenko/fsnotes#671]
**Describe your feature request**
I would prefer/except the note titlebar to inherit the user defined note background and not stay white/dark. 

**Additional context**
See example image below for current behavior. I believe this change will make it less distracting and look more polished. The titlebar of the note list could/should stay as is (white/dark) as it is always divided from the note content with a line. 

![59aaab65-7aaa-4f0b-b48c-5156bb818630](https://user-images.githubusercontent.com/9446455/63581931-5ef00580-c598-11e9-983f-5dbd996db90d.jpg)

**Comment by glushchenko** [comment]
Thanks, fixed

**Comment by manspeterson** [comment]
wow, that was fast! Thank you!
