### ISSUE TITLE
Terminological consistency proposal

### ISSUE THREAD

**Issue by alex-kovac** [glushchenko/fsnotes#674]
**Describe your feature request**
Right-clicking Storage name in project area offers menu:

- New folder
- Rename folder
- Reveal folder
- Delete folder
- View settings

Since the main menu 'Folder' has command 'Attach storage...' I propose that context menu here should use 'storage' and concept of 'attaching' to keep the consistency. Right-clicking on Storage name in project area would then offer:

- New folder
- Rename folder _(see add. below)_
- Show in Finder
- Detach storage
- Show view options

ADD. 'Rename folder' does not seem to function when right-clicking on storage name, or I am doing something wrong.

**Additional context**
General context.

EDIT 1: Changed 'View settings' to 'Show view options' to be more aligned with Finder's similar function (perhaps standard strings make translation easier?)
EDIT 2: Changed 'Reveal storage in Finder' to 'Show in Finder'. I found the latter to be standard in Apple's apps . E.g. FontBook, iTunes... (perhaps it makes translating easier, too?)

THNX for making FSNotes!

**Comment by glushchenko** [comment]
Thank you, will be fixed in next release
