### ISSUE TITLE
FSNotes crashes on start

### ISSUE THREAD

**Issue by alex-kovac** [glushchenko/fsnotes#675]
**Describe the bug**

**To Reproduce**
1. doubleclick on FSNotes icon to start it.

**Expected behavior**
fsnotes running stable.

**Actual behavior**
Less than a second after starting fsnotes it crashes with 'FSNotes quit unexpectedly ... Ignore/Report.../Reopen' dialog box.

**Workaround**
Not known. Happens as soon as FSNotes is started.

**Supporting Files**
Crash report attached.
[fsnotes 3.6.1 crash report.txt](https://github.com/glushchenko/fsnotes/files/3582863/fsnotes.3.6.1.crash.report.txt)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version 3.6.1

**Additional context**
Not aware of. I did notice that the line spacing in 3.6.0 and 3.6.1 is tighter than what I set before. I can start 3.6.0 normally, but setting line spacing did not work (perhaps this should be a separate issue).
- Add. info 1 : FSNotes uses preferences Container: None, Format: Markdown.
- Add. info 2 : was using iAWriterQuatroS Regular font. Replaced it with system's Courier. No improvement.
- Add. info 3 : Removed storages except the default one. No improvement.
- Add. info 4 : Using AppCleaner, removed FSNotes by marking for removal all of the files offered for removal. Installed fresh 3.6.1 from zip. Works! --- Then, set in preferences 'My Notes' folder located in iCloud that contains my .md notes... Crash.

XL thanks for your magic!

**Comment by glushchenko** [comment]
Thanks, i will try to fix it ASAP

**Comment by glushchenko** [comment]
Can you attach a file which crashes FSNotes?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Crash seems to be in system. AppKit Event message dispatch/receive.

**Comment by glushchenko** [comment]
@gingerbeardman you can reproduce it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
No, works for me.

**Comment by alex-kovac** [comment]
Additional info included in the original report.

- @glushchenko Using 3.6.0 I would select another file (so that this file shows-up in 3.6.1 when started): no improvement.

If there is anything I could share to contribute to resolving this, just let me know.

Thanks again & thank you for lightning fast response.

**Comment by alex-kovac** [comment]
I might be onto something. One subfolder in 'My Notes' folder seems to crash FSNotes, while others do not. Might be on my side... I will try to find the reason...

**Comment by gingerbeardman** [comment]
Please try to narrow down and post offending text/file so we can repro and fix.

**Comment by alex-kovac** [comment]
@gingerbeardman ...this file I could positively use to crash FSNotes 3.6.1:
[Klasifikacija djelatnosti za Kovačnica j.d.o.o..md.zip](https://github.com/glushchenko/fsnotes/files/3583756/Klasifikacija.djelatnosti.za.Kovacnica.j.d.o.o.md.zip)
Is it working for you?

I would start with a fresh FSNotes installation. Then, select an empty folder for notes location. Turn off FSNotes. Using Finder, I would add and remove .md files to this folder with no problem. Once this file was added - crash. 

## Observations: 
- [Macdown](https://github.com/MacDownApp/macdown) app opens this file OK.
- Once nested bullet levels were removed, the file will not crash FSNotes (see below for nested bullet level example)
- Adding nested bullet levels in FSNotes does not seem to crash FSNotes. (but incorrectly formats 2nd and higher bullet levels as code)
- Once FSNotes would crash it would not matter anymore if this file is in the folder or not. FSNotes would keep crashing. Removing FSNotes completely using AppCleaner and reinstalling would make FSNotes work again.
- Along the way I have noticed that Toggle Preview keystroke and menu entry are not working. Again, it might just be me.

---

## Nested bullet example:

- Level 1
[TAB] - Level 1.1
[TAB][TAB] - Level 1.1.1

Thank you

**Comment by gingerbeardman** [comment]
I do not have time to test today, as I'm working, but thanks for narrowing it down!

**Comment by gingerbeardman** [comment]
OK, I could not resist.

Adding the file to my FSNotes folder resulted in crash. Different looking crash logs than yours: 

1. seems to be crashing trying to display UTF.
[crash.txt](https://github.com/glushchenko/fsnotes/files/3583933/crash.txt)

2. maybe out of bounds access?
[crash2.txt](https://github.com/glushchenko/fsnotes/files/3583955/crash2.txt)

Removing the file and my FSNotes was back to normal.

**Comment by alex-kovac** [comment]
Don't take risks. It is not that important :)

**Comment by gingerbeardman** [comment]
All my data was safe, no problem! :)

**Comment by glushchenko** [comment]
Guys, please try a new fixed build https://github.com/glushchenko/fsnotes/releases/tag/3.6.2

**Comment by gingerbeardman** [comment]
Fixed for me.

But spotted another issue (unrelated or not?)

**Comment by alex-kovac** [comment]
Fixed for me, too. Also, the smaller issues mentioned above: line spacing, preview toggle, etc. are gone after Mac reboot.
That was a fast fix deliver! My admiration.

Thank you both!
