### ISSUE TITLE
Line Spacing preference is ignored since 3.6.0

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#676]
**Describe the bug**
Line hight is ignored

**Supporting Files**
Two screens with same preference setting:
![Screen shot 2019-09-06 at 15 20 22](https://user-images.githubusercontent.com/49612/64435144-de61f680-d0b9-11e9-9709-9787591d6dfa.png)

3.6.2 || 3.6.1 || 3.6.0
![Screen shot 2019-09-06 at 14 52 53](https://user-images.githubusercontent.com/49612/64434624-d786b400-d0b8-11e9-9a06-c0846c08f810.png)

3.5.0
![Screen shot 2019-09-06 at 15 20 55](https://user-images.githubusercontent.com/49612/64435224-ff2a4c00-d0b9-11e9-8404-2a6f996108af.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version 3.6.2

**Additional context**
3.6.2 = bad
3.6.1 = bad
3.6.0 = bad
3.5.0 = OK

**Comment by glushchenko** [comment]
Fixed, please re-download 3.6.2 build 291

**Comment by gingerbeardman** [comment]
Works for me! Thanks
