### ISSUE TITLE
Add markdown WYSIWYG editor

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#678]
**Describe your feature request**
It would be great to have a WYSIWYG markdown editing mode, where you don't have to see (and work with) the raw markdown.

Examples of this:
*  [typora](https://typora.io)
* [Slate](https://github.com/ianstormtaylor/slate)
* [Toast UI](https://nhn.github.io/tui.editor/api/latest/tutorial-example02-editor-basic.html)

Something like this might also have the benefit of rendering the current RTF support redundant. I for one would be more than willing to convert my entire library from rtf to markdown if I didn't have to edit my notes as though I was using [Wordstar](https://en.wikipedia.org/wiki/WordStar) 🙄 As a programmer, personally the last thing I want to be doing is editing even my notes' source code lol

**Comment by ccmcbeck** [comment]
I can certainly see your point. It would give the product broader appeal for those who don't know (or don't want to know) markdown but want the benefits of richer formatting.  OTOH, _as a programmer_ I love the fact that I can see and edit the source code both in FSNotes and in my external programming editor.
