### ISSUE TITLE
Want to use cmd+J

### ISSUE THREAD

**Issue by JesseAldridge** [glushchenko/fsnotes#68]
I want the shortcut to bring fsnotes to the front to be cmd+J because that's what I used with Notational Velocity and I have strong muscle memory for it.  But when I try to set it in fsnotes I get a popup saying:   "This shortcut cannot be used because it is already used by the menu item ‘Jump to Selection’."  I want to override that and do it anyway.

Not crticial obviously as I can just learn a new shortcut.

**Comment by glushchenko** [comment]
Implemented in 1.1.5
