### ISSUE TITLE
[REQ] Revised/tweaked app icon for v4?

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#681]
**Describe your feature request**
So we're closing in on V4 and I thought we could refine the icon in the ways we didn't have time to for V3. 

So, less of a complete overhaul like we had going from V2 to V3 and more of a refinement to suit grown up FSNotes?

**Additional context**
This is what we have right now.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/49612/64609140-220f7580-d3c4-11e9-9f62-431acf02bb75.png">

**Comment by peavine** [comment]
For people who weren't around at the time, and just for background, the following is the disucssion of the FSNotes version 3 icon. 

https://github.com/glushchenko/fsnotes/issues/477

**Comment by glushchenko** [comment]
Ohhh, new thread about icon 🤪 Guys, i dont understand anything in icons design, so please, without me :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jeff-h** [comment]
Personally, compared to the app icon, I think there's an elephant in the room, or more specifically in the preferences... 🙈

**Comment by gingerbeardman** [comment]
> Personally, compared to the app icon, I think there's an elephant in the room, or more specifically in the preferences... 🙈

Good point. Let's make a thread about improving the prefs interface.

**Comment by alex-kovac** [comment]
Brainstormlet: usabilitywise... this thing's preferences: https://iina.io/ ... Oui!

**Comment by gingerbeardman** [comment]
If @glushchenko is up for this I will action it, using @alex-kovac approach and Apple Human Interface Guidelines document.

**Comment by glushchenko** [comment]
Thanks @alex-kovac 

Guys, more polished menu bar and dock icons from @keymasterr available in 3.8.0. I completely forgot about.

**Comment by alex-kovac** [comment]
Menu bar icon looks fabulous!

**Comment by gingerbeardman** [comment]
Sweet!

**Comment by peavine** [comment]
Since keymasterr's icon has been settled on, I wondered if the icon option in advanced preferences should be removed. It clutters that preference page and selecting the yellow-thunderbolt icon only changes the icon shown in the dock.

**Comment by gingerbeardman** [comment]
I agree. 

Simplify, simplify, simplify.
