### ISSUE TITLE
I added the Simplified Chinese Language Pack for mac, but there are some things that can't be displayed properly!

### ISSUE THREAD

**Issue by cdwmhcc** [glushchenko/fsnotes#682]
**Describe**
I added the Simplified Chinese Language Pack, but there are some things that can't be displayed properly. How can I operate it?

**Additional context**

![image](https://user-images.githubusercontent.com/8030134/64711073-a4df2000-d4eb-11e9-8f05-1cd55e63c043.png)

![image](https://user-images.githubusercontent.com/8030134/64711105-b0cae200-d4eb-11e9-81f8-bf437cf51770.png)

![image](https://user-images.githubusercontent.com/8030134/64711130-bd4f3a80-d4eb-11e9-8f56-7c190c243e70.png)

![image](https://user-images.githubusercontent.com/8030134/64711158-c5a77580-d4eb-11e9-9635-3b11648eaa3d.png)

![image](https://user-images.githubusercontent.com/8030134/64711190-ce984700-d4eb-11e9-86dc-5c7e551b9ae8.png)

![image](https://user-images.githubusercontent.com/8030134/64711217-d8ba4580-d4eb-11e9-8814-299b47f4b7fb.png)

![image](https://user-images.githubusercontent.com/8030134/64711399-1d45e100-d4ec-11e9-9bd0-313dadfa7744.png)

![image](https://user-images.githubusercontent.com/8030134/64711351-08694d80-d4ec-11e9-9eb2-fdc3c57a1d07.png)

**Comment by glushchenko** [comment]
Can you provide pull request?

**Comment by cdwmhcc** [comment]
> Can you provide pull request?

![image](https://user-images.githubusercontent.com/8030134/64750381-56fa0480-d54b-11e9-8cf7-f411c8877257.png)

I modify these two files directly and don't know how to add other languages.

**Comment by glushchenko** [comment]
[zh-Hans.xliff.zip](https://github.com/glushchenko/fsnotes/files/3610396/zh-Hans.xliff.zip)

All non empty string should be filled. You can use XLIFFTool https://remuslazar.github.io/osx-xliff-tool/

**Comment by cdwmhcc** [comment]
> [zh-Hans.xliff.zip](https://github.com/glushchenko/fsnotes/files/3610396/zh-Hans.xliff.zip)
> 
> All non empty string should be filled. You can use XLIFFTool https://remuslazar.github.io/osx-xliff-tool/


Thank you very much, I am going to sleep, I will send it to you tomorrow. The guarantees are all accurate.

**Comment by gingerbeardman** [comment]
App link: https://apps.apple.com/gb/app/xlifftool/id1074282695?mt=12

**Comment by cdwmhcc** [comment]
> App download: https://apps.apple.com/gb/app/xlifftool/id1074282695?mt=12

Wow, I use Xliff Editor,haha.

**Comment by cdwmhcc** [comment]
Source | Target | notes
------------ | -------------
Attach storage | 附加存储 | I don't quite understand. I need to know what it can do.
Archive storage | 存档存储 | I don't quite understand. I need to know what it can do.
Back up storage | 备份存储 | I don't quite understand. I need to know what it can do.
 Set|  |  Is this a setup or a collection? I need to know what it can do.
hour at |  | Does it mean:『sometime』?
Automatic snapshots |  | Does it mean: 『Auto Save』 ?
Default Keyboard On Edititng |  | Does it mean:  『input method』?
2/23/11 |  | What's the meaning of this?
2/23/11 |  | What's the meaning of this?


[zh-Hans.xliff.zip](https://github.com/glushchenko/fsnotes/files/3612518/zh-Hans.xliff.zip)

**Comment by glushchenko** [comment]
1. Attach storage - adds multiple folders.
2. Back up storage - commits all files in Git repository.
3. hour at - every N hours on XX minute of hour.
4. Set - setup font.

Another strings not important

**Comment by cdwmhcc** [comment]
> 1. Attach storage - adds multiple folders.
> 2. Back up storage - commits all files in Git repository.
> 3. hour at - every N hours on XX minute of hour.
> 4. Set - setup font.
> 
> Another strings not important

1、Attach storage - 添加多个文件夹.
2、Back up storage - 提交git的存储库中的所有文件.
3、hour at - every N hours on XX minute of hour. （This is not easy to translate. I will not translate it for the time being.）
4、Set - 设置字体.
5、Code span - 单行代码 (The translation between is wrong and needs to be changed to this.)


![image](https://user-images.githubusercontent.com/8030134/64928926-55815280-d851-11e9-88d6-baa3290408ce.png)

**Comment by cdwmhcc** [comment]
![image](https://user-images.githubusercontent.com/8030134/64929073-b578f880-d853-11e9-8546-aa6262b48e1f.png)

Both of these are Chinese, but there are many differences.
I am offering Chinese Simplified, which is used by more than 95% of Chinese people.
The other is traditional Chinese, only used in Taiwan, China.

**Comment by glushchenko** [comment]
Thank you, @cdwmhcc for awesome work. I make dev build, please check this: 

[FSNotes_3.8.0_dev.zip](https://github.com/glushchenko/fsnotes/files/3614989/FSNotes_3.8.0_dev.zip)

**Comment by cdwmhcc** [comment]
@glushchenko 

## Need correction

Source | Target | notes
------------ | ------------- | -------------
Open | 外部打开 | 
Default storage: | 默认存储位置: | 
Line width: | 内容区宽度 | 
Focus in editor when selecting note: | 当选中笔记时编辑器自动聚焦（笔记内容区处于编辑状态） | 
Show in Terminal: | 在终端中打开: | 
Show in Terminal: | 在终端中打开: | 

## Not sure.
> I tried the following two shortcuts, but they are not the same as the actual performance and words.

Source | Target | notes
------------ | ------------- | -------------
Search shortcut: | 搜索快捷键: | 
Save clipboard shortcut: | 保存到剪贴板快捷键 | 

## Questions and BUG

#### 1、Not translated

<img width="696" alt="Xnip2019-09-16_17-09-42" src="https://user-images.githubusercontent.com/8030134/64947052-c69f2500-d8a6-11e9-890c-e7045bf2d43d.png">

<img width="467" alt="Xnip2019-09-16_17-03-57" src="https://user-images.githubusercontent.com/8030134/64947112-e3d3f380-d8a6-11e9-992e-84b29701aa3f.png">

<img width="446" alt="Xnip2019-09-16_16-46-35" src="https://user-images.githubusercontent.com/8030134/64947134-f2baa600-d8a6-11e9-94f4-d34fb6c95ac7.png">

#### 2、Unable to quit, unable to close
<img width="573" alt="Xnip2019-09-16_16-56-12" src="https://user-images.githubusercontent.com/8030134/64947170-0403b280-d8a7-11e9-90fa-3d0768b2f238.png">

#### 3、Not aligned with the checkbox
<img width="833" alt="Xnip2019-09-16_16-46-16" src="https://user-images.githubusercontent.com/8030134/64947220-1b42a000-d8a7-11e9-9ea4-c5cbe020c731.png">

#### 4、Not fully displayed

<img width="457" alt="Xnip2019-09-16_17-08-05" src="https://user-images.githubusercontent.com/8030134/64947288-40cfa980-d8a7-11e9-9e18-10a36f0b9279.png">

#### 5、I don't know what function it is.
> Markdown Preview CSS:

<img width="478" alt="Xnip2019-09-16_17-08-21" src="https://user-images.githubusercontent.com/8030134/64947324-547b1000-d8a7-11e9-93ed-50ac3ea6f455.png">

## XXXXXXXXXXXX

Apart from these, no more problems have been found so far.

Thank you, 
I love FSNotes.

**Comment by glushchenko** [comment]
Thanks, will be available soon on GitHub and MAS.
