### ISSUE TITLE
Note is rendering with lines in the wrong location

### ISSUE THREAD

**Issue by bnham** [glushchenko/fsnotes#683]
**Describe the bug**
While editing my note, especially when using automatically bulleted lists, the view of the note becomes corrupted and random lines and characters are inserted in the wrong place. Note that the backing storage of the note appears to be fine on disk. It's just the view of the note in the UI that's incorrect.

![fsnotes-corrupt](https://user-images.githubusercontent.com/54685347/64720997-809a2980-d480-11e9-81e0-dd75d8327b2d.png)

For instance, see the attached screenshot. On the left is the note on disk as seen by TextEdit. The last line says "Client initiates DH key exchange" in the actual text file. However, in FSNotes on the right, you can see that the view actually shows "Client initiates DH key - Attach" as if the string has been inserted into the buffer in the wrong place.

I've also attached the note I was editing. Try editing it and adding some new bullet points to the note. Eventually the editing view starts mangling the text as I've described above: [high-perf-browser-networking.txt](https://github.com/glushchenko/fsnotes/files/3602068/high-perf-browser-networking.txt).

I am seeing this in FSNotes 3.6.2 (293).

**To Reproduce**
1. Edit the attached long note. Try adding bullet points, code blocks, and other elements that trigger the text view to do complicated insertions
2. Eventually the text view becomes out of sync with the actual text file on disk and it looks like strings are inserted into incorrect locations in the text view.

**Expected behavior**
The text view should accurately reflect the text file on disk.

**Actual behavior**
The text view goes out of sync with the text file on disk and some of the text in the view is mangled.

**Workaround**
Haven't found any workarounds yet.

**Supporting Files**
See summary for a screenshot and example long text file.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6 (18G87)
 - FSNotes version: 3.6.2 (293)

**Comment by glushchenko** [comment]
Thanks, i will try to reproduce

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glushchenko** [comment]
Anyone can reproduce this?

**Comment by alex-kovac** [comment]
I was not able to reproduce the reported issue.

**Comment by gingerbeardman** [comment]
Cannot reproduce.

Can we get a smaller reproducible document or specific series of steps @bnham ?

**Comment by bnham** [comment]
I'll try--I've noticed this in several different notes over the past few weeks, but there doesn't seem to be any particular rhyme or reason to when it occurs.

If there are some methods in particular that are useful to log for insertion into the text view, I can also try building the app and adding some log lines to see if I can figure out what's going on.

**Comment by glushchenko** [comment]
@bnham please try FSNotes 3.7.1

**Comment by bnham** [comment]
The crash and inability to edit the doc no longer occurs in 3.7.1 for me. I am actually still sometimes seeing random line breaks being inserted into the buffer when using bulleted lists but it seems better than before. Maybe I should close this and reopen when I find a better repro case for that?

**Comment by glushchenko** [comment]
Yes, please provide steps for reproduce and i fix that. Thank you for feedback 👍🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glushchenko** [comment]
Yes, please provide steps for reproduce and i fix that. Thank you for feedback 👍🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
