### ISSUE TITLE
Incorrect italics when text surrounded by bolded text

### ISSUE THREAD

**Issue by dnowacki-usgs** [glushchenko/fsnotes#685]
**Describe the bug**
Text becomes italicized when a character other than a space immediately follows bolded text in a Markdown document:

<img width="471" alt="Screen Shot 2019-09-12 at 8 12 13 PM" src="https://user-images.githubusercontent.com/13837821/64835147-a23b0400-d599-11e9-99b0-5d01d05e07bc.png">

**To Reproduce**
1. Create new note
2. Write text which is bolded, add a character other than space immediately after the bolded text, and then bold more text.
3. The text between the bolded text is in italics, and should not be
4. Removing the non-space character removes the italics

**Expected behavior**
Should be normal text not italics

**Actual behavior**
Text is italicized

**Supporting Files**

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version 3.7.0

**Comment by gingerbeardman** [comment]
Good catch!

**Comment by glushchenko** [comment]
Fixed
