### ISSUE TITLE
3 tilde for Code Block doesn't work in 3.7.1

### ISSUE THREAD

**Issue by helmut72** [glushchenko/fsnotes#686]
**Describe the bug**
3 tilde for Code Block doesn't work in 3.7.1

**To Reproduce**
Try to type 3 tilde

**Expected behavior**
Just see 3 tilde.

**Actual behavior**
2 tilde was typed, then Cursor jumps down a line

**Workaround**
CMD-C 3 tilde, CMD-V, CMD-V, CMD-V ... 

**Desktop (please complete the following information):**
 - OS: macos 10.15 latest Beta

**Comment by glushchenko** [comment]
Seems this is Catalina autocorrection:

I can not test it at this moment, but i am recommend use shortcut fo code block - control - command - c.

You can select text and press control- command - c too.

**Comment by helmut72** [comment]
Autocorrection is disabled, one of the first tasks when configuring a system. I try to get used of ctrl-cmd-c, but it's not there on other editors.

**Comment by helmut72** [comment]
Looks like it's fixed at least in FS Nots 4.0.2 and 4.0.3.

Never changed any keyboard preferences since then. Only updated FS Notes to 4.x and macOS to 10.15.1.
