### ISSUE TITLE
FSNotes Crashing

### ISSUE THREAD

**Issue by neilscott** [glushchenko/fsnotes#687]
Editing notes and FSNotes crashes.

Here is what the crash report says:

> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSBigMutableString characterAtIndex:]: Index 18446744073709551615 out of bounds; string length 9'
> abort() called
> terminating with uncaught exception of type NSException

**Comment by glushchenko** [comment]
FSNotes version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by neilscott** [comment]
3.7.0 (303)

**Comment by glushchenko** [comment]
Already fixed https://github.com/glushchenko/fsnotes/releases/tag/3.7.1

**Comment by neilscott** [comment]
Thanks! I am getting updates from AppStore so will wait for it to auto-update.

**Comment by glushchenko** [comment]
App Store Team lazy and slow, sorry fo that :(

**Comment by glushchenko** [comment]
3.8.0 available in Mac App Store!
