### ISSUE TITLE
Preferences UI Sketching 

### ISSUE THREAD

**Issue by alex-kovac** [glushchenko/fsnotes#688]
Preferences interface quick'n'dirty sketch. Following mention in #681 
...most likely obvious/silly/too late/all of the above:

**General preferences**
![General](https://user-images.githubusercontent.com/174563/65060106-91aed300-d977-11e9-9867-2d4b946aa7ba.png)

**Editor preferences**
![Editor](https://user-images.githubusercontent.com/174563/65061061-6331f780-d979-11e9-8b32-6a5189fdfed2.png)

**Storage preferences**
![Storage](https://user-images.githubusercontent.com/174563/65060115-96738700-d977-11e9-93a3-ec9d9c87d0e5.png)

**Security preferences**
...remain the same.

**Comment by alex-kovac** [comment]
Caveat for the sketches above:
1. Some freedoms were exercised to conflate controls (e.g. 'show previews' and 'note spacing' became 'Note preview' drop-down). 
2. Archiving I do not use/understand completely...
3. Errors are likely. 

Thank you for making FSNotes!

**Comment by gingerbeardman** [comment]
I'm liking this!

**Comment by alex-kovac** [comment]
Edits for the UI proposal above:

in Editor/Text:
- Line width in points would be clearer with 'points max.' instead of just 'points'
- Side margins in points would be clearer with 'points min.'

in General/Note list:
- 'Image thumbnails' checkbox label should probably say 'Show image thumbnails'
- 'Dates' checkbox label should probably say 'Show dates'

**Comment by glushchenko** [comment]
You can always open a PR
