### ISSUE TITLE
Easier nesting of lists using tab to indent current line?

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#689]
**Describe your feature request**
Is it possible to press (TAB) on a new list item to indent it?

so:
```md
- Parent(enter)
- (tab)
```

gives:
```md
- Parent
	- 
```

(Shift-TAB would outdent)

**Additional context**
macOS

**Comment by slonoed** [comment]
Hi! This is marked as done but it doesn't seems to work
Version 5.4.5 (530)


https://user-images.githubusercontent.com/463239/191650380-2b771365-1f89-4c7b-8448-8c711d1b7f7e.mov

**Comment by tadamcz** [comment]
I'm having the same issue, on Version 5.4.5 (530).

https://user-images.githubusercontent.com/43300673/198835789-eade4828-4f2b-4f6e-a06c-e1cd4c95d0d6.mov

**Comment by gingerbeardman** [comment]
Dupe of #627
