### ISSUE TITLE
subfolder support

### ISSUE THREAD

**Issue by aseygo** [glushchenko/fsnotes#69]
would be great if fsnotes could support sub folders (=file system directories)

unlike #56 I would like to use them for organization purposes and sort my notes into different folders.

**Comment by jeff-h** [comment]
I humbly vote against it. I feel the fundamental feature of FSNotes is, like nvALT before it, the near-instant response of its global search. You don't scan a list of folders in the sidebar, possibly expanding one or more, find the one you want and click on it, and then search. You just search.

There are many notes apps which provide hierarchical folder structures (even Apple's Notes app), and the lack of this is almost a feature of FSNotes for me. It forces a certain mindset, which really works once you submit to it, IMO :)

@aseygo — would you consider trialling the low-tech solution which works really well for me and others? At the top of each note you enter, add a hash-tag (or several) being the name of the folder you would file it in, if FSNotes had folders. Then all you have to do is type the first few characters of that word and all you will see in the left-hand are the notes in that "category".

**Comment by aseygo** [comment]
I agree with you @jeff-h, adding sub folder support must by no mean harm any other loved features (simplicity, speed, etc).

I'm now having about 3000 notes (ok there are people with 10k notes..., so lets consider this average), finding the note I need gets more and more difficult. Since a couple of months I'm now using Outline (similar to OneNote) for all new notes I'm creating. The feature I really like is the possibility to order notes in notebooks hierarchically. Everything else is not my taste, but having an option to structure my notes keeps me using Outline. Having sub folder support in fsnotes would make me abandon Outline immediately and only use fsnotes.

Instant response global search:
Sure this must be kept, I also don't want to manually search through all my folders. So I think the default should be to search all folders. But by selecting a particular folder in the sidebar should restrict search to this folder and it's sub folders. The same should apply for creating a new note, default would be the top level folder, but having a folder in the sidebar selected would create the note in there.

Hash-tags:
Hmm, yes could work. I have 2 issues with it. The '#' character is just used to often in my notes. Either I need to think of another character or have fsnotes support a very powerful search syntax where I can limit the search to the first line of a note. (just checking my notes, I would get more that 500 unique hash-tags doing a full note search...). Second issue, having no built-in support in fsnotes for hash-tags leaves me to the problem to remember the hash-tags I used so far and not silently use slightly different tags for the same thing (e.g. #mgmt vs #management).

Tags vs sub folders: I think some apps like nvALT support tags, but they use a specific filesystem attribute to store them. That breaks the simplicity of text file based notes. Not every file system or cloud provider supports that. A file system directory is a basic primitive supported everywhere.

**Comment by thejambi** [comment]
Subfolder contents don't need to be searched to nicely support subfolders. Subfolders can simply be clickable in the notes list to jump into that folder. Then you would be able to see the folder contents and search within the folder.

**Comment by kaapow** [comment]
I vote against this as well. The big win with FSNotes is that you can include multiple folders if you really wish, which is a nice addition above NV.
