### ISSUE TITLE
"Hide FSNotes when activating another application" hides menu bar icon

### ISSUE THREAD

**Issue by keymasterr** [glushchenko/fsnotes#690]
Settings → Layout → Hide FSNotes when activating another application
When checked, the icon in the menu bar is disappearing on another app activation.
![image](https://user-images.githubusercontent.com/6844067/65466473-9be53b80-de67-11e9-8401-18967437bb5f.png)
![image](https://user-images.githubusercontent.com/6844067/65466480-a0a9ef80-de67-11e9-8154-0fb97fea28c2.png)

**Comment by glushchenko** [comment]
Fixed, will be available in next release
