### ISSUE TITLE
Preferences Window does not open under El Capitan (macOS 10.11.6)

### ISSUE THREAD

**Issue by neogomo** [glushchenko/fsnotes#692]
**The apps Preferences window does not open under El Capitan.**

I’ve tried with clicking the preferences item in the menu bar, keyboard shortcut [command]+[,] and also clicking in the corresponding item in FSNotes’s menu extra.

All to no avail.

OS version: 10.11.6 (tried on two different system installations)

**Comment by glushchenko** [comment]
Please try FSNotes 3.8.2 https://github.com/glushchenko/fsnotes/releases/tag/3.8.2

**Comment by neogomo** [comment]
Can confirm the fix. Prefs window is now opening as expected.

Thanks!
