### ISSUE TITLE
Get Info "Copyright" year is out of date

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#694]
Says 2018

See #102

**Comment by glushchenko** [comment]
I can't find, where is it? 2017-2019 in about window.

**Comment by gingerbeardman** [comment]
Sorry, I meant Get Info data 

![Screen shot 2019-09-27 at 15 36 10](https://user-images.githubusercontent.com/49612/65777768-8e1c0880-e13c-11e9-9a69-9d62216c7855.png)

**Comment by LoganDark** [comment]
But... if the issue was fixed why isn't it closed? :thinking:

**Comment by glushchenko** [comment]
Because release not shipped yet and not tested

**Comment by LoganDark** [comment]
You changed a single number though

**Comment by glushchenko** [comment]
And what?

**Comment by LoganDark** [comment]
And.. why would that need to be built, released and tested before closing the issue?

It's just a simple info string, you changed it, it's changed, it will display the correct value now.

**Comment by gingerbeardman** [comment]
@LoganDark because this is his repo and project so he can manage it however he pleases

**Comment by LoganDark** [comment]
Mk, whatever dude.
