### ISSUE TITLE
Popclip extention

### ISSUE THREAD

**Issue by maxwell108** [glushchenko/fsnotes#696]
**Describe your feature request**
Request: a PopClip extension. does make a good workflow
**Additional context**
https://pilotmoon.com/popclip/extensions/

**Comment by gingerbeardman** [comment]
Maybe we could do the same with a macOS Service? "Add to FSNotes" on context menu.

https://github.com/glushchenko/fsnotes/wiki/Services-(macOS)

**Comment by gingerbeardman** [comment]
Proposals in #697 would help with better experience with third-party app integrations

**Comment by maxwell108** [comment]
I got the Nvalt Popclip edited to add to Fsnotes :) works well with text and links! but its internal on my system and I don't understand the packing procedure ...

the service opens Safari and have to select "yes" even from Textedit 

“TextEdit.app“ wants access to control “Safari.app“. Allowing control will provide access to documents and data in “Safari.app“, and to perform actions within that app.' 

and then 

Do you want to allow this page to open “FSNotes.app”?

 A bit long winded

**Comment by maxwell108** [comment]
except it won't copy anything with & in it it stops at the &

**Comment by gingerbeardman** [comment]
I will create a better Service soon.

**Comment by gingerbeardman** [comment]
Done! 

Please re-download "Add Selection to FSNotes"

https://github.com/glushchenko/fsnotes/wiki/Services-(macOS)

**Comment by maxwell108** [comment]
yes thats much better 👍 

any idea why  a 

> & 

 stops the pasting through popclip like its a < end >  thing, thats it **no** more

**Comment by gingerbeardman** [comment]
& is separator for URL query strings. Popclip will need to deal with the URL in the correct way.

I tried using service with the phrase "except it won't copy anything with & in it" and it was added OK to FSNotes.

Feel free to share Popclip screens and info.

**Comment by maxwell108** [comment]
here is a screeny 
![screencast 2019-09-28 12-04-54](https://user-images.githubusercontent.com/18672084/65811452-f45f6480-e1ea-11e9-863c-cbf1c1f813c6.gif)
pop clip as seen will open up Fsnote and paste when the app is closed, and when running it is not brought into focus
the service is only available when fsnote is running 
apple scripts can be used in popclip extensions [github-popclip](https://github.com/pilotmoon/PopClip-Extensions) but i couldn't figure how to use your applescript
this is the shell script I changed from the nvALT one
 `open "fsnotes://new/?txt=$POPCLIP_TEXT"`
and a few edits in Config.playlist to change the name and icon 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Actions</key>
	<array>
		<dict>
			<key>Shell Script File</key>
			<string>nvALT.sh</string>
			<key>Title</key>
			<string>Fsnote</string>
			<key>Image File</key>
			<string>Fsnote.png</string>
		</dict>
	</array>
	<key>Apps</key>
	<array>
		<dict>
			<key>Bundle Identifier</key>
			<string>net.elasticthreads.nv</string>
			<key>Check Installed</key>
			<false/>
			<key>Link</key>
			<string>http://brettterpstra.com/project/nvalt/
</string>
			<key>Name</key>
			<string>nvALT</string>

		</dict>
	</array>
	<key>Credits</key>
	<array>
		<dict>
			<key>Name</key>
			<string>Marc Abramowitz</string>
		</dict>
	</array>
	<key>Extension Description</key>
	<string>Create a note in nvALT.</string>
	<key>Extension Identifier</key>
	<string>com.pilotmoon.popclip.extension.nvalt</string>
	<key>Extension Name</key>
	<string>Fsnote</string>
	<key>Required Software Version</key>
	<string>701</string>
</dict>
</plist>
```
references  and the one above [github-popclip](https://github.com/pilotmoon/PopClip-Extensions)
 https://github.com/glushchenko/fsnotes/wiki/Finding-&-creating-documents-via-URLs

**Comment by gingerbeardman** [comment]
You'll need to make sure the $POPCLIP_TEXT variable is escaped.

**Comment by DesBw** [comment]
If sb is still looking for one, here is a nice extension that can clip the selected text and its url address. 
[Uploading FSnotesclipper.zip…]()

**Comment by gingerbeardman** [comment]
@DesBw upload was not completed, link broken
