### ISSUE TITLE
Open attachment

### ISSUE THREAD

**Issue by Pusnow** [glushchenko/fsnotes#698]
**Describe your feature request**

- Currently, there is no way to open an attachment with an external editor.
- ex) Open attached PDF file with external PDF reader.
- Suggested UI: double clicking attachment (both link and preview) to open it with external editor.

**Additional context**

- macOS version

**Comment by Pusnow** [comment]
QuickLook is not enough. 
To modify (annotate) PDFs, I have to open with external editor (PDF Expert).
Also, there are many files does not have QuickLook extension.

BTW, QuickLook seems to be supported only for TextBundle.

**Comment by gingerbeardman** [comment]
I understand the need to open/view attachments. 

But I'm not sure what you mean regarding QuickLook on TextBundle. Is this in Finder or FSNotes? Does QuickLook have Open button on or not?

These questions are to gauge how much work is needed to implement the feature.

**Comment by Pusnow** [comment]
TextBundle's context menu:

![스크린샷 2019-10-01 오후 6 53 56](https://user-images.githubusercontent.com/6031017/65952494-f5a7c000-e47c-11e9-8c37-5dafa4df24bb.png)

Pure markdown's context menu:

![스크린샷 2019-10-01 오후 6 54 09](https://user-images.githubusercontent.com/6031017/65952519-fdfffb00-e47c-11e9-8023-8c379fb7ebe7.png)

**Comment by gingerbeardman** [comment]
If you choose QuickLook Attachments, the top of the QuickLook window looks like this:

![Screen shot 2019-10-01 at 11 10 52](https://user-images.githubusercontent.com/49612/65953687-6975a880-e43c-11e9-8234-c1ad116adda5.png)

So you can choose to "Open with Preview" (default app for that file type) there.

Not ideal, but a temporary workaround.

**Comment by glushchenko** [comment]
Nice catch, will be implemented in next release 👌
