### ISSUE TITLE
Corrupts prefs window

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#699]
**Describe the bug**
![Screen shot 2019-09-27 at 17 10 43](https://user-images.githubusercontent.com/49612/65950049-3976d700-e435-11e9-9f90-afd141e08e26.png)

**To Reproduce**
Cannot reproduce.

**Expected**
Distinct pref panes

**Actual**
overlaid pref panes

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version 3.8.2

**Comment by glushchenko** [comment]
Fixed in 3.9.1
