### ISSUE TITLE
Making fast notes

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#7]
Love this enhancement :)

One suggestion/request — would you consider the nvALT behaviour with this? When you type a string then hit enter to create a new note, currently you name the new note "Untitled Note" and pre-populate the note with the entered string.

My request is to base the filename off the entered string, and leave the note empty.

**Comment by jeff-h** [comment]
Hmm, I'm obviously confused! I think the behaviour I'm asking for above is what the app already did previously, but you just changed away from it?

**Comment by glushchenko** [comment]
I did not like it either. Fixed yesterday :) 

https://github.com/glushchenko/fsnotes/commit/f7531d15ef7e1efb1354c40b79f634c15f8bc065

**Comment by proksch** [comment]
This does not seem to be fixed in the .zip that is available for download.

**Comment by glushchenko** [comment]
@jeff-h if you want blank note, just press "return" in search field.

**Comment by williamsmj** [comment]
I'd love to move from nvALT to an actively maintained project, but this is a deal-breaker for me.

nv and nvALT get this exactly right. Search, if it doesn't exist hit enter, now it does (with the string you typed as the name).

This streamlines the process of creating notes enormously, and is the main advantage of using nv/ALT rather than creating text files manually.

**Comment by glushchenko** [comment]
@williamsmj it is just experiment, don’t worry. You are right.

**Comment by jeff-h** [comment]
Yeah, another vote for the old way :) When your search results in no match, hitting enter should set the search text as the filename, and the note body should be empty.

**Comment by glushchenko** [comment]
Hi, Jeff. Now all fine with naming behaviour?

**Comment by jeff-h** [comment]
Yes, perfect. Thanks for your work!
