### ISSUE TITLE
Option to Suppress Smart Quotes

### ISSUE THREAD

**Issue by RickCogley** [glushchenko/fsnotes#70]
I think there should be an option to suppress "smart quotes" or "curly quotes". If you're using FSNotes to store any code, it's a pain to have to then re-format everything in another text editor, just because FSNotes tries to help by fixing quotes in code. 

I'd rather have the option, depending how I use it. I hope you'll consider, thanks.

**Comment by glushchenko** [comment]
Smart quotes disable by default. What you mean?

**Comment by RickCogley** [comment]
Ok, sorry about this. Your comment prompted me to look elsewhere, and I found a Mac setting I did not know about. You can have macOS convert any quotes to smart quotes, in System Preferences. Mine was set to change quotes to their "smart" versions, so I think that is where this problem was coming from. I'm on the latest High Sierra. This is the setting: 

<img width="704" alt="jrc screenshot 2017-12-12 at 8 55 37" src="https://user-images.githubusercontent.com/512328/33860126-893e078a-df1a-11e7-9991-de714cbb7d9b.png">
