### ISSUE TITLE
Convert from TextBundle to Markdown

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#700]
**Describe your feature request**
It would be nice if there was a quick/easy way to convert from TextBundle to Markdown for those times where I forget to reset container to None.

**Additional context**
macOS?

**Comment by tewe** [comment]
I want the opposite, convert a `.txt` to a `.textbundle` before inserting an image.

**Comment by Aetles** [comment]
What @tewe said. I'd like a way to convert all old notes to textbundles, but especially when adding images.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!

**Comment by tewe** [comment]
Convert to TextBundle works for me. But Convert to Plain does absolutely nothing. I tried both notes with and without image assets.

Or is this a new issue?

6.0.0 (542) on 12.6

**Comment by glushchenko** [comment]
> Or is this a new issue?

May be, can you provide note example?

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/6.0.1/FSNotes_6.0.1.zip

**Comment by tewe** [comment]
There is no feedback, but it does work. Thanks!
