### ISSUE TITLE
Consider using libcmark_gfm

### ISSUE THREAD

**Issue by Pusnow** [glushchenko/fsnotes#703]
I've found many issues of fsnotes come from its underlying library [cmark-gfm-swift](https://github.com/GitHawkApp/cmark-gfm-swift).

cmark-gfm-swift seems not to under active development and it uses very outdated version (2 years ago, I can't find version) of cmark-gfm.

[libcmark_gfm](https://github.com/KristopherGBaker/libcmark_gfm), on the other hand, supports recent version(4 month ago, 0.29) of cmark-gfm.

It contains lots of [bug fixes, features, and other improvements](https://github.com/github/cmark-gfm/release).

Also, fsnotes uses cmark-gfm-swift as a markdown renderer not AST things (libcmark_gfm doesn't support). 
So, it is not so hard to change rendering library.

Actually, I've already tested fsntoes with libcmark_gfm, and it seens working well.
With small amount of changes, I've already added footnotes #525, bracket links (local file link with whitespace) #544.

Input:

<img width="510" alt="스크린샷 2019-10-05 오후 11 58 39" src="https://user-images.githubusercontent.com/6031017/66256765-2d3fa080-e7cc-11e9-8d2e-2bef3201b1c5.png">

Output:

<img width="509" alt="스크린샷 2019-10-05 오후 11 58 46" src="https://user-images.githubusercontent.com/6031017/66256769-33ce1800-e7cc-11e9-8e0f-5e37331eb8a8.png">

**Comment by glushchenko** [comment]
Can you make Pull Request? We can test this

**Comment by Pusnow** [comment]
Closed by #704
