### ISSUE TITLE
Rich RTF formatting does not shown in Fsnotes

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#705]
**Describe the bug**
99% of the time I use *.md format to store my notes. However, there are situations that I would like to have richer format (e.g., colored font), so I go to "File" -> "new RTF" to create new document.

I tried to color the font but apparently it didn't save in Fsnotes. Then I tried to use TextEdit to do formatting on the file directly.

However, Fsnotes (both MacOS and iOS versions) can't display the extra formatting done with TextEdit (e.g., bigger and colored font).

I wonder is it a bug or it's not designed to support rich formatting in RTF files?

**To Reproduce**
See above

**Expected behavior**
Formatting saved in the *.rtf should be displayed correctly

**Actual behavior**
Seems like Fsnotes can only display the format found in "Format" menu.

**Workaround**
Can't find one yet.

**Supporting Files**
nil.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - iOS: 13.1.1
 - FSNotes version 3.5.0 (Mac), 3.0.1 (iOS)

**Additional context**
nil.

**Comment by glushchenko** [comment]
Font color and size in RTF not changable by design

**Comment by glushchenko** [comment]
We can discuss this of course ...

**Comment by jakemkc** [comment]
I see. 

It's not an essential feature -- just thought there is an option to use RTF, might be I can use it for formatting.

Keeping it simple is good for me. 😎
