### ISSUE TITLE
FSNotes 3.9.1 on Catalina

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#706]
I upgraded my computer to the first release of Catalina and installed FSNotes 3.9.1 from Github. FSNotes would not run and I received the following error dialog:

“FSNotes” can’t be opened because Apple cannot check it for malicious software.

I deleted 3.9.1 and intalled 3.8.1 from the app store and it seems to run OK. Thanks.

**Comment by peavine** [comment]
I had so much trouble with Catalina--both hardware and software--that I went back to Mojave for now. Thanks.

**Comment by gingerbeardman** [comment]
Good to know, I am actively avoiding it for now. iOS 13 also burned me.
