### ISSUE TITLE
Korean delete character bug

### ISSUE THREAD

**Issue by Pusnow** [glushchenko/fsnotes#708]
**Describe the bug**

Korean (Hangul) has a tricky input method.
To enter single syllable (character), I have to combine one or two consonant and a vowel.
For example, to produce Korean syllable "간", I have to press three keys "ㄱ", "ㅏ", "ㄴ".

During the combination, if I press delete(⌫) key, it should delete only the last input ("ㄴ").

"ㄱ" + "ㅏ" + "ㄴ" + ⌫  => "ㄱ" + "ㅏ"  => "가"

However, fsnotes deletes whole syllable.

"ㄱ" + "ㅏ" + "ㄴ" + ⌫  => "" (empty string)

**To Reproduce**

Input above key sequence.

**Expected behavior**

"ㄱ" + "ㅏ" + "ㄴ" + ⌫  => "ㄱ" + "ㅏ"  => "가"

**Actual behavior**

"ㄱ" + "ㅏ" + "ㄴ" + ⌫  => "" (empty string)

**Workaround**

I've found [these codes](https://github.com/glushchenko/fsnotes/blob/5ea1acfd70b1c8c47855196edcf4680cb9520c1a/FSNotes/View/EditTextView.swift#L770-L775) cause this bug.

Why not just pass key event to the super class's keydown method?
Is there any reason to manually edit textview view removeChar method? 

**Supporting Files**

No files

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15
 - FSNotes version 3.9.1.

**Additional context**

Nothing

**Comment by glushchenko** [comment]
Seem like obsolete code related to editor performance speedup.
