### ISSUE TITLE
Crash when adding folder through plus icon

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#709]
**Describe the bug**
Crash when adding folder through plus icon

**What I did**
1. Click + in sidebar

![Screen shot 2019-10-10 at 16 46 50](https://user-images.githubusercontent.com/49612/66584746-9a14bb00-eb7d-11e9-864c-3610e9ce59c0.png)

2. Type folder name "Kickstarter"

3. Crash

(Cannot reproduce)

**Expected behavior**
Folder should be created without issue.

**Actual behavior**
FSNotes crash

**Workaround**
n/a

**Supporting Files**
Crash log
https://gist.github.com/gingerbeardman/0a23559a71c7f9512459d19b13ed3d70

[FSNotes_2019-10-10-164419_matt.crash.zip](https://github.com/glushchenko/fsnotes/files/3713442/FSNotes_2019-10-10-164419_matt.crash.zip)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 3.9.1

**Comment by glushchenko** [comment]
Anyone can reproduce this?

**Comment by jakemkc** [comment]
I don't have the issue when following the step 1 to 3 (though I am using a different version of Fsnote)

MacOS 10.14.6; Fsnotes 3.5.0(285)

**Comment by gingerbeardman** [comment]
Closing as cannot repro.
