### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by jeremycherfas** [glushchenko/fsnotes#71]
I'm really happy with the latest version from the MAS. One minor niggle that I noted in my review: 

> the display of links is different from nvALT's. A well-formed Markdown link is clickable in the preview mode, but not in "native" mode.

I have no idea how hard it would be to implement this, but it would be really useful.

Thanks

**Comment by glushchenko** [comment]
Hi, @jeremycherfas, please checkout MAS.

**Comment by jeremycherfas** [comment]
Well done; that is really good.

Jeremy 


On Mon, 11 Dec 2017, at 09:50 PM, Oleksandr wrote:
> Hi, @jeremycherfas[1], please checkout MAS.


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/jeremycherfas
  2. https://github.com/glushchenko/fsnotes/issues/71#issuecomment-350853875
