### ISSUE TITLE
Crash when right clicking note preview

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#710]
**Describe the bug**
Crash when right clicking note preview after search results

**To Reproduce**
1. Right click list item preview
2. Crash

**Expected behavior**
Context menu should be shown

**Actual behavior**
Crash

**Workaround**
Use 3.8.2

**Supporting Files**
[FSNotes_2019-10-10-164956_matt.crash.zip](https://github.com/glushchenko/fsnotes/files/3713457/FSNotes_2019-10-10-164956_matt.crash.zip)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 3.9.1 & 3.9.0

**Comment by gingerbeardman** [comment]
Correction, but is present in 3.9.1 and 3.9.0.

3.8.2 works fine.

**Comment by gingerbeardman** [comment]
Odd. I can no longer reproduce this one.

Closing, will reopen if it happens again.

**Comment by gingerbeardman** [comment]
Just had this happen again.

**Comment by glushchenko** [comment]
This bug related to git history integration. 

https://stackoverflow.com/questions/25559608/running-shell-script-with-nstask-causes-posix-spawn-error

**Comment by gingerbeardman** [comment]
Yes!

If I try to click git pane in FSNotes preferences I get a similar crash.

**Comment by glushchenko** [comment]
I'm trying to reproduce that in virtual machine with Mojave 10.14, but nothing happens. May be anyone explain cause of this error?

May be some security settings or firewall block, notarization check, etc?

**Comment by gingerbeardman** [comment]
It's related to App Translocation and/or Quarantine xattr bit.

For some reason, Mojave (or at least my setup) is no longer correctly removing App Translation (quarantine bit) when I install the app (unzip and manually move to Applications).

To get around this I have a script that removes the xattr and opens the app. 

```
xattr -cr "/Applications/FSNotes.app"
open "/Applications/FSNotes.app"
```

If I do this on FSNotes then the right click will work normally.

So, you should be able to set the xattr to reproduce the problem. 

Alternatively, extract https://github.com/glushchenko/fsnotes/releases/download/4.0.0/FSNotes_4.0.0.zip using [Keka](https://www.keka.io/)
