### ISSUE TITLE
Per-note setting for preview mode?

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#713]
**Describe your feature request**
I'd like to be able to set Preview mode as a per-note setting.

So I can switch between previewing one note and editing another.

**Comment by buddax2** [comment]
How about stepping out of thinking about it as "Preview Mode"? I would rather make all notes editable, but then you can "Save" it so it will be in read-only mode until you manually turn it to edit mode.

**Comment by gingerbeardman** [comment]
Yes, that would work for me.

You could use an `xattr` to store the setting on the file.

**Comment by amarendra** [comment]
This is exactly my use-case as well. Some way to mark some notes uneditable, but starts with editable as default. I think it's already available in iOS (not sure). This will be an awesome feature.

**Comment by glushchenko** [comment]
Implemented in FSNotes 6

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
