### ISSUE TITLE
In TODO section, the todo items have wrong checkmark icon

### ISSUE THREAD

**Issue by iSapozhnik** [glushchenko/fsnotes#717]
**Describe the bug**
When I create a new TODO list and mark some items as "Done" - the checkmarks for those items are rotated by 180 degrees.

**To Reproduce**
1. Go to `TODO` section
2. `CMD+N` to create a new entry
3. Add some TODO items
4. Click on some of them to mark as "Done"

**Expected behaviour**
The checkmark icon should have the right orientation.

**Actual behavior**
The checkmark icon is upside down

**Supporting Files**
![image](https://user-images.githubusercontent.com/1089384/67381011-83159600-f58b-11e9-8c4b-f488b536379c.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - OS version: 10.14.4
 - FSNotes version: 3.9.1 (323)

**Additional context**
Great app anyways ;)

**Comment by glushchenko** [comment]
Fixed in last beta, please try

**Comment by fturcheti** [comment]
I was facing the same problem, but I can confirm it's fixed in the last release, 4.0.0 (328).

**Comment by iSapozhnik** [comment]
Tested with 4.0.2 — All good!
