### ISSUE TITLE
About window size needs to be fixed size

### ISSUE THREAD

**Issue by iSapozhnik** [glushchenko/fsnotes#718]
**Describe the bug**
The user is able to change the size of the window therefore th content might be screwed

**To Reproduce**
1. Go to `About FSNotes` window
2. Start dragging one of the edges of the window
3. Observe that content might overlap

**Expected behavior**
The About window should have a fixed size and user should not be able to change it

**Actual behavior**
User can change the size of the window so that it's not even possible to read the content and there is no way to undo it.

**Workaround**
No workaround

**Supporting Files**
![image](https://user-images.githubusercontent.com/1089384/67382345-9e81a080-f58d-11e9-93b7-4615aa706d8e.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - OS version: 10.14.4
 - FSNotes version: 3.9.1 (323)

**Comment by iSapozhnik** [comment]
I've made some changes here —> #719

**Comment by glushchenko** [comment]
Can not reproduce this on Mojave

**Comment by gingerbeardman** [comment]
On Mojave for me, if I resize the window

FSNotes 4.0.0

![Screen shot 2019-10-26 at 15 32 02](https://user-images.githubusercontent.com/49612/67621177-d004a100-f805-11e9-848b-2abd7c2979e9.png)

**Comment by iSapozhnik** [comment]
4.0.2 — works as expected.
