### ISSUE TITLE
MermaidJS CSS not optimized for Dark Mode

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#720]
When using dark mode, MermaidJS charts render with white text, which looks bad on boxes with a light background. Can we have styles optimized for dark mode that load if dark mode is used?

See this example:

<img width="837" alt="Screen Shot 2019-10-24 at 14 40 00" src="https://user-images.githubusercontent.com/6884276/67519437-7cab1b00-f66c-11e9-9ff6-2c4563c5ae7a.png">

**Comment by glushchenko** [comment]
I tried "dark" theme, its looks not good. I think this issue should be addressed to https://github.com/mermaidjs
