### ISSUE TITLE
V4.0.0 - Tag browser in sidebar now empty?

### ISSUE THREAD

**Issue by iandol** [glushchenko/fsnotes#722]
**Describe the bug**
Just upgraded to V4.0, and my tags have all disappeared from the sidebar. Previously they were all visible and I could interact with them. I would have assumed inline #tags should be an "additional" feature, not remove previous tags?

**To Reproduce**
1. Have tagged notes
2. Upgrade to V4.0
3. Sidebar #tags now empty

**Expected behavior**
Retain my tags, but allow additional use of inline tags, not exclusive replacement

**Actual behavior**
Previous tags have disappeared

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**

![Screenshot 2019-10-28 at 09 11 26](https://user-images.githubusercontent.com/153905/67645468-e58fdd00-f963-11e9-9311-338a2e2f7756.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.15.0
 - FSNotes version: 4.0.0

**Additional context**

**Comment by iandol** [comment]
OK, disabling inline notes and the tags come back, so it appears this is by design?

**Comment by glushchenko** [comment]
Yes, inline tags works now by default. I wrote about it in release notes.

**Comment by iandol** [comment]
OK I'll close this then, but out of curiosity is there no way to combine these by default (i.e. metadata tags are shown and available, and inline tags are ANDed to the list by scanning.
