### ISSUE TITLE
Completely screwed up my notes, especially tags

### ISSUE THREAD

**Issue by sdclee** [glushchenko/fsnotes#724]
My IOS and Mac systems have all been updated recently (Catalina 10.15.1, IOS 13.1.3)
I now have none of my tags (there were about 20) and instead have fragments from my notes extracted as tags (e.g. 'hello', 'unlimited' etc). The tags differ between my Mac and Mac Book Pro at the moment as well.

I cannot reproduce the behaviour as everything has been trashed between looking at notes yesterday and updating my iPad pro to the latest version of the app (3.5 on the iPad store, 4.0.3 (334 on the mac).

I expected my data to be preserved above all other functionality !
There is no workaround that I can see as I can no longer trust the app to keep my data intact.

Thanks in advance.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 3.8.2

**Additional context**

**Comment by sdclee** [comment]
The tags differ between devices (all messed up either way) - see attached screenshot from the Mac.
<img width="192" alt="Screenshot 2019-10-31 at 11 20 48" src="https://user-images.githubusercontent.com/1264229/67942818-a0241780-fbd0-11e9-8c66-684d57b29f33.png">

**Comment by glushchenko** [comment]
Hello @sdclee. You use version 4.0.2 as minimum, because I see "Welcome" project introduced in 4.0.2.

So If you read Release Notes, you can see, that now by default for tags used inline tags. If you want use obsolete tags go to Preferences -> Editor and unheck "Scan inline tags"

Thanks

**Comment by sdclee** [comment]
Many thanks for the quick reply :)
I can't find release notes on the web or in GitHub that refer to inline
tags but setting 'scan inline tags' off does indeed restore my tags.
I'll keep looking for the notes on inline versus 'obsolete' tags to see if
there is a way of converting existing tags.
Thanks again.
L
ee

**Comment by glushchenko** [comment]
If issue solved please change you review on the MacUpdate. Closed

**Comment by sdclee** [comment]
Apologies but I don't know which 'MacUpdate' review you are referring to (?)
I did previously leave a review in the App Store (not related to this
issue) but currently I see only five reviews in total (3.5 out of 5 rating).
L
ee

**Comment by gingerbeardman** [comment]
@sdclee there is a review by a user with the same username: https://www.macupdate.com/app/mac/60426/fsnotes#comments

**Comment by sdclee** [comment]
Thanks for the reply with the clarification Matt.
The review I made at the time still stands as I have low confidence with
FSNotes right now.
I will gladly change it if I can go a week without losing any data or
having it otherwise knocked out of shape.
As I stated before, with a relatively small number of notes it is easy to
keep track of the sync across devices but my notes are growing rapidly and
I am still far from comfortable that the data is safely preserved.
In the absence of an audit log to show sync activity with add/edit/delete
status and timestamps I still worry about the relative stability and
validity of the data.
The issue which was addressed in the support desk ticket was to do with
inline tags, not my sync issues.
Also currently, even with inline tags disabled I am getting an automated
#tag of the existing tag inside any new note created. The note itself is
frozen, then it disappears from view, only to be found out of place
somewhere else.
Finally I have many duplicates (which may be from an early version) - see
attached screenshot.
So all in all as much as I want to love this product, it is not yet mature
or stable enough IMHO.
L
ee

**Comment by gingerbeardman** [comment]
I'm not sure I follow your concerns.

The notes are stored in the filesystem, and synced through iCloud. Both of which fall under Apple's remit in terms of confidence of storage reliability. Your request for syncing log is really to Apple not to FSNotes so we cannot help.

If you are seeing notes being lost through operation of FSNotes, by all means file a bug report. 

Also please file one for the tag issue you describe. That does sound like a bug in the new feature.

Your screenshot did not come through to this issue, please also file a new issue based on your duplicates. From that you've written it sounds like user error, but let's be sure.

**Comment by glushchenko** [comment]
Duplicates created when one file changed in one place, and not synced yet with other. And in same time second file modified. FSNotes can not resolve conflicts, this is may be dangerous, therefore in this cases new file will be created.

**Comment by sdclee** [comment]
Ok thanks. That is a very helpful answer.
Unfortunately I still have little confidence in the app.
I will gladly raise a separate ticket if you wish.
I have only been using FSNotes on my Mac today and simply made a change to
the title of one note to "Midnight Commander". It should be found under the
'linux' tag/ A search reveals nothing with the word 'Midnight' in it.
You will see from the screenshot (in sort by modified date/time) that,
apart from the three sticky notes, the latest update at the top is dated
yesterday (3rd November), so it looks like the change has not been saved.
The note is actually one of the duplicates mentioned previously (in fact a
triplicate) so whilst I am happy with your explanation, one of the three
notes should have been changed (see 2nd screenshot which should the
original timestamps).
I would appreciate your thoughts.
Thanks in advance.
L
ee
--

**Comment by gingerbeardman** [comment]
Your screenshot email attachments don't arrive at GitHub. If you want to add them you'll need to use the site directly. 

Can you locate the file you're looking for in Finder?

**Comment by sdclee** [comment]
Thanks for the reply. I'm going to create a video with annotations and
supply a link for the issues I'm encountering.
My only regret is that I didn't take a screenshot this morning before
changing something but never mind.
As I will be away for a few days this week I may not get the video done
until the weekend so please bear with me and thank you very much for your
continued support :)
L
ee
