### ISSUE TITLE
Visibility flag not working in 4.x

### ISSUE THREAD

**Issue by TannerTechnical** [glushchenko/fsnotes#726]
**Describe the bug**
In a folder's properties, unchecking the " Visibilty: Show in Notes and Todo Lists" checkbox has no effect. The folder's items still appear in "Notes" and "Todo".

**To Reproduce**
1. Uncheck a folder's visbilty checkbox
2. Create a new item with some text and also a Todo
3. View the "Notes" list
4. View the "Todo" list

**Expected behavior**
The items should not be displayed in the "Notes" and "Todo" lists.

**Actual behavior**
The items are displayed in the "Notes" and "Todo" lists.

**Workaround**
None.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - FSNotes version: 4.0.3

**Comment by glushchenko** [comment]
Tried to reproduce, for "Notes" category can not reproduce. For Todo fixed.

**Comment by TannerTechnical** [comment]
I am not seeing the fix in 4.0.4 (335). The behavior remains the **same as originally described**, for both the "Notes" and "Todo" categories.

I am using plain text files with an ".md" file extension. Permissions on the test folder are 755, and on the test text file 644. FSNotes is the only application accessing these notes.

Is there any more info I can provide, or tests I can run, to help debugging this issues.

**Comment by CoolMa7** [comment]
I found the same behavior in Mac version 4.1.5(372). If I uncheck the " Visibilty: Show in Notes and Todo Lists" checkbox in one folder it has no effect. The folder's items still appear in "Notes" and "Todo".
