### ISSUE TITLE
Support parsing Textbundle packages containing text files with all extensions of text.* files

### ISSUE THREAD

**Issue by magicnemo** [glushchenko/fsnotes#728]
**Describe the bug**
Inside a text-bundle package, FSNotes only looks for a file named text.*markdown* (i.e. the extension to the text-file is "markdown).

Problem is, if using other apps (E.g. export from Ulysses using textbundle) or "markdown to textbundle conversion tools" (e.g. https://github.com/jsorge/textbundleify) they might product text.*md* files instead of text.*markdown*, the extension to the text file is not the same.

According to markdown spec any extension to "text.____" should be allowed. (http://textbundle.org/spec/)

Looking at Ulysses for instance, if you try to export from Ulysses using TextBundle and then try to read the text in FSNotes, its not possible, the text file looks empty in FSNotes UI. This due to Ulysses use .md extension instead of .markdown extension.

**To Reproduce**
Open a textbundle file that FSNotes created and inside it rename text.markdown to text.md and try read it in FSNotes afterwards.

**Expected behavior**
FSNotes can read and show .textbundle files, where at least also text.md files are parsed, not only text.markdown (and best would of course be text.* is supported with any extension)

**Actual behavior**
FSnotes shows an empty text file altough text exists.

**Workaround**
Manually rename text.md to text.markdown (for each .textbundle)

**Supporting Files**
Non needed.

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.14.5
 - FSNotes version: 4.0.3

**Additional context**
Otherwise thanks for a great app, and also supporting textbundle which i think is great way to handle images & other files! I'm using FSNotes together with "Folding Text" as external editor.

**Comment by voltaireodactyl** [comment]
It would be outstanding if the .highland format could also be supported -- my understanding is that the spec is the same as Textbundle, just purposed toward screenwriting: https://quoteunquoteapps.com/highland-2/highland-format.php

Thanks as always for all the hard work -- love the app so much.

**Comment by gingerbeardman** [comment]
@voltaireodactyl let's wait for them to release the highland spec (bottom section of the page you link says "coming soon")

**Comment by scaba** [comment]
The .highland file format has been used in their commercial product Highland (1 & 2) for seven years now and hasn't changed, so I'd suggesting any interested parties to implement the spec as written and update if needed. The [.fountain spec](https://fountain.io/) is already pretty well documented

**Comment by gingerbeardman** [comment]
@scaba where is the highland spec? please add a link to it here.

**Comment by glushchenko** [comment]
@magicnemo please test https://github.com/glushchenko/fsnotes/releases/tag/4.0.6

**Comment by magicnemo** [comment]
Working perfectly in 4.0.6, thanks!!! :)
