### ISSUE TITLE
Folding attached folders

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#731]
**Describe your feature request**
In fsnotes, we can attach external folders and they are shown in the sidebar (Folder ➙ attach storage).
The subfolders will be shown as nested under each storage folder.

I have an archive storage folder which has subfolders created by month. I wonder is it possible to make the attached storage foldable to simplify the sidebar?

This is exactly as what Finder can do (see below).

<img width="149" alt="Screen Shot" src="https://user-images.githubusercontent.com/18485734/68160842-9bd66200-ff22-11e9-97ff-8138ac0fd82d.png">
<img width="150" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/18485734/68160844-9bd66200-ff22-11e9-8632-5f1e29483270.png">

**Additional context**
This is a feature only needed for MacOS version

Thanks!

**Comment by davidlohner** [comment]
add to this request:  re-arrange attached folders (change order) via drag and drop.

**Comment by lemonballoons** [comment]
+1
Currently I manually attach and unattach storage to save on screenspace, but that's finicky and I can't navigate as quickly.

**Comment by glushchenko** [comment]
I think nested folders implementation close this issue
