### ISSUE TITLE
Pie charts not rendering in preview, mermaidjs extension

### ISSUE THREAD

**Issue by supersmart-at** [glushchenko/fsnotes#732]
**Describe the bug**
MermaidJS - PieChart not rendering 

**To Reproduce**
1. Use Sample Code from mermaidjs website
`
```mermaid
pie
    "DataKey1" : Positive numeric value (upto two decimal places)
    "Calcium" : 42.96
    "Potassium" : 50.05
    "Magnesium" : 10.01
    "Iron" :  5

```
`

**Expected behavior**
A rendered Chart

**Actual behavior**
stays blank
**Workaround**
none

**Desktop (please complete the following information):**
 - OS: macOS catalina
 - OS version: 10.15.a
 - FSNotes version: 4.0.3 (334)

**Additional context**
could not figure out if its an fsnotes issue or mermaid problem; checked all issues so far on github, nothing found

**Comment by glushchenko** [comment]
So, at first you should use syntax:

```
pie title Positive numeric value (upto two decimal places)
    "Calcium" : 42.96
    "Potassium" : 50.05
    "Magnesium" : 10.01
    "Iron" :  5
```

At second update to FSNotes 4.0.10

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/4.0.10

**Comment by supersmart-at** [comment]
Thank you. Verified and chart renders properly as expected.

**Comment by stephencweiss** [comment]
@glushchenko is the brew cask behind a build? Just upgraded and got v4.0.9.

![image](https://user-images.githubusercontent.com/39878535/70073301-35df0800-15be-11ea-8fb6-ef327a733a55.png)

**Comment by glushchenko** [comment]
@stephencweiss brew receipt updated by community, some time needed.

**Comment by stephencweiss** [comment]
Got it! Thanks! Is there anything I can do to help with that? 

Cheers!

Stephen Weiss | 651.233.6827

**Comment by gingerbeardman** [comment]
You can follow their guide to update this file:

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/fsnotes.rb
