### ISSUE TITLE
Change #tag parsing so it doesn't pick up normal numbering usage

### ISSUE THREAD

**Issue by isao** [glushchenko/fsnotes#733]
<img width="127" alt="image" align="right" src="https://user-images.githubusercontent.com/46951/68344529-08c53580-00a4-11ea-935c-c0f27a001d59.png"> **Describe your feature request**

I would really like tags to be text, like "#mytag", or "#my-tag", and ignore "#" followed by a non-alphanumeric character.

**Additional context**
I just bought FSNotes for macOS, and it seems really nice!

But after attaching folders of some of my existing notes, I was sad to see  tags like `0`, `1`, `1245`, etc. I keep machine logs snippettes, code, and other text that use the hash character that I do not want to be treated as a tag. Examples image at right -->

Thanks for listening. :)

**Comment by isao** [comment]
Alternatively, perhaps a preference to define tags only in special lines:

    some stuff not not tagging things like #1 ...
    tags: #mytag1 #mytag2

**Comment by glushchenko** [comment]
Digits removed from tags list

**Comment by blipblipblop** [comment]
Actually was looking why tags with digits were not created, so it is intentional

BTW, second level tags with digits are still created. Example #SomeTag/123
Is it normal behaviour and I can continue using it or is it a bug?

**Comment by glushchenko** [comment]
@blipblipblop it is normal, you can use digits on second level.
