### ISSUE TITLE
Note is deselected on mouse-click or arrow-keys in the editor

### ISSUE THREAD

**Issue by npras** [glushchenko/fsnotes#735]
**To Reproduce**
2. Click any note
3. Edit it
4. Use mouse-click or arrow-keys to change cursor position
5. See the editor closing automatically

**Expected behavior**
When editing a note, using mouse to point to a specific location in the file or using arrow keys to navigate shouldn't cause the note-editor to close.

**Actual behavior**
The note-editor is closing as soon as I click mouse in the editor (to keep the cursor somewhere) or when I move around using arrow keys.

This behavior is not consistent though. Some times it doesn't crash. But it's too often that it's annoying and we can't work on a file with focus.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.4 (335)

I've placed my notes repo in `~/Google Drive`. It syncs to cloud using google's `backup and sync` app. Maybe that could be the issue? I haven't tried with changing the repo location though. If needed will try.

**Comment by gingerbeardman** [comment]
See #734

**Comment by npras** [comment]
Yes, this is the same issue as #734. Will close this.
