### ISSUE TITLE
Dark (system) appearance is not true dark mode

### ISSUE THREAD

**Issue by pryley** [glushchenko/fsnotes#737]
**Describe the bug**

1. The colour of the main screen is an incorrect hue (compare with the FSNotes preferences window).
2. The note selection highlight colour does not adhere to the system Highlight Color preference, this is especially jarring when you select text in the note and the System Highlight colour is something other than blue.
3. The sidebar icons are too bright, they should be dimmed like the icons in the sidebar of the Finder window.

**Desktop**
 - OS: macOS
 - OS version: 10.15.1
 - FSNotes version: 4.0.3 (334)

**Comment by glushchenko** [comment]
I think UI better in FSNotes 5, please try.
