### ISSUE TITLE
First selection always lost

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#738]
**Describe the bug**
In RTF notes, the first text selection made (by dragging, not double-clicking) always immediately deselects.

**To Reproduce**
1. Go to any RTF note.
2. Type any character on the keyboard.
3. Attempt to select some text by dragging.
4. The selection deselects itself.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.1
 - FSNotes version: 4.0.5

**Additional context**
This bug has been present for a very long time — sorry I did not identify which release introduced it. I kind of assumed someone else would eventually raise the issue but nobody did lol Am I really the only person using FSNotes for RTF? I hope not!

![selection-issue](https://user-images.githubusercontent.com/841871/68736250-f53a4180-0644-11ea-9db6-2ae8036929e0.gif)

**Comment by glushchenko** [comment]
Please try 4.0.8

**Comment by jeff-h** [comment]
Fixed for me. Awesome work!
