### ISSUE TITLE
Tags does not show up when using iCloud

### ISSUE THREAD

**Issue by circleapps** [glushchenko/fsnotes#739]
**Describe the bug**
Tags does not show up when using iCloud

**To Reproduce**
1. Switch to use iCloud for file container
2. Adding some tags to notes
3. Check the tags 

**Expected behavior**
The new tag will show up in the tag list.

**Actual behavior**
tags  is empty

**Supporting Files**
![image](https://user-images.githubusercontent.com/44904628/68739673-54d42500-0624-11ea-80d6-aa1a641fd09d.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.15.1
 - FSNotes version: 4.0.4

**Comment by glushchenko** [comment]
This is obsolete interface, removed in 4.0.7. Now uses inline tags, just type #tag and this will bi visible in sidebar.

**Comment by circleapps** [comment]
I'm using  `brew cask install fsnotes` to install fsnotes, looks like it is still the 4.0.4 version.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/4.0.7

**Comment by circleapps** [comment]
Thanks
