### ISSUE TITLE
When moving between lines the 'note' closes

### ISSUE THREAD

**Issue by csi-lk** [glushchenko/fsnotes#740]
**Describe the bug**
When using keyboard or mouse to move between lines in a note the note closes (loses focus)

**To Reproduce**
1. Download fsnotes on appstore
2. Create note in folder
3. Write some things
4. Arrow key up
Note closes
5. Re-open note, click on any non focused line
Note closes

**Supporting Files**

I have tried restarting my computer and fsnotes,

![2019-11-13 10 19 41](https://user-images.githubusercontent.com/2224266/68754876-7e2e8a00-05ff-11ea-99af-d433a52274ae.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.4 (App Store)

**Additional context**
This seems to have been introduced with the update on the 8th, strangely it's been getting worse over time and is now practically unusable

**Comment by glushchenko** [comment]
Fixed already, please download last version from GitHub.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by csi-lk** [comment]
Hey @glushchenko thanks for the reply, can you publish the latest version to the app store please? In the meantime i'll use the github published version as a workaround

**Comment by gingerbeardman** [comment]
Dupe #734

**Comment by glushchenko** [comment]
@csi-lk sure. New builds in App Store coming a little bit later, some time needs for review by AppStore team.

**Comment by csi-lk** [comment]
Thanks @glushchenko, closing 👍

**Comment by glushchenko** [comment]
Available in Mac App Store.
