### ISSUE TITLE
New note appears to get frozen with just a #tag

### ISSUE THREAD

**Issue by sdclee** [glushchenko/fsnotes#741]
Hi - I'd like to report this bug "frozen new note" by providing a link to a video I've made which probably explains it better than a typed explanation.

http://softdev.co.uk/videos/fsnotesbug.mp4

macOS Catalina 
FSnotes 4.0.2 (331)

Creating a new note gets an automatic #tag inserted but the note is not editable, then disappears from view when you navigate away from the current location.
In my video I create a new note whilst in the 'dxo' tag area on the LH side.
The note looks to be frozen (it is actually elsewhere in the system under 'inbox' or 'notes' but not where I am currently located.

Hopefully the video will demonstrate.
Thanks in advance.
Lee 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 3.8.2

**Additional context**

**Comment by glushchenko** [comment]
At first update to last version is 4.0.7. At second dont use tags form, is obsolete and used for non linline tags system.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sdclee** [comment]
Many thanks for your reply.
I will update the version tomorrow but I’m afraid I don’t know how to
convert my existing  tags to online tags.
I disabled inline tags because they were meaningless when they
automatically changed my existing tags (the ones that you refer to as
obsolete) at the last version update.
Lee

**Comment by sdclee** [comment]
Thanks for the reply - appreciated. There are still areas around inline tags that for me, are less than ideal. Please take a look at this second video which might best explain what I am referring to.
http://softdev.co.uk/videos/fsnotes-scaninlinetags.mp4
