### ISSUE TITLE
Folder level encryption commands

### ISSUE THREAD

**Issue by kerim** [glushchenko/fsnotes#742]
**Describe your feature request**

I would like to be able to lock/unlock all notes in a folder at once, preferably by that folder's contextual menu and/or a keyboard command.

**Additional context**
Add any other related information here. macOS or iOS?

Right now I can lock/unlock individual notes (or more than one by selecting them first), and lock all encrypted notes, but there is no ability to do this at the folder level. I would like to have a research journal folder, and since encrypted notes are not searchable, when I'm using that folder I would want all notes in there to be unlocked. Right now this requires first selecting all notes and then locking them. Having a folder-level command would make this easier and more intuitive. Even better if it worked on sub-folders as well.

**Comment by obear** [comment]
+1 👍 
That would be super helpful. I couldn't imagine that this wouldn't work and I searched forever for a menu command until I found out that it really only works with the solution described above. (At least on the mac) Under iOS I have not found a solution yet. If I have thousands of notes, I don't want to decrypt each note individually. This is so impractical that I can leave it at that and then the encryption doesn't make sense anymore. :-(

**Comment by egalitarian** [comment]
+1 👍
Also ability to encrypt all notes by default would be nice.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
