### ISSUE TITLE
Keyboard shortcut to go "Notes" section.

### ISSUE THREAD

**Issue by gpinnadhari** [glushchenko/fsnotes#744]
On MacOS, could we get a keyboard shortcut to go directly to the "Notes" section?
I use this section to see the list of my recently edited notes/files and this currently requires mouse navigation.

![image](https://user-images.githubusercontent.com/2374753/69249776-72514380-0b7c-11ea-9388-d0b67daa072b.png)

**Comment by glushchenko** [comment]
ctrl + 1 - Inbox
ctrl + 2 - Notes
ctrl + 3 - Todo
ctrl + 4 - Archive
ctrl + 5 - Trash

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1
