### ISSUE TITLE
Opening iOS app after more than ~7 days causes all notes to re-index / load

### ISSUE THREAD

**Issue by jurb** [glushchenko/fsnotes#747]
**Describe the bug**
If I open the FSnote app on my iphone after a week or 2, I see a list of fast loading notes, which takes a long while (I have ~1500 notes in that directory). I see very old notes flashing by (from 2011, for instance).

**To Reproduce**
1. Like described, when I open the app after a week or 2 all notes seem to reindex / reload. 

**Expected behavior**
Show the newest note and put the newest notes that are loaded visibly on top. Even better would be to update my notes in the background, so I always get the newest notes when I open the app, no matter the time I didn't open it.

**Comment by jurb** [comment]
Can’t reproduce this anymore

**Comment by glushchenko** [comment]
May be you dont have enough space. In this case iCloud Drive files may be deleted from you device.
