### ISSUE TITLE
Inconsistent Keyboard Shortcut Focus Behavior  

### ISSUE THREAD

**Issue by stephencweiss** [glushchenko/fsnotes#748]
**Describe the bug**
The keyboard shortcuts to navigate from a note to a notes list to the side bar (up and down) using `enter` and `cmd+enter` works inconsistently. Sometimes they work when I start the app, but I've found that once I've gotten _into_ a note for the first time, they stop working. 

**Expected behavior**
I expect that when I'm in a note and type `cmd+enter` it should elevate focus to the notes list.

Similarly, when I'm in a notes list and hit enter, my focus should move to the note.

**Actual behavior**
 Instead it often either:
1. Creates a new line (when in the note) or does nothing (when in the notes list)
2. "Errors" (emits a noise) and does nothing

**Workaround**
Use the mouse. 

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.2
 - FSNotes version: 4.0.7

**Comment by glushchenko** [comment]
I can not reproduce this
