### ISSUE TITLE
Search is not scoped between different folders

### ISSUE THREAD

**Issue by npras** [glushchenko/fsnotes#749]
**Describe the bug**
The default storage for my notes source is a folder `_prasnotes`.
Inside this I have 2 folders `work` and `other`.
All of my notes (text) files are present in these 2 folders.

At any given point of time, I'll have only one of these 2 folders selected. At work time, it is `work` and at personal times, it is `other`.

When I search for an existing note in the main `Search or create` text box, I expect FSNotes should only list matching files present under the selected folder `work` or `other`.

But right now, it doesn't respect the folder selection and lists all the matching files present in all folders.

Eg: 
I have a `scratchpad` file under both `work` and `other` folder. I use it to jot down something quickly.
If I'm at work and have the `work` folder selected, when I search for `scratchpad`, I'm seeing both the scratchpad files listed in search results. But I expect it should only return only the `scratchpad` note from the `work` folder.

Can this be fixed?
I think it is a very reasonable request and a necessary one.

**Comment by glushchenko** [comment]
Please try 4.0.8

**Comment by npras** [comment]
@glushchenko it works in 4.0.8.

Thanks a lot, you are awesome! 🎉
