### ISSUE TITLE
Program crashes after latest High Sierra update

### ISSUE THREAD

**Issue by mcuix** [glushchenko/fsnotes#75]
The program fails to start. Shows "FSNotes quit unexpectedly".

**Comment by mcuix** [comment]
Application Specific Information:
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file "fsnotes" couldn't be opened because there is no such file." UserInfo={NSURL=file:///Users/xxxxxx/Library/Mobile%20Documents/com~apple~CloudDocs/fsnotes/, NSFilePath=/Users/xxxxxx/Library/Mobile Documents/com~apple~CloudDocs/fsnotes, NSUnderlyingError=0x60400024afb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.74.1/src/swift/stdlib/public/core/ErrorType.swift, line 181

**Comment by glushchenko** [comment]
Please attach crash report. 1.1.16 still on review in MAS, but you can try build from github.

**Comment by glushchenko** [comment]
Folder above does exist?

**Comment by mcuix** [comment]
Yes, the folder exists.

**Comment by mcuix** [comment]
Removed program with all associated files and the re-installed it. Program now launches.
