### ISSUE TITLE
dark flashes in notes list while editing

### ISSUE THREAD

**Issue by rawlins** [glushchenko/fsnotes#750]
**Describe the bug**
While typing in a note, or moving the mouse, the notes list area sometimes flashes a dark color, and the alternating shading in the notes list sometimes glitches.

**To Reproduce**
This reproduces very easily for my by simply doing normal note editing with a note selected; I haven't been able to pin down any specific trigger that consistently causes the visual flash. It doesn't happen on its own with no input at all, but I've seen it happen when moving the mouse, typing normal text, or selecting text. It happens for both top and side positions for the notes list, but is much more obvious for the side-aligned. However, it may well be system-specific in some way; this is a 2017 macbook pro running 10.12.6 (so, pre-dark-mode). Since I don't know how well it will replicate, a screen recording demonstrating the issue is attached. I *think* I've been more easily able to reproduce it when there are various windows under FSNotes (which you can see in the screen recording); I first tried to make a screen recording in fullscreen mode and couldn't get it to happen at all, and I also had trouble getting it to happen while recording just part of the screen.

**Expected behavior**
Not flashing, it's fairly distracting.

**Actual behavior**
The notes list flashes a dark color every few seconds while I'm editing. Sometimes, the shading of the rows in this list shifts so that gray and white don't alternate. The attached screen recording shows both of these glitches (the shading starts off, recovers just before the flash, and then glitches again towards the end.

**Workaround**
I haven't been able to get this to happen in fullscreen mode. Hiding the notes list of course keeps it from happening.

**Supporting Files**
Screen recording attached as a zip of a quicktime movie:
[fsnotes_flash_bug.zip](https://github.com/glushchenko/fsnotes/files/3883786/fsnotes_flash_bug.zip)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.12.6
 - FSNotes version: 4.0.7 (338); the current app store version

**Additional context**
Thanks for a great piece of software!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/4.8.3_build438
