### ISSUE TITLE
Window Position Restore Doesn't Restore To Secondary Screens

### ISSUE THREAD

**Issue by devtimi** [glushchenko/fsnotes#751]
Window positioning restoration does not restore the window to secondary screens.

**To Reproduce**
1. Move window to secondary screen
2. Close FSNotes
3. Open FSNotes
4. Find window on main screen

**Expected behavior**
Window should restore to secondary screen position.

**Actual behavior**
Window restores to relative position on main screen.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.8 (339)

**Comment by glushchenko** [comment]
Finally fixed, thanks.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.10.0/FSNotes.zip
