### ISSUE TITLE
Checkbox vanishes after toggling preview

### ISSUE THREAD

**Issue by rawlins** [glushchenko/fsnotes#752]
**Describe the bug**
After toggling preview on and off for a md note with checkboxes, the checkboxes stop being shown in edit mode.

**To Reproduce**
1. Make a new note
2. Type in `- [ ] test bullet`
3. hit command-\` to turn preview on. (checkbox renders.)
4. hit command-\` to turn preview off. All that is visible is the text to the right of the checkbox.

**Expected behavior**
Checkbox markdown should remain editable in editing mode.

**Actual behavior**
The `- [ ] ` part is no longer present in the edit window.

Furthermore, it sort of acts like it is there; you can even delete it by hitting backspace at the beginning of the line; format -> toggle todo works correctly (toggling a strikeout in edit mode); if you go back into preview the checkbox is still there. If the file is synced with the phone app, you can edit and manipulate the checkbox on the phone.

When I reveal the md file in finder and open it directly in an editor, the file looks as it should.

**Workaround**
Edit on phone, or edit md file directly. Otherwise, haven't found anything.

**Supporting Files**
(sorry for inconsistent sizing on these screenshots)

Original md: ![Screenshot 2019-11-26 14 25 02](https://user-images.githubusercontent.com/6290753/69666175-d59a1480-1059-11ea-84c6-7d8080852304.png)

After toggle preview on: ![Screenshot 2019-11-26 14 25 08](https://user-images.githubusercontent.com/6290753/69666191-ddf24f80-1059-11ea-8e20-c5d0516ab1ee.png)

After toggle preview off: ![Screenshot 2019-11-26 14 25 18](https://user-images.githubusercontent.com/6290753/69666209-e480c700-1059-11ea-8ade-36303c2e7cfc.png)

After doing toggle todo: ![Screenshot 2019-11-26 14 25 40](https://user-images.githubusercontent.com/6290753/69666241-efd3f280-1059-11ea-9911-290bf29efa2d.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.12.6
 - FSNotes version: 4.0.7 (338)

**Comment by rawlins** [comment]
(actually, I realized after submitting this that maybe the expected behavior is something more like what the phone app does, where the checkbox is rendered graphically even in edit mode? I'm new to the app so I'm not sure what it used to do.)

**Comment by glushchenko** [comment]
Hi @rawlins, thank you for patience. Of course it was bug. Personally i recommend update macOS from Sierra to Mojave or higher. FSNotes working more stable and has features not available in 10.12.

**Comment by glushchenko** [comment]
Fixed in 4.0.9
