### ISSUE TITLE
File content replaced with previous edit

### ISSUE THREAD

**Issue by yene** [glushchenko/fsnotes#753]
There is a critical bug which I can not reproduce. It happens rarely but results in data loss. It goes something like this:

1. Open file `A.md`
1. Make changes to `A.md`
1. Change to file `B.md`
1. File `B.md` is **overwritten** on the filesystem with what was shown in the Editor View (Content of `A.md` + changes)
1. File `B.md` is openend in the editor view
1. The undo buffer of file `B.md` is empty

My guess is that is possible for power users to switch files during save and the content gets stored in the wrong file.

Another guess could be that it is possible to send input to the Editor View and Search at the same time, triggering a file change + save in the wrong order.

Version: 4.0.8

**Comment by glushchenko** [comment]
I think commit above should fix this

**Comment by glushchenko** [comment]
Please try 4.0.12
