### ISSUE TITLE
When deleting a note, ask for confirmation

### ISSUE THREAD

**Issue by npras** [glushchenko/fsnotes#754]
**Describe your feature request**
Given I have a note-file called "thoughts" among many other notes,
And I search for it in the "search-or-create" textbox by typing "thoughts" there,
And fsnotes lists all matching files and the top-result that is auto-selected is the one I want.

Now,

When my focus is still in the "search-or-create" textbox,
And I try to delete it by pressing the "cmd+delete" keys together,

**Then I want fsnotes to show me a warning popup with message "Are you sure you want to delete note `thoughts'?". The popup should have 2 buttons "delete" and "cancel". The "cancel" button should be on focus by default.
I'll have to press the tab key or use the mouse to click the "delete" button to actually delete the note.**

Currently the note-delete operation happens instantly as soon as I press "cmd+delete" keys. I can bring it back by pressing "cmd+z". But it happens so fast that I might not think about it or notice it if I delete the incorrect note.

Sometimes, my intention won't even be to delete the note. I just want to delete the text I typed so far in the "search-or-create" textbox by pressing "cmd+delete" keys. It's a normal UI pattern implemented in all textboxes in all software. Here in fsnotes we are overriding it to delete the note. That's fine as long as fsnotes warns me about the impending delete with a prompt dialog box.

**Additional context**
Add any other related information here. macOS or iOS?
It's in macOS app.

**Comment by scaba** [comment]
Deleted notes go into the Trash folder, which you need to manually empty, so this seems like it would just another redundant and annoying prompt. If you accidentally delete a note you can always click on the Trash folder and drag it back to wherever you want it to be. If it were disabled by default and you had to explicitly enable it in Preferences, then that would be ok.

**Comment by glushchenko** [comment]
⌘-z shortcut also can be useful fo revert deletion

**Comment by npras** [comment]
I see that when trying to delete from Trash, there's a confirmation popup asking if I'm sure.
This is comforting.

But it would still be nice to have a popup even when the note goes to trash because the "delete note" shortcut "cmd + delete" is actually a universal key action for deleting all text under the cursor upto the line's starting point. So when I'm in the "search or create" text box and type a note's name, pressing "cmd + delete" means I really want to delete (only) the text I'd entered so far, and not the note that was auto-selected by default.
I'm not asking to change the current behavior of the "cmd + delete" key. I like that it deletes a note. Just that a warning popup will train the user that "maybe this is not what you wanted, you sure?"

Anyway, this was just my opinion. I'm ok with this as is and grateful for the software. So closing this now.
