### ISSUE TITLE
Entering text in txt files isn't saved in preview mode

### ISSUE THREAD

**Issue by porteous42** [glushchenko/fsnotes#755]
This may be considered a bug... If you a viewing a plain text file in preview mode, you can enter new text into a note, but as soon as you select a different note, they text goes away, something you would not expect as a new user. I now have all of my notes as .md files (even if they are just plain text), so I cannot edit the files while in preview mode. I would suggest not allowing editing in preview mode for txt files, as to avoid the user thinking what they are typing will be saved. I would also suggest using a checkmark next to the "Toggle Preview" menu so you can tell if you are in preview mode or not. (or some other way to visually indicate when preview mode is active)
(FSnotes 4.0.7, MacOS)

**Comment by gingerbeardman** [comment]
Sounds like this is a bug in preview mode

**Comment by glushchenko** [comment]
Fixed in 4.0.9
