### ISSUE TITLE
GraphQL Code Doesn't Get Syntax Highlighting

### ISSUE THREAD

**Issue by stephencweiss** [glushchenko/fsnotes#756]
**Describe the bug**
The Preview of `graphql` doesn't seem to be working as expected

**To Reproduce**
1. Create a new note with a code block. Add the language of `graphql` -- for example:
\```graphql
 ... graphql code goes here
\```
2. Turn on preview (cmd + `)

**Expected behavior**
Syntax highlighting should appear as `graphql` is a supported Prism language

**Actual behavior**
It looks like code, but there's no syntax highlighting. 

**Workaround**
No workaround found for syntax highlighting. 

**Supporting Files**
- PrismJS languages: https://prismjs.com/#supported-languages

In Editor
<img width="864" alt="Screen Shot 2019-11-28 at 1 12 50 PM" src="https://user-images.githubusercontent.com/39878535/69828359-3ef85f80-11e1-11ea-811f-358c4f7eef94.png">

In Preview
<img width="864" alt="Screen Shot 2019-11-28 at 1 12 56 PM" src="https://user-images.githubusercontent.com/39878535/69828875-399c1480-11e3-11ea-9ab0-a978fc8368ca.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - FSNotes version: 4.0.8

**Comment by glushchenko** [comment]
Why bug? Seems this not declared in features ...

**Comment by stephencweiss** [comment]
I thought the features suggested that the syntax highlighting was for 179 prism languages.

**Comment by glushchenko** [comment]
https://github.com/highlightjs/highlight.js/tree/master/src/languages

**Comment by stephencweiss** [comment]
Cool, thank you!
