### ISSUE TITLE
Limit search to current folder

### ISSUE THREAD

**Issue by kerim** [glushchenko/fsnotes#757]
**Describe your feature request**

I would like search to initially work only on the currently selected folder, with the ability to expand to all documents if necessary. 

**Additional context**
Add any other related information here. macOS or iOS?

I have folders for different topics, and search across all folders means I get a lot of search hits that aren't relevant to what I am currently working on.

**Comment by gingerbeardman** [comment]
Done recently in https://github.com/glushchenko/fsnotes/issues/749
