### ISSUE TITLE
Suggestions for improved "Add Selection to FSNotes" service

### ISSUE THREAD

**Issue by kerim** [glushchenko/fsnotes#758]
**Describe your feature request**

Right now the "Add Selection to FSNotes" service just grabs plain text. It doesn't preserve links in the text and it doesn't preserve the URL of the source page. I would like an updated version that grabs selected text with markdown formatting so that links are preserved, and appends the URL of the source page (and perhaps the title as well?) at the bottom for future reference.

**Additional context**
Add any other related information here. macOS or iOS?

Would be good if there was a share extension on iOS that worked similarly. I haven't looked into this yet.

**Comment by gingerbeardman** [comment]
I tried this originally and Rich Text wouldn't work as a Service so I had to do Plain Text.

Any thoughts @glushchenko

**Comment by JimmyLv** [comment]
@gingerbeardman maybe just use markdown Plain Text syntax

**Comment by gingerbeardman** [comment]
@JimmyLv you misunderstand, I am already using Plain Text. 

We're trying to get it working using Rich Text so everybody is happy.

**Comment by gingerbeardman** [comment]
I tried this again and the problem is that Automator workflow receives only plain text from the browser.

We need some way of:
1. getting the rich text
2. converting it to markdown

Workarounds 
- HTML to Markdown, but it is too much to ask of users to copy HTML source rather than selected text

**Comment by kerim** [comment]
Would something like this help? 

http://heckyesmarkdown.com/ 

(There's an API.)

**Comment by gingerbeardman** [comment]
No worries, I have a first version working (with one caveat)

- works well!
- BUT line breaks are not currently respected

Feel free to open in Automator and try to improve what I have so far.

[Add Selection as Markdown to FSNotes.workflow.zip](https://github.com/glushchenko/fsnotes/files/4516022/Add.Selection.as.Markdown.to.FSNotes.workflow.zip)

Credits
- https://apple.stackexchange.com/questions/128106/how-can-i-convert-html-rich-text-to-markdown-in-automator

**Comment by gingerbeardman** [comment]
I had uploaded a broken version, fixed version now above.

**Comment by gingerbeardman** [comment]
Line breaks are removed in the part of the workflow that creates the URL. Trying to fix now.

**Comment by gingerbeardman** [comment]
Here we go!

Some AppleScript voodoo incantations solved it.

[Add Selection as Markdown to FSNotes.workflow.zip](https://github.com/glushchenko/fsnotes/files/4516615/Add.Selection.as.Markdown.to.FSNotes.workflow.zip)
