### ISSUE TITLE
Add GraphQL Language Syntax Highlighting

### ISSUE THREAD

**Issue by stephencweiss** [glushchenko/fsnotes#759]
**Describe your feature request**
Syntax highlighting for GraphQL would be helpful, but currently, there's not syntax highlighting for GraphQL - https://github.com/highlightjs/highlight.js/tree/master/src/languages

**Additional context**
This should apply to both macOS and iOS.

**Comment by stephencweiss** [comment]
Sorry - missed that the implication was that this was based on a dependency. 

Looks like `highlightjs` has a solution. Working with them to try to get it included in the main package. https://github.com/highlightjs/highlight.js/issues/1471

**Comment by glushchenko** [comment]
No problem
