### ISSUE TITLE
Bulk add inline tags

### ISSUE THREAD

**Issue by kerim** [glushchenko/fsnotes#761]
**Describe your feature request**
The ability to select multiple notes and add inline tags via either a pop-up menu or by dragging to the tag sidebar. (Should ideally include the ability to add new tags as well as apply existing ones.)

**Additional context**
Bear does this nicely.

**Comment by stephencweiss** [comment]
@kerim can you add a GIF? I came from Bear really recently and am not sure what this means.

**Comment by kerim** [comment]
1. Select multiple notes
2. Drag and drop on to a tag to add it. (Or use the contextual menu to remove a tag.)

(Sorry, I don't have time to make a GIF right now.)

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5b2/FSNotes_v5b2.zip
