### ISSUE TITLE
FSNotes 4.0.12 install on macOS Catalina

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#762]
I just installed the GitHub version of FSNotes 4.0.12 on my computer, which is running Catalina with all updates, and FSNotes refused to start. Instead I received the dialog, a screenshot of which is included below.

I was able to fix this by authorizing FSNotes to run in:

System Preferences > Security & preferences > General

So, I report this FWIW.

BTW, I did a search but couldn't find any previous mention of this. If I missed a previous issue on this my apologies.

<img width="420" alt="FSNotes" src="https://user-images.githubusercontent.com/35905279/70193700-31e5df80-16bd-11ea-9e87-1871243cc4fd.png">

**Comment by gingerbeardman** [comment]
I think (not 100% sure) you can also avoid the by using right click context menu to open the app for the first time:
https://www.fireebok.com/resource/how-to-fix-that-app-can-not-open-on-macos-catalina.html

And also by changing Gatekeeper options:
https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave

**Comment by stephencweiss** [comment]
@peavine, sounds like you got to the solution. Every time I update FSNotes, I have to repeat that process - which is a minor annoyance, but similar to other brew installed applications. 

For anyone who comes later, the only thing I'd add to @gingerbeardman's answer is that you don't need to totally turn off Gatekeeper as recommended by the imore.com article -- If you go follow the steps to view Gatekeepr ( System Preferences > Security & preferences > General as @peavine noted), you'll be able to authorize FSNotes and it will work correctly until you update again.

**Comment by peavine** [comment]
Thanks @gingerbearman and @stephencweiss for the suggestions. I don't have to have the absolute latest version of FSNotes, so I think I'll just install the App Store version, which I assume avoids this issue.
