### ISSUE TITLE
Cask checksum does not match

### ISSUE THREAD

**Issue by RudStar** [glushchenko/fsnotes#763]
Cask checksum for 4.0.12 does not match.
Expected: 15a187621a3ffde79d5365219e0de7c45d5d11a939db09a62a3ec1a096c69215
Actual: ca4037c70a90f8026c7d69eaab180286e22da601c79a0fbcde333f5ef71d54b4
File: /.../fe7d920e35eb927ddceafbd7e0b4ed441ab08d5b39af9668f1bfe5dcc2df6d54--FSNotes_4.0.12.zip

**Comment by glushchenko** [comment]
Yes, build was reuploaded. Cask not in my hands so, sorry.

**Comment by stephencweiss** [comment]
@RudStar I ran into the same issue. Tried updating it here: https://github.com/Homebrew/homebrew-cask/pull/73769

Have you tried repulling since?

**Comment by RudStar** [comment]
Yes, everything is okay now.
First deleted the loaded file with the wrong checksum and then a `brew update`...
Thank you
