### ISSUE TITLE
Markdown Preview CSS isn't working

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#764]
**Describe the bug**

Custom markdown CSS file isn't working for me.

**To Reproduce**

1. I created a file for some custom markdown preview CSS at `/path/to/my/notes/markdown.css` containing the following lines:
```css
body {
    color: red !important;
    text-transform: capitalize !important;
}
```
2. I added this file to the _Markdown Preview CSS_ file selector in the settings. 
3. I quit and re-opened FSnotes.
4. I opened a .md note and turned on preview mode. 
5. The default styles displayed. Type was not red, nor capitalized.

**Expected behavior**

The type in my preview window should be red, and capitalized.

**Actual behavior**

No change to the styles.

**Workaround**

🤷‍♂️

**Supporting Files**

See css file contents above.

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.14.6
 - FSNotes version: 4.0.11 (343)

**Additional context**
BTW, I don't really want red and capitalized text, I tried other CSS too, nothing works. My goal is to add CSS to change the size of the type when printing a preview page.

**Comment by glushchenko** [comment]
Fixed in 4.0.14
