### ISSUE TITLE
Feature Request: Text Expansion on MacOS

### ISSUE THREAD

**Issue by stephencweiss** [glushchenko/fsnotes#765]
**Describe your feature request**

FSNotes should respect local text replacement / text expansion settings.

**Additional context**
Add any other related information here. macOS or iOS?
macOS has native text replacement in the system settings for keyboard. While this is functionality works in apps like Notes and Mail (and other note apps like Bear), it's not working in FSNotes

GIF: https://media.giphy.com/media/ideob6OMZVwjYudFLx/giphy.gif

https://www.techjunkie.com/text-replacement-mac/

Interestingly, this does seem to work on iOS
![IMG_1FA3D8128F82-1](https://user-images.githubusercontent.com/39878535/70381871-8be1e180-1917-11ea-8a58-5814538cd990.jpeg)

**Comment by bugpowder** [comment]
Did something change in FSNotes in this regard?

Text expantion (macOS native one) used to work for me until recently.

Now, on my new M1 it doesn't. But this issue implies it never worked?

**Comment by gingerbeardman** [comment]
Works for me in Big Sur 11.4

Check your settings through Substitutions in context/edit menu

<img width="400" alt="Screen shot 2021-06-07 at 16 18 29" src="https://user-images.githubusercontent.com/49612/121042929-12e17580-c7ac-11eb-807b-267fe17d1090.png">

**Comment by bugpowder** [comment]
@gingerbeardman Thanks, that was it! Apparently you need to re-enable it per-app for a new install!

**Comment by gingerbeardman** [comment]
Oh! Thanks for that info.
