### ISSUE TITLE
Cmd+click links to open them in the background

### ISSUE THREAD

**Issue by fturcheti** [glushchenko/fsnotes#766]
**Describe your feature request**
There a times when I want to open multiple links listed on a note. And when this happens, it's really handy to be able to open them in the background by command-clicking them. This way, instead of the ping-pong game of `click → go to browser → go back to FSNotes → click → goto browser → go back FSNotes…`, I can just `cmd+click, cmd+click, cmd+click → go to browser`.

I use other applications that provide this feature, command-clicking to open links in background, so it seems to be a common pattern in macOS.

**Additional context**
I'm talking about the macOS version, but iOS could present a similar feature by displaying a "Open in background" option when long-pressing a link.

**Comment by glushchenko** [comment]
Added in 4.0.17

**Comment by fturcheti** [comment]
Cool! It's working as expected. Thanks @glushchenko!
