### ISSUE TITLE
Clicking email address link opens web browser for email domain

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#767]
**Describe the bug**
Clicking an email address in FSNotes opens the web browser:

<img width="272" alt="Screen Shot 2019-12-16 at 17 40 21" src="https://user-images.githubusercontent.com/6884276/70952302-75c8d500-202b-11ea-9bbf-16b5e36f73d9.png">

**To Reproduce**
1. Enter `hello@example.com` in a note.
2. Click it.

**Expected behavior**
I expect my email program to open (as if the link were `mailto:hello@example.com`

**Actual behavior**
It opens http://example.com.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.12

**Comment by gingerbeardman** [comment]
I guess it needs to prepend email links with `mailto:` ?

**Comment by glushchenko** [comment]
https://en.wikipedia.org/wiki/URL

By default if scheme not provided we use http://[userinfo@]host[:port]

**Comment by gingerbeardman** [comment]
But

> URLs occur most commonly to reference web pages (http), but are also used for file transfer (ftp), email (mailto), database access (JDBC), and many other applications.

**Comment by relikd** [comment]
Agreed, looks like a bug to me. Every other App considers email addresses and acts accordingly. I would prefer each "URL" that contains an at (@) but not a slash (/) nor a colon (:) to be an email address. And if someone really means a web url they can prepend http: or ssh: or whatever. Prepending mailto: to each email address seams absurd if you only want to save contact information.

**Comment by glushchenko** [comment]
Fixed in 4.0.14
