### ISSUE TITLE
Formatting text as Underline has strange behavior in dark mode.

### ISSUE THREAD

**Issue by hellonoko** [glushchenko/fsnotes#769]
Sometime making text underlined in dark mode leave the underline line as black not white. Seems OK in light mode.

![Screen Shot 2019-12-21 at 1 44 12 PM](https://user-images.githubusercontent.com/4123025/71314162-74ffbc80-23f8-11ea-9971-f9553a039f53.png)

Also formatting text removes the text selection after the action is completed. This is annoying if you want to do multiple formatting options to selected text.

**Comment by glushchenko** [comment]
Finally fixed, thanks.
