### ISSUE TITLE
Delayed showing of notes in 1.1.17

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#77]
The timer introduced in v1.1.17 has introduced a delay in the selection of the note that matches your search. In prior versions the instant you type in the search field, the best matching note is highlighted in the notes list and the note body is shown.

In 1.1.17, as soon as you enter a character in the search, the notes list is filtered instantly, but there's a delay before the best matching note is selected and shown.

Can I ask what this is for? I personally dislike it pretty intensely heheh

**Comment by glushchenko** [comment]
"Code highlighting" feature is a little bit slow operation, and "notes" auto filling on every char pressed, in search field , reduce speed search. 

But, now timer moved to code highlighting. "Search" works fast as before.

**Comment by jeff-h** [comment]
Wonderful :)
