### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by BenjaminHoegh** [glushchenko/fsnotes#770]
I get these two errors when I try to build/run the code in Xcode 11.3

`error: /FSNotes/Pods/Target Support Files/Pods-FSNotesCore macOS/Pods-FSNotesCore macOS.debug.xcconfig: unable to open file (in target "FSNotesCore macOS" in project "FSNotes") (in target 'FSNotesCore macOS' from project 'FSNotes')`

And

`error: /FSNotes/Pods/Target Support Files/Pods-FSNotes/Pods-FSNotes.debug.xcconfig: unable to open file (in target "FSNotes" in project "FSNotes") (in target 'FSNotes' from project 'FSNotes')`

I'm new at Xcode so if this is because of some settings I need to change please guide me

**Comment by glushchenko** [comment]
Sorry, I don't know. For me works fine on 11.3

**Comment by fish0il** [comment]
> I get these two errors when I try to build/run the code in Xcode 11.3
> 
> `error: /FSNotes/Pods/Target Support Files/Pods-FSNotesCore macOS/Pods-FSNotesCore macOS.debug.xcconfig: unable to open file (in target "FSNotesCore macOS" in project "FSNotes") (in target 'FSNotesCore macOS' from project 'FSNotes')`
> 
> And
> 
> `error: /FSNotes/Pods/Target Support Files/Pods-FSNotes/Pods-FSNotes.debug.xcconfig: unable to open file (in target "FSNotes" in project "FSNotes") (in target 'FSNotes' from project 'FSNotes')`
> 
> I'm new at Xcode so if this is because of some settings I need to change please guide me

The same error... I sloved
try type command follows:
pod  deintegrate
pod  install
