### ISSUE TITLE
Remove URL from note does not work / saves / remembers state

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#771]
**Describe the bug**
I have a note with an email address in it. I try to delete the link from the email address (which works) but as soon as I change the note and come back, the URL was added again.

**To Reproduce**
1. Create new note
2. Paste `my@email.com`
3. Right click 'Remove Link'
4. Change to another note, then select this note again

**Expected behavior**
Email should not be clickable.

**Actual behavior**
Email address is a clickable link.

**Workaround**
Save as plain text, which in turn does not allow to style the note.

**Supporting Files**
None.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.0.12 (344)

**Additional context**
Also, please make the version number in the about view selectable so we can copy & paste from there (for this bug report).

**Comment by glushchenko** [comment]
Submenu "Remove Link" and "Edit Link" removed. For markdown we can not save link states. Links highlights automatically by syntax parser.

Version number now selectable.
