### ISSUE TITLE
Markdown formatting broken for code snippets

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#772]
**Describe the bug**
Formatting precedence is not respected. Asterisk inside code block should not be evaluated.

**To Reproduce**
1. Create new note and paste:
```
```ls ${*}``` this shouldn't be italic `ls ${*}`
```

**Expected behavior**
The text in between should not be italic but it is.

**Actual behavior**
As described. Text shouldn't be italic. Here is the Github output with the exact same input:

```ls ${*}``` this shouldn't be italic `ls ${*}`

**Workaround**
N/A

**Supporting Files**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.0.12 (344)

**Additional context**
N/A

**Comment by stephencweiss** [comment]
Found another example of this I think.

In Markdown, text between `_` is italicized in highlighted portion.

![Screen Shot 2020-02-09 at 2 54 24 PM](https://user-images.githubusercontent.com/39878535/74109871-05cb5c80-4b4d-11ea-8305-99321018884d.png)

Render correctly identifies that the first `_` is in a code block and doesn't italicize text. 

![Screen Shot 2020-02-09 at 2 54 38 PM](https://user-images.githubusercontent.com/39878535/74109870-0532c600-4b4d-11ea-9d28-34fd1dbecd4c.png)

**Comment by glushchenko** [comment]
Fixed here https://github.com/glushchenko/fsnotes/issues/1065

**Comment by tewe** [comment]
It looks like this was only fixed for underscores, not asterisks. Here is 6.8.1.
<img width="547" alt="CleanShot 2024-06-23 at 01 10 55@2x" src="https://github.com/glushchenko/fsnotes/assets/645412/cdd3a91b-929b-4962-a4c6-4bed0edd332c">
