### ISSUE TITLE
Issue when creating new note. Title clipped / cropped / truncated

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#773]
**Describe the bug**
When creating a new note via search bar, every character after the curser is dropped.

**To Reproduce**
1. Click on search bar.
2. Enter some text, e.g., 'Hello World'
3. Click/move the cursor between the two 'l'
4. Hit enter/return

**Expected behavior**
New note should have the title 'Hello World'.

**Actual behavior**
New note with title 'Hel' is created.

**Workaround**
N/A

**Supporting Files**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.0.12 (344)

**Additional context**
N/A

**Comment by glushchenko** [comment]
Fixed thanks
