### ISSUE TITLE
Paragraph indentation for indented bullet lists

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#774]
**Describe your feature request**
Not sure if this should be a bug report or a feature request. However, any indented item (whether bullet list or something else) should also indent any subsequent lines.

Here is an example. the `JHFS` should be indented to the same x position as the \``diskutil`

![screen](https://user-images.githubusercontent.com/1321720/71649343-329a8180-2d0e-11ea-911f-216d17df773c.png)

**Additional context**
Using macOS version 4.0.12.

**Comment by crankygeologist** [comment]
Thanks for suggesting this. This would be very helpful to improve the readability of multi-line ordered and unordered lists.

**Comment by glushchenko** [comment]
Thanks, implemented.

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by relikd** [comment]
Indentation works, though I would remove the background color for the indentation

![screen](https://user-images.githubusercontent.com/1321720/125194911-a26ac000-e253-11eb-8686-5c9a807de7ce.png)

**Comment by glushchenko** [comment]
We can not, this is the part of markdown syntax.

![image](https://user-images.githubusercontent.com/1089917/125195446-56714880-e25e-11eb-8158-73fa73a8e146.jpeg)

**Comment by relikd** [comment]
alright, it is better already, just a little confusing. I am happy for the fix anyway =)

*but*, here is how github displays it:

![screen](https://user-images.githubusercontent.com/1321720/125195616-b4019700-e256-11eb-90e0-a0b8b4e44e8f.png)

Similarly, your preview works the same. Just not in edit mode.

![screen](https://user-images.githubusercontent.com/1321720/125195692-093da880-e257-11eb-9111-4bd60278b58b.png)

BTW, the beta version has an issue with bullet lists in preview mode. They are lacking indentation which was there in 4.10.2 (see screen above).

**Comment by relikd** [comment]
Interesting enough, I have found two edge cases.

It seems that if error highlighting is on, the indentation background color is actually correct:

![screen1](https://user-images.githubusercontent.com/1321720/127342841-960eee10-7ee1-4ae5-8030-b268b7f637a9.png)

I have no clue why the second example is not breaking and indenting properly. There is a lot of whitespace where it could break but somehow the parenthesis prevent that. Also, I am clueless why the indentation is dropped for this example only:

![screen2](https://user-images.githubusercontent.com/1321720/127342845-bc4d2ece-49c7-4400-a0f2-1b92d4659225.png)
