### ISSUE TITLE
Issue with mutiple lists and checkboxes

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#775]
**Describe the bug**
This regards the markdown preview.
Parsing of a combination of checkboxes and bullet lists does not seem to work properly.

**To Reproduce**

Here are four inputs that produce unexpected results. All are missing bullet points. Once there is an empty line between those two lists (input 3 & 4) it starts breaking the checkboxes too...

Input 1:
```
- some
- here
- [ ] checkbox1
- [ ] checkbox2
```
Output 1:
![1](https://user-images.githubusercontent.com/1321720/71649591-72faff00-2d10-11ea-9bdf-d9ab4af911db.png)

Input 2:
```
- [ ] checkbox1
- [ ] checkbox2
- some
- here
```
Output 2:
![2](https://user-images.githubusercontent.com/1321720/71649596-78584980-2d10-11ea-9a82-145e9220d054.png)

Input 3 :
```
- some
- here

- [ ] checkbox1
- [ ] checkbox2
```
Output 3:
![3](https://user-images.githubusercontent.com/1321720/71649610-a0e04380-2d10-11ea-9ce3-ab0502395b8f.png)

Input 4 :
```
- [ ] checkbox1
- [ ] checkbox2

- some
- here
```
Output 4:
![4](https://user-images.githubusercontent.com/1321720/71649615-a76ebb00-2d10-11ea-8cb4-ae426c0fb930.png)

**Workaround**
N/A

**Supporting Files**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.0.12 (344)

**Additional context**
N/A

**Comment by glushchenko** [comment]
Please make request here: https://github.com/github/cmark-gfm. I am not a renderer developer.
