### ISSUE TITLE
Blurry image preview / low resolution

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#776]
**Describe the bug**
A local image file in edit mode is displayed rather blurry on my retina display. I guess it uses the same width as the displayed size neglecting the higher pixel density. This results in a blurry image where I can hardly read anything at all. In markdown preview mode the image is displayed properly (I guess with full resolution).

Also, in edit mode, the image does seem to be downscaled to a fixed size and centered. Whereas in preview mode the image takes the full width of the window.

**Workaround**
N/A

**Supporting Files**
Edit Mode:
![1](https://user-images.githubusercontent.com/1321720/71650309-544b3700-2d15-11ea-8d91-f1634a443464.png)

Markdown Preview:
![2](https://user-images.githubusercontent.com/1321720/71650308-544b3700-2d15-11ea-8e3b-4dbc1338975a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.0.12 (344)

**Additional context**
N/A

**Comment by glushchenko** [comment]
Fixed in 4.0.13
