### ISSUE TITLE
Deselecting a tag in the sidebar doesn't remove filter

### ISSUE THREAD

**Issue by rtimmons** [glushchenko/fsnotes#779]
Thank you for your work on FSNotes and a happy new year to you. I am starting to use it instead of nvAlt and liking it so far.

**Describe the bug**
Deselecting a tag in the sidebar doesn't remove filter

**To Reproduce**
1. Create a new folder
2. Create 2 documents: one with #tag1 and another with #tag2. Both tags show up in the sidebar.
3. Select tag1 on the sidebar
4. Command-click or do *anything* to try to unselect tag1 so the #tag2 note displays

**Expected behavior**
No notes are filtered by tag - both notes should be visible.

**Actual behavior**
The tag1 tag filter is still applied

**Workaround**
- Do a search (Command-L) for anything and then clear the search (select all + delete)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.12 (344)

**Comment by glushchenko** [comment]
Thanks for bug report, happy new year, @rtimmons.

**Comment by glushchenko** [comment]
Fixed in 4.0.13
