### ISSUE TITLE
Fine-tuned esc behaviour

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#78]
I am wondering if it would be possible to modify the behaviour of the `esc` key. At the moment, it provides a quick way to enter a new search term by placing the cursor in the search field, and removing any text entered there.

Would it be possible to have it place the cursor in the search field (as it does now) but selecting it, instead of deleting the text there. This would allow you to type a new search term as you can do currently (thus replacing the selected search text), but would also mean you could easily modify an existing search by pressing the left or right cursor key and continuing to type.

**Comment by glushchenko** [comment]
Why not use ⌘-L ?

**Comment by jeff-h** [comment]
Ha — never knew about ⌘-L before! That's exactly what I was hoping for. Still, I think there'd be no downside to doing the exact same thing with the `esc` key. Is there a specific upside to clearing the filter text?

**Comment by jeff-h** [comment]
With time to think this over more I think the current solution is fine.
