### ISSUE TITLE
Title (filename) disappears when creating new notes from search

### ISSUE THREAD

**Issue by rtimmons** [glushchenko/fsnotes#780]
Thank you for your work on FSNotes. I hope this bug-report is helpful.

**Describe the bug**
Title (filename) disappears when creating new notes from search

**To Reproduce**
1. Create a new folder and select it in the sidebar
2. Command-L to search for `Something` (a term without any matches)
3. Enter to create the note. (Note: sometimes the focus is entirely lost at this point and requires a mouse-click in the notes-list but that's likely a separate bug.)
4. Enter `foo` as the note text.
5. Click in the notes list to unselect the note.
6. Command-L to search for foo

**Expected behavior**
The note title (`Something`) is visible

**Actual behavior**
- The note title is not visible
- You can still search for `Something` (the note title/filename) and the note is found but the title is not displayed

**Workaround**
- Restart FSNotes
- Command-R to rename the note (the title field is populated as empty), then press escape.)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.12 (344)

![DisappearingTitle](https://user-images.githubusercontent.com/119094/71782182-54616600-2fa5-11ea-85b8-825a9012f4c0.gif)

**Comment by glushchenko** [comment]
Fixed in 4.0.13
