### ISSUE TITLE
Creating notes from search doesn't let you edit note content

### ISSUE THREAD

**Issue by rtimmons** [glushchenko/fsnotes#781]
Thank you for your time. I hope this is helpful.

**Describe the bug**
Creating notes from search doesn't let you edit note content

**To Reproduce**
1. Create a new folder.
2. Command-L to create a new note.
3. Enter `Something` and press enter to create a new note.

**Expected behavior**
The new "Something" note is selected and the cursor is in the note editor.

**Actual behavior**
The search bar is still focused, and it's not possible to use tab or enter to edit the note content like it normally is if the search term is matched.

**Workaround**
Use the mouse to select the newly-created note or search 

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.12 (344)

**Additional context**
1. In the attached screenshot gif at the end I am trying to press tab, enter, down arrow, ... to actually edit the newly-created note but nothing works.
2. Pressing escape deselects the "Example" folder from the sidebar and then all newly-created notes go to the "Inbox" and all searches happen everywhere rather than being limited to just that folder.
3. Additionally it doesn't seem possible to change the folder using the keyboard, only the mouse, so every time I search-to-create a new note I have to use the mouse or all my notes after that point end up in the inbox. That may be a separate bug or feature-request but that would be less necessary if this bug were fixed.

Thank you.

![SearchToCreate](https://user-images.githubusercontent.com/119094/71782518-d1420f00-2fa8-11ea-8b29-675664d342bb.gif)

**Comment by rtimmons** [comment]
I was able to reproduce this over and over again in creating this bug-report, but I tried again just now and it's working as expected.
Actually no it's happening again now and is being especially unfriendly when combined with #780 😸

**Comment by glushchenko** [comment]
I can not reproduce this bug :/

**Comment by rtimmons** [comment]
Thanks for taking a look.

Playing around with settings I noticed that this does not ever happen if the "Note auto selection when body text matched" is **not** checked, but it does happen when that box **is** checked. 
I can list the additional settings (or attach my settings plist if I can ever remember where MAS apps put those these days). If that would help just let me know.

However when that box is not checked, the delete shortcut (Command+Backspace) doesn't work to delete notes. This is better than not being able to create notes or deselecting the folder from the sidebar, but it's less than ideal.

If anything I hope this helps to repro. I'd be happy to send along additional information if it would be helpful.

Thanks again for your time and for your continued work on FSNotes.

**Comment by glushchenko** [comment]
Fixed in 4.0.14
