### ISSUE TITLE
Automatic Backups should be able to be scheduled by an interval

### ISSUE THREAD

**Issue by BeWe11** [glushchenko/fsnotes#783]
**Describe your feature request**
Currently, when turning on the automatic backup, the backup is performed once a day at "HOUR:MINUTES" (even though the text implies a different behavior). I think it would be useful if instead of giving a time on a day, a frequency could be provided as well, something like "backup all notes every full hour".

**Comment by gingerbeardman** [comment]
FWIW if you have Time Machine active then you already have hourly backups (on external disk) or snapshots (on internal disk).

**Comment by glushchenko** [comment]
No, backups performed every hour.

**Comment by BeWe11** [comment]
Hey @glushchenko,

what do you mean with your reply? That you won't change the current behavior or that the backups already should be performed every hour?

If the current behavior is actually intended to perform backups hourly, then maybe I should create a bug report instead, because that's definitely not working for me.

**Comment by glushchenko** [comment]
Backups already should be performed every hour.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/1089917/72097403-fcb85700-3324-11ea-8130-3b8f32a7436d.png">

In example above at:

00:05
01:05
...
23:05

**Comment by BeWe11** [comment]
Hey @glushchenko ,

this is a screenshot of my settings:
<img width="472" alt="Screen Shot 2020-01-10 at 14 10 14" src="https://user-images.githubusercontent.com/14355528/72155240-fec8f700-33b2-11ea-8efe-94436c807049.png">

FSNotes is always open in the background and I frequently make changes to several notes.

Still, the git log of the backup repository looks like this:
<img width="555" alt="Screen Shot 2020-01-10 at 14 12 13" src="https://user-images.githubusercontent.com/14355528/72155344-39329400-33b3-11ea-90fd-d0a42f5edda9.png">

No backup commits have been performed for several days, even though FSNotes was open all the time and I made changes to notes. The one single "Scheduled snapshot" commit happend when I entered `18 hour at 10 minutes` in the backup settings a few days ago (I'm at UTC+1).

This is why I wondered whether the setting specifies a time instead of a frequency.

**Comment by glushchenko** [comment]
OK, how i should reproduce it? Did you try last build 4.0.15?

**Comment by relikd** [comment]
Kind of related, but maybe another feature request. Could you add an option to disable backups completely? I've set it to manually but from time to time I hit ⌘R accidentally (which creates a backup). Also the backup folder is created regardless of any content, this could be postponed until an actual backup is made.

**Comment by glushchenko** [comment]
Finally, i found a bug!

**Comment by BeWe11** [comment]
Thank you @glushchenko !
