### ISSUE TITLE
Auto git backup not working

### ISSUE THREAD

**Issue by h-jia** [glushchenko/fsnotes#785]
**Describe the bug**
- Added My repository in a local folder (not cloud folder), and change contents and added MD files via FSNote. 
- Changed git repository in FSNote to My repository. 
- Clicked ```Back up every 0 hours at 5 minutes```. 

Auto minutes/hours git backup not working. Tested via 5, 10, 15 mins and 1 hour.

***

**Expected behavior**
 Should be backed up to my GitHub repository after 5 minutes if not misunderstood.

***

**Actual behavior**
Not backed up. While adding a folder called ```e9a1 - FSNotes.git```

***

**Workaround**
Changed repository to other folders and other time intervals.

***

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.2
 - FSNotes version: 4.0.12 (344)

**Comment by gingerbeardman** [comment]
Dupe of #783
