### ISSUE TITLE
New install on Catalina fails to open (possibly due o notarization)

### ISSUE THREAD

**Issue by pslobo** [glushchenko/fsnotes#786]
**Describe the bug**
After installing a new version of FSNotes (or updating an existing working version), we are greeted with the following "error" message. 

![Screenshot 2020-01-08 at 14 17 23](https://user-images.githubusercontent.com/1452095/71984867-9a2a6280-3221-11ea-9b24-d5a15133f60b.png)

This is possibly due to issues with notarization, however I was under the impression that was already solved for Mojave.

**To Reproduce**
1. Install FSNotes via `brew cask install fsnotes` (or download via github release)
2. Open FSNotes normally (not using any of the workarounds)

**Expected behavior**
FSNotes should open normally.

**Actual behavior**
Mac OS displays the above error and we are forced to open the app via known workarounds

**Workaround**
Right click on FSNotes and choose open or go to System Preferences > Security and allow execution

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.2
 - FSNotes version: 4.0.14 (also happens on 4.0.13 and 4.0.12)

**Additional Notes**
```
spctl -v -a /Applications/FSNotes.app
/Applications/FSNotes.app: accepted
source=Developer ID
```

**Comment by pslobo** [comment]
If needed, for troubleshooting, I have another machine where FSNotes hasn't been updated and is working as expected (was upgraded from Mojave to Catalina with FSNotes already installed and working)

**Comment by gingerbeardman** [comment]
Can you try this:

```bash
xattr -cr "/Applications/FSNotes.app"
open "/Applications/FSNotes.app"
```

This removes App Translocation. I have the same problem, for this and many other apps, and am yet to find a permanent solution other than this workaround.

**Comment by gingerbeardman** [comment]
Could it be that only the Mac App Store version has been notarised and the interim releases are not notarised? Does notarisation need to be done with every release?

**Comment by pslobo** [comment]
Not entirely sure how the notarisation works, but I'm under the impression that each new version is notarised and it probably part of the build process.

**Comment by glushchenko** [comment]
I don't know why this going on. Every release notarized already.

> Dear Oleksandr,
> Your Mac software has been notarized. You can now export this software and distribute it directly to users.
> Bundle Identifier: co.fluder.FSNotes

**Comment by pslobo** [comment]
Very weird indeed!

This is what I see on the other Mac which has been updated to catalina, but I still haven't updated FSNotes:

```
~ % brew cask info fsnotes
fsnotes: 4.0.12
https://fsnot.es/
/usr/local/Caskroom/fsnotes/4.0.12 (121B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/fsnotes.rb
==> Name
FSNotes
==> Artifacts
FSNotes.app (App)
~ % spctl -v -a /Applications/FSNotes.app
/Applications/FSNotes.app: accepted
source=Notarized Developer ID
```

**Comment by glushchenko** [comment]
Please re-download 4.0.15

**Comment by pslobo** [comment]
Yep, that fixed it!

```
λ brew cask info fsnotes
fsnotes: 4.0.15
https://fsnot.es/
/usr/local/Caskroom/fsnotes/4.0.15 (121B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/fsnotes.rb
==> Name
FSNotes
==> Artifacts
FSNotes.app (App)

~
λ spctl -v -a /Applications/FSNotes.app
/Applications/FSNotes.app: accepted
source=Notarized Developer ID
```

**Comment by gingerbeardman** [comment]
> Please re-download 4.0.15

What was the problem?

**Comment by glushchenko** [comment]
@gingerbeardman i incorrectly exported build from xcode :-)
