### ISSUE TITLE
Unable to Rename File

### ISSUE THREAD

**Issue by MMontelimar** [glushchenko/fsnotes#787]
**Describe the bug**
Currently unable to rename files. 

**To Reproduce**
1. Select "file name" in "notes list" with arrow keys OR by clicking on "file name". 
2. Right click on file name in "notes list" and select "rename" from drop down menu OR hit "command R". 
3. Type "new file name". 
4. Hit "return". 
5. "File name" is unchanged. 

**Expected behavior**
Expected "file name" to change to "new file name". 

**Actual behavior**
"File name" does not change. 

**Workaround**
Rename the file in the Finder. 

**Supporting Files**
None

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.1
 - FSNotes version: 4.0.14 (346)

**Additional context**
None.

**Comment by glushchenko** [comment]
Thank you @MMontelimar, fixed.

**Comment by glushchenko** [comment]
Please try this build https://github.com/glushchenko/fsnotes/releases/download/4.0.15/FSNotes_4.0.15.zip
