### ISSUE TITLE
Inline Images are upside down and Mirrored

### ISSUE THREAD

**Issue by igutekunst** [glushchenko/fsnotes#788]
**Describe the bug**
On a fresh install of FSNotes from the App Store, I noticed all inline images are upside down and mirrored.

**To Reproduce**
1. Install FSNotes on Mac OS 10.14.6. 
2. Open up the example note "5. Sidebar"

**Expected behavior**
The example note and included image display correctly.

**Actual behavior**
The images display upside down and in mirror image. 

**Workaround**
None. I will consider installing Catalina, but have been holding off since I've heard some things don't work so well. 

**Supporting Files**

** Screenshot**
<img width="785" alt="FsNotes-mirror-image-screenshot" src="https://user-images.githubusercontent.com/657081/72181651-a982ea80-339e-11ea-8216-539dd06c695e.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.15

**Additional context**

I could try building from source if that might help debug this issue, but I am happy to pay for this since it looks great!

**Comment by glushchenko** [comment]
Reproduced on Mojave. Thanks

**Comment by glushchenko** [comment]
Please try 4.0.16

**Comment by igutekunst** [comment]
Thanks! I didn't have notifications on, so I didn't see how fast you fixed it!
