### ISSUE TITLE
Auto-sort or menu item to re-sort?

### ISSUE THREAD

**Issue by wyaqoob** [glushchenko/fsnotes#791]
If I understand current FSNotes behaviour correctly, if the user wants a new note to be sorted immediately, they have to click the relevant 'sort by' submenu item. They then have to click it again to have the notes list sorted in the previously selected order (i.e. ascending or descending).

Would it be possible for FSNotes to auto-sort notes on a timed basis, set in preferences: in other words the app would auto-sort the note list after x number of seconds? 

Another half solution would be to have a menu item to force the sorting the notes list, so the user doesn’t have to go to the menu twice to sort.

**Comment by gingerbeardman** [comment]
So do you mean that a newly created note does is not placed correctly in the sorted list?

**Comment by wyaqoob** [comment]
Yes - on 4.0.17 (352), when Sort by > Title is selected, new notes are not placed correctly in the sorted list. e.g. right now I have ’test’ placed between ‘dictation’ and ‘film’. When I restart the app, the note is correctly placed.

**Comment by glushchenko** [comment]
Please try 4.0.18

**Comment by wyaqoob** [comment]
> Please try 4.0.18

Works great now. Thanks!
