### ISSUE TITLE
Font size in iOS

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#792]
**Describe your feature request**
Fsnotes in iOS allows me to change the editor font family. However, I don't able to find the option to change font size.

Currently there is no section jumping through a "table of content", and I would like to change the font to be smaller to help navigating a longer note.

Font sizing is discussed in https://github.com/glushchenko/fsnotes/issues/377, and I suppose this setting should have already added. I wonder am I missing something?

**Additional context**
iOS 13.3, fsnotes 3.1.5 build 155

**Comment by glushchenko** [comment]
Did you try Dynamic Type fonts settings?

**Comment by jakemkc** [comment]
hm... I don't see it in the "view" setting and "settings" of fsnotes in my phone, is it hidden somewhere..?

**Comment by gingerbeardman** [comment]
It's global iOS setting in Accessibility

**Comment by jakemkc** [comment]
It doesn't work well. Setting in accessibility affects the whole phone..

**Comment by glushchenko** [comment]
OK, @jakemkc added in todo.

**Comment by glushchenko** [comment]
Please, try 3.2.0

**Comment by jakemkc** [comment]
Thanks @glushchenko 

Just updated to 3.2, and it works well! 

Note: You need to go to Fsnotes -> settings -> dynamic type to change font size.
