### ISSUE TITLE
Todo section to show only non-completed tasks

### ISSUE THREAD

**Issue by jakemkc** [glushchenko/fsnotes#793]
**Describe your feature request**
We have a Todo section in the upper left of the app that can display all the notes with todo toggled. 

However, it doesn't ignore those notes with all the toggled todo checked. I could have notes with toggled todo all checked still displayed in the Todo section.

Showing only the unchecked tasks in the Todo section should make it more useful.

**Additional context**
This is a behavior found in both MacOS and iOS versions of Fsnotes.

MacOS: 10.14.6, fsnotes 4.0.12 (344)
iOS 13.3, fsnotes 3.1.5 build 155

**Comment by shawnaxsom** [comment]
I have a PR up to fix this. The Todo sidebar doesn't have much value to me either without being able to remove finished Todo notes. I have it fixed for both macOS and iOS.

**Comment by glushchenko** [comment]
Thank you, @shawnaxsom
