### ISSUE TITLE
Add ability to sponsor FSNotes via GitHub

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#798]
@glushchenko, is it possible and desirable to add a `Sponsor` button to the fsnotes project in GitHub? 

Example:

<img width="622" alt="Screen Shot 2020-01-21 at 20 38 49" src="https://user-images.githubusercontent.com/6884276/72858314-62de9b80-3c8e-11ea-81c3-d83847868089.png">

This would enable people like myself who prefer to install via `brew` but still want to send some money to you.

**Comment by gingerbeardman** [comment]
It's an application-based process and there's apparently quite a wait list.

https://github.com/sponsors

**Comment by DJM0** [comment]
@gingerbeardman You can still have the sponsor button without using GitHub Sponsors: https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

Lots of projects use Liberapay, Open Collective, Patreon etc..

**Comment by gingerbeardman** [comment]
Good spot!

**Comment by glushchenko** [comment]
I can add Patreon for feature requests, i.e. 2 $ for month?

**Comment by glushchenko** [comment]
https://www.patreon.com/hlushchenko

**Comment by glushchenko** [comment]
Thanks @quinncomendant you are first.
