### ISSUE TITLE
Markdown renders text between dollar signs

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#799]
**Describe the bug**
The text between the dollar signs ($) in the following text is rendered as italics with spaces removed:

    **Subscription cost:** $20/user/month (e.g., 7 users = $1680/year)

Screenshot:

<img width="494" alt="Screen Shot 2020-01-21 at 21 28 39" src="https://user-images.githubusercontent.com/6884276/72860742-c3bda200-3c95-11ea-8281-a777ff2c39f0.png">

**To Reproduce**
1. Create a new note
2. Paste in the text above
3. Enter preview mode

**Expected behavior**
Dollar signs should not have special meaning in Markdown.

**Actual behavior**
The text is italic, and spaces are removed.

**Workaround**
Use the emoji dollar sign 💲 instead of $. 🤷‍♂️

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.18 (354)

**Comment by glushchenko** [comment]
Text detected as MathJax formula and correspondently highlighted.

**Comment by relikd** [comment]
When is it triggered though? Could it be limited to inside code blocks? or even to `<pre>` tags?
Authors text seems like a pretty common use case where you don't want it to be triggered.

**Comment by matchavez** [comment]
I went to check if you can escape the things through \$, but it appears that it still renders. It would be a good idea to make MathJax optional in the settings, especially if you can't escape them.

**Comment by glushchenko** [comment]
Finally! Yo can toggle ⌘-option-control-` or click menu item.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/1089917/77854335-5d538380-71f2-11ea-8de9-b3ec549d7f88.png">

**Comment by dansmindspace** [comment]
You can also double escape (`//$`) the dollar sign to avoid this issue.
