### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#8]
I currently have about 1,200 notes (each an .rtf file) managed by nvALT. With this many notes, fsnotes isn't performant when filtering, due to the fact that it loads the contents of every single note file each time another character is entered into the search string (in `populateTable`).

I propose moving the note loading into the AppDelegate's `applicationDidFinishLaunching` and store them all in a `Notes.shared` singleton. That way, note searches should be pretty much instantaneous even with 10,000 notes.

The only downside I can think of is keeping the notes array synced with those on disk. I personally think that could be ignored for a while, and just assume that fsnotes is the only app editing notes. Down the track it shouldn't be too hard to monitor the filesystem for external changes to notes.

**Comment by glushchenko** [comment]
Yes, i have same behaviour. It need some time for refactoring.

**Comment by jeff-h** [comment]
(I'm happy to have a crack at it if you like)

**Comment by glushchenko** [comment]
Fixed in 0.7. Checkout https://github.com/glushchenko/fsnotes/releases/tag/0.7

**Comment by jeff-h** [comment]
This definitely seems awesomely fast now, even on my 1,000+ notes :)
