### ISSUE TITLE
After renaming note, the new name does not appear in the list

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#800]
**Describe the bug**
After renaming a note by clicking its title (or `⌘R`), the name of the file changes, but the title of the note in the note list does not update. After quitting and reopening FSNotes, the name in the list is updated.

![rename-fail](https://user-images.githubusercontent.com/6884276/72862010-983cb680-3c99-11ea-9d68-724ecf06e0c9.gif)

**To Reproduce**
1. Open a note
2. Rename the note
3. Notice the list name doesn't change.

**Expected behavior**
The list name should update immediately.

**Actual behavior**
A restart is required to get the new name in the list.

**Workaround**
🤷‍♂️

**Desktop:**
- OS: macOS
- OS version: 10.14.6
- FSNotes version: 4.0.18 (354)

**Comment by glushchenko** [comment]
Thanks for bug report, fixed
