### ISSUE TITLE
Clunky iCloud handling/setup between iOS and Mac

### ISSUE THREAD

**Issue by jasonekratz** [glushchenko/fsnotes#803]
I bought the iOS client today and downloaded the Mac app. Have to say that iCloud setup most definitely is not intuitive to sync both applications. When I run the app on iOS I see items appearing in iCloud Drive which makes sense. Unfortunately getting to those items on the Mac app is clunky at best. Ideally there should be a "sync via iCloud" option in the preferences which sets stuff up automatically. Even better would be on first app startup to look for the FSNotes folder and ask the user if they want to add it. 

And are we supposed to set the default location to the FSNotes folder in iCloud Drive or full sync or should we be adding that folder via "Attach Storage"? This whole thing is very unclear.

**Comment by gingerbeardman** [comment]
I agree this could be and should be more intuitive.

**Comment by bgibers** [comment]
Agreed completely. I cannot for the life of me figure out how to sync the two up. A wiki would be super helpful at the least for the time being

**Comment by sloria** [comment]
I'm considering switching from Dropbox to iCloud for storing my notes in order to use the iOS app, and I'm also a bit lost as to how to configure iCloud syncing. I agree that there should be an easy way to do this from the macOS app preferences. For the time, being, though, can someone document how to do this?

**Comment by sitase** [comment]
In preferences, under General, change default storage. There should be an application specific container under iCloud. It would be handy if this was the default setting.

**Comment by sloria** [comment]
Do you have to use a specific folder name within iCloud Drive for it to work on iOS?

**Comment by sitase** [comment]
There should be an application specific folder in your iCloud Drive called FSNotes. Maybe it is only created if you launch the iOS app first?

**Comment by glushchenko** [comment]
iCloud Drive is default storage for apps from AppStore and Mac App Store.
