### ISSUE TITLE
Don't create empty folders

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#804]
**Describe your feature request**
The folders `Archive` and `Trash` are created regardless of any content. Even if they aren't used at all. Further, I'd like them automatically to be deleted whenever they are empty again. E.g., if I clear the trash the folder should disappear too.

Probably also applies to the `Backup` folder.

**Additional context**
Regarding macOS

**Comment by glushchenko** [comment]
Option for configure Trash path added. I think this resolves issue

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
