### ISSUE TITLE
Images/files disappear in encrypted notes when locking them 

### ISSUE THREAD

**Issue by DJM0** [glushchenko/fsnotes#806]
Images/files disappear in encrypted notes when locking them 

**To Reproduce**
1. Create a new note
2. Lock the note
3. Unlock and add an image or file into the note
4. Lock the note again
5. Open the note, notice the image or file is now gone 

**Expected behavior**
It shouldn't do this

**Actual behavior**
The image or file is now gone

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.2
 - FSNotes version: 4.0.18

**Comment by glushchenko** [comment]
Can not reproduce this.

**Comment by DJM0** [comment]
Is media supported in encrypted notes?

**Comment by glushchenko** [comment]
Do you use containers? Seems bug related only for .md files.

**Comment by joshfarrant** [comment]
I'm seeing this behaviour too, as below.

https://gfycat.com/wildvictorioushornedtoad

There's also another issue where when you drag an image in to add it to a note it doesn't render immediately. Switching to a different view/note and back again fixes the issue.

**Comment by glushchenko** [comment]
@joshfarrant macOS version?

**Comment by glushchenko** [comment]
fixed

**Comment by joshfarrant** [comment]
@glushchenko Thanks for the quick fix! Just in case you still want my version I’m on 10.15.2 (19C57)

**Comment by glushchenko** [comment]
Please try test build https://github.com/glushchenko/fsnotes/releases/download/4.0.21/FSNotes_4.0.21.zip
