### ISSUE TITLE
Nested tags display in sidebar but selection doesn't work

### ISSUE THREAD

**Issue by fncll** [glushchenko/fsnotes#811]
**Describe the bug**
I have notes with the following tags

```
#testing
#testing/nested
#testing/different
```

The nested tags display in the sidebar properly, including the toggle to expand and show the nested tags. But selecting any of those nested tags simply collapses the tag and shows all notes in the note list.

**Expected behavior**

i would expect selecting the nested tag from the expanded selection would limit the display in the note list to the selected tag.

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.14.6
 - FSNotes version: 4.0.18

**Comment by buddax2** [comment]
I'm working on it.

**Comment by glushchenko** [comment]
Fixed in 4.0.19. Thanks @buddax2
