### ISSUE TITLE
Changing folder changes timestamp

### ISSUE THREAD

**Issue by thiemehennis** [glushchenko/fsnotes#814]
**Describe the bug**
When I move files between folders, the time-stamp is updated. 

**To Reproduce**
1. Add 'New Folder' using rightclick in the sidebar
2. Move/drag-drop a file to the new folder
3. Check the list of notes (files) under the main folder
4. You will see the note (file) updated so it is on top of the list.

**Expected behavior**
When moving files, the timestamp remains the same (of the final edit).

**Actual behavior**
When moving files, the timestamp is updated.

**Workaround**
Moving files using Finder.

**Supporting Files**
N.A.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.0.3

**Additional context**
N.A.

**Comment by gingerbeardman** [comment]
I guess (untested) that moving the files around using Finder would be a workaround? Not ideal though.

**Comment by thiemehennis** [comment]
> I guess (untested) that moving the files around using Finder would be a workaround? Not ideal though.

just tried it: yes it;s a workaround. Will update the issue. thanks.

**Comment by gingerbeardman** [comment]
Is it the "last modified" or "created" timestamp that you are seeing changed?

**Comment by thiemehennis** [comment]
> Is it the "last modified" or "created" timestamp that you are seeing changed?

it is sorting by modification rate.

**Comment by glushchenko** [comment]
Thanks @thiemehennis, fixed!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.0.20/FSNotes_4.0.20.zip in MAS soon.

**Comment by thiemehennis** [comment]
thanks! great job!
