### ISSUE TITLE
Tag Autocomplete Fails To Allow For Branching

### ISSUE THREAD

**Issue by stephencweiss** [glushchenko/fsnotes#816]
**Describe the bug**

**To Reproduce**
1. Create a new file
2. Start typing in a tag for something you already have
3. Instead of pressing enter (to select an existing tag), press backspace to short circuit the auto-complete
4. Notice that auto-complete does not return.

**Expected behavior**
When adding a _new_ tag, I should be able to branch from an existing nested tag, but still receive auto-complete support.

Example:
I have the following tags already:
`#_topics/topic_one/sub_topic_one`
`#_topics/topic_one/sub_topic_two`
`#_topics/topic_two/sub_topic_one`

If I start typing `#_topics/to`, I should see `topic_one` and `topic_two`.

If I tab into that, I should jump to the end. 
For example, if I tab into `topic_one` such that I now have: `#_topics/topic_one/`

Then, I should see:
- `#_topics/topic_one/sub_topic_one`
- `#_topics/topic_one/sub_topic_two`

As options to select from.

**Actual behavior**
![](https://media.giphy.com/media/mEIsczpdqPkyp0iBiV/giphy.gif)

**Workaround**
A lot of copy/paste / manual confirmation that I'm nesting my tags correctly.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.15.3
 - FSNotes version: 4.0.18

**Additional context**
Unfortunately, this is another area where Bear really shines.

**Comment by glushchenko** [comment]
Of course Bear is a good software. Ulysses even better.

Everyone chooses what suits him best.

**Comment by stephencweiss** [comment]
Sorry - not trying to imply that it’s better. I like FSNotes for a lot of reasons (and it’s why I’ve left Bear for FSNotes :)).

Referenced it only in case that was helpful for thinking about this issue (unless it’s not an issue, in which case I guess I don’t understand how autocomplete of tags is supposed to work in FSNotes.

Cheers,

**Comment by glushchenko** [comment]
@stephencweiss please try 4.0.22 https://github.com/glushchenko/fsnotes/releases/download/4.0.22/FSNotes_4.0.22.zip

**Comment by stephencweiss** [comment]
@glushchenko - oh my gosh! I'm in ❤️ ! 

Thank you so much - just noticed it and it's a huge improvement!

Cheers!

**Comment by glushchenko** [comment]
Thank you for reports!
