### ISSUE TITLE
Quote indent block color is hardly readable in Dark Mode

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#818]
**Describe the bug**
Using a quote indentation will render the text darker.
```
some text
> quoted text
```
However, on Catalina with dark mode, this darker color becomes hardly visible.

![screen](https://user-images.githubusercontent.com/1321720/74147750-2aced680-4c04-11ea-8de6-384221f1912a.png)

(note: this is the editor, not the preview)

**To Reproduce**
N/A

**Expected behavior**
The color should be as light as the `>` character.

**Actual behavior**
N/A

**Workaround**
N/A

**Supporting Files**
see image above

**Desktop (please complete the following information):**
 - macOS version: 10.15.3
 - FSNotes version: 4.0.20

**Comment by glushchenko** [comment]
Please try 4.0.22 https://github.com/glushchenko/fsnotes/releases/download/4.0.22/FSNotes_4.0.22.zip
