### ISSUE TITLE
Auto-continue lists

### ISSUE THREAD

**Issue by fguada** [glushchenko/fsnotes#82]
Could you provide an auto-continuation of lists—e.g. when I hit enter at the end of a line starting with a dash/asterisk/bullet, make the new line start with the same marker (and same indentation)?

Thanks

**Comment by jeff-h** [comment]
This is fantastic :) I used this feature a lot in nvALT.

I've created a PR which adds to this a little:

* adds the — (em-dash), and * as accepted bullet characters
* adds functionality to finish the auto-bulletting if you press enter without typing any characters
