### ISSUE TITLE
Ending a line with a colon results in duplicate line with todo checkbox

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#822]
**Describe the bug**
If you type a line like this and hit return:

    Hello I am just an innocent line:

The line will duplicate and a checkbox is added, like this:

    Hello I am just an innocent line:
    Hello I am just an innocent line:🔲

Here's a screencast:

![list items fail](https://user-images.githubusercontent.com/6884276/74985027-adc20f00-5404-11ea-8ae8-eaa5bc23cfe2.gif)

**To Reproduce**

Sadly, I can't reproduce this, it only happened in one note, and now it's working as expected. 🤷‍♂️ I'm just reporting it in case @glushchenko know what might be the cause. Feel free to set as `wontfix`.

**Expected behavior**
I expect a new line without a checkbox.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.23

**Comment by glushchenko** [comment]
Seems it fixed in FSNotes 5
