### ISSUE TITLE
inline tags sort order doesn't match between mac and ios devices

### ISSUE THREAD

**Issue by sdclee** [glushchenko/fsnotes#827]
I couldn't find this issue reported elsewhere so hopefully I'm not duplicating anything.
My inline tags show in alpha order on the mac irrespective of where the tag was created, so I have one from this morning for example which has the smart tag of #nebo which I created on my iPad Pro.
Firstly it did not appear on my iphone X as a smart tag (LH panel) but when I searched for a word in the content on the iPhone it found the note.
Closing the app and reloading it added the tag *but* the IOS tags are in no particular order which makes them somewhat difficult to use. It looks like they might be ordered bt datetime created as #nebo sits at the top of the tag list on the IOS devices.
I looked in settings but can't find anything obvious to dictate the sort order.
I am unsing 4.0.25 (362) Catalina 10.15.3 and IOS 13.3.1.
Thanks in advance for any help.

**Comment by glushchenko** [comment]
Fixed, @sdclee, thanks.

**Comment by glushchenko** [comment]
Please try 3.2.0

**Comment by sdclee** [comment]
Wonderful - thank you :)
