### ISSUE TITLE
With plain text documents, "Paste and match style" should be the default option

### ISSUE THREAD

**Issue by fiv** [glushchenko/fsnotes#828]
**Describe the bug**
Paste should default to "Paste and match style" when using plain text file format 
(and the user should not be able to use any formatting/rich text with plain text documents)

**To Reproduce**
1. Set file format to plain text (.txt)
2. Create new document & write some text
3. Copy & Paste (cmd+v) some formatted text (e.g. from web browser) 
4. Copy-pasted text has formatting/background color

**Expected behavior**
With plain text documents, "Paste and match style" should be the default option and copy-pasted text should have no formatting/rich text

**Actual behavior**
Copy-pasted text has formatting/rich text with plain text documents

**Workaround**
Use "Paste and Match style" manually

**Supporting Files**
![Screenshot 2020-03-19 at 9 08 03](https://user-images.githubusercontent.com/2693750/77040762-41b1d700-69c1-11ea-84ba-62473e4d61ea.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.4 Beta (19E242d)
 - FSNotes version: 4.0.25 (362)

**Additional context**
Old related issue #467

**Comment by glushchenko** [comment]
Can anyone reproduce this bug?

**Comment by greendog99** [comment]
I just tried this in v4.7.4 and could not reproduce.

**Comment by glushchenko** [comment]
Thanks @greendog99, closed.

**Comment by gingerbeardman** [comment]
I could not repro either
