### ISSUE TITLE
Preferences not saving

### ISSUE THREAD

**Issue by chevem** [glushchenko/fsnotes#829]
**Describe the bug**
Change in preferences are not saving in 4.0.25 just installed on Mac OS 10.13.6

**To Reproduce**
Open preferences try to change anything. 
Close Preference panel
Open Preference panel again. All checked boxes are back in their original state...

**Expected behavior**
Changes should apply in the app and stay applied

**Actual behavior**
Most changes don't even apply in app (eg. default folder or First line as title). Some of them apply (eg. change note list location)

**Workaround**
No workaround

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.13.6
 - FSNotes version: 4.0.25

**Comment by glushchenko** [comment]
Tried on 10.13. Works fine for me.

**Comment by gingerbeardman** [comment]
Working fine for me also.

**Comment by chevem** [comment]
Thanks,
Updated High Sierra, reinstalled FSNote and everything is now working properly.
Sorry for the inconvenience but the behavior was really weird…

**Comment by gingerbeardman** [comment]
Great news! Thanks for reporting back.
