### ISSUE TITLE
Automatic file renaming

### ISSUE THREAD

**Issue by Pusnow** [glushchenko/fsnotes#831]
**Describe your feature request**

Currently, fsnotes use UUID filename for a new note.
Without explicit renaming (cmd + R), the new note keeps using UUID.
I think it is not good for interoperability. I also use Linux and Windows sometimes.

My suggestion is adding "First line as filename" option (similar to "First line as title").
I know there should be many issues: filename conflict, file system limitations (character, length).

Below is my suggesting renaming algorithm.

1. File content changes.
2. Parse first line (same as "First line as title").
3. If the first line does not change, stop renaming.
4. Else, escape it to `filename` and find a file which has same name.
5. If there is a file which has same name, add a number to `filename`  until there is no conflict.
6. If there is no conflict, rename the file.

**Additional context**

macOS

**Comment by jakemkc** [comment]
I am using Devonthink to archive Fsnotes texts with the following AppleScript:

```applescript
tell application "DEVONthink 3"
	set selectionList to selection
	repeat with i in selectionList
		repeat with aParagraph in (paragraphs of (rich text of i))
			if ((count of characters of aParagraph) > 2) then
				set name of i to aParagraph as text
				exit repeat
			end if
		end repeat
	end repeat
end tell
```
The script is simple and for DT, and may not work as you suggested. Anyway, I am sharing it for your reference. Hope this will be helpful.

Jake

**Comment by SoyunoForinfo** [comment]
Hello. I have recently discovered FSNotes and it is great, 'NValt on steroids' is exactly what I want. I wanted to +1 this request, which will make the app play more nicely with other editors people use to work with their store of markdown files. I use the zettel convention for both file names and note titles, eg '202005101854 Blah blah my title' and would like to be able to use FSnotes in a way that is consistent with the thousands of notes I already have (and that allows me to use other editors which display the file name as the note title). 

Many thanks, great app 

SF

**Comment by glushchenko** [comment]
Added here https://github.com/glushchenko/fsnotes/releases/download/4.5.2b/FSNotes_4.5.2.zip
