### ISSUE TITLE
Old search reactivates when app focus returns

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#832]
**Describe the bug**
Old search reactivates when app focus returns

**To Reproduce**
1. Open FSNotes with URL scheme to do a search
2. Use FSNotes, go to other notes
3. Cmd+Tab to another app
4. Cmd+Tab back to FSNotes

**Expected behavior**
- FSN should be as it was left

**Actual behavior**
- focus shift back to search results, moving away form note I was editing

**Workaround**
n/a

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.0.25 (362)

**Additional context**

**Comment by gingerbeardman** [comment]
The problem here is confounded because if I used URL scheme to create a new note, then each time this bug is triggered a new blank note is created.

Perhaps related to #834 ?

**Comment by glushchenko** [comment]
@gingerbeardman please record video. May be this will be helpful.

> Perhaps related to #834 ?
Don't think so. #834 related to iOS

**Comment by gingerbeardman** [comment]
Oh, HAHAHAH 😄

**Comment by gingerbeardman** [comment]
Will record video soon

**Comment by gingerbeardman** [comment]
Not been able to capture this on video but flow is like:

1. open using URL scheme (search or create)
2. use FSNotes
3. use another app, Cmd+Tab between them
4. Go back to FSNotes

at some point the URL scheme will re-trigger resulting in
- search: old search results displayed based on url scheme
- create: another new note created based on url scheme

**Comment by glushchenko** [comment]
Seems it fixed?

**Comment by gingerbeardman** [comment]
I'll keep an eye out for it!
