### ISSUE TITLE
Undo should undo last edit group, not individual characters

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#833]
**To Reproduce**
1. Paste a text, eg. "1 Litre"
2. Delete last four chars by (quickly) hitting backspace 4 times
3. Press undo (or cmd-z)

**Expected behavior**
Undo should re-insert "itre" at the end of the string.

**Actual behavior**
FSNotes inserts only the "i".

**Workaround**
I think what Apple does is having a timeout timer that gets reset after every tap. If the timer runs out (because there is no further user input) the edit action gets added to the stack.

**Supporting Files**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.3
 - FSNotes version: 4.0.25

**Comment by glushchenko** [comment]
Finally fixed
