### ISSUE TITLE
Empty note appearing on creation of a note

### ISSUE THREAD

**Issue by Shivani-Bajaj** [glushchenko/fsnotes#834]
**Describe the bug**
On creating a new note, there's an empty note screen that appears on swiping left from the notes listing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FSNotes iOS app
2. Click on plus to add a note. And type any note information.
3. Click on the back icon.
4. When the listing is displayed, swipe left twice.
5. An empty note appears

**Expected behaviour**
There shouldn't be an empty note appearing on swiping.

**Actual behaviour**
An empty note is appearing on left swiping twice from notes listing.

**Workaround**
n/a

**Supporting Files**
n/a

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 3.8.2

**Additional context**
n/a

**Comment by glushchenko** [comment]
Can not reproduce.

**Comment by Shivani-Bajaj** [comment]
@glushchenko  Please check the video in the link:
https://www.dropbox.com/s/vnmkofbs03chtzk/FSNotes%20issue.mov?dl=0

**Comment by glushchenko** [comment]
Seems like preview page for markdown documents. Why just not use markdown?

**Comment by Shivani-Bajaj** [comment]
What are the markdown documents, you are referring to @glushchenko ?

**Comment by glushchenko** [comment]
@Shivani-Bajaj https://en.wikipedia.org/wiki/Markdown
