### ISSUE TITLE
Add ability to hide Todo heading from sidebar

### ISSUE THREAD

**Issue by cweagans** [glushchenko/fsnotes#835]
**Describe your feature request**
The sidebar has a Todo item that I do not use. I'd love to hide it entirely if possible.

**Additional context**
macos but probably ios too

**Comment by cweagans** [comment]
Same with the "Inbox" item.

**Comment by gingerbeardman** [comment]
Perhaps the option should be extended to all of those groups:

- Inbox
- Notes
- Todo
- Archive
- Trash

I do not use any of them.

**Comment by glushchenko** [comment]
Added in 4.1.2 https://github.com/glushchenko/fsnotes/releases/download/4.1.2/FSNotes_4.1.2.zip

**Comment by cweagans** [comment]
Wow! This is perfect! Thanks!!
