### ISSUE TITLE
Slowing down with large code blocks

### ISSUE THREAD

**Issue by shurain** [glushchenko/fsnotes#836]
**Describe the bug**
When a note contains a large chunk of code block, it has a hard time processing my backticks (`). It will take quite long before I can type my next character.

**To Reproduce**
Create a note with a large code chunk. I can easily reproduce it with two code blocks each with about 5 paragraphs worth of lorem ipsum. Next time I press backtick, it will grind to a halt for sometime before I can type any other character again.

**Expected behavior**
It shouldn't slow down

**Actual behavior**
Whenever I press backtick, it will slow down and take quite long before I can type any other character.

**Workaround**
Instead of typing the backtick, I can copy paste it which will be a bit faster.

**Supporting Files**

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.3
 - FSNotes version: 4.0.25 (362)

**Comment by ulab** [comment]
I have the same issue for some while now. Usually I press `three backticks, enter, three backticks enter, cursor up, enter` to start a new block and after "pre-typing" that, it takes more than 5 seconds before I can go on.

I use fsnotes to document installations hat usually require multiple code blocks and it feels like it gets worse with every block.

Also overall rendering is often problematic with backtick blocks.

**Comment by glushchenko** [comment]
Guys, I think you should understand that pressing one backtick completely reformats all document. All code blocks rescanned at this moment.

Please use shortcut ⌘ - ctrl - c for code blocks. It's fast and productive.

**Comment by shurain** [comment]
I've turned off the real-time syntax highlighting.
