### ISSUE TITLE
Taking first title as note title

### ISSUE THREAD

**Issue by yene** [glushchenko/fsnotes#837]
**Describe your feature request**
Inspired by the iOS app iA Writer:

* Open new text file
* write "# title something" newline
* the editor takes the title and sets it as file name

**Additional context**
prio: low
I love your work and will donate once I get a stable income. ❤️

**Comment by gingerbeardman** [comment]
This is already in the MacOS version. Not sure about iOS.

![Screen shot 2020-04-10 at 12 09 18](https://user-images.githubusercontent.com/49612/78986891-43843b80-7b24-11ea-8a38-559ab14d2c3b.png)

**Comment by yene** [comment]
👍

**Comment by yene** [comment]
ups sorry, that was bad communicated on my part.

What I meant that it sets the filename (on filesystem) to the first title.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/issues/831 Dupe?

**Comment by davidlohner** [comment]
#831 would be great!

**Comment by andybyte** [comment]
When I tried it on Mac

> ups sorry, that was bad communicated on my part.
> 
> What I meant that it sets the filename (on filesystem) to the first title.

I tested on mac os and with "First line as title" turned on it still named the file as CCA51BC8-0DFF-4697-B64C-02B38B8E9AC0. Using version 4.5.1.

Was expecting it to rename the file as whatever the first line of text is.

**Comment by andybyte** [comment]
Okay. I see this works as expected on iOS when you use the Files Naming > Auto rename by title preference. Is this available on Mac OS? @glushchenko

**Comment by glushchenko** [comment]
@andybyte yes! https://github.com/glushchenko/fsnotes/releases/download/4.5.2b/FSNotes_4.5.2.zip

**Comment by andybyte** [comment]
> @andybyte yes! https://github.com/glushchenko/fsnotes/releases/download/4.5.2b/FSNotes_4.5.2.zip

Excellent. Thank you! 👍

**Comment by yene** [comment]
good job
