### ISSUE TITLE
How to clean the Markdown Preview CSS ?

### ISSUE THREAD

**Issue by debugly** [glushchenko/fsnotes#839]
I used  FSNotes 4.1.2, In Preferecnes Panel, Advanced Tab:

I Selected a css file, It works fine!
but  when I want cancel the chose, I want to use the default preview, I failed!

Tank you, Dear Developers!

**Comment by glushchenko** [comment]
@debugly just remove css file.

**Comment by debugly** [comment]
> @debugly just remove css file.

Thanks!
