### ISSUE TITLE
A preference to change list font size

### ISSUE THREAD

**Issue by fguada** [glushchenko/fsnotes#84]
Could you provide a preference to change the list font size? The preview lines are too small for my eyes.

Thanks

**Comment by kaapow** [comment]
I second that. I’d also like to be able make it bold like in the original Notational Velocity

**Comment by feoh** [comment]
Definite +1 on this. I'm partially blind and have to zoom the screen to see the note titles in the list. Not optimal :(

Great product though, thanks!

**Comment by glushchenko** [comment]
Release in FSNotes v3
