### ISSUE TITLE
Parentheses render as italics

### ISSUE THREAD

**Issue by tewe** [glushchenko/fsnotes#840]
**Describe the bug**
Round brackets are interpreted as Markdown links even with no square brackets in sight.

**To Reproduce**
1. Add a new note
2. type `Text with (parentheses)`
3. Toggle to the Markdown preview
4. Click on the word "parentheses"

**Expected behavior**
Visible parentheses, no italics, nothing clickable.

**Actual behavior**
Parentheses hidden, text in italics, clicking moves selection highlight.

<img width="161" alt="Screenshot 2020-04-13 at 11 03 06" src="https://user-images.githubusercontent.com/645412/79108572-e92ee900-7d76-11ea-9720-86bd4b77ea41.png">

**Desktop**
 - macOS
 - OS version: 10.14.6
 - FSNotes version: 4.1.1

**Comment by gingerbeardman** [comment]
You should disable "Preview MathJax"

![Screen shot 2020-04-13 at 10 37 28](https://user-images.githubusercontent.com/49612/79110660-d61a1a00-7d72-11ea-8a69-2bb9c9e71521.png)

I would argue it should be off by default.

**Comment by tewe** [comment]
That helped, thanks!

I agree that MathJax should not be the default. And even after your hint I looked for it in preferences (where Marked has it), not the View menu.

**Comment by glushchenko** [comment]
Now disabled by default
