### ISSUE TITLE
Interactive Markdown preview

### ISSUE THREAD

**Issue by nimbling** [glushchenko/fsnotes#842]
**interactive, non static Markdown preview**
I'd like to be able to keep typing in the Markdown preview.
The FSNotes single pane approach is good - and can be even better if it were to allow typing.

** After switching using cmd+` - please resume / place the typing cursor where it was**

**Pretty (markdown) does not have to mean non functional :)**
macOS and iOS, yes please

Thanks for having a look!

**Comment by nimbling** [comment]
I just noticed the markdown preview of the "to do list" view is also not interactive.
Is that by design?

**Comment by glushchenko** [comment]
Todo is interactive.
