### ISSUE TITLE
Small layout changes, requests.

### ISSUE THREAD

**Issue by nimbling** [glushchenko/fsnotes#846]
**Describe your feature request**
I'd like some more "room" around the elements.

- the search field could be the full height of the rect it is in
- The alternating rows coloring of the notes list could do with less contrast, perhaps some lit seams?

Here's a bit of a mockup. I couldn't help myself but redo the icons, too.

![fsnotes](https://user-images.githubusercontent.com/821411/79133600-9839e780-7dac-11ea-9d0f-f922d356f6dc.png)

**Comment by gingerbeardman** [comment]
I'd like to see new improved icons in the sidebar (especially if tags get their own icons, as requested elsewhere).

I believe the search field is a standard macOS control so not sure about how much it can be modified. I mean, the border could be hidden but the surround would need to be made clickable.

On my (old) monitor there is already very little contrast between rows in Light Mode, so I think this is just Dark mode. I wonder if @glushchenko has used Apple standard colours for these elements?

**Comment by nimbling** [comment]
I'm happy to hear! Shall we make an issue where collaborate on implementing them? I have no idea about specifics on their size. I have them in Illustrator, so any way and size you need them is fine.

About the search field: I'd like a bigger hit target (yes, I use cmd+L - but that does not mean I'll never click it, or that I can unsee the tight margins in that area).

As for the rows: standard or not, we can do prettier :) - I'd also gladly share the asset for that seam.

If you look in the note field, you can also see my sneaky attempt at creating a new icon, which is derived from these (none final, just for reference) :

![fsnotes icons](https://user-images.githubusercontent.com/821411/79135228-52cae980-7daf-11ea-971d-bc56a4f38cd9.png)

**Comment by nimbling** [comment]
how about these? :)

![image](https://user-images.githubusercontent.com/821411/79360390-2694a180-7f44-11ea-83af-82d2a0d4a3ae.png)

**Comment by glushchenko** [comment]
@nimbling this a little bit ugly.

**Comment by nimbling** [comment]
I'll do better! :)

**Comment by gingerbeardman** [comment]
The app icon is the least pressing issue, I think the UI improvements you spotted are worth more of your time @nimbling

**Comment by nimbling** [comment]
Sweet!
So! side bar icons :) what format do you want them in?
I'll do the preference icons, too, to match!

What sizes are they used?

Yes - the tag icons would need a nice open source library.

The App icon is rather pressing too though!

**Comment by gingerbeardman** [comment]
@nimbling please see the old issues about the app icon design sessions we have already had. IIRC this is the 3rd and is only a year old, most people are happy with it.

take a look at the repo to see the format of the current sidebar icons
