### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by abdcef** [glushchenko/fsnotes#847]
Hello,

I recently started using FSnotes on Mac and iOS. The sync process is very erratic. I am using the latest versions from the respective app stores and sync via iCloud Drive FSNotes folder.

On the Mac, I see these folders pop up:
<img width="197" alt="Screen Shot 2020-04-14 at 3 09 28 PM" src="https://user-images.githubusercontent.com/56148250/79196162-1ad0ae80-7e62-11ea-852c-b9656d152043.png">

The iPhone notes are not updated if I make changes on the Mac. The iPad sync is also unreliable.

Appreciate any suggestions on how to fix this annoyance.

**Comment by glushchenko** [comment]
Do you really think that synchronization will work if you put the git repository in the root?

**Comment by abdcef** [comment]
Yes that’s my default storage on Mac
I’m not sure how I can change it on iOS

**Comment by glushchenko** [comment]
What is "Lib > Clo" ? 

In example proper iClouDrive destination on my computer:

> /Users/fluder/Library/Mobile Documents/iCloud~co~fluder~fsnotes/Documents

**Comment by abdcef** [comment]
The path on mine is /Users/myname/Library/CloudStorage/iCloud Drive/FSNotes

**Comment by glushchenko** [comment]
Ahh, its default iCloud Directory location in Catalina. Ok, but why Git backup directory in you root? 

Remove this and change repositories path here:

![image](https://user-images.githubusercontent.com/1089917/79230464-4efd9c80-7e6d-11ea-8628-add54807cf21.png)

**Comment by abdcef** [comment]
This is blank for me currently. What should I change it to?
<img width="480" alt="Screen Shot 2020-04-14 at 9 37 31 PM" src="https://user-images.githubusercontent.com/56148250/79231144-348ce880-7e98-11ea-9862-eee484263e56.png">

**Comment by glushchenko** [comment]
Backups by default stores in Application Support. Change path to /tmp for test and remove *.git directories from root. 

May be sync not working because at this moment hundreds files from repositories uploads to iCloud Drive.

Please let me know about result.

**Comment by abdcef** [comment]
I cannot see /tmp when I click change and go to Users/myname/
Is it hidden? How can I change to a hidden forlder?

**Comment by glushchenko** [comment]
Holy shit, change to any not in iCloud Drive and remove .git from root. Thats all.

**Comment by abdcef** [comment]
Sorry for my questions but I guess not everyone is a techie
Looks like the Mac app should be sorted now.

How do I replicate this on iOS?

**Comment by abdcef** [comment]
Can I make the sequencing of the folders in the sidebar same cross devices?
![IMG_3F64BB7FAF67-1](https://user-images.githubusercontent.com/56148250/79289637-68015e80-7efc-11ea-9d5b-d8b204607257.jpeg)
<img width="245" alt="Screen Shot 2020-04-15 at 9 34 44 AM" src="https://user-images.githubusercontent.com/56148250/79289653-6f286c80-7efc-11ea-8760-e8cdfee72b75.png">

**Comment by glushchenko** [comment]
Yes, order different on iOS - will be improved in next release.

Did synchronization work?

**Comment by abdcef** [comment]
it's now showing the same projects on the Mac and iOS
the contents are not the same though

**Comment by glushchenko** [comment]
Do you have enough space on your device?

**Comment by abdcef** [comment]
Yes, enough space on the device

**Comment by glushchenko** [comment]
Phone not in low power mode?

Can you try to download files in Files.app and open FSNotes?

**Comment by abdcef** [comment]
No, phone was not in low power mode.
The Files app shows the correct files across devices.

On April 16, 2020 at 7:30:29 AM, glushchenko (notifications@github.com)
wrote:

Phone not in low power mode?

Can you try to download files in Files.app and open FSNotes?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/glushchenko/fsnotes/issues/847#issuecomment-614330059>,
or unsubscribe

**Comment by glushchenko** [comment]
I dont know how to reproduce this.

**Comment by abdcef** [comment]
Seems to be fixed Sync working fine for me now.
