### ISSUE TITLE
text format error

### ISSUE THREAD

**Issue by olikilo** [glushchenko/fsnotes#851]
**Describe the bug**
Typesetting errors.

**To Reproduce**
1. enter the following text:
`**_Sentential connectives_**: *not, and, or, if ... then, if and only if*. (logisch connectief, een symbool of woord dat wordt gebruikt om twee of meer zinnen grammaticaal geldig te verbinden.)`
2. preview the entered text

**Expected behaviour**
You expect:
1. 'Sentential connectives' to be bold and underlined.
2. 'not, ... if' to be italic.
3. '(logisch connectief ... verbinden.)' to be normal 

**Actual behaviour**
1. 'Sentential connectives' is bold and italic.
2. 'not, ... if' is italic.
3. '(logisch connectief ... verbinden.)', the '(',  ')' and ' ' (spaces) are removed, the text is italic. 

**Workaround**
I didn't find any so far.

**Supporting Files**
I think the description suffices

**Desktop (please complete the following information):**
 - OS: macOS and iOS
 - OS version: 10.15.4
 - iOS version: 13.4
 - FSNotes version: 4.1.1

**Additional context**
None.

**Comment by olikilo** [comment]
Hi, I would like to help your project by offering to translate it to Dutch, Dutch is not a huge language area but still it is counts for quite some potential users ;-) If interested can you explain me how to proceed? Although I have a masters degree in computer science I didn't develop any serious code for the last 30 years ...

**Comment by gingerbeardman** [comment]
@olikilo duplicate uk.lproj to nl.lproj and translate the contained file

**Comment by gingerbeardman** [comment]
@olikilo 

1. neither Markdown nor FSNotes supports underline. _ and * are interchangeable, using one gets italic, using two gets bold.
2. (no bug)
3. turn of View > Preview MathJax (it was on by default until very recently)

**Comment by olikilo** [comment]
You are right there, underlining is not in the Markdown nor in the MultiMarkdown definitions! I'll avoid it.

Your suggestion to switch of Preview MathJax doesn't work for me as most of my work is LaTeX based. But indeed if you switch it of the typesetting issue with the text '(logisch connectief, ... te verbinden.)' disappears. It's up to you to see it as a bug ;-) In my case it means I can't use the '()' in normal text, which is somewhat of a limitation.

**Comment by gingerbeardman** [comment]
@olikilo then I think the MathJax implementation needs some refinement

**Comment by glushchenko** [comment]
> Hi, I would like to help your project by offering to translate it to Dutch, Dutch is not a huge language area but still it is counts for quite some potential users ;-)

No problem, i can make translation file at the weekend.

**Comment by glushchenko** [comment]
@olikilo Hi, Chris. If you still want to make a translation, translation file here: 

[nl-NL.xliff.zip](https://github.com/glushchenko/fsnotes/files/4500165/nl-NL.xliff.zip)

You can edit this in XLiff Tool on Mac.

**Comment by olikilo** [comment]
Hi Oleksandr,

I’m working on it, thanks for sending the file and the tool name.

For me to have an extra translation check, could you sent me the German file as wel, than I can double check my translations, because my English is ok, but my German is a my Dutch native.

Cheers,

Chris

**Comment by glushchenko** [comment]
[de.xliff.zip](https://github.com/glushchenko/fsnotes/files/4510756/de.xliff.zip)

@olikilo

**Comment by olikilo** [comment]
Maybe I’m doing something wrong, but I do not see the German translations in it.

I’m almost done with translating, with it I’ll ask for some text a little bit more context to check if my translation is correct, and this context you could put in the comment fields for future translators.

Cheers,

Chris

**Comment by olikilo** [comment]
Hi Oleksandr,

Here is my translation:


A couple of remarks and question:
In the original text in several locations I see ‘Markdwon’, I think this should be ‘Markdown’.
In your text with the copyrights you write '2017-2019', I translated it into '2017-2020', I think you should also change this in original text.
I translated ‘Encrypted Text Pack’, as ‘Versleuteld Tekst Pakket’, this is a literal translation. I would like to know the context to see if a literal translation is possible and correct. Could you give more information on the context of this text?
In your text ‘Please enter password for current note’ misses a colon at the end like the other texts in the same section do have, so it should be ‘Please enter password for current note:’ I think. If not you have to remove the ‘:’ from my translation.
I think ’Needs for attach photo in notes’ should be ’Needed to attach photos in notes’, as the note in XLIFFTool suggests it is about getting access privilege to Photos, if so the Dutch translation should be ’Nodig om foto’s in notities bij te voegen’. The translation I added now is a more literal translation. Another thing is that you use ‘photo’, i.e. one photo, to attach it to several notes, I assume that what you mean is to attach photos to notes.
same holds for ’Needs for attach images in notes’, in which case the Dutch translation should be ’Nodig om afbeeldingen in notities bij te voegen'.
You write ’Code span’ I didn’t get what you meant until I tried it, and I think in other markdown tools it is cold ‘inline code’, so I would take as menu entry ‘Code Inline’.
There is a typo in 'Default Keyboard On Edititng’, it should be ‘Editing’.
I didn’t understand ‘Live images preview’ until I checked it, I would write ‘View images in editor’
I translated ‘hour at’ literally, could you give me some context to see if this is a correct translation?
I translated ’Table View Cell’ literally, could you give me some context to see if this is a correct translation?
I need more context to translate ’Set’, for now I assumed it is about putting a parameter to a certain value (‘Instelling’), but it could also be ‘Instellen’ which means ’to set’.
To translate 'Note auto selection when body text matched’ I need more context, for now I did it literally. I found it in the layout settings menu, but I have no idea what it does, functionally. If you could describe it to me I can check my translation.

Cheers,

Chris

**Comment by gingerbeardman** [comment]
> Encrypted Text Pack

Text Pack is a type of file format, containing markdown and images together. Optionally it can be encrypted.

**Comment by olikilo** [comment]
Ok I adapted the translation to this interpretation, the new file:
