### ISSUE TITLE
Viewing Markdown Bolded Table Text in FSNotes

### ISSUE THREAD

**Issue by petrodubloseven** [glushchenko/fsnotes#853]
**Describe the bug**
In Catalina 10.15.4 running in dark mode, when viewing a markdown table with strikethrough or bolded text, the text is rendered in white font on a standard (light mode?) banded background table rendering the text invisible.  I am previewing the markdown in FSNotes Version 4.1.5 (372)

**To Reproduce**
1. Preview the following table in FSNotes running on dark mode Catalina
| Facility | Ext |
|--------- | ---- |
| Most Tyler facilities | **[6]** |
| ETMC Athens | **[2]** |
| ~~ETMC Behavioral Health~~ | **~~[4]~~** |
| ETMC Carthage | **[4]** |

**Expected behavior**
1. I expected the extension column to be rendered in a visible font
2. I expected the strikethrough text to be rendered in a visible font
3. It would be nice if the table were rendered in colors more appropriate to dark mode.

Unrelated to the bug it would also be nice to be able to set the default view to preview for my markdown notes.  I bought the application because of the formatting.  I know I could probably use RTF but markdown is sort of cool and I want to be a cool kid too.

**Actual behavior**
Text formatted within the table in bold or strikethrough is invisible to the human eye.

**Workaround**
Don't use formatting in tables or don't use tables in markdown documents

**Supporting Files**

**Desktop (please complete the following information):**
 - OS: macOS only.  The IOS app does not have the same bug
 - OS version: 10.15.4
 - FSNotes version: 4.1.5 (372)

**Additional context**
Thanks for your consideration

**Comment by petrodubloseven** [comment]
<img width="484" alt="raw markdown table" src="https://user-images.githubusercontent.com/1808459/79624198-c89fbf80-80e5-11ea-814a-45b63d0579d5.png">
<img width="500" alt="Preview Markdown table" src="https://user-images.githubusercontent.com/1808459/79624202-cdfd0a00-80e5-11ea-9dd1-6ac1cf9145cf.png">

**Comment by glushchenko** [comment]
Thanks, fixed.
