### ISSUE TITLE
auto-complete prompt

### ISSUE THREAD

**Issue by John15263** [glushchenko/fsnotes#856]
**Describe your feature request**
The suggestions prompted could not be changed once the Auto-completion is triggered by pushing F5. Is it possible to make the prompts changing while I'm typing or deleting?
I'm a nvALT user and this is the most important reason I'm still using it.
Thank you.

**Additional context**
macOS

**Comment by glushchenko** [comment]
Finally added 🤝

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/download/4.2.2/FSNotes_4.2.2.zip

**Comment by John15263** [comment]
This is Great!!!

I build a Note-Taking System Workflow(https://www.bilibili.com/video/BV147411A7CP/, https://github.com/John15263/note-taking-system), and I'm using nvALT as the central writing tool which connect with MarginNote, for reading,  DEVONThink, for storing,  and TheBrain, for creating visual concept systems. Auto-complete Prompt help me get out of the job of taking my consciousness out to type and check everything, especially for the long strings of words, which could stop the "Thinking&Writing in the Flow". And if this "type and check" job keeps annoying me, the new idea will be faded. This does a great help. Thank you!!

**Comment by jakemkc** [comment]
Is there a setting to enable this? I just downloaded 4.2.2, and I don't see auto complete prompt for wiki link when typing "[[". I tried fn-f5 and it no longer works. 

Tag auto complete prompt works though @glushchenko 

Using MacOs 10.14.6.

**Comment by glushchenko** [comment]
@jakemkc, pop up with all titles opens right after ⌘-9 pressed. It is will be more clear.

**Comment by mohammedri** [comment]
Hey @glushchenko I have tried to do this with FSNotes 4.3.3, but am not able to get it working. 

I type [[ and try typing the name of a note, nothing shows up. Also tried fn+f5 - without any luck. 

cmd-9 works to see all but doesn't have auto complete.

**Comment by glushchenko** [comment]
Press ⌘ - 9 and type what do you want autocomplete.

**Comment by mohammedri** [comment]
That works, but is there no fuzzy search on there? without typing out just the first letter exactly?
