### ISSUE TITLE
tag missing

### ISSUE THREAD

**Issue by L1cardo** [glushchenko/fsnotes#857]
**Describe the bug**
tags are missing and I dont know how to add a tag.
a blank area can be clicked

**To Reproduce**
1. tags are mising
2. right click on the area can show the blank cell

**Expected behavior**
be able to add a tag to notes

**Workaround**
no

**Supporting Files**
![image](https://user-images.githubusercontent.com/33802186/79934256-ba0a2d00-8484-11ea-9b30-88977c2d1042.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.4 (19E287)
 - FSNotes version: 4.2.0 (374)

**Additional context**

**Comment by glushchenko** [comment]
Please show your Preferences -> Editor.

**Comment by L1cardo** [comment]
Sorry to bother, the `scan inline tag` was on.
by the way, how do I write a scanable inline tag in md file?

**Comment by glushchenko** [comment]
#tag/subtag
