### ISSUE TITLE
update the picture url rules to support other apps

### ISSUE THREAD

**Issue by chinyajie** [glushchenko/fsnotes#858]
**Describe your feature request**
When we paste a picture into fsnotes markdown file, the software would create a folders name as "i", copy pictures there, and create a picture url like "/i/example_piture.jpg".
As you can see, the url would not be supported by other apps. Could you please change the url to "./i/example_piture.jpg", which mean change the absolute path to relative path.

**Additional context**
I do love fsnotes, but I would also open the files created by fsnotes in other apps like DEVONthink. It would be great helpful, if you can update the picture rules. Thank you.

**Comment by glushchenko** [comment]
Root slash removed in last build.
