### ISSUE TITLE
Sharing notes with other person (like Evernote)

### ISSUE THREAD

**Issue by iAmRenzo** [glushchenko/fsnotes#859]
I like iCloud sync for my personal syncing. But I also like to share all of the notes with an other person in my household. Like Evernote does too.

**Comment by Labutin** [comment]
I would like to see this feature too. I like to share some notes with my wife in standard notes app.

**Comment by glushchenko** [comment]
In FSNotes 6 you can push notes on github or publish on the web.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
