### ISSUE TITLE
Preferences->Advanced->Language is not set correctly right after first install

### ISSUE THREAD

**Issue by VKondakoff** [glushchenko/fsnotes#861]
**Describe the bug**
My system is set to use Russian language as the default interface language. Right after first FSNotes install the interface language was automatically set to Russian, but the dropdown list in Preferences->Advanced->Language still reads English.

**Supporting Files**

<img width="610" alt="Скриншот 2020-04-25 12 48 48" src="https://user-images.githubusercontent.com/230824/80277045-0f4c7580-86f5-11ea-8cb4-a3b3d854d880.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.4
 - FSNotes version: 4.2.0 (374)

**Additional context**
I can reproduce the same behaviour just by deleting FSNote preferences and restarting FSNote: the interface is set to Russian, while the Preferences->Advanced->Language still reads English.
If I actually choose English in this drop-down list, the interface changed to English. So - it is just a cosmetic issue: the Language preference should be set according the system setting.

**Comment by glushchenko** [comment]
Fixed. Please try 4.2.1 https://github.com/glushchenko/fsnotes/releases/download/4.2.1/FSNotes_4.2.1.zip
