### ISSUE TITLE
cmd + option + shift + L and `cmd + option + shift + n keyboard shortcuts are not working

### ISSUE THREAD

**Issue by VKondakoff** [glushchenko/fsnotes#862]
**Describe the bug**
`cmd + option + shift + L` and `cmd + option + shift + n` keyboard shortcuts are not working on my system. `cmd + option + shift + L` just do nothing, and `cmd + option + shift + n` creates new note, while is should save clipboard, according to the docs:

> `cmd + option + shift + L` - open main window and focus search bar
> `cmd + option + shift + n` - save clipboard
> 

**Expected behavior**
I was hoping `cmd + option + shift + L` shortcut to be a global system shortcut to open FSNotes main window while I'm working in another app. Am I wrong?

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.4
 - FSNotes version: 4.2.0 (374)

**Additional context**
To be honest, I don't understand what 'save clipboard' means. Just paste from the clipboard (Cmd+V)? Something else?
Here is an excerpt from the docs. What does this means?

> Global shortcuts (clipboard save/search).

**Comment by gingerbeardman** [comment]
> cmd + option + shift + n - save clipboard

create new note using the contents of clipboard

**Comment by VKondakoff** [comment]
Ah, thank you. Unfortunately `cmd + option + shift + n` does not work on my system. If the keyboard layout is Ru, it creates empty note. If the keyboard layout is En it just do nothing.
`cmd + option + shift + L` does not work in either keyboard layout.

**Comment by glushchenko** [comment]
Documentation bug, of course proper shortcuts is:

control + option + shift + L and control + option + shift + n
