### ISSUE TITLE
Attached images are not deleted when deleting note

### ISSUE THREAD

**Issue by VKondakoff** [glushchenko/fsnotes#863]
**Describe the bug**
Attached images are not deleted when deleting note which contains this image (Container set to None). The image stays in "i" subfolder even after you delete note from the Trash folder. 
The images are moving along with the note when moving notes across folders (say, from Notes to Archive). The images are moved when you drag note from Notes to Trash, as well. But they are not deleted when you delete note. Currently there are around 15 orphan images in my 'i' folders after just an hour of work. I think this is terribly wrong and this issue is a show stopper for me.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.4
 - FSNotes version: 4.2.0 (374)

**Additional context**
I'm aware of textbundle availability: this container is great for sharing notes. But I'm pretty sure even when Container is set to None, the attachments path should be updated when moving notes around folders and attachments should be deleted when deleting corresponding notes.

There is a report about this from the last year: https://github.com/glushchenko/fsnotes/issues/548
I'm really surprised nobody noticed this issue... :(

**Comment by glushchenko** [comment]
Thanks for feedback, fixed.

**Comment by glushchenko** [comment]
Please try 4.2.1 https://github.com/glushchenko/fsnotes/releases/download/4.2.1/FSNotes_4.2.1.zip
