### ISSUE TITLE
Reset list function

### ISSUE THREAD

**Issue by Gododdin** [glushchenko/fsnotes#864]
I had a search for this but couldn't find it.  I use FSNotes on my Mac and iPhone and one useful thing is a grocery shopping list (especially in these difficult days when we have to be more organised about our shopping!).  So I have a 'universal' grocery list which has everything I could possibly need.  Before I go shopping I tick off any that I don't need, then as I shop I tick off items in my basket.  Now when I get home I would like to **reset** the list to all items unchecked so that it's ready for next time.  Is this a possibility?  Many thanks for a great app!
Rhod

**Comment by glushchenko** [comment]
Implemented, thanks you for feedback.

**Comment by glushchenko** [comment]
Please try 4.2.1 https://github.com/glushchenko/fsnotes/releases/download/4.2.1/FSNotes_4.2.1.zip
