### ISSUE TITLE
"Toggle Todo" deletes text rather than making todo list

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#865]
**Describe the bug**
When selecting a block of text and then using the Toggle Todo formatting action (via the Format menu item or the ⌘0 shortcut), it deletes the text and then replaces it with a  Markdown-style checkbox, rather than turning each highlighted line into a todo list item. The gif below demonstrates this.
Is there a way to get this formatting option to do the latter instead? Thanks!

**To Reproduce**
1. Select multiple lines of text
2. Click on Format > Toggle todo

**Expected behavior**
Each line of text should be preserved, but start with a - [ ] todo list box

**Actual behavior**
The text is replaced

**Supporting Files**
![screenrecording](https://user-images.githubusercontent.com/8772017/80484076-207bc900-8925-11ea-8b52-8463348253e7.gif)
**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - FSNotes version: 4.2.0

**Comment by glushchenko** [comment]
Implemented, thank you for feedback.

**Comment by glushchenko** [comment]
Please try 4.2.1 https://github.com/glushchenko/fsnotes/releases/download/4.2.1/FSNotes_4.2.1.zip

**Comment by volt4ire** [comment]
It's working now – thank you much!!!
