### ISSUE TITLE
Mathjax support feature broken

### ISSUE THREAD

**Issue by shurain** [glushchenko/fsnotes#866]
Mathjax feature seems broken at the moment. LaTeX equation is not rendered properly.

Browse `7. Mermaid and MathJax` notes and see MathJax equation not rendering properly.

<img width="775" alt="screenshot_166" src="https://user-images.githubusercontent.com/509888/80574849-8eb3af00-8a3d-11ea-8656-056279e89676.png">

- OS: macOS
- OS version: 10.15.3
- FSNotes version: 4.2.0 (374)

**Comment by glushchenko** [comment]
MathJax disabled by default now. Click View -> Preview MathJax
