### ISSUE TITLE
Un-indent does not properly update formatting

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#867]
**Describe the bug**
Text formatting updates are semi-broken when removing an indentation. Behavior depends on where you edit the previous line. Here are two examples. This is the initial state:

![screenshot1](https://user-images.githubusercontent.com/1321720/80862323-5b0e9a00-8c74-11ea-9dce-7b6e7e6259e2.png)

If my cursor is at the end of the line and I press shift-tab (to un-indent the line) the text color is updated properly but the background color remains:

![screenshot3](https://user-images.githubusercontent.com/1321720/80862321-5a760380-8c74-11ea-988c-e9847bb56fb9.png)

If my cursor is somewhere in the middle or beginning of the text, pressing shift-tab will not update the formatting of the next line at all. Both, text font and background color remain:

![screenshot2](https://user-images.githubusercontent.com/1321720/80862322-5b0e9a00-8c74-11ea-973f-1dcec16f8607.png)

On the other hand, if I un-indent and re-indent line "four" the formatting is as follows:

![screenshot4](https://user-images.githubusercontent.com/1321720/80862320-5944d680-8c74-11ea-9026-251d4ba8d86f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.3
 - FSNotes version: 4.2.0

**Comment by glushchenko** [comment]
This is not bug.

On the screens i see "indented code blocks". You can disable it here:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/1089917/124378390-c0677c00-dcb9-11eb-9794-9fe273814182.png">

**Comment by relikd** [comment]
It is a while ago since I submitted the issue. But if I remember correctly this issue has nothing to do with the option you mentioned. My point was that un-indenting and re-indenting a text-line does not produce the same output as pasting the text as a whole. There is a state in-between where some parts are highlighted correctly and others are not. Feels like the `change code` > `update formatting` cycle does not update all affected lines.

**Comment by glushchenko** [comment]
Thanks @relikd, may be. But now seems all OK.
