### ISSUE TITLE
Setting to Ignore Files/Folders

### ISSUE THREAD

**Issue by igutekunst** [glushchenko/fsnotes#868]
**Feature**
Specify at least one folder, and ideally multiple patterns for paths to be ignored by the editor. This could be implemented similar to a .gitignore file, or as a setting in the UI.

**Motivation**
I'd like to store some scripts and automation inside my root notes folder. I have an experimental web server that generates a site of all my notes, which is helpful so I can share read-only access to other people. It would nice to have the files associated with this ignored by the editor so they don't interfere with search results. This is especially pronounced when I have a python virtual env, with lots of dependencies. 

I can take a crack at implementing this myself if you point me in the right direction.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/wiki/Advanced-settings#hideshow-directories-in-sidebar-fsnotes-497
