### ISSUE TITLE
Ability to configure GIT to use System config

### ISSUE THREAD

**Issue by apvarun** [glushchenko/fsnotes#869]
Currently, the bundled GIT in FS notes is not configurable. It doesn't use the system's git config but uses its own one.

This prevents to use git hooks as they run without system context, and so not having PATH set properly.

**How to reproduce:**
- Add a post-commit hook that will push the code to a remote git when backup happens
- Manually backup your notes - DOES NOT RUN THE HOOK
- Try an empty commit from terminal - HOOK IS TRIGGERED AND EXECUTED

**Expected:**
- Should be able to use the system git or at least the config from system.
- Run hooks with the system config and PATH being set properly

**Additional context**
Operating System: macOS
FSNotes version: 4.2.0

I noticed that FSNotes sets the `GIT_CONFIG_NOSYSTEM` as true by default. That might help in triaging the issue.

**Comment by glushchenko** [comment]
Git implementation moved to libgit2, so no, sorry.
