### ISSUE TITLE
MATH_JAX_JS at the head of page

### ISSUE THREAD

**Issue by kiiiiit** [glushchenko/fsnotes#871]
**Describe the bug**
I'm going to print any pages, but at the top of page I see this title:
`MATH_JAX_JS`

**To Reproduce**
1. Make any page.
2. Print it.
3. Scroll down to the top.

**Expected behavior**
Clear page without of any errors.

**Desktop (please complete the following information):**
- OS: macOS
- OS version: 10.15.5 (19F72f)
- FSNotes version: 4.2.0

**Additional context**
Example in the previous issue in file [list.pdf](https://github.com/glushchenko/fsnotes/files/4580726/list.pdf).

**Comment by glushchenko** [comment]
Thanks, fixed.

**Comment by kiiiiit** [comment]
Hello! Thank you for your application!
New version doesn't work correctly too :(

## Desktop (please complete the following information):

OS: macOS
OS version: 10.15.5 (19F72f)
FSNotes version: 4.2.2

[MATH_JAX_JS.pdf](https://github.com/glushchenko/fsnotes/files/4586961/MATH_JAX_JS.pdf)

**Comment by glushchenko** [comment]
This not released yet.

**Comment by kiiiiit** [comment]
It works! Thank you!
