### ISSUE TITLE
Menu bar menu brings app to front

### ISSUE THREAD

**Issue by sitase** [glushchenko/fsnotes#873]
**Describe the bug**
Clicking in the menu bar menu (not the app menu) brings the app to front. This is unexpected and contrary to the purpose of menu bar menus (might just as well switch to the app and invoke the same menu bar item from the menu bar there). 

**To Reproduce**
Click on  the menu bar icon (text and flash icon).

**Expected behavior**
The menu  should drop down, but focus should remain wherever it was before.

**Actual behavior**
FSNotes is brought to front, potentially switching spaces.

**Workaround**
Not using the menu 
**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.15.3
 - FSNotes version: 4.2.2 (378)

**Additional context**

I would expect this menu to expose functionality that does not require the app to come to front. Such as a HUD window for quick entry of a new note without leaving the current context.

**Comment by glushchenko** [comment]
This is not a bug. Right click does what you want.

**Comment by sitase** [comment]
No other menu bar extra that I have changes focus like that, so I would definitely say it is unexpected behaviour. 

Also, right clicking on the menu bar extra still brings the app to front, changing spaces.

**Comment by glushchenko** [comment]
I think it fixed long time ago, feel free to open if right click not working
