### ISSUE TITLE
HUD window for creating a new note without leaving current context

### ISSUE THREAD

**Issue by sitase** [glushchenko/fsnotes#874]
**Describe your feature request**
A quick action that would bring up a HUD window that would permit entry of a new note without bring fsnotes to front, keeping the current app in focus (and thus the context the user is in).

**Additional context**
macOS

**Comment by sitase** [comment]
See #873 for bug  that is a blocker for this request.

**Comment by glushchenko** [comment]
In FSNotes 6 available new feature – Quick Note. I thing you will be satisfied ;-)

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
