### ISSUE TITLE
latency while typing

### ISSUE THREAD

**Issue by bsphere** [glushchenko/fsnotes#875]
I'm new to fsnotes and there's a very annoying latency while I type.
I tried to disable live syntax highlighting and it's the same.

**To Reproduce**
1. create a new note
2. type anything

**Expected behavior**
typing should not have any delays

**Actual behavior**
latency while typing

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.4
 - FSNotes version: 4.2.3

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/tag/4.2.4

**Comment by bsphere** [comment]
i think its a bit better, but it still doesn't feel as responsive as any other app...

an extreme case is if I do "new RTF". they latency is insane. i'm not using this mode but it emphasizes the problem.

**Comment by glushchenko** [comment]
I don't know how to reproduce this. Works fine for me.

**Comment by gingerbeardman** [comment]
> i think its a bit better, but it still doesn't feel as responsive as any other app...

Can you share a screen recording?
