### ISSUE TITLE
Titles on previously imported notes change when "First line as title" setting changed

### ISSUE THREAD

**Issue by bradydjohnson** [glushchenko/fsnotes#876]
**Describe the bug**
When I create a new note, based on nvALT's behavior, I expect the first line to become the title. This does not happen when "First line as title" is unchecked. 

Now, if I check "First line as title," then the titles to all of my notes imported from nvALT get messed up. 

**To Reproduce**
1. Create new note
2. Start typing. Notice that note title is a random string of characters.
3. Set "First line as title" setting to checked
4. Notice how all imported notes have their titles changed.

**Expected behavior**
Titles on previously-imported notes to stay the same when checking/unchecking "First line as title"

**Actual behavior**
Titles change when checking/unchecking "First line as title"

**Workaround**
None.

**Supporting Files**
<img width="591" alt="FSNotes 2020-05-06 20-14-06" src="https://user-images.githubusercontent.com/6741590/81243790-6a744700-8fd6-11ea-8b2e-7d8bb3e564e2.png">

<img width="585" alt="FSNotes 2020-05-06 20-16-30" src="https://user-images.githubusercontent.com/6741590/81244048-f25a5100-8fd6-11ea-9ccb-e0230db023ae.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.15.4
 - FSNotes version: 4.2.0

**Additional context**
None.

**Comment by glushchenko** [comment]
Of course previously imported notes changed too, how do you imagine should i separate old and new notes?

**Comment by gingerbeardman** [comment]
Not sure about this idea, but perhaps only notes with UUID filenames could be changed?
