### ISSUE TITLE
Timestamp as default filename

### ISSUE THREAD

**Issue by mcchrish** [glushchenko/fsnotes#877]
**Describe your feature request**
Instead of a random string (I think it's UUID?) for default filename when creating a new note, use a timestamp of the time the note is created. Something like`2019-12-25 12.57.59 PM`.

Or at least an option for this.

**Comment by jakemkc** [comment]
In Fsnotes, if you create a new note by "cmd+n", it will create a file with UUID(?).

However, if you create a note with "cmd+L" (it's a search but equivalent to create a new note if the term is unique), it will use the search term as filename.

I think a non-elegant workaround could be: use timestamp text expansion by 3rd party app when you create a new note with the search function. For example, I am using Alfred to insert timestamp.

Jake

**Comment by sloria** [comment]
This would be nice. Zettelkasten uses the `yyyyMMddHHss` format for note IDs (example: `202005121126`). Seems like a better default than UUIDs. It could be useful to have an option to select between

1. 2019-12-25 12.57.59 PM
1. 20191225126759
1. UUID

Certainly not a "Must Have" for me since I use BetterTouchTool to generate the timestamp IDs when I type `,,t`. But having this built-in might allow me to get rid of that, and it would probably useful for other Zettelkasten users.

**Comment by mcchrish** [comment]
Wow, thanks for the suggestions. I actually just have discovered that all along I have a trick to do this as well. Instead of Alfred or BetterTouchTool I have Dash.

Would still be nice for FSNotes to support this regardless.

**Comment by gingerbeardman** [comment]
@mcchrish can you outline your method for the benefit of others?

**Comment by mcchrish** [comment]
I don't own Alfred nor BetterTouchTool so I don't really can't compare what are their differences. But to explain how it works with Dash, it's kinda the same as behavior as other text expanders. e.g. I type "`dt" and it will expand to the current date time.

**Comment by gingerbeardman** [comment]
The Dash app I have is the API doc viewer? Is there another?

**Comment by sloria** [comment]
@gingerbeardman Looks like Dash (the doc viewer) has support for snippet expansion: http://kapeli.com/guide/guide.html#snippets .

**Comment by gingerbeardman** [comment]
Nice!

**Comment by glushchenko** [comment]
> Added 3 new options 

1. Untitled Note
2. 2019-12-25 12.57.59 PM
3. 20191225126759

**Comment by glushchenko** [comment]
Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

**Comment by wilhelmloof** [comment]
> Please test https://github.com/glushchenko/fsnotes/releases/tag/5beta1

Great.
But "yyyy-MM-dd HH.mm.ss" didn't exist, only "yyyy-MM-dd HH.mm.ss a" and "yyyyMMddHHmmss" created a new file based on title.

**Comment by glushchenko** [comment]
@wilhelmloof anyone requested "yyyy-MM-dd HH.mm.ss"? I see only "yyyy-MM-dd HH.mm.ss a " in issue.

**Comment by wilhelmloof** [comment]
> @wilhelmloof anyone requested "yyyy-MM-dd HH.mm.ss"? I see only "yyyy-MM-dd HH.mm.ss a " in issue.

In the v5b1 release (https://github.com/glushchenko/fsnotes/releases/tag/5beta1), it reads:

> * Adds new default filenames "Untitled Note", "yyyy-MM-dd HH.mm.ss", "yyyyMMddHHmmss"

But "yyyy-MM-dd HH.mm.ss" is not available in beta 1.

**Comment by wilhelmloof** [comment]
> Just mistake in change log, thanks

Ok

But "yyyy-MM-dd HH.mm.ss" is a nice format for filename. And if "yyyy-MM-dd HH.mm.ss a" is available then logically so should also "yyyy-MM-dd HH.mm.ss" be.
