### ISSUE TITLE
Wrong syntax highlighting of list item markers

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#879]
Characters used as list item markers (digits, dot, hyphen, plus, asterisk) get highlighted everywhere in list items (not just at beginning of item and followed by a whitespace):

![Screenshot 2020-05-08 at 16 07 36](https://user-images.githubusercontent.com/30050534/81413913-8696f600-9146-11ea-8685-6fa75f9d6d50.png)

**Desktop:**

 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.2.4

**Comment by glushchenko** [comment]
Fixed, thanks!
