### ISSUE TITLE
Multilevel ordered list compilation error

### ISSUE THREAD

**Issue by kiiiiit** [glushchenko/fsnotes#883]
**Describe the bug**
I make multilevel ordered list, but when I gonna print document without of any css files, list compiled with error started from paragraph 2.

**To Reproduce**
1. Make multilevel ordered list
2. Compile
3. Print

**Supporting Files**
Markdown list on file - list.png
<img width="1154" alt="doc" src="https://user-images.githubusercontent.com/8556010/81493982-a4cb3600-92ad-11ea-9765-1ae2a0bb43c9.png">

Preprint list on file - doc.png
<img width="1154" alt="list" src="https://user-images.githubusercontent.com/8556010/81493952-6e8db680-92ad-11ea-90ca-62621ccd4bc7.png">
**Desktop (please complete the following information):**
 - OS: macOS
 - FSNotes version: 4.2.6

**Comment by glushchenko** [comment]
This is default markdown rendering behaviur by cmark-gfm. Please open issue here https://github.com/github/cmark-gfm

**Comment by glushchenko** [comment]
If you want make non markdown lists, just use RTF.
