### ISSUE TITLE
Unexpected List behavior

### ISSUE THREAD

**Issue by ziiem** [glushchenko/fsnotes#893]
**Describe the bug**
When changing several lines that start with numbers into a List, FSNotes removes the numbers and some of the following characters.

**To Reproduce**
1. Select all lines:
> 200ml
> 500g
> 25ml
> 10g
> 1kg

2. Format > List

**Expected behavior**
Expected result:
> - 200ml
> - 500g
> - 25ml
> - 10g
> - 1kg

**Actual behavior**
Actual result:
> - ml
> - g
> - l

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.4
 - FSNotes version: 4.3.2 (389)

**Comment by glushchenko** [comment]
Fixed, thanks for bug report.
