### ISSUE TITLE
Option to add `.` image folder prefix for the image path, which need to be compatible with Typora or DEVONthink

### ISSUE THREAD

**Issue by JimmyLv** [glushchenko/fsnotes#894]
e.g. Typora can't render the image with `![](/i/07349593-2762-4aa2-a68f-21e746d9b234.jpg)` but work with `![](./i/07349593-2762-4aa2-a68f-21e746d9b234.jpg)`

![image](https://user-images.githubusercontent.com/4997466/81761080-91ada580-94fb-11ea-915e-2d35211fa560.png)

![image](https://user-images.githubusercontent.com/4997466/81761127-b73aaf00-94fb-11ea-8ef0-67dab1b7e40f.png)

**Comment by glushchenko** [comment]
Root slash removed in last build.
