### ISSUE TITLE
Highlight marks

### ISSUE THREAD

**Issue by gittynick** [glushchenko/fsnotes#896]
**Describe your feature request**
Hello, I would much like to have the ==highlight== markdown supported

**Additional context**
macos and ios

**Comment by gingerbeardman** [comment]
Where did you see this syntax?

FSNotes uses https://commonmark.org specification.

**Comment by gittynick** [comment]
That must have been some kind of "wishful thinking" from my side as I like highlighting texts, I didn't realise it was not a common mark. FYI I found it ia writer's last update notice https://ia.net/writer/blog/new-pdf-preview-better-web-publishing-improved-editing

**Comment by glushchenko** [comment]
No
