### ISSUE TITLE
Ability to list all untagged notes

### ISSUE THREAD

**Issue by kaizau** [glushchenko/fsnotes#899]
**Describe your feature request**

Currently on Mac, individual tags are visible in the sidebar. However, there's no easy way to list all notes that _do not have any tags_.

It'd be useful to see a "not tagged" item in the sidebar:

![example](https://user-images.githubusercontent.com/226967/82434620-b2f72e80-9ac5-11ea-94c5-a23f66e20c1f.jpg)

**Additional context**

This is often possible in other note-taking apps via advanced search syntax (ex: Evernote, Bear). So there's more than one way to achieve the same end.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/5beta3/FSNotes_v5beta3.zip
