### ISSUE TITLE
default file extension not respected in 1.2.1

### ISSUE THREAD

**Issue by jeff-h** [glushchenko/fsnotes#90]
First, thanks again for all your ongoing work bringing such a great app into being! I don't miss nvALT at all anymore, and it's a really nice feeling knowing that all my notes are now accessible from an app which is at the start of its life, not creaking and groaning at the end like nvALT seems to be.

Anyway, to the issue... for me at least, v1.2.1 does not respect the 'default file extension' preference, and always creates notes in `md` rather than my chosen `rtf`. It was fine 1.1.18.

**Comment by glushchenko** [comment]
Fixed in 1.2.2

**Comment by jeff-h** [comment]
Brilliant!
