### ISSUE TITLE
[iOS] Disable Show Title by First Line

### ISSUE THREAD

**Issue by ybbond** [glushchenko/fsnotes#900]
**Describe your feature request**
Add configuration option to display note in the notes list by their file names.
Like the macOS version.

**Additional context**
iOS & iPadOS.

**Comment by glushchenko** [comment]
You can dot it in settings.

**Comment by ybbond** [comment]
Sorry but I cannot find the settings in the app (to be clear I meant iOS app)

I tried both the AppStore and Testflight version with no luck

**Comment by glushchenko** [comment]
![IMG_1728](https://user-images.githubusercontent.com/1089917/83360965-dce60600-a38d-11ea-97cc-14bb7ee45601.jpg)

![IMG_1729](https://user-images.githubusercontent.com/1089917/83360970-e4a5aa80-a38d-11ea-814b-75982508c277.jpg)

**Comment by ybbond** [comment]
This is embarassing, I didn’t try to press each items from the lists 
in `Projects`.

Thank you for the guide @glushchenko ! Dyakuyu!

I will close this Issue now.

**Comment by glushchenko** [comment]
No problem. You can do it here too:

![image](https://user-images.githubusercontent.com/1089917/83361387-4287c180-a391-11ea-8770-653c8d36a9e4.jpeg)
