### ISSUE TITLE
Search timeInterval 

### ISSUE THREAD

**Issue by samer** [glushchenko/fsnotes#901]
Hello,
I'm a new FSNotes user trying to re-create the nvAlt experience as much as possible. Thank you so much for your hard work so far!

One thing I have noticed is the timer on the search field, as can be seen in the following line of code: https://github.com/glushchenko/fsnotes/blob/5066637c4dcca92b31d1c9fb66cdeeecd399fa82/FSNotes/View/SearchTextField.swift#L106

One thing I love about nvAlt is that the search was instantaneous and had no timeout. Do you think that this timeout is absolutely necessary, or could it be removed?

**Comment by glushchenko** [comment]
Check 4.4.0

**Comment by samer** [comment]
Fixed, thanks!
