### ISSUE TITLE
Import sub-folders

### ISSUE THREAD

**Issue by kerim** [glushchenko/fsnotes#904]
**Describe your feature request**
If I import a folder of files from the finder, I'd like all the files in all the subfolders imported as well. As best I can tell, right now FSNotes only imports the top-level items and ignores the subfolders? 

**Additional context**
I tried both importing and also just dragging and dropping to my FSNotes folder.

**Comment by gingerbeardman** [comment]
Items in sub folders come up in search but the hierarchy which folder is this in?) is hidden.

See #188 from 2018.
