### ISSUE TITLE
Incorrect error when creating title with a /

### ISSUE THREAD

**Issue by GeoJunkie** [glushchenko/fsnotes#907]
**Describe the bug**
When changing a note's title to something containing the `/` character, FSNotes incorrectly reports that the note already exists

**To Reproduce**
1. Go to a note
2. Double click the title area to change the title
3. Type a title containing a slash (`/`) (that doesn't already exist).

**Expected behavior**
Either a / should be allowed in the filename, or the error should indicate that the filename has illegal characters (preferably with a list). 

**Actual behavior**
The error message `File with name "fname/withslash" already exists!` is displayed

**Workaround**
No workaround. However, it will cause confusion and doesn't properly inform the user how to fix. the error.

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

![](https://d.pr/i/L9awhr+)
Image Link: https://d.pr/i/L9awhr

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.5
 - FSNotes version: 4.0.25 (362)

**Additional context**
It looks like this was incompletely reported in #38 but no follow-up action was reported.

**Comment by glushchenko** [comment]
Finally fixed https://github.com/glushchenko/fsnotes/releases/download/4.9.0b444/FSNotes_4.9.0.zip
