### ISSUE TITLE
list of self creating projects ?

### ISSUE THREAD

**Issue by wizardfox3** [glushchenko/fsnotes#908]
**Describe the bug**
Hello,
On the iOS app on the blue screen to the left where projects go there are many that I did not create listed. I am not clear as to where they can from. I have deleted them manually and they simply reappear. Any suggestions?
Thank you. Please see attached picture. 

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Workaround**
A clear and concise description of any workarounds.

**Supporting Files**
![1542F18F-0922-49BC-8B79-5BD2E5CEF050](https://user-images.githubusercontent.com/41124755/83277589-8a3efb00-a18f-11ea-9e21-4fe13e462d05.png)

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 3.8.2

**Additional context**

**Comment by glushchenko** [comment]
Are you using macOS version?

**Comment by wizardfox3** [comment]
Hello,

Yes. I am using the Mac version on 2 laptops, no modifications of where files are stored. 

Thank you 
I love the app so far. 

Isak

**Comment by glushchenko** [comment]
So, are you changed Preferences -> Git -> Repository path?

**Comment by wizardfox3** [comment]
Hello,
Thank you for your response.

Here is what happened:
- installed FSNotes on iOS and OS on two different MacBook pros
- Changed file repository to dropbox (For some reason I thought that would be better)
- iOS wasn’t syncing with OS so I deleted all apps from iOS and OS on both laptops
- Installed FSNotes on my primary laptop and iOS
- The new installation on OS shows the GIT repository to point to the main FSNotes folder in iCloud (Could not understand how to get
it to point back to the default repository….not sure where that is exactly.
- I think it needs to point to: Users > wizardfox3 > Library > Mobile Documents > iCloud~co~fluder~fsn > Documents
	- However, when I click ‘change’ within: FSNotes > Preferences > Git; I do not know how to to get the path listed directly above
	- The above path was found in ‘Preferences > General > Default Storage

- I thought deleting the apps and reinstalling them would solve the problem.

- I apologize for mistake and any inconvenience, however I’d really like to solve the problem as FSNotes is exactly 
what I’ve been looking for, for a few years. Appreciate it.

Below are screenshots that may be useful. I have tried to include as much info in respect for your time.


What may help me out is to know the correct paths for OS to match with iOS
- Preferences
	- General
		- Repositories:?
 - Preferences
	- Git
		- Repositories:?
- Preferences
	- Advanced
		- Repositories:?

Thank you,
Isak

**Comment by glushchenko** [comment]
You Git repository path was changed to root directory, and all backups subfolders now visible in default storage. This is wrong, Git repository should be stored ideally on external HDD or any another dir, non root.

**Comment by wizardfox3** [comment]
Ok great. Thank you. 
Would you mind suggesting where i should direct the Git repository?

Isak

**Comment by wizardfox3** [comment]
Please provide the paths for the preferences so I can use the app properly. If the correct info is provided I will not need to bother you anymore. Thanks again. Appreciate it. 

What may help me out is to know the correct paths for OS to match with iOS
- Preferences
	- General
		- Repositories:?
 - Preferences
	- Git
		- Repositories:?
- Preferences
	- Advanced
		- Repositories:?

Thank you,
Isak

**Comment by wizardfox3** [comment]
I think i understand. I changed the Git depository to my computer And nothing changed. 

Please help my fix this problem. I bought it and I want it to work properly. 

Please provide the info I need so I can fix and not need to bother you again. 

Thank you.

**Comment by glushchenko** [comment]
Change Git path and just remove *.git folders.

**Comment by glushchenko** [comment]
.git folder excluded in FSNotes 4.0 for mobile, please update if not do it yet.
