### ISSUE TITLE
Show parent folder of note

### ISSUE THREAD

**Issue by spacekaila** [glushchenko/fsnotes#909]
**Describe your feature request**
Currently, notes do not display their path/parent folder. This means if I click on a storage location and see all notes within that location, I have no way of knowing to which folder a note belongs without clicking "view in finder". I would like the ability to display what folder a note belongs to when viewing the note list or individual notes.

**Additional context**
I only have experience with macOS, but this would probably be useful for all platforms.

**Comment by gingerbeardman** [comment]
Yes, +1

See #188 from 2018.

**Comment by glushchenko** [comment]
Implemented
