### ISSUE TITLE
Note Font preference doesn't stick

### ISSUE THREAD

**Issue by wolfromm** [glushchenko/fsnotes#91]
v1.2.1 (81) [bug introduced with this version]
The font type returns to the default type whichever the value specified in the preferences.

**Comment by wolfromm** [comment]
It looks like the right font is only applied to `md` files (this problem doesn't occur for the background color) 

-- and as said in #90 the new notes are created as `md` files even if the default file extension is `txt`.

**Comment by glushchenko** [comment]
And one more thing ... Now any font in RTF document, auto converts to default font considering bold/italic selections.

**Comment by wolfromm** [comment]
Thank you.
