### ISSUE TITLE
GFM-style line endings (that don't require two spaces)

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#910]
**Describe your feature request**
Is there a way to have FSNote's markdown rendering respect Github Flavored Markdown-style line endings, such that new lines don't require two spaces at the end of a line? Thanks!

**Additional context**
macOS

**Comment by glushchenko** [comment]
Two spaces don't need anymore.

**Comment by volt4ire** [comment]
Thanks for timely reply for this issue! I'm still having the issue of FSNotes combining two separate lines into one in the preview mode – please see the .gif below. Thanks!
![gif](https://user-images.githubusercontent.com/8772017/83417394-046dba80-a3f0-11ea-9eaa-207b2947f13f.gif)

**Comment by volt4ire** [comment]
@glushchenko Thanks for timely addressing of this issue! Do you know when you'll update the current compiled version on the Releases page to include the [commits you made](https://github.com/glushchenko/fsnotes/commit/51bf50fb21feabfe9e755663e5da1e7e0862c340)? Thanks!

**Comment by glushchenko** [comment]
@volt4ire FSNotes for mac i planned to release one week ago. But FSNotes 4.0 for iOS takes all my time.

macOS version will be released not later then iOS version, because Handoff already implemented. 

I rewrote the entire animation for the second time and am almost ready to release it.

**Comment by volt4ire** [comment]
Great thanks so much!!
