### ISSUE TITLE
App Not Responding

### ISSUE THREAD

**Issue by kerim** [glushchenko/fsnotes#912]
**Describe the bug**

The MacOS app becomes unresponsive. I have to force quit and restart to use it.

**To Reproduce**
Unclear if anything in particular triggers this. All I know is that I switch to the app and get a spinning wheel.

**Expected behavior**
App doesn't hang.

**Actual behavior**
App is unresponsive. 

**Workaround**
Force quit.

**Supporting Files**
I have submitted logs many times using the Apple built-in crash reporter, but stopped doing it because it happened so many times.

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.15.5
 - FSNotes version: 4.3.3

**Comment by gingerbeardman** [comment]
How many notes do you have?

Do you have time to _binary search_ your notes to see if one is problematic?

> Binary Search: Search a sorted array by repeatedly dividing the search interval in half. Begin with an interval covering the whole array. If the value of the search key is less than the item in the middle of the interval, narrow the interval to the lower half. Otherwise narrow it to the upper half. Repeatedly check until the value is found or the interval is empty.

**Comment by kerim** [comment]
I have about 1800 notes. I have no idea how to search for "an interval covering a whole array"? These are all plain text notes, if FSNotes crashes because of a plain text note, something is wrong. Shouldn't error logs or something of the sort catch the problem?

**Comment by glushchenko** [comment]
Try to disable scheduled Git backups.

**Comment by gingerbeardman** [comment]
@kerim sorry that was a quick google search description, i have rephrased the technique of binary search.

**Comment by kerim** [comment]
Thanks both. It seems to me that scheduled Git backups could be the problem, since it often happens when the app is in the background. I'll disable it and see if that helps. If not, I'll try removing notes and see if that helps.

**Comment by kerim** [comment]
Since I turned off Git backups I have not seen the problem happen again.

**Comment by glushchenko** [comment]
Please try 4.4.0

**Comment by kerim** [comment]
Updated today. So far no problems. Thanks.

**Comment by glushchenko** [comment]
Thanks for patience @kerim.
