### ISSUE TITLE
Does FSNotes collect any analytics or telemetry about its users?

### ISSUE THREAD

**Issue by brianwood2783** [glushchenko/fsnotes#913]
Since there's no mention to a privacy policy here on GitHub or on the website, I thought I'd explicitly ask if FSNotes collects any information about its users or the software itself (examples: file names, number of notes, metadata in general, usage time, settings, etc).

I like how the websites states very clearly that is an open source project and there will be no subscriptions ever. It sets a good a tone and users know what to expect from the developers on the future, making relationship with its users very transparent, which I congratulate and appreciate very much!

It'd be great to learn the developer's views on privacy, and whether FSNotes collects any data or not, and if it intends to so in the future. 

I could help drafting a privacy policy of sorts, or a simpler document at least (I'm not a lawyer). I'd venture to say users of open source projects care more about privacy than average, so it could help make the relationship even more transparent.

**Comment by gingerbeardman** [comment]
Take a look at the source code :)

**Comment by glushchenko** [comment]
Don't worry @brianwood2783, any data collection not planned.
