### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by danielparton** [glushchenko/fsnotes#914]
Would it be possible to add a table of contents feature?
The user would type something in the note such as `[toc]` or `{{TOC}}`, and the renderer would generate a table of contents with clickable anchor links that lead to specific sections.

For example, in MacDown:

![image](https://user-images.githubusercontent.com/4217946/83588653-da1b1a80-a51f-11ea-8233-a22d10b5c69d.png)

I would find this feature extremely useful for longer notes.

I'm personally interested in this only for macOS (since I use Android), but it would probably make sense for iOS too.

**Comment by gingerbeardman** [comment]
this would most likely rely on upstream https://github.com/commonmark/cmark/issues/78

but it's possible to use macOS to do this. you could create a [Service](https://github.com/glushchenko/fsnotes/wiki/Services-(macOS)) using something like https://github.com/jonschlinkert/markdown-toc

**Comment by danielparton** [comment]
Thanks @gingerbeardman - interesting this is such a long-standing issue. I guess we'll have to hope that commonmark will eventually settle on a solution. Otherwise perhaps this could be implemented as some kind of post-rendering step in fsnotes. In the mean time there is the workaround you suggest.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
