### ISSUE TITLE
Slow search speed

### ISSUE THREAD

**Issue by ccast04** [glushchenko/fsnotes#915]
Searching from the global search bar results in a 1.5 second delay before any notes are displayed (I'm just starting with the default Welcome package). It may not sound like much, but I assume it's a bug because NValt and nvUltra beta for me are instantaneous incremental search.

Using macOS version 10.15.5
FSNotes version 4.3.3

**Comment by ccast04** [comment]
does this mean that I ignored the template? I included all of the relevant information in the request a more compact format. I can refile if that's going to be faster

**Comment by glushchenko** [comment]
Dont worry, I'll see what can be done later.

**Comment by gingerbeardman** [comment]
@ccast04 it's purely admin, we like to encourage reports in the same format to make it easier for us to deal with

**Comment by samer** [comment]
related: https://github.com/glushchenko/fsnotes/issues/901

**Comment by glushchenko** [comment]
Guys, i think 4.4.0 resolves an issue.
