### ISSUE TITLE
Misaligned cursor position when inserting list item

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#916]
**Describe the bug**
Misaligned cursor position when inserting list item

**To Reproduce**
1. create a list of items using the - character
2. go to the end of one of the lines somewhere in the middle of the list
3. press enter
4. look at cursor position

**Expected behavior**
 - cursor should be aligned with text

**Actual behavior**
- cursor is not aligned with text

**Workaround**
- start typing and things correct themselves

**Supporting Files**

> ![Screen shot 2020-06-10 at 11 25 41](https://user-images.githubusercontent.com/49612/84257825-deda6280-ab0d-11ea-911f-162f6043de91.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.14.6
 - FSNotes version: 4.3.3

**Comment by glushchenko** [comment]
Thank you, Matt. I will try to fix it after FSNotes for iOS release.

**Comment by glushchenko** [comment]
Interesting, can not reproduce, which font do you use?

**Comment by gingerbeardman** [comment]
I use SFMono but can no longer reproduce with 4.4.0 versions.

**Comment by gingerbeardman** [comment]
This is happening again for me. 

I'm using FSNotes 4.7.0 beta 3 
- 4.7.0 (419)

**Comment by gingerbeardman** [comment]
OK, here's a video

The really odd thing is that if I cmd+tab to another app and back then the cursor redraws in the correct place so it feels like this a rendering issue?

https://imgur.com/1ZU6tDR

**Comment by glushchenko** [comment]
Seems fixed in FSN5

**Comment by gingerbeardman** [comment]
Is this related?

- Look at smaller line height on blank lines compared to text lines.
- Then I cut and paste the whole note and blank lines now have proper line height.
- Then I quit and restart FSNotes and blank lines are narrow.

https://user-images.githubusercontent.com/49612/128607604-12236169-1568-4317-a8e4-b67a89e522b9.mov

**Comment by glushchenko** [comment]
Can you attach example?
