### ISSUE TITLE
Notes disappear from note list after removal of searched text from 'Seach or create' field

### ISSUE THREAD

**Issue by DEC32768** [glushchenko/fsnotes#919]
**Describe the bug**
List of notes disappears when searched text deleted in 'Seach or create' field in case of 'Notes' or 'Documents' mode were used on sidebar to list notes

**To Reproduce**
1. Open default notes set
2. Click on 'Notes' on sidebar
3. Click on 'Seach or create' field
3. Type any search text/symbol(s), e.g. 'nvALT'
4. Remove search text from 'Seach or create' field
5. List of notes disappears 

**Expected behavior**
List of notes shall list all notes when 'Seach or create' field is empty

**Actual behavior**
List of notes disappears (no any note displayed) when search text deleted from 'Seach or create' field

**Workaround**
Select any other sidebar item and than re-select 'Notes' you will see all notes again

**Supporting Files**
not applicable

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.3.3 (390)

**Additional context**
the same behaviour when 'Documents' mode selected on sidebar

**Comment by glushchenko** [comment]
Seems fixed long ago, write if not so.
