### ISSUE TITLE
Sort by 'Modification date' works incorrectly when folder selected in sidebar

### ISSUE THREAD

**Issue by DEC32768** [glushchenko/fsnotes#920]
**Describe the bug**
Sort by 'Modification date' works incorrectly when folder selected in sidebar

**To Reproduce**
1. Open default notes set
2. Click on 'Welcome' folder in sidebar
3. Create 3-4 test notes
4. Select View/Sort by/Modification date so that the last modified note will be on top of the list
5. Select 'Documents' (or 'Notes) on sidebar and note the order of modified notes in the list
6. Select 'Welcome' folder in sidebar and note that order of modified notes has changed in the list of notes

**Expected behavior**
Order of sorted notes (e.g. latest note on top of the list) shall remain the same when you re-select folder view in sidebar

**Actual behavior**
Sorted list of notes changes when folder view on sidebar switched to 'Notes' (or 'Documents') and than back to folder ('Welcome') view

**Workaround**
no workaround found

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.
[Sorting bug.zip](https://github.com/glushchenko/fsnotes/files/4773811/Sorting.bug.zip)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.3.3 (390)

**Additional context**

**Comment by glushchenko** [comment]
Welcome project has exclusive project settings:

![image](https://user-images.githubusercontent.com/1089917/107556501-29523880-6be1-11eb-98e9-6bbdfa7d0800.png)

No bugs here.
