### ISSUE TITLE
IP address as a tag is not displayed in sidebar

### ISSUE THREAD

**Issue by DEC32768** [glushchenko/fsnotes#921]
**Describe the bug**
When IP address added as a tag (e.g. `#1.1.1.1`) it is not displayed in sidebar

**To Reproduce**
1. Create new note
2. Add `#1.1.1.1` (or any other IP address) tag to the new note
3. Tag `1.1.1.1` is not displayed in sidebar

**Expected behavior**
Tag `1.1.1.1` (or any other IP address) shall be displayed at sidebar

**Actual behavior**
IP address as a tag is not displayed in sidebar

**Workaround**
no workaround found

**Supporting Files**
not applicable

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.13.6
 - FSNotes version: 4.3.3 (390)

**Additional context**
in case of IP address added as a sub-tag, e.d. `#test/10.1.2.3`, than only first octet (`10`) appears in sidebar

**Comment by glushchenko** [comment]
Fixed, thanks.

**Comment by glushchenko** [comment]
Please check https://github.com/glushchenko/fsnotes/releases/download/4.4.0beta3/FSNotes_4.4.0b3.zip

**Comment by DEC32768** [comment]
> Please check https://github.com/glushchenko/fsnotes/releases/download/4.4.0beta3/FSNotes_4.4.0b3.zip

works correctly on Version 4.4.0 (395)
