### ISSUE TITLE
[ISSUE] problem with autocompletion

### ISSUE THREAD

**Issue by thomaslissajoux** [glushchenko/fsnotes#922]
I've got a problem with autocompletion
When I open the brackets I can see a large list of Notes to autoco;plete from
![Screenshot 2020-06-15 at 11 53 33](https://user-images.githubusercontent.com/1734825/84652125-69a2cf00-af0b-11ea-8f43-9ff93a37d914.jpg)
So say I want to link to a note starting with "C"
but then I **cannot** see most of them
![Screenshot 2020-06-15 at 13 21 02](https://user-images.githubusercontent.com/1734825/84652238-9a830400-af0b-11ea-9018-47705fc2ae5b.jpg)
It seems like it's only autocompleting amongst **Uppercase** !

Is there anything I'm missing or any way to fix that on my side ?

_Originally posted by @thomaslissajoux in https://github.com/glushchenko/fsnotes/issues/512#issuecomment-644070903_

**Comment by gingerbeardman** [comment]
Thanks for posting this as it's own issue.

**Comment by glushchenko** [comment]
I can not reproduce it. Can you provide file examples?

**Comment by glushchenko** [comment]
On my side autocomplete is case insensitive. Please open issue if i am wrong.
