### ISSUE TITLE
Folders inside of folders

### ISSUE THREAD

**Issue by TaylorJonesTRT** [glushchenko/fsnotes#925]
**Describe your feature request**
A way to create a sub-folder inside of an already created Folder. Programming Projects > Python/Switft/JS/etc.

**Comment by gingerbeardman** [comment]
Duplicate. I also really want this.

See:
#188 (April 2018) my issue
#343 (August 2018)
#637 (June 2019)
#904 (May 2020)

**Comment by glushchenko** [comment]
Implemented
