### ISSUE TITLE
Tags list visual glitch

### ISSUE THREAD

**Issue by sibob** [glushchenko/fsnotes#926]
**Describe the bug**

This happens whilst editing hashtags - if you remove a hashtag, the hashtag list becomes a visual mess with the lines 'bunched up'

**To Reproduce**

1. Remove all instances of a hashtag, with the sidebar shown

**Expected behavior**

The tag you've removed disappears, but the other tags still display correctly

**Actual behavior**

The tags merge into a visual mess

**Workaround**

Quitting the app and restarting
Switching between full screen and windowed

**Supporting Files**

<img width="164" alt="Screenshot 2020-06-23 at 12 54 58" src="https://user-images.githubusercontent.com/23299125/85432696-56b67d00-b551-11ea-93be-1444ade41a53.png">

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.15.5
 - FSNotes version: 4.3.3 (390)

**Comment by glushchenko** [comment]
Fixed in 4.9.0
