### ISSUE TITLE
Sync using webdav, ssh or ftp

### ISSUE THREAD

**Issue by egalitarian** [glushchenko/fsnotes#933]
**Describe your feature request**
Syncing notes using webdav, ssh or ftp on iOS would enable the users to sync with their own storage and do more cool stuff like for example use custom web UI for accessing the notes or even use a custom Linux or Windows client for the same notes. In addition it will make the app more open and not dependent on third party storage.

**Additional context**
It obviously concerns iOS more but having the feature also on macOS would be better.

**Comment by glushchenko** [comment]
No

**Comment by egalitarian** [comment]
Can you please elaborate why? Thanks

**Comment by glushchenko** [comment]
I do not see the technical feasibility for proper synchronization. No way to get diffs and fast sync it.

**Comment by egalitarian** [comment]
While diff-ing might be harder syncing by modified time still should be possible. A little bit like it's done in Joplin. The freedom gained from third party storage is well worth in my opinion and will be a big plus for all not trusting their data to corporations.
