### ISSUE TITLE
FSNotes 4.4.0 - Left sidebar gets non-functional after deleting a tag

### ISSUE THREAD

**Issue by trurl** [glushchenko/fsnotes#936]
**Describe the bug**
After deleting an inline tag from a note while prior having selected that note using a tag, the left sidebar containg folders and tags, gets unresponsive/non-functional

**To Reproduce**
1. Create a new note
2. enter an inline tag, e.g. '#foo123'
3. Wait for that tag to appear in the side panel
4. Select this tag in the side panel
5. open the new note via the note list now showing the newly created note
6. delete the inline tag

**Expected behavior**
I can click on another tag or a folder and the note list gets updated

**Actual behavior**
I can click on any item in the side panel, the note list does not get updated reflecting my new selection. The side panel is non-functional. 

**Workaround**
Restart FSNotes

**Supporting Files**
-

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.5
 - FSNotes version: 4.4.0 (394)

**Additional context**
-

**Comment by glushchenko** [comment]
Please check https://github.com/glushchenko/fsnotes/releases/download/4.4.0beta3/FSNotes_4.4.0b3.zip

**Comment by trurl** [comment]
This seems to be resolved with 4.4.0beta3. Thanks a bunch!
