### ISSUE TITLE
To add an option to hidden some of subfolder

### ISSUE THREAD

**Issue by JimmyLv** [glushchenko/fsnotes#937]
**Describe your feature request**
Could you please help to add an option to hidden some of subfolder, just like `/i` image folder? because something I will create other subfolder (e.g. `/05`, `/p`)  but don't want to view them.

![image](https://user-images.githubusercontent.com/4997466/86156390-755fd980-bb38-11ea-950c-23db88e0a632.png)

maybe an option `Not visibility`
![image](https://user-images.githubusercontent.com/4997466/86156520-aa6c2c00-bb38-11ea-8b0d-14b0912797a8.png)

**Additional context**
It's better to add on both macOS or iOS.

**Comment by glushchenko** [comment]
“i” folders hidden by default.

**Comment by JimmyLv** [comment]
@glushchenko yep, actually I want to hidden other folders that have same functionalities but not need to show, just like 'i' folder.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/wiki/Advanced-settings
