### ISSUE TITLE
Sort Order by Title Not Working

### ISSUE THREAD

**Issue by peavine** [glushchenko/fsnotes#938]
**Describe the bug**
I sort notes by Title in ascending order. Beginning with FSNotes 4.4.0, this setting is not remembered. 

**To Reproduce**
1) Start FSNotes 4.4.0
2) Set the sort order to Title in ascending order, which sorts the notes as expected.
3) Restart FSNotes, and the sort order is not by Title.`

**Expected behavior**
Sort notes by title when that option is selected.

**Actual behavior**
The notes are not sorted by title but may be sorted by modification date.

**Workaround**
None I know of.

**Supporting Files**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.15.5
 - FSNotes version: 4.4.0

**Additional context**
N/A

**Comment by glushchenko** [comment]
Thanks @peavine, glad to see you.

Workaround is settings by project:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/1089917/86316065-84c44d00-bc34-11ea-976c-c93f2d670f7e.png">

**Comment by peavine** [comment]
Thanks @glushchenko. Your suggestion works fine.

**Comment by peavine** [comment]
I installed FSNotes 4.5.1 and this issue is fixed. Many thanks.
