### ISSUE TITLE
Font size no longer adjustable in 4.0.0 on iOS

### ISSUE THREAD

**Issue by erikrose** [glushchenko/fsnotes#939]
#377 has regressed in 4.0.0 for iOS: all the text is now very large without any apparent means of adjusting it.

**Comment by erikrose** [comment]
Ah, I see that if I turn off Dynamic Type, a size picker appears. So that's fine, though the leading is still rather large; I wouldn't mind being able to adjust that.

**Comment by glushchenko** [comment]
Can i close it?
