### ISSUE TITLE
Titles are now always first line of note text

### ISSUE THREAD

**Issue by erikrose** [glushchenko/fsnotes#940]
**Describe the bug**
In the main list of notes, titles are not shown. Instead, the first line of each note's text is shown as the title.

**To Reproduce**
1. Show the sidebar.
2. Tap any category, like Notes.
3. See the wrong titles to the right.

**Expected behavior**
I expect to see the titles I gave to the notes.

**Actual behavior**
I see the first line of each note's text.

**Desktop (please complete the following information):**
 - OS: iOS
 - iOS version: 13.0.0
 - FSNotes version: 4.0.0

**Additional context**
I believe this is a regression in 4.0.0. I have tried both "Files Naming" settings, to no avail.

**Comment by glushchenko** [comment]
Yes, first line as title is default now. You can change behavior in project settings. 

Long tap on project in sidebar and select Settings - First line as title. Or click project name in navigation bar - Settings - First line as title.

**Comment by erikrose** [comment]
Ah, brilliant. Thank you!
