### ISSUE TITLE
Incremental search interferes with Asian language input

### ISSUE THREAD

**Issue by 1s4z** [glushchenko/fsnotes#941]
**Describe the bug**
Markdown and tag input will not work properly in languages that use IME for text input, such as Japanese. I think it's because the incremental search works when I key in the first consonant.

**To Reproduce**
1. Use a Japanese IME such as Google Japanese Input.
2. Type “sushi" in Japanese mode after "# ".

**Expected behavior**
"# 寿司" is entered.

**Actual behavior**
"# ｓ牛" is entered.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.5
 - FSNotes version: 4.4.0(395)

**Comment by tewe** [comment]
I cannot reproduce this in 4.6.1 on 10.14.6

**Comment by emdoe** [comment]
reproduce it in 4.6.2 on 10.15.7

**Comment by shuntaroy** [comment]
Reproduce it in 4.9.1 on 10.15.7

**Comment by shuntaroy** [comment]
This does not occur if "Scan inline tags" is turned off.

**Comment by glushchenko** [comment]
@shuntaroy @emdoe @tewe @1s4z  please try https://github.com/glushchenko/fsnotes/releases/tag/4.9.7b2 seems i fixed it.

**Comment by 1s4z** [comment]
It's working fine in 4.9.7b2

Thank you very much.
