### ISSUE TITLE
Latest IOS version not starting on iphone7+

### ISSUE THREAD

**Issue by strikeshield** [glushchenko/fsnotes#942]
**Describe the bug**
Downloaded the version, everytime I try to start it, it pops up and crashes immediately.

**To Reproduce**
Not sure

IOS latest version 13.5.1 on iphone 7 plus

**Comment by glushchenko** [comment]
Please attach crash report here. And try to delete and install app again.

**Comment by strikeshield** [comment]
Chris Laf
________________________________

**Comment by glushchenko** [comment]
Chris, I am tried it in Simulator, nothing happened. Crash report still needed.

**Comment by jobsch** [comment]
I have the same problem on my iPhone XR. For some reason it has stopped producing crash-reports, but this is the last one I got:

`
{"app_name":"FSNotes iOS","timestamp":"2020-07-06 03:50:03.00 +0200","app_version":"4.0.1","slice_uuid":"redacted","adam_id":"redacted","build_version":"192","bundleID":"co.fluder.mobile.FSNotes-iOS","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 13.5.1 (17F80)","incident_id":"9C6F328C-5D3D-49BD-919D-CBFDF8909AB8","name":"FSNotes iOS"}
{
  "uptime" : 1500,
  "procLaunch" : "2020-07-06 03:50:02.0111 +0200",
  "procRole" : "Foreground",
  "exception" : {
    "type" : "EXC_BREAKPOINT",
    "signal" : "SIGTRAP",
    "codes" : "0x0000000000000001, 0x00000001048cf2f0"
  },
  "userID" : redacted,
  "modelCode" : "iPhone11,8",
  "coalitionID" : 471,
  "osVersion" : {
    "train" : "iPhone OS 13.5.1",
    "build" : "17F80",
    "releaseType" : "User"
  },
  "captureTime" : "2020-07-06 03:50:02.1156 +0200",
  "incident" : "9C6F328C-5D3D-49BD-919D-CBFDF8909AB8",
  "pid" : 344,
  "cpuType" : "ARM-64",
  "procName" : "FSNotes iOS",
  "procPath" : "\/Volumes\/VOLUME\/*\/FSNotes iOS.app\/FSNotes iOS",
  "bundleInfo" : {"CFBundleShortVersionString":"4.0.1","CFBundleVersion":"192","CFBundleIdentifier":"co.fluder.mobile.FSNotes-iOS","DTAppStoreToolsBuild":"11E608a"},
  "storeInfo" : {"storeCohortMetadata":"7|date=1593615600000&sf=143443&pgtp=Software&pgid=1346501102&prpg=Software_1346501102&ctxt=Today","itemID":"1346501102","deviceIdentifierForVendor":"redacted","applicationVariant":"1:iPhone11,8:13","applicationType":"User"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "co.fluder.mobile.FSNotes-iOS",
  "crashReporterKey" : "redacted",
  "basebandVersion" : "2.06.00",
  "is_corpse" : 1,
  "termination" : {"reason":"Namespace SIGNAL, Code 0x5","signal":"Trace\/BPT trap: 5","byProc":"exc handler","code":5,"namespace":"SIGNAL","byPid":344,"flags":0},
  "threads" : [{"triggered":true,"id":18107,"queue":"com.apple.main-thread","frames":[[0,1127152],[0,913320],[0,904700],[0,904868],[1,4180652],[1,4200032],[1,4201036],[0,616928],[0,610908],[0,609408],[1,4180652],[1,4200032],[1,4201036],[1,12428540],[1,12442136],[1,12441788],[1,12442520],[1,4199616],[1,4201036],[1,11174500],[1,11172192],[1,11176176],[1,11246404],[1,10907656],[1,10932580],[1,1953852],[1,6983016],[1,1956720],[1,1955228],[1,1956236],[1,1954324],[1,1972528],[1,6059524],[1,7088652],[1,1971820],[1,7088372],[1,1971396],[1,293796],[1,288420],[1,293076],[1,10925052],[1,6217224],[2,53244],[2,210336],[2,97980],[2,209460],[3,13116],[3,24788],[2,366276],[2,365424],[2,366812],[4,711412],[4,711240],[4,709016],[4,687928],[4,686324],[5,13828],[1,10941272],[0,21436],[6,4828]]},{"id":18122,"frames":[[7,39360]]},{"id":18123,"frames":[[7,39360]]},{"id":18124,"frames":[[7,39360]]},{"id":18125,"frames":[[7,39360]]},{"id":18126,"name":"com.apple.uikit.eventfetch-thread","frames":[[8,18308],[8,15272],[4,709396],[4,688288],[4,686324],[9,31512],[9,31216],[1,11622464],[9,1317904],[7,6396],[7,39380]]},{"id":18128,"queue":"com.apple.CoreText.InitShapingGlyphs","frames":[[10,646796],[10,646796],[10,715804],[10,653576],[10,653452],[10,714012],[10,653012],[10,652884],[10,699736],[10,325104],[10,306024],[3,13116],[3,39004],[3,41616],[3,80168],[7,14100],[7,39368]]},{"id":18129,"frames":[[7,39360]]},{"id":18130,"frames":[[7,39360]]}],
  "threadState" : {
  "x" : [
    10780889792,
    6096685464,
    0,
    0,
    25308,
    6096680528,
    7718531120,
    0,
    0,
    0,
    2,
    8589934594,
    8,
    6189124556479,
    3187783680,
    55,
    6577163916,
    7495980292,
    0,
    0,
    6096685584,
    4404473856,
    6096685584,
    10776496528,
    7885711080,
    0,
    0,
    7836647424,
    7589986304
  ],
  "flavor" : "ARM_THREAD_STATE64",
  "lr" : 8948551858642545780,
  "cpsr" : 1610612736,
  "fp" : 6096685568,
  "sp" : 6096685360,
  "esr" : 4060086273,
  "esr_description" : "(Breakpoint) brk 1",
  "pc" : 4371313392
},
  "usedImages" : [
  [
    "3f3cd137-2e43-34b3-bb05-b2f38d626e01",
    4370186240,
    "P"
  ],
  [
    "32d99abd-e47b-38d8-bbd1-68aea293a9a6",
    6637772800,
    "P"
  ],
  [
    "0a1b636b-96dc-3601-bf31-0bdae5650bcb",
    6666592256,
    "P"
  ],
  [
    "cafeee86-4c94-3ac9-8853-bfe11f70c0f4",
    6576705536,
    "P"
  ],
  [
    "af42303f-57b6-3c11-8f18-8e80abf7d886",
    6579003392,
    "P"
  ],
  [
    "fdd62141-ead1-3c35-9f51-9d1f1343f394",
    6751735808,
    "P"
  ],
  [
    "e5e56a85-e4d6-332e-9f32-fed4b986afe0",
    6578094080,
    "P"
  ],
  [
    "4cf76cd7-dc5b-37cf-83d7-46153d0d3962",
    6577127424,
    "P"
  ],
  [
    "42bdcd41-02a6-3529-a271-0e6402154a44",
    6577897472,
    "P"
  ],
  [
    "19fab59f-6527-3245-85bb-905fd4255cde",
    6583103488,
    "P"
  ],
  [
    "d0d4f156-2811-3595-a70b-67f51dfdb363",
    6593454080,
    "P"
  ]
],
  "legacyInfo" : {
  "imageExtraInfo" : [
    {
      "size" : 1343488,
      "arch" : "arm64",
      "path" : "\/Volumes\/VOLUME\/*\/FSNotes iOS.app\/FSNotes iOS",
      "name" : "FSNotes iOS"
    },
    {
      "size" : 18325504,
      "arch" : "arm64e",
      "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
      "name" : "UIKitCore"
    },
    {
      "size" : 487424,
      "arch" : "arm64e",
      "path" : "\/System\/Library\/PrivateFrameworks\/FrontBoardServices.framework\/FrontBoardServices",
      "name" : "FrontBoardServices"
    },
    {
      "size" : 253952,
      "arch" : "arm64e",
      "path" : "\/usr\/lib\/system\/libdispatch.dylib",
      "name" : "libdispatch.dylib"
    },
    {
      "size" : 3661824,
      "arch" : "arm64e",
      "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
      "name" : "CoreFoundation"
    },
    {
      "size" : 36864,
      "arch" : "arm64e",
      "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
      "name" : "GraphicsServices"
    },
    {
      "size" : 217088,
      "arch" : "arm64e",
      "path" : "\/usr\/lib\/system\/libdyld.dylib",
      "name" : "libdyld.dylib"
    },
    {
      "size" : 45056,
      "arch" : "arm64e",
      "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
      "name" : "libsystem_pthread.dylib"
    },
    {
      "size" : 196608,
      "arch" : "arm64e",
      "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
      "name" : "libsystem_kernel.dylib"
    },
    {
      "size" : 2928640,
      "arch" : "arm64e",
      "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
      "name" : "Foundation"
    },
    {
      "size" : 1679360,
      "arch" : "arm64e",
      "path" : "\/System\/Library\/Frameworks\/CoreText.framework\/CoreText",
      "name" : "CoreText"
    }
  ],
  "threadTriggered" : {
    "index" : 0,
    "queue" : "com.apple.main-thread"
  }
}
}
`

**Comment by glushchenko** [comment]
@jobsch WTF?

**Comment by jobsch** [comment]
@glushchenko Sorry, I propably did things the wrong way. I now realized that there is another way to format code here (which is not suggested by the interface as far as I can see).
Also I removed some information from the report where I thought it is not necessary and should not be exposed to the public (user id).
If there is something else wrong I am sorry but maybe you can let me know, I am new to github and iOS.
