### ISSUE TITLE
Reverts from plain text to markdown every time

### ISSUE THREAD

**Issue by bellelopez** [glushchenko/fsnotes#943]
Every time I close and open fsnotes, it reverts from plain text to markdown in the preferences menu.
More importantly, even when I have selected plain text, it still saves it as .md in my storage folder. I am not sure if I’m missing something, but can’t work it out. 

**To Reproduce**
1. Preferences.
2. Format > Plain text (I do not choose the text bundle)
3. Write note > Reveal in finder > always saves as .md 

**Expected behavior**
I want it to save as .txt files and not revert to markdown when I open and close the program. 

version 4.4.0 (397) for mac OS. 

Thanks.

**Comment by glushchenko** [comment]
Thanks @bellelopez, finally fixed.

**Comment by glushchenko** [comment]
Please try https://github.com/glushchenko/fsnotes/releases/tag/4.5.1

**Comment by peavine** [comment]
I had also experienced this issue, and it is fixed for me in FSNotes 4.5.1. Thanks.

**Comment by greendog99** [comment]
Although 4.5.1 fixed the issue where plain text preference was not being honored, it still formats plain .txt files as markdown while I'm typing. Is that expected? I'd expect plain text files to be treated as plain text, and not formatted at all. Thanks!

<img width="951" alt="ss-20200725-104452" src="https://user-images.githubusercontent.com/30274/88459540-2ae62a00-ce64-11ea-847f-b4a0313e2249.png">

**Comment by glushchenko** [comment]
Sorry, @greendog99 but this feature removed. Txt and markdown by default highlighted.
