### ISSUE TITLE
"Use first line as title" setting not correctly being remembered on iOS

### ISSUE THREAD

**Issue by bjerkeweb** [glushchenko/fsnotes#944]
**Describe the bug**
Sometime within the past few weeks, the iOS version stopped remembering project view settings and reverts to having the "use first line as title" toggle on, no matter how many times I switch it to off

**To Reproduce**
1. Tap inbox dropdown in main notes list view
2. Tap "view settings"
3. Toggle "use first line as title" preference to off
4. Close app and come back to it later (not sure exactly how long it takes to reset, but I've been seeing the issue multiple times a day, every day for weeks)

**Expected behavior**
To maintain settings between relaunches

**Actual behavior**
Resets to off

version 4.0.1 b192 for iOS

**Comment by glushchenko** [comment]
Fixed, thank you for bug report.

**Comment by glushchenko** [comment]
@bjerkeweb, please try 4.0.2

**Comment by bjerkeweb** [comment]
👍
