### ISSUE TITLE
Edit mode spacing issues

### ISSUE THREAD

**Issue by kinngh** [glushchenko/fsnotes#945]
**Describe the bug**
Unintended spacing before text when in full screen.

**To Reproduce**
1. Turn app to full screen in edit mode
OR
1. Resize window from the right side

**Expected behavior**
Expected text to completely take up space

**Actual behavior**
Text has a good amount of unintended spacing that cannot be removed in edit mode, but is completely fine in preview mode

**Workaround**
None identified

**Supporting Files**

<img width="1680" alt="Screenshot 2020-07-09 at 7 04 04 PM" src="https://user-images.githubusercontent.com/773555/87046712-22141800-c217-11ea-9454-fb6917e4697a.png">

<img width="1680" alt="Screenshot 2020-07-09 at 7 04 08 PM" src="https://user-images.githubusercontent.com/773555/87046733-28a28f80-c217-11ea-969b-202362b6fb96.png">

<img width="1309" alt="Screenshot 2020-07-09 at 7 05 36 PM" src="https://user-images.githubusercontent.com/773555/87046751-2f310700-c217-11ea-8132-1249b843b071.png">

**Desktop (please complete the following information):**
- macOS 10.5.5
- fsnotes 4.4.0

**Comment by gingerbeardman** [comment]
Preferences > Editor > Margin Size
