### ISSUE TITLE
Trailing punctuation is part of inline tag

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#946]
**Describe the bug**
Trailing punctuation is part of inline tags:

![Screenshot 2020-07-12 at 18 12 02](https://user-images.githubusercontent.com/30050534/87251415-d60de100-c46b-11ea-878a-e956ec9d2efa.png)

**Expected behavior**
Inline tags should not contain any punctuation character like `!?;:.,` at the end of tag. E.g., in the example above "Like this: #hello." the tag expression should be "#hello" and not "#hello."

**Actual behavior**
Trailing punctuation is part of inline tags.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.4.0

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/4.5.1
