### ISSUE TITLE
Wrong fontification of bare links

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#948]
**Describe the bug**
Trailing punctuation is part of bare links:

![Screenshot 2020-07-14 at 15 40 17](https://user-images.githubusercontent.com/30050534/87435824-860a5800-c5ec-11ea-9475-29d8b1515ec0.png)

**Expected behavior**
Bare links should not contain any punctuation character like `!?;:.,` at the end of link. E.g., in the example above the link should be `https://highlights.org` and not `https://highlights.org,`.

**Actual behavior**
Trailing punctuation is part of bare links.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.4.0

**Comment by glushchenko** [comment]
Fixed, thanks.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/4.5.1
