### ISSUE TITLE
Wrong fontification of backticks as part of inline code

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#949]
**Describe the bug**
Backticks as part of inline code are fontified as code delimiters:

![Screenshot 2020-07-14 at 15 38 53](https://user-images.githubusercontent.com/30050534/87436358-3aa47980-c5ed-11ea-8012-9bdd39bb3297.png)
**Expected behavior**
Being a part of inline code backticks should not be fontified as code delimites.

**Actual behavior**
Backticks as part of inline code are fontified as code delimiters.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.4.0

**Comment by glushchenko** [comment]
You should not use multiple backticks, documentation fixed.
