### ISSUE TITLE
No such module 'Marklight' in Storage.swift

### ISSUE THREAD

**Issue by anagram** [glushchenko/fsnotes#95]
Getting build error: "No such module 'Marklight' Storage.swift" -  I do not see Marklight in Podfile as downloaded, yet in repo  Podfile.lock, there is an entry. Any help appreciated

**Comment by glushchenko** [comment]
Just delete marklight from podfile, it is not used anymore.

**Comment by anagram** [comment]
Then also delete import statement from Storage.swift?

**Comment by glushchenko** [comment]
Yes https://github.com/glushchenko/fsnotes/commit/d971a2c4445c05c11594e02f6c02bbc846863ee9

**Comment by anagram** [comment]
cool! builds and runs now
