### ISSUE TITLE
There is something wrong with last release.

### ISSUE THREAD

**Issue by yene** [glushchenko/fsnotes#951]
<img width="572" alt="shot 2020-07-19 at 18 59 52" src="https://user-images.githubusercontent.com/63942/87880464-2815b000-c9f2-11ea-9430-c2dcfca5ba74.png">

I think the filenames have special characters which cause problems.

**Comment by glushchenko** [comment]
Deleted, will be fixed a little bit later. Thanks.

**Comment by glushchenko** [comment]
Re released in 4.5.1 https://github.com/glushchenko/fsnotes/releases/tag/4.5.1

**Comment by gingerbeardman** [comment]
I also got this with Keka unarchiver, but they classed it as a bug because macOS Archive Utility extracted the FSNotes release just fine.
