### ISSUE TITLE
[iOS] Images are not inserting using editor toolbar

### ISSUE THREAD

**Issue by xapai** [glushchenko/fsnotes#952]
**Describe the bug**

On iOS I've tried to insert an image using a built-in editing toolbar. The one above text keyboard. File dialog appears I can select images.

After I've selected all the images to insert and clicked «Select», nothing happens. The image selecting dialog just closes without any images inserted into a document.

I've tried with different containers, e.g. none and «text bundle».

Images insert via the Mac app are displaying correctly. Syncing via iCloud Drive.

Besides images not showing up after image toolbar image selecting dialog, everything seems to work fine

**To Reproduce**
1. Go to any note
2. Start editing
3. Tap on the icon that looks like an image selecting the icon
4. Select one or a few images
5. Click «Select» after selecting one or few images being selected
6. Experience nothing

**Expected behavior**

The app should insert images from Camera Roll into a note

**Actual behavior**
Images are not inserted into a note

**Workaround**
Don't use image inserting from iOS and use it on Mac OS. But I need that functionality and that was a selling point for me deciding whether should I or shouldn't get an app from a store.

**Supporting Files**
I think screenshots will do nothing. Just an image selecting dialog. After supposedly, finishing tap on a «Select» image should be displayed, but they are not.

**Desktop (please complete the following information):**
 - OS: iOS
 - OS version: 12.4.4
 - FSNotes version: 4.0.2 build 192
- Hardware: iPhone 5s (yes, I'm still using it, it is officially supported anyway)

**Additional context**
It'll be cool to fix this issue. I hope it doesn't link to old hardware I'm using (which shouldn't be a case). Updating to 13 is not an answer for me either.

Thanks. Overall, great app! I'm digging searching and tag system on iOS. It's neat.

**Comment by glushchenko** [comment]
I will try to reproduce it a little bit later.

**Comment by glushchenko** [comment]
Thanks @xapai, fixed.

**Comment by xapai** [comment]
Thank you. You've got my 5-star review.

Keep it up with a great work! Have a great day!

**Comment by glushchenko** [comment]
Thanks 👍 You are welcome!
