### ISSUE TITLE
Moving documents on iOS not updating Mac.app

### ISSUE THREAD

**Issue by tiptronic** [glushchenko/fsnotes#954]
**Describe the bug**
When I move documents in the iOS.app (e.g. from the initial 'Welcome' to another directory (previously created on the Mac), I immediately see the updated file-structure on iCloud (even Visual Studio Code updates it's tree), but FSNotes 4.4.0 (397) does not update the documents. Quitting/re-launching the app fixes the problem.

**To Reproduce**
1. Go to iOS.app
2. Drag some documents (I dragged multiple at once) from one folder to another
3. Go to Mac.app
4. Documents are not in the new folder

**Expected behavior**
Documents should be in new folder

**Actual behavior**
Documents are moved (you can see them in iCloud in the new folder), but not in FSNotes.app

**Workaround**
re-starting the Mac.app fixes the problem

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6 (19G73) and iOS 13.5.1
 - FSNotes version: 4.4.0 (397)

**Comment by glushchenko** [comment]
Sorry for delayed response, fixed here https://github.com/glushchenko/fsnotes/releases/download/4.5.4/FSNotes_4.5.4.zip

**Comment by tiptronic** [comment]
thanks for the fix!!
