### ISSUE TITLE
Creating a new note in the "Notes" section of iOS app does not save the note to iCloud

### ISSUE THREAD

**Issue by andybyte** [glushchenko/fsnotes#956]
**Describe the bug**
Using the iOS app (version 4.0.2 build 192), when I select the "Notes" section in the sidebar and create a new note, I notice that it does not save the note to the iCloud FSNotes folder (and therefore does not sync to other devices). But if I create the note in the "Inbox" sidebar, it works as expected. Also, I have the "Auto rename by title" on and it doesn't rename the note in this case. I tested it with UUID selected and the bug of now showing in iCloud still happens.

Further testing, I found that I know that note is saved to iCloud when I see the *Auto rename by title* update the "v" symbol in the top bar of the note. 

*I found that it works fine in Inbox, Archive, Trash. It DOES NOT work when I create notes in Notes, Todo.*

**To Reproduce**
1. Go to 'Notes'
2. Click on '+' button to create note
3. Check Files app for FSNotes folder in iCloud
4. File does not appear, but exists in the FSNotes app.

**Expected behavior**
Creating the note in the "Notes" section would save the note to the FSNotes iCloud folder at the top level with other "Inbox" notes.

**Actual behavior**
After creating the note on iOS in the "Notes" section, it appears in the app but will not appear in the iCloud folder FSNotes uses.

**Workaround**
Being mindful to create new notes in the "Inbox". Which is a problem, because I am mindless most of the time.

**Supporting Files**
[Link to screen recording showing the bug](https://pitt.box.com/s/niyv8o4rawcehhi3iwdoizao8uq6r8f1).

**Desktop (please complete the following information):**
 - OS: iOS
 - OS version: 13.5.1
 - FSNotes version: 4.0.2 192

**Additional context**
It seems to work on normal folders so it is just the "Notes" sidebar that has the issue.

**Comment by glushchenko** [comment]
Thanks @andybyte, fixed.
