### ISSUE TITLE
Incorrect keyboard mappings in alternative keyboard layouts

### ISSUE THREAD

**Issue by GeoJunkie** [glushchenko/fsnotes#958]
**Describe the bug**
Some of the keyboard shortcuts on alternative keyboard shortcuts are mapped to the physical positions of keys instead of the character itself, causing the documented shortcuts to be confusing and, in at least one case (creating a new note), making them inaccessible.

**To Reproduce**
1. Set keyboard layout to Colemak.
2. Open notes list.
3. Press Command-N to open a new note (where J is on a QWERTY keyboard)
4. Try pressing Command-K (where N is on a QWERTY keyboard)
5. Highlight some text and press Command-E (where K is on a QWERTY keyboard)
6. Try pressing Command-F (where E is on a QWERTY keyboard)

**Expected behavior**
* Command-N should open a new note
* Command-K should move to the previous note
* Command-E should use the selected text in Find
* Command-F should open find

**Actual behavior**
* Command-N moves to the next note
* Command-K does nothing
* Command-E moves to the previous note
* Command-F opens find

You can try with nearly any keyboard shortcut. Some (like Command-F) work based on the letter being pressed, some (like Command-N and Command-E) work based on keyboard position, and some (like Command-K) do neither.

Ideally, this would be mapped to the actual Colemak/Dvorak/whatever key, but if not, it should at least have a consistent pattern.

**Workaround**
You can figure out the keyboard shortcuts for most of them, and for the ones that have no shortcut you can use the menus. It slows things down, though, and hampers usability.

**Supporting Files**

Screencast of the above, with the Keyboard Viewer displayed:

![](https://d.pr/i/jnjiHK+)
Image Link: https://d.pr/i/jnjiHK

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.15.6 (19G73)
 - FSNotes version: 4.0.25 (362)

**Comment by glushchenko** [comment]
Finally implemented https://github.com/glushchenko/fsnotes/releases/download/4.9.0b444/FSNotes_4.9.0.zip
