### ISSUE TITLE
App Crash When Escape Key is Pressed

### ISSUE THREAD

**Issue by brandon-carag** [glushchenko/fsnotes#961]
**Describe the bug**
If you press the escape key while a tag is highlighted in the left sidebar, FS Notes immediately crashes and the application unexpectedly quits.

**To Reproduce**
1. Ensure "Scan inline tags" is enabled
2. Add a note and an inline tag (eg #foo/bar/baz).  It seems to be important to have at least one tag within a tag.
3. Use the sidebar to uncollapse the foo and bar tag
3. Highlight one of the tags in the sidebar
4. Press the escape key

**Expected behavior**
The tag highlighted in the sidebar will become deselected (and the search results will no longer be scoped to the highlighted tag)

**Actual behavior**
The application unexpectedly quits.

**Workaround**
None

**Supporting Files**
See the following stack trace:
```
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSOutlineView', reason: 'NSOutlineView error removing child indexes <NSMutableIndexSet: 0x6000008ed800>[number of indexes: 4 (in 2 ranges), indexes: (9 11-13)] in parent 0x0 (which has 13 children).'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff53e5aa7d __exceptionPreprocess + 256
1   libobjc.A.dylib                     0x00007fff7e550a17 objc_exception_throw + 48
2   AppKit                              0x00007fff51aae92b -[NSOutlineView _validateParentRowEntry:reason:indexes:] + 0
3   AppKit                              0x00007fff51aaee3e -[NSOutlineView _removeItemsAtIndexes:inParentRowEntry:withAnimation:] + 129
4   AppKit                              0x00007fff515e93b7 -[NSTableView _doUpdatedWorkWithHandler:] + 74
5   AppKit                              0x00007fff51ab09fd -[NSOutlineView removeItemsAtIndexes:inParent:withAnimation:] + 252
6   FSNotes                             0x000000010f1346b7 FSNotes + 923319
7   FSNotes                             0x000000010f133300 FSNotes + 918272
8   FSNotes                             0x000000010f134eb7 FSNotes + 925367
9   FSNotes                             0x000000010f0d1c92 FSNotes + 519314
10  FSNotes                             0x000000010f05e7f9 FSNotes + 47097
```

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.5.5

**Additional context**
Happy to email full stack trace if helpful.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.5.6/FSNotes_4.5.6.zip

**Comment by brandon-carag** [comment]
Great--thank you!
