### ISSUE TITLE
Default Storage options in iOS

### ISSUE THREAD

**Issue by jncomas** [glushchenko/fsnotes#962]
**Describe your feature request**
FSNotes on macOS allows changing the location of default storage; FSNotes on iOS appears not to provide that option. So, if I change the default-storage location using FSNotes on macOS, I don't have access to my notes using FSNotes on my iOS devices. My request is to enable FSNotes on iOS recognize the new location of default storage that I set on my MacBook. Thanks!

**Additional context**
iOS

**Comment by glushchenko** [comment]
iOS API not exists for this yet, so no.
