### ISSUE TITLE
Auto-correct option and bar for iOS

### ISSUE THREAD

**Issue by andybyte** [glushchenko/fsnotes#963]
**Describe your feature request**
iOS has an auto-correct system so that when I am typing on the small keyboard it will suggest or make corrections. Of course this sometimes backfires but it's gotten pretty good to correct *most* of my mistypes. In similar apps like 1Writer they keep the suggestion bar between the keyboard and the "button bar" with markdown characters and whatnot. 

I noticed in FSNotes iOS auto-correct doesn't happen and the suggestion bar is gone. So currently when I write notes in FSNotes there are so many typos because I've gotten used to auto-correct. It would be great if the auto-correct system and bar could be implemented.

**Additional context**
Add any other related information here. macOS or iOS? iOS 4.03 build 193

**Comment by glushchenko** [comment]
Added in 4.1.0, will be available soon on the App Store 😎
