### ISSUE TITLE
Image button on toolbar crashes FSNotes

### ISSUE THREAD

**Issue by DownAndCross** [glushchenko/fsnotes#966]
**Describe the bug**
FSNotes on iPad (iPhone is okay) - Image button on toolbar crashes FSNotes.
Tested on iPad Air 2 and iPad Pro 12.9 (2017) latest updated iPadOS and FSNotes

**To Reproduce**
1. Go to 'Any note in edit mode'
2. Click on 'Insert image toolbar icon'
3. FSNotes crashes
4.  
**Expected behavior**
Select image dialog appears.

**Actual behavior**

FSNotes crashes

**Workaround**
None

**Supporting Files**
If applicable, add screenshots or files to help explain your problem.

**Desktop (please complete the following information):**
 - OS: macOS or iOS
 - OS version: 10.14.6
 - FSNotes version: 3.8.2

**Additional context**

**Comment by glushchenko** [comment]
3.8.2 is outdated. Have you tried updating the app?

**Comment by DownAndCross** [comment]
Hi, I updated the app this morning. Took the screenshot from the app and tested again and the same thing happens. No more updates available on the app store.
Hope this helps.
Ian

**Comment by glushchenko** [comment]
I still don’t know what version of OS you are using, and what version of the application too.

**Comment by DownAndCross** [comment]
Hi,
iPadOS 13.6
FSNotes 4.1.0 build 197



Ian

**Comment by glushchenko** [comment]
Thanks @DownAndCross, fixed and available in TestFlight.

**Comment by glushchenko** [comment]
4.1.1 on the AppStore now.
