### ISSUE TITLE
Sidebar scrolling is slow using external Bluetooth mouse

### ISSUE THREAD

**Issue by haircut** [glushchenko/fsnotes#967]
**Describe the bug**
I have a note storage location with 28 folders and 49 tags. When using the scroll wheel on my Logitech MX Master mouse, the sidebar does not scroll smoothly. It freezes for a few seconds, then jumps up or down. Scrolling the sidebar list is not fluid at all when using the scroll wheel.

When scrolling by clicking and holding the scroll bar, or when using the built-in trackpad, scrolling is smooth.

I know this may sound like an issue with the mouse, but FSNotes is the only app I've noticed this behavior. I wonder if there's a reason

**To Reproduce**
1. Use an external mouse; observed when using a Logitech MX Master Bluetooth mouse
2. Use the scroll wheel to scroll the sidebar listing of folders and tags

**Expected behavior**
I expect the sidebar to scroll as smoothly as when using the built-in trackpad.

**Actual behavior**
The scrolling stutters, freezes, and jumps around.

**Workaround**
None identified.

**Supporting Files**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.6
 - FSNotes version: 4.5.6

**Additional context**
- The "Smooth scrolling" feature of the mouse is disabled.
- In FSNotes 4.4.0 where this was originally observed, the scrolling was really bad consistently. After upgrading to 4.5.6 it is _slightly_ improved. After first launching the app it scrolls normally but quickly degrades.
- The 'note list' view scrolls normally in all circumstances with no stutter or delay.

**Comment by gingerbeardman** [comment]
I believe this is because it renders syntax/highlighting on the document as it comes into view.

**Comment by glushchenko** [comment]
Fixed here https://github.com/glushchenko/fsnotes/releases/download/4.9.0b444/FSNotes_4.9.0.zip

**Comment by haircut** [comment]
This is absolutely fixed in the latest update – thanks @glushchenko ! Everything is nice and smooth now.

What was the cause? Please don't feel obligated to respond – I'm just curious 😛

**Comment by glushchenko** [comment]
The reason is the old tagging system that tracked the mouse movement :)
