### ISSUE TITLE
Edit font changes only when caret moves over line

### ISSUE THREAD

**Issue by nirajd** [glushchenko/fsnotes#97]
I have inconsolata set as my editing font, but when I initially select a note, it shows in some preview version and only changes when I move the caret through the line, one at a time.

![out](https://user-images.githubusercontent.com/44583/35048635-a6187c60-fb6b-11e7-98ea-48933fd9e891.gif)

**Comment by glushchenko** [comment]
Notes caching need some time after start. Do you have many notes?

**Comment by nirajd** [comment]
No, less than 30. And the notes only change to edit view once I move the caret through, no matter how long FSNotes has been open for

**Comment by nirajd** [comment]
Also just noticed, this only occurs in notes saved as .md files. Notes that are saved as .txt behave appropriately

**Comment by glushchenko** [comment]
I think understand. After font change try restart app.
