### ISSUE TITLE
Apple pencil support

### ISSUE THREAD

**Issue by nammn** [glushchenko/fsnotes#971]
👋  having Apple pencil support would be great!

**Describe your feature request**
- basic apple pencil support like in bear
- more advanced pencil support like in OneNote and Apple Notes

**Comment by nonameplum** [comment]
I'm missing this feature the most.
Also, if the drawing could contain back-links that would be one of the best note-taking apps that support drawing with built-in back-links to build the second brain through handwritten notes.

**Comment by glushchenko** [comment]
You can make a pull request, but there's no point in expecting it from me.
