### ISSUE TITLE
FSNotes selecting searched note too quickly

### ISSUE THREAD

**Issue by volt4ire** [glushchenko/fsnotes#973]
**Describe the bug**
With the "Focus in editor when selecting note" setting enabled, when I enter the search bar to type the name of a note to search for, FSNotes is too quick to select a note and shifts the focus into note editing mode before I have had time to finish typing my search string. Could you please increase the amount of time FSNotes waits after finishing typing before shifting focus to the note editor, or add a setting for increasing the amount time waited? Thanks!!

**Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 10.15.6
 - FSNotes version: 4.5.6

**Comment by glushchenko** [comment]
Focus disabled by default when you type text in search bar. Dont know how reproduce it.

**Comment by gingerbeardman** [comment]
@volt4ire could you please post a video of this happening? I have had it in the past, but cannot currently reproduce reliably.
