### ISSUE TITLE
Support Native Mac OS Text Expansion

### ISSUE THREAD

**Issue by brandon-carag** [glushchenko/fsnotes#974]
**Describe your feature request**
OS X natively supports text expansion.  For example, it's commonplace to have to type in your email address in several different apps.  If your email address was `john@example.com`, you can set up a text expansion shortcut so you only need to type `j@ex` followed by the enter key and j@ex will auto-expand to john@example.com.

*System Preferences > Keyboard > 'Text' tab > + Icon*

![Screen Shot 2020-08-27 at 10 53 38 PM](https://user-images.githubusercontent.com/3423367/91526443-7a32d680-e8b8-11ea-87a5-da760de596ac.png)

This currently works in apps like Chrome, Stickies, etc.

There are other utilities that provide this kind of functionality (e.g. TextExpander, etc.), but supporting the native Mac functionality would give all FS Notes users immediate access to this kind of productivity functionality.

**Additional context**
Mac OS

**Comment by tewe** [comment]
It already works for me with 4.6.1 on 10.14.6

<img width="1269" alt="CleanShot 2020-09-11 at 13 33 27@2x" src="https://user-images.githubusercontent.com/645412/92920983-8334b380-f433-11ea-823c-4f42bfd7f32f.png">

**Comment by glushchenko** [comment]
I did nothing ¯\_(ツ)_/¯

**Comment by gingerbeardman** [comment]
I can't get it to work.

**Comment by brandon-carag** [comment]
I'm on Mac OS Mojave for what it's worth.  Not sure if you guys are running Catalina...

**Comment by gingerbeardman** [comment]
I'm also on Mojave. Strange. 

I had the Text Replacement option unchecked. Now it's checked and it works

<img width="408" alt="Screen shot 2020-09-11 at 20 19 44" src="https://user-images.githubusercontent.com/49612/92964512-230e3380-f46c-11ea-8e2c-a71d04ef1f72.png">

**Comment by brandon-carag** [comment]
gingerbeardman's solution worked for me as well.  Closing this--thanks!
