### ISSUE TITLE
Caret not moving left after 4.6 update

### ISSUE THREAD

**Issue by samer** [glushchenko/fsnotes#976]
**Describe the bug**
When I press the Left Arrow button on my keyboard, the caret does not move left.

**To Reproduce**
1. Open FSNotes
2. Press `<--` key on your keyboard

**Expected behavior**
Caret should move left

**Actual behavior**
Caret does not move

**Workaround**
Downgraded to 4.5.6

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - FSNotes version: 4.6

**Comment by gingerbeardman** [comment]
Can confirm.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/tag/4.6.1

**Comment by gingerbeardman** [comment]
That fixes it for me.
