### ISSUE TITLE
Add a feature to sort folders in the sidebar

### ISSUE THREAD

**Issue by semiopat** [glushchenko/fsnotes#978]
**sort folders in the menubar**
As I use fsNotes more and more, I need a way to sort folders created in the menubar like I can sort notes: pin an important folder, sort folders by date (of creation, modification), other than just sort folders by alphabetical order as it is now.

**MacOS first, but iOS would be great to**

**Comment by gingerbeardman** [comment]
This could be done by manipulating the filesystem date of the folders, and then sorting just those by date (though still sorting the notes inside them by selected option)

**Comment by xor-gate** [comment]
I have a similar feature request for sorting folders on the sidebar. Currently it is simple sorted. But I have subfolders based on year and is sorted in a normal way and not using `natural sort`.

<img width="206" alt="Screenshot 2022-01-08 at 10 18 39" src="https://user-images.githubusercontent.com/1050166/148638934-93e4e8c3-07d6-4f90-90f6-54cb16272dc9.png">

See info about natsort <https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/> and <https://en.wikipedia.org/wiki/Natural_sort_order>

Its easy in swift to do natural sorting with [localizedStandardCompare](https://medium.com/macoclock/how-to-implement-natural-sorting-on-the-alphanumeric-array-in-swift-5b8f64173725) from the `Foundation` framework.

Thank you for this nice native application, it behaves much better than those crappy electron javascript apps.

**Comment by glushchenko** [comment]
Release available for download here https://github.com/glushchenko/fsnotes/releases/tag/6.0.0

I also ask you to vote on Prouct Hunt and Reddit, it will help in spreading:

https://www.producthunt.com/posts/fsnotes-6
https://www.reddit.com/r/macapps/comments/yh8156/fsnotes_v6_pro_notes_manager_for_macos/

Thanks!
