### ISSUE TITLE
URLs and inline italic font rendering

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#980]
**Describe the bug**

URLs containing underlines will render part of the URL as italic. Example:
`https://example.org/this_is_some_sample_url.png`

In this case FSNotes will draw `is` and `sample` in italic font.

**Expected behaviour:**

The markdown processing should ignore URLs.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.6
 - FSNotes version: 4.6.1

**Comment by glushchenko** [comment]
Thanks @relikd, fixed.
