### ISSUE TITLE
Crash when app in background

### ISSUE THREAD

**Issue by gingerbeardman** [glushchenko/fsnotes#981]
**Describe the bug**
App was just running in background.

**Supporting Files**

[FSNotes_2020-09-14-115121_matt.crash.zip](https://github.com/glushchenko/fsnotes/files/5217949/FSNotes_2020-09-14-115121_matt.crash.zip)

https://pastebin.com/raw/sQm0Pz55

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.6.2

**Comment by glushchenko** [comment]
pastebin.com - Forbidden (#403)

**Comment by gingerbeardman** [comment]
new pastebin link

**Comment by glushchenko** [comment]
Any ideas how to reproduce this?

**Comment by gingerbeardman** [comment]
No, sorry, feel free to close.

App was just in background and I was doing other things.

**Comment by buddax2** [comment]
Did it happen on a release build? If yes @glushchenko can try to desymbolicate the crash log with the dSYM file.

**Comment by gingerbeardman** [comment]
Yes, release build, crash log attached above.

**Comment by glushchenko** [comment]
I tried symbolicate but without success:

> atos -o FSNotes.app/Contents/MacOS/FSNotes -arch x86_64 -l 0x1052c0000 0x00000001052c3239
atos[32653]: respawning is disabled (because DYLD_ROOT_PATH or DT_NO_RESPAWN is set), but the analysis process does not match the SDK variant of the target process 0.
Analysis of malloc zones may fail.
0x0000000100003239 (in FSNotes) + 9

**Comment by glushchenko** [comment]
@buddax2 any help appreciated.
