### ISSUE TITLE
Difficult to edit email addresses

### ISSUE THREAD

**Issue by abhibeckert** [glushchenko/fsnotes#982]
**Describe the bug**
Clicking on an email address should move the insertion point so I can edit the address.

**To Reproduce**
1. Type "foo@bar.com"
2. Click on it

**Expected behavior**
The insertion point should move. As it does in virtually any other text editor, including ones that auto-detect links.

**Actual behavior**
An email compose window is opened.

**Workaround**
None that I'm aware of

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.6
 - FSNotes version: 4.6.2

**Additional context**
Users can right click on email addresses to open links. This is how links work in every other other text editor I've ever used.

**Comment by glushchenko** [comment]
In same way works tags, links and wikilinks. 

Does anyone other than the topic starter, supports the proposal?

**Comment by glushchenko** [comment]
What do you do more often, click on the link or edit it?

**Comment by gingerbeardman** [comment]
Workaround is to click outside the link and use cursor keys to move insertion point.

I like the ability to click links without going into preview mode.
