### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by wyaqoob** [glushchenko/fsnotes#983]
**Describe the bug**
New notes are not automatically sorted by Title even when Sort by Title is selected. Only creating another note or restarting FSNotes sorts the list

**To Reproduce**
1. Create a new note
2. Give the note a name
4. See that the note does not sort

**Expected behavior**
Once a new note is created and named, the note should be sorted in the order required by the 'Sort by' preference.

**Actual behavior**
Notes do not sort automatically.

**Workaround**
Creating a new note or restarting FSnotes.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.6
 - FSNotes version: 4.6.2

**Comment by gingerbeardman** [comment]
Yes, sort should definitely happen after a rename.
