### ISSUE TITLE
Inline Mathjax expression are not being rendered

### ISSUE THREAD

**Issue by juanfcocontreras** [glushchenko/fsnotes#984]
**Describe the bug**
Inline Mathjax expressions are not being rendered

**To Reproduce**
1. Input the following text:

When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

2. Turn on 'Preview Mathjax'
3. Preview note

**Expected behavior**
Inline and display-mode expressions rendered with Mathjax.

**Actual behavior**
Only display-mode expressions are actually redered.

**Workaround**
Insert (($ and $)) to get inline mode.

**Supporting Files**
Screenshot of the issue:
<img width="500" alt="Captura de pantalla 2020-09-24 a las 10 04 45" src="https://user-images.githubusercontent.com/4047415/94118134-62198d00-fe4d-11ea-96a0-dc1e256dd719.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.6
 - FSNotes version: 4.6.2

**Additional context**

**Comment by glushchenko** [comment]
This feature is disabled. Slash is a common symbol, so no, not a bug.

**Comment by juanfcocontreras** [comment]
Ok, I have added how to get inline mode in the workaround section. I think it may help other people.
