### ISSUE TITLE
[Question] Is there migration Tags from older version to current

### ISSUE THREAD

**Issue by griffin-stewie** [glushchenko/fsnotes#985]
I used Tags feature on older version which has a UI to input tag name.
Today I updated latest FSNotes for macOS and then all tags are gone.
Is there a way to salvage all tags?

**Comment by gingerbeardman** [comment]
Are the tags on the files in Finder?

**Comment by griffin-stewie** [comment]
I downgraded [v3.9.1](https://github.com/glushchenko/fsnotes/tree/3.9.1) FSNotes then all tags are reappeared.

**Comment by gingerbeardman** [comment]
@griffin-stewie that's great and gives us something to go on.

I think there will need to be a command, perhaps manual/user-invoked rather than automatic, to migrate all tags (macOS Finder) from the old way to the new way (as markup).

**Comment by griffin-stewie** [comment]
Oh I see. I was wondering how FSNotes handles tags without any database or any metadata block. That was Finder tags.
Personally I prefer Finder tags rather than markup because I can copy and paste to other services. 

I look forward you to make solution to migrate all tags. Thank you!

**Comment by glushchenko** [comment]
Hi, @griffin-stewie!

Old style tags removed completely from FSNotes 4+. Metadata is not reliable data storage. iCloud can miss it on sync etc. 

I am not planning to do a migration for 1 user. Better spend time on something more worthwhile.

**Comment by griffin-stewie** [comment]
Hi, @glushchenko 
I understand what you said. I would write a migration tool for me when I have a spare time.
@gingerbeardman, you helped me a lot thank you.

**Comment by gingerbeardman** [comment]
Migration ideas...

using macOS buit-in tools
1. list all tags `/usr/bin/mdfind -0 "(kMDItemUserTags == '*')" |xargs -0 mdls -name kMDItemUserTags |grep '^    ' |cut -c5- |cut -d , -f 1 |sort -u`
1. find notes with tag `mdfind 'kMDItemUserTags=Music' -onlyin /path/to/folder`
1. append text tag to end of file `echo "#Music" >> $file`
1. optionally remove tags from files `sudo xattr -d com.apple.metadata:_kMDItemUserTags "$file"; sudo xattr -d com.apple.FinderInfo "$file";`

using an external tool
1. https://github.com/jdberry/tag/

**Comment by griffin-stewie** [comment]
@gingerbeardman 
Thank you. I'll give it a try.

**Comment by gingerbeardman** [comment]
Let us know how you get on!
