### ISSUE TITLE
Syntax highlighting of backtics in fenced code blocks

### ISSUE THREAD

**Issue by saf-dmitry** [glushchenko/fsnotes#987]
**Describe your feature request**

I would suggest highlighting backtics and language specifier in fenced code blocks using "dimmed" color, much like it is already done for backtics marking inline verbatim text:

![Screenshot 2020-10-06 at 13 38 21](https://user-images.githubusercontent.com/30050534/95197387-d0f5cf00-07d9-11eb-94e9-4c505ed6853f.png)

**Comment by glushchenko** [comment]
Thanks, implemented 😎

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.1/FSNotes_4.7.1.zip
