### ISSUE TITLE
Sharing in droplr.com freezes - bug

### ISSUE THREAD

**Issue by almeco** [glushchenko/fsnotes#990]
Hello,
When I try to use sharing in droplr.com loading just freezes and do nothing - 
![image](https://user-images.githubusercontent.com/6984839/96014345-911c9080-0e46-11eb-96ee-5d2ddf6de01c.png)
![image](https://user-images.githubusercontent.com/6984839/96014462-b4474000-0e46-11eb-963f-b6a7d169bcef.png)

**Comment by gingerbeardman** [comment]
droplr is expecting a screenshot, right?

**Comment by gingerbeardman** [comment]
@almeco but droplr is only for sharing screenshots and videos?

**Comment by almeco** [comment]
Not only. Text too

**Comment by gingerbeardman** [comment]
Can you please share a droplr link of text shared from another app? Thanks

**Comment by gingerbeardman** [comment]
Interestingly I have written some share menus myself (Twiiter, Facebook, Clipboard) and they also do not work with FSNotes. https://github.com/bartdorsey/sharegap

Perhaps some difference between what FSNotes sends and what the share menus expect?

**Comment by almeco** [comment]
I tried with Bear app and quiver and it looks like we have same problem there. Perhaps I should contact droplr first

**Comment by glushchenko** [comment]
Droplr sharing not working for me in Catalina. But files url was added in share extension, now you can upload files. This can be helpful.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.2beta1/FSNotes_4.7.2.zip
