### ISSUE TITLE
Disable the automatic addition of the first line to the note from the title

### ISSUE THREAD

**Issue by juanfcocontreras** [glushchenko/fsnotes#991]
**Describe your feature request**
Every time I create a note from the search bar, the title I enter is automatically added as the first line in the note. I would like to know if I can disable this option in some way.

**Additional context**
MacOS. I have disabled the option to show the first line as the note title.

**Comment by glushchenko** [comment]
Preferences -> Files naming -> UUID

**Comment by juanfcocontreras** [comment]
I would also like to be able to keep the option of using file names instead of UUID.

**Comment by glushchenko** [comment]
This mode works like in nvAlt, if you are press enter in search box, note will be created with typed name.

**Comment by juanfcocontreras** [comment]
Yes, but the title is for the file name, but it is not automatically inserted as the first line in the note. At least, when migrating from nvALT to FSNotes, I don't have in any of my previous notes the title in the first line of any of them, only in the file name. 

Please sorry if I am not explaining myself well, English is not my native language.

**Comment by gingerbeardman** [comment]
Maybe make a short screen recording or screenshot?

**Comment by juanfcocontreras** [comment]
Sure, here it is. I put some rectangles in order to hide my notes.

https://streamable.com/vgrtzi

**Comment by gingerbeardman** [comment]
@juanfcocontreras I can't reproduce this behaviour. i get the note named correctly, but with no heading title line or any contents at all.

What version FSNotes are you using?

**Comment by gingerbeardman** [comment]
Ah, OK, I have managed to reproduce. If I set `Files naming` to `Auto rename by title` then i get the heading contents as you have shown.

But, as @glushchenko said, if you set `Preferences > Files naming` to UUID you will not get this. Contrary to expectation, when you create the note it will actually have the filename as the title (not UUID!)

**Comment by glushchenko** [comment]
UUID is just file naming by default. We can rename it to Default for example ...

**Comment by glushchenko** [comment]
But we can add later Date and Time, who knows what is Default.

**Comment by juanfcocontreras** [comment]
So, if I am not mistaken, two issues have been identified by @gingerbeardman:

- the first, that even if UUID is set as an option for the file name, the title is still used
- the second, that if the title is used as a file name, it is entered automatically, and I think there should be in this case, an option to disable such automatic text

Am I wrong?

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/wiki/Advanced-settings

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.3/FSNotes_4.7.3.zip

Please remember that the best support for a project is positive feedback in the AppStore.

Best regards,
Oleksandr Hlushchenko
