### ISSUE TITLE
Setting Background Colour Crashes and Relaunches App

### ISSUE THREAD

**Issue by madranet** [glushchenko/fsnotes#992]
When trying to set a background colour for edit window, the task is made annoyingly difficult by the fact that, as soon as I click on the colour picker anywhere, FSNotes immediately crashes and relaunches [I see the icon disappear and then reappear in the main menu bar]. 

This puts FSNotes into the background and I have to bring it to the front again, to see the results of the colour change. 

![2020-10-17_21-17-49](https://user-images.githubusercontent.com/669658/96352818-5e7ccd00-10be-11eb-82f1-3a9afff6896b.png)

**Comment by glushchenko** [comment]
App not crashed, this is just restart.

**Comment by madranet** [comment]
OK. But the app restarts as soon as you click anywhere on the Colour Picker [which also closes the colour picker]. So you have to get the exact colour right first time, because you can't move the cursor about on the colour picker to fine tune it. 

This is not how choosing colour with the colour picker behaves anywhere else in OSX.

**Comment by glushchenko** [comment]
I really dont like this type of customisations, so think soon will be removed completely.
