### ISSUE TITLE
Copy selected text in search bar doesn't work

### ISSUE THREAD

**Issue by quinncomendant** [glushchenko/fsnotes#993]
**Describe the bug**
Copying text in the `Search and create` bar doesn't work. The text is not copied. 

**To Reproduce**
1. Enter the `Search and create` bar (`⌘`+`L`) and type some random text.
2. Try to copy the text by selecting it and using `⌘`+`C` or selecting Edit > Copy.
3. Check the clipboard; the text you copied isn't on the clipboard. 

**Expected behavior**
It should be possible to copy text from the search bar.

**Actual behavior**
Text is not copied. 

**Workaround**
No workaround.

**Supporting Files**
Please [see this screencast](https://media.giphy.com/media/hmt8hyd3CpdTKXxPsl/giphy.mp4) where I demonstrate the problem.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.14.6
 - FSNotes version: 4.7.1

**Comment by glushchenko** [comment]
Thank you, fixed!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.2beta1/FSNotes_4.7.2.zip
