### ISSUE TITLE
Delete / Disable global shortcuts is not working

### ISSUE THREAD

**Issue by feigaoxyz** [glushchenko/fsnotes#994]
**Describe the bug**
I am trying to delete / disable the global shortcuts (i.e. search and save clipboard). But the app still response to the default keystrokes. And the app restore these shortcuts after re-launch (quit & open).

**To Reproduce**
1. Go to 'preference'
2. Delete "Search shortcut" and "Save clipboard shortcut"
3. Close app window
4. Press "⌃⌥⇧L" anywhere, the app window still pops up
5. Quit FSNotes app, and launch it again
6. In "Preference", both shortcuts reset to defaults

**Expected behavior**
After deleting the shortcuts, the app won't response to the shortcut keystrokes.
And the preference of shortcuts (including deletion of such) remains after app relaunch.

**Actual behavior**
The app still responses to the shortcuts even user deleted them.
The app restores the shortcuts after re-launch.

**Workaround**
NA

**Supporting Files**
NA

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7 (19H2)
 - FSNotes version: 4.7.1 (427)

**Additional context**
Installed by Homebrew.

**Comment by glushchenko** [comment]
Fixed, thanks.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.2beta1/FSNotes_4.7.2.zip
