### ISSUE TITLE
Jump to first occur in found note as within nvAlt

### ISSUE THREAD

**Issue by KreiDer** [glushchenko/fsnotes#995]
**Describe your feature request**
Jump to first occur in founded note as within nvAlt
What I expect:
1) Go to fsnote search bar with cmd+l
2) search any word
3) open found document
4) As result cursor will be placed to the firs occurrences of the word in the document as in nvAlt
![image](https://user-images.githubusercontent.com/14274525/96545746-a3b52080-12b1-11eb-890a-1f8e8d729c7a.png)

That would be handy to jump right to first searched word in the document
**Additional context**
I've no longer nvAlt user already as switched to fsnotes and it would be nice to have close behavior as in nvAlt once I open founded note.

**Comment by glushchenko** [comment]
Honestly i never hear about this option in nvALT. Current behaviour is saving and restoring last position, like in nvALT.

**Comment by KreiDer** [comment]
> Honestly i never hear about this option in nvALT. Current behaviour is saving and restoring last position, like in nvALT.
Could you pleas have a look at nvAlt behavior 
![nvAltbehavoir](https://user-images.githubusercontent.com/14274525/96872975-fe4ea800-147c-11eb-9549-bb874600fbd4.gif)

**Comment by glushchenko** [comment]
Thanks @KreiDer, feature has been implemented.

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.3/FSNotes_4.7.3.zip

Please remember that the best support for a project is positive feedback in the AppStore.
-
Best regards,
Oleksandr Hlushchenko

**Comment by spenat28** [comment]
@glushchenko this stopped working - and i have a LOT of text in my notes. Could you reopen this?
I have last version of FSNotes 5.3.4
