### ISSUE TITLE
Open link at cursor by cmd+Enter

### ISSUE THREAD

**Issue by KreiDer** [glushchenko/fsnotes#996]
**Describe your feature request**
As Keyboard centric app it would be handy to be able open link at cursor by Cmd+Enter shortcut and don't touch mouse

**Additional context**
macOS

**Comment by gingerbeardman** [comment]
I love this about TextMate, which also allows numeric pad enter to open the link. 

ps: careful confusing keys labelled Return/Enter.

**Comment by glushchenko** [comment]
⌘ - Return reserved for navigation already. What about ⌘ - O ?

**Comment by KreiDer** [comment]
> ⌘ - Return reserved for navigation already. What about ⌘ - O ?

This combination also fine

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.2beta1/FSNotes_4.7.2.zip
