### ISSUE TITLE
History Causes Lost Note

### ISSUE THREAD

**Issue by pdanford** [glushchenko/fsnotes#998]
**Describe the bug**
When selecting a note's previous version from History causes all current changes to be lost

**To Reproduce**
1. Create new note and add text
2. Save Revision (cmd-s)
3. Add more text to same note
4. Right click on note's list entry and select previously saved version

**Expected behavior**
A warning or an automatic save of current change should happen (e.g. git's warning "error: Your local changes to the following files would be overwritten by checkout").

**Actual behavior**
Any changes to note since last Save Revision are silently discarded.

**Workaround**
Try not to forget to cmd-s before looking at older revisions. 

**Supporting Files**

**Desktop (please complete the following information):**
OS: macOS
OS version: 10.15.7
FSNotes version: 4.7.1

**Additional context**

**Comment by glushchenko** [comment]
Hi @pdanford, auto rename by title is enabled?

**Comment by glushchenko** [comment]
If you rename file back, all revisions come back.

**Comment by pdanford** [comment]
Hello! No, "Files naming" is set to UUID and "First line as title" is unchecked. The revisions listed in history do not disappear, it's any changes/edits to the current note you've made since the last cmd-s save revision.

**Comment by glushchenko** [comment]
Sorry but no, working fine for me. May be Repository path not writable in your environment?

**Comment by pdanford** [comment]
Hi. I'm not sure we are talking about the same thing. Would you mind posting what you did to test to see if they match my "To Reproduce" section? I ask this because I agree that actually getting previous history revisions of a note is working as it should. What is a problem is all changes *to the actual text* are lost for the *current note* when you switch to a previous revision of that same note. That is, there is no way to go back to what you were working on prior to looking at some revision in history. This is equivalent to checking something out in git with existing modified files - and git just silently throwing away the local changes without warning - which it does not.

**Comment by glushchenko** [comment]
@pdanford thanks. Understand now.

**Comment by pdanford** [comment]
Thank you for your responsiveness and great software!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.3/FSNotes_4.7.3.zip

Please remember that the best support for a project is positive feedback in the AppStore.

Best regards,
Oleksandr Hlushchenko
