### ISSUE TITLE
Can't use option+` as shortcut to open fsnotes

### ISSUE THREAD

**Issue by KreiDer** [glushchenko/fsnotes#999]
**Describe the bug**
Can't use option+key as Search shortcut to open fsnotes

**To Reproduce**
1. Go to Preferences
2. Try to setup Search shortcut with "Option + `" for example
3. See that we can't set that key combination

**Expected behavior**
User should be able to set up Option + ` key as Search shortcut

**Actual behavior**
User not able to set up Option + ` key as 

**Desktop (please complete the following information):**
 - OS: macOS 
 - FSNotes version: 4.7.1

**Additional context**
NvAlt allow user to setup Option + `

**Comment by glushchenko** [comment]
Implemented

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.7.3/FSNotes_4.7.3.zip

Please remember that the best support for a project is positive feedback in the AppStore.

Best regards,
Oleksandr Hlushchenko
